### ISSUE TITLE
Incorrect error message when using int param on component deactivate method

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1012]
Section 112.5.15 of Compendium (R5) states that a component deactivate method may take an integer parameter, which contains the deactivation reason.

Bnd throws an error message when this is used:

    Deactivate method for org.example.osgi.exchange.prices.RandomPriceFeed does not have an acceptable prototype, only Map, ComponentContext, or BundleContext is allowed. Found: (I)V

**Comment by bjhargrave** [comment]
Which `@Deactivate` annotation are you using?

**Comment by bjhargrave** [comment]
This must be the bnd Deactivate annotation. The DS spec annotation already tests for int.

Furthermore, the bnd annotation support life cycle methods is broken in other places. Other parts of the code don't handle int (like selecting the best of overloaded methods). It also does not handle the new component property types which can be passed to life cycle methods in DS 1.3.

I suggest you migrate to the DS spec annotations as I think the plan is to deprecate the bnd annotations.

**Comment by njbartlett** [comment]
Thanks BJ you're right, I didn't even think about that. Closing.
