### ISSUE TITLE
Include newer Felix resolver

### ISSUE THREAD

**Issue by jest** [bndtools/bnd#1023]
I'm experiencing OOM errors in resolution process using BndTools, even when I have like 20 bundles or so to resolve. Looks like [this][1] bug in Felix resolver.  [That][2] is also a slowdown in resolution.

The bugs were fixed in 1.2, and resolver is currently at 1.4. Please update the lib.

[1]: https://issues.apache.org/jira/browse/FELIX-4656
[2]: https://issues.apache.org/jira/browse/FELIX-4762

**Comment by bjhargrave** [comment]
I'll look at updating the resolver to 1.4.

**Comment by jest** [comment]
Thanks
