### ISSUE TITLE
Include-Resource inserts an extra directory when using assignment mode on a file inside a jar

### ISSUE THREAD

**Issue by seanrohead** [bndtools/bnd#1027]
I have the following header in a manifest file:

Include-Resource: \
 win32/KeyViewFilterLibsWindows32-10.23.0.0.jar=KeyViewFilterLibsWindows32-10.23.0.0.jar,\
 win32/KeyViewFilter.dll=@KeyViewFilterLibsWindows32-10.23.0.0.jar!/KeyViewFilter.dll

The resulting jar should have a win32 directory with the following files:
    KeyViewFilter.dll
    KeyViewFilterLibsWindows32-10.23.0.0.jar

Instead, KeyViewFilter.dll is placed inside a *folder* which is also named KeyViewFilter.dll.

I am able to workaround this by modifying the Bundle-NativeCode header to include the extra folder:
Bundle-NativeCode: win32/KeyViewFilter.dll/KeyViewFilter.dll; osname=win32; processor=x86
                                           ^^^^^^^^^^^^^^
                                           This extra folder should not be here

**Comment by seanrohead** [comment]
I found that changing to assign to a folder path instead of a file path works. It still seems like a bug since it is inconsistent with the assignment in the line above, but maybe that's how it was intended to work?

Include-Resource: \
win32/KeyViewFilterLibsWindows32-10.23.0.0.jar=KeyViewFilterLibsWindows32-10.23.0.0.jar,\
win32=@KeyViewFilterLibsWindows32-10.23.0.0.jar!/KeyViewFilter.dll

**Comment by timothyjward** [comment]
This is working correctly. In the first case it's a simple assignment, but in the latter the @ symbol means that you're using an "inline" instruction. 

Assignment instructions take a single file and put it at the named location. Inline instructions map a group of files into a directory. In this case your "group" matches a single file.

See http://bnd.bndtools.org/chapters/125-tour-features.html#include-resources and http://bnd.bndtools.org/heads/include_resource.html for documentation.
