### ISSUE TITLE
assorted R6 metatype problems

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#1030]
I'm on latest bndtools.

I've converted a project from bnd annotations to (R6) DS annotations.

Now the /OSGI-INF/metatype is no longer generated.

I've selected 'DS 1.2 Annotations' the bndtool bnd file editor, which replaces 'Service-Component: *' with '-dsannotations: *'.
I've also converted the classes to use the R6 metatype aanotations, see patch below.

Rather critical since it all falls over now.

```
diff --git a/nl.mindef.ahr.ahrwand.egress/bnd.bnd b/nl.mindef.ahr.ahrwand.egress/bnd.bnd
index ab7531a..e51c93f 100644
--- a/nl.mindef.ahr.ahrwand.egress/bnd.bnd
+++ b/nl.mindef.ahr.ahrwand.egress/bnd.bnd
@@ -2,12 +2,10 @@ Bundle-Name:AHR WAND Egress
 Bundle-Version:1.0.0.${tstamp}
 Private-Package: \
 	nl.mindef.ahr.ahrwand.egress
-Service-Component: \
-	*
+-dsannotations: *
 -buildpath: \
 	osgi.core;version=${osgi.core.version},\
 	osgi.cmpn;version=${osgi.cmpn.version},\
-	biz.aQute.bnd.annotation,\
 	nl.mindef.ahr.common.types;version=latest,\
 	nl.mindef.ahr.gateway.reporter.api;version=latest,\
 	nl.mindef.ahr.util;version=project
@@ -15,5 +13,4 @@ Service-Component: \
 	${junit},\
 	nl.mindef.ahr.testmocks;version=project
 Conditional-Package: \
-	nl.mindef.ahr.util.trigger,\
-	aQute.bnd.annotation.metatype
\ No newline at end of file
+	nl.mindef.ahr.util.trigger
\ No newline at end of file
diff --git a/nl.mindef.ahr.ahrwand.egress/src/nl/mindef/ahr/ahrwand/egress/AhrWandEgress.java b/nl.mindef.ahr.ahrwand.egress/src/nl/mindef/ahr/ahrwand/egress/AhrWandEgress.java
index b7bfa88..8f52a06 100644
--- a/nl.mindef.ahr.ahrwand.egress/src/nl/mindef/ahr/ahrwand/egress/AhrWandEgress.java
+++ b/nl.mindef.ahr.ahrwand.egress/src/nl/mindef/ahr/ahrwand/egress/AhrWandEgress.java
@@ -14,21 +14,22 @@ import java.util.concurrent.atomic.AtomicLong;
 import java.util.regex.Matcher;
 import java.util.regex.Pattern;
 
+import org.osgi.service.component.annotations.Activate;
+import org.osgi.service.component.annotations.Component;
+import org.osgi.service.component.annotations.Deactivate;
+import org.osgi.service.component.annotations.Modified;
+import org.osgi.service.component.annotations.Reference;
 import org.osgi.service.log.LogService;
+import org.osgi.service.metatype.annotations.Designate;
 
-import aQute.bnd.annotation.component.Activate;
-import aQute.bnd.annotation.component.Component;
-import aQute.bnd.annotation.component.Deactivate;
-import aQute.bnd.annotation.component.Modified;
-import aQute.bnd.annotation.component.Reference;
-import aQute.bnd.annotation.metatype.Configurable;
 import nl.mindef.ahr.common.types.Bandwidth;
 import nl.mindef.ahr.gateway.reporter.api.Gateway;
 import nl.mindef.ahr.gateway.reporter.api.GatewayReporter;
 import nl.mindef.ahr.util.trigger.TriggerTarget;
 import nl.mindef.ahr.util.trigger.TriggerTask;
 
-@Component(designate = Config.class, provide = {})
+@Component(service = {})
+@Designate(ocd = Config.class)
 public class AhrWandEgress implements TriggerTarget {
   /*
    * Services
@@ -53,9 +54,9 @@ public class AhrWandEgress implements TriggerTarget {
    */
 
   @Activate
-  void activate(final Map<String, Object> props) {
+  void activate(final Config config) {
     synchronized (this.configContainerLock) {
-      this.setupConfig(props);
+      this.config = config;
     }
 
     this.timer = new Timer(this.getClass().getSimpleName());
@@ -82,20 +83,12 @@ public class AhrWandEgress implements TriggerTarget {
   private final Object configContainerLock = new Object();
   private Config       config              = null;
 
-  /* MUST be called in a synchronized (configContainerLock) block */
-  private Config setupConfig(final Map<String, Object> props) {
-    final Config prevConfig = this.config;
-    this.config = Configurable.createConfigurable(Config.class, props);
-    return prevConfig;
-  }
-
   @Modified
-  void modified(final Map<String, Object> props) {
+  void modified(final Config config) {
     Config previousConfig;
-    Config config;
     synchronized (this.configContainerLock) {
-      previousConfig = this.setupConfig(props);
-      config = this.config;
+      previousConfig = this.config;
+      this.config = config;
     }
 
     if (!previousConfig.ahrwandEgressFile().equals(config.ahrwandEgressFile())) {
diff --git a/nl.mindef.ahr.ahrwand.egress/src/nl/mindef/ahr/ahrwand/egress/Config.java b/nl.mindef.ahr.ahrwand.egress/src/nl/mindef/ahr/ahrwand/egress/Config.java
index 92958c6..5e49a9a 100644
--- a/nl.mindef.ahr.ahrwand.egress/src/nl/mindef/ahr/ahrwand/egress/Config.java
+++ b/nl.mindef.ahr.ahrwand.egress/src/nl/mindef/ahr/ahrwand/egress/Config.java
@@ -1,21 +1,22 @@
 package nl.mindef.ahr.ahrwand.egress;
 
-import aQute.bnd.annotation.metatype.Meta;
+import org.osgi.service.metatype.annotations.AttributeDefinition;
+import org.osgi.service.metatype.annotations.ObjectClassDefinition;
 
-@Meta.OCD(name = "AHR WAND Egress", description = "Configuration for the AHR WAND Egress service")
-public interface Config {
-  static final String DEFAULT_EGRESS_FILE         = "/var/run/ahrplefe-sgw-egress.conf";
+@ObjectClassDefinition(name = "AHR WAND Egress", description = "Configuration for the AHR WAND Egress service")
+@interface Config {
+  static final String DEFAULT_EGRESS_FILE = "/var/run/ahrplefe-sgw-egress.conf";
   static final String DEFAULT_QUERY_INTERVAL_MSEC = "1000";
 
   /*
    * Querier
    */
 
-  @Meta.AD(deflt = DEFAULT_EGRESS_FILE, required = false,
+  @AttributeDefinition(defaultValue = DEFAULT_EGRESS_FILE, required = false,
       description = "The AHR WAND Egress file (default = " + DEFAULT_EGRESS_FILE + ")")
   String ahrwandEgressFile();
 
-  @Meta.AD(min = "1000", deflt = DEFAULT_QUERY_INTERVAL_MSEC, required = false,
+  @AttributeDefinition(min = "1000", defaultValue = DEFAULT_QUERY_INTERVAL_MSEC, required = false,
       description = "The interval on which to query the network (msec) (default = " + DEFAULT_QUERY_INTERVAL_MSEC + ")")
   int queryIntervalMilliSeconds();
 }
\ No newline at end of file
```

**Comment by djencks** [comment]
I don't quite understand how you have stuff set up, perhaps because you are working within bndtools?  but I think you are missing the -metatypeannotations: <comma-separated list of metatype-annotated classes> in your bnd instructions.  Perhaps you should try selecting ds 1.3 as ds 1.2 has no configure-by-annotations support?

**Comment by fhuberts** [comment]
So what are the concrete things to have then?

**Comment by fhuberts** [comment]
I've added ```-metatypeannotations: *``` and that seems to convince bnd to generate the metatype files.

This is - to me - a gaping hole in bndtools.
How the heck should you know that you need this?

Anyway, thanks David

**Comment by fhuberts** [comment]
Previously - for bnd annotations - you didn't need this, it was automatic

**Comment by djencks** [comment]
Well, now it works the same as needing -dsannotations: <list of classes> to scan for ds annotations.  I'm not responsible for the bnd annotation behavior.

**Comment by bjhargrave** [comment]
OSGi Metatype annotations support is new for bnd 3.0. So we need to highlight in the release notes that you need to specify `-metatypeannotations` instructions.

**Comment by fhuberts** [comment]
Or just add a selection box in bndtools in the bnd file editor. Just like for DS annotations

**Comment by fhuberts** [comment]
Ok, now I have the problem that I get *empty* Config instances injected.

When I look in the bundles I see that the generated metatype are significantly different.

pre-R6-conversion:
```
<?xml version='1.0' encoding='UTF-8'?>
<metatype:MetaData xmlns:metatype="http://www.osgi.org/xmlns/metatype/v1.1.0" localization="nl.mindef.ahr.ahrwand.egress.Config">
  <OCD name="AHR WAND Egress" id="nl.mindef.ahr.ahrwand.egress.AhrWandEgress" description="Configuration for the AHR WAND Egress service">
    <AD name="Ahrwand egress file" id="ahrwandEgressFile" cardinality="0" required="false" default="/var/run/ahrplefe-sgw-egress.conf" type="String" description="The AHR WAND Egress file (default = /var/run/ahrplefe-sgw-egress.conf)"/>
    <AD name="Query interval milli seconds" id="queryIntervalMilliSeconds" cardinality="0" required="false" default="1000" type="Integer" min="1000" description="The interval on which to query the network (msec) (default = 1000)"/>
  </OCD>
  <Designate pid="nl.mindef.ahr.ahrwand.egress.AhrWandEgress">
    <Object ocdref="nl.mindef.ahr.ahrwand.egress.AhrWandEgress"/>
  </Designate>
</metatype:MetaData>
```

post-R6 conversion:
```
<?xml version="1.0" encoding="UTF-8"?>
<metatype:MetaData xmlns:metatype="http://www.osgi.org/xmlns/metatype/v1.3.0" localization="OSGI-INF/l10n/nl.mindef.ahr.ahrwand.egress.Config">
  <OCD id="nl.mindef.ahr.ahrwand.egress.Config" name="AHR WAND Egress" description="Configuration for the AHR WAND Egress service">
    <AD id="ahrwandEgressFile" type="String" required="false" name="Ahrwand egress file" description="The AHR WAND Egress file (default = /var/run/ahrplefe-sgw-egress.conf)" default="/var/run/ahrplefe-sgw-egress.conf"/>
    <AD id="queryIntervalMilliSeconds" type="Integer" required="false" name="Query interval milli seconds" description="The interval on which to query the network (msec) (default = 1000)" min="1000" default="1000"/>
  </OCD>
  <Designate pid="nl.mindef.ahr.ahrwand.egress.AhrWandEgress">
    <Object ocdref="nl.mindef.ahr.ahrwand.egress.Config"/>
  </Designate>
</metatype:MetaData>
```

Is there another thing that I'm missing?

**Comment by fhuberts** [comment]
@djencks Any ideas?

**Comment by bjhargrave** [comment]
The injected config object is based upon the component properties which come from the component description and the configuration. This is not directly related to the metatype resource. What are the component properties for the component?

**Comment by fhuberts** [comment]
This is the Config class:
```
@ObjectClassDefinition(name = "AHR WAND Egress", description = "Configuration for the AHR WAND Egress service")
@interface Config {
  static final String DEFAULT_EGRESS_FILE = "/var/run/ahrplefe-sgw-egress.conf";
  static final String DEFAULT_QUERY_INTERVAL_MSEC = "1000";

  /*
   * Querier
   */

  @AttributeDefinition(defaultValue = DEFAULT_EGRESS_FILE, required = false,
      description = "The AHR WAND Egress file (default = " + DEFAULT_EGRESS_FILE + ")")
  String ahrwandEgressFile();

  @AttributeDefinition(min = "1000", defaultValue = DEFAULT_QUERY_INTERVAL_MSEC, required = false,
      description = "The interval on which to query the network (msec) (default = " + DEFAULT_QUERY_INTERVAL_MSEC + ")")
  int queryIntervalMilliSeconds();
}
```

So what is injected is **not** based on this class?

**Comment by fhuberts** [comment]
```
@Component(service = {})
@Designate(ocd = Config.class)
public class AhrWandEgress implements TriggerTarget {
  ...
}
```

**Comment by bjhargrave** [comment]
The component's properties are used to provide the data. So when you call the config object, the returned values are from the component's properties. Since you are getting no values, the component's properties appear to be empty. What does the component xml for the component look like?

**Comment by fhuberts** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.3.0" name="nl.mindef.ahr.ahrwand.egress.AhrWandEgress" activate="activate" deactivate="deactivate" modified="modified">
  <implementation class="nl.mindef.ahr.ahrwand.egress.AhrWandEgress"/>
  <reference name="GatewayReporter" interface="nl.mindef.ahr.gateway.reporter.api.GatewayReporter" bind="setGatewayReporter"/>
  <reference name="Logger" interface="org.osgi.service.log.LogService" bind="setLogger"/>
</scr:component>
```

**Comment by bjhargrave** [comment]
Something is odd then since the default values from the config type should appears as <property> elements in the component xml. Can you prepare a small example of the problem we can look at?

**Comment by fhuberts** [comment]
will try

**Comment by fhuberts** [comment]
See https://github.com/fhuberts/bndIssue1030

**Comment by bjhargrave** [comment]
Move the default value from the @AttributeDefinition annotation to the
default keyword on the annotated element. DS annotation processing does not
know about metatype annotations but does know about the default keyword.

We should probably add a warning from in bnd for this situation.

On Sat, Aug 15, 2015 at 06:35 Ferry Huberts <notifications@github.com>
wrote:

> See https://github.com/fhuberts/bndIssue1030
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bnd/issues/1030#issuecomment-131333658>.
>
-- 
-- 
BJ

**Comment by fhuberts** [comment]
What do you mean?
Can you push a commit to my example repo?
I've made you a collaborator there

**Comment by fhuberts** [comment]
Ah I've got it.
Like this
```
-  String ahrwandEgressFile();
+  String ahrwandEgressFile() default DEFAULT_EGRESS_FILE;
```

**Comment by fhuberts** [comment]
This is a bit unhandy.
And confusing.
What is the ```defaultValue``` attribute on the ```@AttributeDefinition``` for then?

Do I keep the default on the @AD or just remove it?
Confusing.

Previoulsy bnd just picked up de default from the annotation.

**Comment by bjhargrave** [comment]
> Ah I've got it.
> Like this
> 
> -  String ahrwandEgressFile();
> +  String ahrwandEgressFile() default DEFAULT_EGRESS_FILE;

Yes. bnd has separate annotation processors for the DS annotations and the Metatype annotations. The DS annotations processor knows nothing about metatype annotations so the defaultValue in AttributeDefinition does not end up in the component xml as <property> elements. The DS annotations processor does understand the configuration property types and the default keyword so those default values do result in <property> elements in the component xml.

The Metatype annotations processor understands the defaultValue in AttributeDefinition as well as the default keyword in annotations. So if the type annotated ObjectClassDefinition is an annotation, it is best to use the default keyword since it is understood by the DS annotations processor and the Metatype annotations processor. The defaultValue in AttributeDefinition is best used only for interfaces which (1) don't have a default keyword and (2) cannot be used as configuration property types in DS.

You are on the bleeding edge of converting from the bnd annotations to the new OSGi DS and Metatype annotations. It would be really great if you could collect up these "gotchas" so we can post it as a wiki entry (referenced from the release notes) for others to come. Would you be able to do that? Thanks.

**Comment by fhuberts** [comment]
ok thanks a lot for the help.
I now have an entire application converted to R6.

I find the duplicated defaults cumbersome but can live with it.

**Comment by djencks** [comment]
I think the duplication is kind of annoying too but actually does some good if your component is configuration optional in that the metatype suggests a value that your component will get even without a configuration.

I think configuration-optional an anti-pattern so I expect to only use the ad default-value element and not the annotation default value.

I’m glad to know someones project still works with the R6 stuff :-)

thanks!
david jencks

**Comment by fhuberts** [comment]
@djencks 
>  I think configuration-optional an anti-pattern so I expect to only use the ad default-value element and not the annotation default value.

If you do this then you'll get the zeroed-out config instances injected, just like I did.
You really need to set the default on the field.

I would prefer bnd to be smarter about this and just propagate the ```defaultValue``` of the AD into the component's xml. **Or** the other way around (but I prefer it being in the AD). Just as long as it's not duplicated.

**Comment by bjhargrave** [comment]
> If you do this then you'll get the zeroed-out config instances injected, just like I did.

I think David's point was that the component should require a configuration in Config Admin. Then it does not matter what properties are in the component xml since the component will have configuration properties in a Config Admin configuration.

> Just as long as it's not duplicated.

I am not sure why you think you need to duplicate the configuration. Just put it on the default keyword. Both DS annotation processing and Metatype annotation processing will then use that value for the default.

**Comment by djencks** [comment]
I don’t understand.

configuration-policy ignore:  not sure why you are using a annotation for configuration, since you’ve said the component isn’t configurable… but use the annotation element defaults.

configuration-policy optional: anti pattern, don’t do it.  If you insist on doing it anyway, use the annotation element defaults so without a config you’ll get the default values and the metatype will have a clue to show the user what the default is.

configuration-policy require: use AD default value element to get the default into the metatype and not the component.xml.  In the metatype and config admin setup I use (proprietary, unfortunately), any configuration created is going to have the metatype applied, including any default values specified there.  So these get to the component in the configuration…. the first it sees of the config annotation is from merging the configuration with the component.xml properties.

So how do you get zeroed-out instances injected?

thanks
david jencks

**Comment by fhuberts** [comment]
You're both right, I read too fast

**Comment by fhuberts** [comment]
On 15/08/15 16:54, BJ Hargrave wrote:
> You are on the bleeding edge of converting from the bnd annotations to 
> the new OSGi DS and Metatype annotations. It would be really great if 
> you could collect up these "gotchas" so we can post it as a wiki entry 
> (referenced from the release notes) for others to come. Would you be 
> able to do that? Thanks.
http://pelagic-open-source.blogspot.nl/2015/08/convert-to-osgi-r6.html
