### ISSUE TITLE
R6: using abstract class for component: component XML no longer generated correctly

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#1032]
I have a project with several components.
Each component is almost the same and has all its OSGi lifecycle code in an abstract (common) class. Each component only implements a few abstract methods.
The Config class is also common.

Example:
```
package nl.mindef.ahr.olsrd.txtinfo.plugin.gateway;

import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import java.util.regex.Pattern;

import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.ConfigurationPolicy;
import org.osgi.service.metatype.annotations.Designate;

import nl.mindef.ahr.nmea.sender.api.NmeaUtils;
import nl.mindef.ahr.olsrd.txtinfo.api.OlsrdTxtInfoPlugin;
import nl.mindef.ahr.olsrd.txtinfo.plugin.common.AbstractOlsrdTxtinfoPlugin;
import nl.mindef.ahr.olsrd.txtinfo.plugin.common.Config;

@Component(configurationPolicy = ConfigurationPolicy.REQUIRE, service = {
    OlsrdTxtInfoPlugin.class
})
@Designate(ocd = Config.class)
public class OlsrdTxtinfoPluginGateway extends AbstractOlsrdTxtinfoPlugin {
  static final String COMMAND = "/gateway";

  private static final Pattern TABLE_HEADER = Pattern.compile("^\\s*([Tt]able:|[Ss]tatus)\\s+.+$");
  private static final Pattern COMMENT      = Pattern.compile("^\\s*(|#.*)$");

  @Override
  public List<String> handleOutput(final List<String> output) {
    assert(output != null);

    final List<String> result = new LinkedList<>();
    for (final String line : output) {
      if (TABLE_HEADER.matcher(line).matches()) {
        continue;
      }

      if (COMMENT.matcher(line).matches()) {
        continue;
      }

      result.add(NmeaUtils.toNmeaSentenceContents(Arrays.asList(line.trim().split("\\s+"))));
    }

    return result;
  }

  @Override
  protected String getCommand() {
    return COMMAND;
  }
}
```

With the bnd annotations this worked just fine.
With the OSGi R6 conversion this no longer works correctly.

Generated:
```
<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" name="nl.mindef.ahr.olsrd.txtinfo.plugin.gateway.OlsrdTxtinfoPluginGateway" configuration-policy="require">
  <implementation class="nl.mindef.ahr.olsrd.txtinfo.plugin.gateway.OlsrdTxtinfoPluginGateway"/>
  <service>
    <provide interface="nl.mindef.ahr.olsrd.txtinfo.api.OlsrdTxtInfoPlugin"/>
  </service>
</scr:component>
```

When I copy/paste the abstract class contents into the component itself and adjust to make it compile, then the following is generated, which is correct.
```
<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.3.0" name="nl.mindef.ahr.olsrd.txtinfo.plugin.gateway.OlsrdTxtinfoPluginGateway" configuration-policy="require" activate="activate" modified="modified">
  <implementation class="nl.mindef.ahr.olsrd.txtinfo.plugin.gateway.OlsrdTxtinfoPluginGateway"/>
  <service>
    <provide interface="nl.mindef.ahr.olsrd.txtinfo.api.OlsrdTxtInfoPlugin"/>
  </service>
  <reference name="Logger" interface="org.osgi.service.log.LogService" bind="setLogger"/>
  <property name="queryIntervalMilliSeconds" type="Integer" value="5000"/>
  <property name="sendIntervalMilliSeconds" type="Integer" value="5000"/>
  <property name="address" type="String" value="0.0.0.0"/>
  <property name="port" type="Integer" value="0"/>
  <property name="ttl" type="Integer" value="-1"/>
</scr:component>
```

Note that the metatype xml is generated correctly.

**Comment by fhuberts** [comment]
When I put the OSGi lifecycle methods in the component itself and just call into the (abstract) parent, then it works ok

**Comment by djencks** [comment]
did you try the instruction 
-dsannotations-options=inherit
?

The options are:
inherit: process superclass ds annotations when the superclass is available

felixExtensions: allow lifecycle and event methods to return a service properties map

extender: add the extender requirement to the manifest even if the DS version is < 1.3

Can you think of any other options we need?

thanks
david jencks

**Comment by fhuberts** [comment]
> did you try the instruction
> -dsannotations-options=inherit
> ?

No I did (ofcourse) not.
Another thing you should know, and can't find in docs, sigh.
I'll try it in a minute.

**Comment by fhuberts** [comment]
BTW, why is inherit not the default?

**Comment by fhuberts** [comment]
```-dsannotations-options=inherit``` should have been the default: not using it break behaviour between
the bnd annotations and the OSGi R6 annotations.

**Comment by djencks** [comment]
The r5 annotations also required you to specify this although in the form

-dsannoations-inherit=true (which still works, but please use the options flag)

so making inherit the default would have been a breaking change.

Peter has some reason I don’t understand why you shouldn’t use inheritance at all.  I think if all the classes involved are in the same bundle there are no problems whatsoever and even if they aren’t it’s no more dangerous than using service-component headers or for that matter writing the xml yourself.

david jencks

**Comment by fhuberts** [comment]
On 16/08/15 16:52, djencks wrote:
> Peter has some reason I don’t understand why you shouldn’t use 
> inheritance at all. I think if all the classes involved are in the 
> same bundle there are no problems whatsoever and even if they aren’t 
> it’s no more dangerous than using service-component headers or for 
> that matter writing the xml yourself.
>
Yeah I'm not convinced by that.
When the inherited properties are in the same bundle there is no problem 
at all.
And bnd can easily flag a warning when they are not in the same bundle 
to signal _potential_ problems.

**Comment by pkriens** [comment]
The spec is no-inheritance so that is why it is the default.
