### ISSUE TITLE
OSGi annotation processing default

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#1041]
In the bndtools call today, we agreed that the default for `-dsannotations` should be `*` and for `-metatypeannotations` should be `*`. So by default, bnd will process the OSGi DS and Metatype annotations.

@djencks Can you update the annotation processors to use * if these instructions are not set? We need to put this in for 3.0.

**Comment by njbartlett** [comment]
Hmm if I want to disable DS annotations for a particular project, would I have to write:

    -dsannotations: <<EMPTY>>

or

    -dsannotations: !*

?

**Comment by bjhargrave** [comment]
Or

-dsannotations:

On Fri, Aug 21, 2015 at 20:57 Neil Bartlett <notifications@github.com>
wrote:

> Hmm if I want to disable DS annotations for a particular project, would I
> have to write:
>
> -dsannotations: <<EMPTY>>
>
> or
>
> -dsannotations: !*
>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bnd/issues/1041#issuecomment-133620534>.
>
-- 
-- 
BJ
