### ISSUE TITLE
JunitXmlReport generates XML that cannot be opened in Eclipse JUnit view

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1045]
The test report generated by JunitXmlReport is in the "standard" junit format, except with the addition of a `<bundles>` element. When this element is present, it is not possible to double-click the XML report for display in the Eclipse JUnit view. However if you manually edit the file after generation and remove this element, Eclipse can open it.

Yes, Eclipse is being pretty stupid here. But I wonder if we can either:
a) optionally omit the `bundles` element;
b) generate it with a different XML namespace -- hopefully this will cause Eclipse to ignore it.

**Comment by njbartlett** [comment]
I have experimented with option (b) and it doesn't seem to help if I put `bundles` into a separate namespace.

Does any existing tool actually consume this data? If not, I would suggest generating it only as an XML comment.

**Comment by bjhargrave** [comment]
> omit the bundles element

I vote we simply cease to emit the bundles element.

In the alternate, we should emit the information as properties in the `<properties>` element: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd#L50. This is ignored by the Eclipse JUnit viewer: http://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/model/TestRunHandler.java#n135.

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bnd/commit/4f865bd36e8a30fd587c743f76526af0ba56c58c
