### ISSUE TITLE
aQute.launcher.Launcher should run on Java 1.4 but is built for 1.6

### ISSUE THREAD

**Issue by kiffer580** [bndtools/bnd#1046]
The launcher is advertised as running on Java 1.4, but when I try to launch in a JavaME/CDC environment loading fails because the class file has version 1.50 instead of 1.48.  Has 1.4 support been dropped, or do I need to twiddle some knobs to get this to work?

Issue occurs with 2.5.0.DEV-20141220-123306-g1d7fa81 on Eclipse Luna.

**Comment by kiffer580** [comment]
Update: only version 1.4.0 of the launcher has the later class file version, 1.3.0 and 1.2.1 have class file version 1.48 (JDK 1.4) but still do not run on JavaME/CDC because they use java.util.regex.  So these versions also do not support OSGi Foundation Environment.

**Comment by bjhargrave** [comment]
We are currently building bnd 3.0 now (just made RC1 build). 2.5.0 was an early name for 3.0.

The launcher currently targets Java 1.6 now: https://github.com/bndtools/bnd/blob/master/biz.aQute.launcher/.settings/org.eclipse.jdt.core.prefs#L10. The launcher was updated from target Java 1.5 to target Java 1.6 for bnd 2.4: https://github.com/bndtools/bnd/commit/a8784ecb091b5fa89847482c021851a7a93711f7. History shows it was target Java 1.5 as far back as bnd 2.0: https://github.com/bndtools/bnd/commit/3c0f68ca5246deca8c680275b9113e01f3ee416d#diff-1d9dec11a7fd21b60fc4d4739b1581f1L12. So it must have been a _very_ long time ago that the launcher worked on Java 1.4.

**Comment by pkriens** [comment]
You an always put an old version of the launcher on -runpath

      -runpath: biz.aQute.launcher;version='[1.x,1.y)'

**Comment by kiffer580** [comment]
README should be updated, would have saved me a bit of time.

**Comment by bjhargrave** [comment]
Fixed! Thanks.
