### ISSUE TITLE
Missing -metatypeannotations: when selecting DS 1.2 annotations

### ISSUE THREAD

**Issue by marcdejonge** [bndtools/bnd#1049]
This is a bit confusing for me. I'm moving from the bnd annotations to the OSGi 6 annotations for DS. But when I selected the DS 1.2 annotations option in the first screen of the bnd.bnd editor, the metatype annotations weren't parsed. This is different from the bnd annotations where it simply worked at once.

I think it would be helpful if the -metatypeannotations are also added automatically.

**Comment by marcdejonge** [comment]
Wait, this seems to be discussed in issue #1030 also. I have the latest version, so still not fixed?

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/pull/1043. We will change the default for `-dsannotations` and `-metatypeannotations` to `*`. Just need some fixes in the PR before we merge.
