### ISSUE TITLE
Supplied Bundle-SymbolicName not trimmed

### ISSUE THREAD

**Issue by djencks** [bndtools/bnd#1055]
Starting with a bnd file with a terminal space such as:
Bundle-SymbolicName: foo.bar.mybundle <<<< note terminal space

the Bundle-SymbolicName in the generated manifest preserves this space, which is not a grammatical token.  I'm not sure where the file name for the assembled bundle comes from but in my ant-based build the filename also preserves this space.

I haven't looked into it but wonder if the QuotedTokenizer should always trim the returned tokens?

**Comment by pkriens** [comment]
I am not processing this header at all so that is why you see the space.

It should also not be a problem since the framework must strip it.
