### ISSUE TITLE
Resolver throws NPE if Run Requirements is empty list

### ISSUE THREAD

**Issue by seanbright** [bndtools/bnd#1060]
This manifests in Bndtools but the bug appears to be in bnd, so I am reporting it here.

Reproducing steps:
 1. Open bnd or bndrun file
 2. Click on 'Run' tab
 3. Remove everything from the Run Requirements list
 4. Click Resolve

This is with bndtools from cloudbees.

**Comment by bjhargrave** [comment]
Stacktrace?

**Comment by seanbright** [comment]
![image](https://cloud.githubusercontent.com/assets/114601/9548200/22fe8bb6-4d6d-11e5-9a6f-e277ea0fd43c.png)

That's it. Nothing logged to Eclipse's Error Log.

**Comment by bjhargrave** [comment]
Not clear it is a bnd (vs. bndtools) bug without a stacktrace, but this should be looked at.

**Comment by seanbright** [comment]
In my own testing, I traced it back to AbstractResolveContext.getInputResource() returning null, but I don't know how helpful that is.

**Comment by seanbright** [comment]
I believe https://github.com/bndtools/bndtools/commit/24c18f0fc02fc10cbb79b130dca6e28553fd5243 made the stack trace in the resolution panel less useful.

**Comment by bjhargrave** [comment]
> I believe bndtools/bndtools@24c18f0 made the stack trace in the resolution panel less useful.

I don't think that makes a difference since the exception is not a `ResolutionException`. I suspect the caller of `formatFailureStatus` needs to set the `exceptions` argument to true to get the stack trace.

**Comment by seanbright** [comment]
So the resolver calls ResolverContext.getMandatoryResources() (implemented by BndResolverContext) which does this:

https://github.com/bndtools/bnd/blob/master/biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java#L148

Because getInputResource() is returning null, we end up passing a single element list back to the resolver and that element is null. Felix Resolver 1.4.0 (ResolverImpl:151) assumes that the elements in the list are not null.

An easy (but potentially wrong) fix is just to add a check in getMandatoryResources() that returns an empty list if getInputResource() returns null.

**Comment by timothyjward** [comment]
> An easy (but potentially wrong) fix is just to add a check in getMandatoryResources() that returns an empty list if getInputResource() returns null. I don't know the implications of that change, so I defer to smarter people.

The resource should never be null. It may have no requirements, but it should always exist.

**Comment by bjhargrave** [comment]
Yes, I suspect the bug is in bndtools since it should not attempt to resolve with zero resources (null).

**Comment by timothyjward** [comment]
It looks like bndtools fails to call https://github.com/bndtools/bnd/blob/master/biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java#L969 with an empty array.

**Comment by timothyjward** [comment]
Actually it looks like this is the culprit:

https://github.com/bndtools/bnd/blob/master/biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java#L391

We should never return null, just a resource with no requirements.

**Comment by bjhargrave** [comment]
Agree. You make a PR?

**Comment by timothyjward** [comment]
The PR is  #1061
