### ISSUE TITLE
Fixed Indexed Repo caches on URL, not on SHA

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1062]
The current caching of Indexed Repo can potentially fail. By default there is a single shared cache for all these repos. Since the cache key is the URL, we potentially run the problem that one repo is updated but keeps the same URL. The other repo will then have a different sha in its index file.

We should replace this mechanism with a SHA directory name.

**Comment by pkriens** [comment]
When bnd creates directories in bndcache, their names are an encoded URL's of the repository, e.g. https%3A%2F%2Fbndtools.ci.cloudbees.com%2Fjob%2Fbnd.master%2FlastSuccessfulBuild%2Fartifact%2Fdist%2Fbundles%2Forg.osgi.impl.bundle.repoindex.cli.

For some filesystems such names can be too long (observed on eCryptfs on Ubuntu with a filename limit of 143 octets).

The solution might be to generate a directory structure corresponding to URL components, instead of a flat directory.

**Comment by bjhargrave** [comment]
FixedIndexRepo replaced by OSGiRepository.

**Comment by six86** [comment]
How does migrating work? Just replacing "aQute.bnd.deployer.repository.FixedIndexedRepo" with "aQute.bnd.repository.osgi.OSGiRepository" doesn't work with a Nexus repository.
