### ISSUE TITLE
DS analysis doesn't detect invalid unbind methods

### ISSUE THREAD

**Issue by djencks** [bndtools/bnd#1064]
in a apec-annotated DS component, apparently if you have a bind method

{code}
@Reference
protected void setA(A a) {}
{code}
and an unrelated unbind method
{code}
protected void unsetA(B b) {}
{code}
bnd won't notice the type mismatch and generate xml listing both the bind (setA) and non-unbind  (unsetA) methods.  Felix DS 2 objects strongly to this.

Along with not generating the invalid xml, I guess we should emit a warning since this is very likely a mistake?

**Comment by timothyjward** [comment]
> Along with not generating the invalid xml, I guess we should emit a warning since this is very likely a mistake?

I agree, assuming that B is not a super type of A. Obviously if you can pass an `A` into `unsetA(B b)` then Felix DS 2 should not be barfing. If you can't then omitting the unbind attribute and emitting a warning (with error location details for bndtools!) sounds like the correct behaviour.

Good catch, and definitely something to fix for bnd 3.0 RC2!

**Comment by bjhargrave** [comment]
There is no need for A and B to be related types. A must be a valid type for the bind method given the type of the Reference and B must be a valid type for the unbind method given the type of the Reference. So it is not correct to talk about a type mismatch between the argument(s) of the bind and unbind methods.
