### ISSUE TITLE
Add shutdown hook to Launcher for clean Framework stop

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1066]
This [StackOverflow question](http://stackoverflow.com/questions/32211120/how-to-stop-an-osgi-application-from-command-line) got me thinking... shouldn't we support a similar shutdown hook in the bnd Launcher?

**Comment by bjhargrave** [comment]
FYI. I added a comment to your SO answer that the cast to `Framework` is not spec compliant.

**Comment by njbartlett** [comment]
Thanks BJ... I wasn't aware of this. Does there exist a spec-compliant way for an ordinary bundle to get the Framework object? Or is it only really allowed from the launcher?

**Comment by bjhargrave** [comment]
`Framework` objects are only specified to come from the `FrameworkFactory`, so a bundle running in the framework has no safe way to get the `Framework` object for their framework. They just have access to the `Bundle` object of the system bundle which does not have to be an instanceof `Framework`.

It would be better if the shutdown hook is part of the launcher. So, if we decide to add this to the bnd launcher, then it of course will have access to the `Framework` object.

**Comment by njbartlett** [comment]
Sure we can do it in our launcher. Sucks for the Stackoverflow question but oh well.

**Comment by timothyjward** [comment]
> `Framework` objects are only specified to come from the `FrameworkFactory`, so a bundle running in the framework has no safe way to get the Framework object for their framework. They just have access to the `Bundle` object of the system bundle which does not have to be an instanceof `Framework`.

I thought it was required for bundle zero to be adaptable to `Framework` e.g.

    Bundle systemBundle = context.getBundle(0);
    Framework framework = systemBundle.adapt(Framework.class);

**Comment by bjhargrave** [comment]
You are correct. So the proper thing is not to cast it to `Framework` but to adapt it to `Framework` since the adaptation can  return a different object. (So many things in the spec...)

**Comment by bjhargrave** [comment]
I updated the example code in the SO entry.

**Comment by bjhargrave** [comment]
Looking into this a bit and I am not sure the Launcher should register a shutdown hook to perform a clean framework stop. From the javadoc of `addShutdownHook`:

> Shutdown hooks run at a delicate time in the life cycle of a virtual machine and should therefore be coded defensively. They should, in particular, be written to be thread-safe and to avoid deadlocks insofar as possible. They should also not rely blindly upon services that may have registered their own shutdown hooks and therefore may themselves in the process of shutting down. Attempts to use other thread-based services such as the AWT event-dispatch thread, for example, may lead to deadlocks.

> Shutdown hooks should also finish their work quickly. When a program invokes exit the expectation is that the virtual machine will promptly shut down and exit. When the virtual machine is terminated due to user logoff or system shutdown the underlying operating system may only allow a fixed amount of time in which to shut down and exit. It is therefore inadvisable to attempt any user interaction or to perform a long-running computation in a shutdown hook.

Given that so much can happen during framework stop that is outside the control of the framework (e.g. BundleActivators), I don't think it is wise for the launcher to register a shutdown hook to stop the framework.

**Comment by bjhargrave** [comment]
Bndtools call: Discussed and agreed to not do this.
