### ISSUE TITLE
badly terminated extension lines in .bnd files produce odd errors

### ISSUE THREAD

**Issue by djencks** [bndtools/bnd#1078]
```
Include-Resource: \ 
  WEB-INF=resources/WEB-INF,\
```
produced the error

      [bnd]  Input file does not exist: b

I don't have an example handy but whitespace after a \ prevents it from being a line continuation and tends to produce incomprehensible errors, especially when this is in the middle of a long Service-Component header defining DS components.

Both of these were accepted and interpreted leniently by old versions of bnd (I don't know how old).

**Comment by pkriens** [comment]
Check if the input likely has this case by checking for strange property keys.

**Comment by pkriens** [comment]
Should be fixed in https://github.com/bndtools/bnd/pull/1241
