### ISSUE TITLE
AetherRepository does not work if the version only has major and minor like 2.5

### ISSUE THREAD

**Issue by cschneider** [bndtools/bnd#1106]
I am trying to resolve a bundle from maven central:
-buildpath: \
	javax.servlet:servlet-api;version=2.5

The error below shows that somewhere the version is converted into the format with three parts which is incorrect. In maven some artifacts are stored with a version that does not adhere to major.minor.bugfix syntax. In this case it is major.minor but there might also be other more exotic ones.

Description	Resource	Path	Location	Type
javax.servlet:servlet-api;version=2.5.0 Not found in [bnd-cache, Release, Local, Bndtools Hub, /home/cschneider/workspace/bndtools/cnf/buildrepo r/w=true, JpmRepository [writable=false, name=Central, location=~/.bnd/shacache, digest=DA39A3EE5E6B4B0D3255BFEF95601890AFD80709], aQute.bnd.deployer.repository.aether.AetherRepository@392af8d]	bnd.bnd	/service1	line 1	Bndtools Path Problem Marker

Some more details:
bnd-release    = https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles

-pluginpath: \
    ${plugin-dir}/biz.aQute.repository/biz.aQute.repository.jar,\
    ${build}/cache/biz.aQute.repository.aether-latest.jar;url=${bnd-release}/biz.aQute.repository.aether/biz.aQute.repository.aether-latest.jar
    
-plugin: \
	aQute.bnd.deployer.repository.LocalIndexedRepo;name=Release;local=${workspace}/cnf/releaserepo;pretty=true,\
	aQute.bnd.deployer.repository.LocalIndexedRepo;name=Local;local=${workspace}/cnf/localrepo;pretty=true,\
	aQute.bnd.deployer.repository.FixedIndexedRepo;name=Bndtools Hub;locations=https://raw.githubusercontent.com/bndtools/bundle-hub/master/index.xml.gz,\
	aQute.lib.deployer.FileRepo;name=Build;location=${workspace}/cnf/buildrepo;latest=false,\
	aQute.bnd.deployer.repository.aether.AetherRepository; name=Maven Central; url=http://repo1.maven.org/maven2/

**Comment by gamerson** [comment]
For buildpaths this can work if you use 'strategy=exact' along side of the
version string.  So something like this

-buildpath: javax.servlet:servlet-api;version=2.5;strategy=exact



On Mon, Sep 14, 2015 at 4:06 AM, Christian Schneider <
notifications@github.com> wrote:

> I am trying to resolve a bundle from maven central:
> -buildpath: \
> javax.servlet:servlet-api;version=2.5
>
> The error below shows that somewhere the version is converted into the
> format with three parts which is incorrect. In maven some artifacts are
> stored with a version that does not adhere to major.minor.bugfix syntax. In
> this case it is major.minor but there might also be other more exotic ones.
>
> Description Resource Path Location Type
> javax.servlet:servlet-api;version=2.5.0 Not found in [bnd-cache, Release,
> Local, Bndtools Hub, /home/cschneider/workspace/bndtools/cnf/buildrepo
> r/w=true, JpmRepository [writable=false, name=Central,
> location=~/.bnd/shacache, digest=DA39A3EE5E6B4B0D3255BFEF95601890AFD80709],
> aQute.bnd.deployer.repository.aether.AetherRepository@392af8d
> <https://github.com/aQute.bnd.deployer.repository.aether.AetherRepository/bnd/commit/392af8d>]
> bnd.bnd /service1 line 1 Bndtools Path Problem Marker
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bnd/issues/1106>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by pkriens** [comment]
we are working a replacement for the Aether repo.
