### ISSUE TITLE
Primitive conversion in aQute.lib.converter.Converter

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#1124]
Currently when the Converter class attempts to convert a null reference into a number, it will default to 0 in all cases. In the case of primitive *wrapper* types this throws away information which it might actually be useful to keep.

For example when creating a service implementation of osgi.enroute.rest.api.REST, and extending the RESTRequest interface to have query strings mapped to methods:

    interface NumberedRESTRequest extends RESTRequest {
      public int number1();
      
      public Integer number2();
    }

If the request doesn't include values for number1 or number2 they will both return 0. Why not have number2 default to null so the developer can decide what behaviour actually makes sense when no number is given?

**Comment by pkriens** [comment]
The problem is that people often use autoboxing. If we return null it will create a weird NPE error on an int assignment.

The best way to get another value when not set is to pass a parameter to the method:

               NumberedRESTRequest n = ...;
               int foo = n.number2( -1 );

In this case foo will be set to the value in the map if set, or -1 if no set.

**Comment by eliasvasylenko** [comment]
Thanks for the workaround, I hadn't noticed you could do that.

Still, I'm not convinced that a potential NPE is really a problem. I mean, the value is fundamentally nullable, so if people aren't properly dealing with that and are relying on an arbitrary internal choice of default value then they're probably making a mistake as it is...

If they really do want a default 0, it would be much more sensible to provide it explicitly in the way you described.

Or just use 'int' instead of 'Integer' and avoid the problem altogether...

Fair enough though, I suppose I am just quibbling over trivial details :)

**Comment by pkriens** [comment]
Well, there is also the issue of backward compatibility. Don't want to start breaking people.

**Comment by eliasvasylenko** [comment]
True.
