### ISSUE TITLE
BND 3 is failing when processing a @ProvideCapability annotation containing a macro

### ISSUE THREAD

**Issue by izaera** [bndtools/bnd#1129]
Given the following code that worked perfectly for BND 2.4.1:

```java
	@ProvideCapability(
		name = "jsp.taglib", ns = "osgi.extender",
		value = "uri=http://alloy.liferay.com/tld/alloy", version = "${version}"
	)
```

It is now throwing an exception for BND 3. The problem is a change in BND that now tries to validate ${version} as a valid version number (matching a regex) which, of course, fails. It looks like the macro should be expanded before validating the version.

This is the stack trace:

```
/Users/ivan/Liferay/devel/current/liferay-portal/build-common-java.xml:172: Failed to build jar file:
	at aQute.bnd.ant.BndTask.executeBackwardCompatible(BndTask.java:281)
	at aQute.bnd.ant.BndTask.execute(BndTask.java:116)
```

Unfortunately, the real exception (the one explaining the parsing problem) cannot be seen because it is swallowed by a try/catch which is not logging or rethrowing the original exception (a very bad, practice BTW, but such is life :-( ).

**Comment by bjhargrave** [comment]
Closing per @rotty3000.
