### ISSUE TITLE
biz.aQute.remote.launcher "Error: Could not find or load main class"

### ISSUE THREAD

**Issue by paulbakker** [bndtools/bnd#1131]
I'm testing out the remote launcher as describe in the docs: http://bnd.bndtools.org/chapters/300-launching.html.

With a newly created workspace and project (bndtools 3.0) and the following bndrun file I'm getting "Error: Could not find or load main class" when trying to run.

```
-runfw: org.apache.felix.framework;version='[4,5)'
-runee: JavaSE-1.7
-runsystemcapabilities: ${native_capability}

-resolve.effective: active;skip:="osgi.service"
-runpath:       biz.aQute.remote.launcher;version=latest

```

**Comment by pkriens** [comment]
Did you use the bnd native entry in the bndtools menu?

**Comment by paulbakker** [comment]
I just retested it to make sure, and it now seems to work... Might be because of a newer bndtools but I'm not quite sure which exact version I was on (besides that it was > 3.0).

Anyway, it seems to work well! This opens up some nice possibilities again :)
