### ISSUE TITLE
ConfigParser for OSGi 6 metatype annotations

### ISSUE THREAD

**Issue by marcdejonge** [bndtools/bnd#1134]
https://gist.github.com/marcdejonge/5cf60fca7641d3378c04

I've created for my project a ConfigParser to convert a property map to a configuration object that has been defined using OSGi 6 metatype annotations. This class is based on the Configurable class that you have, but it parses all the properties directly in the parse method, such that any error will directly throw a ConfigurationException (which simple inherits from the IllegalArgumentException). I'd like to share this code with you, maybe you want to include it somewhere in bnd.

**Comment by bjhargrave** [comment]
You know that in DS 1.3, DS handles this for you? You can define a component property type (as an annotation type) and DS will map your configuration properties into an instance of the component property type. See 112.8.2.

```java
@interface Config {
  boolean enabled() default true;
  String[] names() default {"a", "b"};
  String topic() default "default/topic";
}
@Component
public class MyComponent {
  void activate(Config config) {
    if (config.enabled()) {
      // do something
    }
    for (String name:config.names()) {
      // do something with each name
    } 
  }
}
```

**Comment by bjhargrave** [comment]
No response. Please reopen with any feedback. Thanks.

**Comment by marcdejonge** [comment]
Sorry, a lot has come up at work, so I forgot this issue. I didn't know this option in DS 1.3 and it looks even easier, so I'll use that.

 :+1:
