### ISSUE TITLE
bnd-indexer-plugin: Support long term stable uri for maven artifacts

### ISSUE THREAD

**Issue by cschneider** [bndtools/bnd#1144]
Currently the bnd-indexer-plugin looks up a mvn artifact and determines from the meta data in the local repository where the artifact came from. 
So a uri may look like https://mynexus.locationa.myompany/org/apache/aries/jpa/org.apache.aries.jpa.container/2.2.0/org.apache.aries.jpa.container-2.2.0.jar

If I now upload this index to maven central the URI will be completely useless for other users.

Even worse this completely does not work during the release build if I want to create an index from some artifacts in my project. At the time of the release build my artifacts are not yet in any remote repository. So when I create the index I get the issue #1142. 

Even if the URI in the index is the maven central uri https://repo1.maven.org/maven2/org/apache/aries/jpa/org.apache.aries.jpa.container/2.2.0/org.apache.aries.jpa.container-2.2.0.jar this does not work in many cases. It is very common in companies that direct internet access is forbidden. So the http uri will not work. Instead these companies use a local Nexus instance that will act as a proxy to maven central and maybe also for other maven repos in the company. 

I think the only solution to this is to use a mvn uri for the index. This has the disadvantage that anyone who wants to use the index will need the logic to resolve a mvn uri but I do not see any other way to create a long term stable uri.

I am open to other solutions but have not found any other till now.

**Comment by timothyjward** [comment]
> Currently the bnd-indexer-plugin looks up a mvn artifact and determines from the meta data in the local repository where the artifact came from. 

This is not actually true, it looks at the metadata in the configured remote repositories, and selects the first named repository that contains the content. There are automated tests that demonstrate this using an old version of bnd, and a snapshot of Aries Async.

> If I now upload this index to maven central the URI will be completely useless for other users.

This isn't normal practice - normal  practice would be to do a mvn clean deploy with a different profile selected. Regardless of whether you're creating an index or not, if you're publishing to maven central then the profile should not reference "private" repositories. If private repositories are used you can end up with dependencies that are not publicly available and then nobody can depend on the transitive closure of the artifact that you're uploading. In the case where private repositories have been removed then the generated index would then also not reference the private repositories.

> Even worse this completely does not work during the release build if I want to create an index from some artifacts in my project. At the time of the release build my artifacts are not yet in any remote repository. So when I create the index I get the issue #1142.

This is also incorrect. At *development* the artifacts are not in a release repository, but you should be using a development profile with local URLs. The release build will use mvn deploy, at which point the artefacts *are* in the release repository at the point they are indexed. The issue #1142 is different. In this case the local maven repository contained a pre-existing cached artifact with no dependency information. This simply would not happen in CI where the cache is cleaned between builds to ensure that a "clean" build can proceed.

> Even if the URI in the index is the maven central uri https://repo1.maven.org/maven2/org/apache/aries/jpa/org.apache.aries.jpa.container/2.2.0/org.apache.aries.jpa.container-2.2.0.jar this does not work in many cases. It is very common in companies that direct internet access is forbidden. So the http uri will not work. Instead these companies use a local Nexus instance that will act as a proxy to maven central and maybe also for other maven repos in the company.

In this case the generated URI would not point at maven central. When the index is built the generated URIs use the repositories configured for that pom. In this case the corporate user's index would point at the internal company repository, which is also the location that the index will be published to.

I think that our disconnect comes from the fact that you see the generated index as being some sort of "universal artifact", which it simply cannot be. The index that is generated will always contain, either explicitly or implicitly, information about the repositories used to create it.

Your view is that we should use mvn: URLs to implicitly hide the dependency on the repositories, forcing every client of the index to have the repositories/mirrors configured locally. Mine is that the index will be created and published within a scope, and that the primary URLs should be correct and valid with in that scope, without the need for extra local information.

I would be perfectly happy to add mvn: URLs as a second content capability, but I strongly believe that forcing the use of mvn: URLs is a major barrier to user adoption. I also believe that the instability of mvn: SNAPSHOT URLs fundamentally breaks the repository model. The SHA in the index, and potentially all of the capabilities in the index, will be incorrect as the referenced binary changes over time.

**Comment by cschneider** [comment]
How about simply creating two index files? One with mvn uris and one with http uris. Then the user can decide which one to use. So for karaf we can use the mvn based one and for bndtools the http based one.

**Comment by timothyjward** [comment]
> How about simply creating two index files? One with mvn uris and one with http uris. Then the user can decide which one to use. So for karaf we can use the mvn based one and for bndtools the http based one.

I don't understand why we would do this when we can have both URIs inside the same index? The OSGi specification is very clear that a resource must have at least one content capability, but may have many to support different mirrors and/or URI schemes. It would seem to be much more sensible to have one index that contained both URIs, then the provisioner can simply select the one(s) that it wants to try.

**Comment by cschneider** [comment]
I was not aware that this is possible by default. One concern still may be that the wrong uri might produce a lot of noise. If you have a index with incorrect http uris then the provisioning tool might log an error for each of them. Or inside a firewall you might do "forbidden" accesses to the outside world. 

On the other hand the mvn uri might confuse a provisioning tool that can not handle them and again create a lot of errors. 

So the separate indexes would help to avoid these errors. If this can be achieved with one index file too then this would be completely fine for me.

**Comment by timothyjward** [comment]
I've put a rough attempt at a solution here: b9cd3faae3f40ae843d96eb1f3f1be7e980c5395

I'm not going to have more time to work on this today, but hopefully you'll have an opportunity to test it out. 

    <addMvnURLs>true</addMvnURLs>

enables the extra content capability.

**Comment by cschneider** [comment]
I tried the change.. btw it was pretty hard as the commit does not seem to be in any branch. 
The code compiled fine but when I used the plugin in my project to create the list it showed a compilation error. Not sure what went wrong. 

The source code looks good as far as I can tell. Probably I just did something wrong in assembling the parts.

**Comment by timothyjward** [comment]
> I tried the change.. btw it was pretty hard as the commit does not seem to be in any branch. 

I just put it in the timothyjward/bnd master branch, sorry for not mentioning that!

**Comment by timothyjward** [comment]
> The source code looks good as far as I can tell. Probably I just did something wrong in assembling the parts.

Given that you seem happy with the solution I've created a PR.

**Comment by cschneider** [comment]
I just tested the newest version from master. Works fine. I get http url and mvn url. The index also still works in bndtools. So from my side this looks fine. 
I will now start the discussion on the karaf list how we can use such indexes.

**Comment by cschneider** [comment]
Ouch ... I was too fast with reporting success. I checked that I can still find my artifacts but I did not save my launcher. When I do this and it calls the resolve step I get the error:
An internal error has occurred.
Resource is schizophrenic

I guess bndtools complains that the resource has two osgi.content nodes. So it seems at least bndtools needs to be changed to be able to cope with this.

**Comment by timothyjward** [comment]
Thankfully it's a simple fix in a utility class. I'm fixing it under bndtools/bndtools#1195
