### ISSUE TITLE
Update documentation on http://www.aqute.biz/Bnd/MetaType with regards to default metatype annotations

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#1147]
Since OSGI 6 there are also Standard Metatype Annotations which can be used. Are those already understood by bnd? If so it would be good to mention that in http://www.aqute.biz/Bnd/MetaType.

**Comment by bjhargrave** [comment]
Docs are now at bnd.bndtools.org. @pkriens will update his website to point to the new location.

**Comment by pkriens** [comment]
Though it still requires a lot of work, the documentation is currently at bnd.bndtools.org. I will make sure we redirect to the new site.

Volunteers for helping to update that site?
