### ISSUE TITLE
Generated manifest line lengths are too long.

### ISSUE THREAD

**Issue by mattnathan** [bndtools/bnd#1156]
See http://stackoverflow.com/questions/33143460/does-the-jar-manifest-mf-max-line-length-of-72-include-the-eol-bytes

I'm using BND to generate OSGi manifests/bundles for use in an embedded OSGi container and the container appears to be stricter than the JDK implementation wrt reading Manifest files. Namely it enforces the max line length defined in the specification, something the JDK is lax on when reading the files.

While the exact meaning of the Manifest specification is a little vague the JDK implementation does output manifest files where line length includes the EOL markers CR and LF, this results in _usable_ line content of 70 characters (or 69 characters for continuations). It would be nice if BND would output manifests in the same format as the JDK where each line is 72 bytes or under including the EOL characters.

I'm using BND via the maven-bundle-plugin version 3.0.0
The Java version I checked the Manifest implementation of is jdk1.7.0_79
I guess the code that needs looking at to fix this is here: https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java#L495

**Comment by bjhargrave** [comment]
Yes, it does look like `w>=72` should be `w>=70`. 

Also, since the [manifest spec](https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#Manifest_Specification) allows LF line endings, we could do `w>=71` if we change to use LF instead of CRLF line endings.

**Comment by mattnathan** [comment]
The JDK hard codes to CRLF - might be worth keeping it like that to maintain consistency (and just in case)
