### ISSUE TITLE
non-workspace gradle plugin and bnd-maven-plugin silently ignore `Include-Resource` header

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1161]
While it seems the recommended way of handling resources is `-includeresource` directive, when using the older `Include-Resource` header instead, the gradle plugin silently ignores it's contents making it hard to identify why it's not working.

**Comment by rotty3000** [comment]
Thanks! :)

**Comment by bjhargrave** [comment]
Please test to make sure it works (and that something else is not broken!)
