### ISSUE TITLE
deploy biz/aQute/bnd/biz.aQute.launcher to maven central

### ISSUE THREAD

**Issue by retog** [bndtools/bnd#1163]
To allow creating launchers from maven based projects.

**Comment by bjhargrave** [comment]
@pkriens Please make a list of the jars we really should publish to maven central. Current list is here: https://bintray.com/bnd/bnd.

**Comment by timothyjward** [comment]
I would expect to see the bnd repository implementation jar in there. I'm pretty sure that none of it gets sucked into bndlib (and currently unable to check), and it would be a useful dependency for any maven plugins that want to deal with bnd repositories e.g. A tester plugin or the proposed executable jar plugin.

Tim

**Comment by bjhargrave** [comment]
For 3.1, we will add launcher, junit and tester in Maven Central.
