### ISSUE TITLE
Spurious split package warnings from issues amongst jars inside the bundle classpath

### ISSUE THREAD

**Issue by benson-basis** [bndtools/bnd#1172]
Please have a look at https://issues.apache.org/jira/browse/FELIX-5069. It seems to me that this has to be inside of bnd. What is happening here is that a package is split between jars that are all within the Bundle-Classpath, where the concept of a split package doesn't actually mean anything.

**Comment by bjhargrave** [comment]
This is referring to where bnd is finding the package contents. It is split across multiple input jars some of which you may put on the `Bundle-Classpath`. Please just use the `-split-package` directive as suggested by the message.

**Comment by benson-basis** [comment]
With all due respect, not 'some of which', but rather 'all of which'.

The problem here is that I've educated my local users to be very, very,
very, averse to split packages, so I wish they didn't get a warning in this
case.

Is there some reason that it's particularly hard to imagine changing this?
I would be willing to look at making a patch since I'm the one who is
whining.

**Comment by bjhargrave** [comment]
bnd is complaining about the input. It is not making a statement about the resulting bundle. Since you present multiple inputs to bnd, it sees the package split across the inputs when they are analyzed.

**Comment by bjhargrave** [comment]
And looking at your [example](https://github.com/bimargulies/felix-unwanted-split-package-messages-tc), you do have 2 projects contributing to the package. Since your combiner knows the packages are being combined, it can either use the `-split-package` directive to merge the packages or `-fixupmessages` to elide the message.

**Comment by pkriens** [comment]
It is hard to see what is happening on the bnd side with the Maven plugin. Could you make a bnd test case that gives the error you want to get rid of? In principle I am ok to not have warnings when JARs come from the Bundle-ClassPath but I am not sure I see how you can get them yet.

**Comment by benson-basis** [comment]
Can you help me a bit? I've never used bnd _except_ in maven. I started to try to see how to make a .bnd file and repro from command line, but I'm mildly stumped. The job description: Here's a tree of .class files and two jar files. I want to end up with a Bundle-Classpath of .,jar1,jar2.

**Comment by bjhargrave** [comment]
You may want to ask for help in the felix mail list since they maintain the maven-bundle-plugin. This project has a different maven plugin, bnd-maven-plugin, which is fairly simple compared to the implicit behavior of maven-bundle-plugin.

**Comment by benson-basis** [comment]
@pkriens I succeeded in abstracting a test case. If you pull the latest from the repo, and cd to the 'bnd' directory, you can run the following, with your own path for the bnd jar, of course.

```
java -jar /Users/benson/misc/bnd/dist/bundles/biz.aQute.bnd/biz.aQute.bnd-3.1.0.jar -f combine.bnd
```

If it turns out that the bnd instructions in combine.bnd are wrong for the task at hand, I will make the necessary repairs to the maven-bundle-plugin, as I am a committer on it. 

I have to offer a caveat: the instructions that the maven-bundle-plugin generates don't _seem_ to include `-classpath` at all, so I added that to get bnd to do anything at all. I will do some debugging of the plugin to see if there's some other information flow I'm missing.

**Comment by pkriens** [comment]
a) If you install bnd( install jpm from http://www.jpm4j.org) with sudo jpm install -f bnd
b) I think I would have to see your combine.bnd file.
c) It is probably easiest to clone the bnd repo, and add a testcase in biz.aQute.bndlib.test/src/test/BuilderTest. There are lots of examples there.
d) The instructions are basically in pseudocode
 
builder.addClasspath( jar1.jar, jar2.jar )
builder.setBundleClasspath( ".,jar1.jar,jar2.jar" )
Jar bin = new Jar(bin);
builder.setJar(bin);
builder.setExportContents("????")
Jar jar = builder.build();

e) Bundle Class path is a really bad idea. It makes your bundles not work for a compiler and tends to create lots of unnecessary dependencies
f) The basic model of bnd is to express how your bundle should look like, what packages it contains. This is important because everything you include is causing imports. There is no easy way to do this except to control it by hand. Just like developing source code, creating your packaging is also design.

**Comment by benson-basis** [comment]
The entire test case is at https://github.com/bimargulies/felix-unwanted-split-package-messages-tc.

The combine.bnd is at https://github.com/bimargulies/felix-unwanted-split-package-messages-tc/blob/master/bnd/combine.bnd.

I appreciate that bundle class path is not a desirable pattern. Like many other people, I have the problem of adapting long-existing code to OSGi, without freedom to do arbitrary refactoring. The existing code was not divided into jar files according to OSGi bundle design principles. I am solving this problem by creating bundles that export functionality through new OSGi services in new packages, and gathering split packages together into single bundles. In other words, my whole reason to resort to Bundle-Classpath is to cure split packages within constraints.

I will work on a test case PR later today.

combine.bnd contains:

```
Embed-Dependency=sp-tc-jar1,sp-tc-jar2
Bundle-DocURL=http\://www.apache.org/
Bundle-ClassPath=.,sp-tc-jar1-0.0.1-SNAPSHOT.jar,sp-tc-jar2-0.0.1-SNAPSHOT.jar
Export-Package=org.apache.felix.tc
Bundle-License=http\://www.apache.org/licenses/LICENSE-2.0.txt
Include-Resource=sp-tc-jar1-0.0.1-SNAPSHOT.jar\=jars/sp-tc-jar1-0.0.1-SNAPSHOT.jar,sp-tc-jar2-0.0.1-SNAPSHOT.jar\=jars/sp-tc-jar2-0.0.1-SNAPSHOT.jar
-removeheaders=Include-Resource,Private-Package
Bundle-SymbolicName=org.apache.felix.sp-tc-combine
Private-Package=org.apache.felix.combined
Bundle-Version=0.0.1.SNAPSHOT
Import-Package=*
Embedded-Artifacts=sp-tc-jar1-0.0.1-SNAPSHOT.jar;g\="org.apache.felix";a\="sp-tc-jar1";v\="0.0.1-SNAPSHOT",sp-tc-jar2-0.0.1-SNAPSHOT.jar;g\="org.apache.felix";a\="sp-tc-jar2";v\="0.0.1-SNAPSHOT"
Bundle-Vendor=The Apache Software Foundation
-sourcepath=../sp-combine/src/main/java
Bundle-Name=sp-tc-combine
-classpath: stuff,jars/sp-tc-jar1-0.0.1-SNAPSHOT.jar,jars/sp-tc-jar2-0.0.1-SNAPSHOT.jar

```

**Comment by benson-basis** [comment]
@pkriens I've supplied a PR with the test case.

**Comment by pkriens** [comment]
This can be fixed by using -includeresource && -exportcontents instead of Export-Package and Embed-Dependencies

       Bundle-ClassPath=.,${lsr;jar/*}
       -exportcontents=org.apache.felix.tc
       -includeresource= jar=jar
       -sourcepath=../sp-combine/src/main/java
