### ISSUE TITLE
gradle plugin: testResultsDirName deviates from Gradle default

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#1176]
* The default

See http://scratchpad.pietschy.com/gradle/java_plugin.html, table 15.3
```
testResultsDir 	testResultsDirName 	test-results 	buildDir/test-results
```

* Bnd's value

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy:69:
```
      testResultsDirName = bnd('test-reports', 'test-reports')
```

(also present in biz.aQute.bndlib/src/aQute/bnd/build/ProjectTester.java:25)

**Comment by bjhargrave** [comment]
This was done per https://github.com/bndtools/bnd/issues/730.

**Comment by fhuberts** [comment]
IMHO that decision is unfortunate.
It would have been way easier for everyone to use the Gradle default and to name the file differently, like TEST-bnd-<testclass>.xml

**Comment by bjhargrave** [comment]
You can just set

```
test-reports: test-results
```
in the `cnf/build.bnd` of your gradle build to get what you desire.

**Comment by fhuberts** [comment]
yes I have that.
And when I remove it my normal JUnit tests end up in test-reports as well !
That is not inteneded, right?

**Comment by fhuberts** [comment]
It seems that now both JUnit and OSGi-JUnit test end up in the same directory.
The bnd gradle plugin is responsible since it overrides testResultsDirName

**Comment by fhuberts** [comment]
So you still have the same clash that you trying to avoid in #730

**Comment by bjhargrave** [comment]
The point of #730 was to get the results all in the same folder. The name clash issue exists anyway unless you configure the test and check tasks to use different output folders (and this issue asked for them to be the same (but different that the current) default folder.)

So you have what you wanted by configuring `test-reports` to the desired folder name.

**Comment by fhuberts** [comment]
Then I'm lost.
In 730 you say something like 'what if a test is run both normal and osgi, the files will clash'

That is still the case here

Just use the default that Gradle defines, and name the OSGi-test file differently

**Comment by fhuberts** [comment]
> That is still the case here

And that makes having the results in a non-default directory pointless and therefore unneeded

**Comment by fhuberts** [comment]
And actually, you are now moving the normal JUnit output to a non-default location.
IMHO a big no-no
