### ISSUE TITLE
bnd-maven-plugin: Use incremental build api

### ISSUE THREAD

**Issue by cschneider** [bndtools/bnd#1180]
I have recently enabled the servicemix maven-depends-plugin to run in the m2e incremental builds.
Now the dependencies.properties are automatically updated whenever someone saves the pom file.
A similar change could be done to the bnd-maven-plugin to update the DS xml descriptors and the Manifest whenever a java file is saved. Below I describe what I needed to do for the dependency plugin to make this work.

If you want I can take a look into it and create a pull request.

Here is a documentation from M2E about the API:
https://wiki.eclipse.org/M2E_compatible_maven_plugins

I needed to do three things:

Add the API to the pom:
https://github.com/apache/servicemix-maven-plugins/blob/master/depends-maven-plugin/pom.xml#L40-L45

Use the API to determine if there are changes:
https://github.com/apache/servicemix-maven-plugins/blob/master/depends-maven-plugin/src/main/java/org/apache/servicemix/tooling/depends/GenerateDependsFileMojo.java#L138

Announce each file change through the API:
https://github.com/apache/servicemix-maven-plugins/blob/master/depends-maven-plugin/src/main/java/org/apache/servicemix/tooling/depends/GenerateDependsFileMojo.java#L178

Announce that the mojo may take part in the incremental build:
https://github.com/apache/servicemix-maven-plugins/blob/master/depends-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml

**Comment by bjhargrave** [comment]
The `bnd-maven-plugin` already hooks into the m2e incremental build: <https://github.com/bndtools/bnd/blob/master/maven/bnd-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml#L13>. So perhaps all that might be needed is to to announce the changes to `target/classes` after the `bnd-maven-plugin` runs.
