### ISSUE TITLE
Directories created in bndcache have too long names

### ISSUE THREAD

**Issue by jest** [bndtools/bnd#1186]
When bnd creates directories in `bndcache`, their names are an encoded URL's of the repository, e.g. `https%3A%2F%2Fbndtools.ci.cloudbees.com%2Fjob%2Fbnd.master%2FlastSuccessfulBuild%2Fartifact%2Fdist%2Fbundles%2Forg.osgi.impl.bundle.repoindex.cli`.

For some filesystems such names can be too long (observed on eCryptfs on Ubuntu with a filename limit of 143 octets).

The solution might be to generate a directory structure corresponding to URL components, instead of a flat directory.

**Comment by pkriens** [comment]
Is combined with #1062
