### ISSUE TITLE
-resolve.effective is not inherited from parent bndrun files

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#1188]
Observed at the OSGi Community Event. When specifying the following:

    -resolve.effective: active;skip:="osgi.service"

OSGi service capabilities are skipped but other active-time requirements are used. This is correct, but it only works if the property is defined directly inside the bndrun being resolved. If the property is inherited from a parent bndrun then it no longer applies...

**Comment by pkriens** [comment]
According to the code we inherit from the `build.bnd` and `ext` directories. (Unless it is a standalone `bndrun` of course.) I am not sure how you inherit from another bndrun file except for `-include`, which should then also work?

The `bndrun` files do not inherit from the project in the same directory (and never have).

**Comment by timothyjward** [comment]
This was using `-include` to pull in entries from a common file. It reliably did not work.

**Comment by bjhargrave** [comment]
Perhaps then the issue title is misleading. It sounds like you mean -resolve.effective from included bndrun files is ignored.

**Comment by pkriens** [comment]
@timothyjward Hmm. Can you show me the exact setup? The instruction is obtained from the ProjectResolver's properties, like all other instructions. There seems nothing special for this property.

**Comment by timothyjward** [comment]
> @timothyjward Hmm. Can you show me the exact setup? The instruction is obtained from the ProjectResolver's properties, like all other instructions. There seems nothing special for this property.

It's in the OSGi IoT SDK. https://github.com/osgi/osgi.iot.contest.sdk/blob/master/osgi.enroute.trains.application/trains-rsa.bndrun#L12
https://github.com/osgi/osgi.iot.contest.sdk/blob/master/osgi.enroute.trains.application/paremus.rsa.bnd#L10

**Comment by pkriens** [comment]
With junit tests I cannot break it. I tried putting the definition in the workspace, the include file, and the final bndrun file and it was all correct. Since I am not sure how to get the error in the IoT project (whatever I do things resolve fine) I need to get an error, what did not work?
