### ISSUE TITLE
JavaDocs are unreadable in the source files

### ISSUE THREAD

**Issue by jest** [bndtools/bnd#1190]
The commit 8178f7a11a2803efda6c2ca20885d5c5f5dfdd58 ("Post 3.0 big code reformat") removed all end-of-lines in JavaDocs and replaced the with auto-generated ones. The docs (in source form) became very difficult to read.

Is it possible to revert the changes, e.g. by re-applying the rules (Eclipse formatter?) for the source code, but with nicer defaults for JavaDocs?

**Comment by bjhargrave** [comment]
It would be better to figure out why the formatter is messing up the javadoc. I never had time to figure it out.

**Comment by jest** [comment]
After importing the workspace into fresh Eclipse 4.5.1 the reformatting of JavaDocs works for me.

Shall I do a mass-formatting of all files as a single PR?

**Comment by bjhargrave** [comment]
I would like to understand what is different and why the formatting is made better by a fresh eclipse install.

In any case, we are planning to finish 3.1 around Dec 11, so any mass reformat will need to wait until after 3.1 is released.

**Comment by bjhargrave** [comment]
Can you export the prefs from your fresh eclipse install and put the up where I can download and look at them?

**Comment by jest** [comment]
I pasted the prefs to https://gist.github.com/jest/a75dd8b20deef569d03f
