### ISSUE TITLE
Integration test failures using Gradle

### ISSUE THREAD

**Issue by dlandoll** [bndtools/bnd#1192]
Gradle Wrapper: 2.1.1
Bnd Gradle Plug-in: biz.aQute.bnd:biz.aQute.bnd.gradle:3.0.0
Eclipse Bndtools Plug-in: 3.1.0.DEV-20151106-022219-gfc476f7

Example project to replicate the issue: https://github.com/dlandoll/bnd-gradle-jna

There is an when issue trying to run OSGi integration test projects from Gradle. In my particular case, the issue appears to be with the com.sun.jna bundle (3.0, 4.1, or 4.2) starting. There could potentially be other bundles that exhibit this problem if it is related to system packages provided by the framework at runtime.

The tests always run correctly if started from Eclipse. If I do a clean/rebuild of all bundles from Eclipse and then run "gradlew check" from the command line that also works. If I run "gradlew clean check" from the command line, the tests always fail because the com.sun.jna bundle is stuck in the Started state and my services that depend on JNA never resolve.

I've tried using 2.4, 3.0 and 3.1 versions of the BND Gradle plug-in with no luck. I've also tried using versions 4.4, 5.0 and 5.2 of the Apache Felix framework. From what I've been able to gather, it seems like the build/assemble process done by the Gradle plug-in is missing something that's done by the Eclipse bndtools plug-in.

**Comment by bjhargrave** [comment]
The com.sun.jna bundle is strange. It has `Bundle-ActivationPolicy: lazy` yet defines no `Bundle-Activator` class. So there is no point in having lazy activation since there is no activation class.

The bnd launcher starts bundles with `Bundle.start(START_ACTIVATION_POLICY)` which means the bundle's activation policy is honored. So if you need to actually get the bundle to the ACTIVE state, you will either need to remove `Bundle-ActivationPolicy: lazy` from its manifest or add some code to your test which explicitly starts the bundle: `Bundle.start()`.

**Comment by dlandoll** [comment]
I tried removing that line from the com.sun.jna manifest and the bundle
shows up as Active now when I run the test from Gradle, but still have the
test failure due to services not being activated.

**Comment by bjhargrave** [comment]
Well if all the bundle are active, then there must be some problem with the bundles not caused the services to be activated. You'll need to debug that.

**Comment by dlandoll** [comment]
Ok, I found the root cause. In the bnd.bnd file for my integration project
I only specify the api bundle on the buildpath (which is all that is needed
to compile the tests) and include both the api and implementation/service
bundles in runbundles.

However, when a Gradle build is executed with that configuration (and
without all bundles already created) the implementation bundle is not built
before the integration tests run, so there is no implementation bundle to
deploy during integration testing.

A see a couple of options to consider:
1) The integration test runner should report an error if all runbundle's
can't be found
2) Gradle plug-in should consider runbundles as dependencies and also build
those projects before building/testing the integration test project

I can add my implementation bundle to the buildpath for now to avoid this
issue.

**Comment by bjhargrave** [comment]
I think it is wrong for the gradle plugin to assume -runbundles are build dependencies. They are not.

Computing runbundles dependencies in the gradle build creates other problems. We specifically prevent this (see 02a95449). So we don't want the gradle plugin asking bnd to compute the runbundles dependencies while configuring the build. They must of course be computed for the check task, but they are assumed to have been built by then.

If you want, you can always add a `-dependson: my.impl.project` to your bnd file to require the named projects are built before your project.

I agree (1) would be a good idea. You should open a specific issue for that.
