### ISSUE TITLE
Potential issue with 32ad027 and Servlet?

### ISSUE THREAD

**Issue by seanbright** [bndtools/bnd#1203]
Before 32ad027 I had code that looked something like this:

    @Component(service = Servlet.class)
    public class FooBar extends HttpServlet

That worked fine. After updating to the latest bndtools from cloudbees, I am getting the following error:

    Class com.seanbright.FooBar is not assignable to specified service javax.servlet.Servlet

Changing the class declaration to the following silences the error:

    @Component(service = Servlet.class)
    public class FooBar extends HttpServlet implements Servlet

But this seems a bit inelegant. Is this a bug in bnd or a user error?

**Comment by seanbright** [comment]
FWIW, this is almost identical to the example in the R6 compendium specification:

![image](https://cloud.githubusercontent.com/assets/114601/11227931/33e781a6-8d57-11e5-8327-f0e55d88ec12.png)

**Comment by bjhargrave** [comment]
Sounds like a bug. @djencks can you look into this?

On Tue, Nov 17, 2015 at 18:03 Sean Bright <notifications@github.com> wrote:

> Before 801dd1 I had code that looked something like this:
>
> @Component(service = Servlet.class)
> public class FooBar extends HttpServlet
> {
>     /* Stuff */
> }
>
> That worked fine. After updating to the latest bndtools from cloudbees, I
> am getting the following error:
>
> Class com.seanbright.FooBar is not assignable to specified service javax.servlet.Servlet
>
> Changing the class declaration to the following silences the error:
>
> public class FooBar extends HttpServlet implements Servlet
>
> But this seems a bit inelegant. Is this a bug in bnd or a user error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bnd/issues/1203>.
>
-- 
-- 
BJ

**Comment by seanbright** [comment]
Confirmed working in latest DEV build
