### ISSUE TITLE
non-workspace gradle plugin seems to invoke the build twice

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1219]
Can't find the erroneous call, but logs don't lie.

**Comment by bjhargrave** [comment]
I think some more details are needed to understand this...

**Comment by rotty3000** [comment]
I'll make a test case if I can in the morning.

**Comment by bjhargrave** [comment]
run the build with `--debug` too to get more details on what is happening

**Comment by rotty3000** [comment]
that didn't show anything of value. Also a test case is tricky to implement easily. However,

if you implement a plugin which emits a sys out, and add it to the bnd settings, you will see the log statement twice.

I'll try to figure out how to do this in the test suite.

**Comment by rotty3000** [comment]
I tried to debug bu the call stacks are identical... see https://gist.github.com/rotty3000/bd6532a143f699a225ca (i.e. this didn't help)

**Comment by bjhargrave** [comment]
> if you implement a plugin which emits a sys out, and add it to the bnd settings, you will see the log statement twice.

This is a bnd analyzer plugin? Can its stdout emission include the current stack trace?

**Comment by rotty3000** [comment]
I can do that..

**Comment by bjhargrave** [comment]
What does com.liferay.ant.bnd.version.VersionVerifierPlugin look like? Perhaps it implements AnalyzerPlugin and VerifierPlugin? So then it is called twice?

**Comment by rotty3000** [comment]
it only implements VerifierPlugin.

**Comment by bjhargrave** [comment]
Can we close this?

**Comment by rotty3000** [comment]
I'll reopen it if I get something more concrete and reproducible, but it still seems to be happening.
