### ISSUE TITLE
local maven repo's incorrectly get url appenended

### ISSUE THREAD

**Issue by david-t-daniel** [bndtools/bnd#1233]
The bnd-indexer-plugin seems to have an issue with local filesystem repositories or I configured something wrong. 

The url gets appened between file: and {/file location} and that doesn't seem correct.  Also I think there is an initial slash missing.  I am not sure how this is handled on windows though.

    <capability namespace="osgi.content">
      <attribute name="osgi.content" value="abefda4326aaccbab58542b216d702a58e4ba80bb69950ea851a8a2be3185be1"/>
      <attribute name="url" value="file:/virtualmachines/development/aardvark/indexer-pom/repo/virtualmachines/development/aardvark/indexer-pom/repoorg/osgi/osgi.configurer.provider/1.0.0.201404171643/osgi.configurer.provider-1.0.0.201404171643.jar"/>
      <attribute name="size" type="Long" value="189056"/>
      <attribute name="mime" value="application/vnd.osgi.bundle"/>
    </capability>

This missing intial slash happens regardless of if I have a slash after repo in my pom.xml or not
        <repository>
            <id>project.local</id>
            <name>project</name>
            <url>file:${project.basedir}/indexer-pom/repo/</url>
        </repository>

**Comment by timothyjward** [comment]
Hi, 

Two things to check.

1. If you delete the cached indexer plugin from your local repository then does that fix the problem? As bnd doesn't use snapshot versions then old development builds can sometimes get used instead.

2. Could you possibly send a copy of the settings.xml from .m2? These will help to make a test case for the problem. My guess is that the missing '/' originates there. 

This is something that I thought had been fixed in master, so if the first option doesn't work then the second would be really helpful!

Thanks,

Tim

**Comment by david-t-daniel** [comment]
I deleted the following three and reran but still got the same issue

[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>biz.aQute.bnd:bnd-indexer-maven-plugin:3.1.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/david/.m2/repository/biz/aQute/bnd/bnd-indexer-maven-plugin/3.1.0/bnd-indexer-maven-plugin-3.1.0.jar
[ERROR] urls[1] = file:/home/david/.m2/repository/biz/aQute/bnd/org.osgi.impl.bundle.repoindex.cli/3.1.0/org.osgi.impl.bundle.repoindex.cli-3.1.0.jar
[ERROR] urls[2] = file:/home/david/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar


My settings dont have much 

<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <server>
      <id>orbis</id>
      <username>maven</username>
      <password>****</password>
    </server> 
</settings>

Here is my repo setup

	<repositories>
		<repository>
			<id>bnd-latest</id>
			<url>https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/maven/target/m2/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
		</repository>
	</repositories>

**Comment by david-t-daniel** [comment]
< settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          http://maven.apache.org/xsd/settings-1.0.0.xsd" >
  < server>
      < id>orbis</ id>
      < username>maven</u sername>
      < password>***</ password>
    < /server > 
</ settings >

**Comment by timothyjward** [comment]
Thank you for the background - I was able to mock up a failing test in the plugin's integration test suite and then fix it in PR #1238. Assuming that there are no Windows gotchas this should make the cut for the 3.1 release.
