### ISSUE TITLE
Baselining should not assume static methods are inherited

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1235]
package a; public class A {}
       package b; public class B extends A {}

Currently, if we add a static method to A:

       package a; public class A { static void foo() {} }

We now get an error in package b because a new method is added to B. Since it is static, we should not have this error

**Comment by fhuberts** [comment]
really?

foo() is still accesible through B

**Comment by bjhargrave** [comment]
> foo() is still accesible through B

Perhaps to the compiler but the generated could would still require a method signature naming A and not B. So from a binary compatibility point of view, foo is not part of B.
