### ISSUE TITLE
Blueprint / Apache Camel  - include referenced Exception packages in calculated imports

### ISSUE THREAD

**Issue by paul-mcculloch** [bndtools/bnd#1258]
Apache Camel  has a capability to catch exceptions that can be defined in a blueprint descriptor.(http://camel.apache.org/exception-clause.html). For example:

``` xml
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0">
    <camelContext xmlns="http://camel.apache.org/schema/blueprint">
        <route>
            <from uri="..."/>

            <onException>
                <exception>org.foo.bar.MyException</exception>
                <redeliveryPolicy .../>
            </onException>

            <to uri="..."/>
        </route>
    </camelContext>
</blueprint>
```

It would be nice if the exception packages were identified as such and included in the calculated imports, in the same way that`<bean class="org.foo.MyClass"/>` elements are handled at present.

**Comment by bjhargrave** [comment]
bnd does not know about Blueprint nor process blueprint xml. It must be some other tool which is processing the blueprint xml.

**Comment by bjhargrave** [comment]
You could try modifying https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/lib/spring/extract.xsl to handle the camel xml and make a PR.

**Comment by paul-mcculloch** [comment]
Thanks for the pointer. I need this to work is in org.apache.felix:maven-bundle-plugin as well, so it looks like I'll have to fix it in two places.

**Comment by bjhargrave** [comment]
maven-bundle-plugin uses bndlib, so if you fix it here, the next release of maven-bundle-plugin can use the updated bndlib.

**Comment by paul-mcculloch** [comment]
maven-bundle-plugin seems to include its own XSLT  which looks to be responsible for this . https://github.com/apache/felix/blob/trunk/tools/maven-bundle-plugin/src/main/resources/org/apache/felix/bundleplugin/blueprint.xsl

**Comment by bjhargrave** [comment]
Well... Perhaps you should ask @cziegeler about it.

**Comment by paul-mcculloch** [comment]
Will do - thanks again.

**Comment by cziegeler** [comment]
That code has actually been added by @gnodet  as part of FELIX-2175.
(I just moved the code base and it seems the history is lost here in git, it's available via svn)

**Comment by gnodet** [comment]
The main reason for using a different xslt is to be able to generate the Import-/Export-Service or Require-/Provide-Capabilities headers.
If bnd is willing to start generating those (for blueprint, spring, scr), we could move some code from the maven-bundle-plugin to bnd.

**Comment by pkriens** [comment]
@gnodet We would be more than pleased to accept a PR for this.
