### ISSUE TITLE
Check R6 spec compliance when processing OSGi component annotations

### ISSUE THREAD

**Issue by oliverlietz** [bndtools/bnd#1266]
e.g. when using `@Reference` on a field which violates R6 spec (not volatile, unsupported type, final) errors should be emitted (see [FELIX-5139](https://issues.apache.org/jira/browse/FELIX-5139))

**Comment by bjhargrave** [comment]
You misused the annotation. If you apply the annotation to a field, then that field will be injected. If you want to use method injection, annotate the bind method and not a field.

Looking at your felix bug, your field declaration has issues and bnd reported them when processing the annotations.

As far as I can see, bnd did everything correctly. I do not see any bnd problem here.

**Comment by oliverlietz** [comment]
The errors are reported by Felix SCR at runtime and **NOT** by bnd at compile time. I suggest to check R6 spec compliance already at compile time by bnd.

**Comment by djencks** [comment]
I think there's a problem in bnd.  For one thing, I think that mentioning bind and unbind methods on a field annotation should be an error.  I think that if you want both field injection and events you should annotate the fields and the bind method.

**Comment by djencks** [comment]
Also, I think bnd should compute the FieldOption as Update, which according to the spec should make the example field work.

**Comment by oliverlietz** [comment]
@cziegeler made a good point why `bind` and `unbind` arguments on a field are useful. Otherwise `bind` and `unbind` arguments are becoming quite useless (not allowed on a field, redundant on a method - except `unbind` not following naming convention).

**Comment by seanbright** [comment]
> Also, I think bnd should compute the FieldOption as Update, which according to the spec should make the example field work.

It already does, here is the generated XML using bnd 3.1.0.REL and @oliverlietz's code example from his Felix issue:

    <reference name="fooServices"
               cardinality="1..n"
               policy="dynamic"
               interface="FooService"
               bind="addFooService"
               unbind="removeFooService"
               field="fooServices"
               field-option="update" />

**Comment by bjhargrave** [comment]
I don't think there is any issue here. Can we close this?
