### ISSUE TITLE
Export-Package=* blows up the bundle

### ISSUE THREAD

**Issue by xtracoder** [bndtools/bnd#1276]
I've got strange behavior with one of my bundles ...

I'm going to create a bundle which both declares it's own APIs plus exports APIs of external libraries - these ones are to be embedded, therefore i'm adding instructions

- `Include-Resource` - with the list of JAR to embed
- `Bundle-ClassPath` - mentions `.` plus above-listed JARs
- `Export-Package=*` - to export all packages in my code and packages in embedded JARs

**What happens ...**
- processing of Bnd-only takes around 1 minute
- additionally to JARs listed in `Include-Resource` instruction bundle also contains plenty of merged packages right into root of the JAR (just like with '@' prepended to Include-Resource) - and size grows from 10MB to 77MB.

It looks like Bnd tries to export packages not only from the JAR's content, but also from all transitive dependencies. Is it wanted behavior or a bug?

**Expected behaviour:**
- packages outside of my code and out of classes explicitly embedded into jar are not listed in 'Export-Package' in JAR's manifest
- no files other than listed explicitly in `Include-Resource` and project's resources and classes are available in generated jar

I've created minimalistic Gradle project to reproduce that issue. Please find it attached. It uses org.dm.gradle bundle plugin v0.7.2, which uses Bnd v3.0.0. But I 've got same behavior with bnd tools just compiled from 'master'.

[bnt-export-all-test.zip](https://github.com/bndtools/bnd/files/67819/bnt-export-all-test.zip)

**Comment by bjhargrave** [comment]
Export-Package=* means export all package include those visible on -buildpath. Which can be a lot of package. You need to be more precise on the list of packages to export. I think what you want is `-exportcontents: *` (but I am not very familiar with that instruction.

**Comment by xtracoder** [comment]
Yes, replacing 
```
    instruction 'Export-Package', '*'
```
with 
```
    instruction '-exportcontents', '*'
```
makes the difference and at first glance seems to be what I need. Thanks for suggestion.

Mentioned side effect of `'Export-Package', '*'` (*include those visible on -buildpath*) is not clear from available docs and really misleading.

**Comment by xtracoder** [comment]
After more usage of given recommendation it appears that `instruction '-exportcontents', '*'` is not sufficient enough - packages from embedded artifacts are exported using version of the bundle, not version of the embedded JARs.

I see that *imported packages are version-tagged correctly*. At the moment I have no idea about how Bnd identifies the version for imports, but I expect same version identification strategy can be used also *for exporting* of packages from embedded JAR.

Am i missing something?

**Comment by xtracoder** [comment]
Ok, I think original problem is resolved - i.e. misunderstanding about how 'Export-Package=*' works internally.

Wrong versioning of the exported package for embedded JARs is still in-place. Is this also 'by design' or  an issue needs to be created for this?

Below is sample `build.gradle` to reproduce the problem - i'm getting in `MANIFEST.MF`
`    Export-Package: org.dom4j;version="0.0.1"` 
instead of 
`    Export-Package: org.dom4j;version="1.6.1"` 

```
project.group = "dummy.test"
project.version = "0.0.1"

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'biz.aQute.bnd:biz.aQute.bnd.gradle:3.1.0'
    }
}

import aQute.bnd.gradle.Bundle
apply plugin: 'biz.aQute.bnd.builder'

repositories {
    jcenter()
}

dependencies {
    compile "dom4j:dom4j:1.6.1" 
}
    
project.configurations.compile.
    resolvedConfiguration.firstLevelModuleDependencies.each { dependency -> 
    dependency.moduleArtifacts.each { artifact ->
        println 'Include-Resource: ' + artifact.file.canonicalPath

        jar {
            manifest {
                attributes 'Include-Resource': artifact.file.canonicalPath,
                           'Bundle-ClassPath': artifact.file.name
            }
        }
    }        
}

jar {
    manifest {
        attributes '-exportcontents': '*;-noimport:=true',
                   '-nouses': 'true'
    }
}

task bundle(type: Bundle) {
    from sourceSets.main.output
}
```

**Comment by xtracoder** [comment]
Moved topic regarding versioning of JAR-exported packages into separate issue - https://github.com/bndtools/bnd/issues/1284. 

Closing that issue because there are no questions left here.
