### ISSUE TITLE
test: ProjectTester assumes full ownership of test report folder

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#1282]
See https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/ProjectTester.java#L81-L83 and https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/ProjectTester.java#L42-L45. ProjectTester assumes it is the only party writing to the test-results folder. This works ok unless a project has both junit tests and OSGi junit tests. The org.osgi.impl.bundle.repoindex.test is one such project. So after running the `test` task which runs the plain junit tests, the `check` task runs and ProjectTester deletes the test output from the `test` task. You can see this when running gradle again since it now must always rerun the `test` task.

```
:org.osgi.impl.bundle.repoindex.test:test
Executing task ':org.osgi.impl.bundle.repoindex.test:test' (up-to-date check took 0.01 secs) due to:
  Output file /Users/hargrave/git/bnd/org.osgi.impl.bundle.repoindex.test/generated/test-reports/TEST-org.example.tests.cli.TestCommandLine.xml has been removed.
  Output file /Users/hargrave/git/bnd/org.osgi.impl.bundle.repoindex.test/generated/test-reports/TEST-org.example.tests.standalone.TestStandaloneLibrary.xml has been removed.
```

I am not sure what the proper answer is here. It would be nice to have junit and OSGi junit output in the same folder.

**Comment by fhuberts** [comment]
Ah that explains what I saw in one of my project!
