### ISSUE TITLE
Superfluous warning in case bnd is only used to generate a fragment with an extension of the manifest only

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#1287]
The following warnings are logged:
```
[WARNING] Bundle a : Classpath is empty. Private-Package and Export-Package can only expand from the classpath when there is one
[WARNING] Bundle a : Unused Private-Package instructions, no such package(s) on the class path: [!*]
[WARNING] Bundle a : The JAR is empty: The instructions for the JAR named a did not cause any content to be included, this is likely wrong
```
when bnd is only used to generate an OSGi fragment containing only a manifest change (i.e. export additional packages but do not export additional classpath).
In the case where bnd is called with the header `Fragment-Host` those warnings should be suppressed.

**Comment by kwin** [comment]
Actually the 2nd warning from above is due to how the maven-bundle-plugin works (see also https://issues.apache.org/jira/browse/FELIX-2991, but at least the first and the third warning should be suppressed.

**Comment by bjhargrave** [comment]
Try -resourceonly: true.

On Mon, Jan 11, 2016 at 18:42 Konrad Windszus <notifications@github.com>
wrote:

> Actually the 2nd warning from above is due to how the maven-bundle-plugin
> works (see also https://issues.apache.org/jira/browse/FELIX-2991, but at
> least the first and the third warning should be suppressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bnd/issues/1287#issuecomment-170629521>.
>
-- 
-- 
BJ

**Comment by JanMosigItemis** [comment]
Is it possible that -resourceonly: true stopped working? I am having the exact same issue and tried adding this instruction to the fragment's bnd file. However, the warning is still there. Fragment does only contain a manifest file which is exactly what I want it to contain. Any thoughts?

**Comment by bjhargrave** [comment]
I don't think it suddenly stopped working :-)

Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by JanMosigItemis** [comment]
Sure: https://github.com/JanMosigItemis/resourceonly

**Comment by bjhargrave** [comment]
Thanks for the repo. I think you are misunderstanding `-resourceonly: true`. This is for the case where the bundle does not contain any classes and only contains resource. In your case, the fragment contains no classes and no resources (manifest is added after the no resources check). So `-resourceonly: true` still causes a warning since the fragment is empty (except for a manifest). 

You should instead use `-fixupmessages: The JAR is empty` instead of `-resourceonly: true`.

**Comment by JanMosigItemis** [comment]
Ok thank you for pointing that out. However it is a bit awkward though to suppress the warning like this. Imo this use case (Fragment contains manifest only) is perfectly valid and should not yield a warning. Is there any chance to change this behavior in the future?

**Comment by bjhargrave** [comment]
It is a very atypical bundle to build. There is nothing wrong with it, per se, but it is not normally the case to build something which has only a manifest. Think of using `-fixupmessages` just like you might use `@SuppressWarning` in your source code. Bnd is warning you of a potentially bad bundle. But you know this is correct in your use case, so you suppress the warning.

**Comment by kwin** [comment]
I would also say that a bundle just extending the manifest (as fragment) is not that unusual. Just think about some bundles from a 3rd party provider. In case you want to access classes which are not exported, you must extend the manifest. The only way to do that is to supply a bundle fragment to the 3rd party bundle exporting that additional package. Those fragments only contain a manifest.

**Comment by JanMosigItemis** [comment]
Supressing the warning does come at a price: You cannot distinguish situations that you know to be correct from those that are not. Imagine a situation where a former "empty" fragment is changed so that it actually contains e. g. a resource but you forgot to add an appropriate statement to the bnd file. I would like to be notified about that but this is not going to happen. Keep in mind that others may put in the suppression without your knowledge, so you will definitely miss that one.

We are using this kind of "empty" fragment setup to be able to have a test bundle next to the host bundle. The test bundle contains OSGi integration tests that need to access internal classes of the host in order to be functional. From my point of view, this setup is not that atypical, isn't it?

**Comment by wszeboreq** [comment]
Hi,

I'm using bnd-4.2.0 via Gradle plugin, to build resource-only bundle fragments. I'm using '-resourceonly', but I still get the warnings:

warning: Host com.xxx.yyy= for this fragment/require bundle cannot be found on the classpath
warning: Host com.xxx.yyy= for this fragment cannot be found on the classpath

The related Gradle code:

`
  jar {
        bnd('Fragment-Host': project.name),
            'Bundle-SymbolicName': project.name + '.fragment',
            '-resourceonly': 'true')

        classifier 'fragment'
    }
`

Am doing something wrong, or '-resourceonly' does not have effect on the warning in this use case?

**Comment by bjhargrave** [comment]
You are making a fragment. Bnd looks on your class path to verify the host. The warning states this. So you can elide the warning with `-fixupmessages` or you can put the host bundle on the classpath so Bnd can see it.

**Comment by wszeboreq** [comment]
But does building the resource-only fragment require the host to be on classpath? I have the feeling that for resource-only fragments verifying the host is not necessary. One may build a resource-only fragment for bundle he has no access to at the time of the build.

**Comment by bjhargrave** [comment]
Bnd validates the Fragmen-Host header against the host. It is orthogonal to whether the bundle is resourceonly.

You can of course build a fragment without having the host bundle available for Bnd to verify the Fragment-Host directive. But then you get the warning :-). So use `-fixupmessages` to elide the warning (Much like you might use `@SuppressWarnings` in your java code to tell javac you know what you are doing.)

**Comment by wszeboreq** [comment]
OK, I think now I understand. I will play with this `-fixupmessages`, hope it may be used selectively only for this precise kind of warning.

Thank you for your help.
