### ISSUE TITLE
Create an indexer task for Gradle

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#1288]
Bnd users who also use maven can use the bnd-indexer-maven-plugin to produce an OSGi index for a set of maven dependencies. There is no equivalent support from bnd for Gradle users.

This task encompasses the work needed to add similar indexing support to the bnd gradle plugin. The indexing task should create an index using the dependencies of the build project, and the build output for the project is the XML serialized index.

**Comment by bjhargrave** [comment]
This may not be possible. I started work on this using a gradle configuration to hold the set of artifacts to index.

For example:

```groovy
repositories {
    mavenCentral()
}
configurations {
  index
}
dependencies {
    index 'commons-codec:commons-codec:1.5'
    index 'commons-lang:commons-lang:2.6'
}
```
Then the index task would be configured to index the dependencies in the specified configuration. This works great until I need to determine the remote URL for the dependency. There does not appear to be any way to determine the source URL for a dependency in the gradle API.

Here is my full test gradle script.

```groovy
apply plugin: 'java'
repositories {
    mavenCentral()
}
configurations {
  index
}
dependencies {
    index 'commons-codec:commons-codec:1.5'
    index 'commons-lang:commons-lang:2.6'
}
task('index') << {
  def index = configurations.index
    def resolved = index.resolve()
    println "Resolved files"
    resolved.each { file ->
      println "${file}"
    }
    println "allDependencies"
    index.allDependencies.each { dep ->
      println "${dep}"
      println "${dep instanceof ModuleDependency}"
      if (dep instanceof ModuleDependency) {
        println "${dep.artifacts.size()}"
        dep.artifacts.each { artifact ->
          println "${artifact.name} ${artifact.url}"
        }
      }
    }
}
```

Running this produces:
```:index
Resolved files
/Users/hargrave/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.5/cf993e250ff71804754ec2734a16f23c0be99f70/commons-codec-1.5.jar
/Users/hargrave/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.6/ce1edb914c94ebc388f086c6827e8bdeec71ac2/commons-lang-2.6.jar
allDependencies
DefaultExternalModuleDependency{group='commons-codec', name='commons-codec', version='1.5', configuration='default'}
true
0
DefaultExternalModuleDependency{group='commons-lang', name='commons-lang', version='2.6', configuration='default'}
true
0

BUILD SUCCESSFUL
```

**Comment by bjhargrave** [comment]
I posed a [question](https://discuss.gradle.org/t/how-do-you-find-the-source-url-for-a-dependency/13885) in the Gradle forum to see if there is any solution.

**Comment by bjhargrave** [comment]
Looks like this cannot be done in gradle: https://discuss.gradle.org/t/how-do-you-find-the-source-url-for-a-dependency/13885/2

    Unfortunately, this information is not exposed by Gradle.

**Comment by sebersole** [comment]
Mind if I ask why you feel you need access to the repo URL for the artifacts?  Specifically why wouldn't the local artifacts + ResolutionResult provide enough info?

**Comment by bjhargrave** [comment]
> Mind if I ask why you feel you need access to the repo URL for the artifacts? Specifically why wouldn't the local artifacts + ResolutionResult provide enough info?

To generate an index which works on any system by referring to the source URL of the indexed items. To refer only to local files in the gradle download cache is not terribly useful. The index entry for a bundle needs to have an osgi.content capability which points to the location to the bundle can be obtained such as a URL in Maven Central or JCenter.

**Comment by bjhargrave** [comment]
FYI, I created an Index task type for Gradle that can perform local index generation only. See 50fd7ee4d3f61e11422d5d6278e3687fc4ece20b
