### ISSUE TITLE
Project reference not updated

### ISSUE THREAD

**Issue by estani** [bndtools/bnd#1289]
Eclipese Version: Mars.1 Release (4.5.1)
bnd Version: 3.1.0.201512181xxx

If in eclipse both projects A and B exists and A imports B bundle as latest, both projects seem to be properly linked (i.e. A imports B as project and uses B generated/B.jar for this)

However if project B is closed, project A cannot be built anymore since eclipse is missing the dependency. bnd won't update the class path even if bndbuild is set to continue building after errors. 

After trying all combinations of cleaning up the projects, reimporting, restarting, removing the directory "generated" and so on I still cannot force bndbuilder to change the classpath.

I think the problem is that the bundles are still listed under Workspace in the repositories view. Refreshing the repositories/restarting doesn't help. I couldn't find a way to remove these entries.

**Comment by bjhargrave** [comment]
bnd operates on projects in the file system. bndtools (the Eclipse plugins for bnd) understands Eclipse projects and uses bnd to build the bundles. But closing a project in Eclipse does not prevent bnd from knowing about it on the file system. So when project A depends upon project B, the dependency is know the bnd level via information in the file system. That is, the bnd.bnd file for project A will express a dependency on project B. 

I you want to remove project A's dependency on project B, you need to edit project A's bnd.bnd file. Just closing project B in Eclipse does not thing to remove a dependency.

**Comment by estani** [comment]
I still se this as a bug, but I didn't realize the bndtool project is somewhere else. I'll comment it there.
