### ISSUE TITLE
Maven plugin should support alternative bnd.bnd locations

### ISSUE THREAD

**Issue by paulbakker** [bndtools/bnd#1293]
I'm helping the Vert.x team to osgi-ify their modules using the bnd maven plugin. They *really* want the bnd.bnd file in an alternative location though, so the plugin should support this. PR on the way.

**Comment by bjhargrave** [comment]
Is this issue still relevant now?

**Comment by paulbakker** [comment]
I'm ok with closing it, you convinced me this is too much effort.
