### ISSUE TITLE
Baselining "cross compiler" fails when using switch on an enum

### ISSUE THREAD

**Issue by brampouwelse** [bndtools/bnd#1296]
Baselining bundles that were built using different compilers has improved a lot with #794 fixed but I just ran into yet another compiler difference ... When using a switch statement on an enum javac generates an additional class file [1] which ecj doesn't. 

For example for a class like: 

``` java
public class Example {

    public enum MyEnum { ONE, TWO }

    public static void main(String[] args) {
        
        MyEnum enumTest = MyEnum.valueOf(args[0]);
        switch (enumTest) {
            case ONE:
                System.out.println("Selected option one");
                break;
            case TWO:
                System.out.println("Selected option two");
                break;
        }
        
    }
}

```

javac generates the additional Example$1.class

Would be nice if the bnd differ could ignore this compiler difference  

[1] http://stackoverflow.com/questions/1834632/java-enum-and-additional-class-files

**Comment by bjhargrave** [comment]
Does the synthetic class have [`ACC_SYNTHETIC`](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.1-200-E.1) set? I think baselining should ignore all classes with `ACC_SYNTHETIC` set.

**Comment by brampouwelse** [comment]
> Does the synthetic class have ACC_SYNTHETIC set? 

Is there an easy way to check that? I've tried reading the value with Apache BCEL this returns 0x1020  which is not in the table. 


``` java 
ClassParser classParser = new ClassParser("com.example.baseline.jar",
            "com/example/baseline/Example$1.class");
JavaClass javaClass = classParser.parse();
System.out.println(Integer.toHexString(javaClass.getAccessFlags()));
``` 
The example class file: 
[Example$1.class.zip](https://github.com/bndtools/bnd/files/105499/Example.1.class.zip)

> I think baselining should ignore all classes with ACC_SYNTHETIC set.

Do you mean the current bnd version does this?

**Comment by bjhargrave** [comment]
> Is there an easy way to check that? I've tried reading the value with Apache BCEL this returns 0x1020 which is not in the table.

0x1020 is 0x1000 | 0x0020 = ACC_SYNTHETIC | ACC_SUPER

So it is marked as synthetic.

```
$ javap -v Example\$1.class
Classfile /Users/hargrave/Downloads/Example$1.class
  Last modified Jan 26, 2016; size 735 bytes
  MD5 checksum 64af44def51e462fab2a59349878ef72
  Compiled from "Example.java"
class com.example.baseline.Example$1
  minor version: 0
  major version: 52
  flags: ACC_SUPER, ACC_SYNTHETIC
```

> Do you mean the current bnd version does this?

I don't know. But if it does not, it should be changed to ignore synthetic classes (and synthetic methods).

**Comment by brampouwelse** [comment]
It can be so easy if you know the tools ;) 

> I don't know. But if it does not, it should be changed to ignore synthetic classes (and synthetic methods).

Had a quick look DiffPluginImpl does two checks on Java content one compares methods beteween the bundles that are diffed  (using JavaElement) this check works ok even when one bundle is built using javac and the other using ecj. But there is also a resourcesElement check [1] this fails as the Example$1.class file is not there in the bundle that's built using ecj. 

As a workaround I've added ```-diffignore: *$1.class``` to build.bnd that seems to solve the issue. 

1: https://github.com/pkriens/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/differ/DiffPluginImpl.java#L147

**Comment by bjhargrave** [comment]
I am not sure how the baselining code handle anonymous inner classes. They should all probably be ignored since they can't be part of the API (they are anonymous). This would then also cover the case of this issue.

**Comment by brampouwelse** [comment]
@pkriens I don't think your change will fix the issue, the problem is in the resource diff the additional class file is recognized as an added / removed resource.

**Comment by brampouwelse** [comment]
Attached a zip with two versions of the same code build with different compilers

Output from bnd diff on the commandline: 
```
➜  bnd-31  java -jar ~/Downloads/biz.aQute.bnd-3.1.0.jar diff com.example.baseline.ecj.jar com.example.baseline.javac.jar
CHANGED    RESOURCES  <resources>
 REMOVED    RESOURCE   com/example/baseline/Example$1.class
```


[baselinetest.zip](https://github.com/bndtools/bnd/files/122010/baselinetest.zip)

**Comment by brampouwelse** [comment]
@pkriens Just tested the bnd 3.2.0 snapshot from CloudBees in the project in which I had this issue, the fix seems to work. Thanks!

```
BUILD SUCCESSFUL
Total time: 32.352 secs
```
(same build fails with a baselining error when using bnd 3.1.0)

**Comment by pkriens** [comment]
Once you have a test case life is sooo easy ... :-) Thanks.
