### ISSUE TITLE
@Designate annotation only processed when -dsannotations explicitly set

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1315]
We made `-dsannotations: *` the default for processing of the `@Component` annotations. But the same default is not used for deciding whether to process the `@Designate` annotations. They are only processed when the `-dsannotations` header is *explicitly* specified in the bnd file.

**Comment by njbartlett** [comment]
The solution to the problem is clearly to change line 70 of `MetatypeAnnotations` from:

    analyzer.getProperty(Constants.DSANNOTATIONS)

to
    analyzer.getProperty(Constants.DSANNOTATIONS, "*")

However this causes many test cases to break, so it's not such a trivial change unfortunately.

**Comment by bjhargrave** [comment]
@Designate is a metatype annotation: <https://osgi.org/javadoc/r6/cmpn/org/osgi/service/metatype/annotations/Designate.html>. So it should be processed by `-metatypeannotations`.

**Comment by njbartlett** [comment]
Yes I believe you are right.
