### ISSUE TITLE
Enhance "release" command optionally release transitive deps from the workspace

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1331]
It would be nice to be able to generate a repository quickly from the Workspace by executing the `release` command on a single project and all of the transitive dependencies -- as defined by `-buildpath` and `-dependson` -- are released also.

**Comment by bjhargrave** [comment]
The gradle plugin supports a releaseNeeded task which will release the
project and all dependent projects.

On Wed, Feb 24, 2016 at 7:04 AM Neil Bartlett <notifications@github.com>
wrote:

> It would be nice to be able to generate a repository quickly from the
> Workspace by executing the release command on a single project and all of
> the transitive dependencies -- as defined by -buildpath and -dependson --
> are released also.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bnd/issues/1331>.
>
-- 
-- 
BJ

**Comment by pkriens** [comment]
This is so trivial to do from the bnd driver (Gradle, Bndtools) that I wonder if this should be done in bnd? In Bndtools you could create separate monitors for each project so that would make it more clear?

**Comment by pkriens** [comment]
Maybe we should also integrate the release window?
