### ISSUE TITLE
bnd-maven-plugin no longer supports friendly OSGi versioning

### ISSUE THREAD

**Issue by fakeh** [bndtools/bnd#1337]
Hi,

A previously resolved issue, https://github.com/bndtools/bnd/issues/1068 (Bnd-maven-plugin support for OSGi friendly versioning) has been broken in 3.2. I suspect the relevant change is: https://github.com/bndtools/bnd/commit/23969d088887bb8178913b011f85b9ac4399ef17.

Best, Dan.

**Comment by bjhargrave** [comment]
I don't understand the problem here. Can you please provide an example of a version that no longer works properly?

**Comment by fakeh** [comment]
The same as in the previous issue no longer works, e.g. 0.0.1.BUILD-SNAPSHOT. 0.0.1.SNAPSHOT works fine. Both work in 3.1.

**Comment by bjhargrave** [comment]
> 0.0.1.BUILD-SNAPSHOT

Works just fine for me. I did:

```
<version>0.0.1.BUILD-SNAPSHOT</version>
```
in pom.xml. The produced a bundle with 
```
Bundle-Version: 0.0.1.BUILD-SNAPSHOT
```
in its manifest.

**Comment by bjhargrave** [comment]
You should read <https://github.com/bndtools/bnd/wiki/Changes-in-3.2.0#bnd-maven-plugin> which has information about the changes to SNAPSHOT handling in the qualifier portion of the version.

**Comment by fakeh** [comment]
In order to play nicely with other tools, the maven version needs already to be OSGi friendly, hence 0.0.1-SNAPSHOT is not suitable. Since Maven convention is to recognise versions with '-SNAPSHOT' appearances anywhere in the qualifier, one way to allow for this usage is for the .endsWith in http://bnd.bndtools.org/instructions/snapshot.html is changed to something which allows for the possibility that it's not the only component of the qualifier.
Thanks, Dan.

**Comment by bjhargrave** [comment]
I fail to understand the issue here. You are not explaining your problem well. 

> In order to play nicely with other tools, the maven version needs already to be OSGi friendly, hence 0.0.1-SNAPSHOT is not suitable. 

OK, then use 0.0.1.SNAPSHOT. It is very OSGi friendly. Also what do you mean by OSGi "friendly"? Either a version is valid for OSGi or invalid.

> Since Maven convention is to recognise versions with '-SNAPSHOT' appearances anywhere in the qualifier, one way to allow for this usage is for the .endsWith in http://bnd.bndtools.org/instructions/snapshot.html is changed to something which allows for the possibility that it's not the only component of the qualifier.

Why? If you want to use ${tstamp} in the Bundle-Version header, then the Bundle-Version is different than the jar/pom version. If you want them to be the same, then you can do that too. 

Please provide a more detailed explanation of what you want to do but cannot do. So far I don't not understand your issue.

**Comment by fakeh** [comment]
Maven recognises a snapshot version as ending in 'SNAPSHOT'. I'm using another tool which mistakenly requires -SNAPSHOT, and another which requires the version to be already OSGi formatted. Both of these led me to use 'BUILD-SNAPSHOT' as my versioning. BND previously worked with this scheme but now requires 'SNAPSHOT' as the qualifier, according to my testing here and the code at http://bnd.bndtools.org/instructions/snapshot.html. If BND could be changed to recognised SNAPSHOT qualifiers the same way as Maven does (i.e. just endsWith, without the '.'), it would help my case and align the snapshot handling with that of Maven.

As an aside, using e.g. 0.0.1.SNAPSHOT (the only way to use an OSGi format and get the benefits of BND's timestamp?) as a maven version generates warnings:
[WARNING] 'version' uses an unsupported snapshot version format, should be '*-SNAPSHOT' instead. @ line 9, column 12

**Comment by bjhargrave** [comment]
> As an aside, using e.g. 0.0.1.SNAPSHOT (the only way to use an OSGi format and get the benefits of BND's timestamp?) as a maven version generates warnings:
> [WARNING] 'version' uses an unsupported snapshot version format, should be '*-SNAPSHOT' instead. @ line 9, column 12.

No, You can use 0.0.1-SNAPSHOT to get the "free" replace SNAPSHOT with ${tstamp} behavior of bnd-maven-plugin. As I mentioned above in my example.

**Comment by bjhargrave** [comment]
> If BND could be changed to recognised SNAPSHOT qualifiers the same way as Maven does (i.e. just endsWith, without the '.'), it would help my case and align the snapshot handling with that of Maven.

I'll take a look at that.
