### ISSUE TITLE
Exception looking at annotation type to lifecycle method

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1339]
The following error message appears as an Eclipse problem marker when I use a DS 1.2+ annotation configuration type:

    org.example: Exception looking at annotation type to lifecycle method with descriptor (Lorg/example/Config;)V,  type java.lang.String

The error only happens on String or String[] attributes with default value. Other attribute types such as ints, booleans, enums etc are processed correctly. String attributes *without* a default are also fine.

Example code:

	package org.example;
	
	import org.osgi.service.component.annotations.Activate;
	import org.osgi.service.component.annotations.Component;
	import org.osgi.service.metatype.annotations.ObjectClassDefinition;
	
	enum Colour { Blue, Green }; 
	
	@ObjectClassDefinition
	@interface Config {
		int port() default 8080;
		boolean boolAttrib() default true;
		Colour colour() default Colour.Blue;
		Class<?> clazz() default Object.class;
		int[] ports() default {};
		String host() default "0.0.0.0";
	}
	
	@Component
	public class ExampleComponent {
		@Activate
		void activate(Config config) {}
	}

Affects bndlib 3.2.0.2016.02252054

**Comment by njbartlett** [comment]
The above problem marker is attached to the component class. I noticed there is a slightly different problem marker attached to the bnd.bnd:

    com.paremus.packager.pkg.spark.master: Exception looking at annotation type default for element with descriptor host,  type java.lang.String

**Comment by djencks** [comment]
I can’t imagine how this could result in a problem, let alone this problem, but are you compiling your classes with the ds 1.3 (R6) annotations or the 1.2 (R5) annotations?  Is there any way to extract a stack trace from eclipse?

david jencks

**Comment by njbartlett** [comment]
Aha I did have the aQute annotations on my build classpath. Removing it gets rid of the error.

We still need to fix the error reporting here, it's appalling. I will try to get a stack trace, it will involve debugging in the Eclipse building.

**Comment by njbartlett** [comment]
In fact I have been able to reproduce this error on a project that does NOT have aQute annotations visible anywhere on my buildpath. So this error is much worse than I originally believed.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by bjhargrave** [comment]
Please reopen when there is a small github repo to reproduce the problem.
