### ISSUE TITLE
Add support for new OSGi Bundle Annotations (RFC 220)

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#1343]
OSGi is working on new bundle annotations which require support in bnd. See https://github.com/osgi/design/tree/master/rfcs/rfc0220.

We need to add support for these annotations to bnd.

**Comment by cschneider** [comment]
I am also interested in this feature. My main reason is that the current bnd annotations are not repeatable.
Is anyone working on this?

**Comment by bjhargrave** [comment]
> Is anyone working on this?

Not at the moment. This is a placeholder for the work.

**Comment by cschneider** [comment]
Would it make sense that I take I a look at the current annotations and try to add support for repeatable annotations?

**Comment by bjhargrave** [comment]
By current annotations you mean the Bnd annotations? I would rather put the effort into supporting the OSGi standardized annotations.

**Comment by cschneider** [comment]
I guess that the standard annotations will work very similar to the bnd ones. Can you give me some pointers where the current bnd annotations are implemented and where the new support should reside?

**Comment by timothyjward** [comment]
So far the following standard bundle annotation have *some* support:

- `@Requirement`
- `@Capability`
- `@Export`

Things known not to work:

- `@Header` annotations are parsed and added to the Analyzer, but don't show up in the manifest.
- The `substitition` attribute of the `@Export` annotation is not processed
- The `@Attribute` and `@Directive` annotations are not processed

**Comment by bjhargrave** [comment]
> The substitition attribute of the @Export annotation is not processed

I have the change for this in progress. Just need to write more tests before I make a PR.

**Comment by bjhargrave** [comment]
The bundle annotations support appears complete.
