### ISSUE TITLE
support globbing during includeresource's buildpath reference resolution

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1352]
BND supports a very nice ability to resolve jar files referred to in the include resource directive from the classpath (build path).

e.g.
```
-buildpath:\
    /some/dir/somelib-3.0.6.jar;version=file

-includeresource: @somelib-3.0.6.jar
```
This is a wonderful feature.

But it causes duplication of volatile information, in this case the version.

It would be really nice if this mechanism could resolve the same artifact through globbing, like so:

`-includeresource: @somelib-*.jar` OR
`-includeresource: @somelib*.jar`

**Comment by rotty3000** [comment]
To deal with those rare possibilities of collision in buildpath naming I'd be good to just use the first match.

**Comment by bjhargrave** [comment]
Why not solve this by putting `somelib-3.0.6` in a variable and using that in both places since even the file name is duplicative information.

```
somefile:  /some/dir/somelib-3.0.6.jar
-buildpath:\
   ${somefile};version=file

-includeresource: @${somefile}
```

**Comment by rotty3000** [comment]
The lib here is actually in a build.gradle file.

I just used the build path directive to show that it was coming from there.

And so the lib + version are referenced in two places.

**Comment by bjhargrave** [comment]
> The lib here is actually in a build.gradle file. I just used the build path directive to show that it was coming from there.

I am not sure I understand. How does the bnd file know about the lib file path then? 

> And so the lib + version are referenced in two places.

So, variables are great for that!
