### ISSUE TITLE
Allow specifying necessary Bnd plugins within annotation

### ISSUE THREAD

**Issue by balazs-zsoldos** [bndtools/bnd#1362]
### Story

It is a great thing that I can annotate my annotations with @ProvideCapability and @RequireCapability. This works in some cases, but sometimes people will need more special behavior.

What about having a new annotation like @BndPlugin. This annotation could annotate other annotations, like the @ProvideCapability can annotate other annotations.

E.g.:

Imagine that you have an annotation: @MyAnnotation

You would define your annotation in the following way:

@BndPlugin(foo.bar.MyBndPlugin)
public @interface MyAnnotation {
}

At the moment, I can define annotations and plugins that will handle them. The issue is that if someone forgets to add the plugin in his/her project, nothing will fail but the resulting Jar will be incomplete.

With this additional annotation Bnd could fail if the necessary plugin is not available during compilation time.
### Additional note

I would not only allow specifying the necessity of Bnd plugins on annotations, but on every type. The @BndPlugin annotation would force running that plugin as if it was defined with the -plugin switch.

**Comment by pkriens** [comment]
Could you make a PR?

**Comment by balazs-zsoldos** [comment]
@pkriens  Probably, but I need some advice. I see that there is already an @BndPlugin annotation, but I am not sure what it is for. I see that all classes are annotated that implement LifecyclePlugin, but none of the classes that implement Analyzer plugin. Shall I create a new annotation like @RequireBndPlugin? It would give the feeling that an annotation needs a plugin that is annotated with @BndPlugin... The current concept with @BndPlugin is not clear to me so I cannot recommend new names in my patch.

**Comment by pkriens** [comment]
The @BndPlugin was giving a name to a plugin. So we do need a @RequireBndPlugin that can annotate an annotation. It can then have as a parameter the name of a @BndPlugin?

**Comment by balazs-zsoldos** [comment]
@pkriens Thanks for the info! I will have a look if I can create a PR, but I need a couple of weeks before I can start.
