### ISSUE TITLE
Allow to include test resources

### ISSUE THREAD

**Issue by estani** [bndtools/bnd#1363]
similar to the `src` command ([#520](https://github.com/bndtools/bnd/issues/520)) would be useful to have a `testsrc` or `testresource` option to merely copy files to the target directory (e.g. bin_test) to be accessible on unit tests.

Usecase is to copy files required for unit testing which should not be added to the bundle.

**Comment by bjhargrave** [comment]
bnd does not copy the `src` folder contents to `bin`. The compiler will compile the java source files to class files in `bin`. If you using Eclipse, its compiler will copy the non-java source files to `bin`. The gradle plugin will also do this by [configuring the resource folder to be the src folder](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L104).

This same behavior is done for `test` ([default name for test source](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/defaults.bnd#L4-L5)) to `bin_test`.

So I am not sure what else needs to be done here.

**Comment by estani** [comment]
Sorry it took me a while to respond. I think then my example was not good at all.

The problem is, we need to add test resources to be used with unit tests. These should not be packed in the resulting jar but must be accessible from the classpath. Hence we need to add them to the directories included in the classpath (or maybe extend the classpath to include those directories?). Is this possible?

example:
`/`
`- src/...`
`- test/.../SomeTest.java`
`- test_resources/.../test.json`

should result in:
`/bin_test/.../SomeTest.class`
`/bin_test/.../test.json`

So that `SomeTest` is able to find `test.json`.

The proposal was to add a flag to the bnd.bnd so that resources will be copied to the test directory (and not the bin one which will en in the jar file).

**Comment by bjhargrave** [comment]
If you put resources in the `test` folder, they will be copied to the `bin_test` folder by Eclipse and the bnd gradle plugin (as I mentioned above.)

**Comment by swimmesberger** [comment]
Just wanted to leave a note here that it would be very convenient (and consistent) to be able to define multiple test:dir1,dir2,dir3 directories as we can do with src:dir1,dir2,dir3

I experienced that many developers coming from gradle have following setup in mind:
- src/main/java
- src/main/resources
- src/test/java
- src/test/resources

So they try to follow the same structure in bnd and encounter the "src" property in bnd files which allows multiple directories. They will try to do the same structuring in a bnd bundle which will result in following bnd instructions:
src: src,resources
test: test,test_resources

With these settings what bnd does when getTestSrc() is called it refers to a folder called "test,test_resources" not to multiple folders "src" and "resources". This seems misleading and is unexpected for beginners.
The workaround is simple - simply use a single test directory and put the resources there but still coming from a gradle project and seeing the src property might lead to unexpected behavior.

It propose to simply support multiple folders like bnd does with the src property.

Relevant links:
getSourcePath() method
https://github.com/bndtools/bnd/blob/3f2634a5430e457819e9d4519bdaaee5ea5509f6/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L994
getTestSrc() method
https://github.com/bndtools/bnd/blob/3f2634a5430e457819e9d4519bdaaee5ea5509f6/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L502
Issue for multiple src directories
https://github.com/bndtools/bnd/issues/520
Commit for multiple src directories
https://github.com/bndtools/bnd/commit/b5822a57e7e9e0b0b88b51c2c0ae63c29b1587d3
Gradle usage of getSourcePath()/getTestSrc():
https://github.com/bndtools/bnd/blob/3f2634a5430e457819e9d4519bdaaee5ea5509f6/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L129
Issue discussing separat resource directory properties
https://github.com/bndtools/bnd/issues/1466
