### ISSUE TITLE
Duplicate Entries of Provide-Capability Manifest Header

### ISSUE THREAD

**Issue by sameera-jayasoma** [bndtools/bnd#1364]
BND Version 3.0
Java Version 1.8

This issue is related to [https://github.com/bndtools/bndtools/issues/1300](https://github.com/bndtools/bndtools/issues/1300).

I tried putting the following to the bnd instructions.

```
Provide-Capability: osgi.service;effective:=active;objectClass="org.wso2
 .carbon.kernel.startupresolver.RequiredCapabilityListener";capability-n
 ame="org.wso2.carbon.sample.deployer.mgt.Deployer";component-key=carbon
```
But in the generated manifest I can see following entries. Looks like BND has put the instruction specified by me as well as the auto generated header. Is it possible to avoid this duplication?

```
Provide-Capability: osgi.service;effective:=active;objectClass="org.wso2
 .carbon.kernel.startupresolver.RequiredCapabilityListener";capability-n
 ame="org.wso2.carbon.sample.deployer.mgt.Deployer";component-key=carbon

Provide-Capability: osgi.service;objectClass:List<String>="org.wso2.carb
 on.kernel.startupresolver.RequiredCapabilityListener"
```
Thanks,
Sameera.

**Comment by bjhargrave** [comment]
Can you please provide some more details such as a small github repo which demonstrates the problem so we can investigate?

I see on bndtools/bndtools#1300 that @pkriens looked at the example file you provided but did not find a duplicate header.

You may also want to try bnd 3.1 which is the latest released version.

**Comment by pkriens** [comment]
We need a way to shut off automatic Provide/Require clauses.
