### ISSUE TITLE
Use SHA-256 in JPM index

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1367]
This is for discussion, as I'm prepared to do the implementation.

OSGi standard indexes use SHA-256 for content hashes (don't blame me...) and we added support for the syntax `version=hash; hash=<xxxxx...>` in bnd 3.1. Unfortunately JPM uses MD5 and SHA-1 but not SHA-256.

I propose adding SHA-256 as an extra optional field in the JSON index file, retaining the MD5 and SHA1 for backwards compatibility. In a future version we can think about removing those.

**Comment by pkriens** [comment]
I am ok with this, lets work on this.

**Comment by bjhargrave** [comment]
Since we are removing JPM support, I think we can close this.

**Comment by bjhargrave** [comment]
Closing since we removed JPM from Bnd 4.0.
