### ISSUE TITLE
README in maven folder does not reference biz.aQute.bnd.maven folder and vice versa

### ISSUE THREAD

**Issue by paulvi** [bndtools/bnd#1383]
README in maven folder does not reference biz.aQute.bnd.maven folder and vice versa

It is confusing to have 2 folders for maven

there should be README in both #1382 or move into one folder

**Comment by bjhargrave** [comment]
`biz.aQute.bnd.maven` has been removed from the repo. It was something temporary while Peter worked on the maven repo support.
