### ISSUE TITLE
BndBuilder - NullPointerException for empty project

### ISSUE THREAD

**Issue by paulvi** [bndtools/bnd#1387]
BndBuilder - NullPointerException for empty project 

```
D:\Workspaces\STS-372\OSGiBuildExamples\GradleJavaProject>gradle build
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jar'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.09 secs
```

The same environment as in #1386 bnd v3.1 , Gradle 2.12, Java 1.8.0_74, on Windows 7

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bnd/commit/2a2ee694886611c022ca8927b04063c9253cc522 in bnd 3.2.

**Comment by bjhargrave** [comment]
Actually, this is a slightly different issue.

**Comment by paulvi** [comment]
oops, the "sources" are here https://github.com/paulvi/OSGiBuildExamples/tree/master/GradleJavaProjectBndBuilder
