### ISSUE TITLE
What version of biz.aQute.bndlib is used in different plugins?

### ISSUE THREAD

**Issue by paulvi** [bndtools/bnd#1390]
I have just tried to `mvn install` for code of older examples <https://github.com/bndtools/bnd/tree/bnd-maven-plugin-2.4.1/bnd-maven-plugin-examples>

and got many versions of bndlib in m2 repo

**Comment by bjhargrave** [comment]
The build uses the version of bndlib built in the build in the gradle and maven plugins also built in the repo.

**Comment by paulvi** [comment]
@bjhargrave Do you mean all things should be 3.2 in master and 3.1 released?

**Comment by bjhargrave** [comment]
I mean that everything in the bnd repo is the same version: bndlib, gradle plugins, maven plugins. The master branch is now building 3.2 for eventual release.

**Comment by paulvi** [comment]
yes, I see this now.
