### ISSUE TITLE
Alternate index plugin or plugin mode to create a local index

### ISSUE THREAD

**Issue by cschneider** [bndtools/bnd#1391]
I created an alternate index plugin to make my example work reliably.
See
https://github.com/cschneider/osgi-maven-plugins/tree/master/osgi-index-maven-plugin

The plugin has a completely different scope from the indexer plugin from Tim. It is meant to be placed in the maven project structure of a bndtools maven project. The index is created only locally in the target folder. Also all the dependencies in the pom are copied to the target folder. This allows the path to the index in the bndrun file as well as the paths to the individual jars in the index.xml to be relative. 

The disadvantage is that such an index can not be pushed to a maven repo. It also consumes more space in the target dir as the jars have to be copied there. 

The big advantage though is that the created indexes work well with snapshots as well as releases. They also respect the proxy structure or company maven repos as all access to maven resources is done by maven code. 

At least from my side it made the job of creating a full stack demo application a lot easier than with the current index plugin. See here for a full example: https://github.com/cschneider/bndtools-tutorials/tree/master/tasklist-ds

So I think it makes sense to add this plugin in addition to the indexer plugin. Alternatively we could add it as a second mojo in the current indexer plugin.

**Comment by bjhargrave** [comment]
We are trying to close down 3.2 now and so we defer this until after 3.2.

**Comment by cschneider** [comment]
I found that the bnd-indexer-plugin works fine when using localUrls REQUIRE.This is good enough for me so I close this.
