### ISSUE TITLE
Do you need Chinese users?

### ISSUE THREAD

**Issue by paulvi** [bndtools/bnd#1393]
Started in https://github.com/bndtools/bndtools/issues/1330 and https://github.com/bndtools/bndtools/issues/1329

@bjhargrave Google is absent in China completely, and not all are using VPN (It is very slow and unreliable nevertheless, because servers are not near)

Please consider more options in https://github.com/bndtools/bnd#feedback.

UPDATE  2016-4-11

http://marketplace.eclipse.org/metrics/successful_installs/last30days_bycountry

![eclipse-plugins-by-country](https://cloud.githubusercontent.com/assets/1614482/14417424/05bdb300-ffe8-11e5-94e8-63d2706ae80a.PNG)

http://www.euronews.com/2016/04/08/china-stands-firm-after-us-trade-report-slams-great-firewall/

**Comment by bjhargrave** [comment]
It appears you can subscribe to the mail list by sending an email to `bndtools-users+subscribe@googlegroups.com` and unsubscribe by sending an email to `bndtools-users+unsubscribe@googlegroups.com`.
