### ISSUE TITLE
Use Case for Java (non-OSGi) developers

### ISSUE THREAD

**Issue by paulvi** [bndtools/bnd#1394]
`bnd `has grown from generation util into full build tool. http://enroute.osgi.org/book/100-introduction.html promise is also very encouraging. 

Could you do some quick start tutorial for Java (non-OSGi) developers, i.e. making something useful without introducing OSGi runtime dependency and asking developers learn more than just a new build tool.
For example, bnd can easily can make jar with nested jar libraries.

The idea is that if you limit your audience to OSGi developers only, you can never be critical mass force within Java toolchains.

This issue does not fit https://github.com/osgi/osgi.enroute.site so raising here.

**Comment by bjhargrave** [comment]
I am not sure the point of this request. Bnd is a tool for making OSGi bundles. It is not a general purpose tool for making jars. The use case you mention of nested jar libraries only works in OSGi because of the Bundle-Classpath support of OSGi classloaders.

**Comment by paulvi** [comment]
@bjhargrave Can bnd become a tool not only for OSGi bundles (within a year or two)?

A first step would be a tutorial similar to http://enroute.osgi.org/qs/300-application.html , but a question what subset of functionality would be useful and must to learn before getting returns on time invested.

This issue may touch many aspects.  
This issue may be closed with a No, or a tutorial.
