### ISSUE TITLE
`gradle build` fails - Gradle Plugin for non-Workspace Builds

### ISSUE THREAD

**Issue by paulvi** [bndtools/bnd#1399]
For `org.example.bndtools.component1` project within https://github.com/szjug/BndtoolsWorkspaceExample `gradle build` fails

```
D:\Workspaces\Enide-BndTools\SZJUGBndtoolsWorkspaceExample\org.example.bndtools.component1>gradle build
:compileJava                                                                     
D:\Workspaces\Enide-BndTools\SZJUGBndtoolsWorkspaceExample\org.example.bndtools.component1\src\main\java\org\example\bndtools\component1\Example.java:3: error: package org.osgi.service.compon
ent.annotations does not exist
import org.osgi.service.component.annotations.*;
^                           
D:\Workspaces\Enide-BndTools\SZJUGBndtoolsWorkspaceExample\org.example.bndtools.component1\src\main\java\org\example\bndtools\component1\Example.java:5: error: cannot find symbol
@Component                  
 ^                          
  symbol: class Component   
2 errors                    
:compileJava FAILED         
             
FAILURE: Build failed with an exception.
             
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
             
* Try:       
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
             
BUILD FAILED 
             
Total time: 2.972 secs
```

the same environment as in https://github.com/bndtools/bnd/issues/1398#issuecomment-206770386

**Comment by bjhargrave** [comment]
That repo is a workspace model build. It has a cnf. 

If you want a non-workspace model build, you need to set up a normal gradle build and then apply the non-workspace bnd gradle plugin to your gradle projects.

**Comment by paulvi** [comment]
Similar to https://github.com/bndtools/bnd/issues/1398#issuecomment-207264203 the org.example.bndtools.component1 project has
gradle configured to make it independent, where on not there is other `settings.gradle` below the tree.

Puting it out of bnd workspace will lead a user to other errors like https://github.com/bndtools/bndtools/issues/1337, but I think user should be able to put new project inside bnd workspace, configure it as independent to try out something, and then remove empty `settings.gradle` to make it beloning to bnd workspace gradle build. 

The same result in `org.example.bndtools.component3outofworkspace` example

D:\Workspaces\Enide-BndTools\org.example.bndtools.component3outofworkspace>gradle build
:compileJava
D:\Workspaces\Enide-BndTools\org.example.bndtools.component3outofworkspace\src\main\java\org\example\bndtools\component3
outofworkspace\Example.java:3: error: package org.osgi.service.component.annotations does not exist
import org.osgi.service.component.annotations.*;
^
D:\Workspaces\Enide-BndTools\org.example.bndtools.component3outofworkspace\src\main\java\org\example\bndtools\component3
outofworkspace\Example.java:5: error: cannot find symbol
@Component
 ^
  symbol: class Component
2 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.601 secs

**Comment by paulvi** [comment]
The cause for gradle build failure is likely the same as in bndtools-Eclipse https://github.com/bndtools/bndtools/issues/1338 - some missing reference
