### ISSUE TITLE
Using the bnd-maven-plugin with the maven-war-plugin to create a WAB

### ISSUE THREAD

**Issue by vsingleton** [bndtools/bnd#1410]
As a developer using a maven plugin to build an OSGi WAB, I might want to use the bnd-maven-plugin to help me calculate a MANIFEST.MF and some OSGI-INF goodies for DS, and then package my WAB using the maven-war-plugin.

**Comment by vsingleton** [comment]
Hi Folks,

Submitted pull request @rotty3000 
https://github.com/rotty3000/bnd/pull/1

Here is a portlet WAB for trying this out:
https://github.com/vsingleton/jsf.applicant

Here is a pre-built war in case any of the SNAPSHOT libraries in it are not available in the repos:
http://verns.net/foo/jsf.applicant-4.0.0-SNAPSHOT.war

- Vernon

**Comment by rotty3000** [comment]
Hey @vsingleton can you just send the PR directly to @bndtools project user so that we can go through the details more easily during our by-weekly review?

**Comment by bjhargrave** [comment]
bnd-maven-plugin has been updated to support WABs by https://github.com/bndtools/bnd/pull/2670.
