### ISSUE TITLE
Cannot filter a target in test cases using DSTestWiring

### ISSUE THREAD

**Issue by dleangen** [bndtools/bnd#1421]
Hello!

I am using the DSTestWiring to implement my test cases. However, target filtering is not yet implemented for @Refereces.

Example:

	@Reference( target = "(param=value)" )
	void setComponent(MyComponent c) {
            this.c = c;
	}

Since the target filter is as yet not implemented, the c that gets set is undefined. It will just be the first that gets picked up by DSTestWiring.

I have [created a PR](https://github.com/bndtools/bnd/pull/1420) for this as a stub.

**Comment by bjhargrave** [comment]
Well `target` is supported and already tested. Also, please make sure you are using the OSGi DS annotations (`org.osgi.service.component.annotation`) and not the deprecated Bnd DS Annotations.

```

$ git grep @target -- biz.aQute.bndlib.tests
biz.aQute.bndlib.tests/src/test/component/BNDAnnotationTest.java:               assertAttribute(doc, "(abc=3)", "scr:component/reference/@target");
biz.aQute.bndlib.tests/src/test/component/ComponentTest.java:           // "/component/reference[@name='http']/@target", doc));
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("(objectclass=*)", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                        xt.assertAttribute("(objectclass=*)", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                xt.assertAttribute("", "scr:component/reference[1]/@target");
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java:                xt.assertAttribute("", "scr:component/reference[1]/@target");
```

**Comment by bjhargrave** [comment]
Also, `DSTestWiring` is an old test which uses the deprecated Bnd DS annotations.

**Comment by dleangen** [comment]
Ah! Since that is what Peter has been using ([even very recently](https://github.com/osgi/osgi.enroute.bundles/blob/master/osgi.enroute.web.simple.test/src/osgi/enroute/web/simple/test/DispatcherTest.java)), I thought it was up to date.

What would be the currently recommended way to construct test cases, then?

**Comment by bjhargrave** [comment]
Well you will not that Peter is using the OSGi DS annotations: https://github.com/osgi/osgi.enroute.bundles/blob/master/osgi.enroute.web.simple.test/src/osgi/enroute/web/simple/test/DispatcherTest.java#L15

So the use of DSTestWiring may be ok with that. 

My main point is that the `target` element of the `Reference` annotation is supported and tested. So I am not sure why you think it is not supported.

**Comment by dleangen** [comment]
Hmmmm. I say that because it does not seem to work for me, and [this line](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/testing/DSTestWiring.java#L196) indicates that it is not yet implemented. Indeed, the class accepts the target parameter, but it does not seem to do anything with it.

Next week I will create and post a test case to illustrate my problem. It is entirely possible that my problem is due to some other cause...

**Comment by dleangen** [comment]
I added a project: https://github.com/dleangen/DSTestWiringExample

The test class is here: https://github.com/dleangen/DSTestWiringExample/blob/master/enroute.dstest.test/src/enroute/dstest/test/DstestTest.java

I noticed that when I added the @Component annotation on the test class, the target filter does indeed work! However, when the test is run, for some reason the service is null, so the test fails.

**Comment by bjhargrave** [comment]
So I think your issue is not that the Bnd processing of the `Reference` annotation is incorrect.

It is about help modifying a test class so you can write a test case?

**Comment by dleangen** [comment]
Well, here is the situation. When using DSTestWiring to wire the test class:
 * If I use the bnd annotation, the service gets injected properly into the tests, but the target filter does not work
 * If I use the osgi annotation, the target filter appears to work, but the service is not being injected into the tests

Based on this result, it would appear to me that the issue relates to DSTestWiring, but that is why I am asking here.

I thought it would be neat to use DSTestWiring, so I suppose it would be correct to modify your statement to something like: "It is about help modifying a test class so I can write a test case using DSTestWiring". Sorry for causing confusion. I have updated the title to (hopefully) something better. :-)

**Comment by dleangen** [comment]
Hi,

Just to make sure I am not misunderstanding...

1. Are you suggesting that [this class](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/testing/DSTestWiring.java) should not be used (by anybody other than @pkriens) when constructing test cases?

2. Are you suggesting that I should first post this type of question to the list in order to get agreement that there is actually an issue to file?

Thanks for the clarification. :-)

**Comment by pkriens** [comment]
I need to update the DSTestWiring to use the OSGi annotations.

**Comment by pkriens** [comment]
However, it is unlikely it will support the target option. The scope of DSTestWiring was a quick hack to support testing without a lot of boiler plate code. It is actually quite useful.

**Comment by dleangen** [comment]
Oh, that's too bad, but understandable. What would you recommend, then? Just set it to "multiple" and do some if/then logic in the setter method?

**Comment by pkriens** [comment]
In principle, test cases are usually setup in such a way that you won't need those mechanisms since you're setup is specific for the test. I am not even sure it works for multiple?

**Comment by dleangen** [comment]
In my case, I set up an implementation of OAuth that implements the UserAdmin interface. (I figure that the accessToken should be retrieved via UserAdmin.) My "OAuthUserAdmin" is merely a wrapper to an existing UserAdmin, and only intervenes when an accessToken is requested.

I therefore need, in my test, to access the correct UserAdmin impl if I want to test the OAuth capability.

Perhaps this type of thing represents a "rare" case?

**Comment by pkriens** [comment]
No, I think you have a quite normal case. Why would you have multiple User Admin services in your test setup?

**Comment by dleangen** [comment]
Well, the thought I had when I designed the OAuthUserAdmin was that it should just consume whatever UserAdmin happened to be in the system, so it requires the presence of an ACTIVE UserAdmin as a @Reference. The Consumers of OAuthUserAdmin would have to @Reference( "(method=oauth2") ). Any other UA consumer doesn't care which one it gets, because in the end it would get the same service.

But now that you ask, it made me think about part of the discussion that lead to [this app note](http://enroute.osgi.org/appnotes/resolution-notes.html). If I aim for "design time resolution", then I would simply prescribe the underlying UA and wrap it in the bundle, and ensure that there is only one known UA deployed in the runtime. If I aim for "runtime resolution", then my current approach of assuming and requiring the existence of a UA is correct. Perhaps I could go for a middle-of-the-road approach, and use an existing UA if one exists, but fall back to a UA that I include in my OAuthUserAdmin bundle...

That still does not "solve" the problem of the missing targets in the tests in general, but it would solve it for my use case. :-)

**Comment by pkriens** [comment]
In a test case you generally carefully control which User Admin you use. 

And yes, this solution is intended for the common use cases, not a cure for all :-)

**Comment by dleangen** [comment]
Ok, then I will "fix" the problem on my end so I don't have to worry about filtering the service.

Thanks!
=David
