### ISSUE TITLE
Allowing to not specify version in manifest

### ISSUE THREAD

**Issue by Darnok99** [bndtools/bnd#1431]
I want to have an option of not specifying any versions in my manifest. I want to achieve it with passing an empty string to a consumer-policy. Working on the pr for it.

**Comment by bjhargrave** [comment]
Isn't that what you opened https://github.com/bndtools/bnd/pull/1429 for? Or is this something different?

**Comment by Darnok99** [comment]
Yes, i read that i should open an issue first. Sorry for troubles:)

2016-04-28 11:22 GMT+10:00 BJ Hargrave <notifications@github.com>:

**Comment by bjhargrave** [comment]
OK. There are comments on your PR that you need to address. Thanks for taking the time to contribute.

**Comment by Darnok99** [comment]
yep, done:)

2016-04-28 11:25 GMT+10:00 BJ Hargrave <notifications@github.com>:
