### ISSUE TITLE
[bnd-indexer-maven-plugin] Cannot determine scalar type of empty collection.

### ISSUE THREAD

**Issue by ivoleitao** [bndtools/bnd#1437]
Hi,

I'm trying to integrate sling with bndtools and for that I use the bnd-indexer-maven plugin. I have indexed hundreds of other artifacts with this plugin without any problems til now. However, for sling bundles I'm having the error in the subject (Cannot determine scalar type of empty collection).

I  have looked at the source code and the metadata of the bundles that are giving  me problems and for example in the one available on http://central.maven.org/maven2/org/apache/sling/org.apache.sling.commons.mime/2.1.8/org.apache.sling.commons.mime-2.1.8.jar in the OSGI-INF/org.apache.sling.commons.mime.internal.MimeTypeServiceImpl.xml
there's a empty propery with name "mime.types" which is probably an array of values that is empty thus the error that I'm having.

I've checked out the code and changed one of the unit tests and confirmed that.

I don't now if this is really a problem of the plugin or some old scr xml format. I've tried in one of my scr configurations to add an array and if the value is empty nothing is generated.

What I found a little odd is that in a previous / newer ? version of the code that I've found in  https://github.com/njbartlett/repoindex the same bundle works without problems (I've changed a unit test there too). 

This is causing me a lot of problems because I now need to generate a new versions of the affected jar's (and there's many) without empty array properties on the scr file .

**Comment by bjhargrave** [comment]
Per the OSGi spec, it is technically invalid to have an empty value for the `property`. If the `value` attribute is not specified, then the element body is used for the value. From 112.4.6: 

`If the value attribute is not specified, the body of the property element must contain one or more values.`

In any case, I have a fix to the indexer which will not fail in an empty body.

**Comment by bjhargrave** [comment]
> What I found a little odd is that in a previous / newer ? version of the code that I've found in https://github.com/njbartlett/repoindex the same bundle works without problems (I've changed a unit test there too).

This is a very old version and should not be used. The current version is in this repo.
