### ISSUE TITLE
ArrayIndexOutOfBoundException: -1 when Resolving

### ISSUE THREAD

**Issue by JSlain** [bndtools/bnd#1439]
[Original issue, in Bndtools](https://github.com/bndtools/bndtools/issues/1185)

I'm using the: osgi.enroute.template/cnf

In the file:
/cnf/ext/enroute-distro.bnd

There's this line:
-runsystempackages.eqnx: javax.script

When i click the Resolve button in Bndtools, i get an ArrayIndexOutOfBoundException.
This is caused by the resolver.

Bnd creates a special bundle *EE* for the Execution Environment, which is Java8 in my case.
While adding Capabilities for this special bundle, it does the following:
- Scan every package in it, and adds it as a Capability
- Adds every package specified in -runsystempackages

Since *javax.script* is both present in the Java8 packages, AND specified with the environment variable, the same capability is added twice. This is causing the bug, since Felix Resolver seems to not support a bundle providing the same capability multiple times.

**Comment by JSlain** [comment]
Is there a way to call the Resolve thing directly with bnd? (not in bndtools)
The bug is indeed in bnd, but i can't figure out how to test my fix outside of an Eclipse environment.

**Comment by pkriens** [comment]
There are many test cases in the biz.aQute.resolver project.

**Comment by pkriens** [comment]
I've just written a test case that adds 3x javax.script to the system capabilities and that seems to run fine.

Take a look at https://github.com/bndtools/bnd/pull/1452

You can also share your solution and I can take a look

**Comment by JSlain** [comment]
Ok i'll try to make a test that represents exactly my case.

**Comment by bjhargrave** [comment]
Please try the latest 3.3.0.DEV buids from cloudbees. #1472 has a fix which should address this.
