### ISSUE TITLE
[bnd][bndtools32] -pom instruction feature request

### ISSUE THREAD

**Issue by ivoleitao** [bndtools/bnd#1442]
Hi, In my project I'm currently using bndtools 3.2 RC. I have migrated my configuration to maven repos and I'm using it per description in http://enroute.osgi.org/tutorial_maven/320-local and on http://bnd.bndtools.org/instructions/pom.html. The pom instruction is used in this context to generate a pom file. Previously I was using the indexer plugin to generate a R5 index to populate a bndtools repository.

My problem now is that I already have a pom file. Actually I cannot (unfortunately) replace the maven toolchain in my project completely by the bndtools toolchain so in my situation it is kind of odd to generate a new pom file when I already have one. It is possible to accept a pom file in the pom instruction ?

**Comment by bjhargrave** [comment]
If you already have a pom file, don't use the `-pom` instruction since you don't need to generate a pom. Just use `-includeresource` to place your pom at the proper entry name in the bundle.

```
-includeresource.pom: META-INF/maven/group.id/artifact.id/pom.xml=yourpom.xml
```

**Comment by ivoleitao** [comment]
Tnks for your answer. Just tried that, unfortunately I have stumbled upon an error message

I have something like this as you indicated:
-includeresource:\
	META-INF/maven/group.id/artifact.id/pom.xml=pom.xml

I'm obtaining this error messages:
Cannot install path/file.jar into Local because Invalid version in group.id:artifact.id:1.0.0-SNAPSHOT to org.osgi:org.osgi.core:null
Exception: Invalid version in group.id:artifact.id:1.0.0-SNAPSHOT to org.osgi:org.osgi.core:null

Relating to my feature request it could be useful to read the pom file in the bnd instruction, that would allow an approach where i do not need to specify group.id nor artifact.id in the bnd.bnd file. However if the approach mentioned worked it is also perfectly reasonable to me.

**Comment by bjhargrave** [comment]
Well you need to replace group.id with your groupId and artifact.id with your artifactId. I thought that was obvious :-)

I don't know what the `org.osgi:org.osgi.core:null` issue is. Does you pom reference org.osgi:org.osgi.core?

I don't think it is a good idea for the `-pom` instruction to read a pom file, mutate it and write it into the bundle.

**Comment by ivoleitao** [comment]
:-) I have obfuscated the groupid and artifactid on purpose. I'm having this issue with "normal" coordinates

**Comment by bjhargrave** [comment]
Can you post your pom file?

**Comment by ivoleitao** [comment]
My complete bnd file (with company name obfuscated) and just an example pom, I've tried on other poms and the problem is the same:

Bundle-SymbolicName: xxx.platform.console
Bundle-Version: 1.0.0.${tstamp}
Bundle-Name: XXX Platform Console
Bundle-Description: XXX platform console
Bundle-Activator: xx.xxx.platform.console.Activator
Export-Package: \
	xx.xxx.platform.console.*
	
-buildpath: \
	${lib.osgi.core},\
	${lib.osgi.cmpn},\
	${lib.osgi.annotation},\
	${lib.mina.core},\
	${lib.mina.sshd.core},\
	${lib.felix.gogo.runtime},\
	${lib.equinox.console},\
	xxx.platform.common;version=latest

-testpath: \
	${lib.junit},\
	${lib.hamcrest}

-pom: groupid=pt.xxx.platform,\
	artifactid=platform-console,\
	version=${version;===;${Bundle-Version}}-SNAPSHOT

The last segment (-pom) was changed to:

-includeresource: META-INF/maven/xx.xxx.platform/platform-console/pom.xml=pom.xml

My Pom file:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>xx.xxx.platform</groupId>
		<artifactId>platform-boot</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../xxx.platform.boot</relativePath>
	</parent>

	<artifactId>platform-console</artifactId>

	<name>Platform Console</name>
	<description>Platform console</description>

	<build>
		<plugins>
			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<dependencies>

		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.core</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>osgi.cmpn</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>osgi.annotation</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.sshd</groupId>
			<artifactId>sshd-core</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.apache.felix.gogo.runtime</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.eclipse.osgi</groupId>
			<artifactId>org.eclipse.equinox.console</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>platform-common</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>

**Comment by ivoleitao** [comment]
Just another note, the objective was not to change the pom file but to derive the directory structure by reading group.id and artifact.id of the original pom. With this we didn't need to repeat the group id and the artifact id in the bnd.bnd file  justo to put the in the correct folder in my example META-INF/maven/xx.xxx.platform/platform-console/pom.xml (i.e the subdirectories following maven)

**Comment by bjhargrave** [comment]
The problem is the [lack of version in the dependencies](https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/maven/provider/POM.java#L128) because, in maven, you inherit them from the parent pom. bnd maven repo support it is not full maven support :-)

So I don't think you can do what you want here which seems to be a parallel maven and bnd build.

Even if the -pom instruction could read the pom file, the inheriting of dependency versions from parent poms would block you.

**Comment by ivoleitao** [comment]
Ok I understand. I will keep the generation for now. At least with this I don't need to do a full maven build which by itself is already an improvement. Also I was blocked by another problem with the bnd indexer plugin (for which I created an issue)  and this provides an alternative way of solving that problem since with this I do not need to generate an R5 repository.
