### ISSUE TITLE
Private-Package statement in manifest when using bnd-maven-plugin

### ISSUE THREAD

**Issue by cziegeler** [bndtools/bnd#1446]
I have a simple Maven OSGi bundle project using the bnd-maven-plugin. While the resulting jar is correct, all private packages are listed in an additional Private-Package statement in the manifest. As there is no Private-Package bundle header, I think this should not be there

Happens with 3.1.0 and latest 3.2.0-SNAPSHOT

Project can be found at
https://github.com/cziegeler/samples.guessinggame/tree/bnd

**Comment by bjhargrave** [comment]
This is bnd behavior and not unique to bnd-maven-plugin. We should minimize behavioral differences between the different drivers (bnd-maven-plugin, bnd gradle plugin, bndtools in eclipse) by not putting special behavior into bnd drivers.

If you dislike this header, you can remove with the `-removeheaders: Private-Package` instruction. Perhaps in your parent project.

**Comment by cziegeler** [comment]
Ok, I think then the default of bnd should be changed (totally agree that the drivers should stay as close as possible). I don't see the point of Private-Package in the manifest, it will lead users to think that this is a manifest entry specified by OSGi

**Comment by cziegeler** [comment]
Just realized that my request is stupid, Private-Package has of course always been there, its the Apache Felix bundle plugin which removes it by default..sorry for the noise
