### ISSUE TITLE
Packages with org.osgi.annotation.versioning.Version should be exported by default with the bnd maven plugin

### ISSUE THREAD

**Issue by cziegeler** [bndtools/bnd#1447]
I think packages which have the org.osgi.annotation.versioning.Version annotation should be exported by default when using the bnd maven plugin. This annotation is there to add version information to a package. The default usage is to add the version for public api - there might be users who add version information to private package for whatever reason, but that's really the exception. Therefore the current default for the bnd maven plugin embraces the exception rather than supporting the normal case

**Comment by bjhargrave** [comment]
I disagree. One of the nice things about bnd-maven-plugin is that it does not have a lot of this kind of default behavior. This sort of behavior should be put in to your parent pom.

Or if it is such a useful default behavior, it should just be part of bnd itself. 

But, as @njbartlett mentioned, an `Export` annotation is coming from OSGi which is what bnd will support when it arrives.

**Comment by cziegeler** [comment]
Totally overlooked the Export annotation in RFC 220 :( (I know Neil mentioned it)
Ok, let's close this one

**Comment by bjhargrave** [comment]
For posterity, you should use `${packages;VERSIONED}` to obtain the packages in a bundle that are versioned. This covers any form of supplying the version: OSGi Version annotation, old Bnd Version annotation, packageinfo, etc.

https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L2616
