### ISSUE TITLE
[3.2 RC1] cannot download bigger artifacts behind corporate-proxy

### ISSUE THREAD

**Issue by lostiniceland** [bndtools/bnd#1455]
With 3.2 RC1 I get FileNotFoundException when downloading certain JARs from JPM.

This is probably caused by our corporate-proxy (McAffee) which also does virus-scanning. When the download and scanning of a artifact takes longer then the download is redirected. 

`java.io.FileNotFoundException: [http://repo1.maven.org/maven2/org/apache/cxf/cxf-rt-ws-security/3.1.5/cxf-rt-ws-security-3.1.5.jar]
	at aQute.bnd.jpm.StoredRevisionCache.download(StoredRevisionCache.java:131)
	at aQute.bnd.jpm.Repository.scheduleDownload(Repository.java:292)
	at aQute.bnd.jpm.Repository.getLocal(Repository.java:254)
	at aQute.bnd.jpm.Repository.get(Repository.java:237)
	at bndtools.model.repo.RepositoryEntry.getFile(RepositoryEntry.java:117)
	at bndtools.views.repository.RepositoriesView$5$1.run(RepositoriesView.java:313)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

First I expected that this is something which has to be configured in our proxy, but **going back to BndTools 3.1, the artifact can be downloaded**. Since there were [some changes in bnd regarding proxies](https://groups.google.com/d/msg/bndtools-users/CU0focgd4Ls/RcvsZCMpAwAJ), this must be a regression.

**Comment by pkriens** [comment]
Do you explicitly setup a bnd proxy ( ~/.bnd/settings.xml)?

**Comment by bjhargrave** [comment]
> Do you explicitly setup a bnd proxy ( ~/.bnd/settings.xml)?

See http://bnd.bndtools.org/instructions/connection-settings.html

**Comment by lostiniceland** [comment]
No, I only set the proxy in Eclipse preferences. Will have a look at the new settings...

**Comment by pkriens** [comment]
Would you be able to show a wireshark trace?

**Comment by lostiniceland** [comment]
I will try to provide a trace next week, with the help from a colleague

**Comment by lostiniceland** [comment]
See attached traces. I did one trace with 3.1 which works and another failing one with 3.2RC1. 

Not sure if the broken-trace has enough information, but thats what I could get out of Wireshark. I had a filter for Http and used the result of this to follow the TCP-stream.

[wireshark-traces.zip](https://github.com/bndtools/bnd/files/257474/wireshark-traces.zip)

**Comment by pkriens** [comment]
On which files did you get a FileNotFoundException with the broken run? The trace does not show any anomaly :-(

**Comment by lostiniceland** [comment]
[cxf-core-3.1.5](https://jpm4j.org/#!/p/sha/24007F71117685C62E127538C574384753DBD26F//0.0.0)

As said, I used "Delete Cache" from the context-menu, then "Delete" on the artifact org.apache.cxf-core..., started Wireshark, and then draged the version-vignette from JPM4J to BndTools. I stopped Wireshark once the artifact showed up in the JPM4J-Repo (either with the downloaded icon or without)

I wonder why there are no anomalies, because the broken-trace is much shorter than the working-trace. If you could give me some advice how to setup Wireshark I am happy to go for another test-run.

I read in the bnd-documentation linked by BJ that bnd now also takes maven-settings into account. So I checked mine, but I do not have any proxies configured there (only mirrors to a local Nexus).

Since proxies are probably not so easy, there might be another solution: since you already honor maven-settings, how about using the mirror (Artifactory/Nexus) if one is specified. Bnd could just replace the url from JPM4J with the mirror-parts. This way you could completely bypass the proxy-issues and save traffic.

**Comment by psoreide** [comment]
Could this be commit 99d0970 in combination with the read timeout of 5 seconds in aQute.bnd.http.HttpClient?

**Comment by pkriens** [comment]
That is a good one .... let me check this.

**Comment by pkriens** [comment]
It might indeed be the problem ... I've increased it for now to 60 secs so it makes 3.2

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bnd/pull/1463

**Comment by lostiniceland** [comment]
Retesting with latest 3.2 RC3 I can confirm the issue is solved. Thank you very much.
