### ISSUE TITLE
Export-Package calculation includes erroneous entry if a resource has a filename which matches the exportcontents regex

### ISSUE THREAD

**Issue by nedtwigg** [bndtools/bnd#1458]
Let's say I have a jar with contents like this:

```
com/package/<lots of packages and classfiles>
META-INF
plugin.xml
com.package.core.product
plugin_customization.ini
```

I ask bndlib 3.1.0 to create a manifest for me, using -exportcontents=com.package.*.

The generated manifest includes an Export-Package entry for the com.package.core.product package, even though there is no such package, just a file which happens to have that name.

The easy workaround is to instead say `-exportcontents=!com.package.core.product,com.package.*`, but it seems like a bug that bndlib is treating a file whose filename matches the exportcontents wildcard the same as a package which matches that wildcard.

**Comment by pkriens** [comment]
Can you show your bnd file and the full printout of the resulting JAR?  You can send it to me also by email Peter.Kriens@aQute.biz

**Comment by nedtwigg** [comment]
It's part of a giant multiproject build.  I spent ~ an hour trying to make a toy example for easy debugging, but I can't reproduce the issue in isolation.  Seems like it must be my bug and not yours, but I can't imagine what I'm doing wrong.  But the workaround is easy, so I guess I'll leave this mystery mysterious for now.
