### ISSUE TITLE
Accessing Nexus OBR with Basic Authentication

### ISSUE THREAD

**Issue by torstenlunze** [bndtools/bnd#1460]
We have a basic authentication on accessing a Nexus OBR. However it is not possible to set the credentials via BndTools 3.1.

Example entry in repositories.bnd:

aQute.bnd.deployer.obr.NexusOBR;name=Test-OBR;readonly=false;repositoryUrl=https://repo.company.com/nexus/content/repositories/testobr/;username=jenkins;password=mypassword;

The username, password is used for deployement which works fine. Taking a peek on the implementation the aQute.bnd.deployer.obr.NexusOBR only takes the username, password on pushing an artifact to the OBR. Reading an artifact takes the Generic implementation which does not take any authentication credentials.

**Comment by pkriens** [comment]
Could you provide a PR? It would be nice if it uses the HttpClient in bnd now, then you can put the credentials on the URI

**Comment by pkriens** [comment]
I would suggest to either start using the new Maven Bnd Repository or the bnd maven indexer plugin.
