### ISSUE TITLE
Support source and test resource folders

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#1466]
Bnd has standard properties for source and test source code folders: `src` and `test`. These properties can be interrogated by `Project.getSourcePath()` and `Project.getTestSrc()` and are used by the bnd gradle plugin to configure the compilation paths and are used by Bndtools to validate that .classpath matches the values.

However, we should also add standard properties for resource folders: `resource` and `testresource`. The folders named by these property would have their contents copied to the respective `bin` and `bin_test` folders by the bnd gradle plugin and Bndtools which would also validate they are source folders in .classpath.

M2E sets up resource folders in .classpath with `excluding="**"` to prevent the eclipse compiler from processing the folder. However this also means the contents are not copied to the output folder. So we will need to add support in the BndtoolsBuilder to copy the resource folder content to the output folder before building the jar. We also need to make sure the test resource folder content is also copied to the test output folder before junit runs (since the junit test may rely upon the resources).

Having dedicated resource folders which are not processed by the compiler is very useful in certain cases, especially tests, where the resource folder content must not be processed by the compiler. In the bnd repo, many projects have testdata or testresource folders which contain material used by the tests. However the test methods operate directly in the original resource folder and often mutate them, so the tests must clean up or the folders must contain good .gitignore files so these folders don't show dirty. Also, since these are source resource folders, changes to them trigger rebuilds under gradle ([I had to customize the bnd build to ignore files listed in .gitignore to avoid this rebuild issue after running tests](https://github.com/bndtools/bnd/blob/master/build.gradle#L39-L60)). With support for standard source and test resource folders, test cases can just expect their test resources to be copied to the output folder and are then free to alter them as they see fit. The build can also be simplified since resource folders can be excluded from the jar's inputs as the jar's inputs already include the output folder.

**Comment by bjhargrave** [comment]
Discussed with @pkriens today. Here are some notes.

Need to allow multiple source folders per language and different output folders for each language.

We came up with the following bnd instruction proposal:

`-sources.<name>: <lang>;srcs="src/<name>/<lang>";output="build/classes/<lang>/<name>"`

Where `<name>` is the source set name and `<lang>` is the language name. Using Gradle source set folder naming defaults, one can say:

```
-sources.main: java, resources

-sources.test: java, resources
```

to get the folder names:

```
-sources.main: java; srcs="src/main/java"; output="build/classes/java/main",\
 resources; srcs="src/main/resources"; output="build/resources/main"

-sources.test: java; srcs="src/test/java"; output="build/classes/java/test",\
 resources; srcs="src/test/resources"; output="build/resources/test"
```
The `srcs` and `output` attributes can be specific in the bnd file to use other folder names. `srcs` can specify multiple folders. All folders are relative to the project's base dir.

Bnd will provide the following as the default:
```
-sources.main: java, resources

-sources.test: java, resources
```

Additional source sets can be defined and additional languages. For example:

```
-sources.main: java, groovy, resources
-sources.mysources: java, resources
```

The Builder will need to use the output folders of all the source sets.

The Bnd gradle workspace plugin will need to use all the source set information to program the source sets for the gradle project.

In order to allow Eclipse and Gradle to avoid walking on the same output folders, the driver will need to be allowed to modify the output folders. So when Eclipse is the driver (i.e. Bndtools), during Project prepare, the driver will be consulted to modify the source set information. The Eclipse driver will consult the project's .classpath file and configure the output folder of each source folder to match those used by Eclipse JDT.

**Comment by pkriens** [comment]
I wanted to follow the Groovy names but they are quite awkward:

       SourceSetContainer -> SourceSet -> SourceDirectorySet

I am thinking of 

      ProjectSetup -> AspectSetup[MAIN/TEST] -> CompilerSetup[JAVA/GROOVY/RESOURCES]

Actually, this is the model I am thinking of:

```alloy
    
    enum AspectName { MAIN, TEST }
    enum CompilerName { JAVA, RESOURCES, GROOVY }
    
    sig Filter {}
    sig File {}
    sig ErrorFile extends File {}
    sig BSN {}
    sig Error {}
    sig VersionRange {}
    
    abstract sig Container {
        bsn             : BSN,
        versionRange    : VersionRange,
        error           : lone Error, 
        file            : File
    } {
        one error => file = ErrorFile
    }
    
    sig ProjectContainer extends Container {}
    sig FileContainer extends Container {}
    sig RepositoryContainer extends Container {}
    
    
    one sig ProjectSetup {
        aspects     :    some AspectSetup
    } {
        MAIN + TEST in aspects.name 
    }
    
    sig AspectSetup {
        name        : AspectName,   
        compilers   : set CompilerSetup
    } {
        JAVA + RESOURCES in compilers.name
    }
    
    sig CompilerSetup {
        name        : CompilerName, 
        output      : File,
        filter      : set FileSet,
        sources     : set File,
        path        : set Container
    } {
        name = RESOURCES implies no path
    }
    
    run {} for 4
