### ISSUE TITLE
The ${native_capability} macro

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1471]
There was a question on OSGi enRoute about the ${native_capability} macro so I looked into how this was supposed to work. I found a few issues:

* The way we use it is on -runsystemcapabilities but this header is added to the runtime framework while it should be calculated by the runtime framework. This is problematic if you run cross-machine. I.e. on a Raspberry.
* If you did not specify the osversion for another platform then you got the local OS version
* You could not add the aliases automatically for other platforms nor could you add multiple values
* no warnings when you use deprecated values
* language was not supported

For now, I've added 
* -runprovidedcapabilities and they only act for the Bndtools resolver. 
* Updated the native_capability macro and moved its implementation to OSInformation. 
* Warning on use of the macro without args but I actually think this should be an error since it makes the bnd(run) file depend on the platform you execute it.

**Comment by bjhargrave** [comment]
As we discusses, I like adding the `-runprovidedcapabilities` and we need to change the bndtools templates to use it for `${native_capability}`.

I don't think it should be a warning or error to use `${native_capability}` without args since that will be the default in the templates. As people begin to do cross platform work, they will need separate bndrun files to the targeted platform which can then add args to `${native_capability}` as appropriate.

**Comment by fhuberts** [comment]
That would be another incompatible change; you'd be breaking existing projects using ```${native_capability}```

**Comment by bjhargrave** [comment]
> That would be another incompatible change; you'd be breaking existing projects using ${native_capability}

What would be an incompatible change? Adding a `-runprovidedcapabilities` instruction or changing the templates to use the  `-runprovidedcapabilities` instruction for `${native_capability}`?

Neither of those seem incompatible in any way.

**Comment by fhuberts** [comment]
```... we need to change the bndtools templates to use it ...```

**Comment by bjhargrave** [comment]
That does not mean incompatible.
