### ISSUE TITLE
Support for @...jar!/resource syntax in -include directives

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#1498]
For various reasons it would be extremely convenient if I could package common .bnd files into a jar and -include them from there, but currently the @ syntax is not supported as it is with -includeresource.

**Comment by bjhargrave** [comment]
`-include` supports URLs. So wouldn't jar: URLs work?

-include cannot pull from repo artifacts since -include processing happens at an early stage in project setup.

**Comment by eliasvasylenko** [comment]
> -include cannot pull from repo artifacts since -include processing happens at an early stage in project setup.

This makes sense, but I think is not the full story. In my attempts it did not work in the main `cnf/build.bnd` file, or the `cnf/ext/....bnd` files, but it _did_ work in project `bundle.bnd` files, which is sufficient for my purposes. I can watch the artefacts appear in the cache when I try it so it's definitely resolving them.

At any rate, that's tangential to the issue, which I'm not convinced is ready to be closed. I have tried using a `jar:file:///MyJarPath.jar!/MyFileInJar.bnd` style URL, and am unable to resolve files from within jars. Are you sure something like this is supported?

**Comment by bjhargrave** [comment]
> Are you sure something like this is supported?

It does seem like it should work: https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java#L1010

**Comment by eliasvasylenko** [comment]
Right! The problem seems to be that [line 1026](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java#L1026) is reached whether the file was actually found or not. If I mark the include as optional it does actually include the contents with no errors.

(I am confused as to how this has ever worked, though? But people are clearly using this feature.)

I'm making another more accurate issue and will make a pull request in a few minutes if that's okay.

**Comment by eliasvasylenko** [comment]
For reference of passers-by now that #1534 is solved, something like e.g. the following will include jar contents from the repos:

    -include jar:file:///${replace;${repo;org.eclipse.osgi};%;%25}!/systembundle.properties
