### ISSUE TITLE
Superfluous builds before launching

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1501]
The Project Launcher rebuilds the projects and this takes a lot of time because they've just been build.

**Comment by pkriens** [comment]
I thought there was a bug open to investigate a similar issue but I cannot find it anymore.

**Comment by bjhargrave** [comment]
My guess is there is no state to know that there has been a build, so the code assumes it must?

**Comment by bjhargrave** [comment]
Fixed by 0771ddd
