### ISSUE TITLE
resolving against anything wrapped by aQute.bnd.deployer.repository.wrapper.Plugin is painfully slow

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1513]
The issue seems to be that on every invocation of it's `findProviders(...)` it's init method reindexes every repository that it's wrapping completely.

**Comment by gamerson** [comment]
Could this issue be affecting this one or are they unrelated? https://github.com/bndtools/bndtools/issues/1386

**Comment by rotty3000** [comment]
Could be... this was chewing up to like mad. So I wouldn't be surprised if
it eventually ran out of descriptors.
