### ISSUE TITLE
Erroneous Manifest for Jar:javax.servlet-3.1.0.v201410161800 java.lang.ClassCastException: java.util.ArrayList cannot be cast to aQute.bnd.version.Version	bnd.bnd

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1516]
It seems that bnd does not properly handle contracts with a list of versions.

The javax.servlet bundle in this repository: http://download.eclipse.org/eclipse/updates/4.6-I-builds/I20160606-1100/
provides the contract:
```
osgi.contract=JavaServlet;uses:="javax.servlet,javax.servlet.annotation,javax.servlet.descriptor,javax.servlet.http";version:List<Version>="2.5,3.0,3.1"
```
However bnd's aQute.bnd.osgi.Contracts.collectContracts(String, Parameters) has:
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Contracts.java#L107
which casts the result to `Version` which fails with:
```
Erroneous Manifest for Jar:javax.servlet-3.1.0.v201410161800 java.lang.ClassCastException: java.util.ArrayList cannot be cast to aQute.bnd.version.Version
```

**Comment by timothyjward** [comment]
This was a problem with older versions of bnd, but I think it was fixed in 3.1. Are you perchance using the maven-bundle-plugin?

**Comment by rotty3000** [comment]
Actually I'm using master build of bndlib.

**Comment by rotty3000** [comment]
.. you can see the exact cast by reference to master above.

**Comment by rotty3000** [comment]
See the bug demonstrated on this repo, once you've updated eclipse to use bndtools HEAD

https://github.com/rotty3000/com.rotty3000.p2.http
