### ISSUE TITLE
Field injection leads to error for Map.Entry type

### ISSUE THREAD

**Issue by fipro78** [bndtools/bnd#1526]
I tried was to use the Map.Entry field type. The DS 1.3 spec says: "An unmodifiable Map.Entry whose key is an unmodifiable Map containing the service properties of the bound service, as above, and whose value is the bound service object." So I tried the following:

    @Component
    public class StringInverterCommand {

	    @Reference
	    private Map.Entry<Map<String, ?>, StringInverter> serviceMap; 
	
	    public void invert(String input) {
		  System.out.println("From map: " + serviceMap.getValue().invert(input));
	    }
    }

But this leads to an error during the generation of the component. It says _java.lang.StringIndexOutOfBoundsException: String index out of range: -1_

If I change `Map.Entry<Map<String, ?>, StringInverter>` to `Map.Entry<Map<String, Object>, StringInverter>` the error is gone

I am using Bndtools 3.2 with OSGi DS annotations in Eclipse Neon.

I already opened a ticket in Bndtools where it was suggested to open a ticket directly in bnd.
https://github.com/bndtools/bndtools/issues/1405

I have a small repository here: https://github.com/fipro78/osgi-ds-getting-started-bndtools
If you change the StringInverterCommand implementation in org.fipro.inverter.command to the implementation above, you should be able to re-produce the error easily.

**Comment by bjhargrave** [comment]
Thanks.

So you have a workaround which is to use `Object` instead of `?` in the variable declaration.

**Comment by bjhargrave** [comment]
@djencks Can you look at this? It seems the generics parsing is not handling `?` which is shorthand for `? extends Object`.
