### ISSUE TITLE
MavenBndRepository - Parent pom aus plain pom.xml in Repo

### ISSUE THREAD

**Issue by florianpirchner** [bndtools/bnd#1530]
Hey,

i am testing the plugin
"aQute.bnd.repository.maven.provider.MavenBndRepository" and found out,
that maven artifacts need to be available in the form of .jar files.
Oterwise the repo can not resolve the artifact inside the BND-Tools
Eclipse plugin.

But some parent poms (as patent poms) are only defined as .pom-Files without jar. See here:
https://repo.maven.apache.org/maven2/org/eclipse/gemini/blueprint/gemini-blueprint/2.0.0.RELEASE/

Is this an expected feature? I checked some entries in Central and found some projects doing so.

Thanks,
Florian

**Comment by pkriens** [comment]
Do you get a specific error?

**Comment by florianpirchner** [comment]
Only a bit specific. Just "artifact could not be found in local repo
.m2/.....".

But nothing detailed.

Should I debug that bug/case tomorrow? Then I can provide some detailed
info.

Best Flo

Peter Kriens <notifications@github.com> schrieb am Fr., 24. Juni 2016 18:36:

**Comment by rotty3000** [comment]
Is it possible that this could be related to this issue? #1512 

Check the .bnd file which was created in the .m2 repository for the artifact and check the BSN. If it contains a colon then it's suffering from that issue.

**Comment by florianpirchner** [comment]
Thx. I will try...

Raymond Augé <notifications@github.com> schrieb am Fr., 24. Juni 2016 21:36:

**Comment by florianpirchner** [comment]
Did detailed debugging session. 

Nexus only sends a partial `maven-metadata.xml`. The `<snapshotVersions>`-Tag is missing in the downloaded `maven-metadata.xml`. We used a simple script in "Display-View" during debug session to get the raw data from the http inputStream directly in `public TaggedData(URLConnection con, InputStream in, File file)`

But the strange thing is: 
Opening the `remote-maven-metadata.xml` by webbrowser provides the entries for `<snapshotVersions>`. But accessing the same URL by the `aQute.bnd.http.HttpClient` --> `TaggedData` does not return the `<snapshotVersions>`.

Maybe nexus does some filtering? Have no idea right now what happens.

At least `MavenBackingRepository#getVersion(Revision revision)` stops the download by the snippet: 
```
if (metadata.snapshotVersions.isEmpty())
			return null;
```

----
For me there are 2 questions about further proceeding:
1) Is the check `if (metadata.snapshotVersions.isEmpty())` in `MavenBackingRepository` required? Even in our case, the return statement of the method would provide proper results.
2) What may be the problem related to Nexus.

Best Florian

**Comment by pkriens** [comment]
This is caused by the User Agent set during the transfer, it had to do something with backward compatibility between maven versions. An awful practice.

The current development version of bnd should not have this bug as far as I know.

Kind regards,

	Peter Kriens

**Comment by florianpirchner** [comment]
Thanks. https://bndtools.ci.cloudbees.com/job/bndtools.master/ws/build/generated/p2/ did the job :)

But now i am getting the warning:
The dropped URL is not recognized as a remote jar file...

Will do another debug session.

**Comment by florianpirchner** [comment]
Conclusion:

1) Dnd from plain-pom (without a jar-file available for it) is not possible
2) myRepo.mvn allows to specify extension:pom `org.my.foo:org.my.foo.api:pom:0.9.0-SNAPSHOT`. But then `aQute.bnd.osgi.Domain.domain(Domain.java:459)`will throw an exception:
```
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at aQute.bnd.osgi.Domain.domain(Domain.java:459)
	at aQute.bnd.repository.maven.provider.IndexFile.updateDescriptor(IndexFile.java:238)
	at aQute.bnd.repository.maven.provider.IndexFile$1.apply(IndexFile.java:317)
	at aQute.bnd.repository.maven.provider.IndexFile$1.apply(IndexFile.java:313)
```
Domain tries to open the pom-file as a ZipFile.

-----
Possible solution for 2):
I am pretty new in bndTools, so i can only assume a possible solution. It may be possible to enhance the Domain. It should be able to process pom-files.

```
public static Domain domain(File file) throws IOException {
		try (FileInputStream in = new FileInputStream(file);) {

			....
			....

			if (file.getName().endsWith(".pom")) {
				PomParser p = new PomParser();
				p.setProperties(p.getProperties(file));
				return domain(p);
			}

```

If anybody could review my idea, i am going to create a pull request.

Thanks, Florian

**Comment by florianpirchner** [comment]
For 1) see #1532. A detailed description about the Dnd of pom-files.
