### ISSUE TITLE
Drop a pom-file: aQute.maven.provider.POM expects a jar-file for a pom-file

### ISSUE THREAD

**Issue by florianpirchner** [bndtools/bnd#1532]
Dropping a POM file to the Repo-View, lets BndTools expect that there is a file with a jar-extension for the pom-file.

This issue is related to #1530. But more detailed for this special case.

See:

```
    public Archive binaryArchive() {
        return revision
                .archive(
                        packaging == null || packaging.isEmpty() || packaging.equals("bundle")
                                || packaging.equals("pom") ? "jar" : packaging,
                        null);
    }
```

How can this issue by targeted? Any ideas?

Best, Florian

**Comment by florianpirchner** [comment]
I thought about it. And it I think aQute.maven.provider.POM is not the correct place to decide, that packaging-type "pom" leads to an extension ".jar".

Rather than this, the resolving logic which fetches the file should deal with that issue.

Some kind of (pseudo code):
If (archive.extension==pom) {
    - Try to find the .jar
    - If no .jar file is available, look for the .pom file
}

I guess a pull request for this issue is not that easy and time consuming. Specially to find all proper places to change.

But if any of you experts would "accept" my idea, I am going to start implementing a contribution.

Thanks,
Florian

Btw: BndTools are sooo much better than PDE ;)

**Comment by pkriens** [comment]
Please make a PR ... would be highly appreciated

**Comment by florianpirchner** [comment]
Cool :D

Peter Kriens <notifications@github.com> schrieb am Mi., 29. Juni 2016 10:14:

**Comment by pkriens** [comment]
Are you going to make a PR?

**Comment by florianpirchner** [comment]
I am playing around with the issue and try to understand what happens in
the code.

When i remove the "|| packaging.equals("pom")" from aQute.maven.provider.POM
then the issue seems to be fixed. But not always. Very strange! And
sometimes hard to reproduce in Debug Mode.

I am still working on it. But have no idea, when i resolved this issue and
can create a PR for it.



Peter Kriens <notifications@github.com> schrieb am Fr., 22. Juli 2016 um
18:22 Uhr:
