### ISSUE TITLE
Macros expansion within MavenBndRepository index files

### ISSUE THREAD

**Issue by mrulli** [bndtools/bnd#1539]
MavenBndRepository requires index files to define the scope of referenced maven repos. These index files have the following form

```
<group_id>:<artficat_1_artifact id>:<artficat_1_version>
<group_id>:<artficat_2_artifact id>:<artficat_2_version>
...
```

It would be nice to enable bnd macro expansion inside index files. This would allow defining placeholders for version numbers, for example

```
org.apache.cxf:cxf-rt-frontend-jaxrs:${cxf-version}
org.apache.cxf:cxf-rt-rs-security-oauth2:${cxf-version} 
org.apache.cxf:cxf-rt-rs-client:${cxf-version}
```

where the `cxf-version` could be defined in .bnd files.

**Comment by pkriens** [comment]
I think the future of this is the PomRepository. So we close this.
