### ISSUE TITLE
Fail to class annotation on aQute.bnd.osgi.AnnotationHeaders@7f205e8d

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1543]
The above error message fails to give enough information to diagnose the error.

By debugging I found that I had an `IllegalArgumentException` at line 116 of `ClassDataCollectors`. The message on the exception was "Invalid syntax for version: latest" which would have helped fix the problem.

Please fix to show the actual error message and the location in the Java source.

**Comment by pkriens** [comment]
PR?
