### ISSUE TITLE
Is it "-pluginpath", or "-plugin: XXX;path="

### ISSUE THREAD

**Issue by tomq42** [bndtools/bnd#1545]
I'm trying to load a plugin with the -plugin command in a bnd file.
The documentation (http://bnd.bndtools.org/chapters/610-plugin.html) implies that you specify the classpath using

    -plugin: XXX;path=...

However this doesn't seem to work. Looking through the .bnd files in the bnd sourec code, I came across an example that set 

    -pluginpath: location

I tried that and it worked.

So I don't know whether this is just a documentation error, or whether the path attribute is supposed to work and doesn't

**Comment by bjhargrave** [comment]
path is a directive which is why the doc says `path:`. So you need to say

    -plugin: XXX;path:=...

I have builds which use this.

**Comment by tomq42** [comment]
Hmm. I *thought* that was what I'd done, including the colon, but I'll try it again.

**Comment by tomq42** [comment]
OK, what's odd is that I have some plugins in my build.bnd file that look like this:

    -plugin: \
        aQute.bnd.deployer.repository.FixedIndexedRepo;name=Amdatu Dependencies;locations=http://repository.amdatu.org/dependencies/index.xml.gz,\
        aQute.bnd.deployer.repository.FixedIndexedRepo;name=Amdatu Release;locations=http://repository.amdatu.org/release/index.xml.gz

So, of the form class;name=value.
Given that there are obviously multiple forms that these parts can take, perhaps the documentation ought to be more explicit. I take it that this is the difference between "attribute" and "directive"?
The documentation says:

    PLUGIN ::= FQN ( ';' \<directive\|attribute\> )*

I think an example would go a long way here, as unless you know the syntax of the bnd files intimately, this distinction is far from obvious. The fact that there is a colon after the "path" in the bot following "The following directive is defined for all plugin:" could just be there to form a "definition list", it's not at all obvious that it is part of the syntax. 

So at the least I think a documentation update is required.

**Comment by bjhargrave** [comment]
bnd uses directives and attributes like OSGi. Attributes use `=` to separate the key from the value while directives use `:=` to separate the key from the value.

A PR for https://github.com/bndtools/bnd.manual to improve the docs would be appreciated.
