### ISSUE TITLE
aQute.bnd.osgi.Annotation.getAnnotation() doesn't really work

### ISSUE THREAD

**Issue by tomq42** [bndtools/bnd#1547]
The aQute.bnd.osgi.Annotation.getAnnotation() method is implemented as:

    Class<T> c = (Class<T>) getClass().getClassLoader().loadClass(cname);

This doesn't apparently work for annotations defined outside of the bundle containing the aQute.bnd.osgi.Annotation class and things it depends on. 

I am defining my own annotations, and when I call getAnnotation I get null. I would need the loadClass() call to be made on the class loader that loaded MY class, the one that called getAnnotation, not the class loader that loaded the Annotation class itself.

**Comment by djencks** [comment]
I think in your situation you are intended to call getAnnotation(Class<T> c), since your plugin does have access to the class involved?

thanks
david jencks

**Comment by tomq42** [comment]
That only works though if you already know the type of the annotation you've got.

I've created a PR, #1548, with a suggested fix. This allows you to call getAnnotation(), then use "instanceof" to determine what kind of annotation you've got (like the code in bndlib does), rather than testing the annotation name against strings.
