### ISSUE TITLE
ClassDataCollector memberEnd doesn't do what it sounds like it does

### ISSUE THREAD

**Issue by tomq42** [bndtools/bnd#1550]
Given the lack of javadoc on the ClassDataCollector class, I had to guess the reason for memberEnd. Since the way it works is that you get a call for "field" and then a call for "annotation" for each annotation on that field, I guessed that "memberEnd" might be a notification that we've finished processing all of the attributes for the last member (field or method) and we're ready to move on to something else now.
It's not what it does.
You get it once, after all fields and methods have been processed. 
"endOfMembers" would be a better name perhaps.

Some javadoc on this class would be excellent.

**Comment by pkriens** [comment]
PR?

**Comment by tomq42** [comment]
For what? For some javadoc?

**Comment by pkriens** [comment]
You seem to be in the code so provide a PR for an additional method with the right name?

**Comment by pkriens** [comment]
And Javadoc is always appreciated.

Though you must realize that the public API of bnd is the properties format, the internal API was never written for this purpose. Although looking back that seems where it is ending up.

**Comment by tomq42** [comment]
>Though you must realize that the public API of bnd is the properties format
Not sure how I write a plugin then? I mean you're intended to be able to write a plugin? And in order to do so and process the classes in a jar, you need to use ClassDataCollector?

**Comment by pkriens** [comment]
bnd wasn't intended to be a plugin model and I am still quite uncomfortable with it. The plugin was for the few people inside bnd so we could stay outside each other's way. Alas, time moves on and a bnd plugin has become an attractive place because it automagically runs inside Eclipse, Intellij, Gradle, ant, and maven.

I hope you realize that bnd is not backed by any commercial company that makes money on it. It is mostly driven by semi-volunteers and the oldest code originates from 1999.

**Comment by tomq42** [comment]
I have actually abandoned my efforts to do what I wanted using a bnd plugin. Since you suggest it was never intended to do this anyway, that sounds like a good move. 
When I get back to looking at it again, I will revert to using a standard java annotation processor. My suspicion is that I'll have to live with using it as a convenience, but ultimately checking the generates files in to git, rather than attempting to generate them dynamically as part of the build.
