### ISSUE TITLE
Launch failure when trying to use apache derby

### ISSUE THREAD

**Issue by tomq42** [bndtools/bnd#1555]
I'm trying to make use of apache derby, but I'm getting an odd error at launch time,

I have downloaded org.apache.derby 10.12.1 from jpm4j, dragging the vignette across to "Central" in the Repository view.
I can then add derby to my "run requirements" list, I can resolve and it shows up in the runbundles list.
I can add it as a build requirement to a package, and explore the jar, look at its contents.
I definitely have the jar.

Try and launch though, and I get:

Status ERROR: bndtools.core code=0 Cannot find /error/derby;version=[10.12.1000001,10.12.1000002) Not found in [bnd-cache, JpmRepository [writable=false, name=Central, location=~/.bnd/shacache, digest=43085EC8C982577B23344E1507CF40FACFBD2FBA], Local, Release, Distro] null
Status ERROR: bndtools.core code=0 derby;version=[10.12.1000001,10.12.1000002) Not found in [bnd-cache, JpmRepository [writable=false, name=Central, location=~/.bnd/shacache, digest=43085EC8C982577B23344E1507CF40FACFBD2FBA], Local, Release, Distro] null

There is a workspace at  https://github.com/tomq42/derby_error that shows the problem if it is useful.

**Comment by bjhargrave** [comment]
JPM is being deprecated and Peter has shut down the jpm4j server. So I am not sure what can be done here for the jpm repo. Are you able to use the derby jar via other repo types such as MavenBndRepository or BndPomRepository?

**Comment by pkriens** [comment]
Well, the server is still running and JPM is not used to get dependencies (except in very rare cases). 

However, the easiest way is to follow  BJ's advice.

**Comment by pkriens** [comment]
Ok, the problem was caused by JPM. JPM provided the metadata version of 10.12.1.1 while the real version is 10.12.1000001.17322223. This was a bug.

If you change to the BndPomRepository since JPM has been retired then this bug should go away ...
