### ISSUE TITLE
Requirements resolution fails using aQute.bnd.repository.p2.provider.P2Repository with bundle dependencies

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#1557]
If I define the following plugin:

    -plugin.8.Eclipse.4.5.Updates:\
    		aQute.bnd.repository.p2.provider.P2Repository;\
    			name				=		"Test";\
    			url					=		http://download.eclipse.org/eclipse/updates/4.5/

And then try to resolve the following run requirement:

    -runrequires:\
    	osgi.identity;filter:='(osgi.identity=org.eclipse.equinox.registry)'

The resolution fails, unable to satisfy the direct bundle requirement on `org.eclipse.equinox.common`.

However I can manually verify that the dependency does exist by searching for the bundle in the repositories view. If I then copy jar for `org.eclipse.equinox.common` from the cache at `cnf/cache/p2-Test` into a local indexed repository and retry the resolution it succeeds (with the requirement on `org.apache.felix.log` satisfied from Distro).

**Comment by rotty3000** [comment]
Confirmed!
