### ISSUE TITLE
fragments are never returned as part of resolution results

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1559]
If a fragment contributes a capability to it's host, the resolve result will contain the host but not the fragment causing runtime resolution to fail.

**Comment by rotty3000** [comment]
I've been leaning toward this issue being on the bnd side rather than on the resolver side. However, I'm not sure how bnd would know that a fragment was used by the resolver to choose a bundle as part of the result.

**Comment by bjhargrave** [comment]
So https://github.com/bndtools/bndtools/pull/1467 is a fix for this in bndtools?

**Comment by rotty3000** [comment]
After further digging the issue was indeed a bug on the bnd side.
