### ISSUE TITLE
conditionalpackage selector matching for subpackages

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#1586]
Usually whenever the `conditionalpackage` instruction is used (http://bnd.bndtools.org/instructions/conditionalpackage.html) one is interested on matching a given package and all its subpackages. 
From the documentation it is not clear what selector to give there to match e.g. all subpackage and the package `aQute.lib` itself.
If `aQute.lib*` is given, this will also match sibling packages of `aQute.lib`, e.g. ones named `aQute.lib2`. It would be good to be able to specify a simple selector here, which matches for exactly the given package and all subpackages.

**Comment by bjhargrave** [comment]
You are looking for `aQute.lib.*`. That will match `aQute.lib` and all sub-packages of `aQute.lib`. This is true for all parts of bnd which match package names.

**Comment by kwin** [comment]
Thanks I  just created a PR which clarifies the example in the `conditionalpackage` documentation.
