### ISSUE TITLE
Method with MAJOR/MINOR change signature

### ISSUE THREAD

**Issue by luthionb** [bndtools/bnd#1588]
Hi,

I've currently run into such a situation. I have declared interface A in package com.bnd.test. This class looks like:

```
 package com.bnd.test;

 public interface A {
       String getElement();
 }
```

And then I apply a change to this class like:

```
package com.bdn.test;

public interface A {
     Integer getElement();
}
```

After that when I run bnd semantic versioning tool I receive an output informing that there is a MAJOR change in:

```
 MAJOR      METHOD     getElement()
   REMOVED    RETURN     java.lang.String;
   ADDED      RETURN        java.lang.Integer;
```

However when my interface is returning a generic type like this:

```
package com.bdn.test;

public interface A {
     java.util.List<Integer> getElement();
}
```

then the output is completely different (using the bytecode signature):

```
 MAJOR      METHOD     getElement()
   REMOVED    RETURN     java.lang.String;
   ADDED     RETURN     Ljava/util/List<Ljava/lang/Integer;>;
```

What's more interesting if this list won't have defined returning type like:

```
package com.bdn.test;

public interface A {
     java.util.List getElement();
}
```

then we are receiving the same output as in the first example:

```
 MAJOR      METHOD     getElement()
   REMOVED    RETURN     java.lang.String;
   ADDED      RETURN     java.util.List
```

I looked deeper in the code and it seems like the MethodDef when we are getting the signature in one case is returning null (and then we are taking the prototype) and in the second example it's returning the bytecode representation. Why is it so? I just got that with generic type we are calling doSignature from the Clazz object, but why only then I still don't know.

Is it a bug? It would be nice that the system is returning an output in only one template.

**Comment by bjhargrave** [comment]
I am not sure what the problem is here. The diagnosis is correct. The only "questionable" thing is the use of the internal format for the generified return type: `Ljava/util/List<Ljava/lang/Integer;>;` instead of `java.util.List<java.lang.Integer>`. This is a pretty minor output issue though. Please submit a PR with a fix if you have one.

**Comment by bjhargrave** [comment]
I changed the baseline code for 3.4 to only care about erased signatures since that is what binary compatibility is about. See https://github.com/bndtools/bnd/commit/ac982f5ec926342031d013d3aaff97db26d8b4b4 and #1915.

So that is then fixes this issue.
