### ISSUE TITLE
"Failed to sync" error from aQute/bnd/repository/maven/provider/IndexFile.java

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1601]
From a gradle build I had the following error message for each of my projects:

```
Error  : packager :Exception: null
Error  : packager :Failed to sync com.paremus.packager:build:0.0.0
...
```

First comment: what does "Failed to sync" mean? Initially I had no idea whether this message even comes from Gradle or bnd. Grepping bnd sources revealed that it comes from IndexFile.java line 110.

Second comment, why isn't the stack trace printed, or even the exception type/message?

I had to attach a debugger to Gradle (using `export GRADLE_OPTS=-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=7001`) and found that the exception was an `InvocationTargetException` wrapping a `FileNotFoundException`.

The message on the FNFE is as follows:

```
Caused by: java.io.FileNotFoundException: com.paremus.packager:build:0.0.0
        at aQute.maven.provider.MavenRepository$1.run(MavenRepository.java:144)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

That's pretty odd! ` com.paremus.packager:build:0.0.0` is obviously not a file name. Line 144 of MavenRepository is constructing a FNFE using the toString method of an `aQute.maven.api.Archive`. I haven't yet determined why the file couldn't be found. Regardless we shouldn't be saying "file not found" with names that are not file names. There should at least be an explanatory message.

**Comment by bjhargrave** [comment]
I'll unwrap invocation target exception in Processor.exception.
