### ISSUE TITLE
add a -runresource directive which allows integration resources into an executable jar

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1609]
The `-runresource` will operate identically to `-includeresource` however it will collect the resources and place them either:

- in the executable jar directly
- in a jar on the `-runpath` so that they are visible to the framework classloader and any other jars in the runpath.

I'm leaning toward the second option since I don't think the runpath jars can see the executable jar resources.

**Comment by bjhargrave** [comment]
`-includeresource` in a bndrun file will add content to the executable jar. When the executable jar is unzipped at execution, these resources are then on the file system adjacent to the jars. `-runresource` should do that same but only applying to exectuable jars and not normal bundle jars. Putting the resources in some jar which is built and added to the executable jar means the resources are only available on the classpath and not the file system which defeats the point of adding them to the executable jar. You can already make a resource only jar and add it to the executable jar. So I prefer the first option.

**Comment by rotty3000** [comment]
closing without change because I've been taught that there is probably a way to solve this.
