### ISSUE TITLE
Bndtools unable to download snapshot version from Artifactory using MavenBndRepository

### ISSUE THREAD

**Issue by Mr-Frantic** [bndtools/bnd#1620]
When I am defining a dependency in artifatory.mvn with snapshot version, bndtools is not able download that dependency. I get the following exception 

An internal error occurred during: "Downloading repository entry com.ecm:catalog-interface".
java.lang.NullPointerException

I am able to download that dependency from the same artifactory with Maven when i define that in pom.xml and when it works fine when I use sharp version of the dependency

Also when I download the dependency i.e. when that dependency is in my local cache, bndtools is able to resolve that dependency.

**Comment by lukewink** [comment]
I am seeing the same issue.  Additionally, when building via gradle the following error is seen:

> 14:23:55.014 [DEBUG] [aQute.bnd.build.Workspace] Reported exception
> java.io.FileNotFoundException: For Maven artifact com.test.group:test-artifact:1.0.0-SNAPSHOT
>     at aQute.maven.provider.MavenRepository$1.run(MavenRepository.java:140)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)

**Comment by lukewink** [comment]
I added a pull request to address this issue.  In the mean time, if you explicitly set a snapshotUrl that is the same as your releaseUrl, it should work around the problem.

**Comment by bjhargrave** [comment]
I think explicitly setting a snapshot url is the solution. I don't think your PR is a good change.

**Comment by pkriens** [comment]
@Mr-Frantic : I am very interested in the NPE stack trace

**Comment by lukewink** [comment]
I added a PR which addresses the NPE

**Comment by Mr-Frantic** [comment]
Please find the stacktrace attached
[SnapshotDownloadStactTrace.txt](https://github.com/bndtools/bnd/files/452609/SnapshotDownloadStactTrace.txt)

I tried with snapshotUrl, so my main bnd file has the repo defined as

```
-plugin.1.Artifactory = \
    aQute.bnd.repository.maven.provider.MavenBndRepository; \
    releaseUrl  = https://hostname/artifactory/proj-cpi-dev/; \
    snapshotUrl  = https://hostname/artifactory/proj-cpi-dev/; \
    name        = Artifactory
```

And I have a file called `artificatory.mvn`

When I add an snapshot dependency in artifactory.mvn, I am still getting the same NPE while downloading the artifact.

**Comment by bjhargrave** [comment]
> I added a PR which addresses the NPE

Your PR seems to be unrelated to the exception just added.

**Comment by lukewink** [comment]
This is the exception I was getting:

> Exception:java.lang.NullPointerException: null
> 	 at bndtools.views.repository.RepositoriesView$7$1.run(RepositoriesView.java:373)
> 	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by bjhargrave** [comment]
> Caused by: java.lang.NullPointerException at aQute.bnd.http.URLCache$Info.lock(URLCache.java:97) at aQute.bnd.http.URLCache$Info.<init>(URLCache.java:57) at aQute.bnd.http.URLCache.get(URLCache.java:128)

That does not match up with the most recent code for 3.3. Can you try with the latest build from Cloudbees?

**Comment by bjhargrave** [comment]
> This is the exception I was getting:

I think you have a different issue than this one. You should open a separate issue so we can manage them independently. Thanks,

**Comment by lukewink** [comment]
I believe it is the same issue.  If you scroll to the bottom of the file he attached, you see the same NPE exception (just the line numbers are different since he is using 3.2 instead of 3.3).

**Comment by bjhargrave** [comment]
> I believe it is the same issue. If you scroll to the bottom of the file he attached, you see the same NPE exception (just the line numbers are different since he is using 3.2 instead of 3.3).

It may cause the exception you mention but it is a separate exception.

**Comment by Mr-Frantic** [comment]
One thing that I noticed, that bndtools is able to download the maven-metadata xml, but not the jar file.

**Comment by Mr-Frantic** [comment]
This seems to be working properly with Bndtools 3.3.0
