### ISSUE TITLE
Gradle export task to create distribution of runbundles does not create distribution with all jars

### ISSUE THREAD

**Issue by Mr-Frantic** [bndtools/bnd#1625]
When the bndrun file has runbundles have some jars which have the same name i.e.

-runbundle: \
    org.app.common.api;version='[8.0.0,8.0.1)',\
    org.app.dataenquiry.api;version='[8.0.0,8.0.1)'

The actual coordinates of jars in maven is:
org.app.common:api:8.0.0
org.app.dataenquiry:api:8.0.0
--- i.e. both jars are named as api.jar

So when we run the export task to create the distribution, the distribution contains only one api.jar

I think the export task should export the bundles with full bundle symbolic name instead of the jar name.

Also when we use the bundles generated by bndtools, the distribution generated doesn't contain the version of the bundles, it only contains the name of the bundle,

**Comment by rotty3000** [comment]
Could you please retest this scenario after https://github.com/bndtools/bnd/commit/98a4af11a55b7a5703abc01e33fee388d235d21c ?

this may solve your issue!

**Comment by rotty3000** [comment]
Sorry, the issue is different!

**Comment by zhsc** [comment]
Not sure if this is your issue, but I sadly banged my head on this.  Make sure you run the "**jar**" task before running the export or runbundles tasks...

i.e. gradle clean **jar** export.dev

It quietly just doesn't pickup the bundles if they're not built already.

Seems like before it would implicitly do the jar task on all the required projects or something.

**Comment by zhsc** [comment]
This may have been because I was trying to use the -p directive to specify a specific project.  This doesn't appear to be compatible with the export task.  So, this probably isn't your issue.

**Comment by Mr-Frantic** [comment]
Sorry I am a bit confused with the discussion. 

I think the problem is because when we exportRunbundles, we copy the jar by the name of the jar.

In **aQute.bnd.build.Project.java**, method **exportRunbundles** there is the following code:

		for (Container container : runbundles) {
			File bundle = container.getFile();
			IO.copy(bundle, new File(outputDir, bundle.getName()));
		}

Instead we that can be changed use **bundleSymbolicName with version.**

Do you think this is the correct way to fix the export issue?

**Comment by bjhargrave** [comment]
Project.export (via ProjectLauncherImpl.executable) has the same issue. Both export and exportBundles assume the file name of each file is unique when creating the output. We will need someway to make unique file names. BSN+Version may not work if the file is not a bundle (in the case of -runpath for Project.export).

**Comment by rotty3000** [comment]
I was thinking that just a Windows-like file name index could work.

File.jar
File-[1].jar
Etc.

**Comment by Mr-Frantic** [comment]
For non-bundle jars, the name would always be unique as we use the proper jar name in -runpath.

Where as for bundles we can use BSN and versions?

So export logic can segregate if the jar is a bundle or not and based on that create the jar name that need s to be exported.

**Comment by bjhargrave** [comment]
But runpath could look like path1/file.jar:path2/file.jar. So even runpath
can have duplicate file names.
-- 
-- 
BJ

**Comment by Mr-Frantic** [comment]
Is the export of runpath and -runbundles handled in same way?
It would be good if we can use BSN and Versions for bundle and for runpath we can think of having the name based on the path itself i.e. path1.file.jar, path2.file.jar

So for the exported distribution, you will always know where each jar comes from.

**Comment by zhsc** [comment]
My previous comment is irrelevant,  but for this issue:

Would it be too problematic to just create the directory structure mirroring the project paths.  At least in conflict situation. 

I.e.
Project1/api.jar
Project 2/api.jar

Seems this is mostly about creating a flat path for consumption by fileinstall, etc.

For the "export" jar approach,  seems it could be handled by the launcher.  

But trust me,  I'm not an expert.

**Comment by zhsc** [comment]
Although,  this issue seems to also be about maven pom file generation.  But it seems those coordinates are unique,  but maybe confusing.  Maybe there could be a group id base prefix.  But I feel like I've saw that already somewhere. I don't know which is the primary issue. 

Is there a use case that describes what runbundles intent is? I get it's utility,  but don't know how everyone is using it.

**Comment by Mr-Frantic** [comment]
I am using the export runbundles task to create an artifact with the the required bundles and then use that artifact generate the karaf archive file. We use this karaf archive on our production server.
