### ISSUE TITLE
enhance bnd's resolve process to collect as many missing requirements as it can

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1657]
When bnd's resolve process is called, as it is in bndtools, it stops at the first unresolved requirement.

However, it should be possible (because it's done in Apache Aries Subsystems implementation) to "mark" the missing requirement using a special marker type in the result set so that the resolver can proceed to check all other requirements collecting all failures along the way.

Doing this would reduce the number of resolve iterations considerably, particularly when resolving against a large repository or when having many missing requirements.

**Comment by rotty3000** [comment]
I think a little more work still needs to be done here because if all the missing requirements are not diagnosed within 1000ms it simply returns. Do you think that's really enough?

**Comment by bjhargrave** [comment]
It is just iterating over existing data structures. There are no remote communications. But if the 1000ms is not enough, consider allowing more time.
