### ISSUE TITLE
IllegalStateException during Resolution without any cause

### ISSUE THREAD

**Issue by lostiniceland** [bndtools/bnd#1687]
Resolving a workspace which worked previously fails with the lates DEV-build (3.3.0.DEV-20160908-141802-g8c80800) with the following message.

> java.lang.IllegalStateException: What?!? The capability was not found associated with any key! That is not possible at this stage.

The only bundle I know of which uses the require-capability model in this workspace is Pax-CDI  (1.0.0.RC1). Pax-CDI provides a extender-capability. 

test-workspace will follow. Unfortunately, no further information is available (error-log)

[bnd-1687.zip](https://github.com/bndtools/bnd/files/463873/bnd-1687.zip)

**Comment by rotty3000** [comment]
Everything uses the requirement/capability model... every package reference, require bundle, bundle fragments... pretty much every piece of metadata is modeled using requirements and capabilities.

**Comment by lostiniceland** [comment]
I was able to reproduce the issue in a simple workspace (see attachment in initial description).

**The error is caused by the manifest-entry Require-/Provide-Capability**. Bundle _test.service.provider_ uses `Require-Capability: capA` which is provided by _test.capability.provider_ `Provide-Capability: capA`.
The run-file only lists _test.service.provider_ as required bundle and I expect that _test.capability.provider_ is automatically resolved.

Background:
In my actual project I have to create service-instances per user-session (I know, not the best idea). Since I have to cleanup those services a "cleanup" capability is required which is satisfied by a session-listener-bundle.

**Comment by rotty3000** [comment]
I've taken the provided example and determined that there's no bug here.

Both the requirement and capability where improperly stated. Requirements and Capabilities follow a syntax where both a namespace and attributes are required.

The example provided these headers:
```
Provide-Capability: capA
```
and
```
Require-Capability: capA
```
What is actually required is something like:
```
Provide-Capability: capA;capA=true
```
and
```
Require-Capability: capA;filter:="(capA=true)"
```
When I made this change the resolution succeeded without error.

**Comment by lostiniceland** [comment]
Then there should be an error-marker in the bnd-file telling that the notation those headers is wrong. The current IllegalStateException (whoops this shouldnt happen) is not very helpfull.

Sections 3.2.1.26 and 3.2.1.28 in the core-spec are not very detailed (only an example), while 3.3.3 defines that a capability must only provide a symbolic-name I assumed that this is enough for the Provide/Require-headers and the filter is for advanced use-cases.

By the way, Felix seems to handle this wrong definition gracefully since it resolves capabilities as provided by the sample (the project runs fine with BndTools 3.2).

**Comment by seanbright** [comment]
@rotty3000, I'm not sure that your analysis is correct. The BNF in the R6 core spec for both `Provide-Capability` (section 3.3.3) and for `Require-Capability` (section 3.3.6) indicate that only a namespace is required. In fact, section 3.3.2 shows an example `Require-Capability` header that includes the namespace-only `com.acme.ip2loc` namespace.

This appears to be a bug in the resolver.

**Comment by timothyjward** [comment]
I'm with @seanbright on this one. The OSGi core specification (3.3.6) states that:

>A filter is optional, if no filter directive is specified the requirement always matches. The attribute names in the filter expression are used to locate capability attributes in a case sensitive manner.

Therefore it is correct to enter `Require-Capability: capA`

The `Provide-Capability: capA` is also correct, just not very useful as it is hard to filter for, it would only match a filter like `(!(foo=*))` (i.e. the foo property is unset) or a Requirement with no filter at all.

> This appears to be a bug in the resolver.

A pull request for this would be great! :)

**Comment by timothyjward** [comment]
>Then there should be an error-marker in the bnd-file telling that the notation those headers is wrong. The current IllegalStateException (whoops this shouldnt happen) is not very helpful.

If anyone is really keen then we could make this a warning. Requirements and Capabilities like this are a bit iffy...

**Comment by seanbright** [comment]
@timothyjward, so for my understanding: given a bundle with `Require-Capability: foo` and a bundle with `Provide-Capability: foo`, should the resolution succeed?

**Comment by bjhargrave** [comment]
> @timothyjward, so for my understanding: given a bundle with Require-Capability: foo and a bundle with Provide-Capability: foo, should the resolution succeed?

Yes. From 3.3.6 of the Core spec:

    A filter is optional, if no filter directive is specified the requirement always matches.

**Comment by lostiniceland** [comment]
Confirmed for RC3.
Resolution on my project is working again.
