### ISSUE TITLE
NPE in URLCache: reporter always null?

### ISSUE THREAD

**Issue by tonit** [bndtools/bnd#1695]
https://github.com/bndtools/bnd/blob/3.2.0.REL/biz.aQute.bndlib/src/aQute/bnd/http/URLCache.java#L22

Since the reporter field is not being set, a NPE gets raised which in turn breaks the retry mechanism for lockFile logic. Not sure if this is the right way..

**Comment by tonit** [comment]
Its fixed in master, however, the latest release 3.2 is broken. Is 3.3 or 3.2.1 near?

**Comment by bjhargrave** [comment]
3.3 is imminent. We have 3.3.0.RC2 build out now. Since master is fixed, we can close this issue.
