### ISSUE TITLE
jpm install bnd@* points to outdated bnd version

### ISSUE THREAD

**Issue by twystd** [bndtools/bnd#1696]
The instructions for installing command-line bnd include the command _jpm install bnd@*_ which (presumably) is supposed to fetch and install the latest version of bnd from Cloudbees.

It fails consistently with:

_java.io.FileNotFoundException: https://bndtools.ci.cloudbees.com/job/bnd.master/993/artifact/dist/bundles/biz/aQute/bnd/biz.aQute.bnd/3.2.0-SNAPSHOT/biz.aQute.bnd-3.2.0-20160516.191858-1.jar_

(probably because build 993 is no longer on Cloudbees - the current build was 1145)

**Comment by pkriens** [comment]
It is available now
