### ISSUE TITLE
bnd-maven-plugin could take bnd files as maven artifacts

### ISSUE THREAD

**Issue by benson-basis** [bndtools/bnd#1713]
I'd like to have a 'corporate default' bnd.bnd file for maven builds. Following the pattern of other Maven plugins, I propose that this could be accomplished by having this plugin accept Maven coordinates for one or more bnd files that would be treated as if included at the top of the main bnd file. If this is inoffensive, I'll code it into a PR.

**Comment by bjhargrave** [comment]
You can already set a bnd file in the parent pom for a build. What else are you suggesting?

**Comment by benson-basis** [comment]
But isn't that just replaced? I want to combine defaults from a parent with
local config (e.g. export-package) from the local bnd.bnd.

**Comment by bjhargrave** [comment]
No. It inherits from the bnd info from the parent pom. See <https://github.com/bndtools/bnd/blob/master/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java#L234-L239>. It goes to the parent pom and then loads from the current pom to allow the current pom to override the parent.

**Comment by benson-basis** [comment]
I'm sorry, I'm really failing to explain myself.

How about this explanation:

In my current multi-module Maven project, each bundle-building project has a bnd.bnd that looks like:

     include ../../common.bnd
     Export-Package: whatever.it.is.we.export.here

And this works ok, given that I only want to pull in common information that lives _in this project_.

However, I'd wish that I could express the idea of:

    include <com.basistech.defaults:bnd-defaults:1:bnd>

in my common.bnd file -- that is, say that I have some defaults that come from a repository, in addition to defaults in the current project.

Other maven plugins express ideas like this with things like:

```
      <configuration>
       <remoteBndFiles>
         <remoteBndFile>
          <groupId>com.basistech.defaults</groupId>
          <artifactId>bnd-defaults</artifactId>
          <version>1</version>
         <remoteBndFile>
       </remoteBndFiles>
     </configuration>
```

While I am being a pest, why this code in the maven plugin, as opposed to just an `@Parameter`?

```
if (configuration != null) {
  Xpp3Dom bndfileElement = configuration.getChild("bndfile");
  if (bndfileElement != null) {
    bndFileName = bndfileElement.getValue();
  }
}
```

**Comment by bjhargrave** [comment]
> I'm sorry, I'm really failing to explain myself.
> 
> How about this explanation:
> 
> In my current multi-module Maven project, each bundle-building project has a bnd.bnd that looks like:
> 
>  include ../../common.bnd
>  Export-Package: whatever.it.is.we.export.here
> 
> And this works ok, given that I only want to pull in common information that lives in this project.

What does "common information that lives in this project" mean? The `../..` looks like the file is in a parent folder.

> 
> However, I'd wish that I could express the idea of:
> 
> include <com.basistech.defaults:bnd-defaults:1:bnd>

You want this in a bnd file? Then that is a change to bndlib and not just the bnd-maven-plugin since bndlib processed the `-include` directive. I don't think we want to build maven coordinates into bndlib.

`-include` can refer to a URL so you can always say something like:

`-include http://repo2.maven.org/maven2/GAV/common.bnd` if your bnd file is on the web.

> 
> in my common.bnd file -- that is, say that I have some defaults that come from a repository, in addition to defaults in the current project.
> 
> Other maven plugins express ideas like this with things like:
> 
>       <configuration>
>        <remoteBndFiles>
>          <remoteBndFile>
>           <groupId>com.basistech.defaults</groupId>
>           <artifactId>bnd-defaults</artifactId>
>           <version>1</version>
>          <remoteBndFile>
>        </remoteBndFiles>
>      </configuration>
> 
Yes, but that is in a pom when `-include` is processed in bndlib.

> While I am being a pest, why this code in the maven plugin, as opposed to just an @Parameter?
> 
> if (configuration != null) {
>   Xpp3Dom bndfileElement = configuration.getChild("bndfile");
>   if (bndfileElement != null) {
>     bndFileName = bndfileElement.getValue();
>   }
> }

Because this method is recursive and looks at the parent projects. So you cannot @Parameter the elements of all the parents (at least with my limited maven plugin programming skills).

**Comment by benson-basis** [comment]
To answer your question: my use of ../../common.bnd is because I did not know about the parent configuration merging that you taught me about just now. It has precisely the same effect, and I plan to get rid of it.

I don't propose to teach bndlib to talk to maven repositories. I do propose to allow bnd-maven-plugin to be configured with bnd files pulled from repositories, which will have the same effect as that 'include' but without needing to deal with all of that. Now, it occurs to me that I may already know a way to accomplish this; declare the bnd file as a dependency, and then use the maven-dependency-plugin's ability to set a property to a pathname.

However, this will bring me to a much simpler feature request: to be able to supply more than one bndfile in the configuration of the plugin. Which I can knock off for you easily enough.

As for your recursive configuration setting, there is a way to avoid this, but, oddly, if requires you to make an `@Parameter` for a `List<String>` instead of a single String -- just as I proposed above. See [this blog post](http://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects/). Now, you might find this horribly ugly, and I wouldn't argue with you. I am going to research some other options.

**Comment by bjhargrave** [comment]
> However, this will bring me to a much simpler feature request: to be able to supply more than one bndfile in the configuration of the plugin. Which I can knock off for you easily enough.

But since the bnd file supports `-include` why do you need to specify more that one bnd file in the pom? The desire is to minimize the pom configuration and use native bnd features like `-include`.

**Comment by bjhargrave** [comment]
> use the maven-dependency-plugin's ability to set a property to a pathname.

And you can reference this property in the `-include` instruction in the bnd file!

**Comment by benson-basis** [comment]
On Mon, Sep 26, 2016 at 2:45 PM, BJ Hargrave <notifications@github.com>
wrote:

> use the maven-dependency-plugin's ability to set a property to a pathname.
>
> And you can reference this property in the -include instruction in the
> bnd file!
>

Oh, yea. OK, well, we have indeed blown up this entire idea. I'll close it;
if I end up with a proposal to neaten up the parent-inheritance code I'll
open a new one.

**Comment by benson-basis** [comment]
Well, this turned out to be much ado about, at much, a documentation opportunity.
