### ISSUE TITLE
bnd-maven-plugin should have stock Maven plugin documentation

### ISSUE THREAD

**Issue by benson-basis** [bndtools/bnd#1722]
I've made you a PR for this.

**Comment by bjhargrave** [comment]
I don't understand the problem here. We generally put all bnd doc in the docs/ folder of the repo which makes the bnd.bndtools.org website.

**Comment by benson-basis** [comment]
The standard maven site documentation, autogenerated from the code, appeals
to some people. If you don't like it, you don't have to publish it, but it
comes in handy to some of us.

**Comment by bjhargrave** [comment]
We don't  build the "site" in the build.

I am a bit loath to have a maven site in the code which we don't build since it may cease to build in the future.

**Comment by benson-basis** [comment]
Well, hmm. I'm suggesting here that you join the ecosystem in which pretty
nearly all the maven plugins in the work publish this site content
somewhere. I'd be happy to help get it published somewhere; one option is
via gh-pages somewhere. If you don't like anything else here, you might
want to just grab my addition of the help mojo.

**Comment by bjhargrave** [comment]
I understand using a maven site to build a website for the documentation of a maven build. But Bnd is more then just maven. We have the docs/ folder which builds a gh-pages site of the over all Bnd project documentation. I don't see us publishing a separate site to hold the maven site generated pages for the maven plugins. Also, each maven project holds a README.md where any documentation for the plugin can be placed and this does not need building and hosting to be readable.

**Comment by benson-basis** [comment]
On Fri, Sep 30, 2016 at 9:22 AM, BJ Hargrave <notifications@github.com>
wrote:

> I understand using a maven site to build a website for the documentation
> of a maven build. But Bnd is more then just maven. We have the docs/ folder
> which builds a gh-pages site of the over all Bnd project documentation. I
> don't see us publishing a separate site to hold the maven site generated
> pages for the maven plugins. Also, each maven project holds a README.md
> where any documentation for the plugin can be placed and this does not need
> building and hosting to be readable.
>
Well, if you don't like it, you don't like it.

**Comment by benson-basis** [comment]
I'm closing this, since the only commentary from devs here is opposed to the whole idea.
