### ISSUE TITLE
Maven repository support: ensure tests push to local repo

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1724]

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/commit/7db22a30e17d26d39d864e103eaaff2136483698. The test should set -buildrepo to make sure the jar task puts the jar in the local repo before the release task runs.

**Comment by rotty3000** [comment]
Do we need this still? With the recent work on the `bnd-indexer-maven-plugin` which can include the current artifact in the index, and results in the ability to put the testing plugin in the same project as the test code this becomes less of an issue.

For example I can configured the test project like so:

**itest POM**
```
	<artifactId>com.liferay.cdi.extender.itests</artifactId>
	<name>CDI Extender Integration Tests</name>
	<packaging>jar</packaging>

	<build>
		<plugins>
			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-indexer-maven-plugin</artifactId>
				<configuration>
					**<includeJar>true</includeJar>**
					<localURLs>REQUIRED</localURLs>
				</configuration>
			</plugin>
			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-testing-maven-plugin</artifactId>
				<configuration>
					<failOnChanges>false</failOnChanges>
					<resolve>false</resolve>
					<bndruns>
						<bndrun>itest.bndrun</bndrun>
					</bndruns>
					<targetDir>.</targetDir>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
            ...
```
**itest.bndrun**
```
-standalone: target/index.xml

-runrequires: \
	osgi.identity;filter:='(osgi.identity=com.liferay.cdi.extender.itests)',\
        ...
```

**Comment by bjhargrave** [comment]
This bug has nothing to do with the maven plugins. It is about the maven repository support in Bnd.

**Comment by rotty3000** [comment]
which tests is @pkriens referring to then?

**Comment by rotty3000** [comment]
Maybe I just need more information in the report, then I could try to help.

**Comment by bjhargrave** [comment]
This issue arises from a bndtools call discussing the 3.3 release post mortem. I made the fix mentioned above and this issue is to note we need an additional test case to test pushing to a local repo (vs. a remote repo).
