### ISSUE TITLE
Enable cnf to be remote or referenced by URL enabling partial workspace checkout

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1725]
Define a `-cnf` instruction that contains a URL pointing to the workspace. This can be either a local file URL or a remote http(s) reference.

Benefits:
1. No requirement to create a local cnf, which seems to be a major turn-off for many potential users.
2. We can support partial checkout of workspaces, and/or checkouts of projects from multiple bnd workspaces into the same Eclipse instance -- a very frequently requested enhancement!

The default value of `-cnf` shall be `file:../cnf`, meaning that projects not defining this instruction will continue to work exactly as they do now.

Further proposal: if the URL resolves to a non-existent location (i.e. missing/empty dir, or 404 response from http) then a default workspace is inferred. This allows projects to be completely standalone.

Open questions:
1. How should "project", "latest" or "snapshot" dependencies be resolved when the whole bnd workspace is not available?
2. Should the URL point directly to a `build.bnd` file or the directory one level up?
3. Should we allow a URL list, where the workspace is constructed as the aggregate of the list contents? This would allow for, e.g., local overrides of a remote workspace.

**Comment by njbartlett** [comment]
Also note that a lot of work would have to be done in bndtools to support this, especially in the Repositories view and all dialogs that interact with the repositories.

**Comment by stbischof** [comment]
Does something happened on this task the last years?
Would be helpful!

-
