### ISSUE TITLE
No extender requirement for very simple components

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1728]
bnd does not add a requirement for the component extender when the component is so simple it falls under the lowest version that specified the extender name. 

		if (options.contains(Options.extender) || maxVersion.compareTo(AnnotationReader.V1_3) >= 0) {
			maxVersion = ComponentDef.max(maxVersion, AnnotationReader.V1_3);
			addExtenderRequirement(requires, maxVersion);
		}

This does make some sense but I think we actually should always add this from now on.

**Comment by bjhargrave** [comment]
Bnd only added the extender requirement for DS 1.3 since the extender capability was not specified until the DS 1.3 spec.

If you always want the extender requirement in your bundles, add

`-dsannotations-options: extender`

to your bnd file.

It it wrong to change Bnd to always add the extender requirement. If someone updated Bnd in their build, then their bundle will now include a requirement which may not be satisfiable. If Bnd should always add the extender requirement, then why should it also not always use the DS 1.3 namespace for the component xml?

**Comment by pkriens** [comment]
The code I showed made it obviously clear how to force the requirement.

The problem is that we see annotations version X but downgrade if no functions are used from X. This is normally ok but in this case it means that you force people to realize in NEW systems that in certain cases they get the requirements and sometimes not. This is highly unintuitive and very hard to diagnose except for the most experienced people. (It took me 45 mins and only after looking at the source code.) The current model sucks for the resolver.

So this is a rock and a hard place. Looking at the market I think it is pretty safe today to use 1.3 as the base level so it would prevent many problems if we would make the default floor 1.3 and have an option to override it. We could use the since() function.

**Comment by bjhargrave** [comment]
So maybe we need a `-dsversion` instruction with 1.3 as the default floor?

**Comment by pkriens** [comment]
Sounds like a solution. I hate breaking existing builds but sometimes you have to deprecate stuff as well to keep life simple for the current users.

**Comment by djencks** [comment]
I’d prefer to keep it as an options versionMin=1.0 etc.  We have that nice instruction parser, lets use it.

david jencks

**Comment by bjhargrave** [comment]
The options are just enum names. Also, this default should be overrideable separate from the other ds options, no?

**Comment by djencks** [comment]
I was thinking of something like  this, I didn’t make sure it did what I expected….

diff --git a/biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java b/biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
index 5625684..1a1f06d 100644
--- a/biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
+++ b/biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
@@ -32,9 +32,24 @@ import aQute.lib.strings.Strings;
 public class DSAnnotations implements AnalyzerPlugin {
 
        public enum Options {
-               inherit, felixExtensions, extender, nocapabilities, norequirements
+               inherit, felixExtensions, extender, nocapabilities, norequirements,
+
+               minVersion {
+                       @Override
+                       void process(DSAnnotations anno, Attrs attrs) {
+                               for (String s : attrs.keySet()) {
+                                       anno.minVersion = new Version(s);
+                               }
+                       }
+               };
+
+               void process(DSAnnotations anno, Attrs attrs) {
+
+               }
        };
 
+       Version minVersion = AnnotationReader.V1_3;
+
        public boolean analyzeJar(Analyzer analyzer) throws Exception {
                Parameters header = OSGiHeader.parseHeader(analyzer.getProperty(Constants.DSANNOTATIONS, "*"));
                if (header.size() == 0)
@@ -44,7 +59,12 @@ public class DSAnnotations implements AnalyzerPlugin {
                EnumSet<Options> options = EnumSet.noneOf(Options.class);
                for (String s : optionsHeader.keySet()) {
                        try {
-                               options.add(Options.valueOf(s));
+                               Options option = Options.valueOf(s);
+                               options.add(option);
+                               Attrs attrs;
+                               if ((attrs = optionsHeader.get(s)) != null) {
+                                       option.process(this, attrs);
+                               }
                        } catch (IllegalArgumentException e) {
                                analyzer.error("Unrecognized %s value %s, expected values are %s", Constants.DSANNOTATIONS_OPTIONS, s,
                                                EnumSet.allOf(Options.class));


I don’t understand what you mean by your “also”.  I’d expect this all to look like

-dsannotation-options=felixExtensions, inherit, minVersion=1.2

or

-dsannotation-options=minVersion=1.2

david jencks

**Comment by bjhargrave** [comment]
> I don’t understand what you mean by your “also”.  I’d expect this all to look like
> 
> -dsannotation-options=felixExtensions, inherit, minVersion=1.2
> 
> or
> 
> -dsannotation-options=minVersion=1.2

I may want to put `-dsannotation-options: minVersion=1.2` in `cnf/build.bnd` and the add `-dsannotation-options: inherit` in a project. The downside of the options, since you use `getProperty`, is that there is no way to aggregate them. If you used `mergeProperty` then one could do `-dsannotation-options.minVersion: minVersion=1.2` in `cnf/build.bnd` and the add `-dsannotation-options: inherit` in a project.

**Comment by djencks** [comment]
Well, using mergeProperty seems like a good idea in any case.  Should we then also look for an initial ‘-‘ to cancel out an inherited option?  so you could turn off “inherit” in a particular project?

david jencks

**Comment by bjhargrave** [comment]
Or !. We use ! elsewhere as a negation.

**Comment by djencks** [comment]
So I forgot about some of the intricacies of the bnd header parser.  At the moment I think to get this to work without writing a new parser you have to say

-dsannotation-options=minVersion;version=1.2.0

Since we don’t actually expect people to use this often maybe this is ok?

Did I miss something?

thanks
david jencks

**Comment by bjhargrave** [comment]
I think @pkriens wants the default value of minVersion to be version=1.3 (or version=latest version of DS annotations supported by Bnd so this value automatically increases over time)

**Comment by djencks** [comment]
I'm now suggesting version:minimum=1.1.0 or whatever you want for ds and metatype.

**Comment by pkriens** [comment]
The only thing I need is to have an implementation requirement ... I am ok to make the `effective:=active` if it is lower so it won't upset the resolver though I expect it is pretty safe to make it `resolve` time.
