### ISSUE TITLE
Add hint to readme.md of bnd-maven-plugin which goal needs to be executed

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#1739]
Currently the readme.md at https://github.com/bndtools/bnd/blob/master/maven/bnd-maven-plugin/README.md lacks the information which goal needs to be explicitly configured within an `execution` element, namely `bnd-process`. Please complete the given configuration sample by extending it with the following section.
```
<executions>
    <execution>
         <goals>
            <goal>bnd-process</goal>
         </goals>
    </execution>
</executions>
```

**Comment by bjhargrave** [comment]
Can you make a PR?
