### ISSUE TITLE
Calc manifest failed

### ISSUE THREAD

**Issue by db82407** [bndtools/bnd#1742]
I'm getting this error trying to build a stand-alone jar in maven, using bnd-maven-plugin:3.3.0.

[ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:3.3.0:bnd-process (default) on project org.example.project: bnd error: Calc manifest failed, state=

[state is large, so I've added it as bnd-error.txt attachment]

The method is aQute.bnd.osgi.Analyzer.calcManifest()

} catch (Exception e) {
                        // This should not really happen. The code should never throw
                        // exceptions in normal situations. So if it happens we need more
                        // information. So to help diagnostics. We do a full property dump
                        throw new IllegalStateException("Calc manifest failed, state=\n" + getFlattenedProperties(), e);
                }

I also attach the bnd.bnd that I'm using. It uses -conditionalpackage and -includeresource to create the stand-alone jar. I have sanitised some project names in the attachments and renamed them to org.example.

[bnd.bnd.txt](https://github.com/bndtools/bnd/files/522496/bnd.bnd.txt)
[bnd-error.txt](https://github.com/bndtools/bnd/files/522502/bnd-error.txt)

**Comment by bjhargrave** [comment]
I don't see any stack trace. Run maven with --debug and collect the stack trace.

**Comment by db82407** [comment]
Hmm.. it didn't fail with --debug, and now it won't fail without --debug either.

It failed 3 times before I submitted this bug, but seems OK now.
AFAIK nothing has changed on my side, I was just running 'mvn clean install' each time.

I'll close this now, and re-open it it should fail again.

**Comment by alexejsailer** [comment]
I faced this issue while building a project from an IDE, while in parallel VSCode was running in the same folder with all maven and java plugins installed. After closing VSCode everything seemed to work normal again. I think that all were interacting with the target folder and that lead to this problem.
