### ISSUE TITLE
bnd-export-maven-plugin fails if ~/.bnd/default-ws not present

### ISSUE THREAD

**Issue by db82407** [bndtools/bnd#1748]
I had bnd-export-maven-plugin running just fine.
Then I tried to run the build on Jenkins, which didn't have a ~/.bnd directory and the build failed as follows:

[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:3.3.0:export (default) on project org.osc.export: Default handler for Launcher-Plugin not found in biz.aQute.launcher -> [Help 1]

Caused by: org.apache.maven.plugin.MojoExecutionException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:52)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
... 20 more
Caused by: java.lang.IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
at aQute.bnd.build.Project.getHandler(Project.java:2531)
at aQute.bnd.build.Project.getProjectLauncher(Project.java:2480)
at aQute.bnd.maven.export.plugin.ExportMojo.export(ExportMojo.java:57)
at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:48)
... 22 more

It appears the bnd-export-maven-plugin requires:
~/.bnd/default-ws/cnf/cache/3.3.0/bnd-cache/biz.aQute.launcher/biz.aQute.launcher-3.3.0.jar

Running the Export from Eclipse will generate this file, but it is not generated from a pure maven build.

**Comment by cschneider** [comment]
I can reproduce the issue and Guillaume Nodet also had it when building my example without using bndtools. Does anyone have an idea how I can tell bnd(tools) to either populate the dir or get the launcher from some other location?

I think in a maven build the ideal place to store the launcher would be either the local repo or the target dir.

**Comment by cschneider** [comment]
Hi @bjhargrave. I just talked to Peter how to solve this issue. He thought that maybe just the .bnd/default-ws/cnf directory was missing. I checked this but actually the directory is even created but it is not populated.

Peter said that maybe you might know what I need to call to extract the launcher jar into this directory.

**Comment by bjhargrave** [comment]
@cschneider See https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java#L597-L599 where the CachedFileRepo is added to the Workspace. Also see https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java#L456 where the repo directory is set and https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java#L477-L479 where the embedded repo is unzipped into that directory.

**Comment by cschneider** [comment]
@bjhargrave I debugged through the code when executing the export maven plugin. It seems setTypeSpecificPlugins is not called for a standalone workspace. 

I can not call this method or use the CachedFileRepo as they are not accessible  outside Workspace. Can you give me a rough concept how I should approach this?

I definitely can just extract the launcher in the plugin but I am not sure if this is the desired way.

**Comment by cschneider** [comment]
I figured it out. In the end it was easy. I just needed to add the embedded repo jar. To the plugin jar

**Comment by cschneider** [comment]
@db82407 Can you check if this works for you too?

**Comment by db82407** [comment]
So you're suggesting adding the export plugin like this?

                        <plugin>
                                <groupId>biz.aQute.bnd</groupId>

<artifactId>bnd-export-maven-plugin</artifactId>
                                <version>3.3.0</version>
                                <configuration>
                                    <bndruns>
                                        <bndrun>server.bndrun</bndrun>
                                    </bndruns>
                                </configuration>
                                <executions>
                                    <execution>
                                        <goals>
                                            <goal>export</goal>
                                        </goals>
                                    </execution>
                                </executions>
                                <dependencies>
                                    <dependency>
                                        <groupId>biz.aQute.bnd</groupId>

<artifactId>biz.aQute.launcher</artifactId>
                                        <version>3.3.0</version>
                                  </dependency>
                                </dependencies>
                        </plugin>


I'm just testing this now.
Assuming it works, the real fix is just to add the correct dependencies to
the bnd-export-maven-plugin?

Thanks,

--
Derek

**Comment by db82407** [comment]
well that didn't work.
can you tell me exactly what embedded repo jar I have to add?

Thanks,

--
Derek

**Comment by cschneider** [comment]
Oh ..sorry. I thought my pull request would be auto added. See https://github.com/bndtools/bnd/pull/1786

**Comment by db82407** [comment]
ok, thanks.

I'm not in a position to test that involves rebuilding plugin at present.

--
Derek

**Comment by db82407** [comment]
Sorry, only just got around to testing this. It works fine.

Thanks,

--
Derek

**Comment by rotty3000** [comment]
I'm re-opening this issue because I feel the solution isn't quite right and requires a internal fix to both the export and testing plugins.
