### ISSUE TITLE
Macros with implicit version parameter don't work anymore

### ISSUE THREAD

**Issue by helgoboss** [bndtools/bnd#175]
If I use a macro in "Import-Package" without specifying an explicit version as parameter, the implicit version should be taken from the bundle in the classpath which provides the imported package. This doesn't work anymore. 

Example:

```
Import-Package: scala*;version="$<range;[==,=+)>"
```

Output (although a bundle is on the classpath which exports the scala packages with a version):

```
1 : No version specified for ${version} or ${range} and no implicit version ${@} either, mask===
2 : No version specified for ${version} or ${range} and no implicit version ${@} either, mask==+
```

I came across this bug by building with maven-bundle-plugin. In maven-bundle-plugin 2.3.4 (uses bndlib 1.15.0) this still works, since 2.3.5 (uses bndlib >= 1.43.0) not anymore.

Maybe it's already fixed in the "next" branch, I haven't tried it. I need it in "master". And going back to maven-bundle-plugin 2.3.4 is no option for me. This issue is also mentioned on http://davidvaleri.wordpress.com/2011/04/07/secrets-of-the-felix-bundle-plug-in-macros-revealed/ (first comment).

**Comment by jonathanvila** [comment]
Seems to happen in maven-bundle-plugin version 3.0 , if I dont put explicit version I get the same error as the one that created this issue.
