### ISSUE TITLE
automatic reloading of resources

### ISSUE THREAD

**Issue by vatanbytyqi** [bndtools/bnd#1750]
Hi,

I have a resource folder with some static html/css/javascript files that are accessed through a jetty webserver. My problem is that I need to restart the bundle to see the changes that I have made on these static files. When I edit my files using eclipse then it works all fine and they are reloaded but if I use another editor to change those files nothing happens. I have also tried to run the the bundle using 
`$ java -jar biz.aQute.bnd-3.3.0.jar launch.bndrun` and it launches my bundle but I still need to restart the server to see the changes. Do I need to set any flag in bnd or what is the problem here?

**Comment by pkriens** [comment]
Eclipse is watching the file system, bnd does not do that. So if you run in Eclipse you should refresh otherwise you are out of luck ...
