### ISSUE TITLE
Word "clock" in Windows path results in build error

### ISSUE THREAD

**Issue by jonzl** [bndtools/bnd#1766]
Our maven build is using the `maven-bundle-plugin` `(2.5.4),` which has a dependency to the bndtools.
Our build fails, because one of our  package name includes the word "clock".
``
11/4/16, 12:49:04 PM GMT+1: [ERROR] Manifest [....]: Invalid file/directory names for Windows in JAR: [...../clock/Clock.class]. You can set the regular expression used with -invalidfilenames, the default expression is CON(..+)?|PRN(..+)?|AUX(..+)?|CLOCK$|NUL(..+)?|COM1-9?|LPT1-9?|\$Mft|\$MftMirr|\$LogFile|\$Volume|\$AttrDef|\$Bitmap|\$Boot|\$BadClus|\$Secure|\$Upcase|\$Extend|\$Quota|\$ObjId|\$Reparse
11/4/16, 12:49:04 PM GMT+1: [ERROR] Error(s) found in manifest configuration
``

Could you please remove the pattern "CLOCK" in your regular expression, which is checking for invalid file/directory names?

**Comment by bjhargrave** [comment]
maven-bundle-plugin version 2.5.4 uses bndlib version 2.4.1 (which is very old). PR https://github.com/bndtools/bnd/pull/920 fixed the name test to "CLOCK$" (ending in $) for bndlib 3.0.0. So you need to update to a more recent version of maven-bundle-plugin.
