### ISSUE TITLE
Bytecode crawling in Clazz ignores StackMapTable.

### ISSUE THREAD

**Issue by devsr** [bndtools/bnd#1776]
Bytecode crawling done in `aQute.bnd.osgi.Clazz` when parsing a Classfile that contains `Class` orphans in the constant pool ignores the StackMapTable emitted by the compiler when branches are detected.

When `Clazz` scans the constant pool while parsing a class file and finds a Class entry that is not  referred to by any other entry it assumes the Class entry is an orphan. It double checks this assumption by crawling the bytecode to make sure the Class entry isn't referred to directly in a method, however this crawling misses Classes that may be referred to by a method's StackMapTable.  The Class entry is then ignored which means it will fail to generate an Import-Package directive that contains it if that was the sole reference to that package.

Here is an example class from a one class bundle that recreates the issue. I've also attached a zip file containing a maven project that demos this issue.

Demo project: [bndbug.zip](https://github.com/bndtools/bnd/files/602279/bndbug.zip)
JavaSE 1.8
Tested with Apache Felix 5.6.1

```java
package bndbug;

import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

import org.osgi.framework.BundleActivator;
import org.osgi.framework.BundleContext;

public class App implements BundleActivator {

  @Override
  public void start(BundleContext context) throws Exception {

    /*
     * Create an object and assign it to a super-type variable. Note the
     * super-type is in a different package from the concrete type.
     */
    SecretKey key = new SecretKeySpec(new byte[] { 0 }, "NULL");

    /*
     * This branch causes the compiler to emit a StackMapTable in the byte code.
     * The table will refer to the local 'key' and force a reference to the
     * 'SecretKey' class to appear in the constant pool (which would not be
     * required without the StackMapTable).
     * 
     * Bnd sees the 'SecretKey' class in the constant pool but assumes its an
     * orphan because it has no associated entries that refer to it. When it
     * double checks by crawling the byte code the StackMapTable is ignored. Bnd
     * decides that 'SecretKey' is an orphan and does not emit and
     * Import-Package directive for its package. This causes a
     * NoClassDefFoundError at runtime.
     */
    if (System.currentTimeMillis() > 0) {
      System.out.println("Toast!");
    }

    System.out.println(key);

  }

  @Override
  public void stop(BundleContext context) throws Exception {

  }
}
```

**Comment by bjhargrave** [comment]
Thanks for the excellent bug description!
