### ISSUE TITLE
`bnd-indexer-maven-plugin` should support augments

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#1777]
The `bnd-indexer-maven-plugin` should permit augments as configuration. These augments could be used to provide fixup information for active-time dependencies, such as services provided by bundles with no provide-capability.

**Comment by rotty3000** [comment]
@pkriens if you'll help me understand the augments feature you've added into the BndrunResolveContext, it seems to follow that:

* Starting with a bundle which has a capability `Provide-Capability: bnd.augment; path="META-INF/augments.bnd"`
* And which contains a `META-INF/augments.bnd` file at the same path
* And assuming the augments are properly formatted as we find them in enroute

Then any index operation including this bundle will have it's augments loaded by the BndrunResolveContext during resolve!

Is this correct?
If this is the case I'm not sure we have to add anything to the `bnd-indexer-maven-plugin` since augments are simply more bundles included to be indexed.

**Comment by pkriens** [comment]
> On 6 Dec 2016, at 21:56, Raymond Augé <notifications@github.com> wrote:
> 
> @pkriens <https://github.com/pkriens> if you'll help me understand the augments feature you've added into the BndrunResolveContext, it seems to follow that:
> 
> Starting with a bundle which has a capability Provide-Capability: bnd.augment; path="META-INF/augments.bnd"
> And which contains a META-INF/augments.bnd file at the same path
> And assuming the augments are properly formatted as we find them in enroute
> Then any index operation including this bundle will have it's augments loaded by the BndrunResolveContext during resolve!
> 
> Is this correct?
> If this is the case I’m not sure we have to add anything to the bnd-indexer-maven-plugin since augments are simply more bundles included to be indexed.
> 
Brilliant isn’t it? :-)

**Comment by timothyjward** [comment]
>> Is this correct?
>> If this is the case I’m not sure we have to add anything to the bnd-indexer-maven-plugin since augments are simply more bundles included to be indexed.

> Brilliant isn’t it? :-)

I'm not totally sure I follow... 

To give a concrete example, the `org.apache.aries.jpa.eclipselink.adapter` bundle is used to get EclipseLink working with the OSGi JPA service, and it provides an `osgi.service` capability for `javax.persistence.spi.PersistenceProvider` (the missing piece of the puzzle). This Aries bundle has no direct dependency on EclipseLink because it works as a sort of extender. 

Because there is no direct dependency, when I do a resolve on a bndrun I get the Aries bundle, but no EclipseLink. This obviously doesn't work! In bnd I can fix this using the following simple augment:

    -augment.eclipselink.adapter: \
        org.apache.aries.jpa.eclipselink.adapter; \
        requirement:="osgi.identity;filter:='(osgi.identity=org.eclipse.persistence.jpa)';effective:=active"

So my question is - how do I apply this augment when using the `bnd-indexer-maven-plugin`? I want my generated index to contain it, so that when I do a resolve in my tests/export/IDE I get a sensible answer.

**Comment by rotty3000** [comment]
@timothyjward, all you need to do is create an additional bundle in your project (or anywhere for that matter) which contains:
```
Provide-Capability: bnd.augment; path="META-INF/augments.bnd"
```
where the file `META-INF/augments.bnd` inside the bundle contains exactly:
```
-augment.eclipselink.adapter: \
    org.apache.aries.jpa.eclipselink.adapter; \
    requirement:="osgi.identity;filter:='(osgi.identity=org.eclipse.persistence.jpa)';effective:=active"
```
Make sure your indexing configuration includes this bundle in to the index you're creating.

After that, anytime this repository index is used in a resolve on a bndrun the eclipselink.adaptor bundle will get augmented during that resolve operation (which is how all augments are currently handled).

**Comment by rotty3000** [comment]
For further information, augmentation is a function of the `AugmentRepository` which wraps around an `AggregateRepository` which fronts and assembles the real, configured and ordered repositories. So the `AugmentRepository` acts as a filter through which augments are visible on ANY of the resources in any configured repository. In other words, the augments could be in their own repository, and still affect any resources from other repositories the same way they do if the augments were defined locally in the bnd.

**Comment by timothyjward** [comment]
> all you need to do is create an additional bundle in your project

This solution smells pretty bad to me - why do I have to create a whole maven project to create another bundle for this? Why can't I just tell the indexer to add them like I do with repositories in bnd? Also I'm going to end up with this "augment bundle" hanging around in my index, even though it doesn't do anything. I will also be carrying it around inside any local indexes that I generate.

I completely get why you would want to add this model so that people can provide a released "fix-up bundle" for something, but forcing everyone to make one of these...

I know for a fact that when I use a bnd workspace model I don't need to create a special augment bundle. I just tell it what augments to add. I'd like parity in the Maven world.

**Comment by rotty3000** [comment]
! you can have parity in the maven model! just add a `-augment.*` directive in your bndrun file???

**Comment by timothyjward** [comment]
> For further information, augmentation is a function of the `AugmentRepository` which wraps around an `AggregateRepository` which fronts and assembles the real, configured and ordered repositories.

So it sounds to me like the indexer should be able to create an AugmentRepository around the index it generates, and then serialise the resources that come out of the AugmentRepository. That way I can declare augments inline in my indexer configuration and not have to create a whole extra bundle.

It may seem like I'm getting overly precious about creating this extra bundle, but every time we make people make an extra artifact then things get just that little bit harder everywhere else. Augments are a great tool for building better repository metadata, and better repository metadata means simpler assembly and deployment

> ! you can have parity in the maven model! just add a -augment.* directive in your bndrun file???

This is great, but insufficient. It won't affect a local index that I generate and publish, nor will it affect the output of an indexing project which publishes an index to Nexus.

**Comment by rotty3000** [comment]
I'm not averse to the idea... however I dislike the fact that the only indexing mechanism which would support this would be the `bnd-indexer-maven-plugin`. Should we then expand this feature request (since it can't be considered a bug) to include all of the indexing options?

**Comment by rotty3000** [comment]
Also, would we force the augmented requirements to be effective active? Otherwise we'd be lying to the index consumers.

**Comment by rotty3000** [comment]
I like the current implementation because using the latest equinox I can use the same bundle defined in this model for `runtime` augmentation be putting it in the `-runpath` with the equinox augmentation hook and the augments don't have to be limited to `effective=active`.

**Comment by timothyjward** [comment]
> I like the current implementation because using the latest equinox I can use the same bundle defined in this model for runtime augmentation be putting it in the -runpath with the equinox augmentation hook and the augments don't have to be limited to effective=active.

I'm very much focussed on the assemble/provision time here, not runtime. AFAIK there is no standard way to do this transformation outside of Equinox, so while what you're suggesting sounds interesting it can't really be relied on in the general case.

> Also, would we force the augmented requirements to be effective active? Otherwise we'd be lying to the index consumers.

All augments are effectively lies, which is another reason I prefer putting them into the index generation configuration rather than having them appear in "other ways". I definitely think that effective:=active should be the default effectiveness, but I don't see that we should require that it the only value. Users may want to use some other value, and as that's legal we shouldn't stop them.

I envisage some maven config that looks like _something_ like this (note that maven config is inevitably verbose due to the way it gets mapped as XML elements, and that most of the time it will be much smaller than this!):


    <augments>
      <augment>
        <target>
          <symbolicName>foo</symbolicName>
          <versionRange>[1,2)</versionRange>
        </target>
        <capabilities>
           <capability>
             <namespace>my.custom.namespace</namespace>
             
             <effective>active</effective>
             <attributes>
               <attribute>
                 <name>foo</name>
                 
                 <type>Integer</type>
                 <value>5</value>
               </attribute>
             <attributes>
             <directives>
               <directive>
                 <name>mandatory</name>
                 <value>foo</value>
               </attribute>
             <attributes>
          <capability>
        <capabilities>
        <requirements>
           <requirements>
             <namespace>my.custom.namespace</namespace>
             
             <effective>active</effective>
             <filter>(foo=bar)</filter>
             <attributes>
               <attribute>
                 <name>fizz</name>
                 
                 <type>Integer</type>
                 <value>42</value>
               </attribute>
             <attributes>
             <directives>
               <directive>
                 <name>resolution</name>
                 <value>optional</value>
               </attribute>
             <attributes>
          </requirement>
        </requirements>
      </augment>
    </augments>

**Comment by rotty3000** [comment]
My gosh... Couldn't we just continue to use the existing format and stick them in a text blob or just refer to a text file which holds them?

Another nice thing about the bundle approach is that I can slurp up the very same file that's in a bnd workspace without having to duplicate it. I would hope that our maven approach would try to follow a similar approach (as in having a file) so that we don't have to define a new encoding for them. The bnd maven plugin already supports bnd files and a parent hierarchy, so I'd be far more happy going with just looking into the existing bnd properties for augments in an existing syntax.

**Comment by bjhargrave** [comment]
> My gosh... Couldn't we just continue to use the existing format and stick them in a text blob or just refer to a text file which holds them?

What? You don't like verbose maven configuration xml? :-)

**Comment by rotty3000** [comment]
While I don't really disagree with the intent of the request here, I don't have any particular need for this so I'll unassign myself to indicate that I'm not actually working on it, and leave room for someone else to take it. But who knows.. maybe some day.

**Comment by azzazzel** [comment]
Is anyone working on anything that gets us closer to what Tim proposes? 
I don't mean the verbose XML but rather a way that allows to augment bundles while creating an index. If I could, I'd vote +10 for this :)

**Comment by rotty3000** [comment]
As was already stated, there's already a way to do this:

- create a bnd file which contains augments
- make a bundle that contains this file and has a capability header like:
```
Provide-Capability: bnd.augment;path=path/to/bnd/file/in/bundle.bnd
```
*Note:* if there's no path attribute the default used is `augments.bnd` (to
simplify your life.)
- make sure this augments bundle ends up in one of your indexes

The bnd resolver knows how to apply those augments to all the resources in
the repositories used.
