### ISSUE TITLE
bnd-maven-plugin: document all parameters in the plugin descriptor

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#1784]
Since the plugin descriptor (http://maven.apache.org/components/ref/3.3.9/maven-plugin-api/plugin.html) is evaluated 

- for content-assist and exposing the according description in m2e (https://bugs.eclipse.org/bugs/show_bug.cgi?id=442560)
- for http://maven.apache.org/plugins/maven-help-plugin/describe-mojo.html
- for generating a Maven Site with https://maven.apache.org/plugin-tools/maven-plugin-plugin/report-mojo.html

it should contain information about all possible parameters for each goal. Currently neither `bnd`nor `bndfile` are listed there with an according description.

The plugin descriptor is automatically generated by the maven-plugin-plugin from the annotations set on the mojo together with the javadoc of the according field. The changes have been part of the discarded PR https://github.com/bndtools/bnd/pull/1774/files. Please consider adding those changes as well.

**Comment by bjhargrave** [comment]
This sounds basically the same as https://github.com/bndtools/bnd/issues/1722 / https://github.com/bndtools/bnd/pull/1721 which were closed.

**Comment by bjhargrave** [comment]
> for content-assist and exposing the according description in m2e (https://bugs.eclipse.org/bugs/show_bug.cgi?id=442560)

This is new information. To support this, it may be worth adding the bnd/bndfile fields even though the code will not use them.

**Comment by kwin** [comment]
> To support this, it may be worth adding the bnd/bndfile fields even though the code will not use them.
Exactly, those may even be evaluated by other IDEs directly (not sure about it though), but in every case the plugin descriptor should be complete!
