### ISSUE TITLE
Baseline suggests a "micro" bump when there is both a "minor" and a "removed" change

### ISSUE THREAD

**Issue by Ithildir** [bndtools/bnd#1792]
Hi,
I think I found an issue in the baseline code. Here are the steps to reproduce it:

1. create a bundle with 2 exported packages, each one of them with 1 class in it
2. un-export one of the packages
3. add a public method to the class in the only exported package
3. try to run a semantic versioning check between this new bundle and the one created at step 1

AFAIK the change at step 2 is a `REMOVED` change, while the change at step 3 is a `MINOR` one. But baseline suggests a `MICRO` version bump instead of a `MINOR` one.

Thank you!

**Comment by bjhargrave** [comment]
For future readers, a `REMOVED` change is a `MAJOR` bump. PR #1797 includes this fix.
