### ISSUE TITLE
wab: duplicate classes in output war file

### ISSUE THREAD

**Issue by thomasmey** [bndtools/bnd#1808]
Hi,

Here is what I understood and what's happing in the bnd-maven-plugin (3.1.0):

1.) All classes are compiled to target/classes directory

2.) Then the bnd-maven-plugin runs and creates the "metadata-only jar file in memory" and it add first all relevant classes:
 Thread main
 Builder.doExpand(Jar) line: 512
 Builder.build() line: 97
 BndMavenPlugin.execute() line: 161

3.) possible includes are added to the metadata-jar:
 Thread main
 Builder.build() line: 98
 BndMavenPlugin.execute() line: 161

4.) then the wab instruction is processed:
 here happens the problem/error as all classes are renamed, i.e. moved(!) in the in memory metadata jar.
 when tracing is enabled this will be outputted to stderr:
 "# wab: moving: de/m3y3r/testing/Example.class"

Inside Jar.rename() the resource is moved from target/classes/ to target/classes/WEB-INF/classes/
 Thread main
 Jar.rename(String, String) line: 732
 Builder.doWab(Jar) line: 224
 Builder.build() line: 99
 BndMavenPlugin.execute() line: 161

5.) finally all additional resource from the -wab instructions are added to the metadata-jar.
 After this step the resource of the metadata jar will look like this:
 [WEB-INF/classes/de/m3y3r/Example.class, WEB-INF/web.xml, doc/index.html]

And the resource entry of WEB-INF/classes/de/m3y3r/Example.class will actually point to target/classes/de/m3y3r/Example.class

Then the manifest is processed/created and some other things are happening. you can expand the metadata jar with undocumented bnd instruction: "-expand: /dir/to/expand/to" after that the builder is finished.

Fun fact 1: The expanded metadata jar nearly looks correct. There is only a duplicated content of doc/index.html under expanded/WEB-INF/classes/. But this is maybe a bug in the dot.expand(out) (line 174 of aQute.bnd.osgi.Builder class, need to check this again).

6.) After the builder is finished actually resources are created in the target/classes directory:
 First the META-INF/MANIFEST.MF file is created at BndMavenPlugin.execute() line: 164

And then the metadata jar is "expanded":
 BndMavenPlugin.execute() line: 171

Here the bug manifests itself:
 in this method all metadata-jar resource are actually copied from their original position to WEB-INF/classes! I think this is a bug, as before those resource were meant to be moved (in the Builder) but here they are copied and after the copy process the original file is not deleted in target/classes:

Thread [main](Suspended %28breakpoint at line 241 in BndMavenPlugin%29)
 BndMavenPlugin.expandJar(Jar, File) line: 241
 BndMavenPlugin.execute() line: 171

This leaves the target/classes directory in an inconsitent state, with duplicated classes:
 1.) the original classes from the compile step under target/classes and
 2.) the copied classed from the wab osgi Builder move step under target/classes/WEB-INF/classes.

So what do you think about this? I would argue that this is a bug and should be fixed, but I'm not sure what's the best solution for this. Probably remove the original resource after the IO.copy()?

And after going through all this, I would argue that using the type jar is the correct "packager" (maven-jar-plugin) for wab files created by the bnd-maven-plugin, as most work to create a correct war/wab structure is done already in this plugin.

Hope this all makes sense.

Feedback is most welcome!

**Comment by bjhargrave** [comment]
The current bnd-maven-plugin has the philosophy of letting other plugins populate target/classes and then process the contents of target/classes which may resulting metadata being added and possibly copying classes in from the build path and then letting the jar plugin create the artifact from the target/classes contents.

Reorganizing the contents of target/classes (e.g. moving things to WEB-INF) is pretty much out of scope. 

Perhaps your desires would be better pursued with a new maven plugin, e.g. bnd-wab-maven-plugin, which adopts a different philosophy that includes replacing the jar plugin's role in actually creating the artifact.

**Comment by thomasmey** [comment]
"Reorganizing the contents of target/classes (e.g. moving things to WEB-INF) is pretty much out of scope." But that is exactly what is currently happening in the plugin!

**Comment by bjhargrave** [comment]
The use of -wab will reorganize the internal Jar object in bnd which then writes that out to target/classes but as you note, it does not move them from the their original location. Basically using -wab and bnd-maven-plugin is a bad idea. Perhaps the bnd-maven-plugin should detect the use of -wab and error out.

**Comment by timothyjward** [comment]
> Perhaps the bnd-maven-plugin should detect the use of -wab and error out.

We want to let the maven-war-plugin do the moving/packaging. If that is not possible with the current bnd maven plugin then we at least need a separate target, or a change of default based on the project being a war.

**Comment by bjhargrave** [comment]
I'll detect `-wab` and error out.
