### ISSUE TITLE
Unable to download previous 3.3 release binary from cloudbees

### ISSUE THREAD

**Issue by pikeview** [bndtools/bnd#1812]
Hi 
I am unable to download all artifacts as a zip from from https://bndtools.ci.cloudbees.com/job/bnd.master/872/artifact/

The download breaks after a few bytes.

**Comment by bjhargrave** [comment]
Please get the released artifacts from [Maven Central][1] or [JCenter (Bintray)][2].

I am not sure why the zip download from Cloudbees does not work, but that would be a problem with Cloudbees which is out of our control.

[1]: https://search.maven.org/#search|ga|1|g%3A%22biz.aQute.bnd%22
[2]: https://jcenter.bintray.com/biz/aQute/bnd/
