### ISSUE TITLE
Validate (not resolve) -runbundles against requirements

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#1827]
I noticed documentation [here](https://github.com/bndtools/bnd/wiki/Changes-in-3.4.0) for a new `resolve` Gradle task, which along with the new behaviour to maintain `-runbundles` ordering after resolution (I've forgotten where I read this) probably makes automating resolution viable for many people.

Sometimes though manual requirement resolution and `-runbundles` specification is likely still necessary. It would be nice if there were a task to simply *validate* the existing `-runbundles` against requirements, so that these projects can still benefit from all of the safety this provides.

Presumably this would also be way quicker than full resolution, which may be important to some.

**Comment by bjhargrave** [comment]
> simply validate the existing -runbundles against requirements

Against what requirements? `-runrequire`?

**Comment by eliasvasylenko** [comment]
Yes, the same requirements observed by resolution.

**Comment by bjhargrave** [comment]
So it sounds like a solution would be to run resolve again and make sure the resolve output is a subset of the current `-runbundles`.

**Comment by eliasvasylenko** [comment]
That would surely give false negatives, since there are generally multiple ways to satisfy the run requirements. It is also a very expensive operation, whereas validation alone should be cheap. Does the framework itself not check than a bundle's requirements are all satisfied when it is activated, for example? This is performed almost immediately.

**Comment by bjhargrave** [comment]
Well you would probably need to write a special validating resolve process and resolve context to do what you are thinking of. Or some other new mechanism.

PRs welcome :-)

**Comment by eliasvasylenko** [comment]
Okay, thanks for the pointers :)

**Comment by bjhargrave** [comment]
I think if you use -runbundles instead of -runrequires as input to the resolver and don't provide the resolver any other bundles from the configured repositories, then, if the resolve operation is successful, you have a valid closure of bundles in -runbundles. If the resolve operation fails, then you are missing something.

**Comment by bjhargrave** [comment]
So you may be able to use the existing resolve process/context but setting (temporarily) -runrequires to the value of -runbundles and setting -runrepos to be empty and then running a resolve.
