### ISSUE TITLE
Misleading error "The default package '.' is not permitted by the Import-Package syntax"

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bnd#1848]
I am facing a 'default package is not permitted' error in my Bndtools workspace. The `cnf/build.bnd` file has this contents:
```
javac.source: 1.8
javac.target: 1.8
-runee: JavaSE-1.8
Bundle-Activator: ${classes;IMPLEMENTS;org.osgi.framework.BundleActivator}
```
The `cnf/ext/repositories.bnd` declares two repositories:
```
-plugin: \
    aQute.bnd.repository.osgi.OSGiRepository; \
        name=Bndtools Hub; \
        locations=https://raw.githubusercontent.com/bndtools/bundle-hub/master/index.xml.gz; \
    , \
    aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
        releaseUrls=https://repo.maven.apache.org/maven2/; \
        pom=${workspace}/cnf/maven-central.xml; \
        name=Maven Central;
```
and the `bnd.bnd` file contents of the only project in this workspace is:
```
-testpath: \
    junit:junit;version=latest
```

The `Bundle-Activator` header in `cnf/build.bnd` seems to cause the confusion. After removing the line, the workspace builds just fine.

Event though the project does not provide an activator class, from reading the [Automatic Bundle-Activator FAQ entry](http://bnd.bndtools.org/chapters/920-faq.html?#automaticActivator) I assume that it should be legal to do so.

But even if an activator must be provided, given the `Bundle-Activator` header is present, a more revealing error message would help.

The full error message is:
> The default package '.' is not permitted by the Import-Package syntax.
 This can be caused by compile errors in Eclipse because Eclipse creates
valid class files regardless of compile errors.
The following package(s) import from the default package null

Though I am using bnd through Bndtools, I got the impression that this is an issue with bnd itself. Please let me know if this issue doesn't belong here.

**Comment by vorburger** [comment]
@rherrmann thanks for even opening this issue - saved me hours! Fully agree clearer msg would be great.

PS: Yes this is something in BND; I've hit it with the biz.aQute.bnd.gradle:3.3.0 (no bndtools).

**Comment by timothyjward** [comment]
> The `Bundle-Activator` header in `cnf/build.bnd` seems to cause the confusion. After removing the line, the workspace builds just fine.
>
> Event though the project does not provide an activator class, from reading the Automatic Bundle-Activator FAQ entry I assume that it should be legal to do so.

The error being output is obviously incorrect, and I have a proposed fix. The fix will, however, still trigger a warning in the project which has no activator class. Putting a global macro for adding the `Bundle-Activator` is not recommended (and hence not done by default). You will also get errors if multiple activator types are visible within a single project.

Therefore, even after this fix, I would strongly recommend that you consider removing the `Bundle-Activator` header from `cnf/build.bnd`.

**Comment by rherrmann** [comment]
@timothyjward thank you for the hint and for fixing this. I am aware that adding a global `Bundle-Activator` is not recommended. I encountered this issue while experimenting with a sandbox workspace.
