### ISSUE TITLE
Publish `biz.aQute.bnd.builder` on Gradle Plugin Repository

### ISSUE THREAD

**Issue by renatoathaydes** [bndtools/bnd#1850]
I've noticed `biz.aQute.bnd` version 3.3.0 is on the Gradle Plugin Repository, but `biz.aQute.bnd.builder` is not.

Could you publish the builder as well, please?

**Comment by bjhargrave** [comment]
The `biz.aQute.bnd` plugin was published to the Gradle Plugin Portal before the current mechanism put in place by Gradle. So updates to it in JCenter get mirrored into the Gradle Plugin Portal. But the current process works very differently and there is no way to publish an already built artifact to the Gradle Plugin Portal. It must be published from a build, generally a local build on the developer's machine which holds the API key (see <https://plugins.gradle.org/docs/submit> for details). This does not fit with the Bnd build process which builds on Cloudbees. This issues was raised in <https://discuss.gradle.org/t/publishing-to-the-plugin-portal-via-artifactory/9083> but no real answer was ever put forward which would allow and already built artifact to be deployed to the Gradle Plugin Portal. So at this point, I don't see how to publish additional gradle plugin ids to the Gradle Plugin Portal with the current Bnd build process.

**Comment by bjhargrave** [comment]
I updated the gradle-plugin attribute in bintray to add the `biz.aQute.bnd.builder` name:

`$ curl https://api.bintray.com/packages/bintray/jcenter/biz.aQute.bnd.gradle/versions/3.3.0/attributes`
`[{"name":"gradle-plugin","type":"string",
"values":["biz.aQute.bnd:biz.aQute.bnd:biz.aQute.bnd.gradle","biz.aQute.bnd.builder:biz.aQute.bnd:biz.aQute.bnd.gradle"]}]
`

So perhaps that might work...

**Comment by renatoathaydes** [comment]
Thanks for the quick feedback! I will wait for your next release, no problem!

**Comment by bjhargrave** [comment]
The attribute changes I made in bintray have causes the Gradle Plugin Portal to add the `biz.aQute.bnd.builder` plugin! See https://plugins.gradle.org/plugin/biz.aQute.bnd.builder. So you can use the 3.3.0 version of `biz.aQute.bnd.builder` plugin from the Gradle Plugin Portal now.

**Comment by renatoathaydes** [comment]
Great to know, thanks.

**Comment by soberich** [comment]
@bjhargrave this is again become actual.
Are you going to publish 3.5.x - 4.x to gradle portal (particularly I am interested in builder plugin if it matters.

**Comment by bjhargrave** [comment]
There is no way to publish already built binaries to the gradle plugin portal that I can figure out. They must be published from a build. Since we build on Jenkins and then decide after the build to publish, the process defined by gradle does not work for us. We do publish our plugins to Maven Central and JCenter.

If you can figure out how to publish an already built binary to the gradle plugin portal, I am open to learning about it.
