### ISSUE TITLE
Component annotations add @Inherited?

### ISSUE THREAD

**Issue by mattrpav** [bndtools/bnd#1854]
Would it be possible to  add the @Inherited annotation to the bnd component annotations to allow for inherited classes to support sharing things like @Reference from a super class?

**Comment by bjhargrave** [comment]
You should use the `-dsannotations-options: inherit` instruction for the OSGi DS annotations. This is a Bnd extension which will look at super types for things like @Reference.

Note: The Bnd DS annotations are deprecated as they are replaced by the OSGi DS annotations.

**Comment by bjhargrave** [comment]
See also http://enroute.osgi.org/faq/ds-inheritance.html which explains why the standard OSGi DS annotations are not inherited.

Also, OSGi DS annotations are not Runtime annotations for which Inherited could apply.
