### ISSUE TITLE
How to set properties 

### ISSUE THREAD

**Issue by fab1an** [bndtools/bnd#1855]
I can't find information on how to set properties, when using a task like 

```gradle
task makeJar(type: Bundle) {
    bndfile = file('myconfig.bnd')
}
```

The configuration contains entries like

```
Bundle-Version: ${bundle.version}
```

**Comment by bjhargrave** [comment]
I don't understand the bug here? If you have how-to-use-bnd questions, please ask in the bndtools-users mail list: https://github.com/bndtools/bnd#feedback. The issues are to report defects. Thanks.

**Comment by fab1an** [comment]
Shouldn't this be part of the README? Thank you.

**Comment by bjhargrave** [comment]
> Shouldn't this be part of the README? Thank you.

It is: https://github.com/bndtools/bnd/blob/master/README.md#feedback

**Comment by fab1an** [comment]
Not the mailing list of course, the part about the properties.

I read the README btw., it contains a section about properties, which didn't work for me: https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#customizing-a-projects-gradle-build
