### ISSUE TITLE
Gradle 3.2+, bnd.builder in bnd.gradle 3.2+ results in an exception

### ISSUE THREAD

**Issue by yrashk** [bndtools/bnd#1859]
I have a multi-project setup that works fine with bnd.gradle in 3.1.0 but fails to work starting in 3.2.0.

I am using the `biz.aQute.bnd.builder` plugin and when evaluating the project, I get this:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'main'.
> Could not resolve all dependencies for configuration ':runtime'.
   > A problem occurred configuring project ':main-sub1.
      > Could not resolve all dependencies for configuration ':main-sub1:detachedConfiguration1'.
         > Project :main-sub1 declares a dependency from configuration 'detachedConfiguration1' to configuration 'default' which is not declared in the descriptor for project :main-sub1.
```

I've traced the most probably cause to 4cc36606b1369cc174c5caeb4708982694887075 but I am not sure if I am missing something or is this an incompatibility with Gradle 3 API, or something else?

**Comment by bjhargrave** [comment]
Can you provide the exception stacktrace? Also a small github repo to reproduce the problem will help.

Are you using the latest Bnd Gradle Plugin? 3.3? I use Bnd Gradle Plugin 3.3 with Gradle 3.3 all the time.

**Comment by bjhargrave** [comment]
Closing due to lack of response. Please open a new issue when you can supply the requested information.
