### ISSUE TITLE
Connection between osgi and bnd in documentation...

### ISSUE THREAD

**Issue by toddmushenoatflairsoft** [bndtools/bnd#1871]
Having tried to submit a bug about osgi, I was told that this is the proper place to do so.
My issue was that the tutorials do not work for me, and since I was following the OSGi documentation (not the bnd documentation), I assumed it would be a bug for OSGi not BND.
Please make this distinction more clear.

**Comment by bjhargrave** [comment]
I did not suggest that the Bnd GitHub project is the place to submit bugs about OSGi. You attempted to email the osgi-dev list without joining the list. Most list require membership before accepting posts (for spam reduction). As the list owner, I received your complaint about the message rejection. Your messages appears to be about an issue with Bnd, so I pointed you to the feedback section in the README of this repo.

Bnd is tooling for developing OSGi bundles. OSGi and Bnd share many interested individuals but are separate things. Neither controls the other. 

So I am unsure what needs to be done here for the Bnd documentation: <http://bnd.bndtools.org/>. OSGi enRoute documentation states that Bnd is part of the tools chain for enRoute: <http://enroute.osgi.org/doc/210-overview.html>.

**Comment by toddmushenoatflairsoft** [comment]
Most list require membership before accepting posts...
1: This is untrue, for about 95% of the open source projects I have dealt with.
2: That is fine, but shouldn't you explain that to people using your site?
Might I suggest you link to the sign up page rather then just posting an email address that goes no where, and assuming your user base "knows" what your process is?

Todd
