### ISSUE TITLE
[baseline] Should the addition or removal of checked exceptions on API methods be MAJOR/MINOR change?

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1872]
Hello all,

We suffered an issue where a released artifact had one of it's API methods add a checked exception to the method signature. Baseline did not warn about any compatibility issue (which I believe is fine in theory). However consumers compiling to the new API suddenly started to fail as their code did not consider the new exception.

My question is then if this is the proper baseline behaviour? Should this case have warned the developer during baseline?

**Comment by bjhargrave** [comment]
Short answer: No. The declared exceptions are not part of method signatures and thus not part of binary compatibility. The VM does not care. Changes to declared exceptions is only a potential source compatibility issue. See <https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.4.21>.

Baselining is about binary compatibility not source compatibility.

**Comment by rotty3000** [comment]
Would you entertain another level of warnings that cover source compatibility issues?

**Comment by bjhargrave** [comment]
But the compiler handles source compatibility issues. You get compilation failures.

**Comment by bjhargrave** [comment]
Also what about unchecked exception changes? Declared or documented? The problem grows pretty big.

**Comment by rotty3000** [comment]
The issue is more about detectable changes the developer could be warned about.

**Comment by bjhargrave** [comment]
But if I change a method to now throw some new unchecked exception, how should the developer be warned?

**Comment by rotty3000** [comment]
... I don't have a good answer otherwise I would have simply sent a PR. I'm appealing to greater minds for help. And I mean warning the developer who made the change of course (the way baseline typically does).

**Comment by bjhargrave** [comment]
Baselining it to catch syntactlc changes which break binary compatibility. There are also semantic changes which also can break binary compatibility and changes which preserve binary compatibility but break source compatibility. I don't think we can help with all possible breaking changes. Changes to thrown exceptions, checked or unchecked, can be either nothing, a source compatibility change or a binary compatibility change. It would be hard for a tool to distinguish.

Baselining focuses on syntactlc changes which break binary compatibility which can be done without false positives or false negatives. Other changes are more subject to false positives and false negatives (see findbugs for example).

**Comment by rotty3000** [comment]
Got it, thx!

**Comment by fhuberts** [comment]
It is a breaking change: behaviour changed.
