### ISSUE TITLE
Bnd is using maven connection settings without any opt-in

### ISSUE THREAD

**Issue by brampouwelse** [bndtools/bnd#1880]
Took me a while to realize why my workspaces were unresponsive and broken, eventually figured out it was caused by bnd re-using the maven settings to determine connection settings. 

Think it would have been not to use these settings as a default for all connections even when you're not using any of the maven features added in the latest bnd versions.

**Comment by bjhargrave** [comment]
Connection settings are independent of use maven 'features'. See <http://bnd.bndtools.org/instructions/connection-settings.html>.

```
The order bnd looks for settings is therefore:

~/.bnd/settings.xml
~/.m2/settings.xml

If you want to disable the use of these mechanisms from the workspace then you can use the -connection-settings instruction. If you set this to false then it will not look for the aforementioned files.

-connection-settings: false


```

**Comment by brampouwelse** [comment]
Thanks for the link not sure why I didn't find this one :( 

Still think it would've been nice if the default was either set to `false` or `bnd` (as I don't use maven in bnd projects I didn't get the relation between maven settings and my workspace not working).

**Comment by bjhargrave** [comment]
I think the thought was either: 1) A person did not use maven and thus had no maven settings. Or 2) the person did you use maven and may have important proxy settings that should be used.

You seem to fall into a rare other case where you maven settings that are bad. In that case you will need to either set -connections-settings to false or point to a file with better settings. (Or delete the bad maven settings.)

**Comment by brampouwelse** [comment]
> You seem to fall into a rare other case where you maven settings that are bad

Think my issue is that I use the same machine for a non bnd Maven project at work and some side projects at home which are bnd non Maven. I didn't expect the Maven settings to break my bnd workspaces

**Comment by bjhargrave** [comment]
So you should set up a `~/.bnd/settings.xml` file to have separate settings for bnd projects.

**Comment by brampouwelse** [comment]
Thx for the tip will try that tomorrow

**Comment by brampouwelse** [comment]
Adding an empty settings file for bnd seems to do the trick, but the documentation for that is wrong (or the code). 

Bnd doesn't look for `~/.bnd/settings.xml` file like stated in the documentation but for a file named `~/.bnd/connection-settings.xml`

Found this constant: 
`private static final String	BND_CONNECTION_SETTINGS_XML	= "~/.bnd/connection-settings.xml";` (in `aQute.bnd.connection.settings.ConnectionSettings`)

**Comment by bjhargrave** [comment]
Can we close this issue now?
