### ISSUE TITLE
bnd-baseline-maven-plugin 3.4.0-SNAPSHOT: Major change detected if the baseline was not annotated

### ISSUE THREAD

**Issue by cdealti** [bndtools/bnd#1890]
This is a follow-up to #1553.

I've started using this plugin late in the development of Kura. This means that the last released version of the Kura API **was not annotated**.

I'm aware that the plugin assumes a type that **was not annotated** in the baseline as an ``@ConsumerType`` but this did not seem to be a problem if that type was later on annotated with ``@ProviderType``.

At least for Java interfaces, adding a method to an ``@ProviderType`` is detected as a MINOR change. In this case the plugin seems to honor the **explicit** ``@ProviderType`` annotation I've added on the develop branch and not the **implicit** ``@ConsumerType`` annotation in the baseline. Otherwise it would have detected a MAJOR change (adding a method to an ``@ConsumerType`` is a breaking change for consumers).

This behavior is OK, at least for me, because it lets me to use the last released API (not annotated) as the baseline.

In #1553 I've found by accident an issue with classes. In one of our Kura refactor on the develop branch we changed the visibility of a protected field to private and the plugin detected a MAJOR change. After a short discussion, the Bnd committers decided that this is a MINOR change if the class is **explicitly** annotated as an ``@ProviderType``.

However, my build still complains that this is a MAJOR change (I've updated the Bnd plugins in my build to the latest SNAPSHOT build). @timothyjward suggests that this is due to my baseline not being annotated.

The question is why in this case the plugin honors the **implicit** ``@ConsumerType`` of the baseline and not the **explicit** ``@ProviderType`` I've added in the develop branch.

**Comment by bjhargrave** [comment]
In some ways you are fighting the tool. If your baseline is incorrect, in that some types should have been marked as provider types, then fix your baseline. That is, create a special version of your last release to use to baseline the release under development. You wont need to do this next time since your release under development will be properly marked.

**Comment by cdealti** [comment]
You are right. I've finally annotated the baseline and it seems to work as expected.
This can be closed.

**Comment by cdealti** [comment]
I have to reopen this issue as [this commit](https://github.com/bndtools/bnd/commit/b0bec68cfb9d74a10e95fd5c04029b38eb41e3c7) seems to have caused a regression.

How to recreate:
1. Clone [Kura](https://github.com/eclipse/kura/) 
2. Checkout the KURA_3.0.0_RELEASE tag
3. Build with build-all.sh

This used to work with all the latest builds of the baseline plugin until build 1403.  [Build 1404](https://bndtools.ci.cloudbees.com/job/bnd.master/1404/) causes the Kura API baseline verification to fail (see log below).

The baseline for the Kura API is [this](https://github.com/eclipse/kura/tree/maintenance-2.1.0/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura)

It looks like the baseline plugin now detects a MAJOR change in exceptions extending  KuraException even if the change in base class is only MINOR.

See also this [pull request](https://github.com/bndtools/bnd/pull/1858/commits/eeac85654658b47c3c47de5ad1cd36785eb753cd)

```
[ERROR] Baseline mismatch for package org.eclipse.kura, MAJOR change. Current is 1.3.0, repo is 1.2.2, suggest 2.0.0 or -
MAJOR                PACKAGE    org.eclipse.kura
  MAJOR              CLASS      org.eclipse.kura.KuraConnectException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MINOR              CLASS      org.eclipse.kura.KuraException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MAJOR              CLASS      org.eclipse.kura.KuraInvalidMessageException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MAJOR              CLASS      org.eclipse.kura.KuraInvalidMetricTypeException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MAJOR              CLASS      org.eclipse.kura.KuraNotConnectedException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MAJOR              CLASS      org.eclipse.kura.KuraPartialSuccessException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MINOR              CLASS      org.eclipse.kura.KuraRuntimeException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MAJOR              CLASS      org.eclipse.kura.KuraStoreCapacityReachedException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MAJOR              CLASS      org.eclipse.kura.KuraStoreException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MAJOR              CLASS      org.eclipse.kura.KuraTimeoutException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MAJOR              CLASS      org.eclipse.kura.KuraTooManyInflightMessagesException
    REMOVED          FIELD      m_code
      REMOVED        ACCESS     protected
      REMOVED        RETURN     org.eclipse.kura.KuraErrorCode
  MINOR              ENUM       org.eclipse.kura.KuraErrorCode
    ADDED            FIELD      PROCESS_EXECUTION_ERROR
      ADDED          ACCESS     final
      ADDED          ACCESS     static
      ADDED          RETURN     org.eclipse.kura.KuraErrorCode
    ADDED            FIELD      SUBSCRIPTION_ERROR
      ADDED          ACCESS     final
      ADDED          ACCESS     static
      ADDED          RETURN     org.eclipse.kura.KuraErrorCode
  REMOVED            VERSION    1.2.2
  ADDED              VERSION    1.3.0
```

**Comment by rotty3000** [comment]
Can you explain the class hierarchy change so I can build a test case?

Also, the reference PR/change by Tim contains a test case which still
passes after the this latest change. I'd like to clarify the exact Kura use
case.

**Comment by bjhargrave** [comment]
@rotty3000 The issue is here: https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/differ/JavaElement.java#L351

The removed Delta is always MAJOR even when the child is a protected field and the class it is in is marked @ProviderType.

**Comment by rotty3000** [comment]
got it! nice catch... I even doubted myself when I set the remove detla. I will test the change and may add more predicates around what type of change is applied.

**Comment by bjhargrave** [comment]
I am concerned this is still a work-in-progress and we should back #2092 out of 3.4 and finish it for 3.5.

**Comment by rotty3000** [comment]
.. if all else fails... we can again resort to backing off the whole change for 3.4.0.REL

**Comment by rotty3000** [comment]
in fact it might be wise to simply back it out! I'm ok with that too. I can work on a more complete solution! @cdealti I'd still like a more specific description of the change so I can work on a test case.

**Comment by bjhargrave** [comment]
OK, I will revert #2092.

**Comment by rotty3000** [comment]
thx @bjhargrave !

**Comment by cdealti** [comment]
> @cdealti I'd still like a more specific description of the change so I can work on a test case.

The change to the `org.eclipse.kura.KuraException` happened in [this commit](https://github.com/eclipse/kura/commit/db0aeef0bc239d132c1ef6d54554d11bbc6d1938) where `protected KuraErrorCode m_code` was changed to `private final KuraErrorCode code`. This is still correctly detected as a MINOR change (see log above).

What is strange is that the baseline plugin detects MAJOR changes in the subclassess of KuraException, for example `org.eclipse.kura.KuraConnectException`.

The `KuraException` baseline is [here](https://github.com/eclipse/kura/blob/maintenance-2.1.0/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/KuraException.java)

The `org.eclipse.kura.KuraConnectException` baseline is [here](https://github.com/eclipse/kura/blob/maintenance-2.1.0/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/KuraConnectException.java) 

The `KuraException` of KURA_3.0.0_RELEASE is [here](https://github.com/eclipse/kura/blob/KURA_3.0.0_RELEASE/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/KuraException.java)

The `org.eclipse.kura.KuraConnectException`  of KURA_3.0.0_RELEASE is [here](https://github.com/eclipse/kura/blob/KURA_3.0.0_RELEASE/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/KuraConnectException.java)

**Comment by cdealti** [comment]
3.4.0 works just fine for us. Thanks
