### ISSUE TITLE
Wikipage for installing bnd on Windows somewhat outdated: jpm command line available on Windows

### ISSUE THREAD

**Issue by ndcroos** [bndtools/bnd#1899]
The information on this wikipage (https://github.com/bndtools/bnd/wiki/Install-bnd-on-the-command-line) regarding the installation of bnd command line is outdated. 
One can find instructions to install JPM here: http://jpm4j.org/#!/md/windows.

The information on the wikipage regarding this should be replaced with a link to http://jpm4j.org/#!/md/windows.

**Comment by bjhargrave** [comment]
This should point to brew to install bnd for Mac.

**Comment by rotty3000** [comment]
Closing as no longer relevant.
