### ISSUE TITLE
Support generating a properties file for metatype annotations

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#1905]
To ease translating the metatype resources it would be nice to (optionally) generate a `<metatype>.xml` together with the according `<metatype>.properties` file.
For that it is required to replace the `name` , `label` and `description` attribute values (OSGi 6 Compendium §105.7)  by artificial values starting with `%`. Those artificial values must then be used as keys in the properties file (OSGi 6 Core §3.11). The original values should be used as English values. This was done also by the `maven-scr-plugin` (for the Felix SCR annotations, see https://issues.apache.org/jira/browse/FELIX-4378)

**Comment by bjhargrave** [comment]
What are "manifest annotations" and "<manifest>.xml"? Do you mean metatype?

**Comment by kwin** [comment]
Yes, indeed. I fixed the description of this ticket accordingly. This is about metatypes not manifests.

**Comment by bjhargrave** [comment]
I looked at the Felix issue and I am not clear on what it was suggesting since the link to some example code on github is broken. Can you please put some examples of what you want in this issue? Thanks.

**Comment by kwin** [comment]
You can find the source code from maven-scr-plugin in https://github.com/apache/felix/blob/b96eac8c610db6c0cdf060d9b53135739602c34f/tools/org.apache.felix.scr.generator/src/main/java/org/apache/felix/scrplugin/xml/MetaTypeIO.java#L81. Basically it will always generate a properties file for all labels, names and descriptions, if not at least one of them are already starting with a "%" or there is a properties file already existing.

I would propose that the generation of the properties file should be configurable in bnd.

**Comment by bjhargrave** [comment]
OK, sounds like a substantial new feature. PRs welcome!
