### ISSUE TITLE
launcher: does not run under compact1 profile

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#1919]
The bnd launcher uses the compact3 profile for its agent (see below).

I'd really like the bnd launcher to run under the compact1 profile.

Would it be possible that the agent part is split off, be an extension/plugin, or that there be different launchers - one with and one without the agent?

```
$ jdeps -P jar/biz.aQute.launcher-3.3.0.jar |grep -vE '(compact1|biz.aQute.launcher-3.3.0.jar|not found)$'
biz.aQute.launcher-3.3.0.jar -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-1.b14.fc25.x86_64/jre/lib/rt.jar (compact3)
   aQute.launcher (biz.aQute.launcher-3.3.0.jar)
      -> java.lang.instrument                               compact3
   aQute.launcher.agent (biz.aQute.launcher-3.3.0.jar)
      -> java.lang.instrument                               compact3
   aQute.launcher.constants (biz.aQute.launcher-3.3.0.jar)
   aQute.launcher.minifw (biz.aQute.launcher-3.3.0.jar)
   aQute.launcher.plugin (biz.aQute.launcher-3.3.0.jar)
   aQute.launcher.pre (biz.aQute.launcher-3.3.0.jar)
   aQute.lib.collections (biz.aQute.launcher-3.3.0.jar)
   aQute.lib.hex (biz.aQute.launcher-3.3.0.jar)
   aQute.lib.io (biz.aQute.launcher-3.3.0.jar)
   aQute.lib.strings (biz.aQute.launcher-3.3.0.jar)
   aQute.lib.utf8properties (biz.aQute.launcher-3.3.0.jar)
   aQute.libg.cryptography (biz.aQute.launcher-3.3.0.jar)
   aQute.libg.glob (biz.aQute.launcher-3.3.0.jar)
   aQute.libg.tuple (biz.aQute.launcher-3.3.0.jar)
```

**Comment by bjhargrave** [comment]
I think perhaps we just wrap the references to the instrumentation code in `aQute.launcher.Launcher` in a `try/catch(NoClassDefFoundError)` block so that of the Instrumentation class is not present, we just ignore the `LauncherAgent`.

**Comment by fhuberts** [comment]
If so, then make it very clear somewhere that this is done this way, because jdeps will then still hapily indicate compact3

**Comment by bjhargrave** [comment]
Jdeps will still complain since the reference will still be in the bytecode. But the code should run on compact1 which is your desire I think.

**Comment by fhuberts** [comment]
I know.
I'm asking for it to be documented in the bundle, like a README, or in the MANIFEST, or anywhere

**Comment by bjhargrave** [comment]
OK. Can you first confirm the try/catch block actually works for compact1 first?

**Comment by fhuberts** [comment]
I'm not a bnd dev

**Comment by bjhargrave** [comment]
Well if you don't care about this, I can just close the PR and issue.

**Comment by fhuberts** [comment]
That is not a correct conclusion.
I filed the bug for a very good reason, but I have no time to go digging through the code.
I'm not a bnd dev, and you know that very well.

**Comment by fhuberts** [comment]
Ah, that is confusing.
It was not clear that you already made this a PR; should have said so

**Comment by fhuberts** [comment]
I'll try it later this week; busy now.
