### ISSUE TITLE
Stream issues marked as Security Vulnerability not properly closed

### ISSUE THREAD

**Issue by bsulich2** [bndtools/bnd#1929]
Found some issues in the code, where stream is open, but not properly closed.

1. [Workspace.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java#L688)
2. [Jar.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java#L93)
3. [Repository.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/bnd/jpm/Repository.java#L807)
4. [HttpBasicAuthURLConnector.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/bnd/deployer/http/HttpBasicAuthURLConnector.java#L183)
5. [SpringComponent.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/lib/spring/SpringComponent.java#L47)
6. [Builder.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L117)
7. [Project.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L2869)
8. [OSGI_CORE.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/model/OSGI_CORE.java#L15)

List above point to lines in classes where I found problems.
Most of them I fixed in branch (is inPullRequests). 
According to classes listed above:
 - 1, 2, 3, 5, 6, 7, 8 are fixed within the same class

 - 4 is fixed in [CachingUriResourceHandle.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/bnd/deployer/repository/CachingUriResourceHandle.java#L198)

**Comment by bjhargrave** [comment]
> 1- Workspace.java:688 - didn't fix. Could you tell me where is this stream closed? Is this class used in runtime, or only by the bnd plugin for maven/gradle?

This appears to just need a similar fix as https://github.com/bndtools/bnd/pull/1930/files#diff-d42bdfe7f7601ee1423a8e5e7bb6c022
