### ISSUE TITLE
consider automating -runrequires and -distro

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1935]
@gamerson and I have considered possibility of further simplifying the details in bndrun files.

The idea was to declare dependency scopes which map to `-runrequires` and `-distro`.

This could help reduce duplication of information in the bndrun file when using maven or gradle.

**Comment by rotty3000** [comment]
The scopes could be `required` and/or `distro`. Of course this could only be used by gradle.builder and maven plugins.

**Comment by njbartlett** [comment]
What are you suggesting? This is too vague.

**Comment by rotty3000** [comment]
.. it may be ;)

The information contained in the `-runrequires` instruction is often duplicated with respect to the dependencies defined in the project.

If the dependency could simply be included with a scope of, for example, `required`:
e.g.
```
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.0</version>
			<scope>required</scope>
		</dependency>
```

then the plugin could infer that into the `-runrequires`.

... in fact, now that I think of it, we could simply use the `runtime` scope as the input to the `-runrequires`.

**Comment by njbartlett** [comment]
That's an interesting idea, but I'm not comfortable with -runrequires being magically inferred from somewhere else. Bnd would need some instruction to tell it to read -runrequires from the POM rather than (or in addition to) the bndrun file.
