### ISSUE TITLE
Better support Export-Package  include/exclude patterns .

### ISSUE THREAD

**Issue by sesuncedu** [bndtools/bnd#1943]
They can be rather useful when trying to gradually retro-modularize an existing code-base, especially when a class name string is part of the public api (for example non-DataSourceFactory   jdbc drivers). 

For example, when checking to see if an exported package references a private package, only the packages used by the classes that make it through the filter are relevant (actually, probably just the classes that are part of the public signature). Baselining should also use the filters when deciding whether and by how much a package should be bumped. 

This change looks like it  might be a bit of a pain; in the places where inclusion/exclusion is most relevant, the information about which classes are exported does not seem to be available, and only PackageRefs are at hand.  I'm not sure how   expensive to keep the necessary back-references around till they're needed. .

**Comment by rotty3000** [comment]
Do you mean like in section 3.7.9 of the OSGi Core specification: *Class Filtering*?

> An exporter can limit the visibility of the classes in a package with the include and exclude direc-
> tives on the export definition. The value of each of these directives is a comma-separated list of class
> names. Note that the use of a comma in the value requires it to be enclosed in double quotes.
> Class names must not include their package name and do not end with .class. That is, the class
> com.acme.foo.Daffy is named Daffy in either list. The class name can include multiple wildcard as-
> terisks ('*' \u002A).
> The default for the include directive is an asterisk ('*' \u002A) (wildcard matching all names), and
> for the exclude directive, so that no classes are excluded, an empty list that matches no names. If in-
> clude or exclude directive are specified, the corresponding default is overridden.

e.g.
```
Export-Package: com.acme.foo; include:="Qux*,BarImpl"; exclude:=QuxImpl
```

**Comment by sesuncedu** [comment]
Yes. It's a to do in the code, but there are comments suggesting it's not
best practice. It looks like the change might have a lot of ripple effects
, so I'm wondering if it's been tried before ?

**Comment by rotty3000** [comment]
So we understand each other, I think the only limitation here will have to do with bnd's generated uses constraints, right? The other side of this is already supported by frameworks since it's in the core spec.

**Comment by rotty3000** [comment]
I believe this cannot have any effect on imports because we cannot know for sure that the classes excluded from export are not used by those which are included for export and so their imports are still required, no?

**Comment by sesuncedu** [comment]
I believe the excluded  classes are packaged and scanned for imports, and
that this wouldn't be broken. The 'uses' directive gets filled in with
packages from all classes... including  private packages from this bundle,
which triggers a warning, and possibly errors.

I'm not 100% sure what a resolver does if there's a uses clause for a
private package, especially if the package was exported in an older
version.

Exclude/include are messy, but they seem very useful during a transition
period. It's like an extra stage between depreciation and deletion :)


>

**Comment by bjhargrave** [comment]
I don't think we want to support include/exclude on Export-Package. That exist in the OSGi spec for legacy packages which were poorly designed and included implementation classes which should never have been in the package used as API.

**Comment by sesuncedu** [comment]
Think of it as methadone (method-own? :-)

I guess a way of different way of not supporting class filtering would be a
flag to suppress some warnings if there's a include/exclude directive
present, plus a warning not to rely on them,and a list of the headers that
might be wrong.

**Comment by bjhargrave** [comment]
You can suppress warnings/errors with `-fixupmessages`.

You can turn off uses with `-nouses`.

**Comment by bjhargrave** [comment]
May need to update verifier to not complain about include/exclude directives on Export-Package statement.

**Comment by bjhargrave** [comment]
@sesuncedu Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Otherwise, I am unclear as to what need to change. Thanks.

Looking at the analyzer code, everything is package based. Package references, from one package to another, are calculated during the "contained" phase when packages are added to the bundle. This is prior to knowing the exported packages. To change that to handle include/exclude directives for exported package will be a major thing since it will likely require multiple passes over the classes.
