### ISSUE TITLE
-dsannotations generating Require-Capability  

### ISSUE THREAD

**Issue by rimmeraj** [bndtools/bnd#1947]
if -dsannotations: is defined and xml is generated should not

osgi.extender;filter:="(osgi.extender=osgi.component) be added to the Require-Capability header?

**Comment by djencks** [comment]
It does when plausible:

		if (options.contains(Options.extender) || maxVersion.compareTo(AnnotationReader.V1_3) >= 0) {
			maxVersion = ComponentDef.max(maxVersion, AnnotationReader.V1_3);
			addExtenderRequirement(requires, maxVersion);
		}


Plausible means you have a DS 1.3+ component or you’ve indicated you want the extender Require-Capability anyway by specifying

-dsannotation-options:extender

While I wouldn’t mind having the default the other way around, that would be rather inconsistent behavior with old bnd versions.

david jencks

**Comment by rimmeraj** [comment]
If bnd is creating the XML via the -dsannotations how do I specify 1.3 generation?

**Comment by djencks** [comment]
I think 
-dsannotation-options:version;minimum=1.3.0

david jencks

**Comment by rimmeraj** [comment]
It is -dsannotations-options but currently it is only in the head it is not in 3.3 or 3.4 dev tag

**Comment by bjhargrave** [comment]
So is there still a problem here? Or can we close this issue?

**Comment by rimmeraj** [comment]
Only that you have not released 3.4 ;) .. Close this

**Comment by timothyjward** [comment]
Sorry for getting to this late. Can you not use:

    -dsannotations-options: extender

I think that works in bnd 3.3.0
