### ISSUE TITLE
bnd workspace does not build in Eclipse after clean

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1954]
The aQute.junit project seems to have a baseline error that is not reported in eclipse (nor in Gradle btw.) When I fixup all messages or remove baseline the project works fine.

**Comment by bjhargrave** [comment]
There is already a fix up for that in the bnd file. 

https://github.com/bndtools/bnd/blob/master/biz.aQute.junit/bnd.bnd#L18

And it does not baseline the org.junit packages

https://github.com/bndtools/bnd/blob/master/biz.aQute.junit/bnd.bnd#L33

**Comment by pkriens** [comment]
I just found out by starting the debugger ...
