### ISSUE TITLE
Allow to pass merged instructions to the Bnd Builder Gradle Plugin

### ISSUE THREAD

**Issue by Ithildir** [bndtools/bnd#1966]
It's currently impossible to pass a merged instruction like this:
```gradle
jar {
	manifest {
		attributes('-includeresource.foo': 'foo.txt')
	}
}
```

Gradle complains that the attribute name is invalid:
```
The Key=-includeresource.foo violates the Manifest spec!
```

**Comment by bjhargrave** [comment]
Sorry, but there is nothing that can be done to fix this. It is check right in the `java.util.jar.Attributes.Name` class which is used by the Gradle Jar task's manifest DSL.

You will need to use a bnd file to specify property names with `.` in them.

**Comment by Ithildir** [comment]
Hi @bjhargrave,
I sent you a [pull](https://github.com/bndtools/bnd/pull/1968) which adds a new convention property to the `jar` task: a simple map that people can use to provide additional instructions.

**Comment by bjhargrave** [comment]
> I sent you a pull which adds a new convention property to the jar task: a simple map that people can use to provide additional instructions.

We already have the bnd file to use to add instructions. I do not want to add a 3rd way.

**Comment by Ithildir** [comment]
I see! I guess I'll find another way.

Thanks for your time anyway 😊

**Comment by bjhargrave** [comment]
> I guess I'll find another way.

The other way is to use a bnd file :-)

**Comment by Ithildir** [comment]
Unfortunately it's not that easy 😞 I wrote a Gradle plugin which applies the Bnd one and adds some features. One of these is to automatically add a `-includeresource.libs` at runtime based on the dependencies added to a specific Gradle configuration. I'm using `-includeresource.libs` and not `-includeresource` because I can't assume people didn't add a `-includeresource` in their `bnd.bnd` so I have to avoid conflicts.
