### ISSUE TITLE
Bnd OSGi test launcher ignore Tests inside test.fragments

### ISSUE THREAD

**Issue by jwausle** [bndtools/bnd#1970]
My annotated RunWith-Tests ignored if I declare them inside a test.fragment.
- Same Tests works well inside real test.bundle.

bnd-3.3.0 with gradlew

## Buggy-setup (tests ignored)
- host.bundle/bnd.bnd
>  Bundle-SymbolicName: host.bundle

- fragment.bundle/bnd.bnd
> Fragment-Host: host.bundle
> Test-Cases: ${classes;CONCRETE;ANNOTATED;org.junit.runner.RunWith}

## Workaround-setup (tests executed)

- host.bundle/bnd.bnd
> -sub: *.bnd
- host.bundle/host.bnd
>  Bundle-SymbolicName: host.bundle
- host.bundle/fragment.bnd
> Fragment-Host: host.bundle
> Export-Package: host.bundle.internal.*

- test.bundle/bnd.bnd
> Test-Cases: ${classes;CONCRETE;ANNOTATED;org.junit.runner.RunWith}

## Background
- I want to get access to my internal classes while bundle-testing like in RCP-development.

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bnd/pull/2035
