### ISSUE TITLE
Confusing eclipse warning: Found source folder ’src/main/resources'  is not bnd`s source path.

### ISSUE THREAD

**Issue by jwausle** [bndtools/bnd#1972]
I get multiple "Found source folder ..." eclipse warnings if I declare multiple source folder in 'bnd.bnd' and '.classpath' 

**.classpath**
```
        <classpathentry kind="src" path="src/main/java"/>
        <classpathentry kind="src" path="src/main/resources"/>
        <classpathentry kind="output" path="target/classes"/>
        <!-- TEST SOURCES -->
        <classpathentry kind="src" output="target/test-classes" path="src/test/java"/>
        <classpathentry kind="src" output="target/test-classes" path="src/test/resources"/>
        <classpathentry kind="src" output="target/test-classes" path="src/test/java-smoke"/>
```

**bnd.bnd**
```
src = src/main/java,src/main/resources
bin = target/classes
testsrc = src/test/java,src/test/java-smoke,src/test/resources
testbin = target/test-classes
target-dir=target

-----------------
Description	Resource	Path	Location	Type
Bndtools: Found source folder 'src/test/java-smoke' that is not on bnd's source path 'src/main/java,src/main/resources'	bnd.bnd	/com.qivicon.gateway.messagingadapter	line 12	Bndtools Path Problem Marker
Bndtools: Found source folder 'src/test/java' that is not on bnd's source path 'src/main/java,src/main/resources'	bnd.bnd	/com.qivicon.gateway.messagingadapter	line 12	Bndtools Path Problem Marker
Bndtools: Found source folder 'src/test/resources' that is not on bnd's source path 'src/main/java,src/main/resources'	bnd.bnd	/com.qivicon.gateway.messagingadapter	line 12	Bndtools Path Problem Marker
```

**Comment by bjhargrave** [comment]
This is a bndtools message. So you should open an issue in the bndtools repo.

Bndtools verifies that each source folder in .classpath is also reflected in the `src` property in the Bnd project. Including test folders.

**Comment by jwausle** [comment]
:( I have also that multi-language setup.

```
testsrc = src/test/java,src/test/groovy
```

Exist or It is possible to create feature request for that.

**Comment by bjhargrave** [comment]
At this point there are no plans to support more than one test source folder in Bnd Workspace projects. You might wish to create multiple projects to host each test source folder if you cannot combine them.

We do have an open issue to support separate resource folders, https://github.com/bndtools/bnd/issues/1466, but I do not think this will make 3.4 as I plan to focus on OSGi R7 support items first.

**Comment by bjhargrave** [comment]
In #1466, we have reached the conclusion that supporting multiple test source folders is necessary.
