### ISSUE TITLE
P2Repository cache not updated after change of url.

### ISSUE THREAD

**Issue by jwausle** [bndtools/bnd#1974]
If I change my P2Repositry.url to a new one with same bundles with another version inside
Than the 'cnf/cache' and 'downloaded-runbundles' contains always the previous(old) bundles after `gradle runbundles` execution.

### howto reproduce

P2 repos
```
http://p2repo/unzipped/1.0/plugins
- bundle-1.0.jar

http://p2repo/unzipped/2.0/plugins
- bundle-2.0.jar
```
cnf/build.bnd
```
-plugin.p2-repo: aQute.bnd.repository.p2.provider.P2Repository; \
       name = "p2-repo"; \
       url = "http://p2repo/unzipped/1.0"
```

project/bnd.bndrun
```
-runbundles: bundle
```

`# gradle clean runbundles`
- cache bundle 'cnf/cache/p2-repo/bundle-1.0.jar'
- download bundle 'project/generated/distributions/runbundles/bnd/bundle-1.0.jar

**Update** 'cnf/build.bnd'
```
-plugin.p2-repo: aQute.bnd.repository.p2.provider.P2Repository; \
       name = "p2-repo"; \
       url = "http://p2repo/unzipped/2.0"
```
- `url = http://p2repo/unzipped/`**2.0**

`# gradle clean runbundles` again
- **still** bundle 'cnf/cache/p2-repo/bundle-1.0.jar' is cached (**not bundle-2.0.jar**)
- **still** bundle 'project/generated/distributions/runbundles/bnd/bundle-1.0.jar' is downloaded (**not bundle-2.0.jar**)

### quickfix
`# rm -rf cnf/cache/p2-repo`
`# gradle clean runbundles` :)

**Comment by bjhargrave** [comment]
You need to make a clean task for your cnf project. See https://github.com/bndtools/bnd/blob/master/cnf/build.gradle

**Comment by jwausle** [comment]
Thanks @bjhargrave. That`s a quickfix right? 

In general: 
- I don`t want to clean the cache on every 'clean' run or maintain a separate clean-cache task
- I would expect that bnd can handle this correct. (maybe I´m wrong)
- Update of P2Repository.url trigger delete all regarding cached JARs

**Comment by bjhargrave** [comment]
It is the fix. You ran clean to reset to the original state, that should include any caches, no? `git clean -dfx` would also clean the cache. 

If you change the URL of the repo and don't also change the name of the repo, `name = "p2-repo"`, then you have two repos (old URL and new URL; they are distinct repos) sharing the same cache (based on repo name). So you should clean the cache upon changing repos (URLs) or use a different cache (repo name).

**Comment by bjhargrave** [comment]
#1975 adds a `:cnf:cleanCache` task. The `:cnf:clean` task will dependOn the `:cnf:cleanCache` task unless gradle is `--offline`. You can also avoid the `:cnf:cleanCache` task by `-x cleanCache` in the command line:

```
./gradlew -x cleanCache clean build
```

**Comment by fhuberts** [comment]
That is extremely inconvenient since I use "gradle clean build" to force a clean build before I commit.
Doing that offline will blow away my cache and break my build.
Please make clean NOT depend on cleanCache.

**Comment by bjhargrave** [comment]
I discussed this with @rotty3000 and we thought this was OK. But feedback from others would be good.

`gradle --rerun-tasks` is probably a saner choice or `git clean` to get a really clean build. I never really trust `gradle clean`.

**Comment by fhuberts** [comment]
Well on jenkins I do a git clean, but offline I do not...

**Comment by bjhargrave** [comment]
Besides, if you really want a clean build, you should start with an empty cache like your CI system probably does.
