### ISSUE TITLE
Support wildcard in "bndrun" config of testing, resolve and export Maven plugins.

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1995]
The bnd-testing-maven-plugin, bnd-resolve-maven-plugin and bnd-export-maven-plugin all require a list of bndrun files, configured in the POM as:

    <bndruns>
        <bndrun>example.bndrun</bndrun>
    </bndruns>
It would be useful to support wildcards here, e.g.:

    <bndrun>*.bndrun</bndrun>

**Comment by bjhargrave** [comment]
I have proposed getting rid of `<bndruns>` and just have a single `<bndrun>`. Then if you have multiple bndrun files, you have multiple `<execution>`s. This is because of the change in #1978 to use the FileSetRepo. Each execution may need a different set of bundles. See https://github.com/bndtools/bnd/pull/1978#discussion_r110029820

**Comment by bjhargrave** [comment]
This was discusses in the Bndtools call on Apr 14.

* The solution needs to also support directory globbing as well. For example, `**/*.bndrun`. @pkriens suggests using the https://github.com/bndtools/bnd/blob/master/aQute.libg/src/aQute/lib/fileset/FileSet.java class to implement.
* The solution should also support the same globbing for the `<bundle>` configuration as well. This was recent added.

Someone will need to make a PR with a proposed solution.

**Comment by bjhargrave** [comment]
The PR changes the default for `<bndruns>` to 

```
<bundruns>
    <include>*.bndrun</include>
</bndruns>
```
`<bndrun>` still specified a file for backwards compatibility. But you now use `<include>` and `<exclude>` child elements to specify Ant-style glob patterns instead of or in addition to `<bndrun>`.

**Comment by stbischof** [comment]
Thank you! This is really helpful.

Is there a way to recalculate the index after each bndrun?
That i can generate a Subsystem eas and include it into the second bndrun generated subsystem?

Or is that to hard?
regards

**Comment by bjhargrave** [comment]
I think the indexer plugin runs before the exporter plugin.
-- 
BJ
