### ISSUE TITLE
Support abbreviated syntax for -runrequires

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#1996]
We have more and more users who need to edit bndrun files outside Bndtools. Unfortunately the syntax of -runrequires is very cumbersome for direct editing, being based on the full specification of a Require-Capability header.

We should introduce an optional abbreviated syntax for the most common case of requiring a bundle by bsn and version. I'm open to suggestions but propose something like:

    -runrequires:  bundle; bsn=org.example.foo; version=1.2

This does not require changing the parser, since it is still a valid requirement. It just needs post-processing to translate the namespace and filter expression.

**Comment by timothyjward** [comment]
I think it might be better to make the namespace `bnd.bundle` as requirements are a global namespace. Otherwise I think that looks reasonable. Perhaps we should include an option for giving a GAV?

**Comment by njbartlett** [comment]
I'm trying to keep it lightweight, and in that light the `bnd.bundle` namespace seems overcautious.

Using a GAV is intriguing but I'm not sure how we could translate it to a requirement that would resolve against the index?

**Comment by rotty3000** [comment]
Have you guys considered this one? https://github.com/bndtools/bnd/issues/1935

**Comment by bjhargrave** [comment]
This issue was discussed in the Bndtools call on Apr 14.

* A solution would need support in BndEditModel including round-tripping.
* Since the new syntax would not be a normal requirements, we may need the bnd file using it to require a version of Bnd which supports the abbreviated syntax.
* Bnd must fully document the syntax and how it maps onto the specific OSGi namespaces.

Someone will need to make a PR with a proposed solution.

**Comment by njbartlett** [comment]
@bjhargrave I disagree with the second point. The proposed syntax above is perfectly valid for a requirement, it simply describes an arbitrary namespace ("bundle") that is not currently known.

In an older version of bnd it will fail to resolve, but it will still parse and be handled cleanly by all the editors and formatters.

I envision this as a kind of shortcut namespace that is translated to a standard namespace. "bundle" becomes "osgi.identity" or "osgi.wiring.bundle", etc.
