### ISSUE TITLE
bnd-maven-plugin: Do no longer generate the full JAR in memory

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#2013]
Currently the `bnd-maven-plugin` always creates the full JAR (in-memory) and extract those resources from it, which have been modified. This process not only consumes a lot of memory but is also a lot slower than necessary. It would be best if `bnd` would have dedicated API methods to allow to separate the steps of 

1. creating/extending metadata (incl. manifest, service descriptors and metatype resources)
2. creating the JAR out of the resources being created in 1.) and the resources contributed somewhere else (e.g. java compiler)

That way only a) would need to be leveraged from the `bnd-maven-plugin`.

**Comment by pkriens** [comment]
bnd does not build the Jar in memory. The majority of resources remain on the file system so there is no extra overhead. The Jar object is used as the work list of items but does usually not contain the actual items.

Trying to split this as you suggest would just be more work without any gain.

**Comment by bjhargrave** [comment]
Also, the bnd-maven-plugin does both 1 and 2. It copies resource in to target/classes folder.
