### ISSUE TITLE
Dependency problem when snapshot of artifact to be built exists

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#2024]
(1) I have a project that produces artifact `org.jgrapes.core` (in group `org.jgrapes`) as an OSGi compliant library bundle by applying `biz.aQute.bnd.builder`
(2) A snapshot `org.jgrapes.core-0.9.0-SNAPSHOT` has been uploaded to sonatype snapshot repository during development
(3) Now I want to build (and eventually upload) `org.jgrapes.core-0.9.0`

However, every attempt to invoke gradle results in the following error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':org.jgrapes.core'.
> Could not resolve all dependencies for configuration ':org.jgrapes.core:detachedConfiguration1'.
   > Project :org.jgrapes.core declares a dependency from configuration 'detachedConfiguration1' to configuration 'default' which is not declared in the descriptor for project :org.jgrapes.core.
```
The problem is caused by the particular combination of the bnd plugin and the existing snapshot, as indicated by the following observations:
(a) Commenting out `apply plugin: 'biz.aQute.bnd.builder'` fixes the problem
(b) Commenting out the snapshot repository fixes things
(c) Changing the version to be built to something different from 0.9.x fixes things (i.e. problem persists when changing the version to 0.9.1 but goes away when e.g. changing it to 0.8)
(d) Changing the version back to 0.9.0-SNAPSHOT also fixes things

Of course, neither solution works as workaround (not even (b) because in the "real" project, the snapshot repository is required for the build).

I have stripped down my project to the bare essentials for reproducing the problem, here it is:
[BndTest.zip](https://github.com/bndtools/bnd/files/965457/BndTest.zip)

---
bnd version: 3.3.0
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)
Linux artemis 4.10.11-200.fc25.x86_64 #1 SMP
Gradle 3.5

**Comment by bjhargrave** [comment]
The snapshot repository seems to be the confounding factor. If it is configured and the the version of the project is 0.9.0 or higher, then getting the ResolvedConfiguration object causes gradle to throw an unexpected ResolveException.

I fixed the plugin to guard against unexpected ResolveExceptions.

**Comment by mnlipp** [comment]
This makes it sound a bit like a gradle issue, but if I comment out the bnd plugin, it works.

I didn't go into details and you're the expert on this. But what strikes me as odd is that your patch works around an exception that is caused by resolving a baseline configuration. Please note that I'm not using baselining (from what I have understood it doesn't make sense with version below 1.0.0). So there should be no need to resolve a baseline configuration in the first place.

I'm just pointing this out to make sure that the root cause of the problem isn't missed.

**Comment by bjhargrave** [comment]
If you comment out the bnd plugin, then the bnd plugin code does not run and call gradle where it throws the unexpected ResolveException :-)

The Bnd plugin is trying to set up the baseline configuration default (in the `afterEvaluate` closure) if you do not configure the baseline task which is added by applying the Bnd plugin. (If you don't need the Bnd plugin, then not applying it is a good idea.) The `afterEvaluate` closure tries to resolve the most recent jar which is a lower version than the jar being baselined. The `getResolvedConfiguration()` call is not supposed to throw a ResolveException. It is supposed to set hasError() to return true. But this scenario, it does in fact throw a ResolveException which the fix catches.

**Comment by bjhargrave** [comment]
@mnlipp, I made a better fix for this in https://github.com/bndtools/bnd/pull/2030. So please try this out and let me know if you have any issue by opening a new issue.
