### ISSUE TITLE
P2Indexer reloads and reindexes artefacts unnecessarily

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#2027]
There are two components to this problem.

Currently the indexer skips over artefacts URIs which are listed multiple times. This fails to account for instances where the same artefact can be found at multiple URIs, such as with composite repositories.

The solution is to skip based on encountered *id/version pairs* instead of matching URIs. This should be safe, p2 assumes each id/version to be unique within a repository by design and composites have [build checks](https://wiki.eclipse.org/Equinox/p2/Composite_Repositories_(new)#Attributes) to make sure it holds.

The second problem is that even if we already have capability/requirement information in our index, when we refresh the indexer throws this information away and starts from scratch. It would be a lot quicker to only load artefacts which are new to us.

**Comment by bjhargrave** [comment]
> Currently the indexer skips over artefacts URIs which are listed multiple times. This fails to account for instances where the same artefact can be found at multiple URIs, such as with composite repositories.

This seems to be confused. The same URI always points to the same artifact. While the same artifact can be found at multiple URI, each of those URIs is processed. So I do not see a problem here. Processing the same URI multiple times is a waste. But processing each unique URI is necessary since we cannot know in advance they point to the same artifact.

> 
> The solution is to skip based on encountered id/version pairs instead of matching URIs. This should be safe, p2 assumes each id/version to be unique within a repository by design and composites have build checks to make sure it holds.

Based upon my comment above, I don't think this is correct. 

> 
> The second problem is that even if we already have capability/requirement information in our index, when we refresh the indexer throws this information away and starts from scratch. It would be a lot quicker to only load artefacts which are new to us.

Yes, it would be faster as the expense of correctness. There is no guarantee that the artifact for the bsn+version is unchanged and thus you can avoid processing it. For example, the Bndtools build makes a P2 update site each build. So that site has artifacts with the same bsn+version across builds but the artifacts potentially change each build. You would need something stronger like a hash to know the artifact is unchanged and thus can avoid processing again.

**Comment by eliasvasylenko** [comment]
> But processing each unique URI is necessary since we cannot know in advance they point to the same artifact.

Why not? Isn't that exactly the point of storing an id and version in the metadata? To uniquely identify an artefact? According to the [documentation of p2](https://wiki.eclipse.org/Equinox/p2/FAQ) we are supposed to be able to rely on this. (I don't know if there's a formal spec. anywhere?) I don't see why we should second-guess that. If they are *not* unique at any given time then the repo is broken, so it's not bnd's responsibility to support it.

> So that site has artifacts with the same bsn+version across builds but the artifacts potentially change each build.

Ah, well yes artefacts and versions being unique *across multiple builds* is a different matter.

I had thought that with the absence of the concept of snapshot version in OSGi we were supposed to timestamp the version to avoid this problem and ensure (to our best-efforts) they were unique ... but if we can't rely on this then yes we need something better.

> You would need something stronger like a hash to know the artifact is unchanged and thus can avoid processing again.

Yes okay, p2 does store md5 hashes, and are in the middle of upgrading to sha I think, so I'll modify the PR to use those.

**Comment by bjhargrave** [comment]
> > But processing each unique URI is necessary since we cannot know in advance they point to the same artifact.
> 
> Why not? Isn't that exactly the point of storing an id and version in the metadata? To uniquely identify an artefact? According to the documentation of p2 we are supposed to be able to rely on this. (I don't know if there's a formal spec. anywhere?) I don't see why we should second-guess that. If they are not unique at any given time then the repo is broken, so it's not bnd's responsibility to support it.

How can you know in advance that two distinct URIs refer to the same artifact? You cannot until you get the artifacts at each URI to be able to compare them.

**Comment by eliasvasylenko** [comment]
> How can you know in advance that two distinct URIs refer to the same artifact? You cannot until you get the artifacts at each URI to be able to compare them.

Because p2 is supposedly designed to give that guarantee. If a repository contains two different resources at the same time with the same id and version then that repository is broken.

But anyway that's a moot point since I am having to add in a check against md5 to address your other concerns. I hope this is sufficient?

There is now the problem of carrying the md5 hash forward into the indexed capabilities so we can actually check against it.

I'd have preferred to hijack the "osgi.content" capability namespace and put it there but the spec doesn't suggest this is anticipated so it's probably a bad idea. Would there be a problem, in your opinion, with using an internal capability namespace to store the md5 for each resource?

**Comment by bjhargrave** [comment]
Yes, you can probably add a `bnd.p2` capability to the Resource which holds the md5 signature in an attribute.

I am not sure what you are trying to optimize away. The download or the processing of the download?

> Because p2 is supposedly designed to give that guarantee. If a repository contains two different resources at the same time with the same id and version then that repository is broken.

OK, but I don't think that means the same thing as knowing that two distinct URIs refer to the same resource. All that says is that there must not be two distinct URIs referring to the same resource.

**Comment by eliasvasylenko** [comment]
Thanks for the confirmation, I'll use `bnd.p2` as suggested.

It's the redundant re-processing *between-builds* I was originally trying to avoid, since that's what's bothering me in day-to-day use. Being able to use the hashes to skip duplicate downloads within a build is an unanticipated bonus.

I didn't even know there *were* duplicates until I started testing the changes and noticed some unusual behaviour. Turns out well over half the URIs in the main eclipse release/update composite repos refer to duplicates.

The common cause seems to be for composites to have sub-repos for update releases which use the same versions of some of their plugins.

For example, http://download.eclipse.org/eclipse/updates/4.6 contains all the contents of:
- [4.6](http://download.eclipse.org/eclipse/updates/4.6/R-4.6-201606061100/plugins/?d)
- [4.6.1](http://download.eclipse.org/eclipse/updates/4.6/R-4.6.1-201609071200/plugins/?d)
- [4.6.2](http://download.eclipse.org/eclipse/updates/4.6/R-4.6.2-201611241400/plugins/?d)
- [4.6.3](http://download.eclipse.org/eclipse/updates/4.6/R-4.6.3-201703010400/plugins/?d)

Most of the contents are the same for each one! But hey it doesn't really matter any more since the hash awareness will take care of it safely as a side-effect.
