### ISSUE TITLE
Support DynamicImport-Package expansion

### ISSUE THREAD

**Issue by magnet** [bndtools/bnd#2038]
It can be useful to have DynamicImport-Packages fully expanded -- classpath expansion + versioning info to have strong compatibility guarantees while allowing more a more dynamic handling than optional packages (like an optional, greedy reference vs. an optional, reluctant reference in DS).

In [1], @bjhargrave proposed using `resolution:=dynamic` on packages in the `Import-Package` instruction to tell Bnd to move those packages in DynamicImport-Package.

https://groups.google.com/forum/#!topic/bndtools-users/94Wb2uQghf8

**Comment by bjhargrave** [comment]
Fixed by #2039
