### ISSUE TITLE
Update homebrew formula for 3.4

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#2052]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/bnd.rb#L39-L41

**Comment by bjhargrave** [comment]
@njbartlett, this should be done ASAP. Can you work on this?

**Comment by neilxb** [comment]
Unfortunately I'm having some trouble with this. The test command executed by brew causes an NPE:

	$ /usr/local/Cellar/bnd/3.4.0/bin/bnd resolve resolve -b launch.bndrun
	launch.bndrun                                      java.lang.NullPointerException
	-----------------
	Errors
	000: Exception: java.lang.NullPointerException
	        at aQute.bnd.osgi.resource.ResourceUtils.toVersionClause(ResourceUtils.java:549)
	        at biz.aQute.resolve.Bndrun.resolve(Bndrun.java:101)
	        at aQute.bnd.main.ResolveCommand._resolve(ResolveCommand.java:282)
	        ...

**Comment by njbartlett** [comment]
Unfortunately I'm having some trouble with this. The test command executed by brew causes an NPE:

	$ /usr/local/Cellar/bnd/3.4.0/bin/bnd resolve resolve -b launch.bndrun
	launch.bndrun                                      java.lang.NullPointerException
	-----------------
	Errors
	000: Exception: java.lang.NullPointerException
	        at aQute.bnd.osgi.resource.ResourceUtils.toVersionClause(ResourceUtils.java:549)
	        at biz.aQute.resolve.Bndrun.resolve(Bndrun.java:101)
	        at aQute.bnd.main.ResolveCommand._resolve(ResolveCommand.java:282)
	        ...

**Comment by bjhargrave** [comment]
I debugged. The issue is the resolver is returning a null version since the `osgi.identity` capability is malformed in the index. The capability is missing the mandatory type and version attributes

```
    <attribute name="type" value="osgi.bundle"/>
    <attribute name="version" type="Version" value="1.0.0"/>
```

If you fix the index to include these mandatory attributes, it works.

**Comment by njbartlett** [comment]
Thanks, I also found this. I guess that we can also fix bnd to default the version to 0.0.0, to avoid the NPE.

**Comment by njbartlett** [comment]
I have fixed the bnd.rb script but am having some other issues contributing this back to Homebrew. I will need to look at this again tomorrow.

**Comment by njbartlett** [comment]
PR submitted to Homebrew: https://github.com/Homebrew/homebrew-core/pull/16553

**Comment by njbartlett** [comment]
PR accepted by Homebrew.
