### ISSUE TITLE
Detect and "wrap" ordinary non-osgi jars during launch

### ISSUE THREAD

**Issue by Hillrunner2008** [bndtools/bnd#2065]
A feature I find very nice and developer friendly in Karaf is the support for the "wrap protocol" and the "wrap deployer". I would like to propose this be the default for the bnd launcher.

At a high level, I think all that would be required is to check the jar manifest for the bundle symbolic name and version attributes during the generation of the aQute/bnd/build/Project.java runbundles. If a non-osgi jar is found, bnd would be used to generate+cache an osgi-version. The generated bundle would use bnd defaults:

Import-Package *;resolution:=optional
Export-Package all packages from the wrapped jar
Bundle-SymbolicName made up out of the wrapped jar url where all characters that are not in [a-zA-Z_0-9-] are replaced with "_"

Once generated, the path to the osgi version of the bundle would be leveraged instead of the original. 

Relevant Links:
https://ops4j1.jira.com/wiki/display/paxurl/Wrap+Protocol
https://github.com/ops4j/org.ops4j.pax.swissbox/blob/5ad07efb13414ad9f2d8e4e11d08d54eca0ba6c9/pax-swissbox-bnd/src/main/java/org/ops4j/pax/swissbox/bnd/BndUtils.java (see createBundle method)

I will consider contributing a PR if the idea is well received.

**Comment by pkriens** [comment]
I do not think the launcher is the right place. The bnd model is very based on resolving and ensuring a consistent information. Your proposal is a bit of hack. It would basically make it impossible to to use the resolver, which is the direction we generally want to go to. 

However, it could be interesting to make a Bnd Repository that watches a directory with non-OSGi jars and does what you propose. Once the bundles are available as a repository then the resolver works and the rest as well.

So as you propose I do not think it is a good idea, but if you're willing to make a repo it might be interesting.

**Comment by Hillrunner2008** [comment]
Thanks for the feedback Peter.  I've only read small amounts of the bnd code, so the guidance on the best approach to make this useful is appreciated. The high level goal of leveraging some sort of automated wrapping is what I would like to see made possible.
