### ISSUE TITLE
Latest 3.4.0 biz.aQute.bnd.gradle not available in Maven Repository

### ISSUE THREAD

**Issue by prafullp** [bndtools/bnd#2067]
The latest commit which introduces "aQute.bnd.build.Workspace" plugin is not available on maven repository. 

Is this plugin stable and supposed to be used?

**Comment by bjhargrave** [comment]
We have not released 3.4 yet :-) We expect to do so within the next few weeks.

See <https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle#using-the-latest-development-snapshot-build-of-the-bnd-gradle-plugins> for how to test with the latest SNAPSHOT builds.
