### ISSUE TITLE
Felix SCR incompatibities @ObjectClassDefinition

### ISSUE THREAD

**Issue by pun-ky** [bndtools/bnd#2068]
Original issue: https://github.com/Cognifide/gradle-aem-plugin/pull/19#issuecomment-306702547

Is it possible somehow to force BND tool to generate properties which Felix SCR expects at runtime?
I mean 'configureWithInterfaces="true"  

Parser expects it here: https://github.com/snefru/org.apache.felix.scr/blob/master/src/main/java/org/apache/felix/scr/impl/metadata/XmlHandler.java#L291

This will be very helpful...

What is more, when I declare in Kotlin:

```
    @ObjectClassDefinition(
            name = "Posts Service Config",
            description = "Customize endpoint URL for service which is returning posts"
    )
    annotation class Config(

            @get:AttributeDefinition(
                    name = "Data source URL for posts.",
                    description = "Endpoint must return JSON with list of objects containing 'userId', 'id', 'title' and 'body'.",
                    defaultValue = arrayOf(urlDefault)
            ) val url: String
    )
```

then BND tool id generating (missing for instance 'defaultValue' property):

```
<?xml version="1.0" encoding="UTF-8"?>
<metatype:MetaData xmlns:metatype="http://www.osgi.org/xmlns/metatype/v1.2.0" localization="OSGI-INF/l10n/com.example.aem.bundle.services.posts.PostsService$Config">
  <OCD id="com.example.aem.bundle.services.posts.PostsService$Config" name="Posts Service Config" description="Customize endpoint URL for service which is returning posts">
    <AD id="url" type="String" name="Url"/>
  </OCD>
  <Designate pid="com.example.aem.bundle.services.posts.PostsService">
    <Object ocdref="com.example.aem.bundle.services.posts.PostsService$Config"/>
  </Designate>
</metatype:MetaData>
```

but if 

```
    @ObjectClassDefinition(
            name = "Posts Service Config",
            description = "Customize endpoint URL for service which is returning posts"
    )
    interface Config {
        @get:AttributeDefinition(
                name = "Data source URL for posts.",
                description = "Endpoint must return JSON with list of objects containing 'userId', 'id', 'title' and 'body'.",
                defaultValue = arrayOf(urlDefault)
        ) val url: String
    }
```

then it looks properly but is not working because of missing 'configureWithInterfaces="true"'

```
<?xml version="1.0" encoding="UTF-8"?>
<metatype:MetaData xmlns:metatype="http://www.osgi.org/xmlns/metatype/v1.2.0" localization="OSGI-INF/l10n/com.example.aem.bundle.services.posts.PostsService$Config">
  <OCD id="com.example.aem.bundle.services.posts.PostsService$Config" name="Posts Service Config" description="Customize endpoint URL for service which is returning posts">
    <AD id="getUrl" type="String" name="Data source URL for posts." description="Endpoint must return JSON with list of objects containing 'userId', 'id', 'title' and 'body'." default="https://jsonplaceholder.typicode.com/posts"/>
  </OCD>
  <Designate pid="com.example.aem.bundle.services.posts.PostsService">
    <Object ocdref="com.example.aem.bundle.services.posts.PostsService$Config"/>
  </Designate>
</metatype:MetaData>

```

what are possible approaches as workaround to have all properties generated properly and be able to cooperate with SCR?

**Comment by djencks** [comment]
I think you are trying to use a Felix DS extension. For a spec DS component your configuration class needs to be an annotation not a plain interface. If you really need to use a plain interface there are the @DSExt.* annotations in a separate Felix jar whose name I've forgotten, perhaps scr-anno 

David Jencks

**Comment by bjhargrave** [comment]
Closing due to no reply.

**Comment by fabiomgoncalves** [comment]
@pun-ky did you find a solution? We're having the exact same problem, mainly having configuration classes in Kotlin generating all the required XML attributes.

**Comment by pun-ky** [comment]
yep, you have to declare annotation and instead of using annotation property `defaultValue` use java keyword `default` after which you could specify default value.

`interface` approach seems to be just not supported on felix that I have been tested and probably on others too.

**Comment by pun-ky** [comment]
> if you really need to use a plain interface there are the @DSExt.* annotations in a separate Felix jar whose name I've forgotten, perhaps scr-anno

@djencks , I couldn't find such annotations and I doubt if they even exists.

**Comment by djencks** [comment]
> On Jan 18, 2018, at 12:29 PM, Krystian Panek <notifications@github.com> wrote:
> 
> if you really need to use a plain interface there are the @dsext.* annotations in a separate Felix jar whose name I've forgotten, perhaps scr-anno
> 
> @djencks <https://github.com/djencks> , I couldn't find such annotations and I doubt if they even exists
> 
> 
Well, i wrote them, so I’m pretty sure they exist.  For instance http://felix.apache.org/downloads.cgi <http://felix.apache.org/downloads.cgi> points to

http://mirrors.ocf.berkeley.edu/apache//felix/org.apache.felix.scr.ext.anno-1.0.0.jar <http://mirrors.ocf.berkeley.edu/apache//felix/org.apache.felix.scr.ext.anno-1.0.0.jar>

I’ve never used Kotlin  but the @get:AttributeDescription looks odd to me, since I don’t think a java annotation member starts with “get” but is just the name in the annotation.  Is there some way of finding out what the java equivalent of the Kotlin Config annotation originally shown is? Or looking at the byte code and seeing if the java equivalent url() method actually has the @AttributeDefinition annotation?

As I recall specifying a java annotation default has a different effect than specifying defaultValue in the AttributeDefinition annotation.

david jencks
