### ISSUE TITLE
Could not build workspace

### ISSUE THREAD

**Issue by dleangen** [bndtools/bnd#2071]
Could not build workspace in Eclipse nor from Gradle.

Here is the Gradle output:

aQute.bnd.gradle.TestBndPlugin > Bnd Workspace Plugin resolve Test FAILED
    org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: aQute.lib.utf8properties.UTF8Properties.load() is applicable for argument types: (java.io.File, aQute.libg.reporter.slf4j.Slf4jReporter) values: [generated/testresources/workspaceplugin6/test.simple/resolve.bndrun, ...]
    Possible solutions: load(java.io.InputStream), load(java.io.Reader), load(java.io.InputStream), load(java.io.Reader), clear(), clone()

aQute.bnd.gradle.TestBndPlugin > Bnd Workspace Plugin export Test FAILED
    org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: aQute.lib.utf8properties.UTF8Properties.load() is applicable for argument types: (java.util.zip.ZipFile$ZipFileInflaterInputStream, null, aQute.libg.reporter.slf4j.Slf4jReporter) values: [java.util.zip.ZipFile$ZipFileInflaterInputStream@54eb8efb, null, ...]
    Possible solutions: load(java.io.InputStream), load(java.io.Reader), load(java.io.InputStream), load(java.io.Reader), clear(), clone()

aQute.bnd.gradle.TestExportTask > Simple Bnd Export Task Executable Jar Test FAILED
    org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: aQute.lib.utf8properties.UTF8Properties.load() is applicable for argument types: (java.io.File, aQute.libg.reporter.slf4j.Slf4jReporter) values: [/Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/testresources/exporttask1/export.bndrun, ...]
    Possible solutions: load(java.io.InputStream), load(java.io.Reader), load(java.io.InputStream), load(java.io.Reader), clear(), clone()

aQute.bnd.gradle.TestExportTask > Simple Bnd Export Task Runbundles Jar Test FAILED
    org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: aQute.lib.utf8properties.UTF8Properties.load() is applicable for argument types: (java.io.File, aQute.libg.reporter.slf4j.Slf4jReporter) values: [/Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/testresources/exporttask1/runbundles.bndrun, ...]
    Possible solutions: load(java.io.InputStream), load(java.io.Reader), load(java.io.InputStream), load(java.io.Reader), clear(), clone()

aQute.bnd.gradle.TestResolveTask > Simple Bnd Resolve Task Generate -runbundles Test FAILED
    org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: aQute.lib.utf8properties.UTF8Properties.load() is applicable for argument types: (java.io.File, aQute.libg.reporter.slf4j.Slf4jReporter) values: [/Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/testresources/resolvetask1/create.bndrun, ...]
    Possible solutions: load(java.io.InputStream), load(java.io.Reader), load(java.io.InputStream), load(java.io.Reader), clear(), clone()

aQute.bnd.gradle.TestResolveTask > Simple Bnd Resolve Task Same -runbundles Test FAILED
    org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: aQute.lib.utf8properties.UTF8Properties.load() is applicable for argument types: (java.io.File, aQute.libg.reporter.slf4j.Slf4jReporter) values: [/Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/testresources/resolvetask1/same.bndrun, ...]
    Possible solutions: load(java.io.InputStream), load(java.io.Reader), load(java.io.InputStream), load(java.io.Reader), clear(), clone()

aQute.bnd.gradle.TestResolveTask > Simple Bnd Resolve Task Fail On Change Test FAILED
    org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: aQute.lib.utf8properties.UTF8Properties.load() is applicable for argument types: (java.io.File, aQute.libg.reporter.slf4j.Slf4jReporter) values: [/Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/testresources/resolvetask1/changefail.bndrun, ...]
    Possible solutions: load(java.io.InputStream), load(java.io.Reader), load(java.io.InputStream), load(java.io.Reader), clear(), clone()

aQute.bnd.gradle.TestResolveTask > Simple Bnd Resolve Task Resolve Fail Test FAILED
    org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: aQute.lib.utf8properties.UTF8Properties.load() is applicable for argument types: (java.io.File, aQute.libg.reporter.slf4j.Slf4jReporter) values: [/Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/testresources/resolvetask1/resolvefail.bndrun, ...]
    Possible solutions: load(java.io.InputStream), load(java.io.Reader), load(java.io.InputStream), load(java.io.Reader), clear(), clone()

aQute.bnd.gradle.TestTestOSGiTask > Bnd TestOSGi Task Basic Test FAILED
    Condition not satisfied:

    testxml.isFile()
    |       |
    |       false
    /Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/testresources/testosgitask1/build/test-results/test/TEST-doubler.impl.DoublerImplUnitTest.xml
        at aQute.bnd.gradle.TestTestOSGiTask.Bnd TestOSGi Task Basic Test(TestTestOSGiTask.groovy:73)

aQute.bnd.gradle.TestTestOSGiTask > Bnd TestOSGi Task Working Dir Test FAILED
    Condition not satisfied:

    testxml.isFile()
    |       |
    |       false
    /Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/testresources/testosgitask2/build/test-results/test/TEST-doubler.impl.DoublerImplUnitTest.xml
        at aQute.bnd.gradle.TestTestOSGiTask.Bnd TestOSGi Task Working Dir Test(TestTestOSGiTask.groovy:110)

aQute.bnd.gradle.TestTestOSGiTask > Bnd TestOSGi Task Replace bundles Test FAILED
    Condition not satisfied:

    testxml.isFile()
    |       |
    |       false
    /Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/testresources/testosgitask3/build/test-results/test/TEST-doubler.impl.DoublerImplUnitTest.xml
        at aQute.bnd.gradle.TestTestOSGiTask.Bnd TestOSGi Task Replace bundles Test(TestTestOSGiTask.groovy:146)

22 tests completed, 14 failed
:biz.aQute.bnd.gradle:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':biz.aQute.bnd.gradle:test'.
> There were failing tests. See the report at: file:///Users/dleangen/libs/bnd/biz.aQute.bnd.gradle/generated/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 25.872 secs
tofino:bnd dleangen$

**Comment by bjhargrave** [comment]
I am not clear on what you are doing here. Are you trying to build this project (Bnd)? 

We build it all the time on Travis, Cloudbees and our workstations.

What is the command you are running to invoke the build? Are you running `./gradlew`?

The issue smells of having an old version of bndlib on the classpath of gradle.

**Comment by bjhargrave** [comment]
Closing due to no reply.
