### ISSUE TITLE
allow specify winrun4j ini config when install jpm

### ISSUE THREAD

**Issue by AndyWu2015** [bndtools/bnd#2076]
e.g.
If I run 
`java -jar jpm.jar -u -winconf "vm.location=/path/jre/xx/jvm.dll" init`
after install jpm should put 
`vm.location=/path/jre/xx/jvm.dll`
at the end of {jpm.home}/bin/jpm.ini file

the cause is winrun4j will search jre installation on windows , but user may not install it and just install jdk.
so jpm should allow user to specify the jvm location.

**Comment by bjhargrave** [comment]
@gamerson This should be moved to the new jpmcli repo.
