### ISSUE TITLE
bnd baselining requires version increase when switching annotations

### ISSUE THREAD

**Issue by rombert** [bndtools/bnd#2112]
I am migrating a project from using the bnd versioning annotations to using the official OSGi ones.

The code changes are done, but when running baseline validation via the maven-bundle-plugin I get an error that a micro version increase is required.

```
[INFO] --- maven-bundle-plugin:3.3.0:baseline (baseline) @ oak-api ---
[INFO] Baseline Report - Generated by Apache Felix Maven Bundle Plugin
on 2017-08-02T18:13Z based on Bnd - see http://www.aqute.biz/Bnd/Bnd
[INFO] Comparing bundle oak-api version 1.8-SNAPSHOT to version 1.6.2
[INFO] 
[INFO]   PACKAGE_NAME                                       DELTA      
CUR_VER    BASE_VER   REC_VER    WARNINGS  
[INFO] = ================================================== ==========
========== ========== ========== ==========
[INFO] *
org.apache.jackrabbit.oak.api                      changed    3.1.0    
  3.1.0      3.1.1      Version increase required
[INFO]      ~ interface org.apache.jackrabbit.oak.api.QueryEngine
[INFO]          - annotated aQute.bnd.annotation.ProviderType
[INFO]          + annotated org.osgi.annotation.versioning.ProviderType


I don't see why this is an issue since both annotations have CLASS
retention policy so they would not cause any behaviour changes at
runtime.

```

I don't see why this is an issue since both annotations have CLASS
retention policy so they would not cause any behaviour changes at
runtime.

I have tried using bnd 3.3.0 and 3.4.0 with the plugin, and both lead to the same result.

**Comment by timothyjward** [comment]
Hi @rombert - the behaviour that you're describing is definitely intentional, and working correctly. A micro version bump indicates that *something* has changed in your API, but not anything that could affect binary compatibility. This is exactly what has happened here. The output code (and input source) have both changed leading to a different output class file.

Essentially it is very bad practice to make any sort of change (even JavaDoc spelling fixes) without signalling to users that a change has been made. In this case the micro bump indicates a totally compatible, but in some way "better" API package.

**Comment by rombert** [comment]
Thanks for the reply @timothyjward . While I don't fully agree that the change is warranted in this particular scenario, I can see the general argument and will just bump the versions.

**Comment by reschke** [comment]
But then, this means that the same source code will yield different results depending on what jdk it was compiled with. Is that really the desired behavior?

**Comment by rombert** [comment]
@reschke - I think [FELIX-5699](https://issues.apache.org/jira/browse/FELIX-5699) is a different scenario. In here we intentionally changed the source code, in your scenario the the compiler (?) automatically adds an annotation, which is completely outside our control and IMO should not be taken into account.

**Comment by reschke** [comment]
OK, so should we open a new BND issue then?

**Comment by rombert** [comment]
I think so
