### ISSUE TITLE
The use of Strings in the Hex class drags in many dependencies

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#2122]
The bnd Hex class is very useful for dealing with hex encoded Strings, however it has grown a dependency on the bnd Strings utility class, this in turn requires the bnd Collections utility package, which adds further dependencies.

Is this really necessary for a single usage of `Strings.trim(s)`? Especially as the null safety is not helpful (it will NPE a few lines later).

**Comment by bjhargrave** [comment]
Make a PR. Sounds like a good change to reduce dependencies.
