### ISSUE TITLE
snapshots and versions installed by bnd workspace into a maven local repository are ignored by maven

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#2135]
When a maven build searches for dependencies, if there is a remote repository which provides the version/snapshot, the local one is always ignored. The only workaround is to use offline mode.

**Comment by rotty3000** [comment]
I need to check if the same is true of gradle.

**Comment by tomq42** [comment]
I also see this issue, and it confused me hugely for quite a long time. It appears to be that there's no maven-metadata file generated in the local repository as far as I can tell, so maven ignores the artefacts.

**Comment by bjhargrave** [comment]
I see maven-metadata-xxx.xml files in the local repo.

**Comment by tomq42** [comment]
Hmm. Curious. I certainly don't. I just used bndtools 3.4, the osgi workspace from github, and a ".example" project, as per my post on the forum.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.
