### ISSUE TITLE
Adding a dependency of packaging-type pom makes "bnd-maven-plugin" fail

### ISSUE THREAD

**Issue by tomsontom** [bndtools/bnd#2136]
I just tried to put some of the dependencies I always use inside general module with packaging type pom.

so initially i had:
```xml
<project>
<groupId>my.group</groupId>
<artifactId>sample</artifactId>
<!-- -->
<dependencies>
  <dependency>
    <groupId>my.group</groupId>
    <artifactId>libA</artifactId>
    <version>1.0.0</version>
  </dependency>
  <dependency>
    <groupId>my.group</groupId>
    <artifactId>libB</artifactId>
    <version>1.0.0</version>
  </dependency>
</dependency>
<!-- ... -->
```
I extracted libA and libB in a module "libs":
```xml
<project>
<groupId>my.group</groupId>
<artifactId>libs</artifactId>
<packaging>pom</packaging>
<!-- -->
<dependencies>
  <dependency>
    <groupId>my.group</groupId>
    <artifactId>libA</artifactId>
    <version>1.0.0</version>
  </dependency>
  <dependency>
    <groupId>my.group</groupId>
    <artifactId>libB</artifactId>
    <version>1.0.0</version>
  </dependency>
</dependency>
<!-- ... -->
```
and changed my original pom.xml to:
```xml
<project>
<groupId>my.group</groupId>
<artifactId>sample</artifactId>
<!-- -->
<dependencies>
  <dependency>
    <groupId>my.group</groupId>
    <artifactId>libs</artifactId>
    <version>1.0.0</version>
  </dependency>
</dependency>
<!-- ... -->
```

but now bnd-tools fails because it says there's a corrupted zip in "my.group.libs". 

I think the maven-plugin needs to sort out dependencies of packaging-type "pom", would that make sense?

**Comment by bjhargrave** [comment]
This doesn't make sense

https://github.com/bndtools/bnd/blob/bdb3390ce8c49c7c244bd501a0dc543ba5adfe9c/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java#L142-L147

Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by tomsontom** [comment]
should the check not be in the

https://github.com/bndtools/bnd/blob/bdb3390ce8c49c7c244bd501a0dc543ba5adfe9c/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java#L192

**Comment by tomsontom** [comment]
i'll try to provide a sample project

**Comment by tomsontom** [comment]
Here you go: https://github.com/BestSolution-at/bnd-bug-reproducer 

To see the bug just comment out those lines:
https://github.com/BestSolution-at/bnd-bug-reproducer/blob/2f6df14e6a8b74169c5e7dae9bb1a0b4b6ae32b6/sample/app/pom.xml#L21-L26

If I read the code correct I think the check you show just skips the processing on modules of pom type but you forget to skip them when building the classpath you hand over to bnd.

**Comment by tomsontom** [comment]
Not sure if that matters but I observe this in eclipse!

**Comment by tomsontom** [comment]
hm it looks like what i was trying to do with the pom-packaging does not work. Sorry for the confusion

**Comment by bjhargrave** [comment]
:-) I was not sure a project's dependencies could be a pom itself.

**Comment by tomsontom** [comment]
Yeah I hoped I can simple build something similar like "feature" in eclipse :-( but obviously I got it wrong.
