### ISSUE TITLE
HttpClient should not cache after a 302 response

### ISSUE THREAD

**Issue by brampouwelse** [bndtools/bnd#2137]
HttpClient is currently caching a bit too aggressive it should not cache after it got redirected with a HTTP 302 response. 

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.3

(I'm running in to some issues after being re-directed to a login page due to wrong credentials ...)

**Comment by pkriens** [comment]
I think you're right but I ran into too many difficulties trying to implement it. Although it probably should be fixed I do not have the  time. The Http Client should probably partly be rewritten to support this. Since it does not seem a major issue I am moving this to abeyance.

**Comment by bjhargrave** [comment]
@pkriens Did you mean to close this? Or just move to Abeyance?
