### ISSUE TITLE
Version 3.4 of Gradle plugin not published to Gradle plugin repository

### ISSUE THREAD

**Issue by myniva** [bndtools/bnd#2142]
The last version published to the Gradle plugin repository (https://plugins.gradle.org/) is 3.**3**. Version 3.**4** is only available through Maven central. Is there a reason for not (no longer?) publishing to the official Gradle plugin repo?

**Comment by bjhargrave** [comment]
See https://discuss.gradle.org/t/publishing-to-the-plugin-portal-via-artifactory/9083/8.

The Bnd build process does not mesh with changes to the Gradle process for submitting plugins to their portal. They require them to be submitted from a build while Bnd has already completed the build by the time we agree the plugin is declared the final build.
