### ISSUE TITLE
API changes review for Bndlib

### ISSUE THREAD

**Issue by lvc** [bndtools/bnd#2151]
The review of API changes for the Bnd library since 2.4.1 version: https://abi-laboratory.pro/java/tracker/timeline/biz.aqute.bndlib/

The report is updated 3 times a week (Mon, Wed, Fri). Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-tracker and https://github.com/lvc/japi-compliance-checker tools.

Thank you.

![bndlib-2](https://user-images.githubusercontent.com/1517837/30953824-a493fe34-a43e-11e7-9cd5-dc2722e93933.png)
![bndlib-1](https://user-images.githubusercontent.com/1517837/30953823-a4697b28-a43e-11e7-975b-c9106d58bd50.png)

**Comment by bjhargrave** [comment]
I don't see a bug in bnd reported here.
