### ISSUE TITLE
Update brew formula for bnd 3.5

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#2154]
The brew formula for bnd needs updating for bnd 3.5.

**Comment by njbartlett** [comment]
Opened Homebrew PR: https://github.com/Homebrew/homebrew-core/pull/18844

For future reference, assuming the output of the `bnd resolve resolve -b` command has not changed, the following command can be used to generate the PR automatically:

    brew bump-formula-pr --url=<URL_of_new_bnd.jar> --sha256=<sha_of_bnd.jar>

**Comment by njbartlett** [comment]
PR accepted by Homebrew.
