### ISSUE TITLE
`MavenBndRepository` does not fall back to the release URL when no snapshot URL is defined

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#2170]
The doc for the configuration indicates that the snapshot URL is optional. It is not.

**Comment by bjhargrave** [comment]
I think it is not optional if you want to use SNAPSHOT versioned artifacts. 

I found this out when working with the promise 1.1 snapshots from OSGi. The 1.1 snapshot were not visible from the repo unless the snapshotUrl was set.

The doc (http://bnd.bndtools.org/plugins/maven.html) says:

```
Property | Description
releaseUrl | The URL to the repositories of released artifacts.
snapshotUrl | The URL to the repositories of snapshot artifacts. If this is  not specified then snapshots will also be attempted to be released to  the releaseUrl.
```

but it does not say anything about returning snapshot versioned artifacts from releaseUrl. A strict reading would say that snapshot artifacts only come from snapshotUrl.

**Comment by timothyjward** [comment]
I was working on the description provided [here in the configuration definition](https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/bnd/repository/maven/provider/Configuration.java#L13-L18) which seems to say that the release url will be used if no snapshot url is provided.

**Comment by bjhargrave** [comment]
I think the issue is here:

https://github.com/bndtools/bnd/blob/3690401814325d727a4171d62e420c41b40785a4/biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java#L95-L101

If you request a snapshot version artifact, it will only look in the snapshotUrls.

**Comment by bjhargrave** [comment]
Again, it is not clear whether it is just a doc issue or a defect in the code. I suspect it is just a doc issue.

**Comment by bjhargrave** [comment]
@pkriens says this is a doc bug.
