### ISSUE TITLE
[maven-bnd-indexer-plugin] Dependencies are not filtered by scope before being included in index

### ISSUE THREAD

**Issue by magnet** [bndtools/bnd#2198]
The documentation states that `By default the bnd-indexer-maven-plugin will include dependencies with compile and runtime scope. Different scopes may be selected as follows`.

However, the indexer plugin (3.5.0) does include provided dependencies. Overriding the scope configuration as described in the documentation does not fix this behavior.

For instance, the osgi.cmpn dependency is marked as provided (confirmed in effective POM) yet it is in the index and thus suggested by the resolver in BndTools.

**Comment by timothyjward** [comment]
We do have a test for this, so my guess is that there is something else going on. Is it possible that the `osgi.cmpn` artifact is a `compile` or `runtime` dependency of one of the other artifacts in your dependency tree? 
I'm honestly not sure what maven gives us back when we walk the dependency tree, but if it doesn't do any deduplication/version fixing/scoping for us (which seems likely) then this is the behaviour I would expect to see. I would also view it as "correct" in that your dependency has stated that it requires osgi.cmpn at compile/runtime, which means that we should put it in the index.

This may simply be one of those cases that requires an exclusion, and a patch to fix the offending upstream artifact...

**Comment by magnet** [comment]
@timothyjward Thanks for your reply. I have tested with several different artifacts, including some that are not depended on anywhere.

I use the effective POM to see how Maven "sees" the dependency and it is marked as provided. However the dependency is indeed in the same POM, and not as a dependency of a project I depend on, that is it *is* a "provided" dependency of the POM and not removed by Maven itself.

I control the whole build and the dependency is from the POM itself, not from a dependency.

I'll have a look at the test to see if I find differences.

**Comment by magnet** [comment]
@timothyjward So I had a look and debugged the process, and I believe this is a bug in bnd, more precisely in bnd-shared-maven-lib's `DependencyResolver`.

In there, a `DependencyResolutionResult` is constructed using the scope as filters. This result is indeed filtered, however then immediately instead of using `List<Dependency> DependencyResolutionResult#getDependencies()` that returns the filtered dependencies, the call is instead made to `DependencyNode DependencyResolutionResult#getDependencyGraph()` which returns the (unfiltered) dependency graph. 

So in bnd-shared-maven-lib's `DependencyResolver#discoverArtifacts"  the "children" passed are actually unfiltered.

I do not know how your test cases can work, I suspect something is wrong there, I couldn't find how you are comparing generated repositories with the expected ones or how you make sure they are not present in the final output.

I can provide a patch for the code, but I need help to know how these tests work and are run to test the pull request.

**Comment by bjhargrave** [comment]
> I need help to know how these tests work and are run to test the pull request.

The tests are run via the deploy operation.

**Comment by magnet** [comment]
Thanks @bjhargrave I just found where the output is.

Well, the test does output the wrong repo.
The "scoped" test has the following configuration
`	<configuration>
					<scopes>
						<scope>provided</scope>
						<scope>test</scope>
					</scopes>
				</configuration>`

So compile should be excluded. However the `org.apache.felix.log` bundle which has compile scope is in the output repo.

Next question is, is there anything asserting anything on actual vs expected output that I would change as a part of a pull-request?

**Comment by timothyjward** [comment]
> Next question is, is there anything asserting anything on actual vs expected output that I would change as a part of a pull-request?

I hope you like groovy... This line is doing the check for the `scoped` index. Feel free to extend the checks that it does! https://github.com/bndtools/bnd/blob/de8b38bccd1e20ec6256d610fdf87dbd731fccaa/maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy#L78

**Comment by magnet** [comment]
I saw that file earlier and I was hoping that it was not that very dark place ;) I'll have a look if I feel very brave, but first I'll fix the issue.
