### ISSUE TITLE
bnd does not support @Requirement as a meta-meta-annotation (should it??)

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#2212]
The `@HttpWhiteboardServletPattern` annotation is annotated with `@RequireHttpWhiteboard`, which it itself annotated with a `@Requirement` with osgi.implementation=osgi.http. That makes `@Requirement` a meta-meta-annotation(!).

Should this generate a Require-Capability for osgi.implementation=osgi.http when I use `@HttpWhiteboardServletPattern` on a Servlet component?? Because in bnd it currently does not work, I have to add `@RequireHttpWhiteboard` onto my Servlet as well.

If it's not intended to generate the Require-Capability then why bother putting `@RequireHttpWhiteboard` on the `@HttpWhiteboard*` annotations?

**Comment by timothyjward** [comment]
> Should this generate a Require-Capability for osgi.implementation=osgi.http when I use @HttpWhiteboardServletPattern on a Servlet component??

Yes

> Because in bnd it currently does not work, I have to add @RequireHttpWhiteboard onto my Servlet as well.

This should be working without you having to annotate the servlet but bnd's R7 support is not complete, so there are a number of things which may not work properly.

**Comment by njbartlett** [comment]
Thanks, good to know. Worth leaving this open as a placeholder?

**Comment by timothyjward** [comment]
Probably. There's also some tracking happening here: https://github.com/bndtools/bnd/projects/2

My experience with GitHub project tooling is low so I don't know if there's a way to link this issue into that tracker or not

**Comment by njbartlett** [comment]
Yes it was possible (click "+Add cards", drag the issue into the TODO column). Thanks!
