### ISSUE TITLE
-releaserepo is ignored when used inside bnd of sub bundle

### ISSUE THREAD

**Issue by wclaeys** [bndtools/bnd#2213]
bnd.bnd:
  -sub: *.bnd

impl.bnd:
 (Setting the 'releaserepo' to an empty string to not release this bundle in the repository.)
 -releaserepo:

The above releaserepo is ignored and the impl bundle is still released.

**Comment by bjhargrave** [comment]
Yes, -releaserepo applies to the project (bnd.bnd) as a whole. Sub bundles are the recipes for making the sub bundle.

**Comment by wclaeys** [comment]
Thx @bjhargrave for this quick response!
So there's no way to not release these sub-bundles individually?

**Comment by bjhargrave** [comment]
Not to my knowledge.

The release function

https://github.com/bndtools/bnd/blob/14548b633ed2ede1c93f3a6590ac81b3b0391837/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L1118-L1140

gets the jars built in the project and then releases them. That is, releasing is done at the project level, not at the sub bundle level. Bundles are built by Builder objects and released by Project objects.
