### ISSUE TITLE
bndtool support for (p2)-repositories with tls/ssl client-certificates handshake

### ISSUE THREAD

**Issue by jwausle** [bndtools/bnd#2215]
As bndtools user I want to configure a secure-repository with client-certificates for ssl/tls handshake.
- the configuation should be transparent for CLI and UI mode
- e.g in connection-settings.xml

**Example (my secure p2)**: https://secure-nexus-host/my/p2/artifact.jar
- I can download the artifact with curl

```
curl -G https://secure-nexus-host/my/p2/artifact.jar \
 --cert ~/.ssl/public-user-key.pem \
 --key ~/.ssl/private-user-key.pem \
 --cacert ~/.ssl/ca.pem \
 -v -k 
``` 

- I can use p2 with mvn-tycho if I set the right java-D-properties 

```
# keystore.p12 contains above public-user-key.pem and private-user-key.pem
MAVEN_OPTS="-Djavax.net.ssl.keyStore=~/ssl/keystore.p12 \
    -Djavax.net.ssl.keyStoreType=pkcs12 \
    -Djavax.net.ssl.keyStorePassword=XXXXXX"
```

**How can I do this with bnd**?

**Comment by bjhargrave** [comment]
Usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.

**Comment by jwausle** [comment]
@bjhargrave It`s no question.

**Comment by bjhargrave** [comment]
> How can I do this with bnd?

Sorry. But that does look like a usage question. :-)
