### ISSUE TITLE
Double update of bnd files in Eclipse

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#2229]
I consistently need to save the bnd.bnd file twice. It seems the first changes are not picked up but this does somehow not result in an update of the classpath container. Only the second time they are refreshed.

**Comment by bjhargrave** [comment]
Should't this issue be in the bndtools repo?

**Comment by pkriens** [comment]
Probably yes.

**Comment by pkriens** [comment]
https://github.com/bndtools/bndtools/issues/1815
