### ISSUE TITLE
bnd-indexer-maven-plugin should indicate minimum Maven version

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#2251]
Had this error while running a build on a Docker container that only had Maven 3.0.5:

     [ERROR] Failed to execute goal biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:index (default-index) on project _index: Execution default-index of goal biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:index failed: A required class was missing while executing biz.aQute.bnd:bnd-indexer-maven-plugin:3.5.0:index: Lorg/eclipse/aether/RepositorySystemSession;

After upgrading to Maven 3.3.9, this error went away.

Can we make the plugin fail fast if the Maven version is too low?

**Comment by timothyjward** [comment]
Discussed on the bnd call today.

We don't know how to do this with the `maven-plugin-plugin`. It doesn't look like there's any way to set a base version of maven needed by a plugin.

If anyone in the future does know how this should be done then great.
