### ISSUE TITLE
Unit tests and service component metadata generation

### ISSUE THREAD

**Issue by pun-ky** [bndtools/bnd#2257]
Assuming following build file:

```groovy
apply plugin: 'java'
apply plugin: "kotlin"
apply plugin: 'biz.aQute.bnd.builder'
apply plugin: 'com.cognifide.aem.package'

jar {
    def pkg = 'com.company.aem.example.core'

    manifest {
        attributes([
                'Bundle-SymbolicName': pkg,
                'Sling-Model-Packages': pkg,
                'Export-Package': "$pkg.*;-split-package:=merge-first"
        ])
    }
}
```

how to configure that BND will generate SCR metadata used by unit tests?
I am looking for analogical configuration like for maven-bundle-plugin described here ( http://felix.apache.org/documentation/faqs/apache-felix-bundle-plugin-faq.html#use-scr-metadata-generated-by-bnd-in-unit-tests ), but for Gradle / BND plugin.

Any help appreciated. Thanks!

**Comment by pun-ky** [comment]
hmm is it a valid solution?

```groovy
plugins.withId 'biz.aQute.bnd.builder', { 
        test {
            classpath += files(jar.archivePath)
        }
}
```

**Comment by bjhargrave** [comment]
You need the unit tests to depend upon the jar which will contain the generated DS metadata. Your proposed solution seems to do what you want.

**Comment by pun-ky** [comment]
I was thinking that maybe you want to include sth like above to be done by default by plugin.

Thanks for clarification

**Comment by bjhargrave** [comment]
I don't think it is a good default for the unit test `test` task to depend upon the `jar` task. There are certainly cases where it is necessary (the Bnd build uses this to test the Bnd gradle plugins), but it is not always necessary or a good idea for every project.

**Comment by pun-ky** [comment]
it does not depend directly, it could be just sometimes non-effective classpath entry ;)
