### ISSUE TITLE
Leverage new requirement/capability metadata in P2

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#2271]
It seems the latest versions of P2 now actually publishes requirement/capability metadata, so perhaps at some point the P2 repository plugin should be updated to support this. For new enough repos we should no longer have to download all the jars and inspect their manifests ourselves.

Or maybe this is different enough that it should be supported by a new separate repo plugin?

notes: https://www.eclipse.org/eclipse/news/4.8/M4/
bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=313553

**Comment by rotty3000** [comment]
Could provide a schema, or point to documentation, for how this information is stored?

**Comment by rotty3000** [comment]
If the metadata is made available directly in R5 repository formatted index file somewhere in the p2 update site tree and with correctly relative urls to the artifacts, then bnd has nothing really to do since you can simply use the osgi repository type configured with the url of the index file.

**Comment by bjhargrave** [comment]
We need someone to make a PR.
