### ISSUE TITLE
MavenVersionRange.includes is buggy

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#2285]
According to the [maven specs](http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html) the maven version range "[1.0.1,)" means v >= 1.0.1. However, feeding this range and "1.0.1" to `MavenVersionRange.includes` returns `false`. 

The "missing" upper limit is converted to 0.0.0. This is wrong, because `MavenVersion.compare` (used in `MavenVersionRange.includes`) quite correctly does not consider "1.0.1" to be smaller than "0.0.0". So "0.0.0" may not be used as replacement for the missing upper bound (or special handling must be implemented).

**Comment by rotty3000** [comment]
The issue seems to be here: https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/version/MavenVersionRange.java#L48

where if the resolved upper version is zero, then the version used should be `MavenVersion.HIGHEST`.

Could you make a PR?

**Comment by mnlipp** [comment]
Actually, I considered this to be a PR (if PR means Problem Report).

**Comment by rotty3000** [comment]
PR = Pull Request (in git lingo) Sorry for the confusion! :)

**Comment by mnlipp** [comment]
Looking at this (and related issues) I found that part of the code implemented in bnd for maven version handling could be simplified/removed and "canonicalized" by including the [maven-artifact](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22maven-artifact%22) library in the bundle. Is there any reason why I should not do this when providing a PR?

**Comment by bjhargrave** [comment]
I would suggest the first PR fix the bug so we can review it for that purpose. 

If you want to make another PR to restructure the code, then do that after the first PR. But I will say @pkriens spent a lot of time writing the current code and avoided using such libraries. So I do not think he wanted to rely on a 3rd party maven libraries. I will let him comment.

**Comment by pkriens** [comment]
I prefer not to but bnd is by now not my private project anymore. I would prefer just to fix it, after all we had extremely few problems so far in this area.
