### ISSUE TITLE
Annotated Annotations for Requirements and Capabilities result in invalid Manifest entry for String[]

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#2305]
Annotating a Class e.g. with 

`@RequireConfigurator(value = {"test1", "test2"})`

results in

`osgi.extender;filter:="(&(osgi.extender=osgi.configurator)(&(version>=1.0.0)(!version>=2.0.0))))";configurations=test1,test2`

but must be:

`osgi.extender;filter:="(&(osgi.extender=osgi.configurator)(&(version>=1.0.0)(!version>=2.0.0))))";configurations="test1,test2"`

**Comment by bjhargrave** [comment]
> but must be:
> 
> osgi.extender;filter:="(&(osgi.extender=osgi.configurator)(&(version>=1.0.0)(!version>=2.0.0))))";configurations="test1,test2"

Actually, it must be:

`osgi.extender;filter:="(&(osgi.extender=osgi.configurator)(&(version>=1.0.0)(!version>=2.0.0))))";configurations:List<String>="test1,test2"`

since it must specify the type of the attribute as `List<String>` rather than the default type of `String`.

**Comment by bjhargrave** [comment]
This code
https://github.com/bndtools/bnd/blob/f31619ed2c79cd708f99e82ba4bcdabd6ba66e45/biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java#L323-L334
seems to ignore the typing information in the `attributesAndDirectives` Attrs object as a simple `Map<String,String>`. Attrs also hold type information.
