### ISSUE TITLE
Move bundled binaries to their own repositories

### ISSUE THREAD

**Issue by wltjr** [bndtools/bnd#2312]
This came up sometime back in issue #1325, see my P.S. at bottom of first post. There was a [reply from the author](https://github.com/bndtools/bnd/issues/1325#issuecomment-186116792) about splitting up the stuff maybe into their own repos.

There does not seem to be source jars for those available anywhere else, not on maven, gradle etc.Not a problem, but binaries in git are not really ideal. I am willing to help if needed. Either way I would like to get those jars out of the main repo, and sources available in some repo. Either this one, or stand alone ones, etc.

Specifically this one, but I am pretty sure there others. I can produce a list of those I am interested in.
https://github.com/bndtools/bnd/tree/4.0.0.DEV/cnf/repo/aQute.jpm.clnt

This is for my [Gentoo ebuilds](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/aqute-jpm-clnt/aqute-jpm-clnt-2.2.0.ebuild) I made for [BND](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/bnd/bnd-9999.ebuild) sometime back. About to update them to latest versions. Thus revisiting things. Long term I may look to have BND osgi'fy all jars on Gentoo. Though likely will require some bootstrapping. All stuff specific to Gentoo, like how I am building BND, not using BND build system. That was controversial before, but I resolved most all issues, and [seems to work fine](https://github.com/bndtools/bnd/issues/1325#issuecomment-188919292).

Thanks, and no rush!

**Comment by bjhargrave** [comment]
> https://github.com/bndtools/bnd/tree/4.0.0.DEV/cnf/repo/aQute.jpm.clnt

This file does not exist in HEAD. The tag 4.0.0.DEV is the _start_ of the 4.0 development cycle and is other uninteresting as a git tag. So do not rely upon it to mean anything.

So I don't think there are any other binaries in the git repo (other than as test materials).

**Comment by wltjr** [comment]
Where has it gone? Is it no longer used? I am confused that head and 4.0.0.DEV differ. Is head not where 4.0.0 releases are happening? Will it be a binary in 4.0.0.REL?

**Comment by bjhargrave** [comment]
It was just deleted. We removed some old/dead function in 4.0. The JPM function was removed from Bnd and the JPM CLI function was moved to https://github.com/bndtools/jpmcli.

HEAD is the tip commit of a branch and the master branch is the main development branch for Bnd. A tag refers to a specific commit and generally does not change. Bnd 4.0 will be released from the development stream now in the master branch. The 4.0 release will be tagged 4.0.0.REL once released.

**Comment by wltjr** [comment]
Ok great, I may wait to update till 4.0.0 is released. I am way behind on 3.2, but it is not really used at the moment. I could update to newer, but may way and remove the stuff no longer needed. 

Can you provide any information on these? Only 1 is under BND the others the aqute author. I needed them for 3.2, not sure if they are needed for 4.0.0. Please advise thank you!
https://github.com/bndtools/bundle-hub/tree/master/org.osgi.impl.bundle.bindex
https://github.com/pkriens/aQute.repo/tree/master/repo/aQute.services.services
https://github.com/pkriens/aQute.repo/tree/master/repo/aQute.services.struct

Those seem to be the last of the jars in repos I could not find sources to anywhere else. Not sure if they are still used. If so same deal, move to repos. If not, sweet! :)

**Comment by bjhargrave** [comment]
Those are not in the Bnd repo and not used on the Bnd build.

**Comment by wltjr** [comment]
The first one is, and they are needed to build BND, including any dependencies from source. I maybe building it differently. But I know for a fact they are part of the necessary dependencies for BND. The only reason I even packaged them in the first place was to build BND.


```bash
# emerge -pv bnd

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    ~] dev-java/bnd-annotation-3.3.0:3::os-xtoo  USE="-doc -source" 93,106 KiB
[ebuild  NS   ~] dev-java/osgi-core-api-5.0.0-r10:5::os-xtoo [6.0.0:6::os-xtoo] USE="-doc -source" 409 KiB
[ebuild  N    ~] dev-java/osgi-foundation-1.2.0-r10::os-xtoo  USE="-doc -source" 45 KiB
[ebuild  N    ~] dev-java/aqute-services-struct-1.0.0::os-xtoo  USE="-doc -source" 23 KiB
[ebuild  NS   ~] dev-java/osgi-core-api-4.3.1:4::os-xtoo [6.0.0:6::os-xtoo] USE="-doc -source" 333 KiB
[ebuild  N    ~] dev-java/snakeyaml-1.18::os-xtoo  USE="-doc -source" 360 KiB
[ebuild  N    ~] dev-java/xmlpull-1.1.3.3::os-xtoo  USE="-doc -source" 818 KiB
[ebuild  N    ~] dev-java/xpp-3.1.1.4c-r10:3::os-xtoo  USE="-doc -source" 558 KiB
[ebuild  N    ~] dev-java/osgi-impl-bundle-repoindex-api-3.3.0:3::os-xtoo  USE="-doc -source" 0 KiB
[ebuild  N    ~] dev-java/slf4j-simple-1.7.25::os-xtoo  USE="-doc -source" 2,221 KiB
[ebuild  N    ~] dev-java/kxml-2.4.2::os-xtoo  USE="-doc -source" 48 KiB
[ebuild  N    ~] dev-java/osgi-ds-1.3::os-xtoo  USE="-doc -source" 0 KiB
[ebuild  N    ~] dev-java/osgi-util-1.0::os-xtoo  USE="-doc -source" 0 KiB
[ebuild  N    ~] dev-java/felix-resolver-1.14.0::os-xtoo  USE="-doc -source" 153 KiB
[ebuild  N    ~] dev-java/osgi-service-obr-1.0.2::os-xtoo  8 KiB
[ebuild  N    ~] dev-java/libg-3.3.0:3::os-xtoo  USE="-source" 0 KiB
[ebuild  N    ~] dev-java/osgi-compendium-6.0.0:6::os-xtoo  USE="-doc -source" 0 KiB
[ebuild  N    ~] dev-java/osgi-compendium-5.0.0:5::os-xtoo  USE="-doc -source" 754 KiB
[ebuild  N    ~] dev-java/osgi-compendium-4.3.1-r10:4::os-xtoo  USE="-doc -source" 725 KiB
[ebuild  N    ~] dev-java/bndlib-3.3.0:3::os-xtoo  USE="-doc -source" 0 KiB
[ebuild  N    ~] dev-java/osgi-impl-bundle-repoindex-lib-3.3.0:3::os-xtoo  USE="-doc -source" 0 KiB
[ebuild  N    ~] dev-java/felix-gogo-runtime-1.0.10::os-xtoo  109 KiB
[ebuild  N    ~] dev-java/felix-framework-5.6.10::os-xtoo  USE="-doc -source" 443 KiB
[ebuild  N    ~] dev-java/aqute-remote-3.3.0:3::os-xtoo  USE="-doc -source" 0 KiB
[ebuild  N    ~] dev-java/aqute-services-services-1.0.0::os-xtoo  USE="-doc -source" 121 KiB
[ebuild  N    ~] dev-java/aqute-jpm-clnt-2.2.0::os-xtoo  USE="-doc -source" 225 KiB
[ebuild  N    ~] dev-java/osgi-impl-bundle-bindex-2.2.0-r1::os-xtoo  USE="-doc -source" 151 KiB
[ebuild  N    ~] dev-java/aqute-repository-3.3.0:3::os-xtoo  USE="-doc -source" 0 KiB
[ebuild  N    ~] dev-java/aqute-resolve-3.3.0:3::os-xtoo  USE="-doc -source" 0 KiB
[ebuild  N    ~] dev-java/bnd-3.3.0-r1:3::os-xtoo  USE="-doc -source" 0 KiB
```
