### ISSUE TITLE
P2 plugin to use P2 pool

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#2314]
Oomph in Eclipse has the concept of a "bundle pool", where downloaded bundles from p2 repositories are downloaded, stored and shared between Eclipse applications and target platforms. It would be good if the p2 implementation in BndTools could also tap into the bundle pool - it could help reduce the amount of duplicated downloading of bundles.

Having had a brief look, it seems that the p2 implementation in bndtools is custom and doesn't use the Eclipse packages. If it used the Eclipse packages perhaps the option to use the bundle pool would come for free?

**Comment by bjhargrave** [comment]
The p2 repo implementation in Bnd supports a local cache of installed bundles. You can configure the location of the cache with the `location` attribute. See https://github.com/bndtools/bndtools/blob/9a8b134fbc53151501dc2dfd972bf352b9ec4422/cnf/ext/repositories.bnd#L34 for an example. So if you want to have a shared p2 cache, you can configure your p2 repositories to share a local cache.

I do not see that Bnd's p2 repo implementation will change to use the Eclipse packages.

As I understand it, the p2 pool is a shared set of bundles which can be installed. It is not really a cache of artifacts from a p2 repository. But the `~/.p2/pool` folder on my system looks like a p2 repository, so I guess you could try an use that folder as a p2 repository location but that does not seem like the best idea.

**Comment by kriegfrj** [comment]
> The p2 repo implementation in Bnd supports a local cache of installed bundles. You can configure the location of the cache with the location attribute. See https://github.com/bndtools/bndtools/blob/9a8b134fbc53151501dc2dfd972bf352b9ec4422/cnf/ext/repositories.bnd#L34 for an example. So if you want to have a shared p2 cache, you can configure your p2 repositories to share a local cache.

That will allow Bnd workspaces to share artifacts downloaded from P2 repositories. However, it will not allow you to share them between Bnd and Eclipse installations or Eclipse target platforms. If Bnd could leverage the p2 pool (or vice-versa), this would become possible. Would make it more efficient to (eg) develop an Eclipse plugin - you don't have to have a duplicate copy of all the Eclipse bundles on your system.

> I do not see that Bnd's p2 repo implementation will change to use the Eclipse packages.

I guess that's a design decision beyond my "pay grade". :smile: However, admittedly without knowing the details, I'd have thought it would have been an efficient move in the long run to not attempt re-inventing the wheel (eg, p2 pool support would have come for free). Given that I am new to Bnd/Bndtools though, I readily admit that there may have been good reasons for choosing to go with a fully custom implementation (as far as I can see, indexing the repo for fast searching is probably the biggest). 

Another possible advantage of using the Eclipse p2 resolver library is that you might be able to do repository searches without needing to download and index the entire repository locally (though the searches would obviously be slower than if there was a local index).

> As I understand it, the p2 pool is a shared set of bundles which can be installed. It is not really a cache of artifacts from a p2 repository.

Not quite - the p2 pool is a shared set of bundles that _have_ been installed by at least one Eclipse application/target platform. Once installed, they can be shared by all Eclipse installations without each installation needing its own copy.

I guess you are correct in that it is not really a cache of artifacts from _a particular p2 repository_ - it is a cache of artifacts from all repositories.

> But the ~/.p2/pool folder on my system looks like a p2 repository, so I guess you could try an use that folder as a p2 repository location but that does not seem like the best idea.

Actually, I think that this is a good idea - the p2 pool is indeed structured as a p2 repository. However the way that the P2Repository plugin currently works it will still duplicate disk space (though this approach would at least avoid having to download the bundles twice).

**Comment by bjhargrave** [comment]
We don't want to depend upon Eclipse p2 jars as the dependency fan out is huge. We need someone to make a PR here to support using the p2 pool as a quick source of jars.

**Comment by kriegfrj** [comment]
> We don't want to depend upon Eclipse p2 jars as the dependency fan out is huge.
Fair enough.
> We need someone to make a PR here to support using the p2 pool as a quick source of jars.
Perhaps a more generic solution that would facilitate this is to special-case P2 repositories that are installed locally (the P2 pool simply being a special case). This could be implemented either as a different RepositoryPlugin (hopefully sharing code with the existing P2Repository plugin), or else as a configuration option on the current P2Respository plugin. 

This implementation would examine and index the bundles (as the P2Repository plugin does), but  rather than downloading them it would reference the bundles in their original location rather than copying the plugins into the Bnd cache. Conceptually this sounds easy to do (though I am unlikely to have time to commit to this).

**Comment by kriegfrj** [comment]
Now having several months' more experience with Bnd, I think this issue can be closed.

The P2 pool is in fact a P2 repository. To use it, all you need to do is configure a repository plugin to point at your pool directory, and the standard Bnd/Bndtools integration takes care of the rest:

```
    aQute.bnd.repository.p2.provider.P2Repository;\
    	name="Eclipse Local";\
    	url="file:///path/to/.p2/pool/";\
    	location="${workspace}/cnf/cache/stable/EclipseLocal"
```

A nice bit of gloss would be a wizard in Bndtools to add this repo for you automatically. But that can be for another day and another issue.

The last item I mentioned:

> This implementation would examine and index the bundles (as the P2Repository plugin does), but rather than downloading them it would reference the bundles in their original location rather than copying the plugins into the Bnd cache.

I just discovered that this is what Bnd effectively does using symlinking, but that this is typically disabled on Windows due to the difficulties of getting symlink support on that platform (#1834). I wonder if it might be possible to reference the indexed bundles in their original location rather than copy/symlink them, but this is again I think for another issue.
