### ISSUE TITLE
Add 'developer' headers to Constants and Syntax

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#233]
For https://github.com/bndtools/bndtools/issues/443 to be closed we need more headers in bnd.
- Bundle-Developers
  - waiting for this property to be added to Constants and Syntax in bnd
- Bundle-Contributors
  - waiting for this property to be added to Constants and Syntax in bnd
- Bundle-SCM
  - waiting for this property to be added to Constants and Syntax in bnd
- Bundle-MailingList
  - waiting for this property to be added to Constants and Syntax in bnd
- Bundle-Issues
  - waiting for this property to be added to Constants and Syntax in bnd
- Bundle-Revision
  - waiting for this property to be added to Constants and Syntax in bnd

**Comment by bjhargrave** [comment]
OSGi bug 2903 will add a Bundle-SCM and Bundle-Developers header to the spec. We will support in Bnd.

**Comment by bjhargrave** [comment]
Bundle-Developers, Bundle-Contributors, and Bundle-SCM are Constants and Syntax.

Bundle-MailingList, Bundle-Issues, and Bundle-Revision are not mentioned anywhere in Bnd.
