### ISSUE TITLE
New bnd index command NPEs

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#2333]
The new bnd index command is not defensive and does not display help. 

For example `java -jar biz.aQute.bnd/generated/biz.aQute.bnd.jar repo` displays help.

`java -jar biz.aQute.bnd/generated/biz.aQute.bnd.jar index` just NPEs. Even `java -jar biz.aQute.bnd/generated/biz.aQute.bnd.jar index help` NPEs. So not very helpful.

Looking  at the code, the code seems to assume the options are always non-null.

https://github.com/bndtools/bnd/blob/463c7cdf6f0eb223c0da29bd001cfc4c34368121/biz.aQute.bnd/src/aQute/bnd/main/IndexCommand.java#L49-L50

is generally the initial NPE. The code must be more defensive and also help must work.

**Comment by rotty3000** [comment]
This is a bug in the command processor itself. Whenever the argument of a command uses an "ellipsis" argument, the help handler cannot recuperate, AND I found not way to trigger help from within the command.

FYI `bnd help index` works.

**Comment by rotty3000** [comment]
I have found other commands that behave the same way but I'll have to look again to find which they are so I can demonstrate them.

**Comment by rotty3000** [comment]
but yeah, that's certainly a missed null check on the `opts.repositoryIndex()`. thx
