### ISSUE TITLE
Use ResourcesRepository.toResourcesRepository collector instead of forEach

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#2335]
The forEach on the stream should be replaced with a collect using the ResourcesRepository.toResourcesRepository collector to return a ResourcesRepository object. The work in the forEach will need to be moved to map/filter operations.

https://github.com/bndtools/bnd/blob/463c7cdf6f0eb223c0da29bd001cfc4c34368121/biz.aQute.bndlib/src/aQute/bnd/osgi/repository/SimpleIndexer.java#L110-L129

**Comment by rotty3000** [comment]
Can you have exception handling in the map function? How will you deal with the scenario where the jar file could not be indexed, and we have to return null? I don't think map handles this properly.

**Comment by rotty3000** [comment]
nvm... filter...
