### ISSUE TITLE
Improve gradle export task to support custom Exporter Plugins

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#2344]
It would be great if the current gradle export task would support the Exporters beyond allowing the use of bundleOnly. 

I'd suggest something like: ``` gradlew export -exporter my.exporter -toFolder ```

**Comment by bjhargrave** [comment]
I think it will be a configuration option on the export task. Then you can make as many export task as you want each configured to use some specific exporter. 

Using command line options in gradle is new to 4.6 and we need to support 4.0+.

**Comment by juergen-albert** [comment]
What do you mean by configuration option? How would it look like in the end?

As an alternative: there is already an property ```-exporttype``` property, that can provide exporter specific properties. Thus the gradle export could simple honor  this property, and apply all exporters that are defined there. The only thing required in the end would something to define if the exporter results should be written to a file or a folder.

**Comment by bjhargrave** [comment]
```
task export(type: Export) {
   description "Export ${name}.bndrun"
   group 'export'
   bndrun "${name}.bndrun"
   bundles = configurations.bundles
  exporter = 'my.exporter'
}
```

**Comment by bjhargrave** [comment]
> there is already an property -exporttype property, that can provide exporter specific properties

But this option does not select the exporter. It is just a way of passing options to the exporter selected by other means.

**Comment by juergen-albert** [comment]
It is used as such for the moment. The naming itself suggests a definition of what exporter to use as well. So I guess it would not be far stretched to use it like this as well. 

If you go with the task configuration option, can you add an option to define if the exporter result must be written to a folder or a jar? Example: 
```
task export(type: Export) {
   description "Export ${name}.bndrun"
   group 'export'
   bndrun "${name}.bndrun"
   bundles = configurations.bundles
  exporter = 'my.exporter'
  writeToFolder = true
}
```

**Comment by bjhargrave** [comment]
> can you add an option to define if the exporter result must be written to a folder or a jar?

I think that is highly dependent on the type of exporter. What is the exporter makes a docker container? Then there is no folder or jar. Options for the exporter can be passed to it by the `-exporttype` property in the bndrun file.
