### ISSUE TITLE
comparing SHA on baseline

### ISSUE THREAD

**Issue by buerie** [bndtools/bnd#2347]
Hello,

we are working on a project and we are having some issues with comparing the SHA on baseline. We have people who work on macs/ubuntu/windows computers, and we are using GIT as version control. Because of this, line endings are replaced on checkout. If someone does a gradle build with baseline, there are many differences in SHAs on resources, but also the OSGI-OPT folder etc.. ignoring resources isn't an option as we have javascript files in those folders, so if something changes there we need a bump. Any other option than making the developers change their git config? Thanks in advance!

Bnd version 3.5.0, Java 8

Kind regards

**Comment by bjhargrave** [comment]
You need to properly configure your git repo to use the same line ending on all platforms. See the [`.gitattributes`](https://github.com/bndtools/bnd/blob/master/.gitattributes) file in the root of this repo.

It is better to simply use this support already existing in git than to add similar support to bnd to manipulate resources for SHA computations.

**Comment by buerie** [comment]
Ok, thanks!

Kind regards
