### ISSUE TITLE
Bnd doesn't handle src.includes that aren't directories

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#2380]
This was the root cause of bndtools/bndtools#1862.

I'm porting an existing PDE project to Bnd. The PDE project had a build.properties file with a src.includes directive that includes several directories and files.

It appears that `Project` is assuming that all the entries in this property should be directories, and trying to create them if they don't exist:

https://github.com/bndtools/bnd/blob/920be8252daa3850755de049644102276fff6bf0/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L323-L325

Of course, the files in my PDE project did actually exist, hence the attempt to create the directory threw an exception, which caused the attempt to build the Project model to abort. Because just about everything in Bnd depends on the model, this basically means that nothing works.

There are two distinct issues here, I believe:

1. Bnd should not die so abruptly, but should handle the exception and move on as gracefully as possible.
2. More specifically in this case, how to properly handle the case when build.properties contains source paths that point to files.

It seems to be legal syntax for `src.includes` to contain files as well as directories. It is used by PDE to copy files into the final bundle. However, I'm not sure how bnd should handle it.

**Comment by kriegfrj** [comment]
Of course there is a workaround, as I am porting to Bnd anyway, that I can use Bnd directives to copy all of the relevant files into the output jar instead of using the Eclipse build.properties file. But if this is supposed to work, then it should do so cleanly.

**Comment by bjhargrave** [comment]
There is no `src.includes` property in Bnd. That is from PDE and has no special meaning to Bnd. Bnd has a `src` property which holds the source folders for a project. `src` is a merged property.

https://github.com/bndtools/bnd/blob/920be8252daa3850755de049644102276fff6bf0/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L307

This means that the `src` property value and the values from all the properties whose names start with `src.` (which `src.includes` does) are merged into the value of the `src` property. So Bnd expects that `src.includes` specifies additional source _folders_ for the project.

This is not a Bnd bug but a configuration error on your part. You cannot include a PDE build.properties into a bnd file when there are disjoint meanings for property values like `src`.

**Comment by kriegfrj** [comment]
Well, the thing is I didn't include the build.properties file into the bnd file, so I'm not sure how/why bnd was picking it up. I certainly didn't add any `src` directives to my `bnd.bnd` file. And even though I've put the build.properties file back again it seems that it's not getting picked up any more, so I can't reproduce exactly what has happened. I'm happy to put this down to the fact that I was manually manipulating `.project` and `.classpath` files as I was migrating the project from PDE to Bnd.

However, that being said, I still think there is an issue here that needs addressing, as I can reproduce the problem by putting in a src directive in my Bnd file that points to a file that already exists. Bnd doesn't test to see if the file exists before trying to create the directory - instead, it tests to see if the file is a directory. This means that the following code will never get executed:
https://github.com/bndtools/bnd/blob/920be8252daa3850755de049644102276fff6bf0/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L331-L334
...because the mkdir() call a few lines earlier will throw an exception.

It would also be good if the call to mkdir() was a little more robust if it does throw an exception (catch exception, log error, continue to next src element).

I've already got my hands in this code; I'll try and submit a PR to fix these issues.
