### ISSUE TITLE
Comments not skipped in middle of a multi-line directive

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#2394]
I am experimenting with adding/removing different repositories. At the moment, all repositories are added using a single `-plugin:` directive, split over multiple lines using \.

Because I am removing and then putting them back, I decided to comment them out. For example, something like:

````
-plugin:
	aQute.lib.deployer.FileRepo; \
		name='Miscellaneous jars'; \
		location=${build}/misc, \
#	aQute.bnd.deployer.repository.LocalIndexedRepo; \
#		name='Build'; \
#		location=${build}/buildrepo; \
#		latest=false, \
	aQute.bnd.deployer.repository.LocalIndexedRepo; \
		name='Release'; \
		local=${workspace}/build/${target-dir}/repo; \
		pretty=true
````
However, I get an error message in Gradle which seems to indicate that it is trying to load a plugin starting with a # character:

````
:Failed to load plugin #    aQute.bnd.deployer.repository.LocalIndexedRepo;#                name=Build;#            location="C:\workspace\/cnf/buildrepo";#              latest=false, error: java.lang.ClassNotFoundException: #       aQute.bnd.deployer.repository.LocalIndexedRepo not found, parent: org.gradle.internal.classloader.VisitableURLClassLoader@7e8b4139 urls:[] exception:java.lang.ClassNotFoundException: #        aQute.bnd.deployer.repository.LocalIndexedRepo
````

I've seen the same error reported in Bndtools.

Comments seem to work fine if they are not in the middle of a directive.

**Comment by bjhargrave** [comment]
A bnd file is a Java properties file. So it cannot do anything that a Java properties file cannot do. 

A `#` comment is the entire line which means the `\` at the end of the line is part of the comment and not a line continuation character.

You cannot do that sort of comment in the middle of a continued line.
