### ISSUE TITLE
BndPomRepository does not search referenced repositories

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#2396]
If I have a remote pom (for example the enroute reference implementations pom) then I can use the BndPomRepository to make it a repository in my bnd workspace. This works for some poms, but not others. The problem seems to be if the pom (or its parent) declares references to other repositories.

For example - I set up my bnd pom repository like this:

    -plugin.3.R7.Impl: \
     	aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
    		snapshotUrls=https://oss.sonatype.org/content/repositories/osgi/; \
    		releaseUrls=https://repo1.maven.org/maven2/; \
    		revision=org.osgi.enroute:impl-index:7.0.0-SNAPSHOT; \
    		name="OSGi R7 Reference Implementations"

This is able to find bundles from the OSGi Snapshots repo, and it is able to find bundles from Maven Central, but it is *not* able to find bundles from the Apache Snapshots repo. This repo is referenced in the enroute pom: https://github.com/osgi/osgi.enroute/blob/55e14b52e277c653ad8975eccf7e92d7813abfec/indexes/impl-index/pom.xml#L14-L25

I can work around this by adding the Apache Snapshots repo to my snapshotUrls - but why do I have to do this? Shouldn't the BndPomRepository be honouring the repositories declared in the pom files?

**Comment by bjhargrave** [comment]
I don't think the pom traversal includes supporting other repository URLs that may exist. I am pretty sure it does not even parse that part of the pom. The Traverser is initialized with a repo (having a set of URLs) and the traversal assumes all encountered artifacts are available from those URLs. To support repos defined in encountered pom files, the Traverser would need some non-trivial changes.
