### ISSUE TITLE
bnd-baseline-maven-plugin does not evaluate the project's bnd file

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#2403]
Currently the `bnd-baseline-maven-plugin` needs to be configured explicitly via configuration parameters. It would be nice if that plugin would also evaluate the [baseline instruction](http://bnd.bndtools.org/instructions/baseline.html) from the project's bnd file (maybe optionally)

**Comment by bjhargrave** [comment]
The baseline instruction does not allow you to specific a GAV which is needed, in Maven, to select the artifact to baseline against. 

The baseline instruction also assumes a Bnd Workspace model (cnf folder) with configured repositories where a prior version of some Bundle-SymbolicName can be located. Maven builds are not Bnd Workspace model builds (no cnf folder).

**Comment by kwin** [comment]
I see, maybe worth mentioning that in the readme then.

**Comment by bjhargrave** [comment]
There are many bnd instructions and macros which only make sense in the context of a Bnd Workspace model build. It would be nice if the documentation in `docs/` was updated to consistent state this for each item. PRs welcome to improve the Bnd documentation!
