### ISSUE TITLE
bnd-baseline-maven-plugin: don't mark the base parameter as read-only

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#2404]
The base should not be marked as readonly as otherwise features like code completion in Eclipse's pom.xml editor do not work correctly (https://github.com/bndtools/bnd/blob/d7511968b0ec96f1bec5bd3de59f8010cb3cb9f1/maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java#L69). In addition that should be documented as explicit parameter also in https://github.com/bndtools/bnd/tree/master/maven/bnd-baseline-maven-plugin#configuration-properties.

Also it would be nice if all the parameter would have a short javadoc as that is evaluated/exposed as well in IDEs when using code completion.

**Comment by bjhargrave** [comment]
Can you please make a PR with these fixes?

**Comment by bjhargrave** [comment]
> Can you please make a PR with these fixes?

Nevermind, I made the PR.
