### ISSUE TITLE
bnd-export-maven-plugin: No parent for pom null issue 

### ISSUE THREAD

**Issue by rishabh-arora** [bndtools/bnd#2410]
When I try to build (and therefore invoke the bnd-export-maven-plugin) my projects which have bndrun files in them, I keep getting a "No parent for pom null" error. The relevant sections of my pom file are:

```
<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-export-maven-plugin</artifactId>
				<configuration>
					<failOnChanges>fail</failOnChanges>
					<resolve>false</resolve>
					<targetDir>./plugins</targetDir>
					<bundlesOnly>false</bundlesOnly>
					<bndruns>
						<bndrun>blah.bndrun</bndrun>
					</bndruns>
				</configuration>
			</plugin>
```

I've tried deleting my m2 repository and my bnd cache to no avail. Please help.

**Comment by bjhargrave** [comment]
A pom has a parent which cannot be found. 

https://github.com/bndtools/bnd/blob/cb332266fbcf36246ba8fd0998e04e4bab4482e0/biz.aQute.repository/src/aQute/maven/provider/POM.java#L196

However the error message fails to list the missing parent and unhelpfully displays null. I have a fix to display the missing parent.

But you will still need to look into why you have a parent which cannot be found.

**Comment by rotty3000** [comment]
@bjhargrave it's possible that we need to work on the inheritance heuristics

https://maven.apache.org/pom.html#Inheritance

**Comment by rotty3000** [comment]
but yeah, knowing which pom is missing is the first step.

**Comment by rishabh-arora** [comment]
@bjhargrave Yes, knowing which is the erroneous pom would be great. I'll update to the latest version and see what's happening.
Thank you so much!
