### ISSUE TITLE
expand-bcp does nothing, contributeFiles() never called

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#2415]
This is a follow-up of bndtools/bndtools#1871.

Following @bjhargrave's useful tip-off, I started looking at the `expand-bcp` option as a way of supporting bundles on the build path that have embedded jars using the `Bundle-ClassPath` feature of OSGi (implemented in d8c177a055bf051f83acb6e0355d5f280e80d1bb). However, it didn't seem to work (or in fact, to do anything).

After putting in some debug tracing, I determined that my `expand-bcp` parameter is being parsed, but that the setting is simply being ignored. Further, after digging through the code, it seems to me that there may be some code in there which has been partially orphaned.

The unit test for `expand-bcp` verifies that `Container.contributeFiles()` does the right thing when expand-bcp is set. However, it seems that `contributeFiles()` is never called when Bnd assembles the classpath in preparation for the build. Using the Eclipse hierarchy browser, I can see that `contributeFiles()` is only called:

1. recursively, by itself (for handling libraries);
2. by `SubsystemExporter.getBundles()`, which is in turn called by (and only by) `SubsystemExporter.export()`, however it is only called on containers of type `LIBRARY`;
3. by `Project.toFile()`.

`Project.toFile()` looks like it will do the right thing, but it is an orphaned method. It is package-private but is not called anywhere from within Bnd.

Also, though I don't fully understand the purpose or operation of `SubsystemExporter`, by my superficial understanding it seems that this implementation of `expand-bcp` within `contributeFiles()` will actually do the _wrong_ thing in the context of `SubsystemExporter`, as it will incorrectly list the individual embedded jars as separate bundle dependencies in the generated manifest. This bug will only trigger if `expand-bcp` is used in conjunction with a bundle using Bundle-ClassPath and that bundle is part of a library on the build path (if this configuration is even possible).

**Comment by bjhargrave** [comment]
It is unclear what you are requesting here.

**Comment by kriegfrj** [comment]
Yeah sorry, that was kinda deliberate as I didn't feel I had a firm enough grip on the overall architecture or the author's original intent to suggest a particular fix. Some of the possibilities:

* `Project.toFile()` is currently dead code. It is not called anywhere within Bnd and cannot be called from an external app because it is not part of the public API. If the intent was that it should be called from somewhere, I wouldn't know where that somewhere should be without investing a fair bit of time trying to figure it out. I hoped that by reporting the issue, someone might immediately know where to tie in the loose thread without me having to invest that time.
* `Container.contributeFiles()` looks like a useful function, but it doesn't seem to be called when the Builder is assembling the build path. This also means that SubsystemExporter is using an independent codepath to generate the manifest file than what the Builder is using. In my naive understanding, both I think there should only be one code path to generate the build path, and that both should use the same one. But I am not confident that I have properly understood the purpose of SubsystemExporter so I admit that this might be wrong.
* As a result of the above, it seems that the `expand-bcp` parameter doesn't do what it was intended to do, and that the test coverage is incomplete (need more of an end-to-end integration test to catch this; the unit test guarantees that `contributeFiles()` does the right thing, but it doesn't verify that `contributeFiles()` is called when it ought to be).
