### ISSUE TITLE
Test aQute.lib.remote.RemoteTest failed

### ISSUE THREAD

**Issue by Boskovits** [bndtools/bnd#2425]
Gentle maintainer!

I'm trying to get the aQute libg testsuite working on GuixSD.
I need help debugging this, and possibly other test failures.
I could make this test pass by commenting the single line:
assertTrue(IO.getFile(sinkDir, "areas/test/cwd/_ABS")
			.isDirectory());
in public void testTransform()
in bnd/aQute.libg/test/aQute/lib/remote/RemoteTest.java.

What could be the problem here?
How could I debug this?

**Comment by bjhargrave** [comment]
That code is testing that the named file is a directory. 

It is a junit test case, so you should be able to debug it with a debugger like Eclipse.

**Comment by Boskovits** [comment]
Gentle maintainers!

Thanks for the fast and accurate response. It turned out that the build was broken on our site, so I'm closing this as solved.
