### ISSUE TITLE
biz.aQute.remote.launcher "Error: Could not find or load main class"

### ISSUE THREAD

**Issue by axtmann** [bndtools/bnd#2427]
Maybe this is the same like #1131. 
I use bndtool 4.0.0DEV-20180419-201601-g5bad469

My bndrun look like this and it resolves.

```
-runfw: org.apache.felix.framework;version='[5.6.10,5.6.10]'
-runee: JavaSE-1.8

local		=	\
	local; \
	shell   =   4003; \
	jdb     =   1044; \
	host    =   myhost

-runremote: ${local}

-runpath: \
	biz.aQute.remote.launcher
	
-runrequires: \
	osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.shell)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.command)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.scr)',\
	osgi.identity;filter:='(osgi.identity=de.dim.ecf.producer)',\

-runbundles: \
	de.dim.ecf.api;version=snapshot,\
	org.apache.felix.gogo.command;version='[1.0.2,1.0.3)',\
	org.apache.felix.gogo.runtime;version='[1.0.10,1.0.11)',\
	org.apache.felix.gogo.shell;version='[1.0.0,1.0.1)',\
	org.apache.felix.scr;version='[2.1.0,2.1.1)',\
	de.dim.ecf.producer;version=snapshot
```

Without the -runpath it works well, with runpath I get the error "Error: Could not find or load main class"

**Comment by pkriens** [comment]
Did you use the bnd native launching in bndtools?

![image](https://user-images.githubusercontent.com/200494/39935382-1bbb93c6-5549-11e8-9259-c8931ab26d07.png)

**Comment by axtmann** [comment]
No I didn't! I used the "Run OSGi" button in the bndrun file.

With the native laucher, it works for localhost. But not on my Pi. Neither with the hostname nor with the IP Address.

I told the agent -DaQute.agent.server.port=myhost:29998 and see the logging for that on my PI.

When I run the bndrun with the native laucher, the connections hangs at 57% -> "validating session remote - myhost:29998"

**Comment by axtmann** [comment]
I got it running!
With a little bit thinking, I changed the "aQute.agent.server.port" property on the agent to 0.0.0.0:29998.

That did the trick.

Thank you Peter for asking the right question :-)
