### ISSUE TITLE
bnd-testing-maven-plugin could not fine fileinstall.dir

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#2433]
Hi,

I am using the **bnd-testing-maven-plugin** and **Bnd-OSGit-Test-Lancher(Junit)**.
In my .bndrun file i set the property for the fileinstall-dir.
```
-runproperties: \
	felix.fileinstall.dir=cfg
```
Bnd-OSGit-Test-Lancher(Junit) works fine.
Bnd-testing-maven-plugin does only work if I set the absolute path to the fileinstall directory /home/x/y/z/cfg

regards
Stefan

**Comment by rotty3000** [comment]
use this instead:
```
-runproperties: \
	felix.fileinstall.dir=${.}/cfg
```

**Comment by stbischof** [comment]
Thank you!
