### ISSUE TITLE
Component without service but with service properties

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#2442]
Provide a warning if a component has no service defined but still defines service properties

**Comment by bjhargrave** [comment]
The are not (just) service properties. They are component properties. So it is completely legitimate to have a component with component properties which is not a service. So I do not see that that a warning should be provided here.

**Comment by pkriens** [comment]
If they are not service properties one can much better define these properties as defaults on the configuration annotation interface. Using service properties for that is a very roundabout way to set defaults.

It is confusing because we make a heuristic choice based on implemented interfaces. I think it is fair to give a warning when bnd decides to not register the class as a service while it has properties. Alternatively, we could make the heuristic to register the class as a service when it has properties defined.

**Comment by timothyjward** [comment]
> It is confusing because we make a heuristic choice based on implemented interfaces. I think it is fair to give a warning when bnd decides to not register the class as a service while it has properties. Alternatively, we could make the heuristic to register the class as a service when it has properties defined.

That deviates from the specified behaviour of the `@Component` annotation which makes it clear what the value of the `service` member is when not provided. https://osgi.org/javadoc/r6/cmpn/org/osgi/service/component/annotations/Component.html#service()

**Comment by bjhargrave** [comment]
But they are not service properties. They are component properties and have always been so. Yes, component properties are used as the service properties IF the component is registered as a service. A component is a service is the service element is set or the component implementation class directly implements an interface AND the service element is not set to an empty array.

So your scenario is when the component implementation class does not directly implement an interface AND the service element is not set to a non-empty array. This case is also an immediate component.

**Comment by pkriens** [comment]
Yes, and in that particular case I fail to see what reasonable scenario exists that could not be better implemented with defaults on an annotation configuration interface. I cannot think of a scenario where this would be useful?

Clearly when someone sets service={} we should not warn, this would be the way to get rid of the warning. The heuristic is already a a tad hard to see at first (though I think it is intuitively and educationally the best solution) because newcomers assume the service will be the object in that case. 

I agree if there are really useful scenarios it would be not a good idea to warn. However, I can't think of one. Then adding service={} seems a small price for any exceptional scenarios like testing.

**Comment by bjhargrave** [comment]
> Yes, and in that particular case I fail to see what reasonable scenario exists that could not be better implemented with defaults on an annotation configuration interface. I cannot think of a scenario where this would be useful?

Well that is a bit of a stylistic choice. There is nothing wrong or deprecated about using property or properties elements in a Component annotation. There is likely code which does this since that code can predate the introduction of component property types. And even now, it can avoid the creation of a type just to define component properties. Changing Bnd to add a warning will cause issues for builds that upgrade to a newer Bnd which emits the warning you suggest.

**Comment by pkriens** [comment]
well, a warning should not fail and I expect people will find errors. We cannot willy nilly introduce errors but this clearly is a likely an unwanted use so people should take a look.  

We could do it only in -pedantic mode but I expect few people to be affected, and if they are, they probably welcome the warning

**Comment by timothyjward** [comment]
> well, a warning should not fail and I expect people will find errors

A warning should also not occur when you do something that is valid and useful. Setting component properties using the `@Component` annotation is correct, as is not providing a service. Using these together is also the only way to provide default configuration when using DS 1.2 (no configuration annotations).

I don't think that this is a sufficiently significant problem to justify giving erroneous warnings to existing DS 1.2 users using bnd.

**Comment by bjhargrave** [comment]
Closing after discussion.
