### ISSUE TITLE
Support empty parameters for macro "removeargs"

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#2443]
It is often handy to inherit some very common instructions via the bnd-maven-plugin. I want to do that for `-exportcontents: ${removeall;${packages;VERSIONED};${packages;CONDITIONAL}}`

This only works though if neither `${packages;VERSIONED}` nor `${packages;CONDITIONAL}` is empty as `removeall` does currently not support empty parameters (https://groups.google.com/forum/#!msg/bndtools-users/d8K2FTzJdeQ/JeVbVvncAAAJ).

**Comment by bjhargrave** [comment]
Note: you can work around this in Bnd 4.0 as follows:

`-exportcontents: ${removeall;not-empty,${packages;VERSIONED};not-empty,${packages;VERSIONED}}`
