### ISSUE TITLE
Custom Component Property Type used as annotation always leads to including default value as well in the generated component description

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#2445]
I have the following example annotation
```
@ComponentPropertyType
public @interface SlingServletName {
    static final String PREFIX_ = "sling.core.";
    String servletName() default "test";
}
```

And use that within my component as follows
```
@Component()
@SlingServletName(servletName="myname")
public class PathBoundServlet implements Servlet {
  ...
}
```

Now bnd-maven-plugin 4.0.0 generates the following component description out of that
```
<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.3.0" name="org.apache.sling.servlets.annotations.testservlets.PathBoundServlet">
  <implementation class="org.apache.sling.servlets.annotations.testservlets.PathBoundServlet"/>
  <service>
    <provide interface="javax.servlet.Servlet"/>
  </service>
  <property name="sling.core.servletName" type="String">myname
test</property>
</scr:component>
```

Obviously the property with name `sling.core.servletName` is wrong as it contains both the explicitly set as well as the default value in a multivalue property (although the property is being defined as simple String).

**Comment by kwin** [comment]
@timothyjward Do you have any idea, since you contributed https://github.com/bndtools/bnd/pull/2283 initially?

**Comment by timothyjward** [comment]
Looks like a bug in the inheritance handling. There’s no way I can look at this in the next two weeks, so a PR and or @bjhargrave are your best bets in the meantime.
