### ISSUE TITLE
bnd-maven-plugin: Derive values for some OSGi bundle headers from pom elements

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#2447]
Currently only the following headers are automatically set from pom elements (https://maven.apache.org/pom.html)

1. `Bundle-SymbolicName` derived from `artifactId`
1. `Bundle-Version` derived from `version`
1. `Bundle-Name` derived from `name`

In addition the following headers should be derived as well from the according pom elements automatically:
1. `Bundle-Description` derived from `description`
1. `Bundle-Vendor` derived from `organization/name`
1. `Bundle-License` derived from `licenses/license/name`
1. `Bundle-DocURL` derived from `url`
1. `Bundle-Developers` derived from `developers` (with elements `name`, `email`, `organization`, `roles`)
1. `Bundle-SCM` derived from `scm`

**Comment by bjhargrave** [comment]
This is not true. See https://github.com/bndtools/bnd/blob/bb3dfaf5a306c1970e66e1bf23662565a1e87731/biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java#L165. All those headers are processed into the generated pom.

Bnd itself uses this support to generate the poms in the bnd jars.

**Comment by bjhargrave** [comment]
OK. Someone should make a PR.

**Comment by kwin** [comment]
@bjhargrave Can you adjust the milestone accordingly. This will be part of 4.2.
