### ISSUE TITLE
Unable to resolve missing requirement

### ISSUE THREAD

**Issue by phhoef** [bndtools/bnd#2458]
Hi,

I've encountered a problem when building a composite app.
I did basically this [tutorial ](https://enroute.osgi.org/tutorial/030-tutorial_microservice.html) and extended it for a OpenCMIS bundle.

bnd maven plugin: 4.1.0-SNAPSHOT
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

`[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.1.0-SNAPSHOT:export (default) on project my-app: Unable to resolve <>: missing requirement osgi.identity;filter:='(osgi.identity=com.my.app.rest-service)' [caused by: Unable to resolve com.my.app.rest-service version=1.0.0.201805221111: missing requirement osgi.service;filter:='(objectClass=com.my.app.repository.IRepository)';effective:='active' [caused by: Unable to resolve com.my.app.repository.TheRepository version=1.0.0.201805221111: missing requirement osgi.service;filter:='(objectClass=org.apache.chemistry.opencmis.client.api.SessionFactory)';effective:='active']] -> [Help 1]`

I use `@Reference` the SessionFactory in my new bundle.
The bundle can compile, but the error occurs for the Composite Application.

I also figured out, that I can workaround this problem:
When commenting the `@Reference` I can compile and run the Composite Application (of course the field is null). Then uncommenting the `@Reference` and compile ONLY my CMIS bundle and installing the bundle in the started composite application is working fine.

So I do not completely understand why bnd brings up an error during compilation?

**Comment by phhoef** [comment]
Hallo @timothyjward,

thanks for your kind reply.
I am actually quite new to the whole OSGi stuff, so your explanation is very useful.

I added the agument to the bndrun file and a new resolution error came up.
`missing requirement osgi.service;filter:='(objectClass=org.apache.chemistry.opencmis.client.api.SessionFactory)';effective:='active' [caused by: Unable to resolve org.apache.chemistry.opencmis.chemistry-opencmis-client-impl version=1.1.0: missing requirement osgi.wiring.package;filter:='(&(osgi.wiring.package=org.apache.chemistry.opencmis.client.bindings.cache))']]]`
I think this error is different from the first, as it says that a `osgi.wiring.package` is missing and not a `objectClass`. Can I "fix" this also by adding an augment?

I understand, that bnd cannot resolve the dependency as Apache Chemistry does not provide the contract in the manifest, right? - Even if they offer a osgi compatible bundle.
As far as I understood the whole OSGi-thing, now the problem is, that the `opencmis-client-impl` imports the `bindings.cache` bundle and this could not be found, right?
I was wondering why this happens, as the cmis osgi bundle includes the dependencies and Maven should resolve the transitive dependencies?

I have added the `opencmis-osgi-client` to the `runrequries`. Is this necessary?
`-runrequires:\
        osgi.identity;filter:='(osgi.identity=org.apache.chemistry.opencmis.chemistry-opencmis-osgi-client)'`

Sorry, my questions might become a little bit off topic, but I am really stuck ..

Thanks for your help.

**Comment by timothyjward** [comment]
> I think this error is different from the first, as it says that a osgi.wiring.package is missing and not a objectClass. 

Yes, this is different. Previously the error was about a missing service, now it’s a missing package dependency. 

> Can I "fix" this also by adding an augment?

Unfortunately not. Service dependcies are used for resolving, but don’t need to be used at runtime. Package dependencies, however do get enforced at runtime as they are used to wire together the bundles. Using an augment would therefore get you past this resolver error, only to hit the same problem at runtime. 

> I have added the opencmis-osgi-client to the runrequries. Is this necessary?

It is not necessary, but it is not harmful either. It just means that the client will always be part of your application even if nobody is using it. 

> As far as I understood the whole OSGi-thing, now the problem is, that the opencmis-client-impl imports the bindings.cache bundle and this could not be found, right?
I was wondering why this happens, as the cmis osgi bundle includes the dependencies and Maven should resolve the transitive dependencies?

You’re very nearly correct. The client bundle has an import for the named package and that package needs to be provided by someone. This should normally be found somewhere in the dependency graph of the chemistry bundle’s pom, but in this case it seems not to be. 

If you take a look at the dependency graph of your application project you should see the bundles that get added to the index. It looks like you may be missing the client api or the client bindings project. See https://mvnrepository.com/artifact/org.apache.chemistry.opencmis/chemistry-opencmis-client-bindings as a possible source of the package.

**Comment by phhoef** [comment]
Again, thanks for your very detailed explanations.
I am sorry, but I have to bother you again.

I understand, that the `opencmis-client-bindings` package is missing for some reason.
I ran `mvn dependency:tree` and as you already guessed this package occurs in my cmis-bundle and the composite application. I guess, that the composite application just "inherits" the dependencies from the cmis-bundle.
I do not completely understand, why this package is missing. I thought that would be included in the `opencmis-osgi-client` bundle.

Anyhow, I added the `opencmis-client-bindings`, you have mentioned, first the my cmis-bundle and after that also to the composite application. In both cases I get the same error as shown below:

`[ERROR] Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ? osgi.identity: (osgi.identity=com.my.app.api)
          ? [com..my.app.api version=1.0.0.201805260737]
              ? osgi.service: (objectClass=com.my.app.api.repository.IRepository)
                  ? [com.my.app.api.repository.TheRepository version=1.0.0.201805260737]
                      ? osgi.service: (objectClass=org.apache.chemistry.opencmis.client.api.SessionFactory)
                          ? [org.apache.chemistry.opencmis.chemistry-opencmis-client-impl version=1.1.0]
                              ? osgi.wiring.package: (&(osgi.wiring.package=org.apache.chemistry.opencmis.client.bindings.cache))
    [org.apache.aries.jpa.container version=2.7.0]
      ? osgi.service: (objectClass=javax.persistence.spi.PersistenceProvider)
    [org.apache.chemistry.opencmis.chemistry-opencmis-client-bindings version=1.1.0]
      ? osgi.wiring.package: (&(osgi.wiring.package=okhttp3))`

I noticed that the dependency occurs twice. The first time below my Repository implementation, that actually do the CMIS calls and a second time at higher level in the dependency tree.
That confuses me, as I only uses the `opencmis-osgi-client` in my cmis-bundle, nowhere else.
It seems, that the composite application depends also to this package?

It feels like I totally misunderstood something.
Again, many thanks for your help.

**Comment by timothyjward** [comment]
Here the failure chain is telling us that the bindings bundle can’t resolve because it is missing the okhttp3 package. As a result it cannot supply the bindings package, hence you see the same error as higher up. 

There does seem to be something off with the pom dependencies in your project (although it may just be that chemistry have done some weird things). If you are able to share the project in a GitHub repo somewhere then I might be able to get a better idea of what’s going on (although I won’t be able to look at it until Wednesday)

**Comment by phhoef** [comment]
Thanks, I really appreciate your help.
I'll prepare the project and create a repo on github. I'll post the link as soon as it is available ...

**Comment by phhoef** [comment]
Hallo @timothyjward,

I've uploaded my small test project to GitHub. You can pull it from here: https://github.com/phhoef/osgi-test

Thanks for your help :-)
