### ISSUE TITLE
Maven Parent POM include pattern is broken in 4.0.0

### ISSUE THREAD

**Issue by magnet** [bndtools/bnd#2469]
A practical pattern with Maven is to use a common bnd definition in a Parent POM with an optional include to allow child projects to customize the configuration... Something like this:

```<bnd><![CDATA[
Bundle-Description: ${project.description}
-plugin: io.primeval.tooling.bnd.dsap.DSAPPlugin

# Automatically export any package annotated with @Version in its package-info.java
-exportcontents: ${packages;VERSIONED}

# Force Declarative Services bundles to declare a requirement for DS version 1.3
# even when they only use features from a previous version
-dsannotations-options: extender, inherit

# Allow bundles to use osgi.bnd file to extend configuration
-include: -osgi.bnd
]]></bnd>
```

This worked fine up to 3.5.0. Unfortunately this stopped working in bnd 4.0.0, which gives the following error message instead:
```Cyclic or multiple include of /path/to/local/osgi.bnd```

I don't really see why this file would be included more than once, removing that include in the parent POM removes the inclusion. There is no cycle since the osgi.bnd file does not include itself or anything else for that matter.

**Comment by timothyjward** [comment]
The `-include: -osgi.bnd` is an instruction that includes a file from the local directory (in this case the parent). This has never been the recommended way to include a bnd file from a child project when using the bnd-maven-plugin.

If you want to use a bnd file in the child project then you should just include a `bnd.bnd` file in the project (and no `-include` instruction in the parent pom). If you want to use a different name for the bnd file then you can change that in the plugin configuration in the child.

**Comment by magnet** [comment]
Thanks for the suggestion Tim. I understand why does not work now. Your solution works, I can also change the bndfile name in the parent POM.
