### ISSUE TITLE
BndPomRepository should support the BOM pattern

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#2493]
As described in the maven dependency documentation [1] the BOM pattern is nice for aggregating a set of dependencies for reuse by other projects.

The structure is defined as follows:
```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.test</groupId>
        <artifactId>project1</artifactId>
        <version>${project1Version}</version>
      </dependency>
      <dependency>
        <groupId>com.test</groupId>
        <artifactId>project2</artifactId>
        <version>${project1Version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
Note that the packaging is `pom` and the dependencies are located under the `dependencyManagement` element.

[1] https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

**Comment by rotty3000** [comment]
I erroneously stated previously that this was already supported https://github.com/bndtools/bnd/issues/1847#issuecomment-273508791 but I was wrong.

**Comment by bjhargrave** [comment]
I think something like https://github.com/eclipse/microprofile-bom/blob/master/pom.xml is more useful as a "BOM". If your pom depends on that pom, then transitively your pom gets those dependencies. The example in [1] is ridiculously circuitous and complicated. And you still need to write the dependencies in your pom. All the import does is set the version numbers of the dependencies.

**Comment by rotty3000** [comment]
Issue is that people have followed the maven recommended approach:

http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-bom/9.4.11.v20180605/jetty-bom-9.4.11.v20180605.pom

**Comment by bjhargrave** [comment]
Yes, it is not very helpful since I have to repeat all the dependencies in my pom. :-(
