### ISSUE TITLE
p2Repository by target platform misses some artefacts

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#2495]
To reproduce, configure a P2Repository with the following target platform:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><?pde version="3.8"?><target includeMode="feature" name="eclipse.platform">
	<locations>
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
			<unit id="org.eclipse.equinox.sdk.feature.group" version="3.14.0.v20180518-2029"/>
			<repository location="http://download.eclipse.org/releases/photon"/>
		</location>
	</locations>
	<targetJRE path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
</target>
```

Checking the contents of the target platform by opening the file in an Eclipse editor shows, for example, the bundles `org.eclipse.ui` and `org.slf4j.api`, both of which are missing from the resulting Bnd repository.

**Comment by pkriens** [comment]
The P2 repo seems to be heavily used and I've not heard any more reports. @eliasvasylenko do you still see this issue?

**Comment by eliasvasylenko** [comment]
When I try to reproduce the problem now using to the target platform I gave above, Bndtools only shows an empty repository in the Repository view. Which is either the result of another unrelated bug, or is a result of user error. Either way, I can't reproduce the problem like this so I don't know if it's still present, but target-platform-based p2 repositories remain unusable for me.

The plugin entry in `build.bnd` is as follows:

```
-plugin.EclipsePlatform:\
	aQute.bnd.repository.p2.provider.P2Repository;\
		name		=	"Eclipse_Platform";\
		location	=	${build}/cache/eclipse-platform;\
		targetPlatform	=	true;\
		url		=	${fileuri;${build}/eclipse.platform.target}
```

Does this work for you, where `eclipse.platform.target` is as given above?
