### ISSUE TITLE
Bnd platforms for Java 9 and 10 include too many packages

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#2496]
The following modules are present in Java 9/10, but not active by default:

    java.activation
    java.corba
    java.transaction
    java.xml.bind
    java.xml.ws
    java.xml.ws.annotation

The bnd platforms, however include these packages. This means that when I resolve a bndrun against Java 9 or 10 I get a result which does not run due to missing packages at runtime. The relevant packages need to be removed from the bnd platform definitions

**Comment by bjhargrave** [comment]
Are you thinking of the `java.se.ee` module? https://docs.oracle.com/javase/9/docs/api/java.se.ee-summary.html

**Comment by timothyjward** [comment]
> What does not active by default mean? Do you have a pointer to some doc on this?

I encounter the same problems as:
* https://blog.codefx.org/java/java-9-migration-guide/#Dependencies-On-Java-EE-Modules
* https://maarten.mulders.tk/blog/2018/01/migrating-to-java9.html#running-with-java-9

and many more.

This is because the relevant modules are [not present in the runtime by default.](http://openjdk.java.net/jeps/261#EE-modules).

The end result of this is that running the enRoute examples with `java -jar app.jar` blows up due to missing XML packages (needed by JAX-RS). There is no resolver warning about this because bnd expects these packages to come from the platform, which they don't without using extra launch arguments. Specifically I must run:

    java --add-modules java.xml.bind,java.xml.ws -Dorg.osgi.framework.system.packages.extra=javax.xml.bind.annotation,javax.xml.ws -jar app.jar

**Comment by bjhargrave** [comment]
OK, I ran my tools and see the missing packages. So I can remove them from the packages list (e.g. https://github.com/bndtools/bnd/blame/master/biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_9_0.properties).

**Comment by jest** [comment]
Is there any way to remove these packages from EE in bndrun's properties? We're on the stable Bnd and suffering from resolver not adding external bundle with `javax.xml.bind.annotation` package.

**Comment by gopibalagala** [comment]
Hi @jest 

I am facing similar issue, Can you please help me how I will resolve it. 

Thanks,
Gopi.

**Comment by jest** [comment]
@gopibalagala We simply upgraded bnd. In newer versions the definitions of EE-s don't include `javax.xml.bind.annotation`.

We also upgraded EE to Java 11, as 9 and 10 are long unsupported.
