### ISSUE TITLE
Allow Resolve/Bndrun Gradle tasks to be used on bnd.bnd files

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#2513]
Hello,
I am missing tasks in Gradle to resolve and run bnd.bnd files

- [ ] -  separate task "resolve.bnd(project)Name"  that a given bnd.bnd  file could be resolved
- [ ] -  resolve Task should also resolve all bnd.bnd files and not only bndrun
- [ ] -  separate task "runbundles.bnd(project)Name" that a given bnd.bnd  file could  run
- [ ] -  runbundles Task should also run bnd.bnd files

**Comment by rotty3000** [comment]
bnd has bndrun files specifically for that purpose. bnd files are generally reserved for building.

**Comment by stbischof** [comment]
Hi, 

I see, that bndrun should be uses, but as explained here
https://groups.google.com/forum/#!topic/bndtools-users/7Nb43waMg-g

I have to use bnd.bnd files and not bndrun files for testcases.
I want to resolve or just this bnd.bnd file i have no task in gradle.

regards

**Comment by bjhargrave** [comment]
As @rotty3000 stated, bndrun files are the item we support for this. So I don't want to define standard tasks in the Bnd workspace gradle plugin for bnd.bnd file.

Then the solution for you would be to write your own Gradle tasks. See https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/testresources/resolvetask1/build.gradle for examples. But, the current Resolve task wont support bnd.bnd files, so I need to update it to allow you to write your own Resolve tasks in a Bnd workspace gradle build.

I will use this issue to drive changing the Resolve task implementation to allow this.

**Comment by bjhargrave** [comment]
> I will use this issue to drive changing the Resolve and Bndrun task implementations to allow this.

This cannot actually be done. The resolve operation requires a `biz.aQute.resolve.Bndrun` object from the resolver code. I hacked around to make a reasonable solution and it was messy and still failed some tests. So I am abandoning that.

As stated above, bndrun files are intended for things like running and resolving. bnd.bnd files are for project building.

**Comment by bjhargrave** [comment]
PS. I am about to release a change in #3371 which will allow Bndrun tasks to be created for bnd.bnd files of projects in a Bnd Workspace. However Resolve tasks for bnd.bnd files are still not possible.
