### ISSUE TITLE
Delete deprecated SCR annotations 

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#2522]
The bnd SCR annotations have been deprecated for many releases, and the`Service-Component` header is not used any more. These annotations and the associated handling code were targeted for deletion in 4.0, but were missed. They should be deleted.

**Comment by pkriens** [comment]
See #2521

**Comment by timothyjward** [comment]
The old analyzer is here:

https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/make/component/ServiceComponent.java

The old annotations are here:

https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.annotation/src/aQute/bnd/annotation/component

**Comment by bjhargrave** [comment]
We will not delete them but they are marked Deprecated.
