### ISSUE TITLE
pom.xml file has incorrect information

### ISSUE THREAD

**Issue by hughpearse** [bndtools/bnd#2523]
Build artifact: biz.aQute.bndlib-3.4.0.jar/aQute/bnd/plugin/maven/pom.xml
Contains the following content:
```
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>${replace;${project};(.*)\.[^.];$1}</groupId>
  <artifactId>${replace;${project};.*\.([^.]);$1}</artifactId>
  <version>1.0.0</version>
</project>
```
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/plugin/maven/pom.xml
I think under normal circumstances groupId and artifactId should be replaced at compile time, but currently it is not.

**Comment by bjhargrave** [comment]
> biz.aQute.bndlib-3.4.0.jar/aQute/bnd/plugin/maven/pom.xml

Is not the POM of the jar. It is a resource used by code in the `aQute.bnd.plugin.maven` package.

The pom is in the normal place in the jar at `META-INF/maven/biz.aQute.bnd/biz.aQute.bndlib/pom.xml`.
