### ISSUE TITLE
Allow bnd cli to iterate over projects

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#2524]
The "perProject" in bnd.java allows to iterate commands over all projects of the workspace.
But in line 838 it returned the method to early.
https://github.com/bndtools/bnd/blob/6c19d146106fb2ecfd62175f8d542443fb35d5d3/biz.aQute.bnd/src/aQute/bnd/main/bnd.java#L838

Line 1316 needs a nullcheck on Project.
This could be null.
https://github.com/bndtools/bnd/blob/6c19d146106fb2ecfd62175f8d542443fb35d5d3/biz.aQute.bnd/src/aQute/bnd/main/bnd.java#L1316

It would be nice to have 
perProject in the other commands like clean, ~~resolve~~, ~~baseline~~, ~~bump~~

**Comment by bjhargrave** [comment]
Can you please make a PR with fixes?

**Comment by stbischof** [comment]
Sure.

**Comment by stbischof** [comment]
fixed #2529
