### ISSUE TITLE
doc: Incorrect handling of @jar!/path/* on -includeresource

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#2539]
The doc, https://bnd.bndtools.org/instructions/includeresource.html, says
 
> The inline requires a ZIP or JAR file, which will be completely expanded in the target JAR (except the manifest), unless followed with a file specification. The file specification can be a specific file in the jar or a directory followed by ** or *. The ** indicates recursively and the * indicates one level. If just a directory name is given, it will mean **.
 
 
However, the following 2 things are not true:
 
1) `*` is translated by `Instruction` to `.*` in the regex so `*` in the path is the same as `**`. That is `*` is not limited to one directory level.
 
2) If just a directory name is given (e.g. `org/foo`) it is not followed by `**` (e.g. `org/foo/**`)
 
The root problem of (1) and (2) is that the path value is just passed to `Instruction` which uses its normal globbing rules.

**Comment by pkriens** [comment]
This is old text ... this is being rewritten as we speak ...

**Comment by bjhargrave** [comment]
Reopening as a placeholder for the documentation update.

**Comment by bjhargrave** [comment]
Fixed for 4.1.
