### ISSUE TITLE
Bnd fails for Groovy code. Complains about code in default package.

### ISSUE THREAD

**Issue by tombensve** [bndtools/bnd#2557]
I'm using OSGi and are writing my code in Groovy. I'm using maven-bundle-plugin which basically just wraps  bnd. For most groovy bundles bnd complains about there being code in default package. That is not true. I decompiled the class files and looked at what the groovy compiler have produced. There is nothing in the default package. So there is something in bnd which makes it think it is, for groovy code. 

I have currently made a workaround that comments out some code, see: https://github.com/tombensve/bnd/blob/master/README.md

This is then the version I'm using and since it uses Gradle I have no idea how to resolve what version it actually is. I really looked around trying to find a version, but failed. The pom:s under maven only have ${revision} so it must be passed on by some other build script. I cannot find where it actually is specified. I did a "find . -type f -exec egrep "ersion" {} \; -print" but that gave a far too large result to get a candidate. But the latest release in the repo is DEV 4.0.0. 

Java version: openjdk version "1.8.0_152-release"
OS: Mac OS X High Sierra - 10.13.5
Git-SHA: 02bd7a2242b2ac9c99c1e93b35a7124bc917deaf
Git-Descriptor: 4.0.0.DEV-231-g02bd7a224

**Comment by tombensve** [comment]
Well since I got the Git-SHA from my build of Bnd it is really no help, it only points to my latest README.md update. :-)

**Comment by pkriens** [comment]
The code you commented out says you **refer** to the default package. Since you cannot import the default package this is erroneous. The error actually tells you which packages in the bundle refer to the default package.

If you want to ignore this error you can use `-fixupmessages` to remove the offending error.

**Comment by tombensve** [comment]
The point is that I'm not importing the default package. What I am doing is writing code in Groovy, not Java. When I write a bundle in Java, there is no problem. When I write a bundle in Groovy I always get this error. 

Do  note that OSGi itself has no problem what so ever with my Groovy bundles. I've run them in Karaf (felix), Glassfish (might be felix), Knoplerfish, Virgo. If the bundles really were importing the default package I'd think there would be complaints, at least warnings. But I get no such. But as soon as I use Groovy as language bnd complains about default package. There seem to be a clear connection between bnd and groovy code.

**Comment by pkriens** [comment]
I understood that, but then Goovy is importing 'something' from the default package. Did you inspect the code in the packages that bnd points out in the error message?

This is probably another weird quirk of Groovy that is harmless but in that case using `-fixupmessages` is a much simpler solution than removing a quite important error message from the code.

**Comment by tombensve** [comment]
Commenting out this code was a temporary dumb fix to go around the problem. That is why I called the branch dumb-fix. It was never intended as a final solution to the problem, which is why I created this issue. 

I was unaware of the -fixupmessages argument, I will try that. The maven-bundle-plugin does not seem to support that. I do assume that it will work with bnd-maven-plugin.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate.

**Comment by bjhargrave** [comment]
Also note, that the Bnd build itself builds and packages Groovy code since the Bnd Gradle Plugin is written in Groovy. See https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle. So Bnd clearly can work with Groovy code.

**Comment by bjhargrave** [comment]
Please add some information if you want us to reopen.
