### ISSUE TITLE
SCR XML Element Order Compliance

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2561]
The SCR XML generated by Bnd doesn't comply with the schema. According to the schema, the order of the elements should be in sequence but Bnd arranges the elements differently. Apache Felix SCR Maven Plugin does a good job to maintain the order as it is specified in the schema.

I believe it makes more sense to comply with the SCR schema as well even though in OSGi runtime, it works always without maintaining the order.

**Comment by bjhargrave** [comment]
XML Schema compliance is not required by the spec. See https://osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-schema:

> SCR must not require component descriptions to specify the elements in the order required by the schema. SCR must allow other orderings since arbitrary orderings of these elements do not affect the meaning of the component description. Only the relative ordering of property, properties and reference elements have meaning for overriding previously set property values.

**Comment by amitjoy** [comment]
Thanks for pointing it out. Didn't know that it is a part of spec.

**Comment by pkriens** [comment]
Which does not mean that bnd can be a bit more religious than the pope ...

I like the strategy to accept a lot, but generate into minute detail.

**Comment by bjhargrave** [comment]
My point is that Bnd is not in error. If it is easy to change Bnd to emit in the schema specified order, then someone can make a PR.

**Comment by pkriens** [comment]
On that we agree :-)
