### ISSUE TITLE
Max Stale time of 1 Year as default for OSGiRepository

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#2563]
A once downloaded index of an OBR would become stale after a year by default, which is quite heavy. I can set the stale time on every Repository I define, but wouldn't it be nicer, if we would have something more reasonable like a day?

**Comment by pkriens** [comment]
PR?

**Comment by bjhargrave** [comment]
Well the repo for a released product will never change. For example, https://dl.bintray.com/bnd/dist/4.0.0/. So a looooong stale time is fine. But for some it will change, which is why you can configure the max stale time to your needs. :-)

**Comment by juergen-albert** [comment]
We usually use an aggregated index, where all our release versions are in one repository. This naturally changes quite frequently. The default is not very user friendly, because this is not obvious for anybody that is not familiar with the inner workings of bnd. Even with some knowledge I was often wondering, why our build server from time to time didn't find new artifacts in the  OBRs, so I opted for deleting the .bnd before every build. Most people don't have to worry about a few requests more, because the network coverage is good enough. So asking a few times more will not hurt nobody.

**Comment by bjhargrave** [comment]
Well, if you know the repo contents will change at some frequency, then you should configure your max stale time to match. But changing the default is something everyone will need to deal with especially if we assume that most fixed repos are generally stable.

When I know the repo index is stable, I turn off the polling altogether (`poll.time=-1`).

https://github.com/bndtools/bndtools/blob/81e7d71457a07014704904652d4a701889f3741f/cnf/ext/repositories.bnd#L48-L52

When I know the repo index changes, I set an appropriate stale time:

https://github.com/bndtools/bndtools/blob/81e7d71457a07014704904652d4a701889f3741f/cnf/ext/repositories.bnd#L12-L15

**Comment by juergen-albert** [comment]
It is hard, to make the right assumption on what the most common usecase is, to set a reasonable default. We can close the issue from my side, because we at least have it documented now.
