### ISSUE TITLE
Redirect to login overwrites maven jars

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#2586]
Just noticed that the MavenBndRepository can overwrite Maven files when it is redirected to a login screen. The content of the jar is then the login screen

**Comment by kwin** [comment]
Sonatype’s Nexus solves that issue by sending a 401 status code with the login form.

**Comment by pkriens** [comment]
Yes, and that is correctly handled. Unfortunately some setups are more complex and have proxies in front of Nexus and they are not so elegant.

**Comment by pkriens** [comment]
Moving to abeyance since this probably was a bit of a freak case, very hard to diagnose this is happening, and no time to do this really right.

**Comment by bjhargrave** [comment]
@pkriens  Did you mean to close this? Or move to Abeyance?
