### ISSUE TITLE
BndPlugin is not working with Xtend

### ISSUE THREAD

**Issue by Sandared** [bndtools/bnd#2591]
Hi,

I tried to do a gradle build with the bnd-workspace plugin applied to my workspace, where I'm using Xtend as programming language. This leads to the following error message:
`No such property: outputDir for class: org.xtext.gradle.tasks.internal.DefaultXtextSourceDirectorySet`

The BndPlugin [seems to assume that every SourceDirectorySet has the property `outputDir`](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L127), which is not true for `DefaultXtextSourceDirectorySet` . 
First I've [opened a issue at the Xtend repository](https://github.com/xtext/xtext-gradle-plugin/issues/125), but they told me that this property is not mandatory for a SourceDirectorySet.

Can you think of a workaround for this issue?

Kind regards,
Thomas

**Comment by bjhargrave** [comment]
I am not sure why they think that SourceDirectorySet does not have an outputDir property. See the javadoc for yourself: https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html. You can clearly see getter and setter methods for outputDir. 

I think the situation here is that Xtend is pretending to be a SourceDirectorySet (see the type names!) but is failing to actually support the API contract of the gradle type org.gradle.api.file.SourceDirectorySet. So this upsets Bnd (and anyone else who assumes SourceDirectorySet is actually a SourceDirectorySet.)

I do not see how the issue here is not in Xtend's gradle plugin for failing to meet the contract of SourceDirectorySet.

**Comment by oehme** [comment]
There is no contract that says that `sourceSets.main.foo` will be of type SourceDirectorySet. This is just a common convention of the java, groovy and scala plugins, but other plugins are free to add anything they want there. The bnd plugin should replace its implicit type assumption with an explicit check.

**Comment by bjhargrave** [comment]
So how should one treat `sourceSets.main.foo`? If there is no expectation that it has any specific object shape, you basically cannot trust using it. I suppose Bnd could ignore it if it is not an instance of SourceDirectorySet, which is an object shape Bnd understands.

@Sandared, this would mean the Bnd Gradle plugin would basically ignore the Xtext sourceSet. Is that what you expect? `DefaultXtextSourceDirectorySet` goes 95% of the way to actually be shaped like a SourceDirectorySet but doesn't quite finish the job.

**Comment by oehme** [comment]
Yes it should check for that type and yes ignoring Xtext is correct because it is not a JVM bytecode generating language, but a code generator.

**Comment by Sandared** [comment]
@bjhargrave  First: Thank you for your efforts on this issue.
But I'm a little bit lost now. 
So if the Bnd Gradle plugin ignores the Xtext sourceSet, then I cannot use Xtend in a Bnd workspace build? 
Or are there multiple sourceSets and only Xtend is ignored because it generates sources instead of bytecode but others (normal java sourceSet) are working as expected?
Sorry if this is a dumb question, I'm just not that used to Gradle yet.

**Comment by oehme** [comment]
No, this will not prevent you from using Xtend. bnd will just not try to set a class directory for Xtend (because Xtend doesn't generate classes).

**Comment by Sandared** [comment]
Thanks @oehme . Then this solution would be great :)

**Comment by bjhargrave** [comment]
I took a middle ground by not requiring the language convention to implement SourceDirectorySet but requiring it to have the `srcDirs` and `outputDir` properties.
