### ISSUE TITLE
Cannot resolve `Require-Bundle: system.bundle`

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#2600]
A 3rd-party bundle in my repository has:

    Require-Bundle: system.bundle

This results in a failure to resolve, using bnd-export-maven-plugin, version 4.0.0:

```
[ERROR] Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⮡ osgi.identity: (osgi.identity=___.______.___._______.____)
          ⮡ [___.______.___._______.____ version=1.0.0.201809051252]
              ⮡ osgi.wiring.package: (&(osgi.wiring.package=javax.xml.transform.stream)(&(version>=1.3.0)(!(version>=2.0.0))))
                  ⮡ [javax.xml version=1.3.4.v201005080400]
                      ⮡ osgi.wiring.bundle: (osgi.wiring.bundle=system.bundle)
```

I was able to work around by adding a `-runsystemcapabilities` instruction as follows:

```
-runsystemcapabilities: \
	osgi.wiring.bundle; osgi.wiring.bundle=system.bundle
```

... but obviously this should not be necessary.

**Comment by bjhargrave** [comment]
I think this has already been fixed in bb05e82ea5259aac32f4199335bb6072205b9fde for 4.1

**Comment by njbartlett** [comment]
Thanks, I'll try a snapshot build.

I remember the discussion about this in the mailing list, but couldn't find an existing bug report...

**Comment by njbartlett** [comment]
Verified fixed.
