### ISSUE TITLE
Wrap Task for Gradle  

### ISSUE THREAD

**Issue by jozzan** [bndtools/bnd#2615]
I guess that would be a nice addition.

**Comment by unautre** [comment]
There is already a way to bundle external jars ([here](https://bnd.bndtools.org/chapters/390-wrapping.html)), based on creating a .bnd file, and that works in Gradle as well as in Eclipse. Maybe this is redundant ?

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/issues/2422 for some discussion on the direction we are interested in going with wrapping.

Based upon a discussion with the other Bnd developers, we are not currently interested in adding a wrap task to gradle at this time. Once we sort out the issues discussed in https://github.com/bndtools/bnd/issues/2422, we may reconsider a wrap task.
