### ISSUE TITLE
Bndtools cannot be updated anymore

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2619]
Due to the introduction of OSGi CDI in https://github.com/bndtools/bnd/commit/0a13d0499794d9814e3b0b6b37aabb6178a6f7f1, bnd introduced a dependency on javax.exterprise which cannot be resolved in "Eclipse IDE for Java Developers". It will only work in "Eclipse IDE for Java EE Developers".

**Comment by pkriens** [comment]
Oops, that is bad. @rotty3000 can you quickly fix this?

**Comment by rotty3000** [comment]
Yup, I'll fix it asap.

**Comment by rotty3000** [comment]
just confirming the fix right now... should be up in a few moments.
