### ISSUE TITLE
Add a way of preventing bundles being included in -runbundles

### ISSUE THREAD

**Issue by gravelld** [bndtools/bnd#262]
I'd like a way  of preventing inclusion of bundles in -runbundles inside a bndrun file.

ATM logback keeps getting included in -runbundles against my wishes. It's probably some 3rd party bundle (or even my own) but there's no actual runtime dependency on the bundle.

An equivalent of Import-Package: !(package.name),* would be useful. I tried the following LDAP filter in -runrequires to no avail:

osgi.identity;filter:='(!(osgi.identity=ch.qos.logback*))'

**Comment by rotty3000** [comment]
This is now available by `-runblacklist`

```
-runblacklist.enroute:	\
	osgi.identity;filter:='(osgi.identity=osgi.cmpn)'
```

Extend the filter with version attribute to blacklist by version.
