### ISSUE TITLE
Publish BND Gradle Plugin 4.1.0

### ISSUE THREAD

**Issue by anfark** [bndtools/bnd#2625]
Hi,

the docu of the gradle plugin already cites version 4.1.0 as newest release. However the currently available version of the gradle plugins on maven central is still version 4.0.0.

**Comment by bjhargrave** [comment]
4.1 is still under development. That latest released version of Bnd is 4.0. You can see the latest release (ends in `.REL`) here: https://github.com/bndtools/bnd/releases

Once 4.1 is complete, we will of course publish it to all the usual places.
