### ISSUE TITLE
Sourcepath of a project includes sources of dependson projects

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#2627]
I cant see why the sourcepath of a `aQute.bnd.build.Project.` includes sources of dependson projects?
Is this wrong or what are the reasons?

https://github.com/ScienceCityJena/bnd/commit/5e2eabe3b804eadf01a2e06c3e47d0ff17f5a39a#diff-36dfafab267cc44e1c2060c59683808eL418

**Comment by bjhargrave** [comment]
That is not the sourcepath, it is the allsourcepath property which is useful for things javadoc commands where you need the source of the project and all dependencies..
