### ISSUE TITLE
Add support for start levels in bndtools launcher

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#2635]
Please see discussion of this issue in bndtools-users group:

https://groups.google.com/forum/#!topic/bndtools-users/xzPIh9fE6vg

Reported by Scott Lewis on bndtools

**Comment by scottslewis** [comment]
Any changes on this issue?

**Comment by pkriens** [comment]
Nope, and I do not think it will happen this year if I have to do the work for free ... Too many other things.

**Comment by scottslewis** [comment]
Was there anything done for this issue, or just closed without any changes to launcher, or ?

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/pull/3258. I think further refinements have been made since that PR.
