### ISSUE TITLE
Add support of maximum version for SCR and Metatype Annotations

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2643]
`-dsannotations-options` and `-metatypeannotations-options` instructions do support the minimum version but if the developer mistakenly uses any functionality which is introduced in higher versions, the DS or Metatype XML gets generated without any errors or warning but it gets really difficult to find out the problem in runtime since the XML namespace uses higher versions. To make it simple and usable, a maximum version would really help users to encounter such problems beforehand.

**Comment by amitjoy** [comment]
Found the discussion and related PR: https://github.com/bndtools/bnd/pull/2603

**Comment by bjhargrave** [comment]
You should control the maximum version of DS xml by the version of the component annotations on your build path. If you use DS 1.3 component annotations, then you wont use DS 1.4 annotation features.

**Comment by kwin** [comment]
Just for the record: A maximum can now be given: https://github.com/bndtools/bnd/commit/1482d0734c388e1ed9217bd97b6a5538450af2c5

**Comment by pkriens** [comment]
Fixed in #3121
