### ISSUE TITLE
Skip Signed-off-by when going through Github web ui

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#2652]
When we go through the Github web UI all our actions are completely identified in the trail. Do we still need to do `Signed-off-by: Peter Kriens Peter.Kriens@aqute.biz` then? Seems superfluous and easy to forget.

**Comment by timothyjward** [comment]
Yes we always need it. It is your certification that the commit is all your own work and is allowed to be contributed See the detail at https://developercertificate.org. It is really that challenging to add `-s` to your commits? You can even add an alias so that it always gets applied, for example:

    git config --global alias.commit 'commit -s'

**Comment by timothyjward** [comment]
Sorry - I've just noticed that you were talking about the Web UI. We still need the sign off, but I agree that it's easier to forget the sign off. I tend to avoid the Web UI anyway as you can't change multiple files in one commit, or easily test your changes before committing.

**Comment by stbischof** [comment]
A pull_request_template.md could help to not forget. (But it is to late because the commit is done.)

**Comment by bjhargrave** [comment]
> When we go through the Github web UI all our actions are completely identified in the trail.

This is not the issue. We always know who the committer is since their name is in the commit. The `Signed-off-by` is a affirmative statement that you must add to indicate your agreement to contribute under the DCO. 

If you want to remove the need for the DCO and the `Signed-off-by`, then we will need to transition the project to using signed Contributor License Agreements (CLA) which we must require from each contributor before we can accept a contribution. This is much more heavyweight than the DCO.

**Comment by pkriens** [comment]
Can we do the CLA for the people that want that? I.e. casual committers do the sign off, hard core committers do the CLA. I kind of like the Web GUi of Github more and more, especially for the documentation. Not having to worry about the sign off would make it even easier.

**Comment by pkriens** [comment]
... and hard to use ... I think you're already policing the Signoff for IBM? What would be the difference?

**Comment by bjhargrave** [comment]
If you want to change the process from DCO to CLA, then lets discuss what is involved. If you want to have no IP process, then I think people may no longer want to be users of the project or be involved in the project. 

For me, I require we have an IP process. I am very happy with the current lightweight DCO process, but I am open to discussing changing to a heavier weight CLA process to satisfy your personal needs. I am however not interested in having no or a poor IP process for this project. 

Current best practices seem to be DCO or CLA (for projects which want a higher level of control and certainty).  But some mash-up hybrid process would be untested and unproven and I am not at all interested in such a change.

**Comment by stbischof** [comment]
I remember a browser plugin which automaticly fills some text in a named Form of a page

A fast search may gives you a result for your favorite browser.

Chrome autofill.
