### ISSUE TITLE
Artifacts not rebuild when dynamic variables changes

### ISSUE THREAD

**Issue by swimmesberger** [bndtools/bnd#2664]
If you use macros in the bnd.bnd file which can change over time without manually modifying the bnd.bnd file - bnd does no rebuild. A small example based on "${tstamp}" can be found here: https://github.com/swimmesberger/bnd-dynamic-bug-test/tree/master/builderPlugin. 
A other example would be using:
`Custom-Property: $(env;IMPORTANT_PROPERTY;0)`
If the property is changed between build - bnd does no rebuild.

The first issue I identified is gradle, the bnd.bnd file is used as an input - so if the bnd.bnd last modified date changes the jar task is reexecuted but this does not work for dynamic macros because this does not change the file itself but the output the file produces.
As a workaround I have added the following groovy script to my buid.gradle in my example project mentioned above:
```
import aQute.bnd.osgi.Macro;
import aQute.bnd.osgi.Processor;

Processor p = new Processor();
Macro m = new Macro(p);

project.tasks.getByName('jar').inputs.property("time", m._tstamp(new String[0]))
```

This ensures that if the tstamp property changes, gradle does a rebuild of the jar task.

This solves the issue for the builder gradle plugin.

Then there is a second issue similar to this with the workspace plugin - an example can be found here:
https://github.com/swimmesberger/bnd-dynamic-bug-test/tree/master/workspacePlugin

Here we have the same issue with the gradle task inputs which is solved in the "settings.gradle" in a similar fashion of the builder plugin gradle task fix.
In the workspace plugin there is a second "caching" layer which prevents a rebuild of the resulting artifact which we can see here:
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L1922

The last modified of the newly build jar will not be changed by a simple change of an environment variable because we have not touched any *.java file or any *.bnd file. The reason for this is probably here:
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L133
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java#L336

Because setting the newly created manifest does not modify the lastModified property of the created Jar file even if it has changed. Even if the lastModified would be set here - we would trigger a new jar for every build even if there are no changes in the manifest so there would be some kind of hashing needed.

I kind of get why a change of the tstamp property should not trigger a new artifact because why would you need a "new" artifact just because time hast passed but for the use case of using environment variables it's kind of unexpected that a change of such a variable does not trigger any rebuild - especially for beginners who are used to such a behavior based on the experience with maven/gradle.

**Comment by pkriens** [comment]
How does Gradle detect environment vars change? And why could the same mechanism not be used by the bnd workspace build?

Kind regards,

	Peter Kriens

**Comment by swimmesberger** [comment]
My guess:
Because gradle uses well defined inputs and outputs for each task it can determine changes between runs. E.g.:
```
Task t;
t.inputs.property("envVar1", System.getenv("testprop"))
```
This defines environment variable "testprop" as a input property for a Task t, you can now freely use this property in the task action (executing part). Gradle persists every input of a task and compares the pesisted state with the current state if a change is detected - the task is reexecuted.
This can be seen here:
https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

**Comment by pkriens** [comment]
Bu that only seems to work when you program the exact environment variables in your gradle build? 

So I am not sure why you could not do that with a bnd build? I.e. it seems outside anything bnd could do? (Except provide a has on the expanded properties but then you already invoke it and cause a lot of work to be done?)

Puzzled a bit ...

Kind regards,

	Peter Kriens

**Comment by swimmesberger** [comment]
Example:
When I use a environment variable "ENV_PROP_1" in gradle for a task. Gradle uses that property to check if it has to rerun the task.

When I use the environment variable "ENV_PROP_1" in gradle with bnd in a bnd.bnd file 2 things go wrong:
1. Bnd does not define any environment variable as input for it's custom "jar" gradle task which let gradle think that everything is up-to-date. You can as a workaround manually add the environment variable "ENV_PROP_1" as a input for the jar task which solves this point but in my opinion bnd should solve this because bnd knows already (because it understands and parses .bnd files) which variables and used and therefore inform gradle about it.
2. Bnd in workspace mode has a internal "cache" mechanism which does not check for environment variable changes. Like explained in the issue description bnd does not overwrite the file in the "generated" folder because it thinks nothing has changed (because the file modification date is still the same) but in reality the value of the environment variable has changed. There is no workaround for this because you can't tell the bnd workspace build that environment variable "ENV_PROP_1" is used and should therefore trigger a rebuild like you can do with gradle.

The only workaround I have found is to create a extra gradle task with the environment variable as input (so the task only runs then the variable changes) and then touch the "bnd.bnd" file (changing the last modification date) of the project which makes of the variable this lets bnd think that something has changes which then leads to a rebuild.

**Comment by bjhargrave** [comment]
Gradle drives the build here and decides whether to execute a task, which may call Bnd, based upon task inputs and outputs. This is the primary mechanism. You have identified how to use a property value as a task input to drive rerunning the task.

Internally Bnd tries to avoid writing out the jar file is the Jar object is made of the same resources (via resource timestamps) as the jar on disk. Since the manifest is computed, it does not itself have a timestamp which influences the Jar object lastModified time. Otherwise it would always be the current time which makes meaningless the whole effort.

For your uncommon use case, perhaps Bnd needs an instruction to always write out the Jar object regardless of the timestamp comparison with the jar file on disk. Then you could use that Bnd instruction in your use case.
