### ISSUE TITLE
make it possible to emulate contracts when you don't have any on the classpath

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#2701]

**Comment by bjhargrave** [comment]
I am kind of unclear what this issue is asking for. It would seem to me that to provide a contract one must state the packages in the contract, the contract name, the contact version and the versions which are compatible with this contract version.

How can all that information be inferred from the classpath?

**Comment by pkriens** [comment]
I had a short discussion with Ray about this. Ray wants to use more contracts even if the target JARs do not contain contract info. My proposal was to allow other JARs to just provide contract information. By adding one of those contract JARs you could get contract behavior.

**Comment by rotty3000** [comment]
I felt there were too many contacts and too many versions of them for real
jars to be usable. You usually want a particular version at compile time,
but if we make a monolithic container of contracts, at compile you'll
always just get the highest.

I feel it will be much easier to adopt an instruction that can benefit from
things like Maven properties.

I do agree that ideally all of this is just pushed into the background,
never to be seen by users. Sadly, I don't think that is realistic.

**Comment by rotty3000** [comment]
The idea is more about helping library developers. For example, JakartaEE may need to compile against spec jars that don't have contracts. The issue is a chicken and egg problem. We'd like libraries to use contracts, but they won't until there are dependencies with contracts... and so on and so forth. I'd like to be able to break the chain and start somewhere.

@bjhargrave @pkriens feedback?

**Comment by bjhargrave** [comment]
So does this mean Bnd would have included the well known contracts to be used by Bnd? Contracts need to exist at runtime (as well as tool time). If we only emulate contracts at tool time, then how will the generated bundles function at runtime when no one provides the contract?

Or is this about detecting when someone is building something which should provide a contract and guessing the right contract to insert in the built jar?

**Comment by rotty3000** [comment]
> So does this mean Bnd would have included the well known contracts to be used by Bnd?

No!

An example is `microprofile-config`. This project compiles against the spec version `javax.enterprise:cdi-api`. It is improbable that they will change this. However, this also means it is unlikely to get a contract even though there are bundles that provide the contract. So the idea is to have a means to let the library be compiled against a jar that does not provide the contract but declare that a contract will be used when running in OSGi (even if it's optional).

The idea would to provide something like the following in the bnd configuration:
```
-contract-options: JavaCDI;version:Version='${cdi-version}';uses:List<String>='javax.decorator,javax.enterprise.context,javax.enterprise.context.spi,javax.enterprise.event,javax.enterprise.inject,javax.enterprise.inject.spi,javax.enterprise.util'
```
When the mentioned packages are encountered, the contract is applied and no versions are applied to either imports.
If the library doesn't want this to be a hard requirement, then `-contract` instruction can simply be overridden with:
`-contract: JavaCDI;resolution:=optional` OR
`-contract: JavaCDI;effective:=active`

**Comment by bjhargrave** [comment]
> This project compiles against the spec version `javax.enterprise:cdi-api`. It is improbable that they will change this.

Well soon it will be `jakartaee:cdi-api` with different package names...

So I am still not sure what you are saying. That MP will change their pom to include that Bnd instruction to add the CDI contract so that Bnd will acts as if some -buildpath jar actually declared the contract?

**Comment by rotty3000** [comment]
> That MP will change their pom to include that Bnd instruction to add the CDI contract so that Bnd will acts as if some -buildpath jar actually declared the contract?

Yes.
