### ISSUE TITLE
Clazz doesn't provide a way to find `getEnclosingClass` to detect inner classes

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#2714]
The only way I've found to do it is kind of roundabout by checking if the name contains a `$`.

**Comment by bjhargrave** [comment]
The visitor has an `innerClass` method which provides the information from the `InnerClasses` attribute.

**Comment by rotty3000** [comment]
Got it!

However that makes it hard in the case where I want to quickly filter out classes to actually work with:
```
                        Clazz c = ...
			if (c.isEnum() || c.isInterface() || c.isAnnotation() || c.isSynthetic() ||
				!c.is(QUERY.CONCRETE, null, analyzer) ||
---> inner class		(c.getClassName().getFQN().contains("$")) && !Modifier.isStatic(c.getAccess())) {
				// These types cannot be managed beans so don't bother scanning
				// them. See
				// http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#what_classes_are_beans
				continue;
			}
```

**Comment by bjhargrave** [comment]
Yes. I am deep into my work on a new class file object model and parser and that should make what you want to do easier once I am finished and I get it integrated in.
