### ISSUE TITLE
Junit XML parsing fails due to quotations

### ISSUE THREAD

**Issue by karusher** [bndtools/bnd#2725]
The Junit XML report produced by biz.aQute.junit can be invalid.  

This will occur if a Throwble is thrown by a testcase where the Throwable message contains an unescaped quotation.  The message attribute in the <error> tag will have the same unescaped quotation.

The resulting XML report cannot then be parsed.

The example below is an example of the problem. The exception contains a message with JSON.

```
<error type='java.lang.AssertionError' message="cart item price expected 0.0 but was 1.0 for price.unitPrice.amount for the second product from cart
{
  "testType" : "PRICE_CART",
  "numberOfProducts" : 2,
  "initialLifeCycles" : { },
  "productItemsToShareTechnicalContract" : [ 0, 1 ],
  "objectValuesToSet" : [ {
    "productIndex" : 1,
    "objectType" : "PRODUCT",
    "valueToSet" : "productCharacteristic[id='b6f6383470d9c409ba059c56852b0ef6'].value",
    "value" : "2018-11-24T07:22:18.833-05:00",
    "when" : "BEFORE_ADD_CART_ITEM",
    "createIfNotExist" : true
  } ],
  "productIndexToSetIntsallBase" : 1
}">
```

I think it is valid to throw exceptions with unescaped quotations in the message. Would it be possible to perform the quotations escape inside Bnd?

**Comment by bjhargrave** [comment]
The issue is that the code does not handle both `'` and `"` being in the value.  I will make a fix.

**Comment by bjhargrave** [comment]
Turns out this same issue was reported on a different copy of the `Tag` type in this repo: https://github.com/bndtools/bnd/issues/121.
