### ISSUE TITLE
bnd-export-maven-plugin fill up memory

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#2732]
When using the bnd-export-maven-plugin:4.1.0 it happens that the export process hangs and fills up my 8gb memory and the swap. I am unable to provide the exact circumstances, I would like to know if it is a know issue of the resolver or if there is common case that leads to this problem?

**Comment by timothyjward** [comment]
I have not seen this happen. How large is the repository that you're resolving from?

**Comment by cdelg** [comment]
The repository is composed of the OSGI distro provided by enRoute with 100 more bundles. The problem also appears in BndTools. To solve this issue I removed the `-runrequired` and added my dependencies one by one until... the  `-runrequired` was exactly the same as before but this time it has worked :/ I am always a little scared when I hit the resolve button, this button is uncompromising! 

I have not a lot of information to share, debugging the resolve process is hard, so I think this issue can be closed. If it happens again I'll provide more details.

Thanks.

**Comment by stbischof** [comment]
I had some endless resolving issue while trying to resolve with Xerxes and XML-api.

What resolven do you use?

**Comment by cdelg** [comment]
> What resolver do you use?

I am not sure to understand your question! (I use the bnd-export-maven-plugin:4.1.0, it's all I know)

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by cdelg** [comment]
Sorry I can't, next time I will investigate further.  I close this issue since I didn't encounter this problem again.
