### ISSUE TITLE
[bnd-maven-plugin] Add an <instructions> section

### ISSUE THREAD

**Issue by bosschaert** [bndtools/bnd#2769]
The maven-bundle-plugin allows projects to customize bnd behaviour via an <instructions> section where configuration can be specified as XML which is passed to bnd for processing.

It would be nice if the bnd-maven-plugin would support a similar mechanism to specify bnd instructions to make it easier for people to migrate between the maven-bundle-plugin and the bnd-maven plugin.

As this now provides an additional mechanism to specify configuration (the others being a separate bnd.bnd file or a <bnd> section) only one mechanism should be used. 

In order to specify bnd keys that start with a dash, like `-sources`, the keys need to transformed a little as in XML a key is not allowed to start with a `-`. We can support these cases by allowing the keys to start with an underscore `_` and converting these into a dash. This is also what the maven-bundle-plugin does.

If a developer specifies more than one mechanism of configuring the plugin only one will be used and a warning should be emitted to indicate dubious plugin configuration.

**Comment by bjhargrave** [comment]
Closing as we decided not to make this change
