### ISSUE TITLE
Empty manifest produced when Maven plugin configuration is inherited

### ISSUE THREAD

**Issue by io7m** [bndtools/bnd#2778]
Hello!

It seems that Bndtools produces an empty manifest when loading a Maven-based project with an invocation of the `bnd-maven-plugin` that uses a configuration inherited from a parent POM.

Here's a repro case:

https://github.com/io7m/osgitest3-20180902

When using `mvn clean package`, the resulting bundle manifest is quite extensive. However, when deleting the bundle and using "build" in Eclipse, the bundle manifest is almost empty:

```
  Manifest-Version: 1.0
  Created-By: Apache Maven
  Built-By: rm
  Build-Jdk: 10.0.2
```

My understanding is that the Eclipse plugin should pick up the configuration from the `bnd-maven-plugin` execution and give me a manifest identical to that produced by running Maven.

Versions:

```
$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)

Eclipse:
Version: Photon Release (4.8.0)
Build id: 20180619-1200

Bndtools	4.0.0.REL-20180511-182614-g64633ee	bndtools.main.feature.feature.group	Bndtools
Bndtools m2e	4.0.0.REL-20180511-182614-g64633ee	bndtools.m2e.feature.feature.group	Bndtools
```

**Comment by rotty3000** [comment]
I can't build the sample project. I get:

```
]$ mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.io7m.osgitest3:com.io7m.osgitest3:jar:0.0.1
[WARNING] 'parent.relativePath' of POM com.io7m.osgitest3:com.io7m.osgitest3:0.0.1 (/home/rotty/tmp/osgitest3-20180902/pom.xml) points at biz.aQute.bnd:biz.aQute.bnd.gradle instead of com.io7m.primogenitor:com.io7m.primogenitor, please verify your project structure @ line 9, column 11
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------< com.io7m.osgitest3:com.io7m.osgitest3 >----------------
[INFO] Building com.io7m.osgitest3 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.apache.maven.plugins:maven-javadoc-plugin:jar:3.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.505 s
[INFO] Finished at: 2019-02-03T10:24:45-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-javadoc-plugin:3.0.0 or one of its dependencies could not be resolved: Failure to find org.apache.maven.plugins:maven-javadoc-plugin:jar:3.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

However, with closer review I believe the issue you are experiencing is already fixed in bndtools.m2e HEAD (which you can install from https://bndtools.jfrog.io/bndtools/update).

The issue was that multiple executions of the jar task were not well supported. Recently this issue was resolved.

Can you confirm? While attempting this, you may want to also set your maven plugin versions to the latest snapshots using this:
```
	<pluginRepositories>
		<pluginRepository>
			<id>bnd-snapshots</id>
			<url>https://bndtools.jfrog.io/bndtools/libs-snapshot/</url>
			<layout>default</layout>
			<releases>
				<enabled>false</enabled>
			</releases>
		</pluginRepository>
	</pluginRepositories>
```
and then setting all the bnd plugin versions to `4.2.0-SNAPSHOT`.

**Comment by io7m** [comment]
> Please retest your sample with a blank local repo to make sure others can build it using:
mvn -Dmaven.repo.local=~/tmp/empty clean install

I'm unable to reproduce the `org.apache.maven.plugins:maven-javadoc-plugin:jar:3.0.0` failure. Was that a temporary Maven Central issue? Could you try again with the `-U` flag? That artifact is definitely present on Central.

I should be able to try out the latest Bndtools at some point in the next week.

**Comment by rotty3000** [comment]
Hmm, just adding the default execution configuration to the `bnd-maven-plugin` solved the issue in my clone:
```
<plugin>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>bnd-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>bnd-process</id>
			<goals>
				<goal>bnd-process</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**Comment by rotty3000** [comment]
furthermore, I don't see why the parent pom has both a pluginManagement and a plugins/plugin configuration of bnd-maven-plugin. Use one or the other, but not both.

**Comment by io7m** [comment]
> Plugin cannot inherit from both <pluginManagement> AND an inherited <build><plugins>. The moment the local project creates a local configuration of the bnd-maven-plugin it's parent becomes the configuration set in pluginManagement, which has no execution.

I'm not entirely convinced of this. Are you saying that _no_ plugin can inherit from both, or that the `bnd-maven-plugin` can't? Because I feel like it would have to be latter; this separation of `pluginManagement` and `build/plugins` is something I see very commonly, and use personally with no ill-effects with any other plugin across almost a hundred projects.

The `pluginManagement` section specifies "if you were to add a plugin execution in a  project that inherited from this `pom.xml`, this is the configuration it would get", whilst adding an execution in `build/plugins` specifies "if you inherit from this `pom.xml`, you'll get at least this plugin execution". They say different things, so it's common to separate the two, and it's purely coincidental that I do happen to use both here.

I can't add the execution to the `pluginManagement` section, because that would then mean that I'd have to add a plugin execution in the pom files of each inheriting project, but I can probably move the configuration data to the execution in `build/plugins` and use the `pluginManagement` section purely to control the version number of the plugin.

**Comment by rotty3000** [comment]
Bndtools or bnd have no control over this. If anything this is an m2e bug. bndtools.m2e simply invokes the executions found in the pom. The inheritance of which is completely handled in m2e and maven.

**Comment by rotty3000** [comment]
> I can't add the execution to the pluginManagement section, because that would then mean that I'd have to add a plugin execution in the pom files of each inheriting project

On what is this based? I've never seen the need to do that. In fact if you look at enroute it's configured exactly this way https://github.com/osgi/osgi.enroute/tree/master/examples

the parent pom

**Comment by rotty3000** [comment]
if you want to reduce the configuration to just the parent pom completely:

a) add the execution to the plugin config in `<pluginManagement>`
b) add the global `plugins/plugin` config which has zero config and just links it as default
c) don't refer to the bnd plugin directly in any sub projects since they automatically inherit it already from the, otherwise just use the minimal reference.

**Comment by io7m** [comment]
> > I can't add the execution to the pluginManagement section, because that would then mean that I'd have to add a plugin execution in the pom files of each inheriting project
> 
> On what is this based? I've never seen the need to do that. In fact if you look at enroute it's configured exactly this way https://github.com/osgi/osgi.enroute/tree/master/examples
> 
> the parent pom

https://maven.apache.org/pom.html#Plugin_Management

> "this only configures plugins that are actually referenced within the plugins element in the children or in the current POM. The children have every right to override pluginManagement definitions."

What I meant was that I couldn't _only_ define it in the `pluginManagement` section, I would also have to have _some_ declaration in `build/plugins`. I could either put all of the configuration in `build/plugins`, or apparently I could move the execution to `pluginManagement` and use a minimal reference (that contains no configuration) in `build/plugins`, as you suggested.
