### ISSUE TITLE
Add Sources downloads artifact but does not attach source

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bnd#2786]
I am unable to use the _Add Sources_ action of the _Repositories_ view to attach sources. The vie shows artifacts from a `MavenBndRepository` that points to an intranet nexus server (see below).

I can see the files being downloaded into the local Maven cache (`.m2` directory), for example:
> jackson-datatype-jsr310-2.8.3-sources.jar
> jackson-datatype-jsr310-2.8.3-sources.jar.json

However, the source is not attached to the respective bundle. Since I am able to manually attach the source bundle, proves that it has the right format. The `jackson-datatype-jsr310` artifact here is taken as an example, other randomly chosen artifacts show the same behavior.

Repository plugin:
```
-plugin = \
	aQute.bnd.repository.maven.provider.MavenBndRepository; \
		snapshotUrl=http://intranet-nexus-host:8080/nexus/...; \
		releaseUrl=http://intranet-nexus-host:8080/nexus/... \
		index=${.}/nexus.maven; \
		name="Maven Dependencies"
```

**Comment by pkriens** [comment]
I've just verified that this works. However, it can take some time before it is effective and might require a refresh.

Closing for now
