### ISSUE TITLE
Run OSGi fails

### ISSUE THREAD

**Issue by db82407** [bndtools/bnd#2789]
I'm using bndtools-3.3.0.REL on Eclipse Neon with the bnd-export-maven-plugin.
I do not have a bnd/cnf workspace.

Run OSGi on my bndrun file usually works the first time, but then it fails with the error:

'Launching server.bndrun' has encountered a problem.
Launch configuration server.bndrun references non-existing project org.example.export.

There is no stack-trace in the Error log, just a repeat of the above text.

When this happens, I have found that navigating to 'Run configurations...' and deleting the automatically generated entry for 'server.bndrun' allows it to work once more.

However, I actually want to run this configuration using an alternate JRE, and that is currently impossible.
I get the above error whenever I try to run from the Run configurations ... dialogue, even before I have tried configuring an alternate JRE.

**Comment by bjhargrave** [comment]
Please try again on the latest 4.2 snapshot builds and reopen if the issue still occurs.
