### ISSUE TITLE
Enable parallel builds within the BndtoolsBuilder

### ISSUE THREAD

**Issue by ViToni** [bndtools/bnd#2801]
Currently the `BndtoolsBuilder` does not override the `getRule()` methods so it falls back to using the default provided by the `IncrementalProjectBuilder` which is the workspace (` ResourcesPlugin.getWorkspace().getRoot()`). Overriding it could enable more parallelism for the build.

See:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=531554

One approach could be to just reuse the approach used in the `JavaBuilder`:
https://github.com/eclipse/eclipse.jdt.core/blob/28455b57f164175de3b3c74e8ea0c076e28d97f9/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/JavaBuilder.java#L808

If parallelism is enabled for the `JavaBuilder` the `BndtoolsBuilder` would be automatically enabled, too.

**Comment by wborn** [comment]
It would certainly give a nice productivity boost and put all the CPU cores developers nowadays have to use if we can use parallel builds! Parallel Maven builds already save me and my team a lot of time on projects that don't use bnd.

**Comment by wborn** [comment]
I just read in the [bnd 4.3.0 release notes](https://github.com/bndtools/bnd/wiki/Changes-in-4.3.0#bnd-maven-plugins) that the Maven plugins are now thread safe.
It works well after some testing. :+1: So excuse me for mistaking this issue for something else. :-)

**Comment by ViToni** [comment]
Will be solved when #4575 is realized.
