### ISSUE TITLE
aQute.bnd.osgi.Jar doesn't handle symlinks to exploded jar

### ISSUE THREAD

**Issue by earcam** [bndtools/bnd#2825]
The constructor `Jar(String name, File dirOrFile, Pattern doNotCopy)` does not handle symlinks and subsequently fails.

Something like the following is required:

```
-               if (dirOrFile.isDirectory())
+               if (Files.isDirectory(dirOrFile.toPath()))

```

Apologies; I would have submitted a patch but am unable to build with ./gradlew (master or 4.1.0.REL)

**Comment by bjhargrave** [comment]
We can look at this. But I am more concerned you cannot build Bnd. Can you tell me more about that?

**Comment by earcam** [comment]
Hi @bjhargrave, 

While re-running steps to log here as reply, I got the output below - which hinted that importing the project into Eclipse had caused some problem (and I must have missed this in previous output).

Issued a `./gradlew clean` and then `./gradlew` - the build is currently in-progress without issue.

```
caspar@badger /opt/code/github/bnd $echo $JAVA_HOME 
/usr/lib/jvm/java-8-oracle
caspar@badger /opt/code/github/bnd $java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
caspar@badger /code/github/bnd $./gradlew 

> Task :biz.aQute.bndlib:jar FAILED
error  : The default package '.' is not permitted by the Import-Package syntax.
 This can be caused by compile errors in Eclipse because Eclipse creates
valid class files regardless of compile errors.
The following package(s) import from the default package [aQute.bnd.osgi]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':biz.aQute.bndlib:jar'.
> biz.aQute.bndlib has errors, one error was reported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
9 actionable tasks: 8 executed, 1 up-to-date
caspar@badger /code/github/bnd $git status 
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```
I'll attempt to switch this issue from a bug report to a tested PR or otherwise report back.

**Comment by bjhargrave** [comment]
You cannot have Eclipse building the project (Build Automatically) and gradle building the project. They will duel and the result is not good. If you have Eclipse open, then you must turn off Build Automatically _before_ you attempt to build with gradle.

**Comment by bjhargrave** [comment]
Also in JDK 11:

```
jshell> File barl = new File("/Users/hargrave/Downloads/barl")
barl ==> /Users/hargrave/Downloads/barl

jshell> Files.isSymbolicLink(barl.toPath()) && Files.isDirectory(barl.toPath()) && barl.isDirectory()
$20 ==> true
```

In JDK 8:

```
groovy> import java.nio.file.* 
groovy> File barl = new File("/Users/hargrave/Downloads/barl") 
groovy> Files.isSymbolicLink(barl.toPath()) && Files.isDirectory(barl.toPath()) && barl.isDirectory() 
 
Result: true
```
So File.isDirectory works correctly for me on JDK 8 and 11 on my mac.

**Comment by earcam** [comment]
@bjhargrave apologies for spam - the issue I'm seeing is a bit obscure and buried in a Maven build.  I'll close this as not-an-issue and properly investigate
