### ISSUE TITLE
Resolve repository contents from eclipse run configurations

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#2833]
When setting up Run Configurations in Eclipse and specifying Program or VM arguments it may be useful to refer to some bundle from a repository. This isn't possible, I think, via any of the current contributions (that is, to the `Variables...` button menu).

As a use-case example: when running normal (non-OSGi) JUnit tests through the IDE a user may wish to set a -javaagent for jmockit, but there is no way to resolve the location of the jmockit.jar which is on the build path if it is provided via a Bnd repository.

I propose to add a IDynamicVariableResolver implementation for a ${repo_loc:symbolicname}, which would work the same as the ${repo} macro in Bnd. Should be simple enough, will submit a PR.

**Comment by pkriens** [comment]
Why do you need to create an Eclipse run configuration? What are you missing in a bndrun file? The goal is that you should need anything specific Eclipse, all functionality should be reachable from the bndrun file.

**Comment by eliasvasylenko** [comment]
Because this is how normal unit tests (i.e not integration tests requiring an OSGi framework) are run, is it not? Via the normal JUnit launcher in eclipse? (Or via the normal test tasks in Grade/Maven/etc.)
