### ISSUE TITLE
aQute.bnd.annotation.Version gone?

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#2836]
The old package version annotation aQute.bnd.annotation.Version seems to no longer work?

**Comment by bjhargrave** [comment]
Support for the old Bnd annotations was deprecated in 3.2 and removed in 4.0. See https://github.com/bndtools/bnd/issues/2182 and https://github.com/bndtools/bnd/pull/2192.

**Comment by pkriens** [comment]
I am giving this quest up ...
