### ISSUE TITLE
Performance issue in Bndtools 4.1.0

### ISSUE THREAD

**Issue by unautre** [bndtools/bnd#2848]
Hello,

I've recently updated to Bndtools 4.1.0 with Eclipse Oxygen, and experienced hiccups of the whole Eclipse IDE almost everytime I save a file (I'm using the "Build automatically" option), lasting for a good ten seconds everytime.
If I thread dump the eclipse instance at that moment, I often find the main thread stuck in a Thread.sleep call: https://github.com/bndtools/bnd/blob/2ae86fb92fd2a52ee257498c56f8b53daff8ff6a/bndtools.core/src/bndtools/model/repo/RepositoryTreeContentProvider.java#L334
The complete thread dump is here: https://gist.github.com/unautre/a5cca2baf2b83a2069b1ca1343d9f780

Could it be that making the main thread sleep for 100ms is a but much, especially if called multiple times, and thus is slowing down the whole IDE ?

**Comment by bjhargrave** [comment]
You should also look at the Eclipse "Progress View" to see what operation is running during the pause you see.

I will note that all the Bnd devs use Eclipse/Bndtools with many large projects and, other than the fact that some projects do take some time to build due to the nature of their size, overall the responsiveness of Bndtools is quite good.

**Comment by unautre** [comment]
Thanks for answering.
Actually, I can't even check the "Progress View" of Eclipse because the whole GUI is frozen.

The only thing that I know could slow the build process of my project, is a ${system} macro used to set the Bundle Version, that calls git ; from my previous experiences, that could add additional time to the build process, but without ever freezing the whole GUI.
I'll keep looking, though.

**Comment by bjhargrave** [comment]
Do you have any more information to help up understand this problem better?

**Comment by bjhargrave** [comment]
Closing. If you can provide more information which could help us understand the issue, then open a new issue with the information. Thanks.
