### ISSUE TITLE
Templates not working

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2862]
I have two Eclipse IDE setups of the same repository.

One of them uses `Bndtools 4.2.0.DEV-20190111-224354-g252a672`
The other one uses `Bndtools 4.2.0.DEV-20181202-184155-g8260851`

Our custom templates ain't working in the newer version of Bndtools setup whereas it does work perfectly in the other version.

**Comment by bjhargrave** [comment]
In between those builds, the bndtools repo was merged into the bnd repo so there is now a single build.

**Comment by bjhargrave** [comment]
We also updated the Eclipse dependency for Bndtools to 4.7 which may also be a cause.

I see that when I go to validate a template in the Bndtools preferences, it always says it validates to origin/master branch rather than the specified branch

**Comment by amitjoy** [comment]
I tested with a fresh installation and a new instance of our own repo. Template functionality still doesn't work. Not sure where the problem lies.

**Comment by bjhargrave** [comment]
@amitjoy Can you investigate/debug this?

**Comment by amitjoy** [comment]
It started working after I installed the new version of bndtools.
