### ISSUE TITLE
[Feature Request] Proper error notification due to problems with the connection settings

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2881]
`Action:`
The `connection-settings.xml` cannot be read (due to XML problem) or the configured credentials cannot be used to connect to the configured URLs (e.g user credential is invalid)

`Current Behaviour:`
The repositories disappear (empty `Repositories` view in Eclipse)

`Expected Behaviour:`
Error Notification in Eclipse about the problem

**Comment by pkriens** [comment]
Duplicate #3154
