### ISSUE TITLE
bnd 4.2.0-SNAPSHOT fails to evaluate lsa/lsr macro

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#2915]
I have in my project a jar file that is to be included in a bundle. In order to automatically adapt to version changes of the jar, I include it with a macro:
```
-buildpath: \
	${replace;${lsr;jar};^(.*)$;jar/$1\\;version=file}
```
(The complete file can be found [here](https://github.com/mnlipp/de.mnl.osgi/blob/master/de.mnl.osgi.bnd.repository/bnd.bnd).) This worked fine until I updated the bnd workspace in Eclipse Bndtools yesterday. (Strange enough, it has modified the `gradle.properties` to refer to `4.2.0-SNAPSHOT` ; I think default settings shouldn't make your project using snapshot versions.) With this snapshot version, the macro is obviously no longer evaluated properly because the build fails with all classes from the jar no longer being found.

Replacing the macro with the "to be evaluated" value makes it work again, as does going back to bnd-gradle 4.1.0.

I usually don't report issues against snapshot versions. This is only because the workspace upgrade introduced the reference, which I only found out about because of this problem. So feel free to close this issue as being "temporary". But on the other hand side, macro evaluation is a long-standing feature and it seems a bit strange that we get a regression issue here.

**Comment by bjhargrave** [comment]
> Strange enough, it has modified the `gradle.properties` to refer to `4.2.0-SNAPSHOT` ; I think default settings shouldn't make your project using snapshot versions.

There is nothing I know of in Bnd/Bndtools which would modify the gradle.properties file in a workspace. I use Bndtools builds all the time with workspaces and the workspace's gradle.properties file are never altered.

I have recently made significant updates to the macro processing code, so I am interested in this report and will investigate. Thanks,

**Comment by mnlipp** [comment]
> There is nothing I know of in Bnd/Bndtools which would modify the gradle.properties file in a workspace. I use Bndtools builds all the time with workspaces and the workspace's gradle.properties file are never altered.
 
Sorry, but if you have a bnd workspace open and you choose (in Eclipse) File/New/New Bnd OSGi Workspace, a dialog pops up with the (only) option "Update in current Bnd Workspace". And if you confirm, it basically (I didn't check for details) overwrites (after another confirmation) all the files that are in the workspace template. Including gradle.properties!

**Comment by bjhargrave** [comment]
> Sorry, but if you have a bnd workspace open and you choose (in Eclipse) File/New/New Bnd OSGi Workspace, a dialog pops up with the (only) option "Update in current Bnd Workspace". And if you confirm, it basically (I didn't check for details) overwrites (after another confirmation) all the files that are in the workspace template. Including gradle.properties!

OK, I have never used that. But you did ask to update your workspace... :-)
