### ISSUE TITLE
AntGlob fails on this case

### ISSUE THREAD

**Issue by StinkyLord123** [bndtools/bnd#2917]
Glob glob = new AntGlob("**/examples/**/**/*package.json");
PathMatcher matcher = fs.getPathMatcher("glob:" + glob);
matcher.matches(Paths.get("C:\Users\PhilipAbed\Downloads\test\GithubProjects\testfoldershuoldbedeleted\typescript-project-sample-master\node_modules\readdirp\examples\package.json"));
on ant pattern it finds it.. and returns true.
when i convert this to glob it gives false.

**Comment by bjhargrave** [comment]
A couple of things I see wrong here:

1. AntGlob.toString(), which is called here when you do `"glob:" + glob` simply returns the string passed to the AntGlob constructor. So, in your code snippet, you are not converting AntGlob to anything. You are just returning the constructor argument.
2. There is a double slash between `examples` and `**`.
3. The expression starts with slash which means it will match only paths which start with `/examples` not which have `/examples` somewhere in the path.

In debugging with the expression `/examples//**/*package.json`, I see that PathMatcher uses the pattern `^/examples//.*/[^/]*package\.json$` (I am not using Windows, so forward slashed for me.)

If you want to match the example file name, use the expression `**/examples/**/*package.json`. In debugging with this expression, I see that PathMatcher uses the patterm `^.*/examples/.*/[^/]*package\.json$` which should match your example file.

**Comment by StinkyLord123** [comment]
yes thanx , but its still what i wanted,
this worked like a charm

for (String include : bomPatterns){
    Glob glob = new AntGlob(include);
    PathMatcher matcher = fs.getPathMatcher("regex:" + glob.pattern());
    listOfIncludePatterns.add(matcher);
}
