### ISSUE TITLE
Export-Package Header and @Export don't work together

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2926]
I have an API bundle which comprises `Export-Package` header and some of the packages are using `@Export` annotation in their `package-info.java`. The packages with `@Export` ain't getting exported at all.

**Comment by bjhargrave** [comment]
If you use `Private-Package` to add a package to a bundle, then `@Export` in that package is not processed. If you want `@Export` to be processed, use the `-includepackage` instruction.

See https://github.com/bndtools/bnd/commit/a596d811bb26fabd5750d4b788b70bedf8673960

**Comment by amitjoy** [comment]
I haven't added the `@Export` annotated package to `Private-Package` at all.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by timothyjward** [comment]
@amitjoy - what build layout and version of bnd are you using? Is it a bnd workspace, standalone Gradle workspace, Maven?

Also, have you overridden the contents of the bundle in some way in your bnd configuration?

**Comment by amitjoy** [comment]
@bjhargrave will provide a small project workspace to replicate this.

@timothyjward I am using the recent version of bndtools -   4.2.0.DEV-20190205-162449-gc163e03.

Concerning this issue, I haven't overridden any of the contents in the bundle that encountered this problem.

The project is actually a single base API for the complete workspace and hence it exports lots of APIs. Previously we exported the packages the usual way - `Export-Package` header but recently I configured the workspace to use R7 APIs and hence wanted to use the new annotations. I just annotated a recently introduced package with `@Export` but it couldn't get processed since there already exists the` Export-Package` header. After I removed the `Export-Package` header, it did work.

**Comment by bjhargrave** [comment]
If you want to use `@Export` processing for some packages, I would use `-includepackage` to add those packages to the bundle rather than adding them to the bundle with `Export-Package` since `Export-Package` has a dual purpose: adding packages to the bundle and exporting those packages from the bundle.
