### ISSUE TITLE
Emit error in case DS component property and properties are mixed up

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#2927]
Very often developers mix up the elements `properties` (https://osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/component/annotations/Component.html#properties--) and `property` (https://osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/component/annotations/Component.html#property--). It would be nice if bnd would check that the `properties` attribute has a valid value (i.e. an existing resource in the bundle containing a properties file).

One example where this was mixed up can be found in https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1744. It would be nice to catch those errors at build time.

**Comment by bjhargrave** [comment]
Well, I don't think it would be an error. The properties resource could be in a fragment which is not present at build time. So I think a warning is more appropriate.

**Comment by kwin** [comment]
Maybe you can check if one entry within `properties` has the format `<name>=<value>`. I think in that case it is safe to assume a mistake and emit an error? WDYT?

**Comment by bjhargrave** [comment]
> Maybe you can check if one entry within `properties` has the format `<name>=<value>`. I think in that case it is safe to assume a mistake and emit an error? WDYT?

I think it is simpler to just check the entries are in the jar. `=` can be a legitimate character in a file name.

**Comment by bjhargrave** [comment]
> emit an error

Note: A build can convert this warning into an error using `-fixupmessages` if the build wants this class of problem to be an error.

**Comment by kwin** [comment]
@bjhargrave Thanks a lot for the quick fix!
