### ISSUE TITLE
Support sources jar in MavenRepositories

### ISSUE THREAD

**Issue by JochenHiller** [bndtools/bnd#2934]
There is support in MavenRepository to add a JAR file from classifier `sources` which contains the Java sources of a bundle, which will be linked as Java Sources of the bundle. 

For example this does work well with central.maven:
```
# List repository contents using GAV coordinates
org.jline:jline:3.9.0
org.jline:jline:jar:sources:3.9.0
```
You will see in repository view the bundles `org.jline` and `org.jline.source`, and the Java sources of the bundle jar are correctly linked to the sources jar.

But: this does NOT work for a bundle like Felix Gogo command:
```
org.apache.felix:org.apache.felix.gogo.command:1.1.0
org.apache.felix:org.apache.felix.gogo.command:jar:sources:1.1.0
```

Why does it not work?  The jline sources jar file contains in Manifest a `Bundle-SymbolicName: org.jline.source` header, whereas that is missing in gogo jar file.
I did not check in details, but I fear that this is the case for a huge number of source jar files.

Maybe you can consider to add an option to MavenRepository to automatically scan for a given GAV if there is an artifact for sources classifier as well. If so, add automatically the BSN to the jar file when not specified.

**Comment by pkriens** [comment]
Seems to work now out of the box when sources are available on the server

**Comment by JochenHiller** [comment]
Great thanks for supporting that feature
