### ISSUE TITLE
Error: Could not find or load main class aQute.launcher.Launcher

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2947]
All of a sudden, I am encountering problems with all my bndrun configurations. They cannot be run anymore. I am executing them with `Bnd OSGi Run Launcher`.

I am using the current Bndtools version -   `Bndtools	4.2.0.DEV-20190209-222004-gaa3a67f`

```
-runsystempackages.sun       :  sun.misc, sun.reflect
-runfw                       :  org.apache.felix.framework
-runee                       :  JavaSE-1.8
-runstorage                  :  target/sample
-runrequires: \
	bnd.identity;id='org.apache.felix.gogo.command',\
	bnd.identity;id='org.apache.felix.gogo.runtime'
-runbundles: \
	org.apache.felix.gogo.command;version='[1.1.0,1.1.1)',\
	org.apache.felix.gogo.runtime;version='[1.1.2,1.1.3)',\
	org.apache.felix.gogo.shell;version='[1.1.2,1.1.3)'
```

On the other hand, it does execute if I package the configuration to a launchable JAR file. But it doesn't work directly in Eclipse anymore.

**Comment by amitjoy** [comment]
I suspected it to be a problem in Bndtools new version but I have tested it with the release version (4.1) and the result is still the same.

**Comment by amitjoy** [comment]
Found some reference: https://stackoverflow.com/questions/27457710/could-not-find-main-class-while-it-does-exist

but doesn't apply to my problem.

**Comment by rotty3000** [comment]
What kind of project is the bndrun hosted in? A small project to reproduce would be helpful.

**Comment by rotty3000** [comment]
What kind of project is the bndrun hosted in? A small project to reproduce would be helpful.

**Comment by pkriens** [comment]
Any output? Are you using the -runpath in build.bnd?

You really should provide a bit more detail ...

**Comment by rotty3000** [comment]
I have a suspicion... 

Is this a maven project using bnd maven plugins `< 4.2.0-SNAPSHOT` while using `bndtools.m2e = 4.2.0-SNAPSHOT`?

If so, I think I reproduced the issue. Taking a look at that case.

**Comment by amitjoy** [comment]
This is a plain bnd project - not a maven one. I am not using any - runpath. The bndrun comprises the exact configuration as aforementioned.

**Comment by rotty3000** [comment]
We'd at least need a stacktrace from the eclipse log.

**Comment by amitjoy** [comment]
Will send you in few minutes.

**Comment by pkriens** [comment]
but the bndrun inherits from build.bnd ...

**Comment by rotty3000** [comment]
Ok, since this has nothing to do with m2e I'll defer to the workspace folks. Although this issue did make me check a scenario I had overlooked but is not fixed :) https://github.com/bndtools/bnd/pull/2948 so thanks for that!

**Comment by amitjoy** [comment]
@pkriens I don't have any `-runpath` set at all in my workspace.

**Comment by amitjoy** [comment]
@pkriens @rotty3000 I have created a sample workspace to replicate this issue - Here is the link - https://github.com/amitjoy/bnd-2947-issue

**Comment by rotty3000** [comment]
I only made the following change, just so I would see trace info:
```
@@ -6,4 +6,5 @@
 	bnd.identity;id='org.apache.felix.gogo.runtime'
 -runbundles: \
 	org.apache.felix.gogo.command;version='[1.0.2,1.0.3)',\
-	org.apache.felix.gogo.runtime;version='[1.0.10,1.0.11)'
\ No newline at end of file
+	org.apache.felix.gogo.runtime;version='[1.0.10,1.0.11)'
+-runtrace: true
\ No newline at end of file
```
and everything worked. Of course I'm using a bndtools built from current HEAD of master.

**Comment by rotty3000** [comment]
On the other hand, when I attempt the run from the context menu of the project as opposed to the bndrun file, then I see the `No OSGi framework has been added to the run path.` error, but I expect this is since it's assuming the `bnd.bnd` file is also configured as a run, which it's not.

**Comment by rotty3000** [comment]
as support for this, I appended `-include: launch.bndrun` to the `bnd.bnd` file and launching from the context of the project worked as expected.

What may be happening @amitjoy is that you probably had this working before by virtue that your `cnf/build.bnd` was also configured as a run which would have made every bnd file in the workspace projects launch-able.

**Comment by amitjoy** [comment]
I am using the context menu after right-clicking on the `launcher.bndrun` - not the whole project.

**Comment by amitjoy** [comment]
Any of the existing configurations in `cnf/build.bnd` actually didn't make them launchable. It should be something else. I also tried to include the launcher bndrun configurations to the `bnd.bnd` and used the project context menu to run it as `Bnd OSGi Run Launcher`, but it also didn't work for me.

**Comment by amitjoy** [comment]
I have another installation of Eclipse IDE that uses `4.2.0.DEV-20190207-165645-g574c698` and the following configuration works perfectly there:

```
-runrequires: \
	bnd.identity;id='org.apache.felix.gogo.command',\
	bnd.identity;id='org.apache.felix.gogo.runtime'
-runbundles: \
	org.apache.felix.gogo.command;version='[0.16.0,0.16.1)',\
	org.apache.felix.gogo.runtime;version='[0.16.2,0.16.3)'
```

**Comment by pkriens** [comment]
This works for me ... you could try to delete your cnf/cache directory. Maybe the launcher in there is messed up?

**Comment by amitjoy** [comment]
Yesterday, I suspected it too and it resulted in the following:

<img width="962" alt="bildschirmfoto 2019-02-11 um 10 19 54" src="https://user-images.githubusercontent.com/13380182/52554304-b261e980-2de6-11e9-915f-7729bfa96a28.png">

`Continue launching anyway?` didn't also help. I refreshed all my repositories and the `cache` folder got recreated but it didn't work thereafter.

**Comment by pkriens** [comment]
Did you restart Eclipse? Look at cnf/cache/4.2.0/biz.aQute.launcher. It sounds like that file is messed up. If the directory is not there, bnd refreshes it at startup.

**Comment by pkriens** [comment]
Can you run it from the command line? 

       bnd launch.bndrun

Did you add the -runtrace=true?

**Comment by amitjoy** [comment]
It works perfectly from the command line.

**Comment by pkriens** [comment]
I've confirmed this on Eclipse 2019-03 & latest bndtools. An older bndtools from a few days ago is ok.

**Comment by bjhargrave** [comment]
So we can close this now with @pkriens fix?

**Comment by pkriens** [comment]
I wanted to wait for feedback

**Comment by bjhargrave** [comment]
> I wanted to wait for feedback

Right. That is why I was asking for the feedback :-)

**Comment by amitjoy** [comment]
The fix works perfectly
