### ISSUE TITLE
Improve JUnit 4 support

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#2958]
As background, the way that JUnit 4 works: If one of the conditions that you are testing for doesn't pass, then this is considered a test failure; otherwise if there was an unexpected error while running the test it should be considered a test error. Or, in other words, errors in the code-under-test are considered to be "test failures", and errors in the test itself are considered "test errors". Most IDEs/CLIs that drive JUnit distinguish between the two - eg, in Eclipse's JUnit IDE, failures are displayed blue while errors are displayed red.

I noticed that when running OSGi JUnit tests in BndTools, test failures are incorrectly reported as test errors.

When I dug deeper, I noticed that this is because of the way that JUnit 4 support was added - `biz.aQute.junit` uses the JUnit 3 framework and shoehorns the JUnit 4 tests into it using the `JUnit4TestAdapter`. Because of the way the JUnit 3 framework worked, only assertions of type `junit.framework.AssertionFailedError` or subclasses are reported as failures - any other exception is reported as an error. This includes exceptions that are subclasses of `AssertionError` (which is the class that all of the modern assertion frameworks derive from). JUnit 4, on the other hand, reports anything that is a subclass of `AssertionError`, so the other assertion frameworks work.

I should possibly be able to look at this in conjunction with #2168.

**Comment by bjhargrave** [comment]
As you look into this, make sure it continues to support projects with mixed test case types. We have plenty of projects which include a mix of JUnit3 and Junit4 test classes. When JUnit5 support is added, we will also want to support JUnit3/4/5 mixed test class projects.

**Comment by kriegfrj** [comment]
Naturally!

On the topic, are there regression tests for `biz.aQute.junit` and/or `biz.aQute.tester` anywhere? I haven't been able to find I think they need to be in-place before I start gutting the existing code so I can be confident I haven't broken anything. I'm happy to write some if necessary, but didn't want to re-invent the wheel.

**Comment by bjhargrave** [comment]
I don't think there are any tests that specifically test them. They are sort of indirectly tested by some of the gradle plugin test cases which test the `TestOSGi` task type in a gradle runtime environment.

**Comment by eximius313** [comment]
Why not move directly to JUnit5?

**Comment by bjhargrave** [comment]
> Why not move directly to JUnit5?

Because people have lots of existing JUnit3 and JUnit4 test cases which should be well supported.

**Comment by kriegfrj** [comment]
Hi @eximius313,
> Why not move directly to JUnit5?

As BJ noted, many tests are still out there using JUnit 3 & 4. However, given that JUnit 5 has backward compatibility, the solution to this may simply turn out to be that I add support for JUnit 5 and get better JUnit 4 support for free. Which is why I said I'd look at #2168 at the same time.

**Comment by eximius313** [comment]
awesome @kriegfrj !
