### ISSUE TITLE
Add Bndtools Project Nature is not working

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#2961]
When I create Bnd OSGi Project in Eclipse:
![1](https://user-images.githubusercontent.com/5578017/52632769-bb27ed80-2ec2-11e9-855c-ee160451b9c6.png)

it immediatelly shows it in Repositories view and enables all bnd features:
![2](https://user-images.githubusercontent.com/5578017/52632490-042b7200-2ec2-11e9-9b32-6e16c0cb241a.png)

But when I create Java project:
![3](https://user-images.githubusercontent.com/5578017/52632778-c418bf00-2ec2-11e9-850d-d6ce54913a96.png)

and enable Bndtools Project Nature:
![4](https://user-images.githubusercontent.com/5578017/52632527-1e655000-2ec2-11e9-8069-f89bf5c69a4f.png)

Nothing is shown in Repositories view, and what is worse - importing/exporting packages have zero impact on a project:
![5](https://user-images.githubusercontent.com/5578017/52632902-19ed6700-2ec3-11e9-95d5-299c5b83beb5.png)

BUT, when I add another Bnd OSGi project:
![6](https://user-images.githubusercontent.com/5578017/52632794-ce3abd80-2ec2-11e9-9cf6-5088bf39b813.png)

everything magically start to work:
![7](https://user-images.githubusercontent.com/5578017/52632914-207bde80-2ec3-11e9-9cac-e99b9522c2da.png)

Probably after adding project nature something is not rebuilding the Bnd workspace...

This is extremely confusing for new users, because I spent hour trying to figure out why my project is not working.

**Comment by eximius313** [comment]
Bug is still there. 
Reproduce steps in description.
What additional information do you need?

**Comment by gamerson** [comment]
hey @eximius313  This bug would be a super easy one for you to try to send a PR.  The "add bndtools nature" is a very straight forward eclipse action, and the code is not hard to understand.  If you open the Bndtools repo as a bndtools workspace, there are pre-configured "bndruns" per OS that you can use to launch a "test" eclipse workbench.  Look in the bndtools.core/*.bndrun.  Find your OS and right-click and do "Run as Bnd OSGi Run Launcher..."  

Here is the class you want to look at modifying: https://github.com/bndtools/bnd/blob/master/bndtools.core/src/bndtools/nature/ToggleNatureAction.java

Feel free to send an email to bndtools-user mailing list with additional questions: https://groups.google.com/group/bndtools-users

Good luck!
