### ISSUE TITLE
Bnd workspace is not working for Gradle multiproject 

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#2962]
When I have gradle project:
```
Project
 \client
    \client.gradle
 \server
    \server.gradle
 \settings.gradle
 \build.gradle
```
where `settings.gradle` is:
```
rootProject.name = 'Project'

include 'client'
include 'server'

rootProject.children.each { final project ->
    project.buildFileName = project.name + '.gradle'
    assert project.buildFile.isFile()
}
```

Then even if I add Bndtools project nature to subprojects - nothing happens. Project is completly ignored by Bndtools

**Comment by bjhargrave** [comment]
I do not understand what you are getting at here. Bndtools nature is for Bnd workspace module build where all projects are peer folders in the workspace folder and there is a cnf project holding workspace information such as build.bnd.

If you want a custom gradle build, then Bndtools will be of limited to no use in building those projects. Gradle Buildship would be something to look at. You can still use the Bnd Gradle plugins for non-workspace model builds to build the bundles in your projects.

**Comment by eximius313** [comment]
I see, that you support gradle in bndtools workspace (https://github.com/bndtools/bnd/blob/4.1.0.REL/biz.aQute.bnd.gradle/README.md#using-bnd-gradle-plugins-for-workspace-builds - approach 2)

I want to use Bndtools for development, because your tool makes it much easier, but use Gradle for deployment in CI.

**Comment by bjhargrave** [comment]
You can use Bndtools with gradle for Bnd workspace model build. This project is such a build. But you must conform to the directory structure for Bnd workspace model builds which is a flat structure. All projects are directories in the workspace directory. Projects may not be nested in other projects.

**Comment by pkriens** [comment]
This works perfectly if you start in Bndtools and create a new workspace with File/New/Bndtools workspace. This sets up by default a workspace completely ready for Gradle. Just go to the command line and switch to the workspace directory and type ./gradlew

That's all.

You might want to look at 

	https://v2archive.enroute.osgi.org/book/150-tutorials.html

These tutorials contain a wealth of information to get started with OSGi and understand some of the ideas behind OSGi. They all assume the incredible user friendly bndtools workspace (They need to be moved to the bndtools site when I find time.)

Kind regards,

	Peter Kriens

**Comment by eximius313** [comment]
@bjhargrave 
> Projects may not be nested in other projects.

This is very important information. But why you're suggesting using
```
subprojects {
  if (plugins.hasPlugin('biz.aQute.bnd')) {
    // additional configuration for Bnd projects
  }
}
``` 
in the [documentation](https://github.com/bndtools/bnd/blob/4.1.0.REL/biz.aQute.bnd.gradle/README.md#using-bnd-gradle-plugins-for-workspace-builds)?

@pkriens I've read all of the documentation and tutorials on https://bndtools.org but I'll have a look at your link as well. Hopefully I find answer on how to use Gradle multiproject build with Bndtools workspace. But why @bjhargrave says that's not possible?

**Comment by bjhargrave** [comment]
> This is very important information. But why you're suggesting using
> 
> ```
> subprojects {
>   if (plugins.hasPlugin('biz.aQute.bnd')) {
>     // additional configuration for Bnd projects
>   }
> }
> ```

That is showing the configuration of the Bnd projects (which are mapped to a gradle project) in the workspace (which is mapped to the gradle root project).  

You still cannot have Bnd projects inside Bnd projects in the Bnd workspace model build.

**Comment by eximius313** [comment]
So having this simple project: [TestProject.zip](https://github.com/bndtools/bnd/files/2856357/TestProject.zip)

And importing it to eclipse as Gradle project: 
![image](https://user-images.githubusercontent.com/5578017/52645025-406dcb00-2ee0-11e9-9430-7d54b2e4d69c.png)

Is really supposed to create such structure:
![image](https://user-images.githubusercontent.com/5578017/52645122-6e530f80-2ee0-11e9-9290-ed309381ef9c.png)
?

**Comment by bjhargrave** [comment]
You use Import Gradle Project which is not part of Bndtools.

**Comment by eximius313** [comment]
But, this is only when I use:
```
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'biz.aQute.bnd:biz.aQute.bnd.gradle:4.1.0'
  }
}
apply plugin: 'biz.aQute.bnd.workspace'
```

When I dont use it - everything imports as expected. So this is *probably* something up to `biz.aQute.bnd.workspace`

**Comment by eximius313** [comment]
@bjhargrave, as I said in this https://github.com/bndtools/bnd/issues/2966#issuecomment-463366202 thanks to @pkriens settings we can correctly import Gradle projects with applied `biz.aQute.bnd.builder` using Buildship to Bndtools workspace, so it's not the issue with other tools.

One issue here is that when instead `biz.aQute.bnd.builder` plugin we use approach from [documentation](https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle#using-bnd-gradle-plugins-for-bnd-workspace-builds):
> The main approach is to edit settings.gradle as follows:

```
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'biz.aQute.bnd:biz.aQute.bnd.gradle:4.2.0'
  }
}
apply plugin: 'biz.aQute.bnd.workspace'
```
then we end up in weird situation:
![image](https://user-images.githubusercontent.com/5578017/52744216-59f43d00-2fdc-11e9-8f77-f957ebab0dfa.png)

The second isse is when we have [multiproject](https://www.petrikainulainen.net/programming/gradle/getting-started-with-gradle-creating-a-multi-project-build/) Gradle build with `biz.aQute.bnd.builder` plugin applied. In such situation subprojects are ignored by Bndtools workspace

**Comment by eximius313** [comment]
@pkriens I've prepared 3 examples that you can import to the workspace (with Gradle/Maven layout) using Buildship

1) Example 1 - single gradle project: working [gradle.singleproject.ok.zip](https://github.com/bndtools/bnd/files/2864081/gradle.singleproject.ok.zip)
* Import as gradle project
* Add Bndtools project nature
* Do the workaroud (https://github.com/bndtools/bnd/issues/2961)
* It's working!



2) Example 2 - gradle multiproject: not working [gradle.multiproject.zip](https://github.com/bndtools/bnd/files/2864085/gradle.multiproject.zip)
* Import as gradle project
* Add Bndtools project nature to `api` and `impl`
* Do the workaroud (https://github.com/bndtools/bnd/issues/2961)
* It's not working ;(



3) Example 3 - single gradle project with workspace gradle plugin taken from [documentation](https://github.com/bndtools/bnd/blob/4.1.0.REL/biz.aQute.bnd.gradle/README.md#using-bnd-gradle-plugins-for-workspace-builds): it's weird! [gradle.singleproject.workspace.zip](https://github.com/bndtools/bnd/files/2864093/gradle.singleproject.workspace.zip)
* Import as gradle project
* Look what was imported o_O

**Comment by pkriens** [comment]
We're not supporting all these different ways to model projects so I think we can close this issue?

**Comment by eximius313** [comment]
@pkriens, example 3 is taken straight from your documentation

**Comment by pkriens** [comment]
Well, i stopped reading after 2 ... and 3 is also not supported afaik because I do not see a cnf folder?

I am not sure what you want to achieve? There are many ways to get started with your workspace and there are infinite ways that do not automatically work. Clearly no time to support all those other ways.

**Comment by eximius313** [comment]
If it's about 3:
isn't `cnf` folder already in the workspace I'm importing the project into?

If it's about 2:
Multi project builds are very common, so they should not be ignored by serious build tool as yours.
I'm aware that you are not supporting this currently, so I understand that I shall close this bug and open new feature request asking for multiproject build support, is that correrct?

**Comment by pkriens** [comment]
You're perfectly right. However, as the minister of defence Rumsfeld said when he order the army to go into Iraq: "You go into war with the army you have, not with the army you would like to have".
You could of course make  PR that allows you to import these kind of builds. That would be highly appreciated. However, until that moment I cannot contribute anything since I do not have the incentive to work on this ...

**Comment by eximius313** [comment]
@pkriens I'll try, as soon as I have greater expertise in Bndtools. Thanks!

**Comment by eximius313** [comment]
https://github.com/bndtools/bnd/issues/2984
