### ISSUE TITLE
ClassNotFoundException when launching bndrun in Eclipse 2019-03 M2

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#2965]
When using the BND 4.1.0 release the try to launch a bnd run produces a ClassNotFoundException for  aQute.launcher.Launcher

This seems to be related to this thread: https://groups.google.com/forum/#!topic/bndtools-users/2pdAYDivfv0

**Comment by pkriens** [comment]
It is already fixed in 4.2 snapshot. The request for the bug was when you detect something similar.
