### ISSUE TITLE
provide a method to exclude some requirements from resolve

### ISSUE THREAD

**Issue by filippor** [bndtools/bnd#2980]
Provide a method to exclude same requirements during resolve.
I need this to use resolve for an application that use remote services.
I want to resolve all requirements excluding service provided from remote discovery

I suggest a keyword in bndrun file.

**Comment by bjhargrave** [comment]
Did you try `-runblacklist`? https://bnd.bndtools.org/instructions/runblacklist.html

**Comment by filippor** [comment]
Yes but with `-runblacklist` the resolve fail
I'd like to have  somthing like 
`-runprovided`  that exclude requrements from resolution and resolve all other

what I do now is resolve all requirements than manual remove the bundle I don't want
It's a manual operation that work for simple case like
https://github.com/filippor/osgi.enroute.examples.remoteservice/
but for complex bundle with transitive dependencies is not the ideal solution
