### ISSUE TITLE
[Feature] Improve continuous testing support in Bnd/Bndtools

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#2983]
See:
* this SO post: https://stackoverflow.com/questions/51624405/running-junit-tests-inside-a-running-osgi-application-with-ide-integration; and 
* this mailing list thread: https://groups.google.com/forum/#!topic/bndtools-users/W2haviOWBv0
...for background to this feature request.

Current state of Bnd/Bndtools is:
1. Bnd already has good support for continuous testing courtesy of biz.aQute.junit/tester, though it needs to be updated to the latest JUnit (see #2958 and #2168). Starting and stopping OSGi test bundles in a running environment using the OSGi console causes their tests to be automatically run.
2. `biz.aQute.junit` also provides good integration with the JUnit IDE in Eclipse, though arguably it ought to be part of BndTools rather than Bnd.
3. Bndtools already has good support for automatically reinstalling bundles in a launched application as they are updated in the workspace (the "Update bundles during runtime" option). This is a really neat feature and speeds up the development cycle as the bundles are automatically re-deployed almost as soon as you have finished editing them.

What seems to be missing is the combination of the above three features. What I would like is to be able to launch a test environment (including test bundles and the bundles-under-test). Every time that a bundle is edited in the IDE, the launcher would ideally reload the updated bundles, re-run the associated tests, and display the results in the Eclipse JUnit IDE.

Such a feature would greatly speed up test-driven development, in particular integration tests in OSGi environments that have a high startup cost.

**Comment by kriegfrj** [comment]
I have had a bit of a play with this and I think it is feasible.  However, I have hit a few snags which I would like some more seasoned advice on, as they touch on architectural issues. 

My prototype was as follows:

* I moved `registerLaunchPropertiesRegenerator()` and associated code from `bndtools.launch.OSGiRunLaunchDelegate` to `bndtools.launch.AbstractOSGiRunLaunchDelegate`.
* I added `FrameworkLaunchTabPiece` to `bndtools.launch.ui.internal.OSGiJUnitLaunchTab.createStack()`
* Launch the tests using the Bndtools OSGi JUnit launcher.

This was a good start, but hit a snag.

The snag is that `biz.aQute.tester` automatically adds itself to runbundles at the last possible minute in `ProjectTesterImpl.prepare()` at launch time. This is a nifty feature because it means that you don't have to manually add it, nor do you need to explicitly set up the bnd repository in your workspace as the bundle is supplied by the Bndtools wrapper code.

However, the problem is when the launch properties regenerator fires, it follows a different code path - calling `ProjectLauncher.update()`. This method calls `updateFromProject()` followed by `writePropertiesFile()`. However, `updateFromProject()` first clears `runbundles` before updating itself from the project (which removes biz.aQute.tester from runbundles), and so when the updated launch properties file is written and `synchronizeFiles()` is called it uninstalls the tester bundle.

A bit of a hacky workaround to this is if you explicitly add `biz.aQute.tester` to -runbundles in your launch file - then it gets found by `updateFromProject()`.

To fix this, I think I really need some way of hooking into `ProjectTesterImpl.update()`, so that the tester can insert itself after the call to `updateFromProject()` (otherwise its settings get lost), but before `writeProperties()` (which would be too late). Suggestions welcome - subclass `ProjectLauncherImpl`?

**Comment by pkriens** [comment]
I am not sure why just setting:

	-runpath: 		biz.aQute.tester
	-runproperty \
		tester.continuous=true, \
		tester.separatethread=true

Doesn't do the trick? Any save would then automatically run all test cases?

Kind regards,

	Peter Kriens

**Comment by kriegfrj** [comment]
@pkriens, thank you for your response.

I have tried many variations similar to yours (though admittedly not yet exactly as you suggested - I will try that when I get the chance). My understanding of why it doesn't work:

* biz.aQute.tester will automatically rerun tests *if* a bundle is restarted, but it doesn't automatically restart the bundle when it changes. If I restart then manually (eg, from the Equinox console), the tests will rerun automatically.
* The code that automatically triggers the framework to reload changed bundles is in OSGiLauncherDelegate (BndTools, not Bnd). This launcher does not prepare the JUnit IDE.
* The code that prepares the JUnit IDE is in OSGiJUnitLauncherDelegate, but this launcher does not watch for updated bundles.

If you know of a way to do this out of the box, I'm all ears.

**Comment by pkriens** [comment]
> On 15 Feb 2019, at 12:30, Fr Jeremy Krieg <notifications@github.com> wrote:
> @pkriens, thank you for your response.
> 
> I have tried many variations similar to yours (though admittedly not yet exactly as you suggested - I will try that when I get the chance). My understanding of why it doesn't work:
> 
> 	• biz.aQute.tester will automatically rerun tests if a bundle is restarted, but it doesn't automatically restart the bundle when it changes. If I restart then manually (eg, from the Equinox console), the tests will rerun automatically.
Well, the launcher in Eclipse will notice the build has changed, will update the properties, and then the launcher should update that bundle in the target framework. This must include a restart. If this doesn't work as advertised we have a bug. Though I have my doubts this would not work?
> 	• The code that automatically triggers the framework to reload changed bundles is in OSGiLauncherDelegate (BndTools, not Bnd). This launcher does not prepare the JUnit IDE.
Right, you won't get that IDE. But would that not be confusing? After every change you get the JUnit in your face?

This is trickier. 

I do not have to time to try it out but you could try the following.

	- Add `launch.setAttribute(ATTR_JUNIT_PORT, Integer.toString(20651))` in the AbstractOSGiLaunchDelegate (make sure the OSGiJunit can override it
	- Add the following -runproperty

		tester.port = 20651

This might work ... I recall vaguely when I wrote the JUnit handling that the JUnit bundle in Eclipse then opens the given port and shows all output on the console. I think it has a listener registered somewhere to get the launch configuration. It might be necessary to do a similar cleanup as in the OSGiJUnitLauncherDelegate, not sure.

> 	• The code that prepares the JUnit IDE is in OSGiJUnitLauncherDelegate, but this launcher does not watch for updated bundles.
This should work then

> If you know of a way to do this out of the box, I'm all ears.
Good luck :-)


Kind regards,

	Peter Kriens

**Comment by kriegfrj** [comment]
> Well, the launcher in Eclipse will notice the build has changed, will update the properties, and then the launcher should update that bundle in the target framework. This must include a restart. If this doesn't work as advertised we have a bug. Though I have my doubts this would not work?

Sorry, I realise that my previous response was not sufficiently nuanced.

You are correct, this works - *if* you use the plain `OSGiRunLaunchDelegate` ("Run As|Bnd OSGi Run Launcher") rather than `OSGiJUnitLaunchDelegate` ("Run As|Bnd OSGi JUnit Launcher"). But then of course you miss out on the JUnit IDE integration and the implicit adding of `biz.aQute.tester` to `-runbundles`. I'm trying to get both in some way, shape or form.

> Right, you won't get that IDE.

I really like the IDE when doing test-driven development, as you get nice features like being able to see at a glance which tests failed, click on failed tests and be taken straight to the place in the test source where the assertion failed, and graphical diff of expected and actual values when there is a failure.

> But would that not be confusing? After every change you get the JUnit in your face?

Possibly it would be confusing. But the JUnit tab is usually in a pane down the bottom out the way, so it doesn't get "in my face" so much. You could rearrange your workspace windows to minimise the distraction.

As an alternative, if you think that would be too distracting, I have considered a mechanism whereby you can manually trigger a re-run of a test in a running environment and have the results reported via the IDE (perhaps using the "re-run test" button in the IDE). This would probably be more complicated to implement, but I think it might be possible.

> This is trickier.

You're not exactly filling me with confidence here. 😉 

> I do not have to time to try it out but you could try the following.
>
>- Add `launch.setAttribute(ATTR_JUNIT_PORT, Integer.toString(20651))` in the AbstractOSGiLaunchDelegate (make sure the OSGiJunit can override it
>- Add the following
>   -runproperty tester.port = 20651
>This might work ... I recall vaguely when I wrote the JUnit handling that the JUnit bundle in Eclipse then opens the given port and shows all output on the console. I think it has a listener registered somewhere to get the launch configuration. It might be necessary to do a similar cleanup as in the OSGiJUnitLauncherDelegate, not sure.

I've dug pretty deeply into that code and I think you're right that this will work. Yes, it seems the Eclipse JUnit plugin has a launch listener that listens for launches with the `ATTR_JUNIT_PORT` set and fires up `RemoteTestRunnerClient` if it is.

Thanks for the pointers @pkriens, I appreciate your time and I think I will be able to figure it out from here.

**Comment by kriegfrj** [comment]
A bit of an update: I have a working prototype of this now in my fork. It will probably become part of #3145.

For the record: simply setting `ATTR_JUNIT_PORT` and allowing continuous mode didn't work. It would fire once, but wouldn't pick up subsequent runs. Closer inspection revealed that Eclipse's `RemoteTestRunnerClient` stops listening once the test run has been completed, so it doesn't display the result of subsequent test runs.

To get a round this, I dug a bit further and followed the path of `ATTR_JUNIT_PORT`: The JUnit plugin sets a `LaunchListener` that listens for launches with this attribute set. When it finds one, it creates a `TestRunSession` and then notifies all registered listeners by invoking `TestRunListener.sessionLaunched()` (the UI tab part is one of the registered listeners). It was not difficult to copy this code so that the `OSGiJUnitLaunchDelegate` can directly start new test sessions on demand. I then set up a simple control protocol that the `JUnitEclipseReport` uses to communicate with the delegate and notify it when a new test run is about to begin - the delegate then in turn starts the `TestRunSession` and invokes `sessionLaunched()` on all registered listeners.

Hope to have the PR up for all this JUnit stuff soon.
