### ISSUE TITLE
@Export annotation does work correctly

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#2991]
After reading Neil's blog post https://virtual.osgiusers.org/2018/10/pure-annotation-driven-dev I've tried to convert a project over to Export annotation. Alas, that didn't work like expected.

I've put a reproducer on my gitlab account, see https://gitlab.com/fhuberts/musicTreePrograms/tree/export-annotation.
  
See project nl.pelagic.audio.conversion.flac2mp3.api: the generated
bundle is not correct since it is missing the package
nl.pelagic.audio.conversion.flac2mp3.api, even though it has a
package-info.java with Export and Version annotation.

**Comment by amitjoy** [comment]
Use `-includepackage` instead of `Private-Package`

**Comment by fhuberts** [comment]
They are equivalent, should work the same.
Besides, the bnd file editor generates Private-Package headers...

**Comment by amitjoy** [comment]
I am currently using in `@Export` with `-includepackage` in my central API bundle and it works perfectly. Since you are exporting the API package, you shouldn't specify it in `Private-Package` or `-privatepackage`. On the other hand, you would need the package to be part of the target JAR and exported API. That's why you should use `-includepackage` instead. You should only specify a package in `Private-Package` or `-privatepackage` if and only if the package should be part of target JAR and it is *not* an exported API.

**Comment by bjhargrave** [comment]
@amitjoy is correct. For backward compatibility, `Private-Package`/`-privatepackage` means the package is private and `@Export` will be ignored. `-includepackage` can be used to add packages which are processed for `@Export`. 

Also, if you do not use any of the headers or instructions to control the contents of the bundle, then Bnd will `-includepackage` all the built packages in the project. This is how most people expect the jar contents to be from standard maven/gradle projects. So you can probably simply remove the `Private-Package` header from your bnd file and Bnd will include all the packages in the project in the jar.

**Comment by fhuberts** [comment]
IMHO a bit premature to just close it.
The bnd editor generates Private-Package headers, which appear to be incompatible with @Export.

AFAIK Private-Package and -includepackage are completely equivalent, so why do they not act equivalent.

To me the solution can be
- adjust the bnd editor to use -includepackage and make sure everyone know not to use Private-Package (breaking change, since everyone has to adjust their projects)
- make -includepackage  and Private-Package do the same

the latter is obviously preferred

**Comment by fhuberts** [comment]
and if you're going the way of adjusting the bnd editor then at least help your users with automatic conversion from Private-Package to -includepackage for existing bnd files...

**Comment by bjhargrave** [comment]
I closed the issue based upon the claim that `@Export` does not work correctly. It does work as designed. If you think there should be a UI change around the bnd editor for `-includepackage`, perhaps that is best as a separate issue properly describing the suggested improvement.



>     * adjust the bnd editor to use -includepackage and make sure everyone know not to use Private-Package (breaking change, since everyone has to adjust their projects)

The bnd editor has been changed to handle both `Package-Private` and `-privatepackage`. These are equivalent and both mean the any named packages are truly private (as the names suggests) and thus not exported.

The bnd editor could be improved to support `-includepackage` in some way.

>     * make -includepackage  and Private-Package do the same

`-includepackage` was added specifically to support including a package and processing any `@Export` encountered. Thus they are not the same.

**Comment by fhuberts** [comment]
Well, I could argue just as well that Export does NOT work correctly in the presence of Private-Package.

The project with the problem ONLY lists an i18n package in P-P, NOT the exported package. The exported package has the Export annotation.
So I really think there is a bug.

See my issue description, and the code on gitlab.

**Comment by fhuberts** [comment]
Another aspect to the bug is that even though it might work nicely for a Maven based workflow, it does NOT for a bndtools based workflow, in which the bnd editor is normally used to build the bundle(s).
That makes the original primary workflow a second class citizen, that must have been an unfortunate oversight right?

Please consider fixing this.
