### ISSUE TITLE
bndtools does not respect Eclipse indentation formatter settings

### ISSUE THREAD

**Issue by DaHoC** [bndtools/bnd#2996]
When editing `.bnd` files via Eclipse bndtools UI, bndtools always uses tabs as indentation, independent of the currently set formatter options for indentation (preferences at _Eclipse -> Window -> Preferences -> Java -> Code Style -> Formatter -> Indentation -> Tab policy ( & Indentation size & Tab size)_)
It would be nice if the current formatter options were respected.

![image](https://user-images.githubusercontent.com/316884/53008040-cb971580-3438-11e9-9dfa-6be49e617ea3.png)

**Comment by DaHoC** [comment]
Looking at the sources, I guess https://github.com/bndtools/bnd/blob/04b35437416993d56d1c5417d06843a358f56f56/biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java#L75
and
https://github.com/bndtools/bnd/blob/04b35437416993d56d1c5417d06843a358f56f56/biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java#L76
would have to be adapted

**Comment by bjhargrave** [comment]
BndEditModel is in the bndlib jar which is useful independently of Eclipse including the maven and gradle plugins. So this code must not have compile/runtime dependencies on Eclipse plugins.

**Comment by pkriens** [comment]
I am anyway not that happy with this idea at all. I think it is fundamentally wrong to do anything that is developer specific for any object that goes into the build. It will make repeatable build and git patches much harder. It is one of those things where developers think it is important but the fact that it can differ causes problems or inefficiencies downstream in the development pipeline.

Kind regards,

	Peter Kriens

**Comment by DaHoC** [comment]
> So this code must not have compile/runtime dependencies on Eclipse plugins.
I understand - however, this would not be a blocker, it could have a default property (use tabs) that could be conditionally set by Eclipse.
> It will make repeatable build and git patches much harder
That is the very reason we would like to introduce this, as lines in the source view of the `.bnd` files that are edited manually conform the formatting rules, so there's always a changing mix of both.

How about if we could apply the formatting rules to `.bnd` files (i.e. the corresponding text editor) as well, when the developer in Eclipse does a _Source > Format_ - would that be possible / feasible?
![image](https://user-images.githubusercontent.com/316884/53077716-e928b580-34f2-11e9-8655-c8695846ea5a.png)

**Comment by bjhargrave** [comment]
This would be ok with me. My concern was to make sure no Eclipse dependencies creep into bndlib.

**Comment by pkriens** [comment]
The only settings we should use is in the workspace. I do not like any eclipse setting to influence the workspace in any way. So if this is really very important then we need a -tabs=<n> instruction that can be used in the workspace. 

For formatting, we're awaiting your PR :-)

**Comment by ViToni** [comment]
The current behaviour is especially surprising when doing  refactorings.

Say the bnd file contains this:

```
-privatepackage: \
<some_spaces>a.b.c
```
and `a.b.c` gets renamed to `x.y.z` then the bnd file will get automatically updated (which is nice) but now inclunding tabs (not so nice):

```
-privatepackage: \
<tab>x.y.z
```

When people are switching to bnd they might also make some "housekeeping" in addition.
Especially for these it would be very annoying that formatting gets mixed up all over again and again.
