### ISSUE TITLE
Bndtools Developer Guide

### ISSUE THREAD

**Issue by maggu2810** [bndtools/bnd#2999]
I would like to read, debug and perhaps change some code of bnd / Bndtools.

I read https://bndtools.org/development.html and https://github.com/bndtools/bnd/blob/master/CONTRIBUTING.md

I know how to use Git, I also know how to build on command line etc.

But I don't know how to setup the Eclipse IDE to use the change the source code "correctly".

If I try to import all projects of the source repository ("Existing Projects into Workspace") it fails e.g. because there are four projects named "cnf".
Also after importing the other projects it results (on my machine) in thousands of build errors.

If I try to import a "Bnd workspace" the result is the same (thousands of build errors).

Is there some guideline how to setup an IDE (e.g. the Eclipse one) correctly?

Are there some formatter templates?

Would it be an option to provide an Oomph setup file?

**Comment by bjhargrave** [comment]
To build this repo in Bndtools, you must have installed the latest snapshot of Bndtools in Eclipse: https://github.com/bndtools/bnd#using-the-latest-development-snapshot-build-of-bndbndtools

We use our own latest tools to build Bnd.

Then you just import existing projects (not nested projects) into an new Eclipse workspace. The only nested projects to install are the maven projects if you want to work on the maven plugins. Then you will also need m2e installed in Eclipse.

Each projects has its own .settings folder which includes formatter information.

**Comment by maggu2810** [comment]
Thanks a lot!

I assume there has been two problems with my setup:

* I installed the latest released version (not development snapshot) of the Bndtools inside the Eclipse IDE
* I imported all projects -- also the nested ones.

Excuse the circumstances.
