### ISSUE TITLE
Verifier doesn't detect Bundle-Classpath

### ISSUE THREAD

**Issue by andilem** [bndtools/bnd#3006]
I'm trying to verify (with the BND Verifier) an OSGi bundle containing a "main" class and a jar with required classes for that class. I have set the Bundle-Classpath correctly to ., my.jar - but the verifier tells me that the required classes cannot be found on the Bundle-ClassPath: []. That means the analyzer doesn't detect this property correctly.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by andilem** [comment]
Here it is: https://github.com/andilem/bnd-verifier-classpath

**Comment by rotty3000** [comment]
I've also noticed some issues in the verify stage which are probably related by a common symptom.

I had to do this during verify:
```
// We need to use this approach because the analyzer fields are no
// longer in sync with the headers
Parameters provideCapabilities = OSGiHeader
	.parseHeader(mainAttributes.getValue(Constants.PROVIDE_CAPABILITY));
Parameters requireCapabilities = OSGiHeader
	.parseHeader(mainAttributes.getValue(Constants.REQUIRE_CAPABILITY));
```

**Comment by bjhargrave** [comment]
> I've also noticed some issues in the verify stage which are probably related by a common symptom.

@rotty3000 The fix should solve your issues also since when using the `Verifier(Jar)` constructor, it will now read the manifest from the Jar to initialize the Analyzer.

**Comment by andilem** [comment]
Thanks for trying to fix this, but I think there is a further error.
Now it works if the manifest contains the attribute "Bundle-ClassPath", but the attribute is **not fetched case-insensitively**, i.e. it doesn't work for "Bundle-Classpath" (lower case p). The problem lies in aQute.bnd.osgi.Processor, l. 1435f.:
```
Object raw = proc.getProperties()
    .get(key);
```
where key is just a String. To do it correctly, one would have to use java.util.jar.Attributes.Name or something similar as map key type and for comparison.

**Comment by bjhargrave** [comment]
Well, Processor/Domain always get case sensitive but should normalize the key on setting. I have a patch to fix this for Processor.set which will fix your problem.

It is always better to write manifests using the proper casing which Bnd does.

**Comment by andilem** [comment]
Thank you very much. I followed your advice and normalized my attributes.

If anyone is interested in a workaround for the original problem:
```
try (Analyzer analyzer = new Analyzer(jar); Verifier verifier = new Verifier(analyzer)) {
    analyzer.calcManifest();
    verifier.verify();
    ...
}
```
