### ISSUE TITLE
BndEditModel messes up on macros

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3008]
In `biz.aQute.junit`'s `bnd.bnd` file, the `-buildpath` entry is as follows:

````
-buildpath: \
	osgi.core;version=@4;maven-scope=provided,\
	osgi.cmpn;version=@4;maven-scope=provided,\
	aQute.libg;version=project,\
	biz.aQute.bndlib;version=latest;maven-scope=provided,\
	${replacelist;${list;junit};$;\\;maven-scope=provided}
````

The attribute parse in `BndEditModel` does not seem to understand the macro language. So when you edit the raw `bnd.bnd` file through `BndEditModel` (eg, through the `Bndtools` GUI, or using the `ImportPackageQuickFixProcessor`) it messes it up. For example, if you look at the above in the Bndtools GUI it appears as follows:
![buildpath](https://user-images.githubusercontent.com/7224087/53308752-93d61500-38f3-11e9-938d-1ea478c3e5d9.png)
If I add (eg) `biz.aQute.launchpad` to the build path using Bndtools GUI or the Quick Fix processor and saving, the result is as follows:

````
	osgi.core;version=@4;maven-scope=provided,\
	osgi.cmpn;version=@4;maven-scope=provided,\
	aQute.libg;version=project,\
	biz.aQute.bndlib;version=latest;maven-scope=provided,\
	${replacelist;maven-scope=provided},\
	${list;maven-scope=provided},\
	junit};maven-scope=provided},\
	$;maven-scope=provided},\
	\;maven-scope=provided},\
	biz.aQute.launchpad;version=latest
````

It looks like some part of the code is naively stuffing "`maven-scope=provided`" after every semicolon where it is not already present. Bnd of course then falls over on the result.

**Comment by bjhargrave** [comment]
It looks like BndEditModel does not know how to parse `-buildpath` which includes macros like `${replacelist;${list;junit};$;\\;maven-scope=provided}`. It seems to blindly parse the string at semicolons which are separators in macros. Since BndEditModel does not and should not resolve macros, it will need a more sophisticated parser than `Parameters`.

**Comment by kriegfrj** [comment]
I think there are two aspects to this fix:

1. At the basic level, `BndEditModel`, as you say, should be smarter at how it parses `-buildpath` so as to understand macros well enough to skip over them and include them as one entry.
2. As a more advanced feature, on the GUI side it would be nice if it could toggle between showing the raw macro (editable) and the results of its expansion (or perhaps both somehow).

I think this issue should concentrate on the first aspect, so that at least you can use the GUI and quickfix without messing up your macros. The second aspect could be the subject of a separate issue.

**Comment by bjhargrave** [comment]
The UI should recognize macros and make them non-editable.
