### ISSUE TITLE
Exclude module-info class from class version in use calculation

### ISSUE THREAD

**Issue by krystiannowak** [bndtools/bnd#3010]
Exclude module-info class from class version in use calculation:
https://github.com/bndtools/bnd/blob/e9f68839faa746407ca574235a89e7e2581fa27a/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L241-L246
due to the fact that currently almost the whole dependency JAR (its classes) might be compiled against say JDK 7 level but module-info.class might be compiled against JDK 9, as here: https://gitlab.ow2.org/asm/asm/issues/317870
which makes the calculated "Require-Capability" osgi.ee for version 9, which should be practically still for version 7 in this case.

**Comment by bjhargrave** [comment]
FYI. I have cherry-picked this fix into the 4.2 release candidate. So it will be in 4.2 when we release later this week.

**Comment by krystiannowak** [comment]
@bjhargrave Big thanks for that - as soon as its released the upgrade of the dependency link in https://github.com/apache/felix/blob/trunk/tools/maven-bundle-plugin/pom.xml#L164-L168 to it can be done!
