### ISSUE TITLE
Test suite for biz.aQute.junit

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3011]
Because biz.aQute.junit is widely used, making changes is high risk. This risk would be somewhat lessened, and contributors could contribute with greater confidence, if it had some regression tests. This would make it easier for implementing (eg) #2958 and #2983 without introducing any breaking changes inadvertently.

**Comment by pkriens** [comment]
This is not very likely to attract a lot of changes. They were hell to develop since you're often in 2 levels of debuggers. Since they are so specialized I'd suggest to punt on their testing a bit. Any problems are quickly detected imho since these bundles are so much at the bottom of the stack.

**Comment by kriegfrj** [comment]
In support of the case for a test suite, I point to #3288, which I discovered because of the regression tests that I have implemented for `biz.aQute.junit`/`biz.aQute.tester`. :smile:

I get what you are saying about the tester being at the bottom of the stack, but (as #3288 demonstrates) the problem with relying on this is that, most of the time, your tests are all passing. So if we're relying on the code base to exercise our tests for us, we're really only testing the code path for passing tests. As an extreme example, you could introduce a bug into the tester that causes it to always report tests as passing (even when they're not) and you wouldn't immediately notice. Or perhaps more insidiously (and difficult to detect and debug) if there are a certain subset of cases where it incorrectly reports them as passing when they should have failed - this could go unnoticed for some time.

What a dedicated test suite gives us that the regular code base doesn't is verification that the tester behaves & reports properly in the face of failing/bad tests.

**Comment by pkriens** [comment]
You are of course right and it is hard to disagree with you. However, nature tends to err on the messy side which tends to show up as errors in actual testing. It is for me mostly a matter of where to spend my time I think it is most effective. But I will never stop someone from doing it, just a warning that the extra process indirection made developing the launcher and the tester very hard.
