### ISSUE TITLE
[launchpad] bundleSymbolicName() cannot be invoked manually

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3019]
I may have this wrong, but...

It seems to me the intended use of `BundleSpecBuilder.bundleSymbolicName()` is to be able to manually set the BSN of the synthetic bundle you are creating.

The default implementation of `BundleSpecBuilder.bundleSymbolicName()` doesn't permit you to set the BSN twice, and will throw an `IllegalArgumentException` if you attempt it. This kinda makes sense and guards against accidentally trying to set it twice.

However, the constructor in `BundleBuilder` calls `bundleSymbolicName()` as a matter of course with unique, synthetic name. This is useful in that it relieves the programmer of the burden of setting it in most cases where the BSN is not important. However, it also means that if you want to set it manually, by the time you actually get a chance to set it it's already been set, and you get the `IllegalArgumentException`.

It's possible that I've not understood how to use this properly, in which case I apologise. However, it seems to me that the synthetic BSN feature should be added at the latest possible opportunity, if the BSN has not been manually set (ie, during `BundleSpecBuilder.install()` rather than in the constructor).

**Comment by pkriens** [comment]
That looks like an oversight. Could you make a PR?

**Comment by kriegfrj** [comment]
As long as you're happy to wait 13 hours or so, I'm happy to have a go at a PR.
