### ISSUE TITLE
Maven Provided

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3020]
The maven-provided attribute on buildpath seems to be used to handle the dependency section of of the resulting pom. This means that if someone includes a bundle, he gets all the shit on his classpath. Very likely getting versioning issues because we try to compile against the lowest version. This is one of the core idea we've been trying to fight in OSGi that there is no long transitive chain of dependencies. However, people seem to like that and we need to support it I guess.

However, this has resulted in an uglification of the buildpath. Because it is so ugly, people start to muck around with macros to make it more readable or just for reason of lazyness. This was not the intention, the idea was to keep the metadata more readable but this starts to look like XML :-(

If this is really needed (and I still need some convincing if we need it in the bnd build) we could at least provide a better way to use this. We could solve this with a best use pattern. For example:

   in build.bnd:

        -buildpath.provided = ${ .... ${-provided} }

   In the project

    -provided \
        osgi.annotation;version=latest, \
       osgi.core;version=latest, \
       org.osgi.service.component;version='[1.3,1.4)', \
       org.osgi.service.component.annotations;version='[1.3,1.4)'

    -buildpath: \
         aQute.libg;version=project, \
         biz.aQute.bndlib;version=latest;packages=*, \
        org.eclipse.jdt.annotation;version=@2

Alternatively, we could make it a standard instruction.
It pains me every time I see these ugly -buildpath. Could be because I do not see the benefit at all.

**Comment by bjhargrave** [comment]
You also made this same discussion in the mail list. Where are you looking to hold the discussion?

**Comment by pkriens** [comment]
here

**Comment by bjhargrave** [comment]
> here

Yeah, I got confused...

**Comment by bjhargrave** [comment]
Add a `-maven-scope` instruction to set the default maven scope for  dependencies in the generated pom.

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bnd/pull/3043
