### ISSUE TITLE
[launchpad] LaunchpadBuilder instance settings not isolated from each other

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3026]
I was using Launchpad (which seems like a great tool) but was perplexed that my builder settings seemed to be "sticky" between tests and not isolated as I had hoped. This in spite of the fact that I was creating a fresh `LaunchpadBuilder` instance on every test execution. This made my test results dependent on test execution order, which makes it unmaintainable.

A bit of digging turned up the following:

1. `LaunchpadBuilder.set(String, String)` is putting the key/value pair into the static `projectTestSetup`'s properties instance instead of the instance variable `local`'s properties map.
2. The constructor clones `projectTestSetup` and assigns it to `local` at the start of every test. However, `RunSpecification`'s `clone()` implementation is simply a wrapper around `Object.clone()` to narrow the return type. This means that the returned value is a shallow clone rather than a deep clone. This means that every time you edit any of the container values in the builder (`runpath`, `properties`, `runfw`, `runbundles`, `extraSystemPackages`, `extraSystemCapabilities`, `errors`), you are updating the values in `projectTestSetup`.

I'm pretty sure that this is not the intended behaviour - the intended behaviour (it would seem to me) is for individual builder instances to be isolated from each other's changes, and that the constructor should deep clone `projectTestSetup`. However, I thought I'd give @pkriens the opportunity to comment before I submitted a patch in case there was something I hadn't understood.

**Comment by pkriens** [comment]
oops. that is wrong. If you can do a PR it would be appreciated
