### ISSUE TITLE
P2Repository download validation

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3030]
The MavenRemoteRepository has retry loop where after downloading the artifact, it downloads its sha1 or md5 signature and validates the downloaded artifact.

However the P2Indexer merely downloads artifacts and assumes they are OK. It appears we do have the md5 for each artifact, so we should be able to make a retry loop where we confirm the md5 signature of the download and retry if it does not match.

I suspect this is the problem we now have in the CI builds for artifacts from Eclipse p2 repositories.

**Comment by bjhargrave** [comment]
@pkriens I started to look at this, but I don't understand the code well enough. Can you look into this? I think this will make our CI builds more reliable. Thanks.

**Comment by pkriens** [comment]
Probably next week since I'm in Holland this week. However, shouldn't TCP protect us here?

**Comment by bjhargrave** [comment]
TCP may protect against corrupted packets but not against truncated files nor MITM.

Thanks.

**Comment by pkriens** [comment]
You're worried about man in the middle attacks that are so stupid  not to forge the checksums?

**Comment by bjhargrave** [comment]
> You're worried about man in the middle attacks that are so stupid not to forge the checksums?

Of course not. You stated that TCP should protect against invalid files. I pointed out some examples were TCP integrity does not help.

I am concerned about builds the work reliably. I hope that validating md5 sums and retrying when there is a mismatch will enhance build reliability. The maven repo does this checking and I cannot recall ever having had download issues from maven central like we have with the p2 repos at Eclipse.

**Comment by pkriens** [comment]
Hmm, probably something in the code because I don't think normal TCP connections could cause regular problems on high speed networks.
