### ISSUE TITLE
Mark Bndtools tutorial stale until we are able to replace it

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3040]
As discussed on the maintainer's call today, we should mark the Bndtools tutorial pages such that a reader knows that the information is out of date and should not be used. We need to eventually update the information.

@pkriens said he will update the page with such a warning.

**Comment by tomaszG247** [comment]
YES PLEASE DO THAT I JUST LOST 2 HOURS OF MY LIFE AND I AM PISSED

**Comment by seanbright** [comment]
@tomaszG247 thank you, this is helpful feedback.

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bndtools.github.io/pull/17
