### ISSUE TITLE
Projects ain't displayed in Package Explorer View

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#3049]
After updating to the recent version, the projects ain't displayed in `Package Explorer View` anymore. Not sure where the problem lies - Eclipse IDE or Bndtools. I can see the projects in `Project Explorer View` only.

<img width="820" alt="bildschirmfoto 2019-03-06 um 01 23 17" src="https://user-images.githubusercontent.com/13380182/53846832-c399b280-3fae-11e9-92f4-38b981fad135.png">

<img width="829" alt="bildschirmfoto 2019-03-06 um 01 27 51" src="https://user-images.githubusercontent.com/13380182/53846923-15dad380-3faf-11e9-8c37-c6bf71735617.png">

My current configuration is as follows:

 1. Bndtools 4.3.0.DEV-20190304-192239-g38cec6a
2. Eclipse 2019-03 M2 (4.11.0 M2) Build id: 20190207-1445

**Comment by pkriens** [comment]
You're running a milestone build ... This sounds more like an Eclipse problem than a bndtools issue?

Kind regards,

	Peter Kriens

**Comment by amitjoy** [comment]
I thought so. I will run a few more tests to verify it.

**Comment by amitjoy** [comment]
The bug was in Eclipse and the last update got it fixed.
