### ISSUE TITLE
Eclipse Plugin seems to ignore settings.xml / connection-settings.xml

### ISSUE THREAD

**Issue by ArneCL** [bndtools/bnd#3057]
**Setting:** Project in a *Gradle*-Build Environment, some dependencies hosted on own Nexus-Server secured with username/password (No Oauth2). A *settings.xml* file with the server credentials is placed in the user's *.m2* directory as described [here](https://bnd.bndtools.org/instructions/connection-settings.html)). 

**Behaviour:** After importing the project in Eclipse, all external dependencies (e.g. *repo.maven.apache.org*) are resolved fine. However, the BND-Eclipse plugin failes to resolve the internal dependencies. In the BND-Tools Perspective, the internally hosted dependencies are shown with an *'(!)'* in their name. They are also not downloaded to the *m2/repository* dir. Placing the credentials in a *connection-settings.xml* file in the *.bnd* dir / inline leads to the same result.  

**Expected Behaviour:** After importing the project in Eclipse, all dependencies should be present in the user's *m2/repository* dir.  

**Workaround:** After importing the project in Eclipse (and letting it fail), I currently do a `gradle tasks` in the project dir. This correctly downloads the missing dependencies. (Thus, I am assuming that my settings.xml formatting etc. is fine.) Afterwards I restart Eclipse and do a *Project → Clean*, which builds the project correctly. 

**Versions:**
- Eclipse: 2018-12 (4.10.0)
- BND-Tools for Eclipse: 4.1.0
- OS: Windows 10

If there are debugging-options / logs I can provide you with please let me know!

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.
