### ISSUE TITLE
aQute.maven.api.Revision has no public constructor

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#3058]
Is there any special reason why there is no public constructor for `Revision`? This prevents me from subclassing `Revision` which requires some nasty workarounds in my code.

**Comment by bjhargrave** [comment]
The Revision class, like many classes, is designed to be constructed via static methods. This provides more control and flexibility for the returned object. The class is not designed for subclassing.

**Comment by pkriens** [comment]
What is the actual use case?

The problem with making things extendable is that you make the users more miserable because they have fewer guarantees. So you need a strong use case to make things extendable.

**Comment by mnlipp** [comment]
"Not designed for" does not necessary mean that subclassing may not be required.

My use case is to get the "absolut" remote URL for a resource. Therefore I need the reference
to the maven backing repository that provides the revision in order to call its `toURI` method. Unless I have overlooked something very obvious, `MavenRepository.toRemoteURI` is not suited for the task because it always calls `toURI` on `repository.get(0)` which only works if you have only one repository (or you're lucky).

Of course, fixing `MavenRepository.toRemoteURI` would be preferable on the long run (but you'd need a reference to the maven backing repository in the `Revision` for that).

**Comment by pkriens** [comment]
well, changing Revision to hold a pointer to the repo sounds awfully wrong. Wouldn't it be better to fix `toRemoteURI` to search the repos?

**Comment by mnlipp** [comment]
Sounds like spending time on recovering information that was already available.

Of course, nobody will ever have enough backing repositories configured to notice a difference. But conceptually, a `Revision` always has its origin in a maven backing repository. So what's wrong with an object having a reference to its origin?

**Comment by bjhargrave** [comment]
The concept of a Revision does not have a backing repo. Just like in OSGi, an osgi.identity capability is not an osgi.content capability.

The content for a Revision can be hosted on many different backing repositories: Maven Central, JCenter, my corporate nexus, etc.

This is why Revision exists without a link to a backing repository. You can look up a Revision in any configured backing repository which may or may not hold the content for the Revision.

**Comment by mnlipp** [comment]
I don't fully agree with that. Of course, life would be unnecessarily hard if I claimed the same GA(V) coordinates e.g. on Maven Central and JCenter and would then use them for publishing completely different artifacts. But nothing prevents me from doing so.

I suppose *nobody* does it and that's the idea behind the "mvn:..." URIs in karaf. But one has to be aware that nothing enforces this. You'd need something like GAV+Hash --- or, well, repository URL + GAV.

Anyway, we should be able to agree on the fact that not everybody hosts all artifacts on all maven repositories. So the current behavior of `MavenRepository.toRemoteURI` is wrong, because the resulting URI may be invalid. Whether this is fixed by searching the backing repositories for a valid provider or keeping a reference to the origin of the revision in the implemented `Revision` object (my approach, which led to this discussion) is a matter of taste, considering that there will never be that many repositories to search.

**Comment by pkriens** [comment]
The idea of a revision was that it is immutable and that any repo can provide it. Once you add origin you get nasty questions when are two revisions equal? You now also need to think of when you do not have an origin, the meaning of such an object is suddenly very different. By combining the Revision (a name) with the origin (making it a pointer) you combine to very different things and that creates imho a huge amount of complexity because there are no so many error cases that did not exist before. Generally when you combine concepts (ptr and name) you get many combinations that have no meaning and must explicitly tested for or protected against. It basically flies against software law nr 1: high cohesion.
I've no problem for toRemoteUri to become cleverer and search the repos for a match. Alternatively, we could have an alternative object that would combine a revision with a URL?

**Comment by mnlipp** [comment]
Bnd may follow that idea of a revision being immutable and any repo being able to provide it. But the latter assumption doesn't model the reality of maven repositories. Maven only states ["The three fields act much like an address and timestamp in one. This marks a specific place in a repository, ..."](https://maven.apache.org/pom.html#Maven_Coordinates). English is not my first language but I'm quite sure "*a* repository must be read as "*some* repository" (and not "*any* repository"). And as can be seen in [maven source code](https://github.com/apache/maven/blob/master/maven-artifact/src/main/java/org/apache/maven/artifact/Artifact.java) an `Artifact` has, of course, a repository property to identify the repository that makes it available.

You could introduce a type `BoundRevision` that models a "looked up" maven revision. But actually, a `BoundRevision` wouldn't help. Because what I want to do is ask an `Archive` for its (external) location. In bnd the `Archive` has a property `revision` of type `Revision`, which would have to be changed to `BoundRevision`. Eventually, I think you'd end up having `BoundRevision` almost everywhere.

I don't really get the conceptual distinction between `toRemoteUri` being clever enough to find the repository that is the origin of a revision and storing the origin of a revision as attribute of `Revision`. Both reflect the existing relationship (!) between a revision and the repository that provides it (the related artifacts to be precise). The former approach requires looking up the revision in the backing repositories again and again, while the latter simply preserves the information as it was found during the initial lookup of the revision. The `toRemoteUri` approach avoids a temporary NullPointer while you're in the process of creating a new revision that hasn't been uploaded yet. But `toRemoteUri` will also have to return null in that situation. The repeated lookup approach provides automatic fallback if you have two repositories providing the revision and one failing while bnd is running, but ... really?

Anyway, I've worked my way around the problem in my code, of course. (If you cannot extend a type, there are always approaches such as delegation or associating additional properties using a map&mdash;ugly but working.) It would have been easier if `Revision` was extendable (that's why I was asking), but it is not a show stopper.

**Comment by pkriens** [comment]
ok
