### ISSUE TITLE
v4.2 is not working on eclipse neon.3

### ISSUE THREAD

**Issue by novos40** [bndtools/bnd#3069]
4.2.0-REL is completely broken on eclipse neon.3. Repository and resolution views are not working and seems to be missing from the list of views as well as .bndrun file editor. Reverting to 4.1 fixes all problems.

**Comment by bjhargrave** [comment]
4.2.0 was compiled against Oxygen 4.7.3a

https://github.com/bndtools/bnd/blob/055373624c727469243e04570294640ba0c75071/cnf/ext/repositories.bnd#L34-L37

So it should work if you are using Oxygen 4.7.3a or later. Most of the Bnd developers are using much more recent Eclipse versions. I use 2018-12 currently.

Have you tried to use a more recent Eclipse version?

**Comment by novos40** [comment]
Sorry for misleading typo. I meant eclipse neon.3, not oxygen. I understand it's an old version, but it's still in use today.

**Comment by bjhargrave** [comment]
We cannot fix 4.2 since it is released. But for 4.3, we can require the minimum level of the Eclipse platform.
