### ISSUE TITLE
[Launchpad] Add a way to prevent packages from being exported from the framework bundle

### ISSUE THREAD

**Issue by brampouwelse** [bndtools/bnd#3081]
Launchpad is exporting all exported packages from the framework, it would be nice if there is a way to filter these exports. 

@pkriens has some idea on this: https://groups.google.com/forum/?fromgroups=#!topic/bndtools-users/ER9KKcmTDXo

**Comment by kriegfrj** [comment]
+1 I was thinking the same thing just recently.

One possible implementation would be if you could specify a list of package prefixes to exclude on the LaunchpadBuilder. The Similar to Mockito's internal `ExcludingClassLoader` (https://github.com/mockito/mockito/blob/release/2.x/src/test/java/org/mockitoutil/ClassLoaders.java). Using an excluding classloader to bootstrap the framework should do part of the trick.

**Comment by brampouwelse** [comment]
I don't think special class loaders are required, it's just the framework packages extra if Launchpad has a way to filter that before is used that would do. 

For now I've managed to find a place to where I can change the list just before it's used. It's a hack but it makes my logging work :D 

```java
package aQute.launchpad;

import java.util.regex.Pattern;
import java.util.stream.Collectors;

import org.osgi.framework.Constants;
import org.osgi.framework.launch.Framework;

/**
 * {@link LaunchpadBuilder} that removes the slf4j packages from the FRAMEWORK_SYSTEMPACKAGES_EXTRA property value
 *
 * Workaround for: https://github.com/bndtools/bnd/issues/3081
 */
public class LaunchpadBuilderExt extends LaunchpadBuilder {

    @Override
    Framework getFramework() {

        String systemPackagesExtra = local.properties.get(Constants.FRAMEWORK_SYSTEMPACKAGES_EXTRA);
        String filteredSystemPackagesExtra = Pattern.compile(",").splitAsStream(systemPackagesExtra)
                .map(s -> s.trim().startsWith("org.slf4j") ? s.endsWith("\"") ? "\"" : "" : s)
                .filter( s-> !s.equals(""))
                .collect(Collectors.joining(","));

        local.properties.put(Constants.FRAMEWORK_SYSTEMPACKAGES_EXTRA, filteredSystemPackagesExtra);

        return super.getFramework();
    }

}
```

**Comment by kriegfrj** [comment]
You're right, no extra classloader needed - just need to add additional options for configuring the classloader that is already set up.

I've just submitted a PR as a proposed implementation of your request (see #3084). If you check it out and use it, you should be able to achieve the same as your "hack" simply by adding `excludePackages("org.sl4fj.*")` to your builder chain.

I'll be interested in your feedback on the design of this interface.

**Comment by brampouwelse** [comment]
I tried to use the `-exportexcludes` but can't get that to work. I think it has at least two issues
1. Parameters don't seem to work see: https://github.com/bndtools/bnd/issues/3102
2. The exludes are merged in a new excludes list (https://github.com/bndtools/bnd/blob/master/biz.aQute.launchpad/src/aQute/launchpad/LaunchpadBuilder.java#L210) but the `excludeExports` from before merging is passed to the `restrict` method

And then  a third problem I had was that it took me some time to figure out the `-exportexcludes` is not a real instruction but should be passed as part of the `-runproperties`(was that intended) ?
