### ISSUE TITLE
Add "release" as version keyword or ignore GIT-headers in baseline check

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#3093]
There is [currently no way](https://github.com/bndtools/bnd/wiki/Buildpath-Versions) to reference the latest release of a bundle.

Use case: the issue comes up if you have a multi-bundle project with independent releases for the bundles *and* you start using the Git-Descriptor/Git-SHA headers (which are a nice feature).

Once you have released a bundle from the project, you must increment its version to the next micro-SNAPSHOT, else you get a baseline error starting with the next git commit (because the header fields change).

Another bundle in the project that depends on the first must of course not use this not-yet-released snapshot version. Rather, it should depend on the latest released version. Currently, the only way to specify this is with an explicit version number.

An alternative would be to exclude the Git-headers from the baseline check. This wouldn't force you to move to a new version in the first place.

**Comment by bjhargrave** [comment]
BTW, you can control what the latest release for baselining is by the curation of the baseline repo. Here is how we do it for this project: 

https://github.com/bndtools/bnd/blob/2af091310ffd1638b149c17d40810a8f3f035583/cnf/ext/baseline.mvn#L1-L16

**Comment by mnlipp** [comment]
Thanks, I didn't remember `-diffignore`, solves it, of course. Maybe you should add it (at least in comments) to the workspace template.

The second approach comes down to configuring specific versions. That's what I wanted to avoid.
