### ISSUE TITLE
[Runtime Snapshot] Have some means to prefix snapshot names

### ISSUE THREAD

**Issue by brampouwelse** [bndtools/bnd#3103]
If you have the `biz.aQute.runtime.snapshot` and start multiple frameworks several times it get's messy very quick. Would be nice if the name could be prefixed somehow,  just a property that can be passed  as a run property would do. 

That could be used like for example: 

```java
new LaunchpadBuilder()
  .set("biz.aQute.runtime.snapshot", "instanceOne-myTestMethodName")  
  ...
```

![image](https://user-images.githubusercontent.com/1376865/55074725-5b139200-5091-11e9-8733-4bd55d2dc28b.png)

**Comment by pkriens** [comment]
I am traveling right now, will look next week.

Kind regards,

	Peter Kriens

**Comment by pkriens** [comment]
I've just committed a new version of launchpad and snapshot

- Launchpad accepts a name and/or classname in the create method. If no name is given it will use the method name and class name it was called from.
- Excluding exports should work now from a bndrun file as well
- Launchpad Parameters is moved to aQute.libg and made to be more completely matching Parameters
- Parenting builds. A parent(String) method now takes a set of files or either WORKSPACE or PROJECT. The set may be empty and the WORKSPACE xor PROJECT must be last.

Let me know, kind regards,

	Peter Kriens
