### ISSUE TITLE
Error in plugin: Tried to access class aQute.bnd.osgi.URLResource from class aQute.launcher.plugin.ProjectLauncherImpl

### ISSUE THREAD

**Issue by rickbijkerk** [bndtools/bnd#3105]
We're using the biz.aQute.bnd.workspace plugin version 3.5.0 and tried upgrading to a newer version (tried both 4.0 and 4.2) and ran into some issues.

Whenever i run the 'export' gradle task i get the following error:
* What went wrong:
Execution failed for task ':run_x:export.x'.
> tried to access class aQute.bnd.osgi.URLResource from class aQute.launcher.plugin.ProjectLauncherImpl

Im not sure where this problem occurs any pointers what could be the issue?
I tried looking for other similar issues but couldnt find anything related

**Comment by bjhargrave** [comment]
This sounds like you have mixed versions of Bnd jars. The version of the launcher jar is generally coupled to the version of bndlib (bnd gradle).

Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by bjhargrave** [comment]
Closing due to no response.
