### ISSUE TITLE
Modify aQute Launcher to work with equinox native launcher executables

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3109]
While analyzing how the equinox native launcher executables work #3087 how to make use of it for bnd projects I found the following behaviour for starting any java process if it finds a java native lib (like it always does for Mac and win):

Via the configuration ini accompanying the executable (e.g. eclipse.ini) a launcher jar can be set. Unfortunately it does not let java handle the start with the -jar option. It takes the jar, looks into the manifest if a Main-Class is defined. It directly calls the JVM to instantiate the Main class with a zero Args constructor and expects the following method to be available ```public int run(String[] args)```. The reason is, that it expects the method to return the desired exit code and has some additional logic that reacts to the given exit code (e.g. by triggering a relaunche of the java main (code 23) or the whole executable (code 24)).

At the Moment the aqute launcher has it logic of taking properties apart spread over the main method, the constructor and the run method. If we could get this condensed in the run method and get rid of the constructor, we would be instantly compatible and can even provide a version that supports the native JNI Bridge of Equinox that gives e.g. control over the splash screen.

@bjhargrave and @pkriens what do you think?

**Comment by pkriens** [comment]
Kind of bizarre to look a the Main-Class header and then not follow the convention of static main?

Anyway, I do not think there is a problem to move the properties logic to the run method. The run method was private so nobody can see it from outside so we should be ok there.

**Comment by pkriens** [comment]
Be aware that we also have the EmbeddedLauncher ... You need to see what the consequences are for this launcher since I recall it is the main class for executable jars.

**Comment by juergen-albert** [comment]
@pkriens I found that the Embedded Launcher is the one that is actually called. I modified both and It works like a charm in all the scenarios I could test.
