### ISSUE TITLE
Reevaluate bug 2980

### ISSUE THREAD

**Issue by filippor** [bndtools/bnd#3111]
https://github.com/bndtools/bnd/issues/2980
Sorry but I don't know how to reopen bug

with -runblacklist the resolve fail
I'd like to have something g like
-runprovided that exclude requirements from resolution and resolve all other

what I do now is resolve all requirements than manual remove the bundle I don't want
It's a manual operation that work for simple case like
https://github.com/filippor/osgi.enroute.examples.remoteservice/
but for complex bundle with transitive dependencies is not the ideal solution

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by filippor** [comment]
I think this is small https://github.com/filippor/osgi.enroute.examples.remoteservice/
The -runblacklist it fails to resolve otherwise resolve include service implementation that I want to provide through remote service

**Comment by bjhargrave** [comment]
I don't see any readme on how to reproduce the issue you are seeing and why -runblacklist does not address your need.

**Comment by bjhargrave** [comment]
I don't know what command to run, I don't know what the desired result is vs. the actual result. I need you to help us quickly understand the problem you have since you know more about the problem than we do :-)

**Comment by filippor** [comment]
I'm creating a readme on project for build instruction
what I want is a method to make resolve ignore a dependency during resolution and resolve all other without failure for missing dependency

**Comment by filippor** [comment]
-runblacklist try to resolve all dependency ignoring specified bundle

**Comment by filippor** [comment]
Readme added https://github.com/filippor/osgi.enroute.examples.remoteservice/blob/master/Readme.md

**Comment by bjhargrave** [comment]
`server-app/server.bndrun` has:

```
-runrequires: \
	osgi.identity;filter:='(osgi.identity=org.osgi.enroute.examples.microservice.impl)',\
```

So why are you surprised that the resolver would add this bundle to the result?

It does not make any sense to require that bundle and then blacklist that bundle :-). If you do not want that bundle in the result of the resolve, do not add it to the `-runrequires`.

If you know that some service will be provided by a remote service and not a local bundle, then you can tell the resolve using `-augments`: https://bnd.bndtools.org/instructions/augment.html. This will let the resolver produce a result.

**Comment by bjhargrave** [comment]
See https://github.com/osgi/v2archive.osgi.enroute/blob/master/osgi.enroute.pom.distro/augments.bndrun for some `-augments` examples.

**Comment by bjhargrave** [comment]
> -runprovided that exclude requirements from resolution and resolve all other

We have the opposite of this which is `-augment` which adds capabilities (and requirements) to resources in the resolution. This should address your needs here.

**Comment by filippor** [comment]
thanks for the info. Resolved my problem
