### ISSUE TITLE
gradle : ClassNotFoundException: aQute.bnd.build.Project

### ISSUE THREAD

**Issue by btpka3** [bndtools/bnd#3125]
ClassNotFoundException: aQute.bnd.build.Project

Just following the doc of gralde plugin [biz.aQute.bnd.builder](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md) with java 1.8.0_151 ,gradle 5.3.1, 
reported “java.lang.ClassNotFoundException: aQute.bnd.build.Project”。

But after add "biz.aQute.bnd:biz.aQute.bndlib:4.2.0" to "buildscript/dependencies", then it works:

```gradle
buildscript {
    dependencies {
        classpath "biz.aQute.bnd:biz.aQute.bnd.gradle:4.2.0"
        classpath "biz.aQute.bnd:biz.aQute.bndlib:4.2.0"           // added 
    }
}
```

Please update the doc, or add `biz.aQute.bnd:biz.aQute.bndlib` as dependency for `biz.aQute.bnd:biz.aQute.bnd.gradle`

**Comment by bjhargrave** [comment]
That should not be necessary as the biz.aQute.bnd.gradle jar expresses it dependency on biz.aQute.bndlib in its pom. I use biz.aQute.bnd.gradle successfully in many places without having to also add biz.aQute.bndlib to the buildscript classpath. For example, the build of this very project. 

Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by btpka3** [comment]
When preparing the demo. I found it works . I think it's the  maven/gradle cache's problem.
My original code using  four repo, after I comment out mavenLocal and aliyun proxy repo , it works without add `biz.aQute.bnd:biz.aQute.bndlib:4.2.0` to classpath.

```groovy
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url "http://maven.aliyun.com/nexus/content/groups/public/" }
        mavenCentral()
    }
```

**Comment by Vampire** [comment]
This probably was because of #3174
