### ISSUE TITLE
Overriding element in OSGi Requirement annotation does not work

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#3127]
bnd version: Bnd-4.2.0.201903051501

The JavaDoc of the OSGi Requirement annotation says:
> This annotation can be used to annotate an annotation. If the meta-annotated annotation declares an element of the same name as an element in this annotation, the element is considered to override the element in this annotation.

The support to override elements does not seem to work in bnd. Is it normal ? 

Here is an example:
```
@Target(value = {ElementType.PACKAGE, ElementType.TYPE})
@Retention(value = RetentionPolicy.CLASS)
@Requirement(namespace = ImplementationNamespace.IMPLEMENTATION_NAMESPACE,
    name = "test",
    version = "1.0.0")
public @interface MyRequirement
{
  String filter();
}
```

Then when apply like this `MyRequirement(filter="(test=test)")` the generated manifest does not contain the `test=test` filter.

**Comment by bjhargrave** [comment]
You cannot override an element of the OSGi specified annotation with the same element name in the annotated annotation. This was a mistake in the OSGi spec.

See the errata for Core R7 section 10.8: https://www.osgi.org/osgi-release-7-errata/

The online spec has been updated for this: https://osgi.org/specification/osgi.core/7.0.0/framework.api.html#org.osgi.annotation.bundle.Requirement

But I see the online javadoc has not: https://osgi.org/javadoc/osgi.annotation/7.0.0/org/osgi/annotation/bundle/Requirement.html

So I need to fix that.

**Comment by bjhargrave** [comment]
> So I need to fix that.

Fixed.

**Comment by cdelg** [comment]
Thanks for the detailed answer. So there is no way for a meta annotated annotation to contribute to the filter expression (as it was the case with the RequireCapability annotation thanks to macro)?

**Comment by bjhargrave** [comment]
> So there is no way for a meta annotated annotation to contribute to the filter expression (as it was the case with the RequireCapability annotation thanks to macro)?

I am not sure but @rotty3000 may have some advice here.

**Comment by rotty3000** [comment]
haha... eeesh.. I tried to make this a feature of bnd with a special encoding, but would be non-spec (though still only a build time issue). I didn't manage to convince the bnd team (at the time) that it was an acceptable solution. However, I put the work together in a branch for people to dissect at their leisure.

https://github.com/bndtools/bnd/tree/rotty3000/bundle.annotation.inheritance

**Comment by rotty3000** [comment]
the gist of the change can be observed in https://github.com/bndtools/bnd/blob/rotty3000/bundle.annotation.inheritance/biz.aQute.bndlib.tests/test/test/annotationheaders/loader/ServiceConsumer.java

**Comment by bjhargrave** [comment]
> I didn't manage to convince the bnd team (at the time) that it was an acceptable solution.

Is there a PR or issue where we discussed and rejected this?

**Comment by rotty3000** [comment]
> Is there a PR or issue where we discussed and rejected this?

No, but re reviewed this in person at your dinning room table (was mixed in with the JPMS module metadata discussion since I was using this approach for the service loader annotations, which I've since remobeled another way).

**Comment by rotty3000** [comment]
I'm willing to start this conversation over with a PR...

**Comment by cdelg** [comment]
In addition to inheritance, does something can be done specifically for filters? Something like the macro feature from the RequireCapability annotation or may be a bnd @Filter annotation (with the same behavior as the OSGi @Attribute annotation but for filters)?

**Comment by timothyjward** [comment]
As I mention in the PR, we cannot do this naively. It is *absolutely required* that annotations opt-in to overriding the members of things that they are annotated with. We tried doing it the naive way and things exploded horribly.

**Comment by rotty3000** [comment]
Tim there's required opt-in in the form of the bundle annotation must
explicitly use the encoding to pull in anything. Nothing occurs
automatically.

**Comment by timothyjward** [comment]
> Tim there's required opt-in in the form of the bundle annotation must
explicitly use the encoding to pull in anything.

But this opt-in is in the wrong place, as I explain in the PR it's the meta-annotated annotation that needs to opt in, not the meta-annotation.

**Comment by cdelg** [comment]
Has this feature been implemented? I think there was another discussion about this somewhere, but I can't find it...

**Comment by rotty3000** [comment]
Please see https://bnd.bndtools.org/chapters/235-accessor-properties.html for a bnd specific solution.

**Comment by cdelg** [comment]
ah thanks! The mentioned discussion was in fact this documentation page.
