### ISSUE TITLE
References injected into constructor do not take the name of the parameter

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#3143]
When annotating a constructor with `@Activate` and some parameters of the constructor with `@Reference`, users might expect the name of those references to be taken from the respective parameters, as according a naive reading of the spec. Unfortunately the references names appear to be taken from *synthetic* parameter names.

I expect the reason for this is that the annotation processing is done against the class file? And parameter names are of course only an optional attribute and normally are not present unless the compiler is specifically asked to emit them...

But I believe that they *are* available to e.g. `javax.annotation.processing` annotation processors regardless, so I think fixing this should be at least theoretically possible, but may require that the processing of the DS annotations is done in a different way and at a different stage of the build.

Seems like it could be too-deep a change for too-little a payoff, just figured I'd throw it out there for someone with an understanding of the Bnd build pipeline to clarify. Cheers.

**Comment by bjhargrave** [comment]
You are correct in your assessment of the situation and in that it is too much work for too little pay-off to justify developing and maintaining annotation processors when the developer can either:

- Specify a reference name in the annotation; or 
- Simply add `-parameters` to their javac invocation to have the compiler add the `MethodParameters` attributes to the generated class files.

We do the latter for the test cases so we can test the constructor parameter names in the generated references:

https://github.com/bndtools/bnd/blob/be7783b0255ff6ef8d7a3c34aae5cdb723eef87f/biz.aQute.bndlib.tests/build.gradle#L1-L3

https://github.com/bndtools/bnd/blob/be7783b0255ff6ef8d7a3c34aae5cdb723eef87f/biz.aQute.bndlib.tests/.settings/org.eclipse.jdt.core.prefs#L28
