### ISSUE TITLE
bnd resolver doesn't consider multiple cardinality

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#3148]
I have 3 sample projects providing 2 capabilities -

```
1. Sample A - Provide-Capability: com.amitinside.module;capability=my_feature
2. Sample B - Provide-Capability: com.amitinside.module;capability=my_feature
3. Sample C - Provide-Capability: com.amitinside.module;capability=my_2nd_feature
```

I also have a project (`init.requirement`) providing the initial requirement for the launcher -

```
4. init.requirement - Require-Capability: com.amitinside.module;filter:="(capability=*)";cardinality:=multiple
```

If I add `init.requirement` project to the run requirements in bndrun, resolver should resolve all the projects but it does pick the first one it encounters during the resolution process.

For convenience, please find the sample workspace as mentioned below - 

Sample Workspace: https://github.com/amitjoy/bnd-resolver-issue

**Comment by rotty3000** [comment]
I don't believe the specification requires the resolver to find all available solutions in the case of multiple cardinality. It simply has to find _a valid_ solution.

However, I've been considering adding some flags to bnd's own resolver context that could instruct bnd to make the resolver to do a few more additional things, like:
* find all available matches in the multiple-cardinality scenario
* include as many successfully resolved optional requirements as possible
* perform a second resolution using the results of the first resolution _as the repo_ in an attempt to weed out multiple-conflicting matches (which is currently possible if you have a lower quality repository)

**Comment by amitjoy** [comment]
Hi @rotty3000, that sounds promising and the best fit for my scenarios. Do you have any probable timeline for the features to be available in bnd?

**Comment by rotty3000** [comment]
Unfortunately no. It's going to be best effort.

**Comment by glimmerveen** [comment]
I have a similar use case (discussed here [1]), where I expected to match multiple bundles using a single requirement, when assembling an application using the bnd-exporter-maven-plugin. I also ran into the issue that only one match is resolved, rather than all the matching bundles in scope (Maven dependencies in my case).

[1] https://groups.google.com/d/msg/bndtools-users/GbBEfGTG3BY/MCuaTuV9CAAJ
