### ISSUE TITLE
Better visualization and checking of errors in the repositories

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3154]
Currently  the repositories can sometimes ignore errors. we need to make errors visible in the repository view and not build when a repo has errors.

**Comment by kriegfrj** [comment]
It would also be nice if the "download source" and other download options showed progress feedback. Not sure if this belongs in this issue or if we fouls raise a separate issue for it.

**Comment by pkriens** [comment]
All downloads should be visible, including the source. The progress is handled through the Http Client and all code must use that.

I've got a branch for this but no time to finish it off
