### ISSUE TITLE
[reporter] Add a default set of Templates into bnd (cli)

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#3161]
bnd should provide some default Templates to generate MD files.

Uses Command:
'exportreport exportmd'

@cdelg  would it be okay to take your templates as base? 
I would add some "easy to copy code fragments" e.g "configurator json" and fix some bugs 

see https://github.com/bndtools/bnd/pull/3152

- generate List-Entrys every time in same order

**Comment by cdelg** [comment]
> would it be okay to take your templates as base?

Yes you can, see my comment on #3152

**Comment by cdelg** [comment]
The title suggests that the templates are embedded in the bnd cli, they are not. They will also be available from maven.
