### ISSUE TITLE
[cli]

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#3162]
When generating bundles via cli non-.class ressources does not exist in the bundle.
```
commands:
biz.aQute.bnd.jar **build**
biz.aQute.bnd.jar **_par**
```

**Comment by bjhargrave** [comment]
I have not idea what the issue is here. The subject line is non-descriptive and the body does not provide anywhere near enough information to describe a problem. Please improve this issue.

**Comment by stbischof** [comment]
Sorry, i made a PR parallel.  Saved Issue by accident.

**Comment by bjhargrave** [comment]
>  Saved Issue by accident.

OK, Closing then.
