### ISSUE TITLE
Null pointer from bnd-export-maven-plugin

### ISSUE THREAD

**Issue by belun** [bndtools/bnd#3172]
I am trying to setup a BND project starting with enRoute to run on ApacheFelix and OSGI 6.
I have tried to follow on the tutorials from enRoute and then customize them for OSGI 6.

I have a top project that is a generated as enRoute project and it has the enRoute dependencies and bnd maven plugins. I have added extra dependencies : osgi.core:6.0.0, org.apache.felix.gogo.runtime,shell,console

Also, there is a Maven module created as enRoute Application and that uses the top project as parent and imports the extra dependencies from there.

Running on jdk1.8.0_191.
The maven bundle have been setup with an archetypes from enRoute, my bnd.version is 4.1.0

After running mvn package on the module, I get some errors:

[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.1.0:export (default) on project arr-bus-protocol: null: MojoExecutionException: NullPointerException -> [Help 1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.1.0:export (default) on project arr-bus-protocol: null at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81) at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56) at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305) at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192) at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105) at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956) at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290) at org.apache.maven.cli.MavenCli.main(MavenCli.java:194) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) Caused by: org.apache.maven.plugin.MojoExecutionException at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:126) at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) ... 20 more Caused by: java.lang.NullPointerException at java.util.Hashtable.put(Hashtable.java:460) at aQute.bnd.osgi.Processor.setProperty(Processor.java:1679) at aQute.bnd.maven.export.plugin.ExportMojo.export(ExportMojo.java:165) at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:123) ... 22 more

Before this NullPointer, I see that bnd/maven is trying to collect dependencies and it does find my stuff : example.my-project.my-module, osgi.core, org.apache.felix.framework, org.apache.felix.gogo.shell, etc.

[DEBUG] my-module: adding resource javax.servlet-api version=3.1.0 [DEBUG] my-module: adding resource org.eclipse.jetty.http version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.io version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.util version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.jmx version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.security version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.webapp version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.xml version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.websocket.servlet version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.websocket.api version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.websocket.server version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.websocket.common version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.websocket.client version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.eclipse.jetty.client version=9.4.15.v20190215 [DEBUG] my-module: adding resource org.apache.commons.fileupload version=1.3.3 [DEBUG] my-module: adding resource org.apache.commons.io version=2.6.0 [DEBUG] my-module: adding resource org.apache.felix.http.servlet-api version=1.1.2 [DEBUG] my-module: adding resource org.apache.felix.framework version=6.0.2 [DEBUG] my-module: adding resource example.my-project.my-module version=1.0.0.201905020747 [DEBUG] my-module: list(null) [org.apache.felix.http.jetty, org.apache.servicemix.specs.jaxws-api-2.2, org.eclipse.osgi, org.apache.geronimo.specs.geronimo-stax-api_1.0_spec, org.apache.servicemix.specs.jaxb-api-2.2, org.eclipse.jetty.client, org.apache.felix.configurator, org.eclipse.jetty.security, org.apache.geronimo.specs.geronimo-saaj_1.3_spec, org.eclipse.equinox.event, org.osgi.service.event, org.apache.aries.javax.jax.rs-api, tx-control-provider-jdbc-xa, org.apache.felix.gogo.shell, org.apache.servicemix.specs.saaj-api-1.3, org.eclipse.jetty.io, org.apache.felix.http.servlet-api, jaxb-api, org.eclipse.jetty.servlet, osgi.core, org.apache.felix.framework, org.apache.servicemix.specs.annotation-api-1.3, org.eclipse.equinox.log.stream, org.apache.aries.jax.rs.whiteboard, javax.servlet-api, ch.qos.logback.classic, org.apache.felix.scr, example.my-project.my-module, org.eclipse.jetty.server, org.osgi.util.promise, org.osgi.service.http.whiteboard, org.osgi.service.jaxrs, org.apache.geronimo.specs.geronimo-activation_1.1_spec, ch.qos.logback.core, org.apache.commons.fileupload, org.eclipse.jetty.util, org.eclipse.jetty.jmx, org.eclipse.jetty.xml, org.apache.servicemix.specs.stax-api-1.0, org.eclipse.jetty.http, org.osgi.util.converter, org.apache.commons.io, org.apache.servicemix.specs.stax-api-1.2, tx-control-provider-jpa-xa, org.osgi.util.function, org.apache.servicemix.specs.activation-api-1.1, org.apache.felix.gogo.command, org.eclipse.jetty.websocket.common, org.apache.felix.configadmin, org.osgi.service.log, org.osgi.service.metatype, org.eclipse.equinox.metatype, org.eclipse.jetty.websocket.api, org.eclipse.jetty.websocket.servlet, org.apache.aries.jpa.container, org.eclipse.jetty.websocket.client, org.eclipse.jetty.websocket.server, org.apache.felix.gogo.runtime, org.osgi.service.jdbc, tx-control-service-xa, slf4j.api, org.eclipse.jetty.webapp, org.apache.aries.jpa.javax.persistence_2.1, org.apache.geronimo.specs.geronimo-osgi-locator, org.osgi.util.pushstream, org.apache.felix.webconsole]

Then Maven is trying to update the runbundles with an error :

[DEBUG] init [DEBUG] Line is empty, args=C:/workspace/my-project/my-module/target/tmp/export/my-module/cnf/cache/4.1.0/bnd-cache [DEBUG] Original -runbundles was: \ org.apache.felix.gogo.shell;version=1.0.0,\ org.apache.felix.gogo.runtime;version=1.0.10,\ org.apache.felix.gogo.command;version=1.0.2,\ org.apache.felix.webconsole;version=4.3.4,\ org.apache.felix.http.jetty;version=4.0.6,\ org.apache.felix.http.servlet-api;version=1.1.2 [DEBUG] Resolved -runbundles is: null

Original -runbundles was filled by me by hand as I was trying to help bnd.

**Comment by bjhargrave** [comment]
Bnd 4.1.0 is an older release. 4.2.0 is the current release and 4.3.0 is under development. Can you try to reproduce with the 4.3.0-SNAPSHOT? 

See https://github.com/bndtools/bnd/blob/master/maven/README.md#using-the-latest-development-snapshot-build-of-the-bnd-maven-plugins for how to use the SNAPSHOT builds of the Bnd maven plugins.

**Comment by belun** [comment]
with 4.3.0-SNAPSHOT, i run into other problems : the downloaded pom.xml seems to be a html page :)

> [ERROR] Plugin biz.aQute.bnd:bnd-maven-plugin:4.3.0-SNAPSHOT or one of its dependencies could not be resolved: Failed to read artifact descriptor for biz.aQute.bnd:bnd-maven-plugin:jar:4.3.0-SNAPSHOT: 1 problem was encountered while building the effective model
> [ERROR] [FATAL] Non-parseable POM C:\Users\repale\.m2\repository\biz\aQute\bnd\bnd-maven-plugin\4.3.0-SNAPSHOT\bnd-maven-plugin-4.3.0-SNAPSHOT.pom: end tag name </head> must be the same as start tag <link> from line 63 (position: TEXT seen ...sets/37601/201144/script.js?digest=360253048832"></script>\n</head>... @80:8)  @ line 80, column 8
> [ERROR] -> [Help 1]
> org.apache.maven.plugin.PluginResolutionException: Plugin biz.aQute.bnd:bnd-maven-plugin:4.3.0-SNAPSHOT or one of its dependencies could not be resolved: Failed to read artifact descriptor for biz.aQute.bnd:bnd-maven-plugin:jar:4.3.0-SNAPSHOT
	

the top of the pom.xml
> <!DOCTYPE html>
> <html dir="ltr" lang="en-US">
> <head>
>   <meta charset="utf-8" />
>   
> 
>   <title>DEV@cloud End of Life &ndash; CloudBees Support</title>

**Comment by bjhargrave** [comment]
> the downloaded pom.xml seems to be a html page

Uh, what repo URL are you using for the snapshot builds? You seem to be using the defunct cloudbees URL. https://github.com/bndtools/bnd/blob/master/maven/README.md#using-the-latest-development-snapshot-build-of-the-bnd-maven-plugins uses a jfrog URL.

**Comment by bjhargrave** [comment]
I will note that it seems that the NPE from Bnd 4.1 is not present in later version of Bnd and you are now on to how-to-use-the-bnd-maven-plugins questions which are more appropriate in the bndtools-users mail list rather than a github issue.

**Comment by bjhargrave** [comment]
Usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.
