### ISSUE TITLE
Bnd launcher: "Error: Could not find or load main class aQute.launcher.pre.EmbeddedLauncher" is back

### ISSUE THREAD

**Issue by JochenHiller** [bndtools/bnd#3176]
I am using Bndtools 4.3.0.DEV-201904301448-g1cb9908

It seems that the bug fixed in https://github.com/bndtools/bnd/issues/2947 is back again in 4.3.0 snapshot version.

I got the message `Error: Could not find or load main class aQute.launcher.pre.EmbeddedLauncher` from time to time when starting a bndrun configuration in IDE. Sometimes it did work after a restart of Eclipse,. sometime it sticks for some time.

To check if it is related to 4.3.0 version, I fixed the bndrun to use stable 4.2.0 version by adding
```
-runpath: biz.aQute.launcher;version='[4.2,4.3)'
```
and problem disappeared immediately again.

**Comment by rotty3000** [comment]
Another idea I'd like you to try is clearing out any pre-existing eclipse bnd run configurations. I thought I had made those work, but there are so many moving parts in this that maybe I missed it.

**Comment by JochenHiller** [comment]
I tried some ways to solve that issue:
* cleanup `cnf/cache` folder
* restart Eclipse
After doing that sometimes, it did work. I could _not_ figure out which steps in details solved the problem. Just cleaning cache only did not help.

**Comment by JochenHiller** [comment]
I tried to solve that problem to workaround by:
* cleanup `cnf/cache`
* restarting Eclipse
Cleanup cache only did not solve that issue. After some steps of clean/restart it did work again, but unfortunately I could not figure out which steps are needed to reliable solve it.

**Comment by JochenHiller** [comment]
I tried some ways to solve that issue:
* cleanup `cnf/cache` folder
* restart Eclipse
After doing that sometimes, it did work. I could _not_ figure out which steps in details solved the problem. Just cleaning cache only did not help.

**Comment by amitjoy** [comment]
@bjhargrave I just checked that clearing `cnf/cache/` doesn't help.

**Comment by JochenHiller** [comment]
I got that issue fixed, by updating from `4.3.0.DEV-201904301448-g1cb9908` to `4.3.0.DEV-201905062218-g735c647`.
Clean cache, restart Eclipse, everything does work again.

Sorry for bothering you with that issue.
