### ISSUE TITLE
"-runkeep:true" will not be considered during export as jar file

### ISSUE THREAD

**Issue by JochenHiller** [bndtools/bnd#3178]
We use a bndrun file which uses `-runkeep: true`.
We export that bndrun as launcher (both with gradle export:my.launcher and also with export to JAR inside bndrun editor).

We see in generated JAR file in launch.properties then `launch.keep=false` which does not reflect the `runkeep` option.
Setting it as a runproperty `launch.keep=true` does work well.

@pkriens FYI

**Comment by bjhargrave** [comment]
@rotty3000 Could this be related to your recent launcher changes?

@JochenHiller What version of Bnd is being used here? You fail to provide such details. Does this issue occur on Bnd 4.2.0?

**Comment by rotty3000** [comment]
.. it could! But we do have tests for export + launcher + runkeep.

Would it be possible to get a small git repo that reproduces the issue?

**Comment by JochenHiller** [comment]
Sorry my fault: I am using `4.3.0.DEV-201905062218-g735c647` version
I did not yet test it on bndtools 4.2.0 will do that later/tomorrow. Keep you updated

**Comment by pkriens** [comment]
Should be fixed in #3339

**Comment by JochenHiller** [comment]
Thanks for fixing it
