### ISSUE TITLE
regex needs double escape when coming from Gradle configuration

### ISSUE THREAD

**Issue by Vampire** [bndtools/bnd#3180]
When work-arounding #2227, I specified a regex for `-fixupmessages` in my Gradle Kotlin build file.
I wanted to target the exact error message to still get error messages for other classes.
This made it necessary to match an opening curly brace and a dot.
This should normally be `"^Classes found in the wrong directory: \\{META-INF/versions/9/module-info\\.class=module-info}$"`.
One backslash to escape the special character in the regex, and a second to escape the backslash from String processing.
But for the pattern to arrive properly at bnd, I need to double-escape it like `"^Classes found in the wrong directory: \\\\{META-INF/versions/9/module-info\\\\.class=module-info}$"`.
While this works of course, it is a bit unnice, as it reads harder and you cannot use IDE support for regexes in strings.

So currently I have to do
```kotlin
tasks.jar {
    withConvention(BundleTaskConvention::class) {
        bnd(mapOf(
                "-fixupmessages" to "^Classes found in the wrong directory: \\\\{META-INF/versions/9/module-info\\\\.class=module-info}$"
        ))
    }
```

where I would have expected to do
```kotlin
tasks.jar {
    withConvention(BundleTaskConvention::class) {
        bnd(mapOf(
                "-fixupmessages" to "^Classes found in the wrong directory: \\{META-INF/versions/9/module-info\\.class=module-info}$"
        ))
    }
}
```

I guess somewhere on the way from the build script to bnd one level of escaping is going lost wrongly.

**Comment by bjhargrave** [comment]
All Bnd instructions are key/value pairs in the properties file format. For consistency, any instructions to Bnd are processed through a properties file parser. This means that you need to ensure any escaping required by a properties file parser is present. Then, since you have a regex, you will further need any escaping required by your regex expression.

So this is as expected.
