### ISSUE TITLE
regression in `-includeresource` pattern matching

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3185]
Previous versions of bnd (at least 3.5.0) could match the following pattern to a file on the classpath:

`-includeresource: @biz.aQute.bndlib-[0-9]*.jar!/aQute/lib/filter/*`

However upgrading to recent versions loses this ability.

To be fair, I'm not even sure what the above `[0-9]*` translates to in terms of Java Patterns (w.r.t. to matching version that is). But it worked and it's all over our codebase :(

**Comment by bjhargrave** [comment]
It is not a regression per se, but a change to more properly handle regex like parts of the globbing expression.

Before the `[0-9]*` was translated to `[0-9].*` which means a single digit followed by anything. Now it is translated to `[0-9]*` which is zero or more digits.

```java
glob = new Glob("biz.aQute.bndlib-[0-9]*.jar");
System.out.println(glob.pattern()
	.toString()); // biz\.aQute\.bndlib-[0-9]*\.jar
assertFalse(glob.matcher("biz.aQute.bndlib-3.5.0.jar")
	.matches());
glob = new Glob("biz.aQute.bndlib-[0-9].*.jar");
System.out.println(glob.pattern()
	.toString()); // biz\.aQute\.bndlib-[0-9]\..*\.jar
assertTrue(glob.matcher("biz.aQute.bndlib-3.5.0.jar")
	.matches());
```

So if you change the `-includeresource` to 

```
-includeresource: @biz.aQute.bndlib-[0-9].*.jar!/aQute/lib/filter/*
```
(dot after right square bracket)

This should work in both old and new bnd versions.
