### ISSUE TITLE
bnd-indexer-maven-plugin Allow duplicated version

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#3195]
Using the  `bnd-indexer-maven-plugin` we cannot generate an index with multiple version of a same bundle, probably because maven resolves duplicate dependencies before the index is generated. Is it possible to get the full transitive dependencies before maven resolves duplicated versions and generate the index from this list.

**Comment by timothyjward** [comment]
> Is it possible to get the full transitive dependencies before maven resolves duplicated versions and generate the index from this list.

This isn't how Maven works, so the answer is "not really". You can have multiple maven projects which produce indexes, or multiple runs of the indexer in the same project. 

Depending on how you're using your index you may find that "local" indexing (i.e. indexing of dependencies in a folder) is more helpful. This is commonly used in conjunction with the dependency plugin or the assembly plugin (which is used to create the folder to be indexed).
