### ISSUE TITLE
Drag of private package uses -privatepackage and this is wrong

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3198]
Currently the dragging of a package to the private package view in bndtools uses the instruction `-privatepackage` instead of the former `Private-Package`. This is wrong because they have different semantics. The `-privatepackage` instruction is not exactly the same as `Private-Package`.  If only `-privatepackage` is used, the build will switch to use the Project's output directory.

I recall vaguely that the  `-privatepackage` was used to ignore the `@Export` annotation?

**Comment by bjhargrave** [comment]
> I recall vaguely that the `-privatepackage` was used to ignore the `@Export` annotation?

Opposite. `-privatepackage` honors the `@Export` annotation. `Private-Package` ignores the `@Export` annotation.

**Comment by pkriens** [comment]
Additionally:

* The behavior is now not well specified I think, I meet a lot of confused people. We need some docs to specify the default of the project's output directory and annotations.
* The drag & drop of the package on the Private Package view should cleanup the bnd file and use either -privatepackage (once it has the same semantics) or Private-Package

**Comment by bjhargrave** [comment]
> Opposite. `-privatepackage` honors the `@Export` annotation. `Private-Package` ignores the `@Export` annotation.

Oops. I was thinking of `-includepackage`. Never mind.

**Comment by bjhargrave** [comment]
I am not sure there is any difference between `-privatepackage` and `Private-Package`.

**Comment by pkriens** [comment]
-privatepackage presence does not prevent bnd to use the projet's layout instead of instructions. We need to add it to `ProjectBuilder.startBuild(...)`.
