### ISSUE TITLE
[bndtools] Adapt the Eclipse workspace automatically from the bnd workspace

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3199]
It would be really nice if the Eclipse workspace was automatically synced with the bnd workspace. I.e. if a project was added/removed from the file system it was automatically integrated with the Eclipse workspace.

**Comment by ViToni** [comment]
This would be highly appreciated. In my case I'm switching branches a lot so some projects come and go...

**Comment by kriegfrj** [comment]
👍 Ditto @ViToni 's comment.
