### ISSUE TITLE
biz.aQute.bnd.gradle packaging problem

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#3202]
The 4.3.0-snapshot version of `biz.aQute.bnd.gradle` doesn't contain the classes of `biz.aQute.bndlib` anymore and that's why the build fails with the following error message - 

```
* What went wrong:
A problem occurred evaluating settings 'com.qivicon.runtime'.
> aQute/bnd/build/Workspace
```

I had a look into it and found that it doesn't have the `aQute.bnd.build.Workspace`. In contrast to it, 4.2.0 version of `biz.aQute.bnd.gradle` does contain this class.

```
biz.aQute.bnd.gradle-4.3.0-20190516.084102-115.jar -  5,2 MB
biz.aQute.bnd.gradle-4.2.0-20181114.114238-2.jar -  8,7 MB
```

**Comment by bjhargrave** [comment]
`biz.aQute.bnd.gradle` for 4.2.0 does not include the bndlib classes. They were removed for 4.2 by https://github.com/bndtools/bnd/pull/2741.

`biz.aQute.bnd.gradle-4.2.0-20181114.114238-2.jar` is not the released version of 4.2. It must be some snapshot version.

To use `biz.aQute.bnd.gradle` 4.2.0 and later, you must make sure the buildscript has access to the dependencies of `biz.aQute.bnd.gradle`.

**Comment by bjhargrave** [comment]
Yes. You will need to make sure all the transitive dependencies of `biz.aQute.bnd.gradle` are available from what ever repositories you use for your buildscript.

**Comment by amitjoy** [comment]
Could you kindly tell me how I would know the list of bnd bundles `biz.aQute.bnd.gradle` internally requires?

**Comment by bjhargrave** [comment]
You can look at the pom in the jar to see the direct dependencies. Normal maven dependency rules apply since that is what gradle uses to provision the classpath for the plugin.

**Comment by pkriens** [comment]
I think you normally setup a 'learning proxy' to Maven central?

Kind regards,

	Peter Kriens

**Comment by amitjoy** [comment]
Actually we need the maximum DS version feature (which is in 4.3.0-SNAPSHOT) and that's why thought of using only a specific version. We can use jfrog directly but it will be volatile since gradle will always consume the latest snapshot and it might lead to some other problems which I want to avoid. As BJ said, I need to deploy all bnd bundles (of a specific version) to our Nexus repo and then we can consume them from our Nexus instance.

**Comment by pkriens** [comment]
That does suck :-( bndlib had no external dependencies but I hope the reporting deps did not get dragged in ....

**Comment by bjhargrave** [comment]
>$ ./gradlew :buildscriptDependencies
>
> Task :buildscriptDependencies
> bnd_plugin: biz.aQute.bnd:biz.aQute.bnd.gradle:+
> bnd_repourl: https://bndtools.jfrog.io/bndtools/libs-snapshot-local
> /Users/hargrave/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.bnd.gradle/4.3.0-SNAPSHOT/faf4dea3b0d3489046f610822074dbd041345ca6/biz.aQute.bnd.gradle-4.3.0-SNAPSHOT.jar:/Users/hargrave/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.resolve/4.3.0-SNAPSHOT/8142cb16b5880b623520abae650e196a5862f202/biz.aQute.resolve-4.3.0-SNAPSHOT.jar:/Users/hargrave/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.repository/4.3.0-SNAPSHOT/fb2d088704255cde636176c58215b4a7a5cb875f/biz.aQute.repository-4.3.0-SNAPSHOT.jar:/Users/hargrave/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.bndlib/4.3.0-SNAPSHOT/606bdcf682c7728f2709cb99f18bf07e1d2051ed/biz.aQute.bndlib-4.3.0-SNAPSHOT.jar:/Users/hargrave/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar

So you need `biz.aQute.bnd.gradle`, `biz.aQute.resolve`, `biz.aQute.repository`, `biz.aQute.bndlib`, and `slf4j-api-1.7.25`.

**Comment by amitjoy** [comment]
It is really helpful, BJ. Thanks a lot. 👍
