### ISSUE TITLE
Manual assignment of workingset gets undone by building

### ISSUE THREAD

**Issue by ViToni** [bndtools/bnd#3207]
For some work to be done I manually created a workingset and assgined projects to it as I didn't want to change all the bnd files for temporarily.
These projects had also an exisiting`-workingset` instruction. After building the the projects they got removed from the manully assigned working set.

Expected result:
Keep the manually assigned workingset.

I'm not an eclipse expert but this might be the reason:
https://github.com/bndtools/bnd/blob/42efbeefc9788bfbaccd89a4f20fae34fffc38c8/bndtools.builder/src/org/bndtools/builder/WorkingSetTracker.java#L59-L67

**Comment by bjhargrave** [comment]
If you are using the `-workingsets` instruction, then Bndtools will assign projects to working sets automatically during the execution of the incremental builder. If you want to manually assign working sets, then do not use or disable the `-workingset` instruction. You cannot have it both ways :-)

You can use macros in the `-workingset` instruction. See below for what is used in the OSGi build. So you can add the ability to disable the `-workingset` instruction  by setting some other Bnd property, system property or env var when you want to temporarily disable it.

```
-workingset = \
  Build;member=${filter;${p};cnf|licensed|osgi\\..*}, \
  Companion;member=${filterout;${p};cnf|licensed|osgi\\..*|org\\.osgi\\.(impl|test)\\..*}, \
  ReferenceImplementation;member=${filter;${p};org\\.osgi\\.impl\\..*}, \
  ComplianceTests;member=${filter;${p};org\\.osgi\\.test\\..*}
```

**Comment by ViToni** [comment]
Not convinced that "one bnd to rule them all" would make for everybody's favourite.
Also not really sure this macro would really make my life easier...
