### ISSUE TITLE
Gradle parallel builds and Analyzer Plugins

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3209]
I suspect that a DS bug that caused random version assignments is a concurrency bug. Now bnd is not ready to run parallel but the client indicated they run it in parallel. Need to discuss how we protect against this

**Comment by ViToni** [comment]
Might be related to #2801

**Comment by bjhargrave** [comment]
Bnd plugins are singleton objects in the Workspace. They need to be careful to avoid instance variables which change based upon the project being built. 

We need to spend some time to analyze the plugins for this and fix.

**Comment by bjhargrave** [comment]
MetaypeAnnotations needs to be fixed.

**Comment by bjhargrave** [comment]
I looked through the Analyzer and Verifier plugins and only found that MetatypeAnnotations needed fixing.

**Comment by bjhargrave** [comment]
The DS annotations processing was fixed by https://github.com/bndtools/bnd/pull/3208.

I think we are done with this issue, so I will close.
