### ISSUE TITLE
macro: Add a macro to convert maven groupId and artifactId to bsn

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#3211]
Could we add a macro that given a maven groupId and artifactId return a bsn (`tobsn`)?

From https://maven.apache.org/guides/mini/guide-naming-conventions.html, groupId shoud follow Java's package name rules such as `topDomain.domainName.productName`. ArtifactId are often dash separated words, and sometimes with the product name at the beginning, such as `producName-otherName`.

We could have something like that:
* ` groupId` + `artifactId` = `bsn`
* `topDomain.domainName.productName` + `productName` = `topDomain.domainName.productName`
* `topDomain.domainName.productName` +  `otherName` = `topDomain.domainName.productName.otherName`
* `topDomain.domainName.productName` +  `productName-otherName` = `topDomain.domainName.productName.otherName`
* `topDomain.domainName.productName` +  `otherName-anotherName` = `topDomain.domainName.productName.otherName.anotherName`

I can make a PR for this.

**Comment by bjhargrave** [comment]
I am very unclear what you are asking for here. Can't you just do `bsn = ${groupId}.$(replace;${artifactId};-;.}`, if that is what you want? 

My opinion is that bsn should be the same as artifactId. This is what we do in the OSGi build and also in the Bnd build. The simple artifactIds used by many artifacts make the jars names too non-specific when not in a maven repo. So I don't think Bnd should add some macro which promotes simple artifactId naming.

**Comment by cdelg** [comment]
> I am very unclear what you are asking for here. Can't you just do bsn = ${groupId}.$(replace;${artifactId};-;.}

In addition, to remove the duplicated `productName` in case it is present at the end of the groupId and at the start of the artifactId.

```java
List<String> bsn = Strings.split("\\.", myGroupId);
List<String> artifactId = Strings.split("-", myArtifactId);

if (!bsn.isEmpty() && !artifactId.isEmpty() && bsn.get(bsn.size() - 1)
	.equals(artifactId.get(0))) {
	artifactId.remove(0);
}

bsn.addAll(artifactId);

return Strings.join(".", bsn);
```

> My opinion is that bsn should be the same as artifactId...

This was because my company uses the `topDomain.domainName.productName` + `productName-otherName` convention to name maven and eclipse projects. But indeed, I didn't think that the too non-specific jar names could then be a problem when bundles are not in a maven repo.

Thanks for considering this issue.
