### ISSUE TITLE
`org.openjfx:javafx-base:13-ea+8` and friends are not working via the MavenBndRepository

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3214]
The maven model for these artifacts seems to present a challenge for MavenBndRepository in that it's not able to get artifacts for these from maven central.

https://repo1.maven.org/maven2/org/openjfx/

**Comment by bjhargrave** [comment]
If I put `org.openjfx:javafx-base:13-ea+8` into a MavenBndRepository index file, it provides access to the jar.

1. That jar is empty (except for a trivial manifest). You need one of the classified jars for a specific platform. For example `org.openjfx:javafx-base:jar:mac:13-ea+8` which is the jar for the macOS platform. See https://repo.maven.apache.org/maven2/org/openjfx/javafx-base/13-ea+8/ for the various classified jars available.
2. The maven version `13-ea+8` is converted to the OSGi version `13.0.0.ea8` by Bnd. The character `+` is no legal in an OSGi version qualifier, so it is removed. So you will need to use the converted version in any bnd file.

Is there something else I am missing?

**Comment by rotty3000** [comment]
You are correct on all points. You likely have to include all of the various system specific jars into your repo and use some bnd macro + OS detection magic in order to get a working system.
