### ISSUE TITLE
Infinite automatic build loop in Eclipse when overriding resources in POM

### ISSUE THREAD

**Issue by wborn** [bndtools/bnd#3220]
After migrating openHAB from PDE to bnd (4.2.0) one of the remaining issues (https://github.com/openhab/openhab2-addons/issues/5554) is that Eclipse (2019-03) is in an infinite build loop when we enable "Project -> Build Automatically".

After investigating the issue it seems to be caused by the resource definitions in our Maven POMs:

* [openhab-core](https://github.com/openhab/openhab-core/blob/7d374a951f52742a19d96b234f822c9995a03510/pom.xml#L142-L153)
* [openhab2-addons](https://github.com/openhab/openhab2-addons/blob/317cbb58a0273445548b479b8cf1b5c2ec9cbf2b/pom.xml#L122-L135)
* [openhab-webui](https://github.com/openhab/openhab-webui/blob/dcf9eb5c2bda12b01026efdb2ee05382e581a557/pom.xml#L70-L81)

After removing these customizations and updating the Maven projects in Eclipse the infinite loop is resolved. Do you think this loop is caused by an issue in bndtools?

I was able to reproduce the issue on the simpler [bndtools/jpmcli](https://github.com/bndtools/jpmcli) project by adding a similar resources definition in https://github.com/wborn/jpmcli/commit/d1efa6168553af656189a034a50fe7621b7da8ce.

**Comment by IOOOTAlan** [comment]
Is this related to #3201?

**Comment by wborn** [comment]
It looks like different issue to me because it's about invoking Maven from the CLI and the POM in the example [maggu2810/bnd-resolvebug](https://github.com/maggu2810/bnd-resolvebug) project doesn't contain such resource definitions.

**Comment by wborn** [comment]
As a test I also checked if the issue can be reproduced on a simple Maven project (not using bnd) with such a resource definition. There is no build loop when using "Build Automatically" after importing this [hello-world-bnd-3220](https://github.com/wborn/hello-world-bnd-3220) project in Eclipse. So it's probably not an Eclipse or m2e issue.

**Comment by rotty3000** [comment]
As a workaround, is the problem solved by using this approach instead?
in bnd:
```
-includeresource: -${.}/NOTICE, -${.}/*.xsd
```

**Comment by wborn** [comment]
Thanks for the suggestion @rotty3000. I was already thinking about using such a workaround and so far it seems to work after testing it. :+1:

**Comment by rotty3000** [comment]
Great, as long as we can keep you moving forward! :)
