### ISSUE TITLE
Prevent Local Repo OBR to update increment attribute

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#3245]
Hi,

I am thinking if it is possible to not update the increment attribute value of the local OBR XML (in LocalIndexedRepo) if there is no change in the repo contents. When all repositories are refreshed, the increment attribute value gets changes even if the repo contents are the same.

<img width="893" alt="Bildschirmfoto 2019-06-13 um 11 14 53" src="https://user-images.githubusercontent.com/13380182/59420101-883c2a80-8dcc-11e9-8aea-30fdf5153ce9.png">

Thanks and Regards,
Amit

**Comment by bjhargrave** [comment]
I think @pkriens already fixed this in 55df5428671c98e5f2f6b501cb0280fdf17a2633.
