### ISSUE TITLE
bnd distro incorrect package versions

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3246]
If the order in which two versions of a package appear are:

```
osgi.wiring.package=org.osgi.service.log, version=1.4.0
...
osgi.wiring.package=org.osgi.service.log, version=1.3.0
```

1.3 overwrites 1.4, losing that capability.

**Comment by pkriens** [comment]
It helps to use a ';' between the name and the version?

**Comment by rotty3000** [comment]
that output is just for illustration, it's the `toString` output observed while debugging that' all.
