### ISSUE TITLE
Import-Package needs extra character (?)

### ISSUE THREAD

**Issue by J-N-K** [bndtools/bnd#3251]
In one of my projects (https://github.com/J-N-K/openhab-osgiify/pull/2) the .bnd-file for wrapping com.squareup.retrofit/retrofit contains

```
Import-Package: \\
  android.*;resolution:="optional", \\
  com.google.appengine.api.urlfetch.*;resolution:="optional", \\
  org.apache.http.*;resolution:="optional", \\
  rrx.*;resolution:="optional", \\
  *
```

results in a MANIFEST.MF

```
Import-Package: android.net.http;resolution:=optional,android.os;resol
 ution:=optional,android.util;resolution:=optional,com.google.appengin
 e.api.urlfetch;resolution:=optional,org.apache.http;resolution:=optio
 nal,org.apache.http.client;resolution:=optional,org.apache.http.clien
 t.methods;resolution:=optional,org.apache.http.entity;resolution:=opt
 ional,org.apache.http.impl.client;resolution:=optional,org.apache.htt
 p.message;resolution:=optional,org.apache.http.params;resolution:=opt
 ional,org.apache.http.util;resolution:=optional,rx;resolution:=option
 al,rx.subscriptions;resolution:=optional,com.google.gson,com.squareup
 .okhttp,okio,retrofit;version="[1.9,2)",retrofit.android;version="[1.
 9,2)",retrofit.appengine;version="[1.9,2)",retrofit.client;version="[
 1.9,2)",retrofit.converter;version="[1.9,2)",retrofit.http;version="[
 1.9,2)",retrofit.mime;version="[1.9,2)"
```

The first character of `rrx.*` is stripped and results in `rx` in the manifest. If I put `rx.*` in the .bnd-file, it results in `x` in the manifest. This is at least unexpected and should be documented.

**Comment by rotty3000** [comment]
First off, why is there double backslash (`\\`) everywhere in your bnd files? You don't need that and it might actually be causing issues. So first remove all those (even from the inline `<bnd>` elements in the poms.)

**Comment by J-N-K** [comment]
Well. That somehow works. If I only remove the `\\`, there are a lot of complaints about

```
[WARNING] C:\Users\Jan\openhab-master2\git\openhab-osgiify\com.squareup.retrofit.retrofit\osgi.bnd [5:62]: Invalid property key: `com.google.appengine.api.urlfetch.*;resolution`: <<  com.google.appengine.api.urlfetch.*;resolution:="optional>>
[WARNING] C:\Users\Jan\openhab-master2\git\openhab-osgiify\com.squareup.retrofit.retrofit\osgi.bnd [6:44]: Invalid prope>>y key: `org.apache.http.*;resolution`: <<  org.apache.http.*;resolution:="optional",
[WARNING] C:\Users\Jan\openhab-master2\git\openhab-osgiify\com.squareup.retrofit.retrofit\osgi.bnd [7:32]: Invalid prope>>y key: `rrx.*;resolution`: <<  rrx.*;resolution:="optional",
[WARNING] C:\Users\Jan\openhab-master2\git\openhab-osgiify\com.squareup.retrofit.retrofit\osgi.bnd [9:30]: No value specified for key: *. An empty value should be specified as '*:' or '*=': <<  *
```

If I also remove all line breaks, I get the expected result. But 

```
Import-Package: android.*;resolution:="optional",com.google.appengine.api.urlfetch.*;resolution:="optional",org.apache.http.*;resolution:="optional",rx.*;resolution:="optional",*
```

is a lot harder to read than having one line per package.

**Comment by rotty3000** [comment]
@J-N-K hmm, that's really weird. That message comes from `aQute.lib.utf8properties.PropertiesParser` but why it's misinterpreting your bnd files I can only guess.

**Comment by J-N-K** [comment]
Mhm. I'm on a Windows system and my linebreak is `\r\n`. Maybe it's different on *nix-systems?

**Comment by bjhargrave** [comment]
You need a single `\` to continue the line. A double `\\` is a problem.

**Comment by rotty3000** [comment]
Using windows line endings should be safe, but for the sake of argument, if you switch to unix line endings (`\n`), and return to multiline using single `\` does that eliminate the `Invalid property key` issues?

**Comment by J-N-K** [comment]
See my edit above: a single `\` works with Windows line endings. The errors are without any backslash (that‘s what I read from your comment above). So my guess is that in the case of `\\` the first is interpreted as line continuation and the second merges with the `r`  to `\r`, which makes the `r` disappear. It works for other characters as first characters because they don‘t form escape sequences.

**Comment by rotty3000** [comment]
ah sorry for the confusion, when I said:

> remove all those

I really meant

> remove all those double `\\` and replace with single `\`

:)
