### ISSUE TITLE
EclipseOxygen cache getting cleared on startup

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3256]
This picks up an issue that I raised on the developer mailing list.

While working on the Bnd workspace in Eclipse using Bndtools, I've noticed that every time I restart Eclipse, it ends up re-downloading the entire Eclipse Oxygen repository. There are other occasions while running that it seems to start re-downloading it all too. This triggers automatic rebuilds, which in turn fail because the dependencies are missing. This then requires rebuilding some/most/all of the workspace from scratch. Which involves a lot of idle time.

So far as I know, the EclipseOxygen repo hasn't changed since 22nd of March 2019, when it was first set up (5eb68b0d269851eb5b6aace5a5520983128ef5b7). It certainly isn't changing as much or as frequently that it would need to be re-downloaded every time I start Eclipse (and other times in-between).

I have manually verified by:
1. Opening the cnf/cache/stable/EclipseOxygen directory in Windows Explorer.
2. Starting Eclipse.
3. Watching the directory as Eclipse starts.

There is a point during Eclipse startup where the EclipseOxygen directory is completely emptied. Hence the need to re-download everything.

It seems that this isn't happening for other contributors (@bjhargrave confirmed on the mailing list that it doesn't happen for him), so it could be that this is a Windows-specific problem. This is wasting enough of my time that it would probably be good to invest some time trying to find/fix it (given that it only seems to be happening for me, it might be hard for others to reproduce).

A couple of workarounds for anyone who runs into this issue and can't wait for my fix:
* Wait until the entire repository is refreshed, then switch to offline mode. Seems to stop it from happening.
* Possibly revert your local working copy of repositories.bnd to use the P2 repositories (the site instability of the P2 sites is likely to be less of an issue for your local working purposes than for the CI environment).

**Comment by kriegfrj** [comment]
> Wait until the entire repository is refreshed, then switch to offline mode. Seems to stop it from happening.

Update: I've just noticed that this doesn't stop the cache from being cleared on restart. It may stop it from happening while Eclipse is still running though.

**Comment by kriegfrj** [comment]
Ok, I think I've tracked it down. (Note: From what I have discovered, I don't believe that this is a Windows-specific bug.)

1. `RepositoriesView.createPartControl()` starts a background job which calls `Central.refreshPlugins()`: https://github.com/bndtools/bnd/blob/1d9d5f56c75834123d09b258c02c748798fefb49/bndtools.core/src/bndtools/views/repository/RepositoriesView.java#L479-L490
2. `Central.refreshPlugins()` iterates through all `Refreshable` plugin instances and invokes `refresh()` on each.
3. `OSGiRepository.refresh()` calls `this.getIndex(true)`.
4. `OSGiRepository.getIndex(true)` in turn deletes the entire cache directory:  https://github.com/bndtools/bnd/blob/1d9d5f56c75834123d09b258c02c748798fefb49/biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java#L121-L123

I have confirmed that closing and re-opening the Repositories view in Bndtools also triggers this behaviour (which is the likely explanation as to why this was sometimes happening in my running Eclipse instance as well as at startup - I do sometimes close the Repositories window temporarily).

The `refresh()` implementations of the other `Repository` implementations do not appear to be so aggressive at clearing their caches. I looked briefly at `P2Repository` and `MavenBndRepository`, and I think that their `refresh()` implementations simply refresh the *index*, not all of the downloaded bundles. It would be good if `OSGiRepository`'s `refresh()` implementation were a bit smarter.

1. Download the latest index file.
2. Walk the index and Bnd cache in parallel, delete any bundles that are out-of-date or no longer in the index.

**Comment by pkriens** [comment]
Yes, that sounds too aggressive. We could add a menu entry for this aggressive clearing of the cache but the default refresh should imho not clear it.

**Comment by bjhargrave** [comment]
I think there is a blurring of the term "refresh" Bndtools/Eclipse may want to refresh the view while someone else may want to redownload the repository contents. If someone clicks a refresh button in the UI, I can imagine that the clearing of the cache and redownload of the contents are in order. But Bndtools should be calling refresh just because it feels like it. I think it is plainly wrong for Bndtools to simply call refresh in all repositories with out a human request. Bndtools is overly aggressive in this matter and should be fixed.

**Comment by pkriens** [comment]
I think I prefer to make all the refresh implementations lightweight and add menu entries for a heavy weight. I think refresh today is more 'see if you can find some new stuff' instead of clearing caches.

**Comment by bjhargrave** [comment]
But this "lightweight" refreshing you refer to means what? For the repo implementations what are they to do for lightweight refreshing?  How will repo implementations be called to do "heavyweight" refreshing? I think we need some discussion here to decide what is actually needed and how to proceed.

**Comment by kriegfrj** [comment]
> I think I prefer to make all the refresh implementations lightweight and add menu entries for a heavy weight. I think refresh today is more 'see if you can find some new stuff' instead of clearing caches.

I concur. I think this is analogous to automatic/incremental building vs "clean project" or "clean workspace". Eclipse will happily go and to the former, but the latter requires user intervention and is usually a last resort when things have gone wrong that shouldn't have or that the automatic incremental builder didn't anticipate/can't recover from.

**Comment by pkriens** [comment]
snapshots for maven should be refreshed. Checking if the index file is changed. etc.

**Comment by kriegfrj** [comment]
> But this "lightweight" refreshing you refer to means what? For the repo implementations what are they to do for lightweight refreshing? How will repo implementations be called to do "heavyweight" refreshing? I think we need some discussion here to decide what is actually needed and how to proceed.

I think it's a good idea to make sure that the definitions of the "lightweight" vs "heavyweight" are specified/fleshed out a bit so that the repository implementations have a clear idea of what they are trying to implement, and we don't end up with similar inconsistencies again between in the future.

To my mind, "lightweight" refreshing would be like an incremental refresh - it assumes that the index/cache are in a consistent state, and updates that state with any changes that may have happened upstream. It can happen automatically.

"Heavyweight" refreshing would be like the "clean project" or "clean workspace" - a manual fallback that the user can use when the incremental refresh gets things wrong or the cache gets irreparably polluted. It doesn't even necessarily need to re-download the bundles - eg, in the case of `OSGiRepository`, this will happen on-demand automatically when the Bnd projects call upon the repository for their dependencies.

For that matter, not all repository implementations would even need or benefit from a heavyweight implementation (eg, any implementation that indexes files on the local file system in-place, like `MavenBndRepository` probably or `LocalIndexRepo`).

In the case of `OSGiRepository`, incremental refresh would probably do as I suggested in an earlier post: download the most recent version of the index. It could do a timestamp/MD5 comparison with the local cached version of the index and if no change, then it's done. It would then possibly re-build the in-memory model of the repository index from the index file. Otherwise, it iterates through the cached bundles and deletes any bundles that are out-of-date. Or something like that.

**Comment by pkriens** [comment]
I think we should specify the current refresh() on the RepositoryPlugin to require lightweight. Any repository that needs a heavy weight should provide actions which will show up as a menu on the repo.

**Comment by kriegfrj** [comment]
Could it be as simple as changing `OSGiRepository.refresh()` to call `getIndex(false)` rather than `getIndex(true)`?

**Comment by pkriens** [comment]
Yup :-)

**Comment by bjhargrave** [comment]
> I think we should specify the current refresh() on the RepositoryPlugin to require lightweight.

Looking at the ``Refreshable` interface which defines the `refresh()` method, I see the following users:

- `bnd refresh` command. I assume using this command should result in a "heavyweight" refresh, otherwise it is not too useful.
- BndPomRepository and MavenBndRepository call it in their poll method. I assume this should be "lightweight".
- Central calls it in `refreshPlugins` and `refreshPlugin`. I guess these should be "lightweight".

**Comment by bjhargrave** [comment]
> I think we should specify the current refresh() on the RepositoryPlugin to require lightweight.

Looking at the ``Refreshable` interface which defines the `refresh()` method, I see the following users:

- `bnd refresh` command. I assume using this command should result in a "heavyweight" refresh, otherwise it is not too useful.
- BndPomRepository and MavenBndRepository call it in their poll method. I assume this should be "lightweight".
- Central calls it in `refreshPlugins` and `refreshPlugin`. I guess these should be "lightweight".

**Comment by pkriens** [comment]
For now i've changed the major culprit #3263. Lets try it out

**Comment by pkriens** [comment]
I am going to assume this bug is fixed in https://github.com/bndtools/bnd/commit/d4d99c3e24a0c1fe3ed7d6520e3f7adffc017832
