### ISSUE TITLE
bndpackage ant task leaves empty temporary launch properties files behind

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#326]
like

```
launch1576427089125257308.properties
```

**Comment by fhuberts** [comment]
Still the case on bnd 3.0.0

Git-Descriptor: 3.0.0.REL
Git-SHA: 0ac3b76c9bd573dfc30cbeaa53700c13ee5187d0

Please fix this, it's polluting the workspace.
Shouldn't be too hard to do.

**Comment by bjhargrave** [comment]
I am only seeing these launch*.properties files in generated folders which are output folders.

**Comment by fhuberts** [comment]
Yes, but these files are empty: stray.
The real files are in the exported bundles.
These stray files seem to result from leaks or so, I dunno

**Comment by fhuberts** [comment]
They pollute the output folder

**Comment by fhuberts** [comment]
Still the case on bnd 3.3.0.REL

**Comment by fhuberts** [comment]
So it's also the gradle export task; basically the bnd export functionality does this

**Comment by fhuberts** [comment]
tnx
