### ISSUE TITLE
Bnd Resolver Not Showing Unresolved Requirements

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#3270]
Hi,

The newest snapshot version of bnd doesn't show any window informing about unresolved requirements. That is, if we have a bunch of initial requirements in a bndrun file and if we click on `Resolve` button, bnd used to show the resolved dependencies if all requirements are satisfied or the unresolved requirements.

According to the current snapshot version, bnd can only show the window if all requirements can be resolved. If any of the requirements cannot be resolved by clicking on `Resolve` button, it does encounter NPE as shown below.

<img width="358" alt="Bildschirmfoto 2019-06-19 um 01 25 51" src="https://user-images.githubusercontent.com/13380182/59726246-331b7100-9231-11e9-97a0-ae1eca38ffc3.png">

**Comment by pkriens** [comment]
Please provide the details and possible a bndrun example?

**Comment by amitjoy** [comment]
Fixed by https://github.com/bndtools/bnd/pull/3265
