### ISSUE TITLE
bnd-maven-plugin --META-INF/MANIFEST.MF file is not getting generated

### ISSUE THREAD

**Issue by arcsinnovate** [bndtools/bnd#3276]
Hi,
 I am using the 4.1.0 version of bnd-maven-plugin with the maven-jar-plugin v3.0.2 to generate the bundles.
The issue i am facing is that when try to package with maven, the JAR plugin complains that there is no Manifest
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.0.2:jar (default-jar) on project PLATFORM-Commons-jdk12: Error assembling JAR: Manifest file: C:\DATA\lr\18\POC2\PLATFORM-Commons\target\classes\META-INF\MANIFEST.MF does not exist. -> [Help 1]

Given below is my pom file:

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.8.1</version>
					<configuration>
						<release>11</release>
					</configuration>
				</plugin>
				<plugin>
					<groupId>biz.aQute.bnd</groupId>
					<artifactId>bnd-maven-plugin</artifactId>
					<version>4.1.0</version>
					<executions>
						<execution>
							<goals>
								<goal>bnd-process</goal>
							</goals>
						</execution>
					</executions>
					<dependencies>
						<dependency>
							<groupId>biz.aQute.bnd</groupId>
							<artifactId>biz.aQute.bnd.reporter</artifactId>
							<version>4.1.0</version>
						</dependency>
						<dependency>
							<groupId>org.objectweb.asm</groupId>
							<artifactId>org.objectweb.asm</artifactId>
							<version>3.3.1.v201105211655</version>
						</dependency>
						<dependency>
							<groupId>org.objectweb.asm</groupId>
							<artifactId>tree</artifactId>
							<version>3.1</version>
						</dependency>

					</dependencies>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.0.2</version>
					<configuration>
						<archive>
							<manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
						</archive>
					</configuration>
				</plugin>

Please can anyone help why i am facing this issue. I am using open jdk 11.
I have even tried process-classes goal separately. But there is no luck. The plugin does not generate Manifest.MF

**Comment by bjhargrave** [comment]
Why do you have the biz.aQute.bnd.reporter, org.objectweb.asm, tree dependencies for the bnd-maven-plugin plugin? It does not need or use those dependencies. I would remove them from the pom.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by bjhargrave** [comment]
No response.
