### ISSUE TITLE
bnd-maven-plugin: Quoted string used on BundleDescription header values

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#3282]
Although quoted strings are valid according to https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.common.header.syntax and https://osgi.org/specification/osgi.core/7.0.0/ch01.html#framework.general.syntax, they seem not to be unquoted for e.g. the `BundleDescription` values. Once I have a value like

```
BundleDescription: "Some Description"
```

the value will be exposed in the e.g. Felix Web Console with the quotes `"Some Description"` instead of just the value `Some Description`.

**Comment by kwin** [comment]
@bjhargrave Can you point me to the right chapter in the spec which clearly states, where quoted strings are allowed and where they shouldn't be used? To me it is not obvious when looking at the spec  in https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#i2654895

**Comment by bjhargrave** [comment]
Is there a bug in Bnd here? Or are you just asking a question which should be better asked in the bndtools-users mail list?

**Comment by kwin** [comment]
bnd-maven-plugin generates the BundleDescription value as quoted string which is not unquoted in Apache Felix. I am not sure when reading the specs whether this is a bug when producing the header (i.e. in bnd-maven-plugin) or when reading the header (i.e. in the Felix Web Console).

**Comment by pkriens** [comment]
Bundle-Description has no structure and should therefore not be quoted. 

See example 3.2.1.7 

Kind regards,

	Peter Kriens

**Comment by kwin** [comment]
@pkriens Thanks. Is there an explicit section apart from the examples in 3.2.1 which state which bundle header parts may be quoted and which parts shouldn't?

**Comment by bjhargrave** [comment]
> bnd-maven-plugin generates the BundleDescription value as quoted string

You added the code which quoted it:

https://github.com/bndtools/bnd/commit/50736971904285106a5352e8c6a26619e0a1fddc#diff-4582ac9ba70cf3ab82ebaee74bd790d2R318

You should probably make a PR to remove the quoting.

**Comment by bjhargrave** [comment]
> Is there an explicit section apart from the examples in 3.2.1 which state which bundle header parts may be quoted and which parts shouldn't?

If the header does not define a specific syntax, then it is free form.

**Comment by rotty3000** [comment]
https://github.com/bndtools/bnd/blob/master/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java#L320

**Comment by kwin** [comment]
@bjhargrave Will come up with a PR which fixes this. 

I am still not sure about other headers, e.g. `BundleLicense` (defined in 3.2.1.11, https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#i26548950): The syntax boils down to `string` and `<url>` and both are not defined in 1.3.2 either. Also there is no example including a description, so it is not clear whether there you can use quoted strings.

**Comment by bjhargrave** [comment]
The other headers look fine since you do not quote them in their entirety. 

For headers with a grammar, you will need to quote parts of the header which can confuse parsing. So a string which has a comma or semicolon would confused parsing. 

Bundle-Description, Bundle-Vendor, Bundle-Name are just human readable text and have no specific grammar. So no quoting is necessary since no framework would try and parse them.

**Comment by pkriens** [comment]
The rules for all this should imho be in BndEditoModel that has formatters for all headers.

Can't you not reuse those? Careful, because bnd itself is way more liberal than OSGi and will auto quote parts in headers when they can be confusing.

Kind regards,

	Peter Kriens

**Comment by kwin** [comment]
@pkriens Indeed there are other issues, I just tried a description with an  empty line in it and it does not properly get escaped. I will create another bug for that.

**Comment by pkriens** [comment]
I think an empty line should be trimmed?
