### ISSUE TITLE
bnd-maven-plugin: Correctly escape new lines in bundle headers

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#3285]
If e.g. a description with an an empty new line is given in the pom.xml that empty new line is currently just stripped from the `BundleDescription` header but it should be kept and escaped according to the multi line rules from the Manifest spec (https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#JAR_Manifest).

**Comment by kwin** [comment]
According to @pkriens in https://github.com/bndtools/bnd/issues/3282#issuecomment-505481204 the according formatters should be reused which are also referenced in `BndEditModel`.

**Comment by kwin** [comment]
Currently the description 
```
<description>first line
    
second line
</description>
```

Is translated into
```
Bundle-Description: first line second line
```

i.e. the empty line is stripped and the other newline is converted to a space. This is rather unexpected to me, as the Manifest spec at https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#JAR_Manifest clearly allows multiline values.

But once I use the `NewlineEscapedStringFormatter` to convert the value before passing it to `Builder.setProperties(...)` the newline get escaped internally by bnd, i.e. I get
```
Bundle-Description: first line\n\ 	\n\ 	second line
```

@pkriens @bjhargrave  What is the correct way to enforce multiline values in the manifest when using `Builder.setProperties(...)`?

**Comment by pkriens** [comment]
Hmm, the BndEditModel formatters focus on the bnd properties format. 

The setProperties should take an actual String object with the actual value. I.e. the properties never contain escaped characters, they can contain line feeds, etc. In general the Bundle-Description is just the value of the Bundle-Description property of the builder.

The XML element should take its content and then store it in the  Builder property after any XML unescapes. I.e. the string should be clean and unencumbered with any formatting.

Kind regards,

	Peter Kriens

**Comment by kwin** [comment]
>>> The setProperties should take an actual String object with the actual value. I.e. the properties never contain escaped characters, they can contain line feeds, etc.

Ok, do we have a bug then in bnd as empty lines are stripped and new lines converted into space?

**Comment by pkriens** [comment]
Well, I would assume the value is trimmed since most whitespace at the edges is not intended and generally a bad idea because they are there but hard to spot.

I guess you should take the new lines embedded in the text in the XML and put them in the property. The bnd properties allow the \n as well.

Kind regards,

	Peter Kriens

**Comment by bjhargrave** [comment]
> Currently the description
> 
> ```
> <description>first line
>     
> second line
> </description>
> ```
> 

What is the value returned by `MavenProject.getDescription()`?

**Comment by kwin** [comment]
`first line\n\nsecond line\n`

**Comment by bjhargrave** [comment]
See `Jar.clean(Manifest org)`. It is called when writing the Manifest and calls `Jar.clean(String s)` to clean each value of a manifest header. It seems to be converting all adjacent new line characters into a single space. This was added in Bnd 2.3 by https://github.com/bndtools/bnd/commit/f9f7e30590adee6395b702b970a9d4308c3807d9. So it would appear that this is expected behavior.

**Comment by kwin** [comment]
@bjhargrave Thanks for the explanation. Closing it here then.

**Comment by bjhargrave** [comment]
> This was added in Bnd 2.3

Actually, this behavior is from all the way back in 1.12 via https://github.com/bndtools/bnd/commit/6d7cc12769a89750517d742646c5d8dac88bf9cc which was around the time of the initial commit for this git repo.
