### ISSUE TITLE
Strict check for versioned imports expects version on JRE packages

### ISSUE THREAD

**Issue by malnormalulo** [bndtools/bnd#3304]
When `-strict` is enabled, an error is raised whenever the project imports a package without specifying a version. There is a little bit of leeway given for javax packages, which generally are provided by the container:
https://github.com/bndtools/bnd/blob/b46bf533a38c7a7ef1ed9f39b45c5dfb4aca55a2/biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java#L755

This check does not give similar leeway to other JRE packages like org.w3c.dom and org.xml.sax, although the same justifications can apply to them.

**Comment by bjhargrave** [comment]
Can you work on a PR to fix this?
