### ISSUE TITLE
A uses directive should be provided for osgi.service capabilities

### ISSUE THREAD

**Issue by tjwatson** [bndtools/bnd#3307]
I have not observed this directly myself, only going off what others have indicated to me.  When BND emits an `osgi.service` it does not also include a uses directive for the packages of the service types that are included in the objectClass attribute of the capability.  I think this should be done by default.

**Comment by rotty3000** [comment]
for reference https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java#L281-L297

**Comment by rinswind** [comment]
The merged changes seem to explicitly omit `java.*` packages from the uses.
But in OSGi 7 we decided that all packages must be declared, because it is important for Java 9+ support.
Also I am not familiar with BND's code base but it looks to me like only the package directly implemented by the service is added to `uses:=` where as it seems more correct to add all packages in all signatures of all service interfaces listed in `objectClass`

**Comment by bjhargrave** [comment]
> The merged changes seem to explicitly omit `java.*` packages from the uses.
> But in OSGi 7 we decided that all packages must be declared, because it is important for Java 9+ support.

This would be covered whenever https://github.com/bndtools/bnd/issues/2507 is addressed. No other part of Bnd handles importing java.* packages yet either.

> Also I am not familiar with BND's code base but it looks to me like only the package directly implemented by the service is added to `uses:=` where as it seems more correct to add all packages in all signatures of all service interfaces listed in `objectClass`

No. You only need to add the uses for the packages for each objectClass. The provider of the service may import the package of each objectClass. The exporter of those packages will have uses for any other packages referenced by the service's package. This then builds a graph of uses constraints which will do "the right thing". You will see all the examples of providing service capabilities in the various specs, only list the package of the service type in the uses directive.
