### ISSUE TITLE
[launchpad] BundleBuilder to use -runee setting when creating bundles

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3314]
When `BundleBuilder` creates a bundle, it relies on bnd to create the default manifest.

Bnd in its turn will add a `Require-Capability: osgi.ee` setting (if none is present) which (if I've read the code correctly) defaults to the EE of the currently executing JVM (actually, it defaults to the highest EE of all classes in the dependency graph, but usually the highest will work out to be the Java system classes loaded by the JVM).

If you are running a launchpad test with a `-runee` that is different to the executing JVM, this results in Launchpad creating bundles which by default don't resolve in the loaded framework (see what happens with the tests for #3145 under OpenJDK 11/12 for an example).

I think it would make more sense if `BundleBuilder` by default set the `Require-Capability: osgi.ee` header to something that is compatible with the `-runee` setting for the Launchpad.

**Comment by bjhargrave** [comment]
Can you fix by Sep 15 (or defer to 6.1)?

**Comment by kriegfrj** [comment]
I worked around this issue when I needed it and I have no immediate need for it. I also haven't heard anyone else request this. So given my limited time I'm going to put this in abeyance. If anyone else has a pressing need for this feature i will revisit then.
