### ISSUE TITLE
Gradle Index task doesn't seem allow for osgi.content url to point to web resource.

### ISSUE THREAD

**Issue by xloce** [bndtools/bnd#3325]
If I'm interpreting this element of the OSGi spec correctly (and glancing the appropriate chapter):
https://osgi.org/specification/osgi.cmpn/7.0.0/service.repository.html#d0e104855

It states about the osgi.content "url" attribute:
> The URL to the bytes. This must be an absolute URL. 

However, I seem unable to generate an index whose osgi.content "url" attribute is valid web URL. In my index task, If I `setBase()` with say, "http://repo1.maven.org/maven2/adarwin/adarwin/1.0", I notice that the generated index won't relativize the bundle files I provide with the base given.

Is there something I'm not considering? Is this desired?

**Comment by bjhargrave** [comment]
> If I'm interpreting this element of the OSGi spec correctly (and glancing the appropriate chapter):
> https://osgi.org/specification/osgi.cmpn/7.0.0/service.repository.html#d0e104855
> 
> It states about the osgi.content "url" attribute:
> 
> > The URL to the bytes. This must be an absolute URL.

That is referring to the `osgi.content` namespace capability, not the XML. See https://osgi.org/specification/osgi.cmpn/7.0.0/service.repository.html#i3247820 where is says

> Any relative URIs in a Repository XML file must be resolved as specified in [5] XML Base (Second Edition), Resolving Relative URIs. 

Gradle does not provide an API to determine the absolute URL of a dependency, so the Bnd Gradle Index task cannot figure out the absolute URL of a dependency from Maven to even put in an index file.

**Comment by bjhargrave** [comment]
https://github.com/bndtools/bnd/issues/1288#issuecomment-173211643

**Comment by xloce** [comment]
Gotcha. Perhaps I should clarify the end goal: to use this generated index in a deployed environment that is different than the build environment. To have say, Apache Karaf, access this index remotely and consume it with the `url`'s of the index pointed to a location where I host the built artifact(s). I notice I'm unable to give an exact URI of a web resource too - it immediately reverts to a `file:` scheme. Is this usage beyond the scope of the plugin?

**Comment by bjhargrave** [comment]
You can make an index where the urls are relative to the index file. So you make a folder with jars and index that folder placing the index in the folder (the folder is the base uri). Then the complete folder (index + jars) can be placed anywhere. Then when reading the index from some url, all the relative urls in the index are resolved to the url of the index. This all works. Here is an example of how we used it (in the past when we were building on a Jenkins instance) in the Bnd build https://github.com/bndtools/bnd/blob/cec43da117b9b2f00ecd6823d35bf2f52133e897/dist/build.gradle#L25-L39

The url of the index file could then use used for an OSGiRepository index.

**Comment by bjhargrave** [comment]
Here is where we relocated that folder to a server for public hosting of the index and indexed jars.

https://dl.bintray.com/bnd/dist/4.1.0/

**Comment by xloce** [comment]
Ah - you're using the XML base rule:
> The base URI is the URI used to retrieve the entity.
I'm now able to make the generated index produce a relative URI (namely/e.g: 'bundles/<jar>') which is simply my build directory at the moment. Will place the build artifacts on the repo relative to the published index as you mentioned/illustrated - didn't think about relative resolution: sorry for the false alarm!
