### ISSUE TITLE
[launchpad] Use Launchpad name as default bundle name

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3329]
At the moment, the default BSN for a synthetic bundle created by Launchpad is `t-<n>` where n is an integer that is incremented throughout the session.

When you see debug output fly across the screen that contains bundle names of the form "t-1", it is not immediately obvious as to which test this pertains. You usually have to scroll back through the log to figure that out.

I had an idea that I wanted to float: when you construct a Launchpad, you are given the opportunity to name it to something that makes sense to you. By default, it uses the class and method name of the caller I believe). I was wondering if perhaps it might be useful to use these as the basis of the root BSN. For example, if my test was `my.pkg.MyTestClass.myTestMethod()`, then my synthetic BSNs would be `my.pkg.MyTestClass.myTestMethod-<n>`.

Because `LaunchpadBuilder` allows a manual override of the calling className/testName, you'd need same sanitizer around it to reliably use it as a BSN. But other than that I can't see any hiccups?

**Comment by pkriens** [comment]
Sounds good, you make a PR?

**Comment by kriegfrj** [comment]
I can do.when I get a chance. Wanted to make sure you were ok with it first.
