### ISSUE TITLE
make annotation types pluggable / configurable

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [bndtools/bnd#333]
1) there are few annotation changes coming up:

RFP-151 Declarative Services Enhancements

RFC 197 OSGi Package and Type Annotation

the way I deal with this: 
* I provide my own annotations form the standard name space org.osgi.*
* I use standard name space the *.java files
* I keep changing private annotations to track changes in the RFC
* when the RFC is baked into core or compendium, I replace private dependency with reference to the public osgi spec.

the point is:
* I do not have to touch *.java code in 100 places
* I merely update parent dependency in the organization-wide pom.xml

2) for this approach to work, bnd should support an instruction
which would allow to switch proprietary bnd annotations, 
with other annotations, assuming only package name change.

**Comment by paulvi** [comment]
ref #429 the annotations need documentation

**Comment by bjhargrave** [comment]
bnd DS, metaype and versioning annotations are deprecated in bnd 3.2 and support will be removed in bnd 4.0.
