### ISSUE TITLE
[bndtools] -nobundles but packages still show export symbol and version

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3341]
Recently added a `-nobundles: true` tag to a project that previously had `-exportcontents: *`.

Prior to adding it, the two packages in src were correctly shown with the little "+" icon (indicating an exported package) and the bundle version number.

Adding the `-nobundles: true` tag stops it producing a bundle. However, the GUI in Eclipse still showed the old export icon and package version, as if they were being exported.

Rebuilding & refreshing the project didn't fix this. Neither did closing and re-opening the project. I had to remove the project from the workspace and re-add it before the display got refreshed.

**Comment by bjhargrave** [comment]
This sounds like a UI refresh issue rather than a functional issue in the core Bnd functionality. So I don't think this issue will hold up other work.

**Comment by kriegfrj** [comment]
Yes, as far as I can tell it was the ui not refreshing, it was otherwise working properly.
