### ISSUE TITLE
Synchronize dist -dependson with the workspace

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3344]
@bjhargrave noted in a review (see https://github.com/bndtools/bnd/pull/3145#pullrequestreview-263777814) that `dist` was missing `biz.aQute.tester` as well as the new project `biz.aQute.tester.junit-platform`. When I started looking into this to add them, I noticed a number of other projects were missing too, so I thought it would be worth an overhaul to make sure that all the projects that should be there are there, and there are none there that aren't.

Perhaps `-dependson` could be calculated using a macro? Failing that, some sort of comment in the `bnd.bnd` file to explain which project should be included in the `-dependson` so that ad-hoc contributors such as myself know if/when they ought to be adding a project to the `-dependson`.

**Comment by bjhargrave** [comment]
We will just manually manage the -dependon list in dist for now. Thanks.

**Comment by kriegfrj** [comment]
Sorry, maybe the OP wasn't clear - The main point of this issue was to make sure that `-dependson in dist was synchronized with the workspace, as there are a couple of projects missing. This can happen manually for now if that's better, but it still needs to happen and I feel this issue probably shouldn't be closed until it does?
