### ISSUE TITLE
Change projects to be dual licensed under Apache License 2 OR Eclipse Public License 2

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3346]
Currently the projects are a mix of AL2 (Apache License 2) and EPL1 (Eclipse Public License 1). The original bnd repo projects are AL2 and the projects merged from the older bndtools repo are EPL1.

I propose to do both of the following:

1. Update EPL1 to EPL2 (Eclipse Public License 2) for all projects currently using EPL1 <https://www.eclipse.org/legal/epl-2.0/faq.php#h.tci84nlsqpgw>. 
2. Change the entire repo so that all projects will be dual licensed (AL2 OR EPL2) for consistency across all projects <https://www.eclipse.org/legal/epl-2.0/faq.php#h.30qunqoq5upx>.

**Comment by kriegfrj** [comment]
I just noticed that when you install Bndtools in Eclipse, it only asks you to accept the EPL 1.0 license - it doesn't ask you to accept the Apache 2.0 license. Would this need to get fixed too? Or if we dual-license everything does that take care of it?
