### ISSUE TITLE
bndrun: add an Eclipse workspace repository

### ISSUE THREAD

**Issue by maggu2810** [bndtools/bnd#3358]
The Bndtools m2e support and a Maven coordinate using the bnd-run-maven-plugin provides a nice integration of the bndrun launch configurations inside the Eclipse IDE.

The dependend bundles (default scope compile + runtime) are available in the repository and if we resolve the bndrun they are used to satisfy the requirements.

The Eclipse plugin already supports that an opened Eclipse project (using the referenced GAV) is preffered and choosen.
This allows to work on bundles and test them immediately (also for Maven based OSGi bundles).

If an Maven Eclipse project is opened and you would like to make them available in the repository of the bndrun, you need to add them as dependency to the pom.xml file of the bndrun project.

Would it be possible to set an option in the bndrun file, the bnd-run-maven-plugin configuration of the project or a global configuration (did not know which would be the correct place) that all Maven projects in the Eclipse workspace are added to the repository without needing to add them to the pom.xml file?

So, act as they would be present in the pom.xml file as dependency and index also the respective transitive dependencies etc.
Or perhaps a special standalone repository name that can be used (e.g. eclipse-workspace)...

**Comment by rotty3000** [comment]
This would make a _view_ from the cli different than from the IDE and we try really hard to avoid that. Why not simply make a BOM of your current projects the all you need in your leaf (bndrun) project is a reference to the BOM?

**Comment by maggu2810** [comment]
> This would make a _view_ from the cli different than from the IDE and we try really hard to avoid that.

I expected that answer, because it fits to my personal view. 😉 



> Why not simply make a BOM of your current projects the all you need in your leaf (bndrun) project is a reference to the BOM?

For me myself this is not a problem at all because I already know how the things are working.

I tried to migrate the openHAB project from PDE to Maven + Bnd and its Eclipse IDE support.
For the most people that are working on openHAB Add-ons the whole setup is a black box and to complicated.
They used the Eclipde IDE only to work on its addons and at PDE times they can add their plugins easily to an Eclipse PDE based launch configuration without adding it first to a dependency in a pom file, then open a bndrun file to add the bundle to the run requirements, ...

So, it is more about people that just want to use a "prepared" app / bndrun and add the bundles in their workspace to that app. The IDE and this special app is just for testing and so the real CLI behavior is not important.

I have to tell people multiple times about the different maven scopes, how to add something to the demo application, why things are missing because the wrong scope has been choosen, ...

Repeating myself: It is not for the ones that already knowing what they are doing, but for people that don't want to dig into the whole setup but just test their bundles.

**Comment by rotty3000** [comment]
hmm, I get you because I often hear similar complaints. On the other hand, it shouldn't be too magical.

**Comment by rotty3000** [comment]
We discussed this in this weeks bnd call and the result is we agreed that fidelity between IDE and CLI is the most important thing. If we can find something that solves the openhab issue and the fidelity issue we'd definitely entertain it.
