### ISSUE TITLE
[bndtools] Repository view of embedded repo

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3359]
The bundles that are included in `biz.aQute.embedded-repo` are available to `bnd` for things like resolving - ie, you can add `bnd.identity;id='biz.aQute.tester.junit-platform'` to your `-runrequires` and the resolver (whether command line or through Bndtools) will find it, even if it's not in any of your explicitly-configured repositories.

However, the bundles in this repository are not available to the UI tools when you are trying to configure your project - eg, they won't be available in the *Browse Repos* pane of the *Run* tab on your `bndrun`/`bnd` file editor, in the *buildpath* configuration pane, or in the Repositories view.

I think it would be nice if Bndtools made this implicit availability of these bundles more obvious. The best way would probably be similar to what happens with the Workspace repo - a Bnd repo that contains the bundles from the embedded repo in the installed version of Bndtools. This would automatically enable the other UI components to leverage its contents too.

**Comment by kriegfrj** [comment]
Hmm, having had a brief look at this code, it looks like steps have been explicitly taken to *hide* the Bnd embedded repo from the Bndtools runtime, eg:

https://github.com/bndtools/bnd/blob/master/bndtools.core/src/bndtools/wizards/repo/RepoBundleSelectionWizardPage.java#L266-L270

https://github.com/bndtools/bnd/blob/master/bndtools.core/src/bndtools/editor/project/AvailableBundlesPart.java#L205-L208

https://github.com/bndtools/bnd/blob/master/bndtools.core/src/bndtools/views/repository/RepositoriesView.java#L1103-L1105

The `true` parameter explicitly tells `listRepositories()` to omit the embedded repo from its returned list of repositories. As far as I can tell, nowhere in bndtools is this ever called with `false`.

To my mind, I think it would be a good thing to have the repository displayed. At the moment, it seems that the bundles in the embedded repo are already available to `-buildpath`, `-runbundles` and `-tester`, though the resolver seems not to be able to find them (at least not when resolving with the Bndtools GUI). I remember in my early days with Bnd it was a mystery to me (and at times a confusing one) how these bundles would work even if they didn't appear in any of the (visible) repositories. If the embedded repository were displayed in the GUI, this would be much less mysterious. However, given that deliberate steps were taken to hide it in the GUI, I'd be reluctant to make this change without understanding why it was hidden in the first place. If it is important that it be hidden in some circumstances, perhaps this can be made a Bndtools configuration option to get the best of both worlds?

**Comment by bjhargrave** [comment]
The command line command 'bnd repo repos` does not seem to show it either:

```
001: Maven Central         r/o MavenBndRepository   https://repo.maven.apache.org/maven2
002: OSGi Snapshots        r/o MavenBndRepository   https://oss.sonatype.org/content/repositories/osgi-releases/
003: Local                 r/w MavenBndRepository   ~/.m2/repository
004: Release               r/w MavenBndRepository   file:/Users/hargrave/git/bnd/dist/bundles/
005: OSSRH                 r/w MavenBndRepository   https://oss.sonatype.org/service/local/staging/deploy/maven2/
006: JFrog                 r/w MavenBndRepository   https://bndtools.jfrog.io/bndtools/libs-release-local/
007: Eclipse Oxygen 4.7.3a  r/o OSGiRepository       https://dl.bintray.com/bndtools/eclipse-repo/4.7.3a/index.xml.gz
008: Eclipse m2e 1.8.3 Dependencies  r/o BndPomRepository     /Users/hargrave/git/bnd/cnf/cache/stable/EclipseM2EDeps/index.xml
009: Baseline              r/o MavenBndRepository   https://repo.maven.apache.org/maven2
010: Workspace bnd         r/o WorkspaceRepository  /Users/hargrave/git/bnd
```

**Comment by kriegfrj** [comment]
Interesting. Whatever change (or non-change) we propose here should probably apply to the command line as well.

Also note I made a false statement in my OP:
> The bundles that are included in `biz.aQute.embedded-repo` are available to `bnd` for things like resolving - ie, you can add `bnd.identity;id='biz.aQute.tester.junit-platform'` to your `-runrequires` and the resolver (whether command line or through Bndtools) will find it, even if it's not in any of your explicitly-configured repositories.

I tested this again and it appears that I was wrong - I had made a copy of that bundle in a `LocalIndexedRepo` in my workspace so that I could use it during resolution (need to find its dependencies). The resolver wouldn't find it otherwise. However, even without the copy in Local, the builder seems to find it if it's in `-buildpath` and the launcher/tester framework seems to find it if it's in `-runbundles` or `-tester`. I think it would be helpful if this was a bit more consistent - either it's visible to all parts of Bnd, or it's not visible to any.

Thoughts?

**Comment by pkriens** [comment]
The embedded cache is a 'last' resort for code that bnd depends on. These resources are not considered during resolving. I think it would be confusing to show them.

**Comment by kriegfrj** [comment]
Ok, one last appeal: The problem is that `biz.aQute.tester.junt-platform` requires dependencies that are not in the embedded repo. It would be nice to use the resolver to make sure you've added the right ones. You can't do that at the moment - either you have to manually copy.`biz.aQute.tester.junit-platform` into another repo in the workspace to make it available, or you have to manually add the required dependencies to runrequires or runbundles (which is very un-Bnd like). I worry it will be difficult for the average punter uswe'll struggle to use the New tester under these conditions.

I agree it would be confusing to have them visible but not available for resolving. But it is equally confusing to have them not visible but available in other contexts. I think for consistency it would be good if it were available in all contexts (i.e., make it available during resolving as well).

**Comment by bjhargrave** [comment]
But `biz.aQute.tester` also requires dependencies which are not in the embedded repo unless you consider `biz.aQute.junit` to be a source of the junit dependencies of `biz.aQute.tester`.

The embedded repo is a simple FileRepo repo. This repo type does not implement `org.osgi.service.repository.Repository` like `OSGiRepository`, `MavenBndRepository`, and some of the other repo types. So merely making the embedded repo appear in the repo view does not mean it can be a source of `Resource`s which can satisfy `Requirement`s of other bundles for the resolver. 

You should be able refer to something in the embedded repo without it being mentioned in another repo. For example, a bnd file should be able to say `-tester: biz.aQute.tester` and have it come from the embedded repo. But perhaps I am wrong here...

But I will say that in the OSGi build, we explicitly use a `biz.aQute.tester` jar from a configured repo so we do not rely upon the embedded repo. We also specify the junit dependencies from a configured repo.  So I don't see that doing this as bad or un-Bnd-like. I fact I would expect a well configured workspace to use precise testing dependencies from configured repositories rather than use whatever is in the embedded repo (which is a last resort as Peter mentioned).

**Comment by kriegfrj** [comment]
> But `biz.aQute.tester` also requires dependencies which are not in the embedded repo unless you consider `biz.aQute.junit` to be a source of the junit dependencies of `biz.aQute.tester`.
> 

Yes, I noted that `biz.aQute.junit`'s presence in the embedded repo (whether by accident or design) automatically satisfied all of the dependencies for `biz.aQute.tester` dependencies without the need of adding any from any other repo.

> The embedded repo is a simple FileRepo repo. This repo type does not implement `org.osgi.service.repository.Repository` like `OSGiRepository`, `MavenBndRepository`, and some of the other repo types. So merely making the embedded repo appear in the repo view does not mean it can be a source of `Resource`s which can satisfy `Requirement`s of other bundles for the resolver.
> 

This makes sense - so the reason that it isn't used during resolution actually has nothing to do with the fact that it doesn't get listed in Bndtools, but due to the fact that the repo isn't indexed.

> You should be able refer to something in the embedded repo without it being mentioned in another repo. For example, a bnd file should be able to say `-tester: biz.aQute.tester` and have it come from the embedded repo. But perhaps I am wrong here...
> 

Yes, it seems you can use it anywhere except during resolution.

> But I will say that in the OSGi build, we explicitly use a `biz.aQute.tester` jar from a configured repo so we do not rely upon the embedded repo. We also specify the junit dependencies from a configured repo. So I don't see that doing this as bad or un-Bnd-like. I fact I would expect a well configured workspace to use precise testing dependencies from configured repositories rather than use whatever is in the embedded repo (which is a last resort as Peter mentioned).

This makes sense.

To be clear, the "un-Bnd-like" bit I was referring to was not using explicit references to `biz.aQute.tester`, but having to resolve its dependencies manually because the resolver wouldn't load `biz.aQute.tester` or anything from the embedded repo. Adding the tester bundle to an indexed repo fixes that, and if that's best practice I'm happy to do it too.
