### ISSUE TITLE
[launcher] Launcher ignoring changes to properties file

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3360]
The resource listener in Bndtools listens for changes to any of the bundles in `-runbundles` and restarts them if necessary.

It also watches the launch file, in case any of the launch configuration has changed (eg, change in the composition of `-runbundles` itself), and installs/removes bundles as appropriate.

However, the resource watcher will always watch your project's `bnd.bnd`. This may not be the same file that was used to launch the project, which means it will pick up irrelevant changes and ignore the relevant ones if you're launching with anything other than `bnd.bnd`.

It will not be too hard to fix this so that it watches the bnd(run) file that was actually used to start the launch instead of always watching `bnd.bnd`. However, given that it touches the same part of the code as #3300 I'd like to wait for that to get merged so as to avoid conflicts.

**Comment by rotty3000** [comment]
But the `bnd.bnd` file plays a role regardless of which run was used because it defines the bundle. It's not the possibility that it contains run options that is the relevant part, it's the fact that it plays a role in defining the bundle.

**Comment by kriegfrj** [comment]
> But the `bnd.bnd` file plays a role regardless of which run was used because it defines the bundle. It's not the possibility that it contains run options that is the relevant part, it's the fact that it plays a role in defining the bundle.

That's true, but that role is indirect. The running application is only directly affected by the bundles and the run configuration, not the build configuration. If the build configuration in a bnd.bnd file changes, its corresponding output jar will change, and this change will get picked up by the resource listener and the bundle reinstalled. Conversely, if somehow bnd.bnd changes but it's output bundle does not (maybe build automatically is off), then there is nothing (yet) to update in the running application.

**Comment by rotty3000** [comment]
I think we're talking about the logic around here: https://github.com/bndtools/bnd/blob/master/bndtools.core/src/bndtools/launch/OSGiRunLaunchDelegate.java#L244

**Comment by kriegfrj** [comment]
Yes. On the surface of it it looks like it is trying to do what I wanted. Either I broke it somehow in #3145 (which I'm currently using) or else is not quite working properly.

**Comment by kriegfrj** [comment]
Actually, on closer inspection it's not doing what I wanted/expected. The "target" in `Project.getTarget()` :https://github.com/bndtools/bnd/blob/2fcf8f065f3a3680fa202486c38c1e33d8bce382/bndtools.core/src/bndtools/launch/OSGiRunLaunchDelegate.java#L253 refers to the target output directory for the build, not the target bndrun file of the launch configuration.

Instead of blinding monitoring bndBndPath, it should take a note of which bnd/bndrun file was used for the launch and watch that one.

This is a relatively easy fix, but I would like to wait for #3145 to get merged first to avoid merge conflicts.

**Comment by kriegfrj** [comment]
Some more data:

The OSGiRunLaunchDelegate *is* watching the right file:

https://github.com/bndtools/bnd/blob/2fcf8f065f3a3680fa202486c38c1e33d8bce382/bndtools.core/src/bndtools/launch/OSGiRunLaunchDelegate.java#L240

I got confused because the word "target" is reused to mean two different things. `targetResource` seems to refer to the bndrun file (if used)

Further, when I change my bndrun with launcher tracing on, I can see a bunch of statements like "bundle is still current..." which would only happen if the launcher is being refreshed. However, this refresh doesn't seem to properly process changes to the `-runbundles` directive - eg, I just added a couple of bundles and saved my bndrun and I can see that it did a launcher refresh, but the bundles I added to `-runbundles` were not added to the running instance.

I suspect that there is a cache somewhere that is not getting flushed and picking up the changes, so it is propertly triggering an update to the launcher properties but then updating it with the old values.

This is quite possibly related to https://github.com/bndtools/bnd/pull/3293#issuecomment-506399746 I have to echo @pkriens comment in that issue: "It sucks we have no bndtools tests :-("

**Comment by kriegfrj** [comment]
Ok, I've had a detailed look at this in the debugger, and I've figured out what is going on. It has nothing to do with the resource listener watching the wrong file or the file being cached.

The watch timer watches for changed properties file and when it notices a change it calls `Launcher.loadProperties()`, followed by `update()`.
https://github.com/bndtools/bnd/blob/9a021bbdf58ad51e192315848c6a02e4d3b31ec6/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L279-L280

`update()` calls through to `synchronizeFiles()`, which as its first step builds up a list of "desired" bundles based on `parms.bundles`:
https://github.com/bndtools/bnd/blob/9a021bbdf58ad51e192315848c6a02e4d3b31ec6/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L611-L617

However, there is nothing between the call to `loadProperties()` and `synchronizeFiles()` that actually populates `parms.runbundles`, so it ends up using the contents as they were (ie, the same set of runbundles that was already installed and running).

There is another problem: The original `launch()` call copies all of the properties from launch.properties into the `System` properties map:
https://github.com/bndtools/bnd/blob/9a021bbdf58ad51e192315848c6a02e4d3b31ec6/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L323-L324

...then in `loadProperties()`, after loading the properties from the file, all of the launcher-related System properties are copied back into the local properties object:
https://github.com/bndtools/bnd/blob/9a021bbdf58ad51e192315848c6a02e4d3b31ec6/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L243-L256

...so that by the time loadProperties() is finished, it has already discarded any changes in the local properties file.

The nett effect of all this is that while the launcher will properly update when a running bundle changes, it will not properly update any of the properties.

For some properties this may be desired behaviour as it may not be possible to change them in a running environment. However, for others that we'd like to change dynamically (eg, runbundles) the current implementation doesn't make it possible.

Having diagnosed the problem I'm going to pause and have a bit of a think about the best solution. Given that this ties so heavily into the functionality of a core component, thoughts from core developers (@pkriens , @bjhargrave ) would be most welcome (perhaps mandatory).

**Comment by bjhargrave** [comment]
> Ok, I've had a detailed look at this in the debugger, and I've figured out what is going on.

Great job on debugging this! Your write-up really highlighted the issues for me. I hope the PR solves the issue for you. I guess this has been broken for a long time.

**Comment by pkriens** [comment]
One worry, I am absolutely sure that in the past you could change the set of bundles and this was then updated on the target. Could this have been introduced more recently?

**Comment by kriegfrj** [comment]
> One worry, I am absolutely sure that in the past you could change the set of bundles and this was then updated on the target. Could this have been introduced more recently?

That was my concern too which is why I wanted feedback from you guys before attempting to fix it... I know personally, I've never seen this work. It will notice and update if ant in the existing set of the installed bundles change, but it won't change the set of bundles.

**Comment by pkriens** [comment]
There was a bug a few months ago that created the whole automatic update, I expect it got lost somewhere there and in the update after. 
However, we can test this and it is mostly debug behavior so I think risc is low. Let's discuss thi on the friday meeting.
