### ISSUE TITLE
Compiler options from the bnd file

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3363]
In the workspace model, bnd files are the preferred way to specify the build options since they are shared between Gradle and Eclipse.

I think we should at least support common compiler options

**Comment by pkriens** [comment]
Worst case, verify them

**Comment by bjhargrave** [comment]
> I think we should at least support common compiler options

What are you thinking for these common compiler options? Example?

**Comment by pkriens** [comment]
Clearly the already used javac.* properties

Most important (and direct cause for this issue)

    -parameters

Sounds interesting:

    -g, -g:...
    -verbose
    -D?
    -proc: [none, only]
    -processor class1 [,class2,class3...]
    -processorpath path
    -profile

**Comment by bjhargrave** [comment]
We already support `javac.profile` bnd property. 

We support `javac.debug` as a boolean property but we could allow it to contain `-g` parameters.

Verbose is controlled by the gradle `--debug` flag.

We also support `javac.deprecation` and `javac.encoding`.

But all of these only are used by gradle. We have no way to configure the Eclipse compiler in Eclipse when using Bndtools. That is controlled by the .settings folder. So I don't know how we could get any java compiler options in a bnd file into a project's eclipse compiler settings in Eclipse (since the Bndtools builder is called after compilation.)

**Comment by pkriens** [comment]
Wow, would it be hard to add -parameters (`javac.parameters`?)

I could then write a verifier in Eclipse that these properties line up

**Comment by pkriens** [comment]
annotations, I do not have a use case right now but if we can somehow make this work in Eclipse and gradle it might be interesting to do some things that are really hard now.

**Comment by bjhargrave** [comment]
I could definitely add support for `javac.parameters` or even a more general `javac.arguments` to the gradle plugin. But there is no way for these to influence the Eclipse compiler in Bndtools. You would also need to modify the .settings folder to change the Eclipse compiler settings for a project. See https://github.com/bndtools/bnd/commit/1c732b27ff18db7b2b81ea771f2ef3458c4b0d54 where I add `-parameters` to a project's Eclipse compiler settings.

**Comment by pkriens** [comment]
Using org.eclipse.jdt.core.IJavaProject.setOption(String, String) would not be possible?

**Comment by bjhargrave** [comment]
In Eclipse, the java builder runs before the Bndtools builder. So, to call that method, I guess you would need to do so in BndContainerCompilationParticipant.aboutToBuild so any compiler options are set before the compiler runs.

**Comment by bjhargrave** [comment]
But then you would need to worry about overriding what may be set in .settings and if the user cares about such an override.

**Comment by pkriens** [comment]
yes, but that seems manageable. We could by default take the bnd settings and have a preference to not do it for the workspace. Not sure if IJavaProject.setOption will set the value in .settings?

This looks more promising than I hoped.
