### ISSUE TITLE
[enhancement] Ask Bnd to filter arbitrary packages when analyzing bytecode

### ISSUE THREAD

**Issue by gamerson** [bndtools/bnd#3364]
I have a scenario where classes is getting added to a jar that Bnd is analyzing, but I don't want any imports or other requirements emitted into the Manfiest for that "other" packages. 

Is there a way to declare to Bnd that there are certain packages I want it to skip when it's analyzing?

**Comment by pkriens** [comment]
sounds terribly scary. I do not know of any mechanism to do this, it seems quite unnatural for bnd to do this?

**Comment by bjhargrave** [comment]
Yes, this seems kind of sketchy. Why do you want to include packages in a bundle which will fail to load since they may import packages which would not be available?

**Comment by gamerson** [comment]
In our case we have bytecode that will be loaded from a bundle but be executed by a thread that has an aggregate classloader that includes the bundle classloader plus "other stuff".

However, I've since then found another way to solve this that doesn't require any changes to bnd, so I'll close.
