### ISSUE TITLE
Where can I get a pure ant version of the bnd 4.2.0 jar that doesn't include slf4j?

### ISSUE THREAD

**Issue by nzall** [bndtools/bnd#3369]
I have a problem where I need a 4.2.0 version of the biz.aQute.bnd.jar file with just the ANT related files. Reason being is that I don't need any of the maven or Gradle integrations, AND the slf4j included with the jar is conflicting with my own slf4j bindings, leading to build errors.

where can I find a jar like this?

**Comment by bjhargrave** [comment]
We do not build or publish such a jar. You would need to build one yourself from the source code.

**Comment by nzall** [comment]
> We do not build or publish such a jar. You would need to build one yourself from the source code.

I see. do you publish a full jar without slf4j included?

**Comment by bjhargrave** [comment]
> > We do not build or publish such a jar. You would need to build one yourself from the source code.
> 
> I see. do you publish a full jar without slf4j included?

As I said, `We do not build or publish such a jar.` We only publish the jars we actually build.

**Comment by nzall** [comment]
> > > We do not build or publish such a jar. You would need to build one yourself from the source code.
> > 
> > 
> > I see. do you publish a full jar without slf4j included?
> 
> As I said, `We do not build or publish such a jar.` We only publish the jars we actually build.

Ah, okay. Sorry, misunderstood the message. I assume there's also no older version of the bnd jar with the Ant tasks included that both supports Java 1.8 operators AND has no slf4j included?

**Comment by bjhargrave** [comment]
It appears slf4j was introduced to bnd in 3.2.0: https://github.com/bndtools/bnd/commit/9df8499b0df602c8ce31b50b67ab4d5a9996f4e0. So you would need version 3.1.0 or older to find a bnd jar which does not use slf4j. 

I am not sure what you mean by `supports Java 1.8 operators`.

I suggest you simply build a version of the jar from source which does not Private-Package the slf4j api. Using a version of 3.1.0 or older does not seem like a wise idea.

**Comment by nzall** [comment]
To explain the Java 1.8 operators: I recently started using java 8 streams in parts that are included in OSGI bundles in a Karaf environment. The version of the BND Ant jar we used was an ancient one, version 1.5.0 according to the manifest.mf file in the Jar, and when I was building the bnd files, it started throwing ArrayIndexOutOfBoundExceptions: 18 while building those OSGI bundles, indicating that it wasn't compatible with that type of file. Because of that, I wanted to update the BND Ant jar to a more recent version. I am trying to use version 4.2.0, which does throw a handful of warnings:

[bnd] 1 WARNINGS
      [bnd]  Unused Import-Package instructions: [company.util.builders.*, org.apache.log.*, javax.*] 
      [bnd] 1 WARNINGS
      [bnd]  The JAR is empty: The instructions for the JAR named org.apache.servicemix.bundles.c3p0_cfg did not cause any content to be included, this is likely wrong
      [bnd] 1 WARNINGS
      [bnd]  Unused Import-Package instructions: [com.vasoftware.sf.*, com.ibm.*, com.jcraft.jzlib.*, com.sun.*, groovyjarjarasm.asm.*, jxl.*, bsh.*, mondrian.olap.*, nu.xom.*, antlr.*, org.apache.batik.*, org.apache.bsf.*, org.apache.commons.httpclient.*, org.apache.commons.javaflow.*, org.apache.tools.ant.*, org.apache.xalan.*, org.apache.xmlbeans.*, org.apache.xpath.*, org.codehaus.groovy.*, org.eclipse.jdt.*, org.exolab.castor.xml.*, org.jaxen.*, org.jdom.*, org.joda.time.*, org.mortbay.*, org.objectweb.asm.*, org.omg.*, org.w3c.dom.*, org.xmlpull.*, org.xmlsoap.*, sun.*, test.wsdl.import2.types.*, com.caucho.*, com.werken.xpath.*, net.sf.cglib.asm.*, org.aopalliance.*, org.apache.avalon.framework.logger.*, org.apache.commons.fileupload.*, org.gjt.xpp.*, org.codehaus.jackson.*, org.relaxng.datatype.*, org.jruby.*, org.codehaus.jettison.*, org.hibernate.validator.*, org.apache.xml.resolver.*, org.apache.log.*, javax.accessibility.*, javax.imageio.*, javax.jms.*, javax.naming.*, javax.net.*, javax.print.*, javax.rmi.*, javax.security.*, javax.servlet.*, javax.sql.*, javax.swing.*, javax.transaction.*, javax.validation.*, javax.wsdl.*] 
      [bnd] 1 WARNINGS
      [bnd]  The JAR is empty: The instructions for the JAR named org.hibernate_cfg did not cause any content to be included, this is likely wrong
      [bnd] 2 WARNINGS
      [bnd]  Host company.orm= for this fragment/require bundle cannot be found on the classpath
      [bnd]  Host company.orm= for this fragment cannot be found on the classpath
      [bnd] 2 WARNINGS
      [bnd]  Host company.util= for this fragment/require bundle cannot be found on the classpath
      [bnd]  Host company.util= for this fragment cannot be found on the classpath
      [bnd] 2 WARNINGS
      [bnd]  Unused Private-Package instructions, no such package(s) on the class path: [company.plugin, company.util, company.util.base]
      [bnd]  Unused Import-Package instructions: [com.vasoftware.sf.*, com.ibm.*, com.jcraft.jzlib.*, com.sun.*, groovyjarjarasm.asm.*, jxl.*, bsh.*, mondrian.olap.*, nu.xom.*, antlr.*, org.apache.batik.*, org.apache.bsf.*, org.apache.commons.httpclient.*, org.apache.commons.javaflow.*, org.apache.tools.ant.*, org.apache.xalan.*, org.apache.xmlbeans.*, org.apache.xpath.*, org.codehaus.groovy.*, org.eclipse.jdt.*, org.exolab.castor.xml.*, org.jaxen.*, org.jdom.*, org.joda.time.*, org.mortbay.*, org.objectweb.asm.*, org.omg.*, org.w3c.dom.*, org.xmlpull.*, org.xmlsoap.*, sun.*, test.wsdl.import2.types.*, com.caucho.*, com.werken.xpath.*, net.sf.cglib.asm.*, org.aopalliance.*, org.apache.avalon.framework.logger.*, org.apache.commons.fileupload.*, org.gjt.xpp.*, org.codehaus.jackson.*, org.relaxng.datatype.*, org.jruby.*, org.codehaus.jettison.*, org.hibernate.validator.*, org.apache.xml.resolver.*, org.apache.log.*, javax.accessibility.*, javax.imageio.*, javax.jms.*, javax.naming.*, javax.net.*, javax.print.*, javax.rmi.*, javax.sql.*, javax.swing.*, javax.transaction.*, javax.validation.*, javax.wsdl.*] 
      [bnd] 1 WARNINGS
      [bnd]  The JAR is empty: The instructions for the JAR named de.schlichtherle.xml_cfg did not cause any content to be included, this is likely wrong
      [bnd] 1 WARNINGS
      [bnd]  The JAR is empty: The instructions for the JAR named xstream_cfg did not cause any content to be included, this is likely wrong

I wanted to simply get my build working so I can commit and have coworkers look at it, but during the build stage, during my unittests, it complains about multiple slf4j bindings, since you guys chose to include slf4j in your tool. The error I'm getting is related to Jansi:

     [echo] Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path]
     [echo] 	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
     [echo] 	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
     [echo] 	at org.fusesource.jansi.internal.Kernel32.<clinit>(Kernel32.java:37)
     [echo] 	at org.fusesource.jansi.WindowsAnsiOutputStream.<clinit>(WindowsAnsiOutputStream.java:53)
     [echo] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     [echo] 	at org.apache.logging.log4j.core.appender.ConsoleAppender.getOutputStream(ConsoleAppender.java:267)
     [echo] 	at org.apache.logging.log4j.core.appender.ConsoleAppender.getDefaultManager(ConsoleAppender.java:230)
     [echo] 	at org.apache.logging.log4j.core.appender.ConsoleAppender.createDefaultAppenderForLayout(ConsoleAppender.java:176)
     [echo] 	at org.apache.logging.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:587)
     [echo] 	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
     [echo] 	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:86)
     [echo] 	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:171)
     [echo] 	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
     [echo] 	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:70)
     [echo] 	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
     [echo] 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
     [echo] 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
     [echo] 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
     [echo] 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:122)
     [echo] 	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
     [echo] 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
     [echo] 	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
     [echo] 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
     [echo] 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)

Long-term we want to build everything with Java 11, but right now my focus is getting those Java 1.8 features working with bnd.

**Comment by bjhargrave** [comment]
You will definitely need to use a more recent version of Bnd than 3.1.0 to support the latest Java class file versions. It looks like Java 11 support was added in Bnd 4.1.0. Java 8 support was added a lot earlier and is probably in Bnd 3.1.0. But 1.5.0 is ancient.

biz.aQute.bnd.jar has the main purpose today of being a standalone command line tool. As such it must be complete so that `java -jar biz.aQute.bnd.jar` works. Since other parts of Bnd are coupled to the slf4j API, biz.aQute.bnd.jar must include the API.

Frankly, we don't see many Ant users any more. The ant tasks are still in biz.aQute.bnd.jar but we don't have many/any tests for them, so I can't really vouch for the quality of them.

For the purposes of your work, and to validate if it may make sense to produce a `biz.aQute.bnd.ant.jar` binary for the few Ant users left, I would repeat my suggestion that you build from source and exclude the slf4j API from the jar. And then test to see if that works for you.

**Comment by nzall** [comment]
@bjhargrave I just received an email that this issue has been fixed. How should I interpret this? Did you make a separate standalone jar for Ant tasks for the 5.2 release so that the main jar no longer need to include the additional libraries needed to run this as an ant task?

**Comment by bjhargrave** [comment]
See the comments in PR #4220.

There is a new biz.aQute.bnd.ant artifact which depends on other artifacts such as biz.aQute.bndlib (and possibly other Bnd artifacts if you use repositories or resolving.)

**Comment by bjhargrave** [comment]
> depends on other artifacts such as biz.aQute.bndlib (and possibly other Bnd artifacts if you use repositories or resolving.)

The testing of the new artifacts uses some other Bnd artifacts:

https://github.com/bndtools/bnd/blob/6ea0a373d6b513428a1e96966b89c3c5adc272a1/biz.aQute.bnd.ant/bnd.bnd#L25-L27

over an above bndlib

https://github.com/bndtools/bnd/blob/6ea0a373d6b513428a1e96966b89c3c5adc272a1/biz.aQute.bnd.ant/bnd.bnd#L19-L20
