### ISSUE TITLE
MavenBackingRepository silently ignores errors related to authentication

### ISSUE THREAD

**Issue by cfstras** [bndtools/bnd#3379]
We have a repository configured like this, trying to build with gradle:
```
-plugin.97.xyz = \
    aQute.bnd.repository.maven.provider.MavenBndRepository; \
        snapshotUrl=https://my.server/test/snapshot; \
        releaseUrl=https://my.server/test/release; \
        index=${.}/xyz.maven; \
        name="Our Dependencies"
```

And the basic authentication was present in ~/.bnd/connection-settings.xml, as such:
```xml
<settings>
  <servers>
    <server>
      <id>https://my.server/test</id>
      <username>...</username>
      <password>...</password>
    </server>
  </servers>
</settings>
```

Notice how the id has the path appended.

This leads to a cascade of multiple bugs:

1. `SettingsURLConnectionHandler.matches()` only compares against the scheme (http), host and port, but not on the path. The configuration is not picked up and **silently ignored**.
https://github.com/bndtools/bnd/blob/7028683045bf0d6e4c3794958af2b179f754c96b/biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java#L280

2. `MavenBackingRepository.getMetadata(Revision)` silently ignores `Tag.responseCode=401` (Unauthorized), and creates a new, invalid RevisionMetadata

https://github.com/bndtools/bnd/blob/7028683045bf0d6e4c3794958af2b179f754c96b/biz.aQute.repository/src/aQute/maven/provider/MavenBackingRepository.java#L114

3. `MavenBackingRepository.getVersion(Revision)` emits a **warning** `Snapshot and/or buildnumber not set`, but ignores the artifact, leading to an unresolved dependency. This should be a hard error.

https://github.com/bndtools/bnd/blob/7028683045bf0d6e4c3794958af2b179f754c96b/biz.aQute.repository/src/aQute/maven/provider/MavenBackingRepository.java#L165

**Comment by pkriens** [comment]
JUst released a PR to fix this https://github.com/bndtools/bnd/pull/3944
