### ISSUE TITLE
missing Bundle-Version is not being replaced by version from Gradle

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#3380]
I've found in [documentation](https://bnd.bndtools.org/heads/bundle_version.html) that:

> If no such header is provided, a version of 0 will be set.

but on the other hand, in [this thread](https://github.com/bndtools/bnd/issues/1069#issuecomment-137585035) @bjhargrave   wrote:

> "Bundle-Version is set from the gradle project's version property if Bundle-Version is unset."

reality is that when I set `version` in `build.gradle` file and remove `Bundle-Version` from `bnd.bnd` file, then both: `./gradlew release` and `Eclipse` displays:

> The baseline version 0.0.1 is higher than the current version 0.0.0 for my.bundle in Release

it is because I have `@org.osgi.annotation.versioning.Version("0.0.1")` in `package-info.java` file, although version in `build.gradle` is set to `0.0.2`, so indeed - version is set to `0.0.0` but it's more reasonable that it is taken from Gradle.

**Comment by bjhargrave** [comment]
You do not state whether you are using a Bnd workspace model build (cnf folder and use `biz.aQute.bnd` gradle plugin) or a non-Bnd workspace model build (e.g. normal Gradle build using `biz.aQute.bnd.builder` gradle plugin).

The Bnd Workspace model build is fully driven by the Bnd workspace (cnf) and the project bnd files and does not consult any gradle scripts for metadata. If fact, you normally don't need any gradle scripts in projects for Bnd workspace model builds.

For non-Bnd workspace model builds, then any Bundle-Version in the bnd metadata is used if present, otherwise it falls back to the gradle task's version (which falls back to the gradle project's version).         // set bundle version from task's version if necessary
        String bundleVersion = builder.getProperty(Constants.BUNDLE_VERSION)
        if (isEmpty(bundleVersion)) {
          builder.setProperty(Constants.BUNDLE_VERSION, MavenVersion.parseMavenString(version?.toString()).getOSGiVersion().toString())
        }

**Comment by eximius313** [comment]
I'm using bndworkspace plugin but:
* Even Eclipse complains about it:
![image](https://user-images.githubusercontent.com/5578017/63025738-1fdff700-beaa-11e9-8395-606b47bc5ccc.png)
* I must invoke `./gradlew release` in my CI

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by eximius313** [comment]
Ok, here you have it: [BndTest.zip](https://github.com/bndtools/bnd/files/3583694/BndTest.zip)

Although `version` is set in `build.gradle`, when `Bundle-Version` is missing then bundle version is set to `0.0.0`

do:
```
$ ./gradlew release
$ ls cnf/release/my.test.bundle/
my.test.bundle-0.0.0.jar
```

**Comment by bjhargrave** [comment]
As I stated above:

> The Bnd Workspace model build is fully driven by the Bnd workspace (cnf) and the project bnd files and does not consult any gradle scripts for metadata. If fact, you normally don't need any gradle scripts in projects for Bnd workspace model builds.

Your zip file contains a Bnd Workspace model build (cnf folder) and so it does not matter what you put in the gradle scripts regarding versions, a Bnd Workspace model build is fully driven by the bnd files and cnf/build.bnd. So you MUST specify any desired Bundle-Version in the bnd files.

(Also, your zip file is using an out-of-date 4.2.0-SNAPSHOT Bnd gradle plugin when 4.2.0 is released.)

**Comment by eximius313** [comment]
> Also, your zip file is using an out-of-date 4.2.0-SNAPSHOT Bnd gradle plugin when 4.2.0 is released.

I'm using newest Eclipse and created fresh workspace and fresh bnd project, so I don't know why it happened.
How to change it?

**Comment by bjhargrave** [comment]
> How to change it?

I fixed it with https://github.com/bndtools/workspace/pull/11.
