### ISSUE TITLE
Bundle-Version is overriden by variable from included file

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#3381]
I have a file `version.properties`:
```
version = 0.0.103
fooVersion = 0.0.3
```
and when in `bnd.bnd` file I set:
```
-include: ${.}/../version.properties
Bundle-Version: ${fooVersion}
```
and invoke `./gradlew release` then version `0.0.103` is released instead of `0.0.3`

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by eximius313** [comment]
@bjhargrave 
1) take `any` project that you have
2) create version.properties in your project with the two lines I provided
3) indlude this file in any of your `bnd.bnd` file
4) run `./gradlew release` and see which version was released in `~/.m2/repository`

**Comment by bjhargrave** [comment]
Sorry, but I am quite busy. So we really your help to make it easy and quick for the Bnd maintainers to investigate problems. And frankly, the act of creating the sample github repo can often reveal to the submitter what the real issue is :-)

**Comment by eximius313** [comment]
yes.
`fooVersion` could be anything. But still: should "random" variable `version` take precedence over `Bundle-Version`?

**Comment by eximius313** [comment]
Ok, I have replicated this: [BndTest.zip](https://github.com/bndtools/bnd/files/3583660/BndTest.zip)
version are as follows:
```
version=0.0.4
myVersion=0.0.6
```
According to what you say - `myVersion` is higher, so it should be taken (nevertheless I think that even if its lower it should be taken anyway, because it's **explicitly** listed in `Bundle-Version: ${myVersion}`)
after `$ ./gradlew clean release` you get:
```
$ ls cnf/release/my.test.bundle/
my.test.bundle-0.0.6.jar   -> correct
$ ls ~/.m2/repository/io/my/bundle/my.test.bundle
0.0.4/                     -> wrong
```

**Comment by bjhargrave** [comment]
I can confirm this bug. Investigating...
