### ISSUE TITLE
Prompt box cannot be closed

### ISSUE THREAD

**Issue by duan2ping** [bndtools/bnd#3384]
Project build warning prompt box cannot be closed after opening.

Bndtools-Version : 4.2.0.REL-20190305-163318-g7028683
Java-Version : 1.8.0
OS : Ubuntu 18.04.1 LTS

![bndtools2019-08-19 16-18](https://user-images.githubusercontent.com/22853839/63249983-2bae2d80-c29d-11e9-99a4-b6cfcb8862a4.gif)

**Comment by juergen-albert** [comment]
Is this still a thing? I don't even see an overlay anymore, if a bnd file has a warning?

**Comment by juergen-albert** [comment]
@bjhargrave can you close it please as discussed?
