### ISSUE TITLE
Resolving Run Configuration using bnd and bndtools

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#3387]
If we resolve any bndrun in bnd command line or Gradle that drags in any of the workspace projects in the `runbundles`, the version gets specified as `snapshot`

For example,

```
-runrequires:
   bnd.identity;id='workspace.project'

# auto-generated by resolve opearation
-runbundles:
     workspace.project;version=snapshot
```

whereas in Bndtools, it uses the Bundle Version

```
-runrequires:
   bnd.identity;id='workspace.project'

# auto-generated by resolve opearation
-runbundles:
     workspace.project;version=[1.100.0, 1.101.0)
```

This doesn't result in any problem but everytime the bundle version changes, all the existing bndrun configurations need to be updated with the current bundle versions.

**Comment by pkriens** [comment]
Fixed in #3585
