### ISSUE TITLE
Mutiple Repos with one cnf folder (repo)

### ISSUE THREAD

**Issue by rimmeraj** [bndtools/bnd#341]
After reading https://github.com/bndtools/bnd/pull/173 I think I have a much simpler and elegant solution. 

In aQute.bnd.build.Workpsace.java there is already code that if ../cnf or ../bnd is not a directory but a file it reads the contents as a pointer to a location where the cnf lives. The problem is that then the workspace decides that this is the base dir for all projects and everything else has to live ../. 

In the case of bndtools it always hands the physical location of the project to 

public static Project getProject(File projectDir)

so changing 

public Project getProject(String bsn) 

to 

protected Project getProject(File baseDir,String bsn)

and public Project getProject(String bsn)  calls  getProject(getBase(),bsn)

and then static getProject(File projectDir) calls the protected method with the location of the project. This fixes bndtools using multiple git repos.

So my eclipse git layout looks like

```
git/  <- eclipse git workspace
  repo1/  <- repository1
     proj1/
     proj2/
     cnf <- file containing ../cnf.repo
  repo2/ <- repository2
    proj3/
    cnf <- file containing ../cnf.repo
  cnf.repo/  <- cnf repository
     cnf/
```
Running bnd in ant on the command line I added some code to take the relative part of re-direct so if we are building proj3 on the command line and depend on proj1 then the workspace will look in repo2/ and repo1/

The changes are about 15 lines of code in Workspace, I have patch files for both

**Comment by bjhargrave** [comment]
> git/ <- eclipse git workspace
> repo1/ <- repository1
> proj1/
> proj2/
> cnf <- file containing ../cnf.repo
> repo2/ <- repository2
> proj3/
> cnf <- file containing ../cnf.repo
> cnf.repo/ <- cnf repository
> cnf/

This is hard to read this since the formatting is broken. Can you fix to show the intended containment relationships?

Also, why don't symlinks work? `ln -s cnf ../cnf.repo`
