### ISSUE TITLE
[launcher] Support per-bundle reference directive

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3410]
The launcher will by default try to use "reference:" url schema to install bundles into the running OSGi instance, which is much more efficient because the framework doesn't have to copy the bundles but references them in their existing locations. The `-runnoreference` directive allows you to override this if necessary.

Unless you're on Windows, in which case it will never use the "reference:" schema. The documentation mistakenly says that the default on Windows is not to use `reference:`, but the definition of `Launcher.useReferences()` will always return ~~true~~`false` on Windows. (*Edited: originally I wrote `true` when it should have been `false`.*)

There are good reasons for this. Unfortunately, the frameworks typically hold a lock on the bundles that they install, which means that you can't build them while the framework is running, which means you can't get hot updates. However, when you are testing a framework with lots of bundles there is a high startup cost associated with it.

I would like to propose a compromise implementation that allows you to specify "noreference" semantics on a per-bundle basis. So this would become an attribute of the `runbundles` property (similar to the startlevel attribute).

This would be useful because in any given test deployment, a large percentage of the bundles are quasi-static - it's really only the bundles in the Workspace repository that might change. An optimum setup on Windows would be to configure all of the Workspace bundles as "noreference" and the rest of the bundles as "reference". This way you could get 95% of the performance benefit of reference bundles but still allow your hot updates to work.

**Comment by kriegfrj** [comment]
> > but the definition of `Launcher.useReferences()` will always return true on Windows.
> 
> I am not sure I see this. Can you explain why you think this is the case? If `isWindows()` returns `true` then `!isWindows()` is `false` and `false && anything` is `false`.

Sorry, you're right, I mistyped. I should have written "always returns false on Windows". The rest of the post assumes that useReferences I is always false on Windows.

**Comment by pkriens** [comment]
I am hesitant. On modern systems the copying is very fast and this adds a lot of complexity.

Did you measure the performance difference? With fast disks I would expect it to be negligent.

**Comment by kriegfrj** [comment]
> I am hesitant. On modern systems the copying is very fast and this adds a lot of complexity.
> 
> Did you measure the performance difference? With fast disks I would expect it to be negligent.

I'll try and get some solid benchmarks for you, but anecdotally I feel it would be a useful gain with large AUTs. Eg, all the Eclipse bundles when you launch the Bndtools launch in the bnd workspace run to a couple hundred MB, from memory. Even with an SSD it takes a while to copy that much.

**Comment by pkriens** [comment]
Only measuring will tell :-) I've been wrong too many times in my life in this area to trust my intuition.

**Comment by kriegfrj** [comment]
Here are the test results:

## System spec
* Windows 10 64 bit
* i5-3470 @ 3.20GHz, 3201 MHz, 4 core, 64bit
* 8GB RAM
* 111.79 GB Kingston SV300S37A120G Solid-State Drive 

## Test procedure
* Start Eclipse, open the Bnd workspace
* Add code around this line to measure the time elapsed:
https://github.com/bndtools/bnd/blob/2e33419a937f82be7b4be670ba0e5b701c5d75e2/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L428
 My working copy looks like this:
```java
trace("calling update()");
final long start = System.currentTimeMillis();
List<Bundle> tobestarted = update(System.currentTimeMillis() + 100);
trace("update() completed in " + (System.currentTimeMillis() - start) + "ms");
```
* Launch `bndtools.core/bndtools.win32.x86_64.bndrun` with `-runtrace` enabled.

Two sets of tests were run:
1. with `useReferences()` redefined to always return true.
2. with `useReferences()` redefined to always return false.

Two sets of measurements were recorded:
1. The time as reported by the above `trace()` statement
2. The size of the generated `osgi.nnnnnnn.fw` tmp dir created in my user's private temp directory. (These don't seem to be deleted on Windows when the launcher exits - probably a file locking issue. This is normally a source of annoyance to me as it quickly fills up my small SSD, but was handy for this test.)

## Results

### With useReferences() redefined to always return true

|Run| update() completed in *n* | size of osgi tmp dir| Comment
|---:|--------------------------:|--------------------:|:---
| 1 | 20,031ms | 14.9 MB | First launch after rebuilding after adding the trace statements
| 2 |  1,023ms | 14.8 MB |
| 3 |  1,272ms | 15.8 MB |
| 4 |    726ms | 15.8 MB |
| 5 |  1,004ms | 15.8 MB |

### With useReferences() redefined to always return false

|Run| update() completed in *n* | size of osgi tmp dir| Comment
|---:|--------------------------:|--------------------:|:---
| 1 | 119,745ms |  97.0 MB | First launch after rebuilding after redefining `useReferences()` to return `false`
| 2 |  31,064ms | 176.0 MB |
| 3 |  31,450ms | 176.0 MB |
| 4 |  31,067ms | 176.0 MB |
| 5 |  30,747ms |  97.0 MB |

The two different sizes seems to depend on when/how exactly I stopped AUT.

### Other information

The bndtools.win32.x86_64.bndrun launch (including #3145, which I have in my working copy) is comprised the following bundles:

|Repository | # of bundles| % of all bundles |
|-----------|------------:|----:|
|Workspace bnd |  21 |  9% |
|EclipseOxygen | 211 | 91% |
| **Total** | **232** | **100%** |

When it comes to the dynamic update feature and building, it is unlikely that any of those 211 EclipseOxygen bundles will change during a build. It is mainly the 21 workspace bundles that might get rebuilt and/or I might like to dynamically update in a running instance.

## Conclusion

When launching a large and complicated system (eg, an Eclipse instance), with dozens of MB of bundles, there are significant performance gains to be made at startup by installing bundles by reference.

The upside of not installing by reference is that file locking does not prevent you from updating the bundles. But in a large system like an Eclipse instance, most of the bundles are quasi-static - they won't change very often (usually only when the repositories are hard-refreshed). The test system above helps to quantify this as an example: <10% of all the bundles might change during a build. I feel that the additional startup cost imposed by forcing the EclipseOxygen bundles to use noreference semantics is a high cost to pay when weighed against the rare convenience of being able to update them while the target app is running.

In the case of developing Eclipse plugins the high startup cost associated with "noreference" semantics is compounded: Normally, when working on an application using Bndtools, the dynamic update feature somewhat offsets this high startup cost as you only have to launch the application once, and from then on the workspace bundles will automatically be redeployed into the running instance as they are built without having to restart the whole instance. However, Eclipse doesn't seem to be that gracious about handling dynamic updates of plugins (which is presumably why it has to be restarted every time you install/update a new feature) - I've noticed while developing for Bndtools that if you make a change to a Bndtools bundle while the target instance is running, the launcher will successfuly redeploy your change to the target instance, but then instance will start complaining about "registry errors" and a restart will be required. I end up having to stop it and re-launch it for every little change I make to a Bndtools component. This makes the extra startup time required by "noreference" behaviour that much more painful, and the "dynamic update" upside has disappeared.

### Possible solutions
1. Use Linux or Mac
2. Some mechanism to automatically mark all bundles in Workspace repo as "noreference", and all other bundles as "reference".
3. Some mechanism to allow launch file to specify how each bundle will be loaded (the suggestion in the OP).
4. The Rolls Royce solution: tighter Bndtools integration between builder & launcher, so that the builder:
   1. can find all launched instances that are using a bundle;
   2. directs these instances to uninstall the bundle;
   3. completes the build for that bundle; and
   4. re-installs the updated bundle into the instances once the build is completed.
5. Alternative (slightly inferior) Rolls Royce solution: as a final step in the build process, the builder creates a cached working copy of all the bundles in the workspace that are used in a launch configuration. The launcher then is free to use the cached copy with reference semantics, in preference to the original. At first glance this isn't much different to allowing the launcher/framework to create the copy, but the advantage is that the copy will happen during the build process, which happens (in most cases) automatically in the background, so that by the time you launch the copy will already be ready in many cases. It also means you have to copy it once per build rather than once per launch.
6. Some combination of the above. I like the idea of a combination of 2 & 5 - use reference in-place for the quasi-static, non-workspace bundles, and then use reference in-place for the cached copy for the workspace bundles.

**Comment by pkriens** [comment]
Very nice work! Confirms again that Windows sucks :-)

There might be a very simple solution though. We can compare the file date with the installed bundle date before we update. This will work as far as I can see in all cases? 

There would still be a larger startup time but it would require no configuration and it will speed up everybody.

A Mac or Linux is of course the by far best solution :-) These Window machines are even slower than I thought.

Kind regards,

	Peter Kriens

**Comment by kriegfrj** [comment]
> Very nice work! Confirms again that Windows sucks :-)

To be fair, I haven't benchmarked on the same hardware for Linux though... Linux' advantage comes from its looser locking rules.

> There might be a very simple solution though. We can compare the file date with the installed bundle date before we update. This will work as far as I can see in all cases? There would still be a larger startup time but it would require no configuration and it will speed up everybody.

I'm pretty sure the Launcher already does this:

https://github.com/bndtools/bnd/blob/2e33419a937f82be7b4be670ba0e5b701c5d75e2/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L661-L677

This part of it works fine - updates seem to happen quickly, because usually there's only a handful of bundles actually change in any given update and the launcher won't update them if they haven't changed. The problem (for me) is at startup.

**Comment by pkriens** [comment]
But your benchmarking showed much longer times for update?

**Comment by kriegfrj** [comment]
> But your benchmarking showed much longer times for update?

I was benchmarking the "global" update() call, not the call to update an individual bundle. This update() is called at startup via the following call stack:
* main() calls launch() @ L151 
* launch() calls activate() @ L334
* activate() calls update() @ L428
 
My benchmarking code was wrapped around that call to update() in L428.

update() in turn calls synchronizeFiles() @ L510, which is what does the heavy lifting in terms of synchronizing the actual set of running bundles with the desired set of running bundles. update() is also called from the watch timer callback, but my benchmark code was benchmarking the call from activate(), not from the watch timer callback.

So the benchmark is a measure of how long it takes to install **all** of the bundles at startup.

**Comment by pkriens** [comment]
Ok, ok, you're driving a hard bargain :-)

I recently introduced a framework property that we could use. It is available as `launch.runbundles.attrs`. It contains all the `-runbundles` by bsn + attributes. The ParameterMap (a reduced version of Parameters) that can parse this is already in the launcher. So we could therefore define an `installby` attribute on `-runbundles`. 

This could then also take advantage of the decoration that takes place because attributes on `-runbundles` are awkward when you use the resolver. You could specify a decorator:

       -runbundles+     com.father.krieg.*;installby=copy,*;installby=reference

This decoration will be applied to any bundle listed in the `-runbundles` instruction, the result ends up in the `launch.runbundles.attrs` framework property to be used by the launcher update method. 

This mechanism was designed for the start levels but as I expected at the time there are other uses for it :-)

**Comment by bjhargrave** [comment]
> Very nice work! Confirms again that Windows sucks :-)

Did you disable Windows anti-virus before testing? Often the windows fs sucks on write due to AV.

**Comment by kriegfrj** [comment]
> This mechanism was designed for the start levels but as I expected at the time there are other uses for it :-)

:+1: it was exactly the startlevel syntax I had in mind as a possible solution when I raised the issue. I thought it was neat.

**Comment by kriegfrj** [comment]
> Did you disable Windows anti-virus before testing? Often the windows fs sucks on write due to AV.

A good thought - I just checked, and as far as I can tell I don't have any AV running.

Out of curiosity, I tried a bare copy of one of the 176MB osgi directories in Windows Explorer. It took ~44s  to copy the 176MB the first time. If I copy the same directory again it only takes a few seconds. Best explanation I can come up with for this is that the first copy caches the dir in memory which speeds up the second. But as a write is still required in both cases, this would suggest that the performance hit is actually on read side rather than on write???

**Comment by kriegfrj** [comment]
Ok, so I investigated further:

* Copying a single 135MB file from a network drive over Gb ethernet onto my local SSD took only a second or so. Duplicating that same file from my local SSD back onto the same SSD also took only a second or so.

* Copying the OSGi directory from Git Bash shell also took around 40s, so it's not related to the fact that I was doing the copy using Windows Explorer.

Thus the problem seems to be related to the complexity of the directory hierarchy rather than the sheer volume of data. The command `find ./ | wc -l" showed that there are 1764 files/directories in that OSGi temp directory - if it only takes 23ms to generate each file/directory that's 40s right there.

**Comment by pkriens** [comment]
– There is an anti-virus built into Windows I think
– 23 ms for creating a directory is infinite!

**Comment by kriegfrj** [comment]
Ok, after I tried a RAM disk for negligible difference, I started looking around and tried a whole bunch of hacks for Windows 10 small file copy performance tweaks. Nothing worked.

So I had a second look at the AV. It seems I mis-read it when I checked the last time (last two or three times) and it was not quite as disabled as I thought. For the benefit of posterity, the precise thing you need to disable is "Real-time protection", and you can find official instructions [here](https://support.microsoft.com/en-au/help/4027187/windows-10-turn-off-antivirus-protection-windows-security).

On my RAM disk, update() now completes in around 1-1.5s even with `useReferences()` false. On my SSD it goes up to 2-2.5s, which is still extremely tolerable compared with what I had.

Unsurprisingly, it seems to have sped up the build significantly too, so this is probably also a contributing factor to my building woes which BJ originally identified [here](https://groups.google.com/d/msg/bndtools-dev/tWn81bfRoLs/thidY-IICwAJ).

In light of this, I'm not sure if the original suggestion in this issue is still worthwhile - I think that @pkriens' comment https://github.com/bndtools/bnd/issues/3410#issuecomment-529806348 might apply. I'll leave it to you guys to figure out if you want to close this issue or else put it on the backburner.

**Comment by pkriens** [comment]
I prefer to close it to keep things as simple as possible, but I defer it to you to do the honors :-)

**Comment by rotty3000** [comment]
@kriegfrj for posterity is there no way to simply exclude certain directories from the "real-time protection"? I'd think many users would not be well served by entirely disabling it.

**Comment by kriegfrj** [comment]
Hi @rotty3000, I agree. I'm not entirely comfortable running with it disabled either.

While it seems there is a way in Windows Security to disable scanning for certain directories, it didn't seem to apply to real-time scanning. I think it applied to the periodic system scans that Windows Defender runs. But it wouldn't be the first time I hadn't fully understood Windows Security...

Also, I discovered something interesting during my experimentation: doing a `cp -r` on the OSGi tmp folder in Git bash took 30s on the RAM disk,  but `Copy-Item -Recurse` in PowerShell only took a second or so. My theory is that git bash is copying the files by manually opening/closing files using Windows API calls (which is what Equinox was doing when installing the bundles), but Copy-Item is using some kind of atomic Windows API call to perform the copy, which probably isn't subject to virus scanning (file is already on the file system). If that is the case, a workaround for launching might be to copy the bundle into a cache area using `Files.copy()` instead (which hopefully hold in to same atomic call add PowerShell's Copy-Item) and install it from there using reference URLs. I might give this a try.

**Comment by kriegfrj** [comment]
>(which hopefully hold in to same atomic call add PowerShell's Copy-Item) 

Arrgh, that's what happens when you try and post late at night on your phone... that should have read: "which hopefully hooks in to the same atomic call as PowerShell's Copy-Item".

**Comment by bjhargrave** [comment]
> If that is the case, a workaround for launching might be to copy the bundle into a cache area using `Files.copy()`

It `reference:` is not used, the framework itself does the "copying" to the framework's internal cache as part of BundleContext.installBundle. So I don't see anyway Launcher can alter this.

Or are you suggesting that the Launcher start managing its own cache and then use `reference:` from that cache? That is a lot of complexity and overhead to handle the poor performance of Windows AV. It would be far better to get Windows AV to not scan your development folders which are constantly being written to by builds. This will speed up all manner of things in development.

**Comment by kriegfrj** [comment]
> Or are you suggesting that the Launcher start managing its own cache and then use `reference:` from that cache? That is a lot of complexity and overhead to handle the poor performance of Windows AV. It would be far better to get Windows AV to not scan your development folders which are constantly being written to by builds. This will speed up all manner of things in development.

Yes, sorta, yes and yes.

But thus far I've not managed to figure out how to disable real time protection selectively, and I'm not sure how much success I'll have getting MIcrosoft to merge my PR to add the functionality...

**Comment by pkriens** [comment]
This doesn't work for you?

        https://www.windowscentral.com/how-exclude-files-and-folders-windows-defender-antivirus-scans

**Comment by kriegfrj** [comment]
> This doesn't work for you?
> 
> ```
>     https://www.windowscentral.com/how-exclude-files-and-folders-windows-defender-antivirus-scans
> ```

Thank Peter. I did try this and it didn't work. On closer reading, it seems that this exclusion only applies to whole-system scans - it won't descend into the specified directory while scanning the system. From my reading, and my test, it doesn't seem to apply to real time protection. Real time protection seems to be an all or nothing thing. (This was the mistake I made last time - I had system scanning turned off but not real time protection.)

However, I could be wrong (wouldn't be the first time!), and I'm desperate, so I might try it again... I've also made a post in the MS community forum do hopefully that will turn something up. (https://answers.microsoft.com/en-us/windows/forum/windows_10-security/selectively-disable-real-time-protection/c2b7deee-ac0d-45dd-8194-0fd4362a6285?tm=1569053085199)

**Comment by kriegfrj** [comment]
Ok, I tried the directory exclusions again. I must have done something wrong the first time around because it appears to have worked now. Even with real time protection on, I can launch  `bndtools.core/bndtools.win32.x86_64.bndrun` in around 2.5-3s off of the SSD (this would probably drop to 1s if I went back to the RAM disk, but I can live with 2.5-3s so I don't need to bother with the RAM disk).

As a bonus, I've also managed to massively speed up the build (and the builds for my own projects), and to speed up Eclipse's own startup time (through judicious use of other exclusions).

I'd like for other people not to have to go through this again. Do you guys think that it is worth having a page in the Bnd/Bndtools manual with tips for Windows users that summarises my findings? It would be fairly simple and I'm putting my hand up to write it. Just let me know where is the most appropriate place for it and I'll submit it as a fresh PR.

**Comment by pkriens** [comment]
I think you can add it to the bnd manual, maybe add a page for Windows?

**Comment by kriegfrj** [comment]
As discussed, this issue is no longer relevant given that the performance issues it was designed to solve have been solved by superior means.

Closing this issue.
