### ISSUE TITLE
Bndtools launches app in working directory other then project folder since 4.2.0

### ISSUE THREAD

**Issue by babymotte** [bndtools/bnd#3419]
Followup to #3122, the issue remains pretty much the same. When starting a bnd/maven project from eclipse with bndtools 4.1.0 the project directory is used as the working directory, when using bndtools 4.2.0 a directory inside the target folder is used as working directory.

Here's a project to demonstrate the issues with instructions in the readme:
https://github.com/babymotte/bndtools-test/

**Comment by bjhargrave** [comment]
So the maven and gradle plugins have been using a different working dir since 3.4. However Bndtools was out of fidelity with these tools. So in 4.2, we brought Bndtools inline with the maven and gradle plugins.

**Comment by bjhargrave** [comment]
We discussed this in the Bndtools maintainers call and this is the way it now is. You will need to fix your projects to not rely in the value of the working directory.
