### ISSUE TITLE
Support for Eclipse/Equinox Splash Screen in BND Launcher

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3431]
In order to get all the Eclipse RCP Developers to use BND instead of PDE, we need a support for the SplashScreen. This was at least one of the requirements I've heard all the time. 

I'm currently finalizing a first Implementation for a ProjectLauncher, that can start a bndrun with a splashscreen and also provides an export using the equinox executables. The splashscreen is pulled up, before the actual Launcher is running and a Runnable, that simply is called to end the splashscreen is handed to the Launcher. This registers it in the framework as a service and finally removes the splash, if nobody else does it. 

I had a copy of the Launcher and realized, that the changes are relatively minor and do not bring any additional dependencies. Thus I would love to integrate this in the BND Launcher, instead of maintaining a copy with myself. A PR will follow soon.

**Comment by juergen-albert** [comment]
https://github.com/bndtools/bnd/pull/3432#issuecomment-534028158

**Comment by bjhargrave** [comment]
I think we can close this since it is replaced by #3445, right?
