### ISSUE TITLE
[launcher] file: URLs get mangled on Windows during reporting

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3442]
My experience in #3410 has taught me two things: 1. that I ought not to be so patient in waiting for bnd to do things (including launch), and 2. that I shouldn't be so quick to accept "it's Windows => it sucks" as the final answer to every performance issue faced on Windows. :smile:

Having learned these valuable lessons, I turned my attention to the other part of launching that was taking a long time (though not as long as installing the bundles) but which seemed like it shouldn't: the call to `report()` once all the bundles have started. I always observed the following when launching:

* Once installed, the bundles were started fairly quickly.
* The launcher would quickly print the report header and the line containing the information about the system bundle.
* The output would then pause for several seconds.
* Finally, the rest of the report's output would appear more-or-less instantaneously.
* Though I didn't realise it at the time, there was another symptom: the "Modified" field was printed as "<>" for every bundle (no timestamps, even for file-based bundles).

Closer inspection revealed a problem in this reporting code, in particular these lines:

https://github.com/bndtools/bnd/blob/9cc7029010dc3c4637cc18eb5cf49a989cb1553f/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L1202-L1204

The intent here seems to be to see if the specified location was a real file, by parsing out the scheme and seeing if the rest is a resolvable file. The problem is that `file:` URLs on Windows typically contain a segment with a drive letter (which also includes a colon). Here is an example cut-and-paste directly from my system:

`file:/C:/workspace/bnd/cnf/cache/stable/EclipseOxygen/javax.el-2.2.0.v201303151357.jar`

The call to `String.replaceAll()` on L1203 would convert the above to the following:

`//workspace/bnd/cnf/cache/stable/EclipseOxygen/javax.el-2.2.0.v201303151357.jar`

This looks to Windows like a fully-qualified UNC path name. So the pause in the output was in the call to `f.exists()` (L1208), as the OS hit the network looking for the machine called `workspace` with a shared directory `bnd`. Mercifully, the result of this lookup failure must have been cached as the subsequent calls to `f.exists()` were quick (though if it hadn't been, possibly the performance impact would have been so high and unacceptable as to trigger an investigation sooner).

This also explains the missing timestamps in the report output - it didn't find the bundle files (as it was looking in the wrong place) and thus couldn't report their timestamps. (Having never used Bnd on non-Windows, and as this problem seems to have existed on Windows for some time, I didn't realise this was abnormal - had I known, I might have discovered this problem quicker.)

PR to follow shortly. Arguably, this should be squeezed into the upcoming release of 4.3 if possible as the impact is pretty significant.

**Comment by bjhargrave** [comment]
> in particular these lines:

That code is 9 years old: https://github.com/bndtools/bnd/commit/c858f4abf12e9d592fabe924055089f2c051eed9

It seems to be trying to remove the scheme from the front of the URI but there are better ways to do that today in Java 8.

> Arguably, this should be squeezed into the upcoming release of 4.3 if possible as the impact is pretty significant.

Since this has been there for 9 years, this is not a recent regression and probably no need to risk jamming a fix into 4.3 at this late stage.

**Comment by kriegfrj** [comment]
> > in particular these lines:
> 
> That code is 9 years old: [c858f4a](https://github.com/bndtools/bnd/commit/c858f4abf12e9d592fabe924055089f2c051eed9)
> 
> It seems to be trying to remove the scheme from the front of the URI but there are better ways to do that today in Java 8.
> 

Yes. I presume it's trying to remove the scheme do that it can handle reference: irks as well as file:.

On this topic o, is there any reason that the code couldn't simply call Bundle.getLastModified()? Is it possible this method want available at the time, it is there a specific reason for reporting the timestamp on the file directly instead? The former is slightly (bit only slightly) easier to implement.

> > Arguably, this should be squeezed into the upcoming release of 4.3 if possible as the impact is pretty significant.
> 
> Since this has been there for 9 years, this is not a recent regression and probably no need to risk jamming a fix into 4.3 at this late stage.

Ok.

**Comment by bjhargrave** [comment]
> is there any reason that the code couldn't simply call Bundle.getLastModified()

Well the time may be different. File last modified is the file time stamp, bundle last modified is the last time the bundle was installed or updated. So in the launcher, bundle last modified is (almost always) the very recent past. File last modified could be a different time stamp.

**Comment by pkriens** [comment]
We could make the `\\w`+ into `\\w\\w+`, this will skip window file characters

**Comment by pkriens** [comment]
The location is always a url but for a reference it is prefixed with reference:, see #877 install(f).
I guess the code needs to be a more complicated to properly check the modified time

**Comment by kriegfrj** [comment]
I was thinking to actually use URL class to parse it (twice for reference: URLs) and Files to do the last modified check, so we're using the latest APIs. Hopefully this will also be more portable. As it's only for report() performance isn't critical.

**Comment by bjhargrave** [comment]
> I was thinking to actually use URL class

If you plan to try this, please use the URI class instead.
