### ISSUE TITLE
Incorrect behaviour for HttpsVerification.hostnameVerify

### ISSUE THREAD

**Issue by coheigea** [bndtools/bnd#3443]
A source review has thrown up an issue with the behaviour of HttpsVerification.hostnameVerify:

- verifier = (string, session) -> verify;

If "verify" is "true", then it will always return true from this HostnameVerifier method. This is not what I would expect from setting this value to true - I would have expected it to actually properly check that the certificate is correct for the host it is being used for. If verification was turned off, then I would expect the method to return "true".

**Comment by pkriens** [comment]
The certificate verification is done in the LocalTrustManager. Since we're already matching the host in the `matches` method there is no reason to further check the name as far as I know.

**Comment by coheigea** [comment]
Hi @pkriens, the verification done in LocalTrustManager is trust verification in the TLS remote cert. However, we also need to make sure that the certificate in question is associated with the domain of the remote host, that is what the HostnameVerifier does. By just returning true we are turning off the check, which is a security hole. 

I'd suggest it just use the default HostnameVerifier if "verify" is true. So change the code to something like:

if (!verify) {
    verifier = (string, session) -> true;
}

and then only call setHostnameVerifier if it is non-null.

**Comment by pkriens** [comment]
Could you make a PR?

**Comment by coheigea** [comment]
@pkriens Yes, here it is: https://github.com/bndtools/bnd/pull/3457

**Comment by bjhargrave** [comment]
Fixed by #3457
