### ISSUE TITLE
[bndtools] make the Analyzer fail with an error if an exported package has private references

### ISSUE THREAD

**Issue by raducotescu** [bndtools/bnd#3444]
Currently the `Analyzer` logs a [warning](https://github.com/bndtools/bnd/blob/813bc1b6043d7138190decbd036d6e3402988e01/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L391) if an exported package has private references. Could this behaviour be changed to an error? See #209 and #942 for similar discussions.

The use-case is that I'd like the `bnd-maven-plugin` to fail the build if an exported API returns or uses a private reference in its non-private methods.

**Comment by pkriens** [comment]
See `-fixupmessages`

**Comment by raducotescu** [comment]
The `-fixupmessages` trick is brittle, IMO, at least in this case. Because `-fixupmessages` doesn't allow more granular parsing, for the message in question one can only write a directive like:
```
-fixupmessages:"*,  private references*"; \
    restrict:=warning; \
    is:=error
```
As soon as `bnd` will change the logged message this configuration will fail.

**Comment by raducotescu** [comment]
Figure out a way to do more granular parsing, although the docs [0] are a bit ambiguous.

However, I'd much prefer a tool configuration option rather than parsing the tool's log messages to achieve this.

[0] - https://bnd.bndtools.org/chapters/820-instructions.html#selector

**Comment by bjhargrave** [comment]
Use 

```
-fixupmessages.privateexport: "Export *,  has \\d+,  private references"; restrict:=warning; is:=error
```

in the parent pom. The if a child pom want to override, it can set `-fixupmessages.privateexport` to the empty string.

Note: `-fixupmessages` is a merged property.

**Comment by pkriens** [comment]
I do not think I want this kind of configuration ... -fixupmessages works fine so far. If we do anything (but then you need to chip in) is giving errors and warnings a number.

**Comment by raducotescu** [comment]
While using unique numbers to identify warnings and errors would simplify the `-fixupmessages` parsing a user would have to do, I still think the approach is not the nicest.

We're actually hitting this issue when using the `bnd-maven-plugin:4.2.0`. I guess the idea behind the `-fixupmessages` was that no matter which tool embedded the `bndtools`, you'd always have a central way to control what the user does in those cases where they hit a warning or an error. However, I'd argue that configuration flags would be a better option to decide which warnings should actually fail a build or which errors should be ignored.

See a similar issue in #3446, where the approach I'm asking for would be better suited and still serve all purposes.

I guess there are three major use-cases:
1. ignore an error (possibly downgrade it to a warning)
2. elevate a warning to an error
3. ignore warning and errors (which in the Maven plugins is anyways covered through `bnd.*.skip` properties)

These three cases would then need to be supported by all warning / error message types, hence why it does complicate a bit the implementation depending on how many message types you have. The gain would be that in case you decide to change the messages in a subsequent release (see [this comment](https://github.com/bndtools/bnd/issues/3446#issuecomment-535045761) for an example), the developers could still safely upgrade to the newer `bnd` release without having to verify that their `-fixupmessages` instructions are still valid.

A stupid simple idea for configuration flags (for three message types I've already encountered) would be something like:
1. `privateExport=ERROR|WARN|IGNORE`
2. `bundleVersionBaseline=ERROR|WARN|IGNORE`
3. `packageVersionBaseline=ERROR|WARN|IGNORE`

An alternative would be adding a new directive to `-fixupmessages` (`messageType`), so that a developer wouldn't have to care about the actual message when deciding to elevate or downgrade a message:

```
-fixupmessages ::= fixup ( ',' fixup ) *
fixup          ::= SELECTOR directive *
directive      ::= ';' ( restrict | is | replace | messageType )
restrict       ::= 'restrict:=' ( 'error' | 'warning' )
is             ::= 'is:=' ( 'ignore' | 'error' | 'warning' )
replace        ::= 'replace:=' <<text>>
messageType    ::= 'messsageType:=' ('privateExport' | 'bundleVersionBaseline' | 'packageVersionBaseline')
```
Example usage for this alternative:
```
-fixupmessages: "*";restrict:=warning; is:=error; messageType:=privateExport
```

**Comment by pkriens** [comment]
This would create a huge new namespace that I do not see is worth the imho massive effort. 

If someone wants to step up to help out a number (or a 4 letter code) for each message is the best solution imho.
