### ISSUE TITLE
Bndtools does not show bundles in dependencyManagement

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#3458]
Bndtools :  4.4.0.DEV-201909271833-g672b366
Maven bnd: 4.4.0-SNAPSHOT

When using maven (not the Bnd Workspace Model) Bndtools should show the dependencies of a maven project in the `Browse Repos` of the `Run` view of a bndrun file. If the maven resolver plugin is configured with `includeDependencyManagement` set to `true`, dependencies in the dependencyManagement section should  be shown too.

This behavior seems to be not working as shown in the demo repo at [https://github.com/cdelg/demo-resolver](https://github.com/cdelg/demo-resolver). In this repo the bundle `org.demo.provider` should be listed in the `Browse Repos` section, however it is not. Strangely, if I attach the resolve goal to the `package` phase, everything goes fine.

**Comment by rotty3000** [comment]
I think this is the problem:

https://github.com/bndtools/bnd/blob/master/bndtools.m2e/src/bndtools/m2e/MavenImplicitProjectRepository.java#L163-L168
