### ISSUE TITLE
bndtools error with resolve with -runstartlevels 

### ISSUE THREAD

**Issue by scottslewis** [bndtools/bnd#3469]
In bndtools 4.3 release, if the following is added to the bndrun file:

-runstartlevel:  order='sortedbyname'

And the Bndtools Resolve is started the following error dialog appears:

![image](https://user-images.githubusercontent.com/159988/66246287-17e14e00-e6c8-11e9-8d10-94300fe0bf64.png)

Similarly for the order='mergedsortedbyname'

![image](https://user-images.githubusercontent.com/159988/66246305-3f381b00-e6c8-11e9-86fc-4b224290dae4.png)

The others (random, leastdependenciesfirst, leastdependencieslast) do not show this error and appear to work properly.

**Comment by bjhargrave** [comment]
@pkriens Can you look at this? This seems to be in the support you added for runstartlevel.

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bnd/pull/3473. See the updated documentation.
