### ISSUE TITLE
Bundle task / inheritance problem when using Kotlin DSL in Gradle

### ISSUE THREAD

**Issue by pun-ky** [bndtools/bnd#3470]
Probably because of using @CompileStatic

![image](https://user-images.githubusercontent.com/10673561/66288429-77627800-e8d9-11e9-94f5-6c0ce0066329.png)

without having these methods implemented, code in Kotlin will not compile

I am not sure if it is intentional. It would be nice if both Groovy and Kotlin DSLs will work smoothly with this `Bundle` task...

fyi trying to use this as a base of building OSGi bundles in gradle-aem-plugin ; right now I am decorating JAR and calling bundleTaskConvention.buildBundle() in `doLast` https://github.com/Cognifide/gradle-aem-plugin/blob/master/src/main/kotlin/com/cognifide/gradle/aem/bundle/BundleJar.kt but instead doing that now I want to simply inherit behavior from your class

in that way, my plugin will be more integrated with your code / in my opinion it will look more nice;

greetings, Krystian

**Comment by pun-ky** [comment]
of course I could not inherit from this task, but it would be nice to have new features coming when I upgrade dependency to BND tool (if sth new will arrive to this task)

**Comment by bjhargrave** [comment]
The Bnd gradle plugin is written in Groovy and takes advantage of Groovy. It would appear from what you are saying that you cannot easily extends the Groovy class with a non-Groovy class (e.g. Kotlin). 

If this is the case, then it would seem the Bnd gradle plugin would need to be rewritten to a static types language like Java or Kotlin. I am not a Kotlin expert (and since we don't use Kotlin elsewhere in the Bnd project, I would rather not introduce it). I am also not experienced enough with writing Gradle plugins in Java. So I would need help to transition the Groovy source to Java source.

**Comment by bjhargrave** [comment]
FYI, see https://issues.apache.org/jira/browse/GROOVY-7362 where this is fixed for Groovy 3.0 which I think is the base for Gradle 6.0.

**Comment by bjhargrave** [comment]
Can you please check this again with the latest 4.4 snapshot build and Gradle 6.0.1?

**Comment by pun-ky** [comment]
Sure. I will upgrade bnd tool used by GAP in next release within few next days.

**Comment by pun-ky** [comment]
Snapshot... 😉 Ok will try.

**Comment by pun-ky** [comment]
nope, does not work with 4.4.0-SNAPSHOT nor 5.0.0-SNAPSHOT
same issue

**Comment by bjhargrave** [comment]
Looks like Gradle 6.0.1 is using Groovy 2.5.8 still. So it looks like you will need to keep waiting for Gradle to upgrade the version of Groovy.

**Comment by pun-ky** [comment]
yep

```
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.4 (Ubuntu 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OS:           Linux 5.0.0-37-generic amd64

punky@punky-desktop:~/Projects/gradle-aem-plugin$ sh gradlew --version

```

2.5.8

**Comment by bjhargrave** [comment]
Closing since this is a groovy issue.
