### ISSUE TITLE
Publish both master docs and released docs

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3475]
We need a new subdomain `bnd-master.bndtools.org` to host the docs/ folder from the master branch. We then also create a new repo to hold the released version of the docs under the current `bnd.bndtools.org` subdomain.

@njbartlett Can you please create the `bnd-master.bndtools.org` subdomain, using the same configuration as the `bnd.bndtools.org` subdomain?

**Comment by bjhargrave** [comment]
@azzazzel FYI

**Comment by rotty3000** [comment]
I'm thinking of something that handles it as a sub-directory so might not need a domain at all... gimme some time to research my idea.
