### ISSUE TITLE
[maven] bnd-*-maven-plugin cannot load additional repository except when explicitely specifying `-standalone: true`

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3509]

**Comment by rotty3000** [comment]
Omitting `-standalone` is not the same as `-standalone: true` even in scenarios where standalone is the only option (maven, non-workspace gradle).

**Comment by bjhargrave** [comment]
It seems wrong to have a special look aside just for maven plugins when -standalone: true already allows you to specify all the plugins you want in the bndrun file. It seems that if you want to specific -plugin in your bndrun files, you must also say -standalone:true. Is that too big a requirement?

**Comment by rotty3000** [comment]
I'm not suggesting to make a special case for maven or gradle plugins, I'm suggesting that calling `aQute.bnd.build.Workspace.createStandaloneWorkspace` should have the same effect whether `-standalone: true` or `-standalone` or omitting `-standalone` completely.

**Comment by bjhargrave** [comment]
We definitely need to gain agreement with @pkriens around any changes here as this was an area of disagreement in the past.
