### ISSUE TITLE
Move Eclipse base dependency to 4.10

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3513]
Currently bnd/tools is built against `Eclipse Oxygen 4.7.3a`.

However the JUnit 5 version contained in that release is rather old.

It would be nice if we could move to a more recent version of Junit5/Jupiter platform (say 1.3.x/5.3.x) which contains the bulk of recent new features.

**Comment by bjhargrave** [comment]
I have also moved the Gradle support up to 5.1. With these changes, we should also consider moving the version of the next Bnd/Bndtools release up to 5.0.0.

**Comment by kriegfrj** [comment]
It would have been a bit easier to implement `biz.aQute.tester.junit-platform` if the base Eclipse version was a bit higher. 👍

However, FYI, there should be no reason why you can't use a more recent version of JUnit 5 even while running under Oxygen - you just need to source the bundles from elsewhere (eg, from Orbit).

**Comment by kriegfrj** [comment]
> It would be nice if we could move to a more recent version of Junit5/Jupiter platform (say 1.3.x/5.3.x) which contains the bulk of recent new features.

For JUnit Platform, it would be good if we could target an Eclipse version with 1.4.x, as it is this version that gives you the stdout/stderr capture for the legacy XML reports. Unfortunately, I think this means we'd need to target Eclipse 2019-06 which might be too recent?

**Comment by bjhargrave** [comment]
@juergen-albert here is the issue for the upgrade. See the `eclipse-2018-12` branch in this repo for the index url to use.

**Comment by bjhargrave** [comment]
Here is the snippet from the branch.

```properties
-plugin.1.Eclipse:\
    aQute.bnd.repository.osgi.OSGiRepository;\
        name="Eclipse 2018-12";\
        locations="https://dl.bintray.com/bndtools/eclipse-repo/4.10/index.xml.gz";\
        poll.time=-1;\
        cache="${workspace}/cnf/cache/stable/Eclipse-2018-12",\
    aQute.bnd.repository.maven.pom.provider.BndPomRepository;\
        name="Eclipse m2e 1.10.0 Dependencies";\
        revision="org.apache.maven:maven-core:3.5.3,org.apache.maven:maven-aether-provider:3.3.9,org.sonatype.plexus:plexus-build-api:0.0.7";\
        releaseUrls="${mavencentral}";\
        location="${workspace}/cnf/cache/stable/Eclipse-m2e-1.10.0/index.xml"

```

**Comment by bjhargrave** [comment]
Close by #3574.
