### ISSUE TITLE
Repository bundle filter implementation

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3522]
Sometimes you want to pull in just a few bundles from a repository. For example, you might want to pull in just the JUnit 5 bundles from the Eclipse or Orbit repo.

This can be done by configuring a P2Repository in your workspace to point at the appropriate place, but there is a cost associated with that. For P2 in particular, it has to download all of the bundles in the repo to build the index.

Even putting the download cost aside, there are other flow-on costs. In particular, the resolver naturally takes longer to do its work the more bundles that there are to choose from. I noticed when trying to pull in the JUnit 5 bundles from an Eclipse repo that adding the Eclipse repo made a noticeable difference to the resolution times. I made a significant improvement by simply copying those few JUnit bundles into a LocalIndexedRepo and doing away with the Eclipse repo.

A way around this would be to have include/exclude filters on repos. So if, for example, I know that I'm only interested in the JUnit bundles, I could configure the Eclipse repo to only include bundles that start with org.junit. Not only would this significantly decrease the number of bundles downloaded & indexed, it would also significantly increase the resolution time.

Thoughts?

**Comment by rotty3000** [comment]
This past week working with junit5 I've been downloading the eclipse SDK 4.10 extracting it and running `bnd index -n 4.10` from the root and using that. Things still resolve in less time than I can measurably notice. I'm also waiting for @bjhargrave to build that same index for reuse here https://dl.bintray.com/bndtools/eclipse-repo/ then I could push my branch with more of the junit5 testing support on the osgi-test repo.

But yeah, a filter on the p2 repo might be an idea.

**Comment by bjhargrave** [comment]
Today you can use p2 target platform support to do this. But if someone wants to add a glob parameter to the p2 repo config, please make a PR.
