### ISSUE TITLE
Version resolution in -runbundles is buggy or inconsistent (regression?)

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#3523]
I have always assumed that bnd's interpretation of `version` as outlined for [Import-Package (10.2)](https://bnd.bndtools.org/chapters/170-versioning.html) can be used everywhere where I have a version qualifier. I have just found, however, that this is not true for `-runbundles`. Here's the list of slf4j-api versions in my repository:
![image](https://user-images.githubusercontent.com/1446020/68113396-0b812880-fef4-11e9-90f0-2de83994205c.png)
(Actually, it dates back a bit longer, but this doesn't matter in this context.)

(I'm not *absolutely* sure that there was a 1.8.0.betaX when I last tried this with bnd 4.2.0, but I think there was, that's why I've added a question mark to the regression in the title.)

With bnd 4.3.0 `-runbundles: slf4j.api;version=1.7.0` launches the framework with the 1.8.0.beta4 version. This isn't the expected behavior when looking at the "translation rules" for Import-Package statements. (Just to make absolutely sure, I also tried `version==1.7.0`, using the `=` additionally as "modifier" as the documentation -- taken literally -- suggests, but this gives me a syntax error, of course.) Using `version=@1.7.0` or  `version=1.7.0@` results in the expected behavior.

I think either `-runbundles: slf4j.api;version=1.7.0` should be fixed to translate to `-runbundles: slf4j.api;version='[1.7.0,1.7.0]'` or there should be a hint about different semantics in the `-runbundles` instruction documentation.

**Comment by pkriens** [comment]
When you use a version -runbundles bnd will seek the highest version that matches its range. In OSGi, a single version is a range of that version to infinity. 

With compile, bnd will seek the lowest version that matches.

Kind regards,

	Peter Kriens

**Comment by mnlipp** [comment]
So the interpretation of the version as described in [Versioning (end of 10.2)](https://bnd.bndtools.org/chapters/170-versioning.html) is "special" and restricted to an "import context"?

**Comment by pkriens** [comment]
> On 4 Nov 2019, at 12:35, Michael N. Lipp <notifications@github.com> wrote:
> So the interpretation of the version as described in Versioning (end of 10.2) <https://bnd.bndtools.org/chapters/170-versioning.html> is "special" and restricted to an "import context"?
> 
I am not sure what this means? 10.2 describes the parser of the VersionRange. So everywhere a range can be used, these are the rules. 

The '=' to get the exact version should work if you put quotes around the version: `version="1.2.3"`, I hope.

The low/high strategy is parameterized by the header. I.e. -runbundles and -testpath the strategy is HIGHEST and for the -buildpath it is LOWEST.

Kind regards,

	Peter Kriens

**Comment by bjhargrave** [comment]
How single versions are interpreted in Bnd depends on the context. In `-buildpath` we want to compile against the lowest matching version but when running, e.g. `-runbundles` we want to run against the highest matching version. This philosophy can be summarized as "build low, run high". So you build against the lowest version which meets your needs to enable the widest choice of versions at runtime. You run against the highest version to get the most bug fixes and features.

Note that "build low, run high" is a Bnd philosophy which is not part of an OSGi specification. But it generally makes sense for a build tool like Bnd. And is provides some useful lubrication to the build process. This is as Peter says above where `strategy=HIGHEST` is used for running (run high), and `strategy=LOWEST` is used for building (build low).

As you know, a single version when used as a version range means `[version, infinity)`. So for building you generally get what you want. But for running, you may get something much higher versioned than you expect. This is why repository curation is so important to a build. If you have too many versions of a bundle available in the configured repositories, you can end up running against versions you don't want and will need to be more precise in the version ranges you use. In this case, you can either curate 1.8.0 out of your configured repositories or use the version range `[1.7,1.8)` to prevent using version 1.8 for running.

**Comment by mnlipp** [comment]
Thanks for the explanation. The documentation of `-runbundles` etc. would certainly benefit from it. (As mentioned initially "or there should be a hint about different semantics in the -runbundles instruction documentation.").

**Comment by pkriens** [comment]
Please provide a PR

**Comment by mnlipp** [comment]
This was supposed to be the PR ("or there should be a hint about different semantics in the -runbundles instruction documentation."), but it was closed. Okay, I'll open another one.
