### ISSUE TITLE
[junit-platform tester] Pluggable test listeners

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3526]
Now that the JUnit Platform port is merged and being used, I'd like to propose a feature for consideration that I had been thinking about during development.

The current implementation of `biz.aQute.tester.junit-platform` (following in the footsteps of `biz.aQute.tester`) hard-codes the list of `TestListener`s during setup. This doesn't seem to be a particularly "OSGi" way of doing things.

I was thinking of changing this to use SCR to implement pluggable TestListeners. Then you can set up your system to add the listeners that you want. Some examples of how this might be useful:

* JUnit 5 has some nifty TestListener implementations that produce pretty output on a text console (including colours). Unfortunately they are hidden away in a package-private implementation in the `junit-platform-console` module at the moment, but there is an open feature request to make these publicly accessible (https://github.com/junit-team/junit5/issues/1963). It would be nice to be able to leverage these. I have had these working before in conjunction with `biz.aQute.tester.junit-platform` using forks of JUnit 5 and Bndtools.
* EclipseJUnitListener could be factored out and only deployed when actually needed.
* People might like to write their own custom test reporting tools. This gives them the ability to do so.

Thoughts?

**Comment by bjhargrave** [comment]
We would need to use a ServiceTracker to track TestListener services and then could add them to the listeners used for the execute method upon each invocation of the execute method.

**Comment by kriegfrj** [comment]
> We would need to use a ServiceTracker to track TestListener services and then could add them to the listeners used for the execute method upon each invocation of the execute method.

Yes, I was thinking along those lines. What about using DS so that this is automatically taken care of? Disadvantage is that it introduces an extra dependency for the tester on the DS extender bundle, which goes slightly against the lightweight, self-contained intent.

**Comment by bjhargrave** [comment]
I would not use DS here. What is the DS impl bundle is part of the test scenario? ServiceTracker would be must safer as it does not rely upon another bundle.
