### ISSUE TITLE
[tester] Tester adds itself to runbundles even if already there

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3527]
When you launch tests using the `-tester` directive, the tester bundle will add itself to the end of the `-runbundles` directive at launch time.

However, sometimes the tester bundle has already been explicitly included in `-runbundles` manually, in which case you end up with it installed twice. It would be good if the tester bundle first checked to see if it was already included before adding itself.

This behaviour is found in both `biz.aQute.tester` and `biz.aQute.tester.junit-platform`.

**Comment by bjhargrave** [comment]
Normally if you want to specify a certain tester bundle, you use `-tester` and not just put it on `-runbundles`. It may be hard to say if `-runbundles` already holds a tester since the BSN or version may vary. I think it is safest to always specify the tester with `-tester`.

**Comment by kriegfrj** [comment]
I agree that the generic case - where you could have different versions installed - is not soluble. However, the specific case where it is the exact same bundle (same path on the filesystem) should be fairly easy to solve.

There are two difficulties I have had in practice with trying to use the `-tester` directive exclusively:

1. When trying to use the resolver. Ideally, your preferred tester bundle needs to be in `-runrequires` if you want the resolver to resolve it for you, and this then means that it ends up in `-runbundles`. If we had a "bnd testresolve" command that implicitly adds `-tester` into the seed requirements prior to resolution, this perhaps could be used instead.

2. Using continuous testing + IDE. For me, this is perhaps the most pressing issue. More detail on this issue here: https://github.com/bndtools/bnd/issues/3530

**Comment by bjhargrave** [comment]
#3533 avoids duplicate paths in runbundles in the launcher.
