### ISSUE TITLE
[tester] Tester bundle exits if stopped while running in continuous mode

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3528]
If you run the tester in continuous mode, and then stop the bundle (eg, using the gogo shell), then it will call `System.exit()` and terminate the entire process.

Terminating makes sense in one-shot and automatic mode; not so much in continuous mode.

This behaviour applies to both `biz.aQute.tester` and `biz.aQute.tester.junit-platform`.

**Comment by bjhargrave** [comment]
I would like to see the whole launcher/tester process stop calling System.exit. See #2308.

**Comment by kriegfrj** [comment]
Yes, I had noticed that the tmp files don't get cleaned up properly on Windows, and it is quite annoying especially when you're running on a small SSD.

Actually, the problem in the OP is slightly different to what I thought: it's not the tester that calls exit(), but it its run() method returns and control returns back to the Launcher (`mainThread.call()`), which then exits. To achieve what I was hoping for in the OP, we'd need to change the tester not to run as a runnable. Perhaps removing this line would fix it:
https://github.com/bndtools/bnd/blob/33b36ba0fbbceae2922bc09f5e5661b9868b2f44/biz.aQute.junit/src/aQute/junit/Activator.java#L77
... or else, only set `main.thread` if running in one-shot or automatic mode.

I agree that we should move towards getting the tester to not call `exit()`, but I think that this is a separate issue.

**Comment by kriegfrj** [comment]
Ok, I've had a look at this one.

Simply removing the line that adds "main.thread=true" to the Runnable registration doesn't run. The registered runnables get run by the Launcher, and they are only run if the `main.thread` property is set to `true`.

> Yes, I had noticed that the tmp files don't get cleaned up properly on Windows, and it is quite annoying especially when you're running on a small SSD.
> 
> Perhaps removing this line would fix it:
> https://github.com/bndtools/bnd/blob/33b36ba0fbbceae2922bc09f5e5661b9868b2f44/biz.aQute.junit/src/aQute/junit/Activator.java#L77
> 
> 
> ... or else, only set `main.thread` if running in one-shot or automatic mode.

 I've had a quick look at the above, and this simple suggestion will not work.

The magic that automatically runs a registered `Runnable` service lives in the Launcher. The Launcher will only find & run runnables that have their `main.thread` property set to `true`. Removing this property means that the `run()` method is never called.

However, if you set `tester.separatethread=true`, then the Activator code will create and start its own thread rather than registering a `Runnable` service. This means that the Launcher's `exit()` call won't be executed (unless of course some other started bundle has a `main.thread=true` property set). Combined with a patch to the `OSGiJUnitLaunchDelegate` (to loop around the `accept()` call for the control port), this makes it possible to stop the tester bundle without exiting the process.

My proposal is to include this patch for `OSGiJUnitLaunchDelegate`, and then:
1. Update the tester so that if `tester.continuous=true` is set, then the `tester.separatethread` property is ignored (and `true` is assumed), or
2. Leave it as is, and the user has to remember to manually set `tester.separatethread=true` if they want to be able to restart the tester bundle without killing the process.

Thoughts?

**Comment by bjhargrave** [comment]
I think main thread support is necessary for certain test loads. For example, on macOS, the UI must be on the main thread. So if you want to test Bndtools in Eclipse, you must start the test on the main thread. So you cannot just remove main thread support in testing.

**Comment by bjhargrave** [comment]
Fixed.
