### ISSUE TITLE
[bndtools tester] Add update() to ProjectTester

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3530]
The tester implementations automatically add themselves to runbundles at launch time if specified using `-tester`. However, there is no such functionality during an update.

At the moment, when the Bndtools resource listener detects a change, it calls `update()` on the project launcher:

https://github.com/bndtools/bnd/blob/33b36ba0fbbceae2922bc09f5e5661b9868b2f44/bndtools.core/src/bndtools/launch/AbstractOSGiLaunchDelegate.java#L434

This update synchronizes the launch properties file with the project settings, but it doesn't take the `-tester` directive into account. So the tester bundle gets removed from the list of run bundles, and the launcher will uninstall the tester bundle. This is a problem when trying to do continuous testing.

The workaround at the moment is to explicitly add the tester bundle to `-runbundles` in the launch file, so that the call to `update()` keeps it. But then you end up having the tester bundle twice in the effective set of runbundles.

A better solution:

1. Add an `update()` method to `ProjectTester`.
2. Have `ProjectTesterImpl` override `update()` so that it can call `update()` on its associated launcher object, and then add itself to `-runbundles`.
3. Factor out the call to `update()` in `AbstractOSGiLaunchDelegate` so that the JUnit subclass can call `update()` on the `ProjectTester` while the Run subclass calls `update()` on the `ProjectLauncher`.

**Comment by kriegfrj** [comment]
Ok, my proposed solution isn't going to work.

The problem is that the implementation of `ProjectTesterImpl.update()` doesn't give the opportunity to update before regenerating the properties file:

https://github.com/bndtools/bnd/blob/33b36ba0fbbceae2922bc09f5e5661b9868b2f44/biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java#L164-L169

* `updateFromProject()` regenerates the runbundles from scratch. Any changes made programmatically before the call to `updateFromProject()` are ignored. So the tester needs to add itself to runbundles after the call to `updateFromProject()`. However...
* `writeProperties()` generates the launcher properties file based on the properties as they are set at the time of the call. So the tester needs to add itself to runbundles before the call to `writeProperties()`.

So for this to work, somehow the tester needs to hook into the `ProjectLauncher`'s `update()` process *after* `updateFromProject()`, but *before* `writeProperties()`. I'm not quite sure of the best way to approach this or where to add this hook in a way that is generic across different `ProjectLauncher` implementations. Thoughts appreciated.

**Comment by rotty3000** [comment]
We need to be careful that we don't break testing outside of Eclipse. I'm
less concerned with adding new capabilities like continuous testing until
we have junit5 working across the whole bnd landscape; gradle-workspace,
maven, gradle-builder.

**Comment by kriegfrj** [comment]
That is fair enough. Continuous testing is pretty important to me (that was the original trigger for me embarking on this whole project!), but now that #3527 is fixed I can use the `-runbundles` workaround and we can sit on this one for a bit.
