### ISSUE TITLE
Documentation of version handling is lacking

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#3532]
bnd's documentation provides information about version handling -- especially handling the specification of a single version -- only in section ["Versioning" (10.2)](https://bnd.bndtools.org/chapters/170-versioning.html) in the context of imports. As it has turned out in the discussion of a previous problem report (https://github.com/bndtools/bnd/issues/3523) there's more to the topic. Single version specifications are handled differently by different instructions. This should be better documented.

**Comment by bjhargrave** [comment]
Can you make a PR to enhance the docs?

**Comment by mnlipp** [comment]
I don't get it. This is the PR (problem report).

**Comment by bjhargrave** [comment]
In github parlance, this is an issue. A PR is a pull request which is what I was referring to.

**Comment by mnlipp** [comment]
Ah, sorry, PR has the fixed meaning of "Problem Report" in our organization.

But, sorry again, I'm really not the person qualified to document things that I'd like to understand by reading the documentation. I've got a rough understanding from your comment on #3532 of what you try to achieve by interpreting the version differently depending on context. But I certainly do not have the in-depth knowledge which bnd instruction is affected by this in which way.
