### ISSUE TITLE
Create a `bnd-maven-plugin:bnd-process-test` goal for creating test bundles

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3540]
Currently setting up a peer `tests` artifact takes quite a lot of setup:

```
<plugin>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>bnd-maven-plugin</artifactId>
	<executions>
		<!-- Integration Test Configuration -->
		<execution>
			<id>bnd-process-test</id>
			<phase>process-test-classes</phase>
			<goals>
				<goal>bnd-process</goal>
			</goals>
			<configuration>
				<bnd><![CDATA[
					Bundle-SymbolicName: ${project.artifactId}-tests
					Fragment-Host: ${project.artifactId}
					Test-Cases: ${classes;CONCRETE;ANNOTATED;org.junit.Test}
					-fixupmessages: "Host ${project.artifactId}=...";is:=ignore
				]]></bnd>
				<classesDir>${project.build.testOutputDirectory}</classesDir>
				<outputDir>${project.build.testOutputDirectory}</outputDir>
				<manifestPath>${project.build.testOutputDirectory}/META-INF/MANIFEST.MF</manifestPath>
			</configuration>
		</execution>
	</executions>
</plugin>
```
Most of this is boiler plate. There are a few variants that would need to be parameterized but the bulk could be reduced to something like:
```
<plugin>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>bnd-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>bnd-process-tests</id>
			<goals>
				<goal>bnd-process-tests</goal>
			</goals>
			<configuration>
				<testCases>${classes;CONCRETE;ANNOTATED;org.junit.Test}</testCases>
			</configuration>
		</execution>
	</executions>
</plugin>
```
The `maven-jar-plugin` already contains a `test-jar` mojo that aligns well with this that creates an artifact with default qualifier `tests`.
```
<plugin>
	<artifactId>maven-jar-plugin</artifactId>
	<executions>
		<execution>
			<id>test-jar</id>
			<goals>
				<goal>test-jar</goal>
			</goals>
			<configuration>
				<archive>
					<manifestFile>${project.build.testOutputDirectory}/META-INF/MANIFEST.MF</manifestFile>
				</archive>
			</configuration>
		</execution>
	</executions>
</plugin>
```

**Comment by rotty3000** [comment]
Should the tests artifact by a fragment?

I always make the tests bundle a fragment so that it can share package visibility and have visibility of internals. I'm wondering if this could/should be parameterized with a default of `true`?

**Comment by rotty3000** [comment]
Also will have to fix bndtools.m2e to acknowledge the new goal to configure `jar:tests-jar` execution.

**Comment by bjhargrave** [comment]
> <testCases>${classes;CONCRETE;ANNOTATED;org.junit.Test}</testCases>

This is what I have developed for OSGi:

```properties
testcases.junit3 = ${classes;EXTENDS;junit.framework.TestCase;CONCRETE}
testcases.junit4 = ${classes;HIERARCHY_ANNOTATED;org.junit.Test;CONCRETE}
testcases.junit5 = \
 ${classes;HIERARCHY_INDIRECTLY_ANNOTATED;org.junit.jupiter.api.Test;CONCRETE},\
 ${classes;HIERARCHY_INDIRECTLY_ANNOTATED;org.junit.jupiter.api.RepeatedTest;CONCRETE},\
 ${classes;HIERARCHY_INDIRECTLY_ANNOTATED;org.junit.jupiter.params.ParameterizedTest;CONCRETE},\
 ${classes;HIERARCHY_INDIRECTLY_ANNOTATED;org.junit.jupiter.api.TestFactory;CONCRETE},\
 ${classes;HIERARCHY_INDIRECTLY_ANNOTATED;org.junit.jupiter.api.TestTemplate;CONCRETE}

testcases = ${sort;${uniq;${testcases.junit3};${testcases.junit4};${testcases.junit5}}}
```

We may want to define a configuration enum for this or determine the JUnit version in use from inspection of the environment since there can be multiple JUnit versions in use.

**Comment by bjhargrave** [comment]
> Should the tests artifact by a fragment?

I am not sure this is a best practice. Having direct, package access is important for unit tests. But OSGi level testing should be more black box testing from outside of the bundle.

**Comment by rotty3000** [comment]
A very common practice is making tests in the same package. Won't you end up in split package scenarios? I wouldn't like to enforce using a different package.

**Comment by bjhargrave** [comment]
> A very common practice is making tests in the same package

Yes, for unit testing. And you can do that in the unit testing phase of the build. But when you are OSGi testing and running in the OSGi framework, I think you are a different level of testing than unit testing and you are more black box testing: Call the service; does it do what was expected.

**Comment by rotty3000** [comment]
this change of thinking will break all my tests...

**Comment by rotty3000** [comment]
I'd like to at least make if a possibility.

**Comment by bjhargrave** [comment]
I am not telling you that you are wrong. It is more about what I think the default for OSGi testing should be, That is a distinct bundle which tests other bundles rather than a fragment of one bundle which whitebox tests the internals of that bundle.

**Comment by timothyjward** [comment]
> But when you are OSGi testing and running in the OSGi framework, I think you are a different level of testing than unit testing and you are more black box testing: Call the service; does it do what was expected.
👍 Bundle testing should not involve poking the internals of your bundle at all, if it does then you're writing a unit test, not a bundle test.
