### ISSUE TITLE
Mechanism to Report false Plugin properties

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3544]
Today I spend 2 hours to find out, why my BndPomRepository wasn't downloading some dependencies from my remote release Repository. It turned out, that I named the release repository URL with releaseUrl not releaseUrl**s**  The overall Configuration was valid, but I had no change of realising what the problem has been. 

Thus I would be great if we would have our Plugins report any property, that will not be used by the plugin it configures. I guess the Reporter would be the weapon of choice here!?

**Comment by pkriens** [comment]
In this case I am not sure what to report? Missing property? It is not required since you can also specify a GAV. 

Second, where to report to? We only have the workspace but they tend to be ignored. I've got a branch with a lot more reporting on the repositories and then allow the GUI to show them.

Not a trivial problem

**Comment by juergen-albert** [comment]
> In this case I am not sure what to report? Missing property? It is not required since you can also specify a GAV.
In the case I've described a warning/error saying e.g "releaseUrl is no supported attribute" would have been helpful. 

> Second, where to report to? We only have the workspace but they tend to be ignored. I've got a branch with a lot more reporting on the repositories and then allow the GUI to show them.

I would place it on the build.bnd or in the repositories view. What every is the easier way.

**Comment by bjhargrave** [comment]
Need a PR to propose a solution.
