### ISSUE TITLE
[gradle] gradle builder plugin doesn't support configuration of any jar tasks besides ones called exactly `jar`

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3551]
For example, if someone applies the plugin:
```
	id("com.github.johnrengelman.shadow")
```
the `shadowJar` task cannot be configured to emit an OSGi bundle.

**Comment by bjhargrave** [comment]
The `biz.aQute.bnd.builder` plugin is intended and designed to only mutate the default`jar` task created by the `java` plugin. If the user want additional bundle tasks, they can be created using the `Bundle` task type. If the user wants `Bundle` task type behavior on some jar type tasks created by some other gradle plugins, they can apply the `BundleTaskConvention` to those tasks.

So it is not the purpose of the `biz.aQute.bnd.builder` plugin to apply the `BundleTaskConvention`  convention to all tasks of type `Jar`.

In the example above, the user is able to apply the `BundleTaskConvention`  convention to the `shadowJar` task or to all tasks of type `Jar`.
