### ISSUE TITLE
[tester] Incomplete JUnit output in Eclipse

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3559]
I noticed while using the old tester in automatic mode recently that often the test process would complete and exit but the JUnit display in the GUI was still pending/incomplete. It was clear from the console output that all the tests had run.

I suspect that this is an issue of `System.exit()` being used and so the `EclipseJUnitReport` is somehow missing its last chance to flush.

**Comment by bjhargrave** [comment]
I have not personally observed this. Can you look into this?

**Comment by kriegfrj** [comment]
Hmm, I can't seem to reproduce this one anymore either.

I just upgraded to 2019-09, I'm not sure if this is why the problem has gone away. Again, I'll keep an eye on it.

**Comment by kriegfrj** [comment]
Just saw it again while running the tests in osgi-test. Also, this happened with the junit-platform tester, not the old tester. Seemed to happen regularly; will try and investigate.

**Comment by kriegfrj** [comment]
A bit of an update: I have not been actively investigating this, but anecdotally I think I have observed that this doesn't happen with my own development (which is a plain Bndtools using a Bnd workspace). It only seems to happen when I'm working on `osgi-test` (which is using Maven-Bnd).

I've also seen it happen with both the old tester and with the junit-platform tester (but both on osgi-test).

I'm not sure if the use of Maven is in any way significant contributor of this issue, but at the moment it's the only thing I've identified that's different.

@rotty3000 & @bjhargrave , have you noticed this issue when running the integration tests for osgi-test under Bndtools?

**Comment by rotty3000** [comment]
To be completely honest I'm not entirely sure what _automatic mode_ is. If you enlighten me on the steps to do that I'm happy to test since I'm using bnd-maven quite a lot. What I have been noticing is that there's intermittent issues with the detection of tests for the purpose of  showing test launch shortcuts in the context menu but I'm sure that's not related.

**Comment by kriegfrj** [comment]
Automatic mode means without `tester.names` set. Practically speaking, this means when you launch from the project or bndrun file, as opposed to launching from the context menu on a specific class or method.

The issue manifests as the JUnit output in Eclipse appearing to stop part-way through, even though on the console output it is apparent that the tester ran to completion.

**Comment by rotty3000** [comment]
got it, so no I have not experienced partial or incomplete test results, unless the test framework somehow failed it some other way, which would have been attributable to the partial results.

**Comment by bjhargrave** [comment]
I am not sure how to run the bnd maven plugin tests in Eclipse (osgi-test repo). For the other projects with standard unit tests, the junit display seems normal to me.

One way it could be incomplete is if there are race conditions sending the data to Eclipse from the test process such that the "finished" data arrives out-of-order. Perhaps the timing of thread context switching on Windows can surface this. This may be why you see it and Ray and I don't?

**Comment by rotty3000** [comment]
>  am not sure how to run the bnd maven plugin tests in Eclipse (osgi-test repo).

Right click on any test resource, such as class or package in `src/test/java`, or the bndrun files and choose `Run|Debug As > Bnd OSGI Test Launcher (JUnit)`

**Comment by rotty3000** [comment]
For Junit5 project there's one more step because it's in a profile, so you need to:
Right click on the project in `Project/Package Explorer > Maven > Select Maven Profiles...` and set `bnd-next` for Junit5 and parent projects.

**Comment by bjhargrave** [comment]
OK, got junit4 test to run. But junit5 test run hangs. With `-runtrace: true` in `test.bndrun` I see

```
Id    Levl State Modified      Location
0     0   ACTIV <>            System Bundle
1     1   ACTIV 201912051927  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.junit5/target/tmp/resolve/test/cnf/cache/5.0.0/Eclipse%202018-12%20(4.10)/org.apiguardian-1.0.0.v20181005-1442.jar
2     1   ACTIV 201908040444  reference:file:/Users/hargrave/.m2/repository/org/assertj/assertj-core/3.13.2/assertj-core-3.13.2.jar
3     1   ACTIV 201912051929  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.junit5/target/tmp/resolve/test/cnf/cache/5.0.0/Eclipse%202018-12%20(4.10)/org.junit.jupiter.api-5.3.1.v20181005-1442.jar
4     1   ACTIV 201912051928  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.junit5/target/tmp/resolve/test/cnf/cache/5.0.0/Eclipse%202018-12%20(4.10)/org.junit.jupiter.engine-5.3.1.v20181005-1442.jar
5     1   ACTIV 201912051928  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.junit5/target/tmp/resolve/test/cnf/cache/5.0.0/Eclipse%202018-12%20(4.10)/org.junit.platform.commons-1.3.1.v20181005-1442.jar
6     1   ACTIV 201912051929  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.junit5/target/tmp/resolve/test/cnf/cache/5.0.0/Eclipse%202018-12%20(4.10)/org.junit.platform.engine-1.3.1.v20181005-1442.jar
7     1   ACTIV 201912051928  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.junit5/target/tmp/resolve/test/cnf/cache/5.0.0/Eclipse%202018-12%20(4.10)/org.junit.platform.launcher-1.3.1.v20181005-1442.jar
8     1   ACTIV 201706201528  reference:file:/Users/hargrave/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar
9     1   ACTIV 201912051928  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.junit5/target/tmp/resolve/test/cnf/cache/5.0.0/Eclipse%202018-12%20(4.10)/org.opentest4j-1.1.1.v20181005-1442.jar
10    1   ACTIV 201912111304  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.common/target/org.osgi.test.common-1.0.0-SNAPSHOT.jar
11    1   INSTL 201912112057  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.junit5/target/org.osgi.test.junit5-1.0.0-SNAPSHOT-test.jar
12    1   ACTIV 201912112057  reference:file:/Users/hargrave/git/osgi-test/org.osgi.test.junit5/target/org.osgi.test.junit5-1.0.0-SNAPSHOT.jar
13    1   ACTIV 201912111943  reference:file:/Users/hargrave/.m2/repository/biz/aQute/bnd/biz.aQute.tester.junit-platform/5.0.0-SNAPSHOT/biz.aQute.tester.junit-platform-5.0.0-SNAPSHOT.jar
```

which implies the test fragment is not resolved. Some of the `-runbundles` seem to not have been installed like bytebuddy and mockito. They were not the right versions. So I had to resolve the `test.bndrun` file and then it would work.

The junit5 project test result display in Eclipse was odd though. I am not sure what the 3 levels of nesting means.

<img width="409" alt="Screen Shot 2019-12-11 at 16 09 30" src="https://user-images.githubusercontent.com/277682/70660858-0d47b580-1c31-11ea-9950-c876f5652a40.png">

**Comment by rotty3000** [comment]
The nesting is a Junit5-ism that I actually am not sure I can really appreciate. 

I think this has something to do with the fact that a fragment is a child of a bundle and @kriegfrj was trying to capture that.

Third level of nesting indicates which engine was used for a given set of tests and I assume that if you had junit3-4 tests they would come up as being run within the vintage engine.

**Comment by bjhargrave** [comment]
For the junit4 project, the display looks normal and the bar is green.

<img width="409" alt="Screen Shot 2019-12-11 at 16 33 10" src="https://user-images.githubusercontent.com/277682/70662335-04a4ae80-1c34-11ea-84a5-42e1ddf68241.png">

For the junit5 project, there is definitely something odd. The bar grows to full green as the test succeed and then, sometimes, goes back to all grey at the end.

**Comment by bjhargrave** [comment]
Ooo! Just saw the green bar go back to grey on the junit4 project tests now.

**Comment by bjhargrave** [comment]
I wonder if this is an m2e related issue?

**Comment by rotty3000** [comment]
the nesting is even worse if you run just a single test:
![Screenshot from 2019-12-11 16-44-07](https://user-images.githubusercontent.com/146764/70663053-8517df00-1c35-11ea-9288-9b980899ba6f.png)

**Comment by rotty3000** [comment]
and what's with the different timing values?

**Comment by kriegfrj** [comment]
> Ooo! Just saw the green bar go back to grey on the junit4 project tests now.

That's it. If you have a look at the last nodes in the hierarchy are probably showing still pending (grey).

If it is an m2e thing, I'm not sure how as I think the JUnit Launcher is 100% Bndtools?

**Comment by kriegfrj** [comment]
> the nesting is even worse if you run just a single test:
> ![Screenshot from 2019-12-11 16-44-07](https://user-images.githubusercontent.com/146764/70663053-8517df00-1c35-11ea-9288-9b980899ba6f.png)

This is a manifestation of #3581 and needs to be fixed.

The different timing values are because the test was actually run twice; I'm assuming the second run was faster due to the caches being primed by the first run.

**Comment by kriegfrj** [comment]
> The nesting is a Junit5-ism that I actually am not sure I can really appreciate.
> 
> I think this has something to do with the fact that a fragment is a child of a bundle and @kriegfrj was trying to capture that.
> 
> Third level of nesting indicates which engine was used for a given set of tests and I assume that if you had junit3-4 tests they would come up as being run within the vintage engine.

Correct.

The BundleEngine produces the hierarchy bundle-> engine -> <engine's own hierarchy>, or
Host bundle -> fragment -> engine -> <engine's own hierarchy>

If a class has both jupiter and vintage tests, it will appear under both engine's nodes.

This could be simplified for common cases - e.g., don't show the engine node when there's only one engine installed, or don't show the bundle when only one test bundle is installed. But when you've got more than one engine it can be important to know which engine ran your test.

**Comment by kriegfrj** [comment]
> > the nesting is even worse if you run just a single test:
> > ![Screenshot from 2019-12-11 16-44-07](https://user-images.githubusercontent.com/146764/70663053-8517df00-1c35-11ea-9288-9b980899ba6f.png)
> 
> This is a manifestation of #3581 and needs to be fixed.
> 
> The different timing values are because the test was actually run twice; I'm assuming the second run was faster due to the caches being primed by the first run.

Also, it's probably a little more confusing here because in this project the test fragment actually has the same `Bundle-Name` as the host bundle. Its `Bundle-Name` should be set to `org.osgi:org.osgi.test.junit5-test` or even "JUnit 5 Module Tests` or something like that. I'm not sure if this is a bug in the m2e implementation, or else a bug in the way `org.osgi.test.junit5` has been configured?

**Comment by bjhargrave** [comment]
> That's it. If you have a look at the last nodes in the hierarchy are probably showing still pending (grey).

![image](https://user-images.githubusercontent.com/277682/70717481-6f99c800-1cbc-11ea-9a42-9d7022f300bd.png)

No. You can see the last node has a green check while the bar at the top is grey. So it seems all tests were reported as successful (the count at the top confirms this). Yet the bar goes from full green to full grey at the end. Not sure how to debug this...

**Comment by bjhargrave** [comment]
> Also, it's probably a little more confusing here because in this project the test fragment actually has the same `Bundle-Name` as the host bundle.

Perhaps Bundle-Name is not the best choice here? The default for the bnd-maven-plugin is `${project.groupId}:${project.artifactId}` which means it is generally not useful unless the user sets it. Bundle-SymbolicName may be better.

**Comment by kriegfrj** [comment]
I'm happy to change the tester to use bsn rather than name. But writer quite separately from that, shouldn't the bnd-Maven-plugin generate a name for the test fragment that is not identical to the name of the host? By simply appending "tests" to it or something like that?

**Comment by rotty3000** [comment]
How does the bnd-maven-plugin know it's a test bundle?

When we finally get the bnd 5.0.0 `bnd-maven-plugin:bnd-process-tests mojo sure, but we don't have that released yet!

**Comment by rotty3000** [comment]
also, Bundle-Name not a particularly high priority header. Also, it can actually be misleading. The bsn is far more likely to look like something you have in your project explorer.

**Comment by kriegfrj** [comment]
> How does the bnd-maven-plugin know it's a test bundle?
> 
> When we finally get the bnd 5.0.0 `bnd-maven-plugin:bnd-process-tests mojo sure, but we don't have that released yet!

Forgive my bnd-maven ignorance. :smile: In that case, we should probably fix osgi-test to generate the correct `Bundle-Name`.

**Comment by kriegfrj** [comment]
> also, Bundle-Name not a particularly high priority header. Also, it can actually be misleading. The bsn is far more likely to look like something you have in your project explorer.

The gogo command lb & ss seem to use Bundle-Name if set, otherwise Bundle-Symbolic-Name. I was following their lead. But the argument for bsn is compelling.

**Comment by bjhargrave** [comment]
> I suspect that this is an issue of `System.exit()` being used and so the `EclipseJUnitReport` is somehow missing its last chance to flush.

You were right on here. I think the connection was closed or the VM stopped before the Eclipse client received the test run end message. The slight .25 sec delay I added after sending the test run end message makes it very reliable on my machine. I used the osgi-test project's test bndruns as my test env.

**Comment by kriegfrj** [comment]
> You were right on here. I think the connection was closed or the VM stopped before the Eclipse client received the test run end message. The slight .25 sec delay I added after sending the test run end message makes it very reliable on my machine. I used the osgi-test project's test bndruns as my test env.

I think I was close, but not quite 100% there.

I looked at this code closely, and it seemed apparent that there was no way that exit() could be being called before the flush() that happens after the %RUNTIME message is sent. According to the docs, flush doesn't return until the os has actually sent all the data. So my working hypothesis is that the tester didn't exit before sending all of the data, however on the Eclipse side of the connection Eclipse was noticing that the child process had exited and was shutting down the `RemoteTestRunnerClient` before it had finished processing the data from the EclipseJunitReporter/Listener. I hadn't gotten around to testing this hypothesis yet - if it checks out, then that could be a more robust way of fixing this issue. In the meantime, it looks like your simple delay is crude but effective. It should do the job for 5.0, and worst case we can look at something more robust for 5.1.

**Comment by bjhargrave** [comment]
I suspect that the issue is not that our code did not send or flush the test run end message, but that we end up closing the connection immediately thereafter and that the Eclipse client reacts to that connection closing before it reads and reacts to the sent test run end message. So the slight delay allows some time for the Eclipse client to read and react to the sent test run end message before it observes and reacts to the connection being closed by our code.

See https://github.com/eclipse/eclipse.jdt.ui/blob/3dd606caa9285a2d0bc7f458df1dff6c43cfc2d9/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/model/RemoteTestRunnerClient.java#L263-L281. Closing of the connection could result in throwing a SocketException before the read loop has read, and processed, the test end run message.

Since the communications protocol does not appear to be a 2 way protocol, there is no way for our code to know that the Eclipse client code has read and reacted to the sent test run end message such that we know it is then safe to close the connection. That is, the communications protocol does not allow for the Eclipse client to send us an ACK response to our sent test run end message.

So I am not sure of how we could easily improve things.

**Comment by kriegfrj** [comment]
> I suspect that the issue is not that our code did not send or flush the test run end message, but that we end up closing the connection immediately thereafter and that the Eclipse client reacts to that connection closing before it reads and reacts to the sent test run end message.

Yes, that's what I meant. :+1: 

> So I am not sure of how we could easily improve things.

It must be possible somehow because the built-in Eclipse JUnit tester also uses RemoteTestRunnerClient and it doesn't have this issue. I also vaguely recall having the same issue causing some of the unit tests to be flaky.

The JUnit launch delegate might be able to do something, eg register a test listener in Eclipse and wait for the test to end before shutting down. There's also the crude two-way comms protocol I developed to facilitate the continuous testing.

Suffice it to say, I'm not keen to give up just yet. :smile:

**Comment by kriegfrj** [comment]
I've been having a bit of a think about this one over the Christmas break.

The question arose in my mind: why do Eclipse's built in JUnit testers not suffer from this problem? I realised that this is probably because the `RemoteTestRunner` protocol is actually bi-directional: After sending all of the initial test run data to `RemoteTestRunnerClient`, the application-under-test doesn't exit but sits and waits for test re-run requests (which are triggered in Eclipse by right-clicking on a test and selecting "Run", or by clicking one of the "Rerun test" buttons in the JUnit pane's toolbar). If our tests implemented test rerun functionality, then it should fix this race condition at shutdown as a side effect. As a I might create a new issue for this.

**Comment by bjhargrave** [comment]
> After sending all of the initial test run data to `RemoteTestRunnerClient`, the application-under-test doesn't exit but sits and waits for test re-run requests

Can this be true? For remote debugging, Eclipse does not create the remote process and cannot control the lifetime of the remote process. For plain JUnit test, yes, Eclipse will create and manage the process. But for other remote debugging, like OSGi JUnit, Eclipse just opens a port for the remote process to connect with.

**Comment by kriegfrj** [comment]
> Can this be true? For remote debugging, Eclipse does not create the remote process and cannot control the lifetime of the remote process. For plain JUnit test, yes, Eclipse will create and manage the process. But for other remote debugging, like OSGi JUnit, Eclipse just opens a port for the remote process to connect with.

Yes, it's definitely this way for plain JUnit tests, but now that you mention it I'm not sure how the lifecycle works with Eclipse's built-in OSGi JUnit support. I'll try and investigate when I get the chance.
