### ISSUE TITLE
[tester] Unresolved test passes

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3561]
While working on osgi-test, I added a new dependency to a test but forgot to add it to `-runbundles`.

Instead of running the normal suite, the tester ran the `aQute.junit.UnresolvedTester` test, as expected. However, the test passed, which is not expected - the test should fail.

**Comment by bjhargrave** [comment]
@kriegfrj Can you look into this?

**Comment by kriegfrj** [comment]
Wouldn't you know it, when I went to try and reproduce this the problem didn't manifest?

I did update my Bndtools to head, but nothing (to my knowledge) should have affected this. I'll keep an eye out and if I see it again I'll try and jump on it straight away before it has time to escape. :smile:

**Comment by bjhargrave** [comment]
Closing for now since the problem seems to have gone away.

**Comment by kriegfrj** [comment]
Ok, this just popped up again by accident and I managed to figure out the problem: it happens if you have an unattached fragment. This is because `UnresolvedTester` loops through all bundles with a state "INSTALLED" (using equality and not a bitmap test either, mind you! :wink:), and then *if they are not fragments* it will attempt to start them and capture any resultant BundleException that might arise from a resolution failure. So if the only unresolved bundles are unattached fragments, then it won't attempt to start them in the first place and no failure be detected and `UnresolvedTester.testAllResolved()` will pass.

Having had a closer look at this code the implementation seems to have a few other flaws. Aside from minor things like using equality rather than bitmap testing for bundle state, I don't think it's technically correct as it assumes that `INSTALLED` = "failed to resolve" when technically it could also mean "not *yet* resolved". I guess this happens rarely because in practice most frameworks are pretty eager about trying to resolve installed bundles, but if the tester happens to catch a bundle at that split second when the bundle has been installed but not yet resolved, then there is also a chance that it might trigger the `UnresolvedTester` only to have it pass.

I'm not inclined to bother trying to fix these problems. `biz.aQute.tester.junit-platform` has already fixed them, and then some - eg, it will report each resolution failure as a separate test failure (making it easier to see what happened), as well as reporting each unattached fragment. But at least if someone else has the need to scratch this itch, they can use this as a reference.
