### ISSUE TITLE
baseline maven plugin - "Excessive version increase" warning missing

### ISSUE THREAD

**Issue by stefanseifert** [bndtools/bnd#3563]
when using bnd via the `maven-bundle-plugin`, the baseline report generated a WARNING message when a package version was increased more then necessary ("excessive").
Example with `maven-bundle-plugin` (generated using [this branch](https://github.com/apache/sling-org-apache-sling-servlet-helpers/tree/experimental/excessive-version-increase-bundle-plugin)):
```
[INFO] --- maven-bundle-plugin:3.5.0:baseline (baseline) @ org.apache.sling.servlet-helpers ---
[INFO] Baseline Report - Generated by Apache Felix Maven Bundle Plugin on 2019-11-14T15:14Z based on Bnd - see http://www.aqute.biz/Bnd/Bnd
[INFO] Comparing bundle org.apache.sling.servlet-helpers version 1.2.1-SNAPSHOT to version 1.2.0
[INFO]
[INFO]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS
[INFO] = ================================================== ========== ========== ========== ========== ==========
[INFO] < org.apache.sling.servlethelpers                    minor      1.7.1      1.6.0      1.7.0      Excessive version increase
[INFO]      < class org.apache.sling.servlethelpers.MockSlingHttpServletRequest
[INFO]          + method adaptTo(java.lang.Class)
[INFO]              + return java.lang.Object
[INFO]      < class org.apache.sling.servlethelpers.MockSlingHttpServletResponse
[INFO]          + method adaptTo(java.lang.Class)
[INFO]              + return java.lang.Object
[INFO]      - version 1.6.0
[INFO]      + version 1.7.1
[INFO] -----------------------------------------------------------------------------------------------------------
[WARNING] org.apache.sling.servlethelpers: Excessive version increase; detected 1.7.1, suggested 1.7.0
[INFO] Baseline analysis complete, 0 error(s), 1 warning(s)
```

when the same baseline check is applied using the `bnd-baseline-maven-plugin` no warning is generated.
example using `bnd-baseline-maven-plugin` (with [this branch](https://github.com/apache/sling-org-apache-sling-servlet-helpers/tree/experimental/excessive-version-increase-bnd-baseline)):
```
[INFO] --- bnd-baseline-maven-plugin:4.3.0:baseline (bnd-baseline) @ org.apache.sling.servlet-helpers ---
[INFO] Determining the baseline version for org.apache.sling:org.apache.sling.servlet-helpers:jar:(,1.3.0-SNAPSHOT) using repositories [apache.releases.https (https://repository.apache.org/service/local/staging/deploy/maven2, default, releases+snapshots), central (https://nexus-proxy-berlin.pro-vision.de/content/groups/default, default, releases+snapshots), apache.snapshots (https://repository.apache.org/snapshots, default, snapshots)]
[INFO] The baseline version was found to be 1.2.0
[INFO] Baselining check succeeded checking org.apache.sling:org.apache.sling.servlet-helpers:jar:1.3.0-SNAPSHOT against org.apache.sling:org.apache.sling.servlet-helpers:jar:1.2.0
[INFO]
```

it was my impression that this excessive version check was a feature of bnd itself, not an addition by `maven-bundle-plugin`. is it a bug that no warning is generated using the `bnd-baseline-maven-plugin`?

**Comment by rotty3000** [comment]
This is more about what heuristic you apply to the data you are given. The data is produced by the baseline plugin, but bnd-baseline-maven-plugin may have opted not to be interested in that piece of data. Whether this is really ideal or not is up for debate I would imagine :) On the other hand baseline is just that _a base line_ and not an tyrannical overlord. It's goal is to manage to lower bound for you, but the upper bound is totally your choice.

**Comment by stefanseifert** [comment]
agreed - however a warning (not a failure) has proven very useful in my bundle projects to avoid accidentally increasing the package versions when it was not intended (nor needed)

i can come up with a PR for it as well - together with a switch to switch it off (you can decided whether you want to have it by default on or off)

**Comment by bjhargrave** [comment]
> it was my impression that this excessive version check was a feature of bnd itself

No. There is no semantic versioning failure to decide to increment the major version by 8 on everything :-) That is your choice as the developer. Baselining is to find and flag semantic versioning failures were a change from the baseline is not properly recorded in the current version.

So any feature addition for warning about "excessive" version increases would need to be an opt-in switch. That is, the default behavior should be the current behavior which is not to warn about "excessive" version increases.

Also, any change here must also work for Gradle plugins and Bndtools in Eclipse. We need to maintain parity in function between the different drivers (Bndtools in Eclipse, Maven, Gradle) so we don't end up with disjointed behaviors in the different drivers. We want to maintain fidelity.
