### ISSUE TITLE
[junit-platform tester] tester.names causes imported tests to unexpectedly run in the wrong bundle 

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3581]
The `BundleEngineSelector` looks for named classes in each of the bundles by calling `loadClass()` on the bundle. This typically works well, but you can run into issues when using `tester.names` filtering and bundles that import *.

For example, suppose that you have the Groovy Runtime bundle in your installed bundles. This bundle has a `DynamicImport-Package: *` declaration.

Now, if you fire off a one-shot test for (say) `my.test.MyTest` in the bundle my.test.bundle, then the bundle engine will run the test twice:

1. Once as part of `my.test.bundle`;
2. Once as part of the Groovy Runtime bundle.

See attached image.
![DuplicateTest](https://user-images.githubusercontent.com/7224087/69024741-fdfb9080-0a13-11ea-9e2f-1039276f1a6c.png)

**Comment by kriegfrj** [comment]
Another manifestation of this problem is when you have a test fragment: because the fragment's tests are visible to the host's classloader, they get loaded & run under the host bundle (and probably under all fragments too if you've got others, as they all share the same classloader).

**Comment by kriegfrj** [comment]
One possible solution to this problem is to skip the class loading attempt, and rely solely on the `Test-Classes` header to find test classes. The disadvantage of this approach is that you have to make sure your `Test-Classes` header is correct - the current implementation is a little more forgiving.

Opinions? @bjhargrave ? @rotty3000 ?

**Comment by bjhargrave** [comment]
> One possible solution to this problem is to skip the class loading attempt, and rely solely on the `Test-Classes` header to find test classes.

I think this is the proper solution when NOT using a specified `tester.names` property. We must assume the test bundles are properly built so that when they include a test class, we can load that test class from that bundle (or its host if it is a fragment).

When in `tester.names` property mode, then we have to look around to find the test class since we don't have a pointer to a bundle that will supply the test class. Dynamic import * can confuse us, but I also don't think any test bundle should really be exporting the packages holding test classes. These packages are really impl detail of the bundle and should not be exported.

**Comment by kriegfrj** [comment]
Sorry, I don't think I explained myself properly re: the `tester.names` case.

You're right - at the moment, tester.names doesn't tell us which bundle the class is in (I had an idea for a syntax that would include that, like `bsn:version:fqTestClass#testMethod(param1,param2)`, but that can be the subject of another issue). So yes, we have to examine each bundle to see if it contains the test we're looking for. What I was proposing was, instead of trying to find the right bundle by using `loadClass()` to see if the class loads, we could instead look in the `Test-Cases` header.

The idea of not exporting the test classes is a good one which I will implement; however that alone won't solve the issue completely. Eg, in the test fragment case, for any given host bundle with *n* test fragments, each test in each fragment will be run *n + 1* times (once under each fragment and once under the host bundle). I don't see an easy way around this other than directly examining the `Test-Cases` header.

**Comment by rotty3000** [comment]
Yeah, I think finding a test should be predicated by bundles having a test
header. Otherwise it's like a needle in a haystack.

**Comment by kriegfrj** [comment]
> Yeah, I think finding a test should be predicated by bundles having a test header. Otherwise it's like a needle in a haystack.

Well, it's more like finding a needle in a hall of mirrors... we don't seem to have trouble finding them, but which one's the real one? 🙂

**Comment by bjhargrave** [comment]
> I had an idea for a syntax that would include that, like `bsn:version:fqTestClass#testMethod(param1,param2)`, but that can be the subject of another issue

I don't think this is generally possible or useful. No one will type this on the command line of gradle/maven and it wont be part of the Eclipse selection of test classes/methods.



> What I was proposing was, instead of trying to find the right bundle by using `loadClass()` to see if the class loads, we could instead look in the `Test-Cases` header.

Yes. This is also what I mean. When looking for test class `com.acme.Foo`, don't ask each bundle if it can load the class. Instead, ask each bundle's Test-Cases header if it includes the class name and, if it does include the class name, then use that bundle.

**Comment by bjhargrave** [comment]
So maybe we need to make a pass across all the bundle's Test-Cases headers to make a map of test class name to bundle (host bundle in case of a fragment's Test-Cases header). Then we can quickly identity which bundle holds which test class name.

**Comment by kriegfrj** [comment]
> So maybe we need to make a pass across all the bundle's Test-Cases headers to make a map of test class name to bundle (host bundle in case of a fragment's Test-Cases header). Then we can quickly identify which bundle holds which test class name.
> 
> This will be useful when using `tester.names` or not.

:+1: Sounds good. Although I think that in the case of a fragment you should still map to the fragment bundle rather than the host. Otherwise we'll see the test classes listed as children directly under the host bundle rather than as grandchildren under the fragment child. Just need to make sure we use the host bundle when actually attempting to load the class (easily done using `getHost()`).

Is the `Test-Cases` header intended to include class names only? Or is it anticipated that it might have fully-qualified method names too? If the latter it complicates things a bit.

**Comment by bjhargrave** [comment]
The `Test-Cases` header only includes class names. There are no plans to include method names in the header's value.

**Comment by bjhargrave** [comment]
> Although I think that in the case of a fragment you should still map to the fragment bundle rather than the host.

OK, Makes sense.

**Comment by kriegfrj** [comment]
> > I had an idea for a syntax that would include that, like `bsn:version:fqTestClass#testMethod(param1,param2)`, but that can be the subject of another issue
> 
> I don't think this is generally possible or useful. No one will type this on the command line of gradle/maven and it wont be part of the Eclipse selection of test classes/methods.
>

You're probably right. If it comes up we can investigate - it wouldn't be hard to add.
