### ISSUE TITLE
Resolve handles snapshot bundles differently in bndtools 4.3 than in 4.2

### ISSUE THREAD

**Issue by tobigun** [bndtools/bnd#3584]
The resolve behavior of snapshot bundles is different between bndtools 4.3 and 4.2.

To reproduce:
1. add a dependency to a snapshot bundle to the ```-runrequires``` section of a bndrun file:
e.g. ```osgi.identity;filter:='(osgi.identity=<bundlename>)'```
2. press the resolve button in the Eclipse bndtools plugin view of the bndrun file
3. the bundle dependency is now written as ```<bundlename>;version=[0.1.0,0.1.1)``` into the ```-runbundles``` section of the bndrun file

With bndtools 4.2 ```<bundlename>;version=snapshot``` was written to the ```-runbundles``` section.

A side effect of this change is that the change from "snapshot" to "[0.1.0,0.1.1)" is  recognized as a version change and all snapshot bundles are reordered in the resolve process.

It is unclear whether this is a bug or the desired behavior.

**Comment by pkriens** [comment]
Are you sure this was not done with Gradle? I am looking into this because also have bug #3387.

I am working on always making it snapshot but I am not sure I understand why this was different in 4.2?

**Comment by tobigun** [comment]
> Are you sure this was not done with Gradle?

Just tested it again with bndtools 4.2. and a simple workspace that only has one bundle.
runrequires contains "bnd.identity;id='application'" which becomes "application;version=snapshot" in the runbundles list after resolution.

So it is "snapshot" in bndtools 4.2 and it does not seem to be related to Gradle.

**Comment by pkriens** [comment]
Thanks Tobias, that helped. I just fixed it.

**Comment by pkriens** [comment]
Fixed in #3585

**Comment by tobigun** [comment]
Hello Peter,
Thanks for fixing this.

In which release version was the fix included? Seems as if bndtools 5.0.1 still has the changed behavior.

**Comment by bjhargrave** [comment]
There were a number of fixes required to get this right. It should all be properly fixed in 5.1.0 which was just released.
