### ISSUE TITLE
[bndtools.m2e] Bnd OSGi Test Launcher quick launch doesn't appear

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3587]
When using Bndtools via m2e in Eclipse, the quick-launch menus don't appear for tests. I find these useful when I'm working on a particular test class/method and I know from conversations here that others do too.

I'm guessing this is because these projects don't have the Bndtools nature.

It would be nice if m2e could step in and re-enable these quick launch menu items for maven projects that have the bnd-maven-tester plugin configured.

**Comment by rotty3000** [comment]
This was fixed by https://github.com/bndtools/bnd/issues/3576 (I know the
name of that issue doesn't help make the connection, when I filed the
ticket I thought it was something else.)

**Comment by bjhargrave** [comment]
So we can close this?

**Comment by rotty3000** [comment]
@kriegfrj if you find my fix didn't solve your issue, you can reopen this with more details.
