### ISSUE TITLE
SingleTestExecutor is deprecated in updated Eclipse JUnit 5 dependencies

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3600]
The type SingleTestExecutor is deprecated in the updated Eclipse JUnit 5 dependencies.

@kriegfrj Can you work to solve the deprecation warnings by fixing the code to use the replacement?

Thanks.

**Comment by kriegfrj** [comment]
Hmm, the documentation for the replacement frustratingly points to a method that is package private. I've raised an issue on the JUnit site: junit-team/junit5#2113.
