### ISSUE TITLE
bnd-run-maven-plugin: implicit maven repo

### ISSUE THREAD

**Issue by maggu2810** [bndtools/bnd#3609]
Hi,

the content of the implicit Maven repository can be manually configured using Maven dependencies of the respective scope and by a list of bundles that resides in the file system.
(https://github.com/bndtools/bnd/tree/master/maven/bnd-run-maven-plugin#configuration-properties)

I like the usage of Maven coordinates a lot as.
But there is one point I am missing.

Using the dependencies (+ management) only does not allow to use the same groupId artifactId combination with different versions.

Think about that use case:

* you need to use bundle_a and bundle_b in your runtime.
* both bundle requires bundle_c. 
* bundle_a needs a bundle_c version that fits in the range [1,2)
* bundle_b needs a bundle_c version that fits in the range [2,3)

We could add a dependency (dfl. scope runtime) for
`group.id/artifact.id-bundle.c/1.1.0` and `group.id/artifact.id-bundle.c/2.5.0` but one of both will win as there could be only one version per groupId + artifactId.

Would it be possible to add an `artifactItems` section to the plugin configuration that allows to add further Maven coordinates. This way, you could add the artifact references in this section and could use multiple versions of the same bundle (without the need to place them in some folder, use the `bundles` configuration and ...).

* `artifactItems` contains a list of `artifactItem`
* `artifactItem` consists of
  * groupId: mandatory
  * artifactId: mandatory
  * version: mandatory
  * type: optional
  * classifier: optional

For the example above the configuration could look like:

```
<artifactItems>
    <artifactItem>
        <groupId>group.id</groupId>
        <artifactId>artifact.id-bundle.c</artifactId>
        <version>1.1.0</version>
    </artifactItem>
    <artifactItem>
        <groupId>group.id</groupId>
        <artifactId>artifact.id-bundle.c</artifactId>
        <version>2.5.0</version>
    </artifactItem>
</artifactItems>
```

WDYT?

**Comment by rotty3000** [comment]
This sounds like enough of an edge case and solvable by using a [pom repository](https://bnd.bndtools.org/plugins/pomrepo.html) in the bndrun:

```
-standalone: true
-plugin.other.revision = \
    aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
        releaseUrls=https://repo.maven.apache.org/maven2; \
        revision='group.id:artifact.id-bundle.c:2.5.0'; \
        name=OtherVersion
```

Also, are you very sure that both those versions are not ending up in the implicit repo?

**Comment by maggu2810** [comment]
> Also, are you very sure that both those versions are not ending up in the implicit repo?

That's should be the normal case for Maven dependency management.

I tested it again (I used guava here but the bundle itself does not matter)

If the dependency section looks like:

```
  <dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>23.1-jre</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>27.1-jre</version>
      <scope>runtime</scope>
    </dependency>
```

the version 27.1-jre will be part of the implicit repo.
If the dependencies order are rotated 23.1-jre is part of the implicit repo.

The last one wins.

> This sounds like enough of an edge case

Really? Isn't it such uncommon to rely on 3rd party bundles that use another third party library in different major versions?

If I do not use the POM file but setup additional repositories in the bndrun file it works:

```
-standalone: true
-plugin.v23.1-jre = \
    aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
        releaseUrls=https://repo.maven.apache.org/maven2; \
        revision='com.google.guava:guava:23.1-jre'; \
        name=v23.1
-plugin.v27.1-jre = \
    aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
        releaseUrls=https://repo.maven.apache.org/maven2; \
        revision='com.google.guava:guava:27.1-jre'; \
        name=v27.1
```

So, okay for me if it should not be solved by the maven plugin but the general bndrun file's repository handling.

Thanks!

**Comment by rotty3000** [comment]
Question: Is it maven that is causing the normalization of these dependencies, or is it bnd while creating the implicit repo?

**Comment by maggu2810** [comment]
For the normal Maven dependency handling the "only one version per groupId + artifactId" is done by Maven itself.
If you follow the "standard" Maven dependency handling this is the normal behaviour.
So, I would say: It is Maven that is causing the normalization.

**Comment by maggu2810** [comment]
Look at "Dependency mediation" on this page: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies

**Comment by rotty3000** [comment]
Got it! That seems to fall inline with how OSGi experts I've prompted on the subject feel about the issue. Multiple versions of a dependency should be enough of an outlier that you _should_ consider it as a special case. In this way I really think bnd maven plugins should not try to do more about this. I suspect on the gradle side it'd be even harder.

**Comment by maggu2810** [comment]
If I'd read [the page](https://bnd.bndtools.org/plugins/pomrepo.html) earlier, I wouldn't have asked. :wink:

**Comment by rotty3000** [comment]
It's all good! Keep the contributions coming (issues are contributions).

**Comment by maggu2810** [comment]
One further question:

The "Bnd Pom Repository" plugin page states:

"The pom can be a file on the local file system, a URL, a group, artifact, version (GAV) coordinate, or a query expression on maven central."

I assume this points to the different properties:

* file on local file system or a URL => `pom`
* a group, artifact,version (GAV) => `revision`
* query expression => `query` (to be precise it does not need to be Maven Central as this can be changed by `queryUrl`)

Just for my understanding:

If I use a pom on the local file system, the dependency section of the pom (with respect to the scope) is used.

I a GAV is used, you need to point to a "JAR" file that (and dependent on `transitive` its dependencies) are used.

Is this correct:
There is no way to use a "pom.xml" coordinate to fetch the "pom" (not "jar") from a Maven repository and use that's dependencies.

At least a short look at the code seems (if my reading has been correct) that query only respect jar files.

**Comment by pkriens** [comment]
Just use the `revision` property. This is a Revision (GAV) and will be used to fetch the POM from the given repositories.

In general, if you use a revision (GAV) then the context decides the extension, ie. pom.

Kind regards,

	Peter Kriens

**Comment by maggu2810** [comment]
Can you please answer to this question if my observation has been correct? If not, I will create a simple reproducable example and a separate issue:

If I use the BndPomRepository configuration as stated above and reference a GAV by the revision parameter, it is always resolved from the Maven repository (local or remote) but not from the workspace if opened.
Or should also an opened project (e.g. Maven + bnd plugins) inside the Eclipse IDE be used similar as it is done if the Application uses a implicit Maven repository?

**Comment by bjhargrave** [comment]
BndPomRepository is about providing resources from remote repositories. BndPomRepository will never look in the local workspace for a resource.
