### ISSUE TITLE
Macro usage

### ISSUE THREAD

**Issue by maggu2810** [bndtools/bnd#3617]
As I did not know how to test or debug the macro handling (how is a macro replaced) I used the following simple approach:

1. Add to the bndrun file something like that:

```
-runvm: --fail-because-of=${macro_that_value_i_would_like_to_know}
```

2. Click in the Eclipse IDE on "Run OSGi" and inspect the error message in the console view.

This works e.g. for `${now}`
The line `-runvm: --fail-because-of=${now}` will result into the following message in the console view:

```
Unrecognized option: --fail-because-of=Fri
```

So, today `${now}` will be replaced by "Fri".

If I do the same for `${ee}` and `${maven_version}` -- both macros listed on https://bnd.bndtools.org/chapters/855-macros-ref.html -- I get a popup that contains a message like:

```
Status WARNING: bndtools.core code=0 No translation found for macro: ee null
```

Further notes: I am using a Maven based setup.

Why do the macros not working?

**Comment by pkriens** [comment]
If you use the bnd command line you can do:

$ bnd help shell
NAME
  shell                       - 

SYNOPSIS
   shell [options] ...


OPTIONS

   [ -p, --project <string> ] - Identify another project

$ bnd shell
Base Workspace [bnd]
> ${p}
bnd
> p
bnd
> foo=10
> foo
10
> tstamp
201911290828
> ${tstamp;YYYY}
2019
> foo=${1} ${1} ${1}
> ${foo;aaa}
aaa aaa aaa
> 
 
The -p option also takes a bndrun file. The ./cnf/build.bnd and the bnd files in the ./cnf/ext directory are always inherited.

Hope this helps. Kind regards,

	Peter Kriens

**Comment by maggu2810** [comment]
@pkriens Thanks for your reply.
If I read your comment here https://groups.google.com/d/msg/bndtools-users/GQb-50si8cc/R8UYnvK_BgAJ correctly `${ee}` can be used "Only when you start the VM".

Perhaps https://bnd.bndtools.org/chapters/855-macros-ref.html can be improved at which stage the variable can be used.

**Comment by pkriens** [comment]
The execution environment is a _requirement_ on the VM, it does not steer it. The executable JAR takes whatever VM it has been invoked with, after which the EE is verified to match the running VM.

I.e. we delegated the choice of the VM to the environment. We could start digging around once started (with a low Java version code) to find a better VM (I think Gradle does this) but this takes time and is highly environment sensitive. It is easier to do this in shell script or some Go code. It might be interesting to standardize this, and we can host this in bnd, but it is not something commercially interesting to me right now. However, PRs are welcome.

Kind regards,

	Peter Kriens

**Comment by bjhargrave** [comment]
I don't think there is a defect here. This is a usage question which should be discussed in the mail list.
