### ISSUE TITLE
[bndtools tester] Wait for build to finish before update

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3623]
A common use case I've had while developing using continuous testing:

Suppose that you have a bundle-under-test B, and a test bundle T.

1. Launch continuous testing framework (including B and T).
2. Make a change to B - Bndtools automatically rebuilds B.
3. `AbstractOSGiLaunchDelegate's resource listener notices the change to B and updates the running framework.
4. B is restarted during this update, and because T depends on B, T also restarts during the update.
5. junit-platform tester's `BundleListener` notices that T has restarted, and re-runs its tests.
6. Meanwhile, Bndtools is continuing to rebuild the dependencies of B, so T is also rebuilt shortly afterwards. 
7. `AbstractOSGiLaunchDelegate` notices T's change and reinstalls (and restarts T).
8. Tester notices that T has changed again and runs the test again.

A similar thing happens if there are any other bundles (and their test bundles) dependent on B.

It's a little bit disconcerting when all of this happens, and in the case where you have dependent bundles and their own tests you'll probably want to see them all together in the test output (rather than coming in one-at-a-time as currently happens).

I think the best solution for this is to wait for Bndtools to finish building before updating the running framework.

**Comment by bjhargrave** [comment]
> I think the best solution for this is to wait for Bndtools to finish building

Bndtools has an incremental builder which builds one project. The overall building of all projects is controlled by Eclipse and not Bndtools. So Bndtools itself has no idea when building is finished. So I don't know how you can know when Eclipse has finished building. You will need to look for how this can be known.

**Comment by kriegfrj** [comment]
> > I think the best solution for this is to wait for Bndtools to finish building
> 
> Bndtools has an incremental builder which builds one project. The overall building of all projects is controlled by Eclipse and not Bndtools. So Bndtools itself has no idea when building is finished. So I don't know how you can know when Eclipse has finished building. You will need to look for how this can be known.

I discovered that the Eclipse JobManager has hooks for syncing with other background jobs (including the Eclipse build manager).

I have submitted a PR for this (#3672) which worked in my testing. Let me know if you see any problems with it.
