### ISSUE TITLE
"Add Bndtools Project Nature" not completely working

### ISSUE THREAD

**Issue by Xeratul** [bndtools/bnd#3629]
Bndtools 4.3.1.REL-201911131708-g281e71d
Possibly related to #2961

How to reproduce:
1. Use a working bnd workspace 
2. Create a new java project in eclipse 
    (make sure it's actual location is next to the cnf folder)
3. Right click project and choose "Configure" > "Add Bndtools Project Nature"
    (.classpath and .project files are correctly modified, empty bnd.bnd file is created)
4. Add any bundle from "Repositories" Part to the Build Path of the new bnd.bnd file.
    Bnd Bundle Path entry is not showing up, required bundles can not be used by own classes, nothing working.
5. Hit all clean, rebuild and reload buttons available, nothing changes. However after restarting eclipse it works.

Since it works when you use "File" > "New" > "Bnd OSGi Project" I checked the source code and found that the following thing is executed on "new project" but not on "add nature":

**bndtools.central.Central.getWorkspace().refreshProjects();**

After a test where i only executed this line after the nature adding everything works perfectly. So my suggestion would be to add this line to "Add Bndtools Project Nature" code.

**Comment by juergen-albert** [comment]
I will have a shot at this
