### ISSUE TITLE
Eliminate logging to System.err

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3631]
There are several places where bnd logs to `System.err`.

`aQute.bnd.maven.support.Pom`
`aQute.bnd.maven.support.ProjectPom`

This output is unmanageable so we should move these to slf4j API.

**Comment by rotty3000** [comment]
.. or just remove the output altogether.

**Comment by kriegfrj** [comment]
The testers have a couple of places where they log to `System.err`, but @pkriens was reluctant to introduce a dependency on slf4j for such low-level components (https://github.com/bndtools/bnd/pull/3145#issuecomment-503580840).

**Comment by bjhargrave** [comment]
> reluctant to introduce a dependency on slf4j for such low-level components

Correct, we don't want that. The embedded launcher, launcher, and tester (code running in the launched JVM) must not depend upon slf4j.
