### ISSUE TITLE
Allow tracking the sources of wrapped jars and inlined resources

### ISSUE THREAD

**Issue by rombert** [bndtools/bnd#3640]
bnd allows us to easily wrap jars and inline classes in a bundle through various mechanisms. At times, it becomes useful to find out where the classes from a specific bundle are coming from, for instance:

- debuggers that reconstruct the source path dynamically at runtime
- SDK generators that will build javadoc for whole applications

When these kinds of tools discover inlined classes at runtime they have no idea where they're coming from. Since practically all artifacts contain Maven metadata , the typical mechanism is to look for a corresponding "-sources" jar. But most of the time that artifact does not contain the source classes as well.

It would be great if bnd, when wrapping/inling, would add a track of where it has picked up the external resources from, so that the trail can be resconstructed by other tools.

**Comment by pkriens** [comment]
with `-sources true` the sources are packaged in the JAR itself in OSGI-OPT/src as recommended by the OSGi spec. This is supported by Eclipse out of the box and I'd expect also by Intellij since this is an OSGi standard.

If you release this bundle through the BndMavenRepository plugin then sources are automatically created like Maven.

**Comment by rombert** [comment]
Thank you for the pointer to `-sources true`. I think this will be harder to push for adoption with other projects, mainly because Maven, as the _de facto_ standard for packaging, already has a `sources` classifier.

I think what would be more tenable would either be:

- copying over all `META-INF/maven/**/pom.{xml.properties}` files when inlining/wrapping
- adding a dedicated bundle manifest header which lists the GAV of the embedded/inlined bundles

**Comment by bjhargrave** [comment]
I don't think it is a good idea to copy the maven metadata from other jars into the new jar. They you cannot easily tell from inspecting the jar what its GAV is.

The second choice is better from the above perspective. However, it will require work to collect the information.

I am not sure why -sources: true cannot work. Doing this does not preclude sources classified artifacts as well.

**Comment by rombert** [comment]
FWIW I just tried `-sources true` on a project and it does not embed the sources for packages included via `-conditionalpackage`. Not sure if that is intended or a bug.

The differences that I see between embedding sources and referencing the artifacts in the manifest are:

- size ( smaller concern ) - emebdding sources makes jars larger
- interoperability - if we have a defined header set we can define it via other tools as well, or manually. with sources we can only do this via bnd

**Comment by pkriens** [comment]
Were the sources included via the -conditionalpackage visible? I.e. it will not find them from a JAR that does not contain sources itself or another project.

**Comment by rombert** [comment]
No, the sources were not visible. Actually, I picked a wrong example, since the packages that were inlined come from a jar that has no sources.

But from your reply I understand that `-sources` jars are not considered when packaging source code with `-sources true`. Is that correct?

**Comment by pkriens** [comment]
When -sources is true, bnd does a best effort to pack the sources. It looks in the source folders and in the OSGI-OPT/src directory for matching sources.

PK

**Comment by rombert** [comment]
Ack. So it won't work for our scenario unfortunately, as we mostly wrap third-party bundles - our own have proper OSGi metadata. Being able to add the header would work though.

Would adding such a header be an option? I am thinking about something like:

```
Inlined-Package-Sources: com.foo.bar=com.foo:foo-bundle:1.2.0,com.foo.baz=com.foo:baz:1.4.0
```

(Did not think too much about names, but I think the data that we need is all there).

**Comment by pkriens** [comment]
Most maven artifacts have source JARs. If you use the MavenBndRepository you can add the source in the mvn file:

     foo.bar:foo.bar.example:1.2.3
     foo.bar:foo.bar.example:jar:sources:1.2.3

You should be able then to add to your `bnd.bnd` file:

     src = src/main/java, ${repo; foo.bar:foo.bar.example:jar:sources;1.2.3}

Alternatively, this might also work:

     -includeresource OSGI-OPT/src=@${repo; foo.bar:foo.bar.example:jar:sources;1.2.3}

**Comment by rombert** [comment]
> If you use the MavenBndRepository

I assume this comes by default if I use the `bnd-maven-plugin`

> you can add the source in the mvn file (...)

I added the sources jar to the pom.xml, but then they got included in the jar as class files, and bnd complains about split packages.

>  src = src/main/java, ${repo; foo.bar:foo.bar.example:jar:sources;1.2.3}

This did not unfortunately have any effect

>  -includeresource OSGI-OPT/src=@${repo; foo.bar:foo.bar.example:jar:sources;1.2.3}

Although the syntax looks correct to me, the build fails with

```[ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:4.2.0:bnd-process (bnd-process) on project org.apache.sling.scripting.jsp: bnd error: Unclosed group near index 9
[ERROR] \$(?:repo```

Not sure if I did something wrong, you can see the latest changes at https://github.com/apache/sling-org-apache-sling-scripting-jsp/commit/2103b8bdee4021d4b2789249db9302ff325ac592 ( still part of the bnd-sources-true branch )

**Comment by pkriens** [comment]
Oops. I do not use the maven plugins, the workspace with Gradle is soooo much nicer :-)

This stuff is all different since Maven handles the class path in your case. Maybe one of the other guys can help you.

**Comment by rombert** [comment]
Ack, thanks @pkriens :-)
