### ISSUE TITLE
[Launchpad] BundleBuilder.addConfiguration should add the Configurator requirement

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3654]
I understand that the configuration added, should be a json as specified by the Configurator Spec!? If so, it would make sense to automatically add the osgi.extender with ```requireCapability("osgi.extender").attribute("filter" , "(osgi.extender=osgi.configurator)")``` to the bundle.

**Comment by juergen-albert** [comment]
Taking a deeper look into this, I must admit, that I have no clue what kind of configuration this should be. It will always be added as ```configuration/configuration.json``` which is not the Configurator Spec conform place. I would opt for making this compatible with the Configurator Spec.

**Comment by pkriens** [comment]
No, this is the original configurer from enroute that was the inspiration of the configurator. I guess we should change it to the configurator.
