### ISSUE TITLE
[junit-platform tester] Check for mixed JUnit 3/4 tests

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3671]
If a test class contains JUnit 4-style `@Test` annotations *and* extends from `junit.framework.TestCase` (JUnit 3-style), then the engine will silently ignore the `@Test`-annotated tests and only run those that start with `testXXX()` (JUnit-3 style).

Although JUnit 3 is old, there are still quite a few tests out there using it and getting migrated to 4 or 5. The above is a trap that can make you think that your tests are all passing when really there are a bunch that aren't running at all.

The old tester had code to check for and warn of this situation:

https://github.com/bndtools/bnd/blob/a116b9446ff64fa3d90e7c7880b5832c70bb96d2/biz.aQute.junit/src/aQute/junit/Activator.java#L513-L518

I was hoping that the JUnit Team might add similar support to the Vintage engine (as this is surely not an issue that is unique to Bnd testing), but they have recently declined this request (junit-team/junit5#1964) as they see it as a legacy issue.

So we should perhaps consider adding this check to `BundleEngine` too, if we think this is still a case that is likely to catch people out.

**Comment by bjhargrave** [comment]
Yes, we should detect this condition and report a test failure.
