### ISSUE TITLE
gradle plugin: Bundle tasks that work with gradle 4.10.3, fail with versions 5 and 6

### ISSUE THREAD

**Issue by paul-ecan** [bndtools/bnd#3674]
gradle tasks of type aQute.bnd.gradle.Bundle that run fine under gradle 4.10.3, fail under 5.6.4 and 6.0.1 with errors like...
```
> Task :bundle_1 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bundle_1'.
> No value has been specified for this provider.
```

[build.gradle.zip](https://github.com/bndtools/bnd/files/3981292/build.gradle.zip)

**Comment by bjhargrave** [comment]
I think this is the same as https://github.com/bndtools/bnd/issues/3672. 

The workaround is to make sure the either that `project.version` is set or that the `jar.archiveVersion` is set.

**Comment by paul-ecan** [comment]
Excellent, that works! (the gradle stacktrace gave me no useful hint to what was going on)
