### ISSUE TITLE
Replacement for maven-bundle-plugin`s Embed-Dependency

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#3704]
There are IMHO two different bnd instructions which ease embedding of third party code

1. https://bnd.bndtools.org/instructions/conditionalpackage.html and
2. https://bnd.bndtools.org/instructions/includeresource.html

While the former works pretty well with the `bnd-maven-plugin` (as it acts on the classpath being populated by the Maven Plugin) the latter works only on the filesystem and therefore requires to dig into the Maven repository or otherwise first copying from the Maven repo to some other path (e.g. with <https://maven.apache.org/plugins/maven-dependency-plugin/copy-mojo.html>). In some cases one really wants to have the full Jar embedded (either inline, i.e. exploded or as embedded Jar with an according enriched Bundle-Classpath header), without knowing all included packages. It would be really nice to have an easy way to embed full Jars as being given on the Maven dependency classpath.

**Comment by rotty3000** [comment]
@kwin you _can_ refer to classpath dependencies with `-includeresource`

Assuming a typical classpath dep you can refer to it by filename (i.e. `<artifactId>-<version>.<extension>`) like so:

```
-includeresource: -includeresource: openwebbeans-impl-[0-9.]*.jar;lib:=true
```

**Comment by kwin** [comment]
Ah perfect then, it is even documented it is just that the amount of options is kind of overwhelming...

**Comment by rotty3000** [comment]
> the amount of options is kind of overwhelming...

totally! Any suggested improvements would be very welcome! ;)

**Comment by ehimsi** [comment]
I do have a suggestion - please include the info mentioned in this forum ticket https://groups.google.com/forum/#!topic/bndtools-users/NAdU0_X8OKY . This looks really useful.

Thanks
Himanshu
