### ISSUE TITLE
Missing dependencies in launch

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3716]
While working on head, when trying to launch a test Eclipse instance using `bndtools.win32.x86_64.bndrun`, I get the following Launch Problems reported at launch time:

![Missing deps](https://user-images.githubusercontent.com/7224087/72491561-54494c00-386a-11ea-8d26-74556e61cbb4.png)

I have verified that these deps are indeed not present in any of the repositories.

There is still a fair bit that can be tested without these modules, because if I ignore it and continue I can still seem to test what I'm working on (mostly the tester). However I think they are runtime requirements of the templating module.

@bjhargrave, can we add these to the list of included packages for our Eclipse 2018-12 subset?

**Comment by bjhargrave** [comment]
It looks like https://github.com/bndtools/bnd/commit/e40c5189d8078e4872e51a0e4483136fbcb41759 broke this when @rotty3000 added m2e support. Resolving fails for me due to missing deps in the repo. I'll try and add the missing deps and see if I can get resolving working.

**Comment by kriegfrj** [comment]
I guess the alternative then is if we don't need them in the Eclipse test instance, we can simple remove them from `-runrequires` and `-runbundles`. I guess we need @rotty3000 to confirm if they were added on purpose, or else if it was some kind of fork/merge conflict that re-introduced them accidentally.
