### ISSUE TITLE
Missing documentation for parameterized Header-Annotation

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#3719]
There is a way to have parameterized Header-Annotation using a not documented bnd feature.

(Reminder @juergen-albert )

https://github.com/bndtools/bnd/blob/cf3e1780b76469df87aabde80fc814c104d33e7d/biz.aQute.bndlib.tests/test/test/annotationheaders/custom/CustomA.java#L18-L32

I think it is not part of the OSGI-Spec (maybe it should) and i didn't find an public documentation from bnd

https://github.com/bndtools/bnd/blob/735c647e91e4314ea1f8c438a4c832ce63135254/docs/_chapters/230-manifest-annotations.md

**Comment by bjhargrave** [comment]
I think it is documented here: https://bnd.bndtools.org/chapters/235-accessor-properties.html

**Comment by stbischof** [comment]
Thank you @bjhargrave.
