### ISSUE TITLE
bnd finds 2 contracts in bundle that provides only 1 if `-contract` instruction is parameterized

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3726]
The `org.apache.geronimo.specs:geronimo-jaxrs_2.1_spec:1.1` contains a single contract in the namespace `JavaJAXRS`. However, bnd is reading this contract two times when the `-contract` instructions is parameterized to make the requirement optional. This causes an error when requirements are added to a client bundle.

for example: a client bundle uses N contracts, 1 of which is JavaJAXRS, but jaxrs should not be a hard requirement because the packages are imported `resolution:=optional`. However, when parameterizing the `-contract` instruction to make it optional like:

```
-contract: JavaJAXRS;resolution:="optional", *
```
an error occurs because the contract is read 2 times by the contract collection logic.

**Comment by rotty3000** [comment]
The only workaround is to _not_ use `*` naming each contract explicitly and parameterizing the ones that require it.

**Comment by bjhargrave** [comment]
Perhaps you should mention the issue # and the workaround in the Known Issues section of the 5.0 changes wiki page?

**Comment by rotty3000** [comment]
done!
