### ISSUE TITLE
[builder] arraycopy index out of bounds on utf

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3730]
Getting this error on building:
![ArrayCopyError](https://user-images.githubusercontent.com/7224087/72859086-9400af80-3d12-11ea-8a12-47befcd8024f.png)

Unfortunately I don't seem to have a stack trace in this error report and I'm not familiar enough with the builder code to know here it might be. I'm not even sure if it is Bndtools' fault (the error suggests it might be Eclipse's JavaBuilder, but as I understand it the JavaBuilder is under the control of BndtoolsBuilder?).

I suspect that the problem is that my source has a multi-byte character in it, and somewhere the builder code has assumed that # of bytes = # of chars.

**Comment by pkriens** [comment]
Yup, it is the Java builder, it runs before the Bndtools builder. You might find the stack trace in the 'Error' view.
