### ISSUE TITLE
resolver seems to ignore Import Packages wit attached Bundle Symbolic name

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3748]
The bndtools.core bundle has a lot of Imports that are bound to a specific Bundle like:

```org.eclipse.ui.browser;bundle-symbolic-name="org.eclipse.ui.browser";bundle-version="[3.6,4)"```

If I throw the bundle in a single bndrun with this as runrequire and hit resolve, org.eclipse.ui.browser will not be part of the resolved bundles. The Import of the package org.eclipse.ui.browser will not be satisfied at all, without the resolver complaining about it.

Thus it seems, that imports with this bundle-symbolic-name property will be ignored for some reason.

**Comment by bjhargrave** [comment]
I think you need to file a bug against the Felix Resolver which is a dependency.

**Comment by bjhargrave** [comment]
It may be an issue in the indexing. I am working on that area now.

**Comment by bjhargrave** [comment]
FYI, I updated the index on bintray for our Eclipse deps. The index was built with the updated ResourceBuilder and the package capabilities are decorated with bundle-symbolic-name and bundle-version. 

This updated index with the latest Bnd should properly resolve bundle-symbolic-name and bundle-version matching attributes to the right package exporter.
