### ISSUE TITLE
"-" qualifier is not behaving correctly for connection-settings

### ISSUE THREAD

**Issue by dleangen** [bndtools/bnd#3759]
According to [this thread](https://groups.google.com/forum/#!topic/bndtools-users/c_UPwSfo47U), "-bnd" should still output the contents of ./bnd/connections-settings.xml. The "-" should only suppress errors. However, that is not the case, as verified by the test below.

-  Set up a minimal workspace using the template from github/bndtools.workspace.min. Having only the cnf project in the workspace is sufficient for this test.
- Run 'bnd com settings’ to verify that there is some data in ~/.bnd/connection-settings.xml, and that the data is being output.
-  Add the following to build.bnd and rerun ‘bnd com settings'. Ensure that both the dummy setting (which should be blank because it is an error) and the bnd settings are being output.
```
-connection-settings: \
      -dummy; \
          id=https://oss.sonatype.org; \
          username=username; \
          password=password, \
          bnd
```
-  Add a “-“ before “bnd” as below, and rerun ‘bnd com settings':
```
 -connection-settings: \
      -dummy; \
          id=https://oss.sonatype.org; \
          username=username; \
          password=password, \
          -bnd
```

- The contents of ~/.bnd/connection-settings.xml are no longer being output.

**Comment by bjhargrave** [comment]
Bnd failed to handle `-` prefix on the special names `bnd`, `maven`, `env`, and `server`.
