### ISSUE TITLE
Gradle plugin -wablib instruction does not place libs in WEB-INF/lib directory

### ISSUE THREAD

**Issue by ermel272** [bndtools/bnd#3765]
Not sure if this is a bug or something on my end that I am doing incorrectly. If the latter is true, hopefully I can get some help.

I'm currently running v4.3.1 of the bnd gradle plugin. My bnd config looks something sort of like the following:

```
jar {
    bnd (
           ... <snip>
            "-wab": "${project.projectDir}/src/main/resources, ${project.projectDir}/src/main/webapp",
            "-wablib": "*.jar"
    )
```

The `-wab` instruction is correctly placing the .class files under WEB-INF/classes, setting the Bundle-ClassPath in the MANIFEST.MF, and placing the contents of resources/webapp under the archive root.

I'm trying to use the `-wablib` instruction to place all of the non-transitive and transitive dependency JARs that my runtime/compile configurations depend on into the WEB-INF/lib folder, and automatically generate the corresponding Bundle-ClassPath as is documented https://bnd.bndtools.org/instructions/wab.html. I can see all of the dependencies being pulled in however they are being pulled in directly to the root of the archive rather than under WEB-INF/lib. Am I doing something wrong? Please let me know what additional info you need.

**Comment by bjhargrave** [comment]
@rotty3000 You did something with wab for the maven (and gradle?) plugins?

**Comment by rotty3000** [comment]
Yeah, I solved this in the maven plugin but I need to bring parity to gradle (this work took place before we got strict about parity ;) ). Self assigning.

**Comment by rotty3000** [comment]
I should add that I'd been meaning to do this anyhow since my company is interested in the gradle support.
The one complication I do see is potential interactions with the gradle war plugin. Not sure if that is desirable or not. It would however simplify things for developers already using it.
