### ISSUE TITLE
Extend .gitignore to ignore IDE settings by default

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#3768]
I would recommend extending the gitignore with the contents from https://www.gitignore.io/api/java,maven,gradle,eclipse,intellij+iml. That way IDE specific files will be automatically ignored.
It is questionable whether https://github.com/bndtools/bnd/tree/master/biz.aQute.launchpad.tests and https://github.com/bndtools/bnd/tree/master/biz.aQute.resolve.test are really supposed to contain Eclipse-specific metadata in git (.project, .classpath).

**Comment by bjhargrave** [comment]
We use Eclipse/Bndtools to develop Bnd/Bndtools. So I am not sure why we want to ignore Eclipse metadata files in this repo.

**Comment by kwin** [comment]
Usually a (smart) project importer takes care that the bnd.bnd files are considered when creating an Eclipse project out of a SCM folder (https://bugs.eclipse.org/bugs/show_bug.cgi?id=472614). That way files in SCM can be kept IDE agnostic. Also the gradle nature is missing currently from the .project files in Git.

**Comment by bjhargrave** [comment]
> Usually a (smart) project importer takes care that the bnd.bnd files are considered when creating an Eclipse project out of a SCM folder (https://bugs.eclipse.org/bugs/show_bug.cgi?id=472614). That way files in SCM can be kept IDE agnostic.

That is fine for a project to decide. But this project has decided to keep the eclipse metadata in the repo since we all use Eclipse and target Eclipse with Bndtools.

> Also the gradle nature is missing currently from the .project files in Git.

We do not use Buildship to build this project. We use Bnd/Bndtools to build it which is why we have the Bndtools nature in the Eclipse metadata in the repo.

**Comment by kwin** [comment]
Ok, fine then.
