### ISSUE TITLE
Enable the MavenBndRepository to deploy source jars in local mode

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3784]
Currently bnd is skipping the install of source and javadoc jars in local build mode. Sometimes One wants or needs this to happen without a full release. Thus I'd like to enable this. 

I'm not sure if this is something that should happen by default or if it needs to be enabled manually. I guess it would make sense to have it behave in local mode as it would in release mode to be consistent. Any thoughts on this?

I would provide a PR for this.

**Comment by rotty3000** [comment]
+1

**Comment by bjhargrave** [comment]
> local build mode

What is local build mode?

**Comment by juergen-albert** [comment]
Local mode means rather that no release or snapshot url is set and only the local maven repo is available or it can be enforced via -maven-release: local

**Comment by bjhargrave** [comment]
I think you means `-buildrepo` instruction is set to a local only repo:

```properties
-plugin.Local:\
    aQute.bnd.repository.maven.provider.MavenBndRepository;\
        name="Local";\
        noupdateOnRelease=true

-buildrepo: Local
```

So you want to release sources and javadoc jars to your local m2 cache? e.g. `~/m2/repository`?

**Comment by juergen-albert** [comment]
Yes, that's the intention.

**Comment by bjhargrave** [comment]
ok.

Make sure it is opt-in since we don't want to take the cost of making the sources and javadoc jars for all users. That is, it should not be the default to make sources and javadoc jars for releasing to the `-buildrepo`.

**Comment by bjhargrave** [comment]
I don't see that maven puts source and javadoc jars in .m2. Under what scenario does maven do that? `mvn install` on the osgi-test project only puts the (SNAPSHOT) jar and pom in .m2.
