### ISSUE TITLE
Maven source build without sources in the OSGI-OPT

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3785]
Sources in the OSGI-OPT are usually handy but not everybody wants to ship their sources with an assembled product, while having the maven source jars at the same time.

Thus I would integrate a option, to strip sources from the original jar before it is deployed.

I will provide a PR for this.

**Comment by bjhargrave** [comment]
You don't need to put sources in the jar to release a sources.jar. You can use `-maven-release: sources;path=src/main/java` and the release process will jar up the specified path into the sources jar. See https://bnd.bndtools.org/instructions/maven-release.html.
