### ISSUE TITLE
Bundles on testpath visible for bundle classes

### ISSUE THREAD

**Issue by ViToni** [bndtools/bnd#3789]
While trying to get rid of a dependecy I tried to avoid the hassle to also rewrite test classes.
(For the tests I don't care about footprint).
So I moved the dependency from -buildpath to -testpath to see which classes are affected. Unfortunately the bundle classes get "green" again.
I would expect that bundles on the testpath are only visible to test classes.

Seen on Eclipse 2019-06 with:
  Bndtools 5.0.0.DEV-201911281704-ga74cdba bndtools.main.feature.feature.group

Did also upgrade to check if it might have been solved in the meantime.

Also on Eclipse 2019-12 with:
  Bndtools 5.0.0.REL-202001221519-g612f80a bndtools.main.feature.feature.group

**Comment by pkriens** [comment]
Is the test directory colored grey? There should be visible difference between the test and source directories. This is controlled via the .classpath file. The test directory has an attribute for this in the XML.

**Comment by ViToni** [comment]
This was exactly the issue. Thanks for caring @pkriens
