### ISSUE TITLE
Add current JavaLevel enumerations for project template variable 'javaLevel'

### ISSUE THREAD

**Issue by maho7791** [bndtools/bnd#3798]
Java 11 is not supported in the project template variables in 
org.bndtools.utils.javaproject.JavaProjectUtils#JavaLevel

Jürgen will provide a PR for that

**Comment by pkriens** [comment]
We should take a look at changing the JavaLevel enum to EE in bnd. Not use to have this info multiple times in the same build?

**Comment by juergen-albert** [comment]
True. I will have a look.
