### ISSUE TITLE
Bndtools Explorer paste in search goes terribly wrong

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3801]
If you paste something into the search box strange things happen but the text does not get pasted.

**Comment by pkriens** [comment]
Inspected this problem. The PASTE Command handler somehow always gets directed to the TreeView instead of the new Text component. I've asked a question on StackOverflow because this is out of my league. Unless @gamerson could have a look?


https://stackoverflow.com/questions/60954751/commands-go-to-sibling-swt-control

**Comment by gamerson** [comment]
I'll take a look.
