### ISSUE TITLE
Exporting org.osgi packages

### ISSUE THREAD

**Issue by dleangen** [bndtools/bnd#3805]
Hi!

Is it still necessary to export the org.osgi.* packages? This seems to be causing me troubles during resolution. I am getting this:

```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=osgi.enroute.rest.simple.provider)
          ⇒ [osgi.enroute.rest.simple.provider version=2.3.0.202002260121]
              ⇒ osgi.service: (objectClass=org.osgi.framework.BundleContext)
```

I noticed that on my buildpath when I do `biz.aQute.bndlib;packages=aQute.*` instead of `biz.aQute.bndlib;packages=*` the problem appears to go away, which leads me to the question.

**Comment by pkriens** [comment]
You have a service dependency on (ns=osgi.service) on a _BundleContext_?

That sounds pretty wrong ...

You might have mistakenly done:

	@Reference
	BundleContext	context;

Instead of:

	@Activate
	BundleContext	context;

?

Kind regards,

	Peter Kriens

**Comment by dleangen** [comment]
Ah! You are absolutely right. Now that you mention it, I see how I should have been able to figure this out for myself.

Thanks!
