### ISSUE TITLE
[tester] Gogo commandlet for invoking tests

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3812]
In a continuous testing environment, it would sometimes be nice to be able to invoke tests from the shell. This should be achievable with a simple gogo shell wrapper around the existing testing infrastructure.

Suggestions (including how useful an idea this might be) would be appreciated.

**Comment by bjhargrave** [comment]
This sounds interesting but I suspect it would require the tester activator to have some "API". That API is either some gogo commands or some service which the gogo commands will call. We have generally tried to avoid having API for the launcher and tester.

**Comment by kriegfrj** [comment]
For JUnit Platform, the tester bundle is basically a wrapper around the JUnit Platform launcher. So I don't think the tester would need an API, as the commandlet could invoke the launcher directly. But for this to work we probably need #3526 done (so that the commandlet has a mechanism for finding the appropriate test listeners).
