### ISSUE TITLE
Breaking change after removal of 'aQute.libg.filters.Filter' class

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#3826]
I have been using the aforementioned class since long and due to recent removal changes in 5.1.0, I had to adapt my existing code to work properly.

I wan't aware until the pipeline failed. I just updated the maven dependencies file to use the recent snapshots and pipeline detected such breaking changes.

**Comment by bjhargrave** [comment]
I don't see that the subject class is removed. It is still in the repo. Can you be more specific?

**Comment by bjhargrave** [comment]
https://github.com/bndtools/bnd/blob/master/aQute.libg/src/aQute/lib/filter/Filter.java

**Comment by bjhargrave** [comment]
https://github.com/bndtools/bnd/blob/master/aQute.libg/src/aQute/libg/filters/Filter.java

**Comment by amitjoy** [comment]
I am actually pointing to https://github.com/bndtools/bnd/tree/5.0.0.REL/aQute.libg/src/aQute/libg/filters

**Comment by bjhargrave** [comment]
That package has not changed for over 2 years. It is all still there.

**Comment by amitjoy** [comment]
Yes, it's there. But the packaging somehow went wrong I believe. I just noticed that even though it is in repo. It is missing in `biz.aQute.bndlib-5.1.0-SNAPSHOT.jar`.

<img width="355" alt="Bildschirmfoto 2020-03-06 um 19 54 13" src="https://user-images.githubusercontent.com/13380182/76113373-51eead00-5fe4-11ea-8c26-137fcc837417.png">

<img width="284" alt="Bildschirmfoto 2020-03-06 um 19 54 26" src="https://user-images.githubusercontent.com/13380182/76113382-53b87080-5fe4-11ea-89f0-8741673564f5.png">

`Bundle-Version: 5.1.0.202003040104-SNAPSHOT`

**Comment by bjhargrave** [comment]
bndlib uses some aQute.libg project packages as implementation detail by using `-conditionalpackage` to include them. Those packages are not part of the API of bndlib. That is, you will not see them exported by bndlib. 

If your project tries to use those packages from bndlib, Eclipse will give you a "discouraged access" warning.

If you need to use aQute.libg package in your own project, you must but aQute.libg jar on your `-buildpath` and you must `-conditionalpackage` those package into your bundle just like bndlib (and all other Bnd projects do).

**Comment by amitjoy** [comment]
I am referring to something else. I know how to use the classes from bndlib and have been using them using `-conditionalpackage` since very long. I am referring to the recent snapshot built by bndtools pipeline. In my workspace, I am currently using Bndtools snapshots from Jfrog. And the new bndlib artifact (5.1.0.202003040104-SNAPSHOT) doesn't contain `aQute.libg.filters` package at all. 

The above screenshots are taken after expanding the bndlib JAR entry from the referenced project's `Bnd Build Path` and you can see that the `aQute.libg.filters` package is missing in the snapshot JAR.

**Comment by amitjoy** [comment]
I just had a look into the JAR once again.

<img width="272" alt="Bildschirmfoto 2020-03-06 um 20 07 31" src="https://user-images.githubusercontent.com/13380182/76114365-32f11a80-5fe6-11ea-88e8-d8c995469394.png">

The aforementioned package is missing in the bndlib JAR.

**Comment by amitjoy** [comment]
For reference, you can have a look into https://bndtools.jfrog.io/bndtools/libs-snapshot-local/biz/aQute/bnd/biz.aQute.bndlib/5.1.0-SNAPSHOT/biz.aQute.bndlib-5.1.0-20200306.172723-90.jar

**Comment by amitjoy** [comment]
The package is clearly available in https://search.maven.org/artifact/biz.aQute.bnd/biz.aQute.bndlib/5.0.0/jar but not in 5.1.0-SNAPSHOT

**Comment by rotty3000** [comment]
So, bndlib obtains this package via `-conditionalpackage`
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/bnd.bnd#L46-L48

I suspect what happened was incidentally no more usages of this package from any other code imported into bndlib. The effect is that the package is no longer included.

But, as @bjhargrave says, this was merely an implementation detail of bndlib, and not an API for reuse by others via bndlib. So the solution for you @amitjoy is to change your method of obtaining the package via libg :)

**Comment by amitjoy** [comment]
@rotty3000 I have already adapted my existing code to use aQute.libg instead.

@rotty3000 @bjhargrave Thanks for the clarification 👍
