### ISSUE TITLE
[mvn] Simplify bnd-maven-plugin configuration

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#3828]
at the moment we have add the maven-jar-plugin and configurate the archive with an manifest
```
    <build>
        <plugins>
            <plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

The Goal is that maven-jar-plugin asks bnd-maven-plugin (and others) to manipulate the manifest.

```
    <build>
        <plugins>
            <plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
```

There is a Ticket in Apache Maven-Jira:
https://issues.apache.org/jira/browse/MJAR-193

Robert Scholte:
```
This is not a simple question and requires some good investigation. I'm not able to answer that right away.

What would help is to create an integrationtest with what you would expect. Based on that it might be easier to answer the question.
```

@rotty3000 what do we need? Is an Interface like this enough?

```
interface ArchiverExtension
{
    void modify(org.apache.maven.archiver.MavenArchiver archiver);
}
```

or just
```
interface ManifestProvider
{
    Manifest modify(Manifest manifest);
}
```

**Comment by bjhargrave** [comment]
What change to Bnd is this issue suggesting?

**Comment by rotty3000** [comment]
This issue cannot be fixed purely in bnd, we have to train the maven-jar-plugin (and potential the plexus archiver) to accept some form of input that can be set externally. IIUC the only vehicle for communication across maven plugins is project properties. In the past I've tried wiring this through the component model of maven but that is actually forcibly prevented from happening.

**Comment by bjhargrave** [comment]
Closing this since it is really a maven issue.
