### ISSUE TITLE
Prevent XXE - Disallow DTDs when reading XML using DocumentBuilderFactory

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#3831]
Could be fixes  with:
```
DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
// Disallow DTDs when reading
factory.setFeature(javax.xml.XMLConstants.FEATURE_SECURE_PROCESSING, true);
factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
```

**Comment by bjhargrave** [comment]
What does this mean? I do not understand this issue.

**Comment by stbischof** [comment]
XML External Entities (XXE) is an security issue. When reading an xml using the default DocumentBuilderFactory it allows the uso of xxe
```
<?xml version="1.0" encoding="ISO-8859-1"?> <!DOCTYPE ... [
  <!ELEMENT foo ANY >
  <!ENTITY xxe SYSTEM "https://127.0.0.1/private" >]>
  <!ENTITY xxe SYSTEM "file:///./passwd.cfg" >]> <foo>&xxe;</foo>
```

**Comment by rotty3000** [comment]
@stbischof how so? This is the prevention for XXE! Did you find that this is wrong? Can you perhaps create a test.

**Comment by stbischof** [comment]
afaik is this code a way to prevent XXE
```
factory.setFeature(javax.xml.XMLConstants.FEATURE_SECURE_PROCESSING, true);
factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
```

but we do not have use this inside of bnd. We just use the default DocumentBuilder , that allows XXE
```
DocumentBuilder docBuilder = DocumentBuilderFactory.newInstance()
					.newDocumentBuilder();
```

because of that I filed an Issue before starting to create an PR.

**Comment by bjhargrave** [comment]
But the "feature" to use can vary with the underlying parser implementation which can vary from JVM implementation to JVM implementation. So your example mitigation may fail on some JVMs.

**Comment by bjhargrave** [comment]
Also: https://lgtm.com/rules/2046840730/

I am surprised LGTM does not complain.

**Comment by stbischof** [comment]
i see: there are also two methods that could help
```
dbf.setXIncludeAware(false);
dbf.setExpandEntityReferences(false);
```

**Comment by rotty3000** [comment]
Ok, ok, so in some places we have the right logic in place, in others we don't. I think this is just a "can you send a PR" scenario ;)

https://github.com/bndtools/bnd/blob/ee96a4b4c3325c7db9eeeb181d680a989b78c020/biz.aQute.bndlib/src/aQute/bnd/cdi/CDIAnnotations.java#L60
https://github.com/bndtools/bnd/blob/2ae86fb92fd2a52ee257498c56f8b53daff8ff6a/bndtools.core/src/org/apache/felix/metatype/MetaDataReader.java#L146

**Comment by rotty3000** [comment]
whether it's worth to centralize this in one place is up for debate I suppose.

**Comment by bjhargrave** [comment]
I think we should centralize this. We need some simple static method which do the right thing and can handle potentially different underlying xml parser implementations.
