### ISSUE TITLE
"Contracts [...] declare the same packages in their uses " due to transitive Maven dependency

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#3843]
Some bundles embed/include the contents of other bundles. That also includes the OSGi contracts which would need to be repeated on the embedding bundle's manifest. 
Still depending on the to be embedded bundle `b` with scope "compile" (i.e. transitively visible) in the embedding bundle `a` leads to an error message like this when depending on the embedding bundle `a`

```
Contracts [Contract [name=...;version=...;from=a], Contract [name=...:version=...;from=b]] declare the same packages in their uses: directive: [...]. Contracts are found in declaring bundles (see their 'from' field), it is possible to control the findingwith the -contract instruction
```

Although this error could be prevented by `a` not having `b` as dependency with scope `compile` but `provided` but still this should not lead to an error but only a warn (and the first contract from the classpath should win).

For a concrete use case look at https://github.com/apache/sling-org-apache-sling-commons-johnzon and https://issues.apache.org/jira/browse/SLING-9218.

**Comment by kwin** [comment]
@rotty3000 Do you agree that this error message is wrong in this case?

**Comment by rotty3000** [comment]
at first glace your argument sounds correct. But we'll have to check it.
