### ISSUE TITLE
[Launchpad] Signal when system is ready

### ISSUE THREAD

**Issue by dleangen** [bndtools/bnd#3845]
Would be nice to have some built-in mechanism to delay the actual execution of the test until all the services have been loaded.

At this time, for my tests to work, I need to put in an arbitrary sleep of 200 ms (tried 100, which works most, but not all of the time). This is very hackish and unreliable.

**Comment by pkriens** [comment]
If you inject the services with @Service the code will block until they are all present. The code is also not ran until all bundles have been started. So not sure what further we can do?

**Comment by dleangen** [comment]
My problem was that there are some asynchronous services that are required by the components under test, but which were not ready at the time of the test. If I add a delay, then eventually they start up and the test can pass. If I don't add a delay, then the test starts before they are ready.

Are you saying that as the tester, I need to recursively go into all the components, find which ones may make the test fail, then manually inject them into the test class with a @service annotation?

Note that that is actually how I solved the problem. I wrote a "BundleSanity" test, and just tested for the availability of all the @Required services. For each one that failed, I recursively did the same thing for its @Required services, and so on, until I could find the culprits. In some cases I added them manually to the test, in others I just added a delay to wait until they were ready.

Anyway, my tests are working now, so I will close this issue. From the perspective of somebody who was not party to designing and coding Launchpad, I just thought I'd bring up the difficulties I had in case anybody was interested.

**Comment by pkriens** [comment]
Well, you're the only one that knows that 'ready' means after the framework has been started.

**Comment by dleangen** [comment]
Ok, I see what you mean. Maybe baking in a kind of "ready" service into the testing framework could be useful. Just a thought.

**Comment by pkriens** [comment]
We've tried from the first day of OSGi ... Just really difficult to define.
