### ISSUE TITLE
Support for maven index file for BndPomRepository

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3846]
As far as I understand it, the ```BndPromRepository``` is the better Version of the ```MavenBndRepository```, because it supports transitive dependencies as well plus the pom as and index. In addition to he revisions attribute, I'd like to implement support for maven index files similar to the maven repository as well. For one people are used to it by now and they are easier to maintain then revisions attribute, when they become larger.  

Any thoughts, why this wouldn't be a good idea?

**Comment by pkriens** [comment]
You can add transitive dependencies with a menu. However, I really detest the automatic dependencies because they cause lots of problems because they are not managed. And the XML sucks. So I am moving forward with the MavenBndRepository.

**Comment by bjhargrave** [comment]
> the `BndPomRepository` is the better Version of the `MavenBndRepository`

I don't think this is a valid assertion. It is not better. It is different and addresses a different need. Sometime you have a POM/BOM and need all the transitive dependencies. Sometime you do not want that.

You also cannot release to a BndPomRepository.

I don't think adding the index file from MavenBndRepository to BndPomRepository is a good idea. It defeats the purpose of BndPomRepository which is to be POM driven.

**Comment by juergen-albert** [comment]
> > the `BndPomRepository` is the better Version of the `MavenBndRepository`
> 
> I don't think this is a valid assertion. It is not better. It is different and addresses a different need. Sometime you have a POM/BOM and need all the transitive dependencies. Sometime you do not want that.
This is just my personal opinion, because setting the transitive attribute to false would provide nearly the same functionality as the Maven Repository (yes the release capability is missing, but that's about it). 
> 
> You also cannot release to a BndPomRepository.
> 
> I don't think adding the index file from MavenBndRepository to BndPomRepository is a good idea. It defeats the purpose of BndPomRepository which is to be POM driven.
I don't see the point. We have the revisions attribute that takes a list of GAV coordinates. It already can point to a simple Maven Artifact as well as simple index poms or artifacts containing a index pom. Allowing the repository to read an index file simply provide another way of maintaining the revisions it should look after, what every they are.

**Comment by bjhargrave** [comment]
> Allowing the repository to read an index file simply provide another way of maintaining the revisions it should look after, what every they are.

You don't need to read a file for this. Just use a bnd property and use this property in your `-plugin` definition.

**Comment by juergen-albert** [comment]
BJs suggestion with the property is a workable solution. 
I also begin to hate the transitive dependencies and time is limited,  Thus I will not be able to implement this.

@bjhargrave should we simply close this or mark it somehow, as it was scheduled for 5.3?
