### ISSUE TITLE
QuickFix to support multiple options

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3857]
I just downloaded and played with the new class-level quick fix by @pkriens (#3833). Very nice!

One thing that I noticed is that it seems to only produce one suggestion (or two if it's got a testpath suggestion as well), and it's not always the best option. For example, I had a DS file with an `@Component` annotation, but the relevant bundle containing the annotation was not on the buildpath. Unfortunately, "Component" is a common class name and there was another class in my workspace that got suggested instead (`com.sun.xml.ws.api.Component`).

As a first-cut attempt to support cases like this, it would be good if the quickfix processor listed a multiple suggestions where there are multiple matches. The previous incarnation of the quickfix process would do this (another reason it would be good to get those integration tests re-instated!).

A further enhancement would be to look at the full set of potential matches and see if there are any that we can filter out or adjust the relevance based on the current context. In this example, any match that doesn't extend `java.lang.annotation.Annotation` could be ruled out. Also, there was an (unresolved) import for `org.osgi.service.component.annotations.*`, which could have been used as a tip. But these are icing-on-the-cake suggestions - I think the basic cake would include listing multiple suggestions where they are available.

**Comment by kriegfrj** [comment]
Has there been some work done on this? I noticed while working today that I am getting multiple suggestions. Either I misdiagnosed it originally, or perhaps it has been fixed?

**Comment by pkriens** [comment]
Sorry for the late reply. No, there were no changes in there as far as I know. I checked it and saw multiple returns (and the code clearly allows multiple returns).

However, I've noticed two things:

- Sometimes it does not find a class but it does find a sibling class. I notice it can find Logger but not LoggerFactory. Need to diagnose what is going on.
- We're listed before any import from the buildpath. the buildpath clearly should have priority.

**Comment by kriegfrj** [comment]
By "the buildpath clearly should have priority", you meant that an import from abundle that's already on the buildpath should have priority? I agree.

I've also noticed it suggesting bundles that are already on the build path, or different versions of those bundles, or more generally suggesting to add bundles that contain the same FQ class name as a bundle that's already on the class path. We could (should?) probably filter those out.

**Comment by pkriens** [comment]
Not sure we should filter them out if the -buildpath suggestion has priority?

**Comment by kriegfrj** [comment]
Sorry, I think I wasn't clear - I don't think we should make `-buildpath` suggestions for classes that are already on the build path. For example, if I already have a particular version of `org.osgi` on `-buildpath` and I type `Bundle` in my editor, I expect Eclipse to suggesting adding `import org.osgi.framework.Bundle`, but I think 99% of the time it would be useless to suggest adding either another version of `org.osgi`, or to add `org.apache.felix.framework`, or `org.eclipse.osgi.equinox`, etc. We should simply not make any suggestions in those cases.

However, this is somewhat different from the original issue (which doesn't actually seem to be an issue - I've seen many examples of multiple suggestions since then), so I might raise a new issue for this.
