### ISSUE TITLE
Easier access to refreshing repository contents

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#387]
Need to refresh plugins when remote repo contents changes, but when?

Options:

1) Manually: menu entry to reload plugins.
2) Automatically when a build start? Perhaps on FULL_BUILD, then can trigger with clean?
3) Poll continuously. How? And what do we do when we detect a change... prompt to rebuild?

**Comment by paulvi** [comment]
@bjhargrave Usually it is done on build (2), if any of dependencies is of open (not fixed) version
