### ISSUE TITLE
Used version 5.1.0 in documentation does not match released version 5.0.1

### ISSUE THREAD

**Issue by UdoW** [bndtools/bnd#3871]
In the documentation one should use version 5.1.0 but this version does not exist. The file publish.gradle says that version 5.0.1 was published. I suppose, the documentation is wrong and should be changed to version 5.0.1.

**Comment by bjhargrave** [comment]
The latest documentation at bnd.bndtools.org is for the master branch which is 5.1.0 (SNAPSHOT). There is no doc change for 5.0.1 since it is a maintenance release, so just use the 5.0.0 docs.

**Comment by rotty3000** [comment]
Just to further explain, we don't release docs for maintenance releases, as such any point releases should refer to the previous release which for 5.0.1 is 5.0.0 :)
