### ISSUE TITLE
modify BndPomRepository properties

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3872]
The BndPomRepository has the property pom and revision, but it can handle a List of each. Thus we should add "poms" and "revisions" to the internal configuration to take one or the other together with an update to the Documentation. 

Such inconsistency make a bad user experience.

**Comment by bjhargrave** [comment]
I am not sure what you want. Do you want to rename the config properties from pom->poms, revision->revisions? That seems overkill. We just need the docs to make clear a list can be specified.

**Comment by bjhargrave** [comment]
Leave pom and revision alone.

Create non-s versions of snapshot and release url properties. Leave old ones for backwards compatibility. Update doc to reference non-s versions. Error if user uses bothe s and non-s property.
