### ISSUE TITLE
[junit-platform] NoClassDefFoundError in test class silently ignored

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3882]
>As it happens, my initial attempts at doing this have exposed an issue with the junit-platform tester, which I will document in a new issue shortly.
>
>_Originally posted by @kriegfrj in https://github.com/bndtools/bnd/issues/3881#issuecomment-609628225_

With my first attempt at trying to port `ImportPackageQuickFixProcessorTest` to an OSGi JUnit test, I found that the tester was silently skipping over my Jupiter test case. When I added another (simpler) test in the same bundle, it ran the simpler test fine but still skipped the other.

Using the debugger, I managed to establish that `EngineDiscoveryRequestResolution.resolve()` was throwing a `NoClassDefFoundError`, which was in turn being silently swallowed by the `catch(Throwable t)` in `EngineDiscoveryRequestResolution.resolveCompletely()`.

`BundleSelectorResolver` tries to prevent this from happening by loading the class before handing off to the engines, but it seems this doesn't catch all cases - I suspect that although we're loading the class we're not triggering initialization of the class. Will look at using `Class.forName()` or something instead.

**Comment by kriegfrj** [comment]
Ok, so after more wrestling with the debugger, I've figured out that the `NoClassDefFoundError` is triggered when you first call `Class.getDeclaredMethods()` (which is called by `ReflectionUtils.findMethod()`) - if one of the methods references a class that is not visible to the current class. I think the fix is to try and make sure that it is called before handing off to the engine, so that we can catch and report the error appropriately.

I will try and add some appropriate test cases to cover this and then try and submit a fix.

**Comment by rotty3000** [comment]
One has to wonder how the bundle made it into runtime with missing classes? Maybe all that is needed is for `ReflectionUtils.findMethod()` ensure it always puts the classloader of the test class on the TCCL before looking further at it?

**Comment by kriegfrj** [comment]
> One has to wonder how the bundle made it into runtime with missing classes? 

This is Eclipse,  complete with split packages and missing dependency information... I had to manually add the x86_64 fragment for org.eclipse.swt to runrequires and re- resolve to fix it. Gave me the idea of a quick fix processor to fix these kinds of issues

> Maybe all that is needed is for `ReflectionUtils.findMethod()` ensure it always puts the classloader of the test class on the TCCL before looking further at it?

There are some improvements to be made to the class loading in JUnit, it's true. Bit in my case the class was actually missing and Jupiter reacted by silently skipping the class.

**Comment by bjhargrave** [comment]
>  I think the fix is to try and make sure that it is called before handing off to the engine, so that we can catch and report the error appropriately.
> 
> I will try and add some appropriate test cases to cover this and then try and submit a fix.

@kriegfrj Do you think we can get such a fix in quickly for 5.1? I would like to start getting ready to release 5.1 since it has necessary fixed for Java 15.

**Comment by kriegfrj** [comment]
Is next week early enough?

**Comment by bjhargrave** [comment]
> Is next week early enough?

Perfect!

**Comment by bjhargrave** [comment]
Not sure you means to close this. "Partially fixes xxx" was treated as "fixes xxx" by github :-)

**Comment by bjhargrave** [comment]
Is this still something we can get in shortly for 5.1? Or should we defer this to 5.2?

**Comment by kriegfrj** [comment]
If it can wait until Monday I'm happy to have a go at it for 5.1, otherwise maybe the next release.

**Comment by bjhargrave** [comment]
Monday is good. We will have some RC releases before final. Thanks!

**Comment by kriegfrj** [comment]
Just to connect some of the loose ends for posterity:

> Maybe all that is needed is for `ReflectionUtils.findMethod()` ensure it always puts the classloader of the test class on the TCCL before looking further at it?

Just on this issue specifically: although this was not the problem in my case (it wasn't that the parameter wasn't visible, but that it wasn't present at all) I believe that you are correct, `ReflectionUtils.findMethod()` needs to put the classloader of the test class on the TCCL. That is the subject of junit-team/junit5#2104. The JUnit team decided against using my patch for ReflectionUtils (junit-team/junit5#2106) in favour of a more comprehensive overhaul of the all the classloader issues, hopefully to be incorporated in 5.7.

In the meantime, we have a wrapper around `findMethod()` that does exactly this: https://github.com/bndtools/bnd/blob/2a681d064925334723846f0538a05cbc391e31b0/biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java#L416-L429
