### ISSUE TITLE
Unable to debug in eclipse

### ISSUE THREAD

**Issue by ederjc15** [bndtools/bnd#3889]
I'm not able to debug after update the plugin (bnd-run-maven-plugin)  from version 4.2.0 to 5.0.1.
I just update it on pom. Should I do something more?

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by bjhargrave** [comment]
If this is still an issue, please open a new issue with information on how to reproduce.
