### ISSUE TITLE
Parsing warning occurs when curly brace follows a declared string

### ISSUE THREAD

**Issue by glimmerveen** [bndtools/bnd#3890]
When I include the following in my Bndrun file:
```
my.plugins : ${findproviders;osgi.service;(objectClass=osgitest.app.Plugin)}
-runrequires.plugins : ${template;my.plugins;osgi.identity;filter:='(osgi.identity=${@})'}
```
I get the following warning:

> [WARNING] Warning : Expected a delimeter, like comma or semicolon, after a quoted string but found '}': <<-runrequires.plugins : ${template;my.plugins;osgi.identity;filter:='(osgi.identity=${@})'}>>

Which can be solved by adding a `;` before the `}` as the warning suggests, but based on a discussion on the mailing list [1] this should not be needed.

[1] https://groups.google.com/d/msg/bndtools-users/GbBEfGTG3BY/dVsntPEFBQAJ

**Comment by bjhargrave** [comment]
You need to escape the `;` which is in the template value and not to be used by the macro processor to parse macro arguments. You also need 2 backslashes since the properties file parser (bnd files are properties files) will collapse the 2 into 1.

`-runrequires.plugins: ${template;my.plugins;osgi.identity\\;filter:='(osgi.identity=${@})'}`

**Comment by glimmerveen** [comment]
I updated my bndrun file as you suggested, but I still get this warning:

> [WARNING] Warning : Expected a delimeter, like comma or semicolon, after a quoted string but found '}': <<-runrequires.plugins : ${template;my.plugins;osgi.identity\\;filter:='(osgi.identity=${@})'}>>

**Comment by bjhargrave** [comment]
Then there is something else wrong. What is the value of `my.plugins`?

**Comment by bjhargrave** [comment]
See

https://github.com/bndtools/bnd/blob/d7945763662824194e2a223569ea0c1bb5e46d97/biz.aQute.bndlib.tests/test/aQute/bnd/build/repo/WorkspaceRepositoryTest.java#L49-L65

where we have a test which looks just like what you are doing and it does not make the same warning.

**Comment by bjhargrave** [comment]
Actually, I made a new test which reproduces the issue. So I will debug.

**Comment by glimmerveen** [comment]
Thanks @bjhargrave , verified this to work without warning in my set-up as well!

**Comment by pkriens** [comment]
> You need to escape the ; which is in the template value and not to be used by the macro processor to parse macro arguments. You also need 2 backslashes since the properties file parser (bnd files are properties files) will collapse the 2 into 1.
This is **not** true. The template macro concatenates all arguments after template argument with ';' as a separator. This was specifically done to not end up in escape night mare.

@glimmerveen What is then now the difference that you made?

**Comment by bjhargrave** [comment]
> This is **not** true. The template macro concatenates all arguments after template argument with ';' as a separator. This was specifically done to not end up in escape night mare.

Yes, I realized this after I wrote the comment. Escaping the semicolons does not hurt but is not necessary in the template macro.

**Comment by glimmerveen** [comment]
> > You need to escape the ; which is in the template value and not to be used by the macro processor to parse macro arguments. You also need 2 backslashes since the properties file parser (bnd files are properties files) will collapse the 2 into 1.
> 
> This is **not** true. The template macro concatenates all arguments after template argument with ';' as a separator. This was specifically done to not end up in escape night mare.
> 
> @glimmerveen What is then now the difference that you made?

I have tested with and without escaping the `;` in the template, current version in master works in either case as expected.
