### ISSUE TITLE
[eclipse builder][win32] Build Errors due to not accessible jar

### ISSUE THREAD

**Issue by spacehorst** [bndtools/bnd#3894]
Since an upgrade to bndtools 4.3.1 the following error occurs quite often during the workspace build after saving a java file. The error occurs to a random project (= generated jar) of the workspace.
The translation is 'The process cannot access the file because it is used by another process'.

> Errors occurred during the build.
> Errors running builder 'Bndtools Builder' on project
> 'de.tw.bimex.taxonomy.emaccess'.
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.taxonomy.emaccess\generated\de.tw.bimex.taxonomy.emaccess.jar:
> Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen
> Prozess verwendet wird.
> 
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.taxonomy.emaccess\generated\de.tw.bimex.taxonomy.emaccess.jar:
> Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen
> Prozess verwendet wird.

**Comment by bjhargrave** [comment]
There are issues with open files in Windows. We have seen problems sometimes from other Eclipse plugins holding files open that Bndtools needs to write. We have also made many fixes to Bndtools over time. The latest release is 5.0.1 which you should try.

See https://github.com/bndtools/bnd/wiki/Windows-Locked-Files for information on how you can try to determine which code may be holding open the file.

**Comment by spacehorst** [comment]
I switched to the latest Eclipse Release (2020-03, I20200305-0155) as well as the latest bndTools-Release (5.0.1.REL-202003231327-gab71f2c) and got the following same Errors on first Workspace CleanUp.

I followed your suggested Link and sent the protocol of the File Leak Detector to Peter Kriens.

> Errors occurred during the build.
> Errors running builder 'Bndtools Builder' on project 'de.tw.bimex.application.ui.rap.styling'.
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.application.ui.rap.styling\generated\de.tw.bimex.application.ui.rap.styling.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.application.ui.rap.styling\generated\de.tw.bimex.application.ui.rap.styling.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Errors running builder 'Bndtools Builder' on project 'de.tw.bimex.resource'.
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.resource\generated\de.tw.bimex.resource.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.resource\generated\de.tw.bimex.resource.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Errors running builder 'Bndtools Builder' on project 'de.tw.bimex.project'.
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.project\generated\de.tw.bimex.project.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.project\generated\de.tw.bimex.project.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Errors running builder 'Bndtools Builder' on project 'de.tw.bimex.taxonomy'.
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.taxonomy\generated\de.tw.bimex.taxonomy.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.taxonomy\generated\de.tw.bimex.taxonomy.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Errors running builder 'Bndtools Builder' on project 'de.tw.bimex.mm'.
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.mm\generated\de.tw.bimex.mm.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.bimex.mm\generated\de.tw.bimex.mm.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Errors running builder 'Bndtools Builder' on project 'de.tw.lib.databinding'.
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.lib.databinding\generated\de.tw.lib.databinding.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.lib.databinding\generated\de.tw.lib.databinding.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Errors running builder 'Bndtools Builder' on project 'de.tw.lib.swt.resourceregistry'.
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.lib.swt.resourceregistry\generated\de.tw.lib.swt.resourceregistry.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
> 
> Build Error!
> D:\Devel\bimex-rap\git\bim-explorer-rap\de.tw.lib.swt.resourceregistry\generated\de.tw.lib.swt.resourceregistry.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

**Comment by pkriens** [comment]
There is a Sonarlint thread reading these JARs. Could you try to run without and report?\


Kind regards,

	Peter Kriens

**Comment by spacehorst** [comment]
Hi Peter,

thank you for the hint. Turning SonarLint off did the trick.
See the Report attached by Email.

Hence, I think they played well together in prior releases.

**Comment by bjhargrave** [comment]
So I think we can close this issue now?

**Comment by pkriens** [comment]
I'd like to know what happens with the -x-overwrite-strategy. We should be able to run with Sonar without problems.

**Comment by spacehorst** [comment]
The SonarLint is updated automatically using Oomph - so I can't tell you exactly when it started to get noisy.
Thank you for the hint.
I placed the `-x-overwritestrategy: delay` Instruction to my defaults.bnd and it seems that the error reports have gone away for now. Starting to gather long time experince.
I suggest to reopen this ticket if I get build errors again.

**Comment by pkriens** [comment]
Ok, it means sonar is not properly scheduling their checking. This is normally not such a problem in Eclipse because few build systems are building their JARs all the time. PDE, for example, uses the bin directory and I think m2e uses the target/classes. We use the JAR so the magic bnd can do is exactly the same in debug as in runtime.

Anyway, keep us posted.

**Comment by spacehorst** [comment]
So far, the -x-overwritestrategy: delay Instruction is working for me without problems.
Thank you very much.

**Comment by pkriens** [comment]
You might want to file a bug with Sonar. 

Some background. Bndtools runs in this problem because it always generates the output JAR. PDE added a huge amount of complexity to _fake_ the output for performance. Maven M2E has a completely separate process. This is the reason we run into this erroneous software that opens the JAR, expecting to have monopolistic access to it.
