### ISSUE TITLE
[reporter] Add bnd-reporter-demo to bndtools namespace

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#3922]
It would be nice to have/add a new github-repo with bnd-reporter to bndtools namespace.

@cdelg has build this nice bnd-reporter-demo https://github.com/cdelg/bnd-doc-demo . this would be a great point to start.

**Comment by bjhargrave** [comment]
Are you saying you would like to have the bnd-doc-demo repo in the bndtools github organization? e.g. https://github.com/bndtools/bnd-doc-demo ?

**Comment by stbischof** [comment]
Yes.
I think that will help others a lot with there first steps.

**Comment by bjhargrave** [comment]
OK, I forked https://github.com/cdelg/bnd-doc-demo into https://github.com/bndtools/bnd.reporter-demo and made @stbischof and @cdelg as maintainers.
