### ISSUE TITLE
[reporter] Move Sling Feature to a dedicated subsection in the readme template

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#3923]
The PR #3916 introduces a new Coordinate subsection named Feature-Coordinate. To improve the readability of the readme file I think we should move this subsection into another main section.

The Coordinate section contains the identity of the artifact being documented by the readme file. Actually it contains two identity under two different systems: OSGi and Maven. The Feature-Coordinate is not an identity, it is a snippet to reference an identity in a Sling Feature. So I suggest to  move the newly Feature-Coordinate subsection to another main section named **Reference** and rename the  Feature-Coordinate subsection to **For Sling Feature**. We can also create in the same way other subsections **For Maven** , For Gradle, .... All these subsections should be optional.

The classifier tag should also be moved to the Reference section.

**Comment by bjhargrave** [comment]
@stbischof Can you fix by Sep 15 (or defer to 6.1)?
