### ISSUE TITLE
Runbundles Version to snapshot

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#3928]
According to the latest changes, the resolver always adds the respective bundle versions to the `-runbundles` entries.

For example,

```
-runbundles: \
	californium-osgi;version='[1.0.8,1.0.9)',\
	com.eclipsesource.jaxrs.jersey-min;version='[2.22.1,2.22.2)',\
	com.fasterxml.jackson.core.jackson-annotations;version='[2.7.0,2.7.1)',\
	com.fasterxml.jackson.core.jackson-core;version='[2.7.4,2.7.5)',\
	com.fasterxml.jackson.core.jackson-databind;version='[2.7.4,2.7.5)',\
	com.google.guava;version='[15.0.0,15.0.1)',\
	com.company.binding;version='[1.198.1,1.198.2)',\
	com.company.backend.httpclient;version='[1.198.1,1.198.2)',\
	com.company.backendclient;version='[1.198.1,1.198.2)',\
```

In the aforementioned list, the bundles having reverse domain of `com.company` (the last 3 bundles) are workspace projects.

Previously, this `-runbundles` was as follows (also prepared by the resolver):

```
-runbundles: \
	californium-osgi;version='[1.0.8,1.0.9)',\
	com.eclipsesource.jaxrs.jersey-min;version='[2.22.1,2.22.2)',\
	com.fasterxml.jackson.core.jackson-annotations;version='[2.7.0,2.7.1)',\
	com.fasterxml.jackson.core.jackson-core;version='[2.7.4,2.7.5)',\
	com.fasterxml.jackson.core.jackson-databind;version='[2.7.4,2.7.5)',\
	com.google.guava;version='[15.0.0,15.0.1)',\
	com.company.binding;version=snapshot,\
	com.company.backend.httpclient;version=snapshot,\
	com.company.backendclient;version=snapshot\
```

According to the current configuration we have, for every product release, we use the same version for all the bundles generated from the workspace projects - such as 1.x.y.TIMESTAMP. So, after every release or hotfix, we need to update all the bndrun files we have. This is really time consuming job to get them resolved and wait 40-50 seconds (we have around 300 workspace projects) for every bndrun file.

Is there any way to ensure that resolver always uses `snapshot` as versions for the bundles that exist as workspace projects?

**Comment by bjhargrave** [comment]
It should use snapshot for bundles from the Workspace. For bundles from a repo, it will use a version range. If your build releases your bundles to a LocalIndexedRepo before you resolve, the resolver may be using that copy of the bundle. You may want to set `-runrepos` in the bndrun to exclude such a release repo.

**Comment by amitjoy** [comment]
Thanks BJ for the quick reply. We don't use release repo while resolving the bndruns since we already excluded it from `-runrepos` list. We actually don't use `-snapshot` to be added to the bundle versions before the release and that's why bnd resolver always considers them as release artifacts. Is there anyway I can configure in bnd to inform that we are in snapshot version? (without adding `-snapshot` to the bundle versions)

**Comment by bjhargrave** [comment]
I am not talking about the -snapshot instruction or adding SNAPSHOT to bundle versions. I am talking about version=snapshot in -runbundles. That means the version in the Workspace repository.

If the bundle is from the Workspace repository (that is a project's generated folder)

https://github.com/bndtools/bnd/blob/111f7a23ec2d9c953d77338093e422ee7fdf9838/biz.aQute.resolve/src/biz/aQute/resolve/WorkspaceResourcesRepository.java#L29-L31

then generated -runbundles clause will use version=snapshot.

https://github.com/bndtools/bnd/blob/111f7a23ec2d9c953d77338093e422ee7fdf9838/biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java#L541-L550

**Comment by bjhargrave** [comment]
> Is there any way to ensure that resolver always uses `snapshot` as versions for the bundles that exist as workspace projects?

So my answer is that Bnd does this already unless you have found some new bug. In which case, we will need something to debug.

**Comment by amitjoy** [comment]
@bjhargrave All the workspace bundles are from `workspace` repository, that is, the bnd's default one as shown in `Repository View` - this means, it is the project's generated folder.

**Comment by bjhargrave** [comment]
OK, the I think we will need a small github repo which shows the issue so it can be debugged.

**Comment by amitjoy** [comment]
Here is the repo to replicate this issue - https://github.com/amitjoy/bndtools-bug-3928

**Comment by bjhargrave** [comment]
OK, so I made this change to your repo:

```diff
diff --git a/gradle.properties b/gradle.properties
index d96389e..6752bc5 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -1,3 +1,3 @@
-bnd_version=4.4.0-SNAPSHOT
+bnd_version=5.1.0-SNAPSHOT
 
 bnd_repourl=https://bndtools.jfrog.io/bndtools/libs-snapshot
```

Since it was _NOT_ using the latest Bnd version. 

I then ran

```script
gradle --no-daemon :com.amitinside.dummy.example:resolve.test && cat com.amitinside.dummy.example/test.bndrun
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

BUILD SUCCESSFUL in 4s
5 actionable tasks: 2 executed, 3 up-to-date
-runrequires: bnd.identity;id='com.amitinside.dummy.example'

-runbundles: \
	org.apache.felix.gogo.command;version='[1.1.0,1.1.1)',\
	org.apache.felix.gogo.runtime;version='[1.1.2,1.1.3)',\
	org.apache.felix.gogo.shell;version='[1.1.2,1.1.3)',\
	org.apache.felix.scr;version='[2.1.16,2.1.17)',\
	org.osgi.util.function;version='[1.1.0,1.1.1)',\
	org.osgi.util.promise;version='[1.1.1,1.1.2)',\
	com.amitinside.dummy.example;version=snapshot,\
	com.amitinside.dummy.provider;version=snapshot
```

Which seems to work as expected for me.

**Comment by amitjoy** [comment]
@bjhargrave Thanks for looking into it. I have to agree that it works properly in Gradle but not using the UI's resolve button (in the latest snapshot version). It still will add the proper bundle versions instead of `snapshot`.

**Comment by rotty3000** [comment]
I've found another place where this might be an issue @bjhargrave I'll send a PR with my proposed fix. I believe it's in addition to your current fix.

**Comment by amitjoy** [comment]
@bjhargrave @rotty3000 Thanks a lot for taking care of this. I updated my Eclipse installation to use the latest snapshot built yesterday (5.1.0.DEV-202004192359-g35ac7e9). Unfortunately the resolution result is also quite different. I tried to perform the resolve operation on the `test.bndrun` in the example repo I prepared earlier and it is as follows:

```
-runbundles: \
	com.amitinside.dummy.example;version=snapshot,\
	com.amitinside.dummy.provider;version='[1.0.0,1.0.1)',\
	org.apache.felix.gogo.command;version='[1.1.0,1.1.1)',\
	org.apache.felix.gogo.runtime;version='[1.1.2,1.1.3)',\
	org.apache.felix.gogo.shell;version='[1.1.2,1.1.3)',\
	org.apache.felix.scr;version='[2.1.16,2.1.17)',\
	org.osgi.util.function;version='[1.1.0,1.1.1)',\
	org.osgi.util.promise;version='[1.1.1,1.1.2)'
```

As you see that the current fix only added `snapshot` as version to one of the bundles (built from one of the workspace projects - `com.amitinside.dummy.example`) whereas the version of the `com.amitinside.dummy.provider` still uses semantic versioning format.

Could you guys kindly have a look at it?

**Comment by bjhargrave** [comment]
You need to make a clean build to replace all the `.index` files in the workspace. These files are generated with information required to fix this problem.

It is likely that the `com.amitinside.dummy.provider` project was not rebuilt and its `com.amitinside.dummy.provider/generated/.index` file is incorrect.

I get the desired `-runbundles` on your test repo:

```properties
-runbundles: \
	com.amitinside.dummy.example;version=snapshot,\
	com.amitinside.dummy.provider;version=snapshot,\
	org.apache.felix.gogo.command;version='[1.1.0,1.1.1)',\
	org.apache.felix.gogo.runtime;version='[1.1.2,1.1.3)',\
	org.apache.felix.gogo.shell;version='[1.1.2,1.1.3)',\
	org.apache.felix.scr;version='[2.1.16,2.1.17)',\
	org.osgi.util.function;version='[1.1.0,1.1.1)',\
	org.osgi.util.promise;version='[1.1.1,1.1.2)'
```

One other problem in your test repo is that you incorrectly specified a `-runblacklist` instruction. It must be in the form of a requirement, not just a bundle symbolic name.

```diff
diff --git a/cnf/ext/felix-launcher.bnd b/cnf/ext/felix-launcher.bnd
index b8b83d6..c20f59d 100644
--- a/cnf/ext/felix-launcher.bnd
+++ b/cnf/ext/felix-launcher.bnd
@@ -4,7 +4,7 @@
 -runtrace                       =         true
 -runrepos                       =         Workspace, Maven Central
 
--runblacklist                   =         com.amitinside.dummy.api
+-runblacklist                   =         bnd.identity;id='com.amitinside.dummy.api'
 
```

**Comment by amitjoy** [comment]
@bjhargrave Thanks for your continuous support. It works perfectly.
