### ISSUE TITLE
Improve support for SourceDebugExtension class file attribute

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3930]
The JVMS treats the value as a byte array but there must be an interop specification some place which would parse the information into something useful.

**Comment by bjhargrave** [comment]
JSR 45 seems to be the necessary specification.

**Comment by kriegfrj** [comment]
I just thought of a candidate for that "something useful" that this could be used for...

When looking at the Resolution view in Bndtools, it shows you all of the required capabilities of your bundle and the classes in your bundle that are generating these requirements. It should be possible to leverage the information from the JSR spec to tell you precisely which file/line number(s) generates the requirement and display this information in the Resolution pane, then have the double-click open up the editor at that line.

**Comment by bjhargrave** [comment]
I am closing this issue. The SourceDebugExtension attribute does not hold any type information. It is about mapping line numbers from one source file (e.g. `.jsp`) to the generated source file (e.g. `.java`) that is compiled to a `.class` file. This is of use to debuggers but it not relevant otherwise to Bnd.
