### ISSUE TITLE
Starts an Embedded instance and Unable to debug in eclipse

### ISSUE THREAD

**Issue by ederjc15** [bndtools/bnd#3963]
I'm not able to debug after update the plugin (bnd-run-maven-plugin) from version 4.2.0 to 5.0.1.

I just update it on pom from 4.2.0 to 5.0.1.
Analyzing the log I realize that my application starts an embedded instance and when I stop it on eclipse the Java process continue running.
I could not reproduce creating a simple projetc of exemple.

I just want to know if I can do this upgrade on my pom without another change? is it supported?
I just change the bnd-run-maven-plugin version from 4.2.0 to 5.0.1.
Should I do something more?

**Comment by bjhargrave** [comment]
> I just change the bnd-run-maven-plugin version from 4.2.0 to 5.0.1.
> Should I do something more?

You should not have to do more. But of course many changes have happened since 4.2. 

When you run something, it runs forever until the process ends itself. So perhaps your application is not properly exiting.

**Comment by ederjc15** [comment]
I understood.
when I start with 4.2.0 the java process is managed by eclipse. if I close eclipse the process is closed too, but on 5.0.1 the process conitnue running.

By the way,  I will try  get more informations.
Thank you!
