### ISSUE TITLE
[bndtools] QuickFix to suppress suggestions where class already on -buildpath

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3976]
Suppose I have `org.osgi:osgi.core:7.0` on `-buildpath`, and I type `Bundle` in my editor, and I haven't yet imported `org.osgi.framework.Bundle`.

Suppose also that I have `org.osgi:osgi.core:6.0.0` in one of my workspace repos, as well as one or more versions of framework implementations (Felix and/or Equinox).

As `org.osgi.framework.Bundle` is already on the build path, Eclipse's built-in quick fix suggestions will suggest to add `import org.osgi.framework.Bundle;` as a quick fix.

The new `BuildpathQuickFixProcessor` will also make a suggestion to add osgi.core:6.0.0 to the -buildpath, as well as suggestions for each of the other frameworks available in my repos.

IMO, these other suggestions are superfluous. Given that there is already a bundle on the buildpath that contains a class with fully-qualified name `org.osgi.framework.Bundle`, then there is no need to suggest other bundles that contain a class with exactly the same fully-qualified name. Indeed, as the added bundles would appear later in the classpath processing adding them is unlikely to have any effect on the build (at least as far as this import is concerned). So the `BuildpathQuickFixProcessor` should ideally be smart enough to know this and to avoid making those suggestions in that case.

It would, however, be reasonable for the `BuildpathQuickFixProcessor` to continue to suggest adding bundles that contain a class of the same *simple* name, as it is possible I might want to import another class from a different package.

**Comment by pkriens** [comment]
This is fixed in #4281
