### ISSUE TITLE
[quickfix] Handle inner classes

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3977]
I'm part-way through my port for the quick fix processor tests, and one area where we appear to have a hole is in the handling of inner classes - it seems that `BuildpathQuickFixProcessor` doesn't find or suggest them.

**Comment by pkriens** [comment]
I made that choice consciously since I noticed that inner classes often have very common names and it felt somehow wrong.

But we can discuss it ...

**Comment by kriegfrj** [comment]
One way around the "common name" problem would be if it comes back with too many suggestions, simply don't offer any as the probability that any given one of them is the right one is lower the more suggestions that you have. But if there's only a few matches, the chances are one of them is going to be the right one and so it's worth offering them as suggestions.

This could apply to top-level classes as well, though the chances of finding a name that common are likely to be less.

**Comment by pkriens** [comment]
I think we can get some feedback on this. So far it seems to work excellent. I just converted a build and it worked like a charm! This was a great idea Fr. Krieg!

**Comment by kriegfrj** [comment]
Yes,  converting a build was my original motivation... adding class lookup has multiplied the utility tenfold, and done so elegantly... well done!

**Comment by kriegfrj** [comment]
Just an update: #4291 fixes 80% of the problems with inner classes. The only thing that doesn't work is an unqualified reference to an inner class (ie, if you have `MyClass.MyInner`, and your code is `MyInner var`, then it won't make any suggestions.
