### ISSUE TITLE
publish the workspace instance as a service

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3980]
- entities depending on the workspace should track it
- "we will want a service tracker which lets people add callbacks to be called when the service appears. That way it is easy to init something later when the workspace is available"

**Comment by bjhargrave** [comment]
Do we still need this given recent changes made to Central for anyWorkspace?

**Comment by rotty3000** [comment]
I'd like to switch to this model since it will make several things much simpler.

**Comment by bjhargrave** [comment]
I am not sure how. Not all places in the code will have ready access to a BundleContext to get services. You could use DS but that does not get you a callback model like the current on*Workspace methods. You would also need to distinguish between a default workspace and a cnf workspace.

But I am open to a proposal...

**Comment by rotty3000** [comment]
We can close this for now. And if I ever come up with a proposal I'll just add another or reopen this issue.

**Comment by kriegfrj** [comment]
I'm currently looking at #3175. Prior to #3175, I'd like to convert the builder bundle to use a form of the facade pattern to make the dev work easier. However, I am running into startup dependency issues similar to the ones that plagued the quick fix processor tests.

I would like to revisit the idea behind this issue:
* Publish the workspace as a DS component.
* Other components that 

Re the comment: "Not all places in the code will have ready access to a BundleContext to get services" - with the `ExtensionFacade`, the interface between non-DS and DS code is much easier, and the facade has callback methods for when the backing service arrives/disappears. Also, the facade pattern makes it possible to turn many of the clients of the Workspace into DS components themselves, in which case DS reference annotation mechanism can be used to express the dependency on the workspace and DS will automatically handle the callback mechanism.

Unfortunately, I don't think I'm going to have a full appreciation for how this might work without pressing ahead with a prototype, so there's a risk I'll be wasting my time if I can't make it work, but I think it's a risk worth taking.

**Comment by bjhargrave** [comment]
> * Publish the workspace as a DS component.

See https://github.com/bndtools/bnd/blob/ec9368b9e7e2f71a86ac6a8835aa001a2495487b/bndtools.core/src/bndtools/central/Central.java#L311 where the Workspace is already registered as a service.

**Comment by kriegfrj** [comment]
Yeah thanks I found that after I posted. What do you think of the idea of 
1. unregistering and re-registering when the workspace directory changes;
2. setting a boolean property "default=true/false" on the registration depending on whether it is the default workspace.

**Comment by bjhargrave** [comment]
> 1. unregistering and re-registering when the workspace directory changes;

It would be better to use service properties and the modify these properties when things change. That way there is never a time when there is no workspace service present. You can have service properties for both directory and default-ness.

**Comment by kriegfrj** [comment]
And dependent DS components with static references will still be stopped and restarted when the props change?

**Comment by bjhargrave** [comment]
> And dependent DS components with static references will still be stopped and restarted when the props change?

No, but the component's updated method, if any, will be called. https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e32833

**Comment by kriegfrj** [comment]
> > And dependent DS components with static references will still be stopped and restarted when the props change?
> 
> No, but the component's updated method, if any, will be called. https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e32833

Got it, thanks! But you could achieve the restart behaviour I was talking about if the static `@Reference` annotation used a target expression that filtered on (eg) `default=true` or `default=false`? I'm thinking this might be an easier way to manage the asynchronicity of the workspace in many cases rather than using the callbacks.

**Comment by djencks** [comment]
You can do that for sure, but the referencing component won’t be restarted, because the conditions are no longer satisfied. (Or it will go from stopped to started).

**Comment by kriegfrj** [comment]
> You can do that for sure, but the referencing component won’t be restarted, because the conditions are no longer satisfied. (Or it will go from stopped to started).

:+1: Yes, I was a bit loose in my terminology. That is kind-of the functionality that I am after (I think).
