### ISSUE TITLE
Push `aQute.bnd.build.Workspace.WorkspaceData.classIndex` out of Workspace

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3981]
`WorkspaceClassIndex` should become agnostic of Workspace, akin to `AbstractIndexingRepository`, and then re-used by Workspace via composition so that workspace can be just one of N providers of Class indexes.

**Comment by pkriens** [comment]
That is the purpose of the Workspace ... not sure we should replicate with yet another abstraction?

**Comment by rotty3000** [comment]
See my comment on the other issue. I'm hitting problems with m2e.
