### ISSUE TITLE
bnd.hashes versioning

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3985]
Regardless of the outcome of #3984, I think one thing is clear - at some point, we may wish/need to change the format of `bnd.hashes`, and once there are indexes that have "escaped into the wild" using this format, it will be difficult to migrate them without some kind of versioning strategy in place that allows us to evolve the index format going forward.

This really needs to be in place before 5.1 goes out, otherwise we'll get stuck with legacy indexes with no way of migrating them.

I think the simplest and possibly most effective, space-efficient thing we can do is have a single global resource in the repo that had the version(s) information in it. Failing that, a parallel attribute on the osgi.wiring.package capability that denotes the version(s) of the hash, like `bnd.hashes.versions`.

I also think the schema should allow for multiple versions of the index to co-exist. Those in charge of generating the index can make a decision about which versions to include. Different versions of the index can be distinguished by concatenating the version to the attribute name, eg 'bnd.hashes.<version>'. If there is only one version of the index in the repo, maybe the ".<version>" could be omitted to keep it smaller.

```
  <resource>
    <capability namespace="osgi.identity">
      <attribute name="osgi.identity" value="bnd.hashes"/>
      <attribute name="type" value="bnd.hashes"/>
      <attribute name="version" value="1.0.0" type="Version"/>
    </capability>
</resource>
  <resource>
    <capability namespace="osgi.identity">
      <attribute name="osgi.identity" value="bnd.hashes"/>
      <attribute name="type" value="bnd.hashes"/>
      <attribute name="version" value="2.1.0" type="Version"/>
    </capability>
</resource>
```

...or maybe:

```
  <resource>
    <capability namespace="osgi.identity">
      <attribute name="osgi.identity" value="bnd.hashes"/>
      <attribute name="type" value="bnd.hashes"/>
      <attribute name="version" value="1.0.0,2.1.0" type="List<Version>"/>
    </capability>
</resource>
```

I'm not intimately familiar with the cap-req database schema and the rules so I'm not 100% sure what's possible/permissible (eg, is the multi-valued version attribute allowed for osgi.identity capabilities?) Hopefully the above is enough of an idea for someone to take it and run with it.

**Comment by pkriens** [comment]
I do not think this is necessary to already prepare for versioning in the first version. Once you need to make a version, you can always start adding a version since the first version would be identified by having _no_ version. I'd rather take the cost in the unlikely case we need to change it. For example, we might find out that we prefer a hash name instead of version. I've done many stupid things in my life trying to prepare for the future. Predicting the future tends to be hard and transitioning problems are always underestimated.

That said, I agree that if we can come up with a better hashing scheme than we should do it asap. Personally, I kind of like the standard Java String hash but I am open to suggestions.

**Comment by bjhargrave** [comment]
I think the way to handle versioning is just to use a different attribute name. `bnd.hashes` is v1, `bnd.hashes-2` could be the v2 name. Not unlike SHA-? versions. Then an index can have multiple hash versions and a runtime can use whatever is present with some preferences for better versions. 

So I think we don't need to do anything now. We only have to do something in the future if we decide it is needed.

**Comment by kriegfrj** [comment]
:+1:  I'm convinced. Do we leave this issue for when the time comes or close it?

**Comment by pkriens** [comment]
I think we can move it to abeyance.
