### ISSUE TITLE
[repository] MavenBndRepository source download implementation broken?

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4012]
I'm trying to implement #3899, and I've bumped into this piece of code:

https://github.com/bndtools/bnd/blob/28dbfe50374b9c35369fd173ee37ec184e0e632a/biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java#L916-L937

To me, this looks a bit broken. In particular, the archive referenced in lines 930 and 934 should be `sources` and not `primaryArchive` (which seems to be what `BndPomRepository` does). Otherwise, you get the binary jar returned instead of the source jar.

Either this is broken or there's some magic happening here that I don't understand. As the original author perhaps @pkriens could weigh in on this?

**Comment by bjhargrave** [comment]
Fixed by #4014
