### ISSUE TITLE
Better detection of maven dependencies 

### ISSUE THREAD

**Issue by swimmesberger** [bndtools/bnd#4015]
I have noticed that for some bundles which are published to our maven repository the dependencies in the pom.xml are incomplete. I debugged the cause and it seems that currently we try to determine the coordinates for an artifact based on the META-INF/maven/*/pom.properties file. This seems to work fine for most artifacts. There seems to be a couple of a maven publishes libraries which do not contain these pom.properties files - therefore we can't determine the maven coordinates and the dependency does not land in the dependencies xml tag of the pom.xml file.

Because we use the bnd workspace model with a MavenBndRepository I thought that the repository knows every maven coordinate of every dependency otherwise it would no be able to download it. Therefore my proposal to solve that problem is to let the repository optional provide some metadata information about an artifact which can then be used by the ProjectBuilder to determine the coordinates.

**Comment by bjhargrave** [comment]
You can add the metadata to the bnd file for any deps which don't have pom.properties files.

For an example were Bnd itself has this issue, see: 

https://github.com/bndtools/bnd/blob/0873afa941daf1a342abc2442fb5dd24b9825b6c/biz.aQute.bnd.reporter/bnd.bnd#L5-L16

**Comment by swimmesberger** [comment]
Yeah I have seen that here #3854 it seems fine for a adhoc solution. It's just feels counter intuitive when working with the bnd workspace model where you have defined every dependencies coordinates in e.g. central.mvn file that bnd can't use that information. So I though a "automatic" solution would benefit all bnd users.

**Comment by bjhargrave** [comment]
But how many artifacts in Maven Central are "broken" such that they do not have a pom.properties or pom.xml resource?

**Comment by swimmesberger** [comment]
Good question - in the case of our affected bundle 6 out of 26 dependencies we not added because of that issue. The most "popular" ones are the projectreactor libraries from the pivotal guys.

**Comment by swimmesberger** [comment]
I identified the dependencies which affect us for this bundle:
# no pom.properties
com.h2database:h2:1.4.200
io.projectreactor:reactor-core:3.3.1.RELEASE
org.reactivestreams:reactive-streams:1.0.3
io.projectreactor.netty:reactor-netty:0.9.7.RELEASE
# that seems to be in the list because it contains multiple pom.properties and we still use 4.x bnd
# got fixed with https://github.com/bndtools/bnd/commit/8f5f94f6f1d5a37c1f1c31dd83cdc7e775b48e8c
io.netty:netty-common:4.1.49.Final
