### ISSUE TITLE
[bnd-run-maven-plugin] Run in test phase with target/classes

### ISSUE THREAD

**Issue by kenwenzel** [bndtools/bnd#4031]
This issue is based on the discussion at [https://groups.google.com/d/msg/bndtools-users/MMBdqN-wU78/x1GKtbH2AwAJ](https://groups.google.com/d/msg/bndtools-users/MMBdqN-wU78/x1GKtbH2AwAJ).

For fast turnarounds it may sometimes be desirable to run the OSGi framework with exploded bundles. For example, web applications with HTML templates and JS files don't require a restart of the bundle if just a single line of code changes.
This way of running an application is the default behaviour of Eclipse PDE that simply handles all workspace projects as exploded bundles when starting the OSGi framework.

I tried to do the same with bnd-run-maven-plugin but it fails due to a check in FileSetRepository:
[https://github.com/bndtools/bnd/blob/3a4ea3ea7cba5359f0212487691693d0f488b1b5/biz.aQute.repository/src/aQute/bnd/repository/fileset/FileSetRepository.java#L98](https://github.com/bndtools/bnd/blob/3a4ea3ea7cba5359f0212487691693d0f488b1b5/biz.aQute.repository/src/aQute/bnd/repository/fileset/FileSetRepository.java#L98)

Is it possible to change the respective code for allowing bnd-run-maven-plugin to execute within `mvn test`?

**Comment by bjhargrave** [comment]
> Is it possible to change the respective code for allowing bnd-run-maven-plugin to execute within `mvn test`?

Did you try this change to see if it even works? I suspect there are many other parts of launching that expect bundles to be files. This is probably just the first place.

**Comment by kenwenzel** [comment]
Not yet. What is the best way to build and test the Maven plugins? How can I use Gradle to install them within my local Maven repository?

**Comment by bjhargrave** [comment]
When you build the project with gradle, it will install the jars into the local .m2/repo. 

See https://github.com/bndtools/bnd/blob/master/.github/scripts/build.sh for the targets to build.
