### ISSUE TITLE
bnd-maven-plugin inheritance between global and execution configuration does not work

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4040]
As a followup to #2265, if the parent configures the plugin in the execution configuration

```
<plugin>
  <groupId>biz.aQute.bnd</groupId>
  <artifactId>bnd-maven-plugin</artifactId>
  <version>5.0.1</version>
  <executions>
    <execution>
      <id>generate-osgi-metadata</id>
      <goals>
        <goal>bnd-process</goal>
      </goals>
      <configuration>
        <bnd>
header1: parent
        </bnd>
      </configuration>
    </execution>
  </executions>
....
```

and the child module configures via the global plugin config
```
<plugin>
  <groupId>biz.aQute.bnd</groupId>
  <artifactId>bnd-maven-plugin</artifactId>
  <configuration>     
    <bnd>
header2: child
    </bnd>
  </configuration>
</plugin>
```

Only the one from the parent execution config is seen.
The merging between global and execution configuration is not being implemented correctly (or at least differently than between plugin and pluginMgmt).

**Comment by rotty3000** [comment]
It appears as if you are not instructing the child to inherit from the correct parent execution. the child has to specify the same execution id as the parent. otherwise it inherits from the default execution.

**Comment by bjhargrave** [comment]
Closing this since it may be user error.

**Comment by kwin** [comment]
>  the child has to specify the same execution id as the parent. otherwise it inherits from the default execution.

Yes, but configurations can be given both within the execution and as global plugin configuration. I would expect that the merging does not follow Maven rules (i.e. same name elements in execution config overwrites global config) but rather the rules from bnd (i.e. bnd element would get instructions from both global and execution config). 

If that is not the case it should be clarified in https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin#bnd-instruction-inheritance.

**Comment by rotty3000** [comment]
You are correct, but bnd follows maven configuration inheritance. The scenario you provided doesn't allow for inheritance since the child cannot see the execution scoped configuration the parent provided. It can only see it if it specifies the same execution id.
