### ISSUE TITLE
[source] Make the build-time source lookup lazy

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4055]
Could we make the source lookup lazy? We do not automatically download the sources. The way it is currently done means that we will always download the sources, and actually right in the middle of the build when we initialize the classpath. 

Could make a delegated IClassPathEntry that would delegate to the real guy but fetches the source code when the getSourcePath() is called. We could actually download the source via a Promise and use the promise in the unlikely case it is used.

I have a customer who has no sources for a lot of maven projects. Currently, it always looks up the sources and goes online, only to get a 404. I also talked to BJ to see if we could build a 404 cache in the client but he wasn't too keen on this.

Tell me if you want me to make a proposal for this.

_Originally posted by @pkriens in https://github.com/bndtools/bnd/issues/4029#issuecomment-627992508_

**Comment by kriegfrj** [comment]
This is a good idea. I think it is feasible.

This issue was originally intended to deal with source lookup at launch time rather than build time (ie, `ISourceContainer`/`ISourceLookupDirector` rather than `IClasspathEntry`). My implementation initiates download for the source bundles during the launch initialisation but doesn't wait for it to finish - instead it uses a Promise (via DownloadListener). That way it doesn't slow down the launch but the sources should be ready when you want them.

However, the same concept could probably be applied to `IClassPathEntry` so that the download of sources doesn't happen synchronously on the build thread. That way the sources could be ready when you need them (making code navigation more responsive in the editor) but it shouldn't not slow down the build too much.

I'm happy for you to take this and run with it, as I've got plenty of other things I should be doing... :smile:

_Originally posted by @kriegfrj in https://github.com/bndtools/bnd/issues/4029#issuecomment-628054156_

**Comment by bjhargrave** [comment]
One thing to consider is how to remember you already tried and failed to get the sources jar, so we don't keep trying over and over to get something that does not exist (or is otherwise defective, like a malformed zip).

**Comment by kriegfrj** [comment]
> One thing to consider is how to remember you already tried and failed to get the sources jar, so we don't keep trying over and over to get something that does not exist (or is otherwise defective, like a malformed zip).

A few thoughts about this: I think the repository plugins need to handle this, as each repository type might have different definitions of failure.

We also need a mechanism for `RepositoryPlugin.get()` to be able to distinguish a failure from non-existence, which I think that the existing API gives us. We can use the convention that, in the synchronous case, it will return `null` if the bundle doesn't exist, and if it exists but couldn't be downloaded then the returned `File.exists()` will be false. In the asynchronous case (when you call `get()` with a `DownloadListener`) the `failure()` callback can distinguish between non-existence vs error.

The question then remains how long to cache the failure condition for. Should this be a bnd-wide setting, or a per-repository setting, or a bnd-wide default with a per-repository override? I suspect that the extra flexibility per-repository would be useful, so I think the main question is to whether a bnd-wide default is also useful.

There is also the question of how to manually override the cached failure, which I think is 
a necessary feature. A bnd command and/or a Bndtools menu option.

And that menu option also raises another issue - if/how to represent the download failures in the GUI. I think it would be good to show that the bundle exists with a download error, and then you could right-click on it to get an "retry download" to override the cached failure. Perhaps (eg) the "Clear from Cache" menu item (which the MavenBndRepository GUI already has) can be overloaded for this purpose, or an analogous one added for the sources (eg "Clear sources from Cache").

**Comment by gamerson** [comment]
Perhaps if we get a 404 that is cached, we could clear that cache on the next launch of the debug configuration automatically, along with the user invoked action of "retry download".
