### ISSUE TITLE
use javap output as default view for class files in Bnd Jar Viewer

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#4073]
Hey @pkriens what do you think of this idea? We know we always have access to javap since Java 8. We could use the Java Tooling API to execute it.

**Comment by bjhargrave** [comment]
There is already a bytecode disassembly viewer in Eclipse. Why not use that? We should not need to shell out to javap.

**Comment by bjhargrave** [comment]
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/277682/82254519-f6646800-9920-11ea-98dc-a043f99ee904.png">

**Comment by pkriens** [comment]
I looked at using the disassemblers in Eclipse. There is some way to use it but I got totally lost in trying to find out how to connect to it. It was over my pay grade.

Since we can now save the parsed classes, I think it would be quite simple to create a print output on this?

**Comment by rotty3000** [comment]
I guess I don't see the value in this view:
![Screenshot from 2020-05-19 14-29-22](https://user-images.githubusercontent.com/146764/82364367-3557f380-99dd-11ea-8792-f25fecbf6447.png)

**Comment by pkriens** [comment]
@rotty3000 well, it is a hell of a lot better than what we had before :-)

If you double click on the line you'll end up in whatever Eclipse has installed for editor. Which by default is javap

**Comment by rotty3000** [comment]
Yeah, I get all that. It's not really critical.
