### ISSUE TITLE
[generate] Allow run bundles for generate plugins

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4076]
I've been thinking about the new generate functionality to add Apache CXF code generation capability to my build. 

There is one hurdle i would need to overcome - the cxf codegen library has a lot of dependencies. Currently, the generate functionality requires the bundle to not have any external dependencies.

I can overcome this in bnd by embedding the dependencies in the generate plugin bundle; however this ties the plugin very firmly to a particular version of CXF, and I'm concerned we'll end up in a similar situation to what we had with `biz.aQute.junit`.

I was wondering if it might be worth considering the adding the equivalent of the ability for linking to external dependencies rather than embedding them.   Perhaps having a runbundles property to specify them, or using the revolver to try and find them using the plugin bundle as the seed/runrequires.

**Comment by pkriens** [comment]
It is a dilemma. At almost every pluggable system like Android, Apple iOS & desktop, I see that the direction is not have dependencies. The only dependency is the OS functionality, everything else you have to bring along. Although it creates a larger size, it reduces problems significantly. A very hard learned lesson.

So I considered it but I'd rather get some experience without introducing a dependency system than starting with it and causing lots of problems. No dependencies are the best you can have.

**Comment by kriegfrj** [comment]
> It is a dilemma. At almost every pluggable system like Android, Apple iOS & desktop, I see that the direction is not have dependencies. The only dependency is the OS functionality, everything else you have to bring along. Although it creates a larger size, it reduces problems significantly. A very hard learned lesson.
>

Yes, I think that approach is technically superior in an end-user scenario. However, I'm not convinced that the same reasoning carries over into a development environment, where you're already having to think about and deal with dependencies - in fact, I think the `biz.aQute.junit` experience taught us that taking away the developer's ability to manage the dependencies independently causes its own set of issues.

And it also occurred to me that even in an end-user scenario, the above approach may be technically superior but there are other non-technical reasons why it might not be desirable. Specifically, I'm thinking of licensing issues - some licenses will be fine with something like `-conditionalpackage`'s pick-and-choose approach to embedding dependencies, others will only allow you to redistribute the whole only (without picking and choosing), still others of course won't let you redistribute anything...

> So I considered it but I'd rather get some experience without introducing a dependency system than starting with it and causing lots of problems. No dependencies are the best you can have.

That is fair. For an initial cut of a cxf-codegen plugin I can embed the dependencies - they are all Apache licensed (I think) so there shouldn't be any problem with that. That will serve my immediate needs.

**Comment by pkriens** [comment]
I've been thinking to create an exporter that would make it easier to make stand-alone JARs that have no dependencies for non-OSGi use cases. Then you can define your executable in a bndrun file, resolve it, and export the assembly.

I see at customers and people that contact me that this is a common use case.

**Comment by kriegfrj** [comment]
Well, what if the `-generate` instruction had the option to take that same bndrun file as a parameter? Then the generate core code could dynamically load the bndrun's `runbundles` when it executes the plugin. Beauty of this approach is that the developer inputs are the same regardless of whether your choosing to create an export, or if you bypass the export and load the bundles directly. That would pretty much achieve what I originally asked for in the opening post. :smile:

**Comment by pkriens** [comment]
well, I think it is easier to share the binary, makes it easier for others to use it as well. 

Another concern is that in this case we're really mixing the repositories that are intended for the target product with the code that runs the build. The external plugin already does that but when you add a dependency mechanism it becomes paramount to have a separate set of repos.

**Comment by kriegfrj** [comment]
> well, I think it is easier to share the binary, makes it easier for others to use it as well.
>

As long as they want to use the same version of CXF that my binary was built with...
 
> Another concern is that in this case we're really mixing the repositories that are intended for the target product with the code that runs the build. The external plugin already does that but when you add a dependency mechanism it becomes paramount to have a separate set of repos.

bndrun has the `-runrepo` directive that can separate the repos if that is important.

**Comment by pkriens** [comment]
But how would you distribute that? A core tenet of OSGi/bnd is to share binaries instead of source code? If you make it a JAR(s) then you can share it through the repo model, we have no such model for bndruns

**Comment by bjhargrave** [comment]
Closing as not a good idea.
