### ISSUE TITLE
bnd-resolver-maven-plugin: Allow to reference bndrun and bundle files outside ${project.basedir}

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4077]
Currently looking up both `bndrun` files and `bundles` only works if they are located inside the `${project.basedir}` (https://github.com/bndtools/bnd/blob/19c7bf46b4ec2719fc4d4e72000cb495efd0dd35/maven/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/ResolverMojo.java#L106 and https://github.com/bndtools/bnd/blob/19c7bf46b4ec2719fc4d4e72000cb495efd0dd35/maven/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/ResolverMojo.java#L114). Sometimes it is desirable to reuse both for multiple Maven projects (and therefore reference them from outside the current Maven module's base directory).

Currently a config like this silently fails
```
<plugin>
                    <groupId>biz.aQute.bnd</groupId>
                    <artifactId>bnd-resolver-maven-plugin</artifactId>
                    <version>5.0.1</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>resolve</goal>
                            </goals>
                            <phase>verify</phase>
                        </execution>
                    </executions>
                    <configuration>
                        <bndruns>
                            <bndrun>../target-osgi-environment/aem6.3.bndrun</bndrun>
                        </bndruns>
                        <bundles>
                            <includes>
                                <include>../target-osgi-environment/target/bundles/*.jar</include>
                            </includes>
                        </bundles>
```

**Comment by bjhargrave** [comment]
Closing.
