### ISSUE TITLE
Difference between capabilities between FixedIndexRepo and LocalIndexedRepo in terms of capabilities exposed

### ISSUE THREAD

**Issue by derheld42** [bndtools/bnd#408]
Things don't resolve with FixedIndexRepo, but when deployed locally into a LocalIndexedRepo, they resolve. e.g. try resolving SLF4J-1.7.5 when remote using FixedIndexRepo

I didn't have a chance to dig in see the exact capabilities or metadata that caused this inconsistancy.

NOTE: FixedIndexRepo was pointing at my remote nexus server that has the nexus OBR plugin. I thought I remember a discussion on the mailing list about incompatibilities we might run into, but I can't remember the details.

**Comment by bjhargrave** [comment]
FixedIndexRepo has been removed from Bnd 4.0. It was replaced by OSGiRepository.
