### ISSUE TITLE
[bndtools m2e] Jars continuously rebuilt when "refresh on access" set

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4087]
This bug has been floating around for a while but it just got annoying enough for me to report it. @rotty3000 has seen it in action on my machine, but I've just managed to narrow down the root cause significantly.

It seems that Bndtools + m2e wants to continously re-run the "jar" goal for the project as soon as the jars become visible in the Project Explorer. It stops again once they are hidden. The attached screen capture demonstrates this.
![osgi-test-workspace-Eclipse-IDE-2020-05-21-11-19-07](https://user-images.githubusercontent.com/7224087/82515769-37928d00-9b58-11ea-9402-04016678686f.gif)

**Comment by rotty3000** [comment]
Is there a project for me to test? I have fixed bugs in this area but have
not experienced this with recent bndtools versions.

**Comment by kriegfrj** [comment]
The screen capture is from the `osgi-test` project.

If you're not already seeing it, then perhaps it's a Windows-specific thing?

**Comment by gamerson** [comment]
hey @kriegfrj   do you have "refresh on access" preference turned on in `window > preferencese > general > workspace` ?

**Comment by kriegfrj** [comment]
> hey @kriegfrj do you have "refresh on access" preference turned on in `window > preferencese > general > workspace` ?

@gamerson , yes I did - and when I turned it off, this continuous rebuilding behaviour stopped! Thanks for the pointer.

This is still a bug in some form or another though, isn't it? I'm not exactly sure what "refresh on access" is supposed to do but surely it should cause this?

**Comment by gamerson** [comment]
Yes, there is still some threading of the needle that the bnd-m2e-configurator needs to do in order to prevent the endless loops.  See here: https://github.com/bndtools/bnd/blob/master/bndtools.m2e/src/bndtools/m2e/BndConfigurator.java#L179-L192

**Comment by gamerson** [comment]
I have not been able to reproduce this issue on MacOS, even with the `osgi-test` workspace and `refresh on access` enabled.  There must be some other way to trigger this, but until we have a reproducible way to trigger it, there doesn't seem like much action we can take.

**Comment by gamerson** [comment]
Moving to abeyance.  @kriegfrj  if you are able to help me reproduce on MacOS, I will gladly take another look.

**Comment by bjhargrave** [comment]
Closed by #4789
