### ISSUE TITLE
[maven/m2e] Warn when testCases has invalid data

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4088]
I was trying to embed my Test-Cases header macro directly into the `<testCases>` element and wondering why it wasn't working.

Upon reading the docs more closely, I can see it's not designed for that - it only takes one of a few options (one of which is `useTestCasesHeader`, which I can use to do what I want). But instead of issuing an error, it silently ignored the error and used the default value (junit5).

It would be nice if it weren't so silent. Either warn and continue with the default, or else error and stop execution. I'm leaning towards the latter.

**Comment by bjhargrave** [comment]
I think this may be a maven issue. It is trying to coerce the string value in the `<useTestCasesHeader>` XML element into an enum value. I don't know how is handles a string value which does not correspond to an enum value? It may just use the default (`junit5`) without allowing our plugin to know of the coercion failure.

**Comment by kriegfrj** [comment]
I'd be surprised if Maven didn't have better handling of this but I don't have the time to investigate.

Another possibility (if Maven cannot be coerced into doing the right thing) is that we declare it as a String and do the conversion to enum in the plugin - this would give us the opportunity to do the sanity checking ourselves.

**Comment by bjhargrave** [comment]
> I was trying to embed my Test-Cases header macro directly into the `<testCases>` element and wondering why it wasn't working.

I tried `<testCases>${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE}</testCases>` with debug output showing.

```
<testCases default-value="junit5">${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE}</testCases>
```

this becomes:

```
testCases = junit5
```

in the actual configuration.

Maven is trying to evaluate `${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE}` as a Maven property and, not finding such a property, uses an empty string.

If you specify `<testCases>${some.missing.property.name}</testCases>` or `<testCases></testCases>`, you get the same result: the default value is used.

However, if I specify a bad value `<testCases>badvalue</testCases>`, then Maven properly complains:

> [INFO] [ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:5.2.0-SNAPSHOT:bnd-process-tests (bnd-process-tests) on project test-bnd-process-tests-goal-fragment: Unable to parse configuration of mojo biz.aQute.bnd:bnd-maven-plugin:5.2.0-SNAPSHOT:bnd-process-tests: Cannot convert 'badvalue' to Enum: No enum constant aQute.bnd.maven.plugin.TestCases.badvalue -> [Help 1]
> [INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:5.2.0-SNAPSHOT:bnd-process-tests (bnd-process-tests) on project test-bnd-process-tests-goal-fragment: Unable to parse configuration of mojo biz.aQute.bnd:bnd-maven-plugin:5.2.0-SNAPSHOT:bnd-process-tests: Cannot convert 'badvalue' to Enum

So the problem here, is that you failed to escape the leading `$` to stop Maven from evaluating it as a Maven property. Had you escaped it `<testCases>$${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE}</testCases>`, then you would have gotten the proper error message:


> [INFO] [ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:5.2.0-SNAPSHOT:bnd-process-tests (bnd-process-tests) on project test-bnd-process-tests-goal-fragment: Unable to parse configuration of mojo biz.aQute.bnd:bnd-maven-plugin:5.2.0-SNAPSHOT:bnd-process-tests: Cannot convert '${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE}' to Enum: No enum constant aQute.bnd.maven.plugin.TestCases.${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE} -> [Help 1]
> [INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:5.2.0-SNAPSHOT:bnd-process-tests (bnd-process-tests) on project test-bnd-process-tests-goal-fragment: Unable to parse configuration of mojo biz.aQute.bnd:bnd-maven-plugin:5.2.0-SNAPSHOT:bnd-process-tests: Cannot convert '${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE}' to Enum

So closing this as user error.

**Comment by kriegfrj** [comment]
Maybe the solution here is to warn if <testcases> is specfied, but empty then? That would have at least tipped me off.

**Comment by bjhargrave** [comment]
> Maybe the solution here is to warn if is specfied, but empty then?

I don't think there is any way the mojo can know this. It is just injected with an enum value. The mojo does not know the state of the configuration xml.
