### ISSUE TITLE
[launch] Build before launch option ignored?

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4089]
I've been having issues in m2e with "Build before launch" hanging indefinitely when trying to launch the JUnit OSGi tests. So I decided to try and disable it. Then I got this:

![Build before launch](https://user-images.githubusercontent.com/7224087/82526833-1a6bb780-9b74-11ea-9346-4bdec104c492.png)

It still tried to build before launch!

I'm not sure if this is related to the launch hanging issue. One thing that is different is that whereas it used to hang on 34%, now it is hanging on 4%.

**Comment by rotty3000** [comment]
Bndtools.m2e doesn't use the bndtools builder. The setting screen you are
looking at is mostly about the bndtools workspace model. This could be made
more clear.

**Comment by kriegfrj** [comment]
> Bndtools.m2e doesn't use the bndtools builder. The setting screen you are looking at is mostly about the bndtools workspace model. This could be made more clear.

Yes, but I'm still using the Bndtools _launcher_ when running `test.bndrun`, no? As far as I can tell by looking at the code, the decision about whether or not to build on launch is not made by the builder, but by the launching framework: the launch manager calls the `LaunchConfigurationDelegate`'s `buildForLaunch()`  method (in our case, that's `AbstractOSGiLaunchDelegate`) and if that returns `true`, then it starts an incremental build on the `IWorkspace` object. It is only at that point that Eclipse's builder infrastructure takes over and invokes the appropriate builders (whether that be the m2e builder or the Bndtools builder).

(As an aside, having looked at the code I think I've found the source of those magic numbers 4% and 34% - they are set by the `SubMonitor` setup in `LaunchConfiguration.launch()`.)

I think the issue is here:

https://github.com/bndtools/bnd/blob/b907eb38181892a2270785f4d88517b7a172b8cc/bndtools.core/src/bndtools/launch/AbstractOSGiLaunchDelegate.java#L158

It doesn't matter what you set the GUI to, if `AbstractJavaLaunchDelegate.buildForLaunch()` (the superclass) returns `true`, then so will our launch delegate. It looks like we might have the polarity wrong there. Fix coming.

**Comment by kriegfrj** [comment]
Well, I fixed this issue in my fork but even with the build-before-launch properly disabled & skipped I was still running into the hanging launch problem with the osgi-test repo. I started digging further and I think I'm onto something; (yet) another new issue to follow...
