### ISSUE TITLE
[bndtools m2e] Problems with consuming own artifact?

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4116]
In the osgi-test workspace, I'm persistently having niggling problems with the `org.osgi.test.assertj` bundle. Some of these are:

* I added an `@Export` to a newly-created package. The `test.bndrun` file would not resolve as it complained that the newly-created package could not be found, even though I could look at the generated jar in the project and see that the export was there. On top of this, when I actually ran the `test.bndrun` (as the missing export was from a bundle that was already in `-runbundles`), the tests ran fine.
* I'm seeing lots of warnings in the Eclipse and logback warnings like this "Could not resolve dependencies for project org.osgi:org.osgi.test.assertj:jar:0.9.0-SNAPSHOT: Could not find artifact org.osgi:org.osgi.test.assertj:jar:0.9.0-SNAPSHOT"

For the most part these niggles aren't stopping me from what I am doing. However, there seems to be some underlying inconsistency here that might be causing them and perhaps other run-time weirdness elsewhere.

**Comment by kriegfrj** [comment]
I named the title as I did because I thought this might be the significant feature of the assertj bundle that's causing the issue (ie, the fact that it is produced and consumed in the same workspace). However, I'm not sure if that is the real reason because the `org.osgi.test.common` bundle is also produced and consumed in the `osgi-test` workspace.

**Comment by rotty3000** [comment]
Could you maybe produce a small video to demonstrate? I have not experienced these issues but I wonder if they are somehow windows related.

**Comment by bjhargrave** [comment]
@kriegfrj Can you answer @rotty3000's query? Or can we close this?

**Comment by kriegfrj** [comment]
I'll try and do this at some stage.

**Comment by kriegfrj** [comment]
Ok, in the process of implementing https://github.com/osgi/osgi-test/issues/121 I think I may have hit upon a concrete example of this bug.

- I have added `bnd-resolver-maven-plugin` and `bnd-testing-maven-plugin` to the `org.osgi.test.assertj.framework` project pom.
- When I attempted to resolve my `test.bndrun` (using `./mvnw verify` to build the whole project) , I got the following:

```
[INFO] --- bnd-resolver-maven-plugin:5.1.2:resolve (resolve-test) @ org.osgi.test.assertj.framework ---
[INFO] Bnd inferred -runee: JavaSE-1.8
[WARNING] Could not resolve dependencies for project org.osgi:org.osgi.test.assertj.framework:jar:0.10.0-SNAPSHOT: Could not find artifact org.osgi:org.osgi.test.assertj.promise:jar:0.10.0-SNAPSHOT
[WARNING] Failed to resolve dependency org.osgi:org.osgi.test.assertj.promise:jar:0.10.0-SNAPSHOT
[INFO] -runbundles: assertj-core;version='[3.16.1,3.16.2)',junit-jupiter-api;version='[5.6.2,5.6.3)',junit-jupiter-engine;version='[5.6.2,5.6.3)',junit-jupiter-params;version='[5.6.2,5.6.3)',junit-platform-commons;version='[1.6.2,1.6.3)',junit-platform-engine;version='[1.6.2,1.6.3)',junit-platform-launcher;version='[1.6.2,1.6.3)',net.bytebuddy.byte-buddy-agent;version='[1.10.13,1.10.14)',net.bytebuddy.byte-buddy;version='[1.10.13,1.10.14)',org.mockito.mockito-core;version='[3.4.6,3.4.7)',org.objenesis;version='[2.6.0,2.6.1)',org.opentest4j;version='[1.2.0,1.2.1)',org.osgi.test.assertj.framework;version='[0.10.0,0.10.1)',org.osgi.test.common;version='[0.10.0,0.10.1)',org.osgi.test.assertj.framework-tests;version='[0.10.0,0.10.1)'
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for org.osgi:org.osgi.test.parent 0.10.0-SNAPSHOT:
[INFO]
[INFO] org.osgi:org.osgi.test.parent ...................... SUCCESS [01:44 min]
[INFO] org.osgi:org.osgi.test.common ...................... SUCCESS [ 42.352 s]
[INFO] org.osgi:org.osgi.test.assertj.framework ........... FAILURE [  6.224 s]
[INFO] org.osgi:org.osgi.test.assertj.promise ............. SKIPPED
[INFO] org.osgi:org.osgi.test.junit4 ...................... SKIPPED
[INFO] org.osgi:org.osgi.test.junit5 ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

I thought that the problem might be the reactor build order - the `.promise` project is built after the `.framework` project. So I manually built the `.promise` project first, and then tried re-running the above. Same error.

To get it to work, I had to run `mvn install -pl org.osgi.test.assertj.promise` to install the `.promise` artifact into my local maven repo, and then run.

A workaround for my particular situation would be to not have `.promise` as a test dependency - currently `.framework` does not actually depend upon `.promise`; it has simply inherited the dependency declaration from the parent pom which was put there as a convenience. However, I think in the generic case there might be situations where an actual dependency would exist (eg, the two junit bundles' test dependency on the assertj bundles is analogous).

What would need to happen in this case then is to change the reactor build order so that `.promise` comes before `.framework`. I'm not sure if this is something that maven plugins have any control over. Morever, it seems that maven wants to execute all the goals for each project before moving on to another project, and this configuration would require that it do the jar goals for both `.framework` and `.promise` and only *then* move on to the resolve/integration-test phases for `.framework`.

This might also be a case of circular dependency preventing reactor ordering from coming up with an order that works (as the both assertj bundles are declared as test dependencies in the parent pom, so each inherits the other as a test dependency). In which case, a generic solution might not be possible and perhaps it would be better for us to warn (if possible).

**Comment by rotty3000** [comment]
You have to build modules in the correct order. Maven does not build
projects in dependence order, only in reactor order. That is, unless you
execute maven with `-am` (a.k.a. `--also-make` dependencies: If project
list is specified (i.e. -pl), also build projects required by the list.)

Normally reactors have the modules configured in a particular order to not
require special instructions.

**Comment by bjhargrave** [comment]
> [WARNING] Could not resolve dependencies for project org.osgi:org.osgi.test.assertj.framework:jar:0.10.0-SNAPSHOT: Could not find artifact org.osgi:org.osgi.test.assertj.promise:jar:0.10.0-SNAPSHOT
> [WARNING] Failed to resolve dependency org.osgi:org.osgi.test.assertj.promise:jar:0.10.0-SNAPSHOT

I think this means we need to isolate integration testing to a project which builds at the end of the dependency order. Which is why I think we current have all the integration tests in junit5 project.

So I think this issue is not a real bug.
