### ISSUE TITLE
Name generated of the referenced service in constructor is not as per specs.

### ISSUE THREAD

**Issue by rakeshk15** [bndtools/bnd#4123]
Consider this constructor declaration.

`
@Activate
 public MyComponent(@Reference SomeUsefulService service1, @Reference AnotherUsefulService service2) {
}
`

Now @Reference documentation says - 

**Annotated constructor parameter - The name of the reference is the parameter name**

But generated component xml has something like this

`
<reference name="$000" interface="x.y.z. SomeUsefulService" parameter="0"/>
<reference name="$001" interface="a.b.c.AnotherUsefulService" parameter="1"/>
`

Look at the name of each reference starting with $.

This is not affecting any functionality but still wants to report it for consistency and correctness.

Thanks,
Rakesh

**Comment by rotty3000** [comment]
bnd cannot get parameter names unless you have instructed the compiler to keep parameter names in bytecode (using the `-parameters` flag.)

**Comment by rakeshk15** [comment]
ok, that makes sense.

thanks for the prompt response @rotty3000

**Comment by rakeshk15** [comment]
Working as expected so closing it.
