### ISSUE TITLE
bnd-indexer-maven-plugin: Failed to determine the artifact URI for artifact <x>.... Unable to index artifact <x>. The repository local is not known to this resolver

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4125]
When trying to build https://github.com/apache/sling-org-apache-sling-starter/pull/8 I run into the following exception:

```
[INFO] --- bnd-indexer-maven-plugin:5.0.1:index (index) @ org.apache.sling.starter ---
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/biz/aQute/bnd/biz.aQute.bnd.maven/5.0.1/biz.aQute.bnd.maven-5.0.1.pom
[INFO] Downloaded from central: ...
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/xmlbeans/xmlbeans/maven-metadata.xml (427 B at 27 kB/s)
[ERROR] Failed to determine the artifact URI for artifact org.jvnet.staxex:stax-ex:jar:1.7.6
java.io.FileNotFoundException: Unable to index artifact org.jvnet.staxex:stax-ex:jar:1.7.6. The repository local is not known to this resolver
    at aQute.bnd.maven.indexer.plugin.IndexerMojo$RepositoryURLResolver.resolver (IndexerMojo.java:343)
    at aQute.bnd.maven.indexer.plugin.IndexerMojo.execute (IndexerMojo.java:177)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

(https://builds.apache.org/blue/organizations/jenkins/Sling%2Fsling-org-apache-sling-starter/detail/feature%2Fgenerate-index/1/pipeline)

From the error message it is not clear what went wrong as the artifact https://search.maven.org/artifact/org.jvnet.staxex/stax-ex/1.7.6/jar is clearly available at Maven Central.

**Comment by bjhargrave** [comment]
Are you trying to generate an index in every project?

Also, you have not set the `<localURLs>` config property. So it defaults to `FORBIDDEN` and you are getting an error because it cannot find a remote URL for the artifact (in .m2).

I thought you only needed an index for the bndrun executions?

**Comment by kwin** [comment]
> Are you trying to generate an index in every project?

No, this is a special distribution project which aggregates several bundles

> Also, you have not set the <localURLs> config property. So it defaults to FORBIDDEN and you are getting an error because it cannot find a remote URL for the artifact (in .m2).

This is a transitive Maven dependency which is available from Maven Central, why do I need to configure a local URL then?

**Comment by bjhargrave** [comment]
Why do you want to use a remote URL to generate an index that is only used locally? You ask the user of the index to re-download the files from there remote URL if they are needed. For the purposes of only using the index during the build, local URLs would be preferred. You want to use remote URLs if you are going to publish the index for others to use and they would then need URLs which don't point to local files in your build.

**Comment by kwin** [comment]
> You want to use remote URLs if you are going to publish the index for others to use and they would then need URLs which don't point to local files in your build.

This is exactly my use-case. 
Could you comment on the exception from this issue? I don't want to use local URLs, the artifact itself is available from central and still I get the exception...

**Comment by bjhargrave** [comment]
Can you run with `--debug` to get some debug logging from the plugin?

**Comment by kwin** [comment]
Attached is the debug log from the execution of that goal:
[debug.log](https://github.com/bndtools/bnd/files/4712798/debug.log)

The affected artifact is available in my local repo, in Central and also in my mirror remote repo (a Nexus).

**Comment by bjhargrave** [comment]
From the debug log, the code at 

https://github.com/bndtools/bnd/blob/35be827575e9b3f9b98e20a7cfb2b9d1c8f657df/maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java#L148-L158

found only 2 repositories:

```
[DEBUG] Located an artifact repository nexus
[DEBUG] Located a deployment repository apache.snapshots.https
```

Later we see that a remote repository containing some artifacts cannot be located:

```
[DEBUG] Unable to resolve a remote repository containing org.apache.aries:org.apache.aries.util:jar:1.1.3
```

So later we have the error

```
[ERROR] Failed to determine the artifact URI for artifact org.apache.aries:org.apache.aries.util:jar:1.1.3
```

I am not sure what else may be going on here. We probably need advice from @timothyjward who authored this originally.

**Comment by kwin** [comment]
>[DEBUG] Located an artifact repository nexus
[DEBUG] Located a deployment repository apache.snapshots.https

The 1st one is the mirror from my settings.xml, the 2nd is given in the pom.xml. Both is correct.

> [DEBUG] Unable to resolve a remote repository containing org.apache.aries:org.apache.aries.util:jar:1.1.3
This is wrong, as the repo called "nexus" has it as well as Maven Central which is proxied by "nexus".

**Comment by bjhargrave** [comment]
@kwin Is this still an issue for you? Can you please provide a small github repo which demonstrates the problem? (since Sling is huge).

**Comment by kwin** [comment]
Still an issue. In this case caused by an invalid local metadata in my repo. It would be good to somehow force the resolver to check remote repos in this case. As for the branch mentioned in the description of this issue this also happens on the ASF Jenkins (with no local repo) there must be a 2nd issue. I will provide further logs with an empty local repo...

**Comment by kwin** [comment]
It now only fails on the ASF Jenkins due to https://repo.maven.apache.org/maven2/org/jvnet/staxex/stax-ex/maven-metadata.xml not containing version https://repo.maven.apache.org/maven2/org/jvnet/staxex/stax-ex/1.7.6/. Clearly an issue with Maven Central, I therefore raised https://issues.sonatype.org/browse/MVNCENTRAL-6147.

**Comment by kwin** [comment]
After the metadata was fixed it works correctly now. Therefore closing this issue here.

**Comment by kwin** [comment]
The https://repo.maven.apache.org/maven2/org/jvnet/staxex/stax-ex/maven-metadata.xml is again corrupt. I asked for fixing it again in https://issues.sonatype.org/browse/MVNCENTRAL-6303, but as this seems to be a frequent issue with Maven Central Metadata the bnd-indexer-maven-plugin should be more resilient against those issues (and also emit a clearer warning in case it happens).

**Comment by bjhargrave** [comment]
So you are saying we should not trust the `maven-metadata.xml ` files on Maven Central? 

I am sure we use the Maven APIs to find artifacts in remote repositories. If the Maven APIs are using `maven-metadata.xml ` files and fail to find the artifact, why should we not trust that?

**Comment by kwin** [comment]
All I am saying is that there should be a fallback in case the metadata is corrupt. Also you usually only need to leverage the metadata in case the version isn't given (which shouldn't be the case here)

**Comment by bjhargrave** [comment]
My point is that since we use the Maven API to request artifacts from remote repositories, how are the bnd maven plugins to know the metadata is corrupt? And when I look the file you linked, it does not look corrupt per se. It is just missing some versions you know to exists. How would any reader of the file know it was corrupt without some external knowledge of that fact?

**Comment by kwin** [comment]
Probably you use the wrong Maven API. Also since this is triggering an exception you obviously can try to guess the URL in some other way and only in case that fails as well throw the exception. Let me first try to reproduce the issue with a simple project and then I hopefully have a better idea which API is called internally, because as you said, the actual call to maven-metadata.xml does not fail per se.
