### ISSUE TITLE
[junit-platform] Optionally prune singleton non-leaf nodes from test hierarchy

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4128]
In a departure from the original bnd tester, the new junit-platform tester adds additional levels of hierarchy into the test output:

test bundle -> test fragment (optional) -> test engine -> regular JUnit hierarchy

I did this because I envisioned that large integration tests could have lots of tests from lots of different bundles (even potentially having tests with the same name from different bundles), and having some sort of visual representation of this would allow one to navigate it more easily.

@rotty3000 first mentioned in #3673 that he found this extra depth annoying. Having played with osgi-test for a while now I have come to appreciate this position a bit better - while the feature I added will be helpful for other use cases, I can see that a common use case will be "one test bundle, one engine" (and maybe one fragment). This is how osgi-test is structured, for example. In such cases, the representation of the bundle [, fragment] and test engine nodes do not add any value - in fact, they just get in the way.

As I mentioned in #3673 (and indeed in the original PR #3145), I think the best way to get the best of both worlds is to have a "prune" function that removes singleton non-leaf nodes (ie, those with no siblings) from the test hierarchy. This feature would be enabled by default but could be disabled if you really want to see the full hierarchy always. I guess this is similar in principle to how GitHub's file tree browser skips over empty directories.

One question that I wanted to put to the team for consideration: how far down the hierarchy should this extend? There are three options that make sense to me:

1. `BundleEngine` prunes only its part of the hierarchy and preserves the hierarchy generated by the sub-engine(s) as-is.
2. `BundleEngine` also prunes the hierarchy of sub-engines using the same algorithm.
3. Configurable so that you can do either 1 or 2 (or neither).

Thoughts?

**Comment by bjhargrave** [comment]
I am not sure people will care about a grouping by engine. The will care about a grouping by the test artifacts they create like test bundles/fragments. The engine is just, basically, an impl detail. So I would think we don't need engines to show up in any hierarchy.

**Comment by kriegfrj** [comment]
The problem is if you have mixed tests, some for JUnit 4 and some Jupiter (or even another engine). Even more so when they are mixed in a single class - you'll end up with two class nodes in the hierarchy (one from the Vintage engine, one from the Jupiter engine). There's no easy/portable way to merge them, and it might be a little disconcerting.

**Comment by rotty3000** [comment]
@kriegfrj I think the solution might be over complicating things. at this stage it might be over the top to add configuration options for this. I agree with @bjhargrave that once we choose a tree mode that we should just always use that. So I'm for no configuration for this.
