### ISSUE TITLE
[junit-platform] Add package nodes to test hierarchy

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4129]
Working on osgi-test, as our number of test classes increases, the display becomes a little more cluttered. That's because Jupiter (and Vintage for that matter) always displays the test classes in a flat hierarchy - all test classes from all packages appear at the engine root level.

We have the opportunity to restructure this and make it more hierarchical - adding additional nodes to represent the packages and group test classes under their package nodes. This will be useful if you have a bundle with lots of test classes in multiple different test packages.

I know that @rotty3000 is already concerned that the test hierarchy generated by the junit-platform tester is too deep, and this feature would make it worse, so if I proceed with this it will probably be in conjuction with #4128.

**Comment by bjhargrave** [comment]
I am not sure this is really worth doing. The tree is already bushy. And as I said in the comment in the PR for 4128, I would rather not have user configurable tree shaping.
