### ISSUE TITLE
bnd-resolver-maven-plugin fails to resolve with Java 15 project

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#4137]
an example failure is:
```
[ERROR] Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.apache.aries.jax.rs.itests)
          ⇒ [org.apache.aries.jax.rs.itests version=1.0.9.202006041558]
              ⇒ osgi.wiring.package: (osgi.wiring.package=javax.ws.rs.client)
                  ⇒ [org.apache.geronimo.specs.geronimo-jaxrs_2.1_spec version=1.1.0]
                      ⇒ osgi.serviceloader: (osgi.serviceloader=javax.ws.rs.ext.RuntimeDelegate)
                          ⇒ [org.apache.aries.jax.rs.whiteboard version=1.0.9.202006041558]
                              ⇒ osgi.wiring.package: (osgi.wiring.package=javax.crypto)
```
Note that this issue does not appear when running on any previous versions of Java.

The issue appears to be in the EE enum where starting at Java 15 the `_0` suffix was dropped while the properties file was not updated the same way.

**Comment by rotty3000** [comment]
this should be targeted for a maintenance release.

**Comment by bjhargrave** [comment]
> this should be targeted for a maintenance release.

Do we know if the packages and modules lists in the properties files are correct for Java 15?

**Comment by rotty3000** [comment]
I'll double check.

**Comment by rotty3000** [comment]
modules needs a minor update. doing that. How did we normally generate the package list?

**Comment by bjhargrave** [comment]
> How did we normally generate the package list?

By hand :-/

**Comment by bjhargrave** [comment]
> > How did we normally generate the package list?
> 
> By hand :-/

https://github.com/bjhargrave/java-platform-packages can do it
