### ISSUE TITLE
program gradle Resolve task without a bndrun file

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#4141]
It would be great if the resolve task could be programmed without a bndrun file like the bundle task (which pipes the properties into a file internally to get the correct effect).

This would eliminate a lot of bootstrapping code in ad hoc scenarios.

Current arrangement looks like:
```
def osgiPropertiesFile = file("$buildDir/verifyOSGiProperties.bndrun")

tasks.register("osgiProperties", WriteProperties) {
  outputFile = osgiPropertiesFile
  property("-standalone", true)
  property("-runee", "JavaSE-1.8")
  property("-runrequires", "osgi.identity;filter:='(osgi.identity=${project.name})'")
}

tasks.register("verifyOSGi", Resolve) {
  dependsOn(osgiProperties)
  setBndrun(osgiPropertiesFile)
  reportOptional = false
}

tasks.check {
  dependsOn(verifyOSGi)
}
```
ideally it would be something like:
```
tasks.register("verifyOSGi", Resolve) {
  bndrun(
    "-standalone": "true",
    "-runee": "JavaSE-1.8",
    "-runrequires": "osgi.identity;filter:='(osgi.identity=${project.name})'"
  )
  reportOptional = false
}

tasks.check {
  dependsOn(verifyOSGi)
}
```

**Comment by rotty3000** [comment]
any task that accepts a bndrun should be interested.

**Comment by bjhargrave** [comment]
I think you are saying there is a bnrun file on the file system by it is created by this new support using info provided in the gradle file? 

I think is probably a bad idea since that tmp file would have to be in the root of the project since, as previously discussed, bndrun files must be in the root of the project and writing into the source folder is a bad idea.

**Comment by rotty3000** [comment]
How do we make this work for bundle task? Could we add support maybe for when no bndrun file is passed to require setting the base?

Note that creating standalone workspace already has the ability to forego a real file:
`public static Workspace createStandaloneWorkspace(Processor run, URI base)`

**Comment by bjhargrave** [comment]
For a bundle task, we just need to set properties into the Builder. The Builder is separated from the Project/Workspace types. Bndrun is a Project :-/

**Comment by bjhargrave** [comment]
Closing for now.
