### ISSUE TITLE
support ability for gradle tasks to infer `-runee`

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#4142]
The `bnd-*-maven-plugin`s have this support and it makes testing simpler by allowing the outer build to switch it's Java version whereby that information trickles down into the plugins.

It would be great if gradle tasks supported the same.

**Comment by rotty3000** [comment]
perhaps this is only intersting to the resolve task (unlike in bnd-*-maven-plugins where several of those could resolve.)

**Comment by rotty3000** [comment]
actually, any task that accepts a `bndrun` should be interested.

**Comment by bjhargrave** [comment]
I am not sure what inferring -runee means. Shouldn't Bnd always just use the current java if no -runee is specified? Why should the drivers (gradle, maven, eclipse) have to take special care?

**Comment by rotty3000** [comment]
the fallback would certainly be _current java_. But since drivers have these source/target configurations one might need to consider those. in maven we consider this, and then use _current java_ as fallback.

**Comment by rotty3000** [comment]
See https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java#L275-L299

**Comment by rotty3000** [comment]
actually, the fallback for maven isn't quite _current java_ however, maven itself will always provide a value pretty much. The fallback `.orElse(EE.JavaSE_1_8));` will essentially never be used. It's just a protection.

**Comment by rotty3000** [comment]
actually...
```
.orElseGet(() -> EE.highestFromTargetVersion(System.getProperty("java.version"))
						// if that all fails at least we know bnd needs at least
						// Java 8 at this point
						.orElse(EE.JavaSE_1_8));
```
it does fallback on _current java_!

**Comment by bjhargrave** [comment]
I guess my point is, why isn't the inference of -runee does in Bndrun? Where every driver benefits?

**Comment by rotty3000** [comment]
The point is NOT to set it at all! I maven all I need to do is change JAVA_HOME then run with the new Java and everything resolves and runes against the new Java including the inferred EE. This is great for matrix CI runs.

**Comment by rotty3000** [comment]
This is most useful when resolve happens as part of the build, which is the point here. IF you don't then just set the `-runee` to a preset value.

**Comment by bjhargrave** [comment]
> The point is NOT to set it at all!

Yes, I fully get that. That is why I said "why isn't the inference of -runee done in Bndrun?" That is the type Bndrun, not the bndrun file.

**Comment by rotty3000** [comment]
Got it! I think that would be reasonable. Do you think reading details from the build driver is wrong then?

**Comment by bjhargrave** [comment]
Bndrun (type) can infer -runee from the Java in which it is executing. So if your build is running on Java 11, Bndrun would infer -runee to be Java 11. You don't need to have Bndrun know anything about the driver for that.

**Comment by rotty3000** [comment]
I'm asking if the compilation target level should have anything to do with this calculation the way it does in maven?
