### ISSUE TITLE
support ability for gradle tasks to infer `-runrequires`

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#4143]
The bnd-*-maven-plugins have this support and it makes things simpler by enabling the default to be something like "resolve me".

It would be great if gradle tasks supported the same.

Effectively this is programming a default of `-runrequires: osgi.identity;filter:='(osgi.identity=${project.name})'` when no `-runrequires` instruction is provided.

Any task accepting a bndrun should be interested in this.

**Comment by bjhargrave** [comment]
`osgi.identity=${project.name}` may make sense for maven, but for a Gradle project, there can be many jar tasks. Should all the jar tasks outputs be runrequired?

**Comment by rotty3000** [comment]
Maven can also have many jars. The point is more than 90% of the time there is one only. And I believe that is a reasonable default and assumption.
