### ISSUE TITLE
[ReportGenerator] Short Plugin Names

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4150]
I ran into a bug and then had to debug the ReportGenerator. 

I noticed: https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/generator/ReportGeneratorBuilder.java#L215-L231

First, I think this is a nice feature, it would be nice if that was implemented in bndlib for everybody. (Actually now have support for this by using capabilities). 

Anyway, my problem is with the implementation. In the code you first get the class, then get the name, and then load the class in findName. This is a very roundabout way. Just use the class, and in this case since you have a selected set, I would use a constant for the name that is used in the registration and the BndPlugin name. Then you can use the same constant wherever you are referring to this thing.

**Comment by cdelg** [comment]
I'm not sure what you re suggesting: 

> Just use the class
Does that mean, in general, the register method should use a Class parameter instead of the name the class?

> and in this case since you have a selected set, I would use a constant for the name
And for plugins in the reporter module, to maintain a set of constants referring to the plugins class names instead of calling `class.getCanonicalName` for each of them?

**Comment by stbischof** [comment]
we should use
`registerPlugin(AnyEntryPlugin.class);` not
`registerPlugin(AnyEntryPlugin.class.getCanonicalName());`

because `registerPlugin` calls `findPluginName`
```
public ReportGeneratorBuilder registerPlugin(final String className) {
		Objects.requireNonNull("className", className);

		final String shortName = findPluginName(className);
```

and `findPlugin` calls `final Class<?> pluginClass = Class.forName(className);`

```
private String findPluginName(final String className) {
		try {
			final Class<?> pluginClass = Class.forName(className);
			if (pluginClass != null) {

```

**Comment by cdelg** [comment]
I will make the change.

On another topic but still related to the implementation, the ReportGenerator can generate a report of any type of object, this is nice but maybe useless. I mean the purpose of the generator is to be apply on a workspace, a project, a builder or a jar (a limited set of types). If I could limit to this set of types, I think the use and the implementation could be simplified, the only thing that prevent me to implement in this way is Maven. In Maven we can have a hierarchy of submodules and only one artifact per project, with bnd we have only one layer of submodule (the workspace) and possibly multiple artifacts per projet. So my question is, is it possible to convert the entire structure of a Maven project into a bnd structure, if not is it possible to build the abstraction that could allow this? (This would also prevent to have specific entry plugins for Maven).

Another question for @pkriens, I saw somewhere a tool that you developed to handle a kind a Xpath but for DTOs, I can't find it into the bnd code base. This could be useful to split the generated report and spread the subreports into multiple files to generated a kind multipage wiki doc.

**Comment by pkriens** [comment]
@cdelg See DomDTOParser. I also had to look :-)

> is, is it possible to convert the entire structure of a Maven project into a bnd structure, if not is it possible to build the abstraction that could allow this?

I started working on a Maven project directory (with recursion) to workspace converter. I'll keep this use case in mind.
