### ISSUE TITLE
Lack of information in error message "Non annotation type for activation object with descriptor"

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4171]
In case of a DS component leveraging constructor injection incorrectly like this

```
....
@Activate
    public MyComponent1(@Reference MyComponent2 myComponent2, MyComponent3 myComponent3) {
        ...
    }
```
The following error is emitted from `bnd-maven-plugin:5.1.0:bnd-process`

```
[ERROR] <path to pom.xml> [0:0]: Non annotation type for activation object with descriptor (LMyComponent2)V, type MyComponent3
```

The crucial information, the name of the component/class containing the invalid constructor is missing in the error message, so you have to guess which class might contain such an activate object.

**Comment by pkriens** [comment]
I guess because in bndtools this is reported on the actual location ...

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.
