### ISSUE TITLE
Create bnd-jar-maven-plugin as a maven-jar-plugin replacement

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4174]
Sonatype has a `nexus-staging-maven-plugin` which worms its way into the maven project tree to replace the `maven-deploy-plugin`. So it becomes the replacement for the `deploy` goals.

See https://github.com/sonatype/nexus-maven-plugins/blob/master/staging/maven-plugin/src/main/java/org/sonatype/nexus/maven/staging/deploy/DeployLifecycleParticipant.java for the details of how `nexus-staging-maven-plugin` does this replacement

Perhaps Bnd could do something similar to replace the `jar:jar` and `jar:test-jar` goals of the [`maven-jar-plugin`](https://maven.apache.org/plugins/maven-jar-plugin/). This new `bnd-jar-maven-plugin` could then be a full replacement for `maven-jar-plugin` which would give Bnd full control over the making of the jar while still allowing other maven plugins which expect `maven-jar-plugin` behavior still properly function.

**Comment by stbischof** [comment]
@juergen-albert maybe this would be a good way to go.

**Comment by stbischof** [comment]
I had a short look on the `nexus-stagung-plugin` replacement mechanism. The tests and plugin are here
https://github.com/stbischof/bnd/tree/mvn_jar
