### ISSUE TITLE
Export Bndtools LaunchDelegate

### ISSUE THREAD

**Issue by swimmesberger** [bndtools/bnd#4177]
When writing a profiling plugin it's needed to import the LaunchDelegate (e.g. OSGiRunLaunchDelegate) but currently that's not possible because the package is not exported. PDE is exporting the launch delegate bundle here: https://github.com/eclipse/eclipse.pde.ui/blob/master/ui/org.eclipse.pde.launching/META-INF/MANIFEST.MF#L22

To enable such use cases we should probably move the launch delegates into the [api package](https://github.com/bndtools/bnd/tree/master/bndtools.core/src/bndtools/launch/api) or add the launch package to the exported packages list.

**Comment by pkriens** [comment]
Can you provide a PR? I'm ok with this idea, would be very nice to have profiling support.

**Comment by swimmesberger** [comment]
It seems that since https://github.com/bndtools/bnd/pull/2920 the bndtools.launch package is indeed exported and I'm simply using an older version of bnd.

**Comment by swimmesberger** [comment]
@pkriens just as a side note: In cooperation with ej-technologies we extended the JProfiler eclipse plugin to support BND natively since 11.1.4*

Therefore bndrun files can be profiled directly from start out of eclipse with the JProfiler IDE integration which preivously only supported PDE OSGi launches.

* https://www.ej-technologies.com/download/jprofiler/changelog.html
