### ISSUE TITLE
Remote release requested while building into local Maven repository

### ISSUE THREAD

**Issue by dkorchagin** [bndtools/bnd#4179]
I have local Maven repository via Maven Bnd Repository plug-in. With older version of bndtools (4.0.0) it worked without issues. However now, after installing 5.1.1 I am getting the following error marks on every bnd.bnd in the workspace, except cnf, which is bndtools workspace, and some other project, which is not different from any other (all newly created Bnd OSGi projects immediately receive the same error mark):

Exception: java.lang.IllegalArgumentException: Remote release requested but no release repository set for Local
	at aQute.bnd.repository.maven.provider.MavenBndRepository.checkRemotePossible(MavenBndRepository.java:302)
	at aQute.bnd.repository.maven.provider.MavenBndRepository.put(MavenBndRepository.java:179)
	at aQute.bnd.build.Project.install(Project.java:1742)
	at aQute.bnd.build.Project.install(Project.java:1723)
	at aQute.bnd.build.Project.build(Project.java:1708)
	at aQute.bnd.build.Project.build(Project.java:2458)
	at org.bndtools.builder.BndtoolsBuilder.lambda$build$0(BndtoolsBuilder.java:252)
	at aQute.bnd.service.progress.TaskManager.with(TaskManager.java:37)
	at bndtools.central.Central.bndCall(Central.java:717)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:127)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Can you advise what could be the reason, as local repo is indeed local and I can't see why remote release is being requested during bundle build routine.

I am on Windows 7, and have also upgraded to Eclipse IDE for Java Developers (includes Incubating components)
Version: 2020-06 (4.16.0)
Build id: 20200615-1200
OS: Windows 7, v.6.1, x86_64 / win32
Java version: 1.8.0_101

**Comment by bjhargrave** [comment]
What is `-buildrepo` set to? This looks like Bnd is trying to put the build artifacts in the `-buildrepo` which one normally set to point to the local .m2 cache.

https://github.com/bndtools/bnd/blob/c009a67129803c9e1d264b60e1da281dbcc8a0ce/cnf/ext/repositories.bnd#L64

https://github.com/bndtools/bnd/blob/c009a67129803c9e1d264b60e1da281dbcc8a0ce/cnf/ext/repositories.bnd#L15-L17

**Comment by dkorchagin** [comment]
The -buuildrepo is set to Local, like this:
-buildrepo: Local

And it's defined like this:
-plugin.3.Local:\
       aQute.bnd.repository.maven.provider.MavenBndRepository;\
              index=local.mvn;\
              local=~/.m2/repository;\
              name=Local

Shall I put noupdateOnRelease=true ?
That doesn't look very intuitive to be honest as I am not really doing release..

**Comment by dkorchagin** [comment]
noupdateOnRelease didn't help (expected)

**Comment by bjhargrave** [comment]
> Shall I put noupdateOnRelease=true ?

Yes and get rid of `index=local.mvn`. You should probably also get rid if `local=~/.m2/repository` and just let it default (which will consult the `maven.repo.local` system property, if set).

This `Local` repo is just a reference for `-buildrepo` so that whenever Bnd builds a jar, it will place it in the local .m2 cache. Like `mvn install` does. If you don't want Bnd to put jars in the local .m2 cache when they are built, then you can remove the `-buildrepo` instruction and remove the definition of `Local`.

In Bnd, releasing is different than building. Releasing uses `-releaserepo` and expects the repo definition to have defined `snapshotUrl` and/or `releaseUrl`. This is more like `mvn deploy`.

**Comment by dkorchagin** [comment]
well, I added local=~/.m2/repository after I started to get that exception.. and yes, I used to -releaserepo and -buildrepo stuff, whereas my release repo has those URLs defined - it all worked before I upgraded to the latest 5.1.1.. Maybe it can be for that I also upgraded my Eclipse to the latest?

**Comment by dkorchagin** [comment]
Got rid of 'local' and 'index' - same stuff

**Comment by dkorchagin** [comment]
Also I don't understand why one of the projects remains Ok from this perspective.. it's just the same in terms of bndtools

**Comment by bjhargrave** [comment]
Well we use `-buildrepo` and `-releaserepo` in the Bnd project itself. And I am useing the latest Eclipse (2020-06). It all works fine for me.

What is do you have for the `-maven-release` instruction? If you have `-maven-release' with `remote`, then you are saying not to allow local releases which `-buildrepo` does.

**Comment by dkorchagin** [comment]
Uhmm.. interesting.. I have the following for my -maven-release:
-maven-release: remote;coordinates=${maven-group}:${project.name}

It did work before, and still works for one of the projects in the same workspace though..

What would you suggest to put there instead?

**Comment by bjhargrave** [comment]
I would replace it with the [`-pom` instruction](https://bnd.bndtools.org/instructions/pom.html).

```
-pom: groupid=${maven-groupid};artifactid=${project.name}
```

**Comment by bjhargrave** [comment]
Or better yet, set `-groupid` to your group id. The jar's Bundle-Symbolic name will be used for the artifact id. So you really probably only need to set `-groupid`.

https://github.com/bndtools/bnd/blob/b49f6c5252e54b43bbad40e7b4d380412ad77e8b/cnf/build.bnd#L32-L33

You may also want the `-pom` statement above to clean up your version if it uses something like a timestamp value in the Bundle-Version qualifier.

https://github.com/bndtools/bnd/blob/b49f6c5252e54b43bbad40e7b4d380412ad77e8b/cnf/build.bnd#L27

**Comment by dkorchagin** [comment]
Thanks a lot - replacing with -pom instruction fixed the issue!
