### ISSUE TITLE
BndrunContainer incorrectly assumes artifactId == osgi.identity

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4189]
During resolving with the Maven plugin a `-runrequires` is automatically calculated from the artifact id (https://github.com/bndtools/bnd/blob/3691481b9bde119f06deb3531e2c892a2d00d68c/biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java#L266). This must be the bundle symbolic name instead (https://docs.osgi.org/specification/osgi.core/7.0.0/framework.namespaces.html#i1776750)!

Otherwise you run into errors like
```
[INFO] --- bnd-resolver-maven-plugin:5.1.1:resolve (default) @ <artifact-id> ---
[INFO] Bnd inferred -runrequires: osgi.identity;filter:='(osgi.identity=<artifact-id>)'
[ERROR] Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=<artifact-id>)
```

Although this behaviour is documented at https://github.com/bndtools/bnd/tree/master/maven/bnd-resolver-maven-plugin#bndrun-details-inferred-from-maven it would be nice to improve that behaviour to evaluate the previously generated manifest instead.

**Comment by rotty3000** [comment]
Don't let `-runrequires` be calculated?

But maybe we should log a warn message to indicate that _calculation_ too place and that may not be desired?

**Comment by kwin** [comment]
Is evaluating the BSN an issue here?

**Comment by rotty3000** [comment]
I'm going to fix this up. We talked through and I think I've figured out a logical approach to make this better.
