### ISSUE TITLE
[junit-platform tester] Change output to log to stdout

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4192]
I noticed when implementing #4163 that the test output from my `TestOSGi` task is noisier than standard JUnit unit tests in Gradle, as the tester prints to stderr. 

I had the idea to have a custom `TestExecutionListener` implementation that logs the output to Gradle. May even be able to re-use (in some way) the built-in class that Gradle uses for junit-platform tests.

This would depend on #3526.

**Comment by bjhargrave** [comment]
> as the tester prints to stderr.

We should probably change the tester to print to stdout (which gradle logs at INFO) vs stderr (which gradle logs at ERROR).

**Comment by kriegfrj** [comment]
Ok, just brainstorming here - the STDOUT -> STDERR would be the easiest way to fix it.

The idea with the CI output is that it should be clean if everything runs perfectly but noisy when it doesn't, correct?

So I think it makes sense for unsuccessful or aborted tests to appear in the CI output. The test summary likewise should display in the CI output if there is anything other than 100% success (ie, if there are tests with errors, or skipped/aborted tests, the summary should display in the CI output).

I like the idea of a proper Gradle-aware `TestExecutionListener` as I think integrating with the Gradle build more directly would give longer-term benefits, but this is a medium-term proposition. If we go with your much simpler alternative in the interim, this means that we log test failures to STDERR, and the summary gets logged to STDOUT unless there are any failures in which case it gets logged to STDERR. Does this sound reasonable?

**Comment by bjhargrave** [comment]
> Ok, just brainstorming here - the STDOUT -> STDERR would be the easiest way to fix it.

We have some Gradle code in the Bnd build, which displays the test output _if_ the test fails:

https://github.com/bndtools/bnd/blob/efa79cfddedfce26962f41e81d46cf5fb5ae1632/build.gradle#L54-L82

This is to help when a test in the CI build fails. We can see the test output right then in the log. If the test succeeds, then no output.

So I think the test output should always be to STDOUT to allow the user to decide what they want. Normally one would use `--info` with gradle to see the test output. Or they can do what we do in our build to show test output only on test failure.

If the test output is sent to STDERR, then the user has no easy way to suppress the output for normal, successful test execution.

> I like the idea of a proper Gradle-aware `TestExecutionListener`

We just don't need this. Just write to STDOUT and let the user control what they see based upon using `--info` or some custom gradle script code like we use.

**Comment by kriegfrj** [comment]
> > Ok, just brainstorming here - the STDOUT -> STDERR would be the easiest way to fix it.
> 
> We have some Gradle code in the Bnd build, which displays the test output _if_ the test fails:
>
> This is to help when a test in the CI build fails. We can see the test output right then in the log. If the test succeeds, then no output.
> 
> So I think the test output should always be to STDOUT to allow the user to decide what they want. Normally one would use `--info` with gradle to see the test output. Or they can do what we do in our build to show test output only on test failure.
>

Ahh, this makes sense. I thought that it was the Gradle JUnit test task that was doing the conditional magic - I didn't realise that it was the build that conditionally displaying the output based on failure.
 
> If the test output is sent to STDERR, then the user has no easy way to suppress the output for normal, successful test execution.
> 
> > I like the idea of a proper Gradle-aware `TestExecutionListener`
> 
> We just don't need this. Just write to STDOUT and let the user control what they see based upon using `--info` or some custom gradle script code like we use.

At the moment, you are correct. But longer term, there are some plans to better and more directly integrate the test output from JUnit Platform (in particular for reporting entries) with the Gradle test task (see gradle/gradle#4605), rather than relying on captured console output. If/when that ever gets off the ground (I thought maybe it already had), re-using the same custom test listener might be useful.
