### ISSUE TITLE
Wrong baselining suggestion for newly added (static final) String fields in consumer interfaces

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4197]
If I have an interface marked as `@ConsumerType` and add there a new field the following baselining error is emitted if the package version is not adjusted

```
[INFO] --- bnd-baseline-maven-plugin:5.1.1:baseline (bnd-baseline) @ ... ---
[INFO] Determining the baseline version for ... using repositories [...]
[INFO] The baseline version was found to be <old bundle version>
[ERROR] Baseline mismatch for package <mypackage>, MINOR change. Current is 1.0.0, repo is 1.0.0, suggest 1.1.0 or -
MINOR                PACKAGE    <mypackage>
  MINOR              INTERFACE  <mypackage>.<MyConsumerInterface>
    ADDED            FIELD      NEW_FIELD
      ADDED          ACCESS     final
      ADDED          ACCESS     static
      ADDED          CONSTANT   ADDED
      ADDED          RETURN     java.lang.String
```

According to https://docs.oracle.com/javase/specs/jls/se11/html/jls-13.html#jls-13.4.8 this might break binary compatibility under certain conditions.
As it affects an interface marked as `@ConsumerType` this should suggest a major version increase (instead of a minor).

If you consider this change rather unlikely to break consumers you should instead suggest patch level increase only.

**Comment by bjhargrave** [comment]
I think this is correct in being a minor bump. Adding a (non-default) method to an interface requires all consumer implementors to change to implement a new method.

Add a new static final field to an interface does not require any consumer implemetor to change.

**Comment by kwin** [comment]
According to https://docs.oracle.com/javase/specs/jls/se11/html/jls-13.html#jls-13.4.8  consumer implementors might need to change, e.g. when the implementor has previously defined its own non-static field with the same name.

Also according to https://github.com/bndtools/bnd/tree/master/maven/bnd-baseline-maven-plugin#what-versions-should-i-use minor versions should only be increased in case
> A change which remains backward compatible for consumers but is breaking for providers necessitates a minor version change (i.e. the new version is X.Y+1.0).

I don't see this breaking any providers, as this is a consumer interface!

**Comment by bjhargrave** [comment]
The JLS link is referring to classes with instance fields. The case here is adding a static final field to an interface. A static final field on an interface cannot interfere with a non-static field on an implementing class. So there is no issue here. Static fields are not "overridden" in any case.

Adding a new static final field to an interface is a minor bump since users of the interface may want to use the new static final field and can import the new minor-bumped version to indicate their dependence on the new member.

So adding a static final field to an interface is not a major change but is a minor change. The baseline output is correct here.

**Comment by kwin** [comment]
IMHO baseline should only enforce an upgrade in case of `backward compatible for consumers but is breaking for providers`

This is not the case here. Therefore baseline should not emit an error

> Adding a new static final field to an interface is a minor bump since users of the interface may want to use the new static final field and can import the new minor-bumped version to indicate their dependence on the new member.

This is not a convincing argument for me because it
a) contradicts or at least is not explicitly stated in  https://github.com/bndtools/bnd/tree/master/maven/bnd-baseline-maven-plugin#what-versions-should-i-use
b) Only really mandatory changes should be enforced by baseline, not changes which might be useful to reference

**Comment by bjhargrave** [comment]
> IMHO baseline should only enforce an upgrade in case of `backward compatible for consumers but is breaking for providers`

This is just one case. But it is not the only case. Using a new member means the user needs to express the right import version to make sure the user is not exposed to an older type which does not include the new member. Thus the need to bump the minor version even for changes which do not break providers or consumers that don't care about the new member.

> This is not a convincing argument for me because it
> a) contradicts or at least is not explicitly stated in https://github.com/bndtools/bnd/tree/master/maven/bnd-baseline-maven-plugin#what-versions-should-i-use

That text is a "Summary": `In summary for a version X.Y.Z` and it not exhaustive or normative. The semantic versioning whitepaper is more complete.

> b) Only really mandatory changes should be enforced by baseline, not changes which might be useful to reference

This change is a mandatory change. Without making this change, users of the new member may be exposed to an older type not containing the new member and fail at runtime (NoSuchMethodError/NoSuchFieldError). A major purpose of semantic versioning is to avoid this.

**Comment by bjhargrave** [comment]
> JLS explicitly states for interface fields:
> 
> > The considerations for changing field declarations in interfaces are the same as those for static final fields in classes, as described in §13.4.8 and §13.4.9.

There is no changing a static final field here. It is _adding_ a static final field. If you were _removing_ a static final field, then that would be a major bump.

**Comment by kwin** [comment]
"changing field declarations" encompasses adding, removing and modifying

**Comment by bjhargrave** [comment]
> "changing field declarations" encompasses adding, removing and modifying

One cannot change a field in an interface. All fields in an interface are always public and static and final. In an interface, you can add a field or remove a field (renaming a field is a remove and an add).

**Comment by kwin** [comment]
> This change is a mandatory change. Without making this change, users of the new member may be exposed to an older type not containing the new member and fail at runtime (NoSuchMethodError/NoSuchFieldError)

IMHO not true as all constants are always inlined, therefore there is never a runtime dependency to constants (except if you use reflection)

**Comment by kwin** [comment]
> One cannot change a field in an interface. 
Means in this case changing the type while keeping the name!

**Comment by bjhargrave** [comment]
> IMHO not true as all constants are always inlined

Also not true. Some constants which are compile time constant can be inlined in the using class (int, String).

**Comment by bjhargrave** [comment]
I don't think we are making any progress here. I stand by the current behavior of the baseliner with respect to adding a field to an interface.

**Comment by kwin** [comment]
https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.28:

> Compile-time constant expressions of type String are always "interned" so as to share unique instances, using the method String.intern.

Therefore I would still say, micro version increase would make sense here.

**Comment by bjhargrave** [comment]
> Therefore I would still say, micro version increase would make sense here.

Micro version bump is not for changes in signature like adding a member. Adding a new member is at least a minor bump. In this case, adding a public static final field to an interface is not a major bump, just a minor bump. This is what the baseliner correctly reports.

**Comment by pkriens** [comment]
> Therefore I would still say, micro version increase would make sense here.
Nope. 

In bnd we ignore micro versions on the import range calculations, therefore, _any_ API change must at least be minor. As BJ correctly explained, if adding a static field was a micro change you potentially could get field not found errors in runtime, which is exactly the problem I wanted to prevent when creating the baseline code. 

Micro is reserved for a changes that are not affecting the API in any way, comments, licenses, implementation bug fix, etc.
