### ISSUE TITLE
Need a macro to return the vaule of a merged property

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4198]
Sometimes you want to use the value of a merged property in a macro. But all macros work on single properties. So I think we need a `merge` macro which returns a list of the values of the merged property. Then `${merge;-buildpath}` would be the complete merged buildpath and not just the value of the "stem" property.

**Comment by pkriens** [comment]
`${-buildpath.*}`

**Comment by bjhargrave** [comment]
> ${-buildpath.*}

Perfect, thanks!
