### ISSUE TITLE
Support for further test frameworks

### ISSUE THREAD

**Issue by gurkerl83** [bndtools/bnd#4213]
The bnd-process-tests goal provided in the Bnd-Maven plugin currently only supports JUnit. Other test frameworks, such as TestNG are not supported.

A developer will face a difficult to track error message when using the new bnd-process-tests goal in addition to the standard Bnd-Maven plugin and the bnd-process goal.

If the function and effect of the bnd-process-tests goal are first elaborated on a small sample project, it is clear that the JUnit framework annotation "Test" must be used at least once in a test to avoid provoking the error message listed at the end.

If the new target is not elaborated on a sample project in advance, the principles of using the target will be questioned. I can only speak from our experience in using the goal, and unfortunately, the behavior of the goal was not tested like this in advance. We have assumed that the behavior is equivalent to the standard goal and is not bound to the use of a specific testing framework.

Those who switch from using the Maven Bundle plugin to the Maven Bnd plugin will not have the primary testing framework used in a project in view when using the additional goal.

How additional test frameworks can be supported, the question arises as to how this could be done in a way that is as independent as possible. Of course, an extension of the Enums TestCase with additional frameworks would be the easiest approach. 

I may be completely wrong here, but the goal itself does not interfere with the execution control of tests; this is still reserved for other Maven plugins? Is it not possible to determine if results are being generated by upstream test execution?

Error message when no JUnit framework test annotation is used.

```
biz.aQute.bnd:bnd-maven-plugin:5.1.1:bnd-process-tests (bnd-process-tests) on project xyz: ${sort}, is not understood. too few arguments, for cmd: sort, arguments; [sort]
```

**Comment by kriegfrj** [comment]
Hi @gurkerl83 , thanks for raising this issue.

## Executive Summary:

The error message that you showed is quite cryptic - I think we could do better to more directly detect and report missing test cases. But to the main issue: while I've not directly tested it, I think that Bnd 5.0 and greater can already do what you are asking.

## Detail: 

As of Bndtools 5.0, we have the `biz.aQute.tester.junit-platform` tester bundle. This tester bundle will support running tests using any test harness that supports the JUnit Platform `TestEngine` interface. Well, at least in theory - in practice, we haven't extensively tested it other than with Jupiter (sometimes incorrectly called "JUnit 5") and Vintage (JUnit 3 & 4) engines. However, I have personally tested it with [Specsy](https://specsy.org/) and it works - the most difficult part of this was wrapping up Specsy and its dependencies to make it OSGi-friendly.

I've not personally tried to use TestNG inside of JUnit Platform, but a quick look at the JUnit 5 documentation suggests that it is possible. See these links:
* https://github.com/testng-team/testng-junit5
* https://github.com/junit-team/junit5-samples/tree/main/junit5-multiple-engines, and in particular https://github.com/junit-team/junit5-samples/tree/main/junit5-multiple-engines/src/test/java/testng

It is true that there is no direct support in the TestCases enum, but this is not a show-stopper as you can specify your own `Test-
Cases` macro directly. You would need to do the following:

1. Make sure you've included an OSGi-ified version of TestNG and Testngine in your test dependencies.
2. In your `bnd-maven-plugin` configuration:
   1. set your `testCases` setting to `useTestCasesHeader`
   2. add an instruction to the `bnd` setting that looks something like this: `Test-Cases: ${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE}`

**Comment by kriegfrj** [comment]
I got curious as I thought this would be a good way to put `biz.aQute.tester.junit-platform` through its paces... the result is here:

https://github.com/greekwelfaresa/bnd-testng-example

I managed to get it to work, as the screenshot in the README shows.

Use this example code as your base and see how you go!

**Comment by bjhargrave** [comment]
>     2. add an instruction to the `bnd` setting that looks something like this: `Test-Cases: ${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE}`

We could add this as a `testng` enum value to `TestCases`?

We may also want to update the readme to describe how to use TestNG and perhaps even add a test case to make sure we don't break the support.

**Comment by bjhargrave** [comment]
> Error message when no JUnit framework test annotation is used.
> 
> ```
> biz.aQute.bnd:bnd-maven-plugin:5.1.1:bnd-process-tests (bnd-process-tests) on project xyz: ${sort}, is
> ```

I have a fix coming to improve the situation. The fix will remove the cryptic error message and emit a warning to the log if the Test-Cases header is empty.

**Comment by kriegfrj** [comment]
> > ```
> > 2. add an instruction to the `bnd` setting that looks something like this: `Test-Cases: ${classes;HIERARCHY_ANNOTATED;org.testng.annotations.Test;CONCRETE}`
> > ```
> 
> We could add this as a `testng` enum value to `TestCases`?
> 

This is a great idea. It would be trivial to implement but its utility depends to a large degree on the next point.

> We may also want to update the readme to describe how to use TestNG and perhaps even add a test case to make sure we don't break the support.

I'd love to do this but the `testng-junit5` project doesn't seem to be very stable nor does it seem to be being actively developed. The version that is available in Maven Central doesn't have any OSGi metadata. I submitted a PR for the hack that I threw together to add OSGi (even though it's got some flaws like no version on some of the package imports), if this gets merged then this might be fruitful. But do you think it would still be useful even if it doesn't get merged and people will need my testng-junit5 hack?

I also think that the testng bundle itself could do with some more OSGi love. In my brief experience it seems that it is marking `jcommander` as optional when it really should be mandatory (without this bundle, my very simple test case threw a `NoClassDefFoundError`), so maybe the imports could do with some tweaking.

**Comment by bjhargrave** [comment]
Yes, we do need the testng engine to be stable and have OSGi metadata before we can add a test case. I don't want to add tests which depend on flaky dependencies.

But we can add an enum value to TestCases.

**Comment by kriegfrj** [comment]
> Yes, we do need the testng engine to be stable and have OSGi metadata before we can add a test case. I don't want to add tests which depend on flaky dependencies.
> 
> But we can add an enum value to TestCases.

We can, but I'm not sure how useful it will be without a stable `testng-junit5` project. I guess we can include the enum value with the caveat that support for TestNG is in a beta state.

**Comment by bjhargrave** [comment]
I will add the enum value.
