### ISSUE TITLE
bnd-maven-plugin: Allow to set service.vendor globally

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4217]
Currently the `service.vendor` needs to be defined per service (https://docs.osgi.org/specification/osgi.core/7.0.0/framework.service.html#framework.service.serviceproperties). As often all services within a bundle come from the same vendor it would be good to allow to set the `service.vendor` globally (via bnd instruction or some plugin configuration).

**Comment by bjhargrave** [comment]
This is probably best done by you defining a component property type and applying it to all your components. This was you can set all the standard service properties you want for your component in one type.

**Comment by kwin** [comment]
Fair enough, I guess this is a reasonable answer. Closing issue therefore.
