### ISSUE TITLE
NPE on Resolve job cancel 

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4235]
@scottslewis  reported: 
So...when I hit resolve with this bndrun...without one of the requirements:
![screen1](https://user-images.githubusercontent.com/8199490/88263489-6947e180-ccca-11ea-97e8-764b18be9c7b.jpg)
after just a second or so I get:
![screen2](https://user-images.githubusercontent.com/8199490/88263517-71a01c80-ccca-11ea-8932-7a02e8818052.jpg)

Which is fine.

If, however I add one more requirement (org.eclipse.ecf.provider.jersey) in this bndrun, and save it...
![screen3](https://user-images.githubusercontent.com/8199490/88263537-7bc21b00-ccca-11ea-8074-c4d7adc222d4.jpg)

*then* hit Resolve  I get  the above...i.e. the 'Resolving health.examples.grpc.server.bndrun' never completes on it's own.

If I hit the stop button on the right of the Progress view I get:
![screen4](https://user-images.githubusercontent.com/8199490/88263554-82509280-ccca-11ea-9f39-30bf76f96cbf.jpg)

and there is nothing in the Errors view that indicates what went wrong...or any info about the NPE or previous hang in the workspace log.

What I would have expected:  Rather than having me cancel via the progress view (which may not be present)...is that a progress monitor dialog would appear after hitting Resolve...and that I could cancel the resolve from this progress monitor dialog.   A progress monitor dialog is common in Eclipse for cancellable long-running operations.

On hang+cancellation, I would expect something other than the Problem Occurred/NPE dialog as above...i.e. something that allows me to access the resolve log (or something that allows me to determine or at least investigate why the resolver was not completing).

Currently using this version of bndtools: 
![screen5](https://user-images.githubusercontent.com/8199490/88263569-88467380-ccca-11ea-8eed-cf5349b156b6.jpg)

If I can test or help please let me know.   If you desire I can give you steps to run this example (from the ECF remote services bndworkspace here:

https://github.com/ECF/bndtools.workspace

Thanksinadvance,

Scott

**Comment by juergen-albert** [comment]
@bjhargrave can you assign it to me?

**Comment by juergen-albert** [comment]
@scottslewis can you provide the steps to reproduce it, because my test setup works without an NPE.

**Comment by scottslewis** [comment]
1) Create new bndtools workspace with this workspace template:

https://github.com/ECF/bndtools.workspace

see instructions in readme.md-linked tutorial to setup workspace template in bndtools preferences.

2) Create new project named 'hello.api' using the 'JaxRS Remote Service Hello API Project' template.

3) Create new project named 'hello.impl' using the 'JaxRS Remote Services Hello Impl Project' template

4) In the new hello.impl project will be a bndrun file named hello.impl.zeroconf.jersey.bndrun.  Open it.

5) Click Resolve with existing Run Requirements and this Resolve will succeed/complete

6) Add this bundle to run requirements:   org.eclipse.ecf.provider.jersey.server and save the updated bndrun.

7) Resolve again.  This should hang/not complete

8) Open progress view and cancel resolve job.  This should result in Problem Occurred dialog and NPE under Details button:  

![image](https://user-images.githubusercontent.com/159988/88339179-71197d00-ccee-11ea-9d1e-2bd6b36c744e.png)
