### ISSUE TITLE
Refresh Snaphshots in MavenRepositories

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4236]
Snapshots currently have a timeout of an hour. This is fine, but it would be better if a refresh of the repositories would force the files to be re-fetched regardless of timeout.

**Comment by bjhargrave** [comment]
We would then need to make sure that we don't call refresh on repositories without the user requesting it. I think there are a number of places in the code we call refresh for no valid reason.

**Comment by kriegfrj** [comment]
> We would then need to make sure that we don't call refresh on repositories without the user requesting it. I think there are a number of places in the code we call refresh for no valid reason.

Perhaps this comes back to the old discussion we had on soft vs hard refresh.
