### ISSUE TITLE
bnd-baseline-maven-plugin filter out Mx, RCx, etc

### ISSUE THREAD

**Issue by Emily-Jiang** [bndtools/bnd#4240]
I would like to compare my bundle against the last final release, which means RCx, Mx should not be used as the baseline.
@bjhargrave thoughts?

**Comment by bjhargrave** [comment]
By default, bnd-baseline-maven-plugin which try to find the prior version from the repos:

https://github.com/bndtools/bnd/blob/2df1dbc42be6e5c389b666f0152f385b0afe4d0f/maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java#L198-L201

This uses normal [maven version ordering (which is rather complex and strange)](https://maven.apache.org/ref/3.6.3/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ComparableVersion.html) via the Aether repositories to find versions and then selects the highest non-snapshot version.

https://github.com/bndtools/bnd/blob/2df1dbc42be6e5c389b666f0152f385b0afe4d0f/maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java#L206-L231

bnd-baseline-maven-plugin itself does not know anything about maven versions, their ordering or what Mx or RCx mean. If you want to baseline against a different version that Aether computes as the prior version, then you can configure that into the plugin configuration. For example:

```xml
<configuration>
    <base>
        <version>1.0.0.RC1</version>
    </base>
</configuration>
```

**Comment by Emily-Jiang** [comment]
@bjhargrave I have been using the following to specify baseline for some of MicroProfile specs. 
```
<configuration>
    <base>
        <version>1.0.0.RC1</version>
    </base>
</configuration>
```
As you know the projects are growing and it is hard to sync up with the latest released version. I am wondering in your for loop, you can skip the versions ending with RCx, Mx, etc.

**Comment by bjhargrave** [comment]
>  I am wondering in your for loop, you can skip the versions ending with RCx, Mx, etc. 
> I guess you can introduce a property say bnd.skip.nonfinalrelease=true.

There are many other well known qualifiers too:

```
strings are checked for well-known qualifiers and the qualifier ordering is used for version ordering. Well-known qualifiers (case insensitive) are:

    alpha or a
    beta or b
    milestone or m
    rc or cr
    snapshot
    (the empty string) or ga or final
    sp

Unknown qualifiers are considered after known qualifiers, with lexical order (always case insensitive), 
```

So which of all these qualifiers (besides SNAPSHOT) should be skipped for baselining? All of them before `(the empty string) or ga or final`? (There are so many complications and aliases, that this code would be quite complex I think.)

What about `Unknown qualifiers are considered after known qualifiers`? Should they be skipped for baselining?

Thoughts @rotty3000?

**Comment by bjhargrave** [comment]
>  I am wondering in your for loop, you can skip the versions ending with RCx, Mx, etc. 
> I guess you can introduce a property say bnd.skip.nonfinalrelease=true.

There are many other well known qualifiers too:

```
strings are checked for well-known qualifiers and the qualifier ordering is used for version ordering. Well-known qualifiers (case insensitive) are:

    alpha or a
    beta or b
    milestone or m
    rc or cr
    snapshot
    (the empty string) or ga or final
    sp

Unknown qualifiers are considered after known qualifiers, with lexical order (always case insensitive), 
```

So which of all these qualifiers (besides SNAPSHOT) should be skipped for baselining? All of them before `(the empty string) or ga or final`? (There are so many complications and aliases, that this code would be quite complex I think.)

What about `Unknown qualifiers are considered after known qualifiers`? Should they be skipped for baselining?

Thoughts @rotty3000?

**Comment by rotty3000** [comment]
I haven't looked closely at the logic, but could we add a flag to the baseline plugin to ignore well known qualifiers instead? I imagine this still means complex logic to filter them out?

**Comment by bjhargrave** [comment]
> I imagine this still means complex logic to filter them out?

Yes, I think so. We would also need to make sure we can use the same code for the Gradle baseline plugin.
