### ISSUE TITLE
Java packages appeared in 'Import-Package' header

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#4242]
After the update to the latest snapshot version of bndtools, I noticed the following where all Java packages appeared in the bundle manifest's `Import-Package` header.

<img width="435" alt="Bildschirmfoto 2020-07-31 um 12 46 50" src="https://user-images.githubusercontent.com/13380182/89028228-3a65e700-d32c-11ea-9966-352a0d7438f2.png">
<img width="428" alt="Bildschirmfoto 2020-07-31 um 12 46 33" src="https://user-images.githubusercontent.com/13380182/89028223-376af680-d32c-11ea-9ca1-307d438b5f0f.png">

I am currently using `5.2.0.DEV-202007302128-gd538548` version

**Comment by bjhargrave** [comment]
Good! That means #4241 is working.

See https://bnd.bndtools.org/instructions/noimportjava.html for more information and how to disable this if you need to.

**Comment by pkriens** [comment]
From #4241 

> Yes, it was discussed at length in #2507. I went with the consensus decision from that discussion albeit with some tweaks.
> This is in some way parallel to when we automatically added osgi.ee requirements with the -noee instruction to opt-out.
> If we want to tweak how and when we want to import java.* packages, we should probably open a new issue to discuss. This PR is already merged.

I had not noticed that we now import java. Was it discussed to so drastically change the default? In my case we compare bundles against a previous release and only update when needed. This is creating a massive change. I think the default should be as it always ways and then an opt-in.

Lets discuss this in the next bnd meeting

**Comment by bjhargrave** [comment]
After discussion in the Bndtools call, the maintainers agreed to leave things are they are in PR #4241.
