### ISSUE TITLE
Improve support for Factory Component capabilities

### ISSUE THREAD

**Issue by rovarga** [bndtools/bnd#4243]
As discussed in https://issues.apache.org/jira/browse/KARAF-6625, current default setup of Karaf/maven-bundle-plugin/bnd does not really work for factory components and their users, as per https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#d0e39673.
The primary problem is that bnd generates a 
``Require-Capability: osgi.service;filter:="(objectClass=org.osgi.service.component.ComponentFactory)";effective:=active``
for which no corresponding Provide-Capability is present.

As discussed in the Karaf issue, the Require/Provide here can be improved by taking into account @Component.factory and @Reference.filter attributes to improve the accuracy of both capabilities.

While it is challenging to provide the correct  require/provides pairing in the general case, if the user takes sufficient care, as shown in [the use case](https://issues.apache.org/jira/browse/KARAF-6625?focusedCommentId=17169195&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17169195), the filter constants should be folded at compile-time, allowing properly-filtered require/provides capabilities to be generated.

**Comment by rovarga** [comment]
The typical use case for factory components is really a simple one: we provide a seamless bridge between Service Registry and Declarative Services, while maintaining Requires/Provide safeties. We are using Factory Components, whose configurations are activated based on various circumstances -- the typical being ServiceTracker.
While it may sound unreasonable, it is a migration step from being completely free-for-all services to being component (and require/provide) driven. We just cannot take the leap in one bound, but need clever hacks like https://github.com/opendaylight/mdsal/blob/master/binding/mdsal-binding-dom-adapter/src/main/java/org/opendaylight/mdsal/binding/dom/adapter/osgi/DynamicBindingAdapter.java to provide a seamless integration experience.

**Comment by djencks** [comment]
Using factory components tends to mix up configuration and runtime aspects.  I would consider if you can replace your use of factory components with factory configurations: whatever is currently creating components through the factory component could perhaps instead be adding factory configurations to config admin, and the factory component could turn into a normal component.  I found this approach much simpler and more reliable.  The only reason I can think of not using this strategy is if you actually need to get the instance directly as soon as you create it.  However, this issue may still be worth pursuing.

**Comment by rovarga** [comment]
To qualify that a bit more. The system we are migrating from relied on Service Registry and ServiceTrackers to tie components together. It is obvious that has been a mistake and migrating to proper components is the way to go. Nevertheless we cannot do that atomically.
Factory Components provide an escape hatch, where we still have components, but their instantiation is subject to undisclosed logic -- for example ServiceTracker. Using this intermediate step, we can gradually migrate our SR-based dependencies to component dependencies and let actual implementations' behaviour bridge the gap.
As this migration progresses, we will turn from Factory Components to Immediate Components and then towards delayed components.

**Comment by rovarga** [comment]
As another consideration, the migration path involves switching from Blueprint to DS. It is mostly the blueprint part, which has primary interactions with SR using an ill-conceived model, which is causing most of headaches. Factory Components, their configurations and their activations is used mostly to simulate Blueprint's interaction with Service Registry, so that we can gradually eliminate blueprint use without downstream users having to change.

**Comment by rovarga** [comment]
At the end of the day, we will eliminate most, but not all Factory Components. The reason for that is that some of our components take a *very* long time to initialize and hence we opt to using background tasks leading to creation of component configurations. This is in contrast to using single-threaded long-lived @Activate methods.

**Comment by rovarga** [comment]
A typical async/component bridge is here:
https://git.opendaylight.org/gerrit/c/controller/+/91795/6/opendaylight/md-sal/sal-distributed-datastore/src/main/java/org/opendaylight/controller/cluster/datastore/OSGiDOMStore.java
It is completely non-blocking after https://git.opendaylight.org/gerrit/c/controller/+/91795/6/opendaylight/md-sal/sal-distributed-datastore/src/main/java/org/opendaylight/controller/cluster/datastore/OSGiDistributedDataStore.java (which is a distributed thing) finishes.

**Comment by rovarga** [comment]
All of this complexity could be eliminated if @Activate/@Deactivate methods were allowed to be asynchronous (e.g. by returning a Promise), but this is not where R7 spec is -- and therefore we need some sort of a bridge. Factory components seem to be the only (sane?) mechanism to do so.

**Comment by rotty3000** [comment]
I think this is a reasonable suggestion, particularly given that DS R7 added [`factoryProperty` element](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-factoryproperty.factoryproperties.elements) which enhanced Factory Components with factory properties to increase their usability. Since it seems that Factory Components are receiving enhancements (small as they may be) it stands to reason that bnd grant them some love as well. Adding _at least_ the cap/req seems to be a fairly simple to implement improvement (though it would be proprietary to bnd at least for the time being; we could add a flag to enable such generation.)

I've been bitten by this lack of Factory Component req/cap a few times in the past so I have ulterior motives to entertain such an improvement as well ;)

@rovarga would you be up for providing a PR?

**Comment by rovarga** [comment]
@rotty3000 unfortunately not anytime soon, as I am not familiar with the codebase and currently do not have the cycles :(

**Comment by bjhargrave** [comment]
I am unclear on what is being asked for here. On the service consuming side, the example code looks like:

```java
@Reference(target = "(component.factory=" + OSGiDOMStore.FACTORY_NAME + ")")
ComponentFactory datastoreFactory = null;
```

With this, Bnd can see that there is a reference to a `ComponentFactory` service. But Bnd has know way to know what the `component.factory` property value is (the reference `target` property value can be an arbitrarily complex filter expression), or will be, since the actual value of the reference `target` property value can come from Configuration properties. (Note: while the `component.factory`property value cannot be overridden by a Configuration on the service providing side; on the service consuming side, the `component.factory` value is actually part of the reference `target` property value which _can_ be overridden by a Configuration.)

On the service providing side, things are a little easier:

```java
@Component(factory = OSGiDOMStore.FACTORY_NAME)
```

Bnd can see the `factory` element and can know the factory name (since the factory name cannot be overridden by Configuration). So Bnd can easily generate a valid `osgi.service` capability for `ComponentFactory` and the specified `component.factory` property value.

But without being able to properly generate a valid `osgi.service` requirement for the `ComponentFactory` service, since we can't know the `component.factory` property value, Bnd is probably better off not generating any `osgi.service` requirement for `ComponentFactory` references.

**Comment by bjhargrave** [comment]
> All of this complexity could be eliminated if @Activate/@deactivate methods were allowed to be asynchronous (e.g. by returning a Promise)

I am not sure how these methods can be async. The activate method is basically a post-construct method which much complete execution before the component instance can be considered "ready" for work. The deactivate is a deconstruct method and SCR must discard the component instance after completion.

**Comment by bjhargrave** [comment]
> Bnd is probably better off not generating any `osgi.service` requirement for `ComponentFactory` references.

I suspect the best response to this issue is to teach Bnd to stop generating `osgi.service` requirements for `ComponentFactory` references.

**Comment by rovarga** [comment]
> > Bnd is probably better off not generating any `osgi.service` requirement for `ComponentFactory` references.
> 
> I suspect the best response to this issue is to teach Bnd to stop generating `osgi.service` requirements for `ComponentFactory` references.

Yes, this certainly one way of solving the problem. It is not the best way of doing that, though.

**Comment by rovarga** [comment]
> I am unclear on what is being asked for here. On the service consuming side, the example code looks like:

I am asking for as-good-as-reasonable support on Provides side of things as on Requires side of things. Currently there is a huge mismatch. As I just noted on your other comment, we can solve this by neutering Requires side -- but I do believe we can do much better with low-to-moderate effort.

> 
> ```java
> @Reference(target = "(component.factory=" + OSGiDOMStore.FACTORY_NAME + ")")
> ComponentFactory datastoreFactory = null;
> ```
> 
> With this, Bnd can see that there is a reference to a `ComponentFactory` service. But Bnd has know way to know what the `component.factory` property value is (the reference `target` property value can be an arbitrarily complex filter expression), or will be, since the actual value of the reference `target` property value can come from Configuration properties. (Note: while the `component.factory`property value cannot be overridden by a Configuration on the service providing side; on the service consuming side, the `component.factory` value is actually part of the reference `target` property value which _can_ be overridden by a Configuration.)
> 

Agreed. I am not looking for a solution to a general case, just for a very controlled case. In that case the expression is a *compile*-time constant, as confirmed by examining javac-11 bytecode. In that case, the bytecode constant we are matching is "(component.factory=org.opendaylight.controller.cluster.datastore.OSGiDOMStore)". The Provides side of the equation has enough knowledge to satisfy this:
(javap excerpts)

RuntimeInvisibleAnnotations:
  0: #99()
  1: #100(#101=s#102,#103=[c#104,c#105])

   #99 = Utf8               Lcom/google/common/annotations/Beta;
  #100 = Utf8               Lorg/osgi/service/component/annotations/Component;
  #101 = Utf8               factory
  #102 = Utf8               org.opendaylight.controller.cluster.datastore.OSGiDOMStore
  #103 = Utf8               service
  #104 = Utf8               Lorg/opendaylight/mdsal/dom/spi/store/DOMStore;
  #105 = Utf8               Lorg/opendaylight/controller/cluster/datastore/DistributedDataStoreInterface;

i.e. we should have just enough compile-time information to make this work. Note I am not asking for crazy runtime things -- just what can be inferrred at annotation processor time.

I would not dream to ask for anything beyond  what is observable by annotation processors. Yes, you can write wild requirements. No, we do not (yet) support them. Yes, your can contribute path.

That spiriti'n'all. Yes, I with push a PR once I have the cycles, no, that ain't happening anytime soon.

 Pretty please (from a fellow FOSS downstrem) ? :)

> On the service providing side, things are a little easier:
> 
> ```java
> @Component(factory = OSGiDOMStore.FACTORY_NAME)
> ```
> 
> Bnd can see the `factory` element and can know the factory name (since the factory name cannot be overridden by Configuration). So Bnd can easily generate a valid `osgi.service` capability for `ComponentFactory` and the specified `component.factory` property value.
> 
> But without being able to properly generate a valid `osgi.service` requirement for the `ComponentFactory` service, since we can't know the `component.factory` property value, Bnd is probably better off not generating any `osgi.service` requirement for `ComponentFactory` references.

Agreed, but we do not generated any Provides-side at all, so generating *anything* is a step in the right direction. In this particular case, what we observe at annotation processor step is (again, javap output):

SourceFile: "OSGiDOMStore.java"
RuntimeInvisibleAnnotations:
  0: #99()
  1: #100(#101=s#102,#103=[c#104,c#105])

and:
SourceFile: "OSGiDOMStore.java"
RuntimeInvisibleAnnotations:
  0: #99()
  1: #100(#101=s#102,#103=[c#104,c#105])

and:

  #99 = Utf8               Lcom/google/common/annotations/Beta;
  #100 = Utf8               Lorg/osgi/service/component/annotations/Component;
  #101 = Utf8               factory
  #102 = Utf8               org.opendaylight.controller.cluster.datastore.OSGiDOMStore
  #103 = Utf8               service
  #104 = Utf8               Lorg/opendaylight/mdsal/dom/spi/store/DOMStore;
  #105 = Utf8               Lorg/opendaylight/controller/cluster/datastore/DistributedDataStoreInterface;

i.e. this should be triival to do the right thing at compile-time.

**Comment by rovarga** [comment]
At the end of the day:

Yes, this is potentially runtime-complex But most of the well-formed cases end up being compile-time constants and we do not cover them.

Solving a constraint compile-time-invariant will go a long way towards usability. We do not need to boil the ocean, just make the *very obvious* complile-time-safe case to work.

That case is *utterly* broken now due to Provide-side of things being *completely* absent (hence the alternative solution or not generating Requires).

**Comment by rovarga** [comment]
To sum this up: this issue is about being a bit more smart on requires side and at least as smart on provides side.

My benchmark is utterly low-hanging fruit. I am convinced 99.99% of users of these facilities will be fine with this issue solved. It is completely fair to leave the runtime-level-complexity for another day -- i.e. not in scope of this issue.

I strongly believe a user for runtime-level-complexity will not surface sooner than 2 years after this issue is fixed.

**Comment by bjhargrave** [comment]
So I think what I could do is teach Bnd to

1. emit an `osgi.service` capability for `ComponentFactory` service with the `component.factory` property for factory components.
2. emit an `osgi.service` requirement for `ComponentFactory` service _only if_ the `@Reference` `target` element specifies a filter expression. The specified filter expression will be and-ed into the filter expression of the `osgi.service` requirement like:  `filter:="(&(objectClass=org.osgi.service.component.ComponentFactory)(target))"`. If the `@Reference` `target` element is not specified,  a `@Reference` for a `ComponentFactory` service will not emit an `osgi.service` requirement .

This will work for the simple case and will not result in emitting a plain `osgi.service` requirement for `ComponentFactory` service.

**Comment by rotty3000** [comment]
@bjhargrave I like it! Thank you for your flexibility on this issue.
