### ISSUE TITLE
[bnd] Dependency post-processing pipeline

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4246]
Just an idea I'd like to float, based on a few disparate issues that I have come across that all have something in common.

Very often, there are dependencies in third-party repositories that are almost usable as they are, but which we'd like to tweak. Some examples:

* Embedding source
* Possibly flattening `Bundle-ClassPath` (see #4051).
* Generating OSGi metadata for dependencies that don't have any (similar to #2422).
* A variant on the previous: Augmenting/fixing up the bundle's OSGi metadata (#4245)

At the moment, embedding source is handled in an ad-hoc way by some repo implementations (specifically, MavenBndRepository). It would be nice if this were more uniform.

For others, the only solution currently is to create a project in your local workspace with bnd instructions to create a version of the bundle that you'd like to use. You then also have to manage the fact that you have two overlapping dependencies in your workspace (the original dependency and your mutated version).

[p2-maven-plugin](https://github.com/reficio/p2-maven-plugin) has a feature where it runs all of the dependencies through Bnd. If the jars already have OSGi metadata they are left untouched, otherwise a set of default instructions are applied to wrap them into bundles. Specific instruction overrides can be given for individual artifacts to customise the results.

A similar issue has been raised before (#2422), but was stalled at the time. Perhaps we are now in a better position to re-consider this? Something like:
```
-repopostprocess: \
  my.artifact.reference;bnd="path/to/my-postprocessor.bnd",\
  *;bnd="path/to/default-postprocessor.bnd"
```
Thoughts?

**Comment by rotty3000** [comment]
See https://github.com/bndtools/bnd/issues/4245#issuecomment-668049488
