### ISSUE TITLE
[maven] bnd-resolver-maven-plugin dies on pom-packaged artifact

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4262]
I note that the bnd-maven-plugin will skip execution if it is executed on an artifact of packaging type=pom:

https://github.com/bndtools/bnd/blob/7d2fe47ac7bfa88367d60ede6ae79514c17f0723/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java#L153-L158

This allows you to configure the plugin in a parent pom.

Is there a good reason why other bnd-maven plugins don't also have this feature? For example, I've discovered that bnd-resolver-maven-plugin will die if executed on a pom-packaged artifact.

**Comment by rotty3000** [comment]
Can you give an example of this? I'm fairly certain that I've created pom packaging projects with the bnd-resolver-maven-plugin.

**Comment by kriegfrj** [comment]
This happened with osgi-test when i was trying to implement the integration testing. I'll try and push an example tomorrow.

**Comment by rotty3000** [comment]
Any reproducer for this? The only place I think this might possibly happen is when letting `-runee` be inferred?

**Comment by rotty3000** [comment]
Actually, all our test cases for the bnd-resolver-maven-plugin use pom packaging. So I'm going to close this based on the fact that we don't have a specific error reported or steps to reproduce but plenty of proof that it works as designed.

**Comment by kriegfrj** [comment]
Apologies for the delay - this slipped off my radar.

Forgive me, it was not the resolver plugin where I was having this issue, but the testing plugin. Here is a reproducer: https://github.com/kriegfrj/osgi-test/tree/pom-packaging This differs from `main` only in the root `pom.xml`.

Here is the relevant snippet from the output of `./mvnw -pl org.osgi:org.osgi.test.parent verify`:

```
[INFO] --- bnd-maven-plugin:5.1.2:bnd-process (bnd-process) @ org.osgi.test.parent ---
[INFO] skip project with packaging=pom
[INFO]
[INFO] --- bnd-resolver-maven-plugin:5.1.2:resolve (resolve-test) @ org.osgi.test.parent ---
[ERROR] Could not find bnd run file C:\workspace\osgi-test\test.bndrun
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```
* The `bnd-maven-plugin` is skipped with an explanation. This is nice.
* The `bnd-resolver-maven-plugin` dies on the missing file `test.bndrun`.

I wanted to configure it this way when I implemented https://github.com/osgi/osgi-test/pull/178 because all of the subprojects were configured in the same way for the integration tests. But it tripped on this hurdle, so I had to duplicate the information through all of the subprojects.

**Comment by rotty3000** [comment]
Use `<pluginManagement>` to define plugins globally. Do NOT apply plugins globally.

**Comment by kriegfrj** [comment]
> Why would you enable the plugin for parent? that makes no sense.

The parent is the place where you are supposed to define all of the settings that are common to all of the child projects. When I enabled integration testing on all submodules, it became the case that the integration testing configuration was largely common to all submodules. In this case, it makes sense to define the integration plugins in the parent pom.

> Use <pluginManagement> to define plugins globally. Do NOT apply plugins globally.

`<pluginManagement>` is especially useful when you have a plugin that you want to use in some, but not all sub-modules. But when you know you want to use it in all sub-modules, it makes sense to also add it directly in `<plugins>` so that you don't have to add it manually to all of the sub-modules. 

From what I've seen it's quite common to put the plugin definition in the parent pom so that you don't have to re-enumerate all of the plugins in each of the child poms. There were already more than half-a-dozen plugins defined in the `<plugins>` section of the root pom of osgi-test before osgi/osgi-test#178 (including `bnd-baseline-maven-plugin`!). 

> It would be better to discuss this as a usage question rather then as a bug.

Forgive me - I'm fine with that. I didn't call it bug to begin with! I noted that there was an inconsistency here between the plugins - some of them (eg, `bnd-maven-plugin` and `bnd-baseline-maven-plugin`) will gracefully handle being defined on a POM-packaged artifact, others (`bnd-testing-maven-plugin`, `bnd-resolver-maven-plugin`) do not. The issue I raised was querying why that is - if there's a technical reason for it, or if it's simply that no one has gotten around to adding the two lines of code to the other plugins that would allow them to graciously abort if it notices it is being invoked on a pom-packaged artifact.

**Comment by bjhargrave** [comment]
> Use `<pluginManagement>` to define plugins globally. Do NOT apply plugins globally.

This argument would then question why some of the bnd maven plugin have an early exit for pom packaging but some don't. Shouldn't we be be consistent?

**Comment by rotty3000** [comment]
I disagree with setting the bnd-testing-plugin globally in any project. But if someone is willing to make that work then by all means.

**Comment by bjhargrave** [comment]
So in looking at the Bnd tests for the maven plugins, we actually have tests which resolve in pom packaging projects. So I think we need to continue to support using these plugin on pom packaging projects. Such projects don't build an artifact but may resolve or test artifacts build by earlier projects.

The issue in the https://github.com/kriegfrj/osgi-test/tree/pom-packaging is that you explicitly name a bndrun file which does not exist in the parent pom's enabled execution. I have updated the osgi-test project, https://github.com/osgi/osgi-test/commit/6572117d33ca4ee529cba9f6aabfe0558ca7fe43, to configure the bnd maven plugins in the parent pom using `pluginManagement` to set the base configuration for each plugin and
`plugins` to enable the plugin. It uses `executions` in `plugins` which are not inherited by child projects to skip the bnd maven plugins on the parent project.

For example:

```xml
<plugin>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>bnd-resolver-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>resolve-test</id>
			<phase>pre-integration-test</phase>
			<goals>
				<goal>resolve</goal>
			</goals>
			<inherited>false</inherited>
			<configuration>
				<skip>true</skip>
			</configuration>
		</execution>
	</executions>
</plugin>
```

The child projects inherit the use of the plugin but not the execution which disables the plugin in the parent pom. The child projects get the executions and configuration of the plugin from pluginManagement.

So with this strategy, one can configure and enable the bnd maven plugins in the parent pom for all child projects but not the parent project.

Thus no further changes to ignore pom packaging should be made.

**Comment by kriegfrj** [comment]
> So in looking at the Bnd tests for the maven plugins, we actually have tests which resolve in pom packaging projects. So I think we need to continue to support using these plugin on pom packaging projects. Such projects don't build an artifact but may resolve or test artifacts build by earlier projects.
>
> .. 
>
> Thus no further changes to ignore pom packaging should be made.

This makes sense... the testing and resolver plugins don't have to work directly on a jar artifact so there's no need to constrain them to run only on a jar-packaged project. This explains the different behavior.  Mystery solved, thanks BJ!
