### ISSUE TITLE
Compiling old release for Eclipse as plugin

### ISSUE THREAD

**Issue by genesisxyz** [bndtools/bnd#4265]
Hello, I am trying to compile a old release ([3.4.0](https://github.com/bndtools/bnd/releases/tag/3.4.0.REL))

I modified `settings.gradle` to point to `bndtools.jfrog.io`:

    /*
     * Master Gradle initialization script
     */
    /* Add bnd gradle plugin as a script dependency */
    buildscript {
      repositories {
        maven {
          url uri('https://bndtools.jfrog.io/bndtools/libs-snapshot')
        }
      }
      dependencies {
        classpath 'biz.aQute.bnd:biz.aQute.bnd.gradle:3.4.0'
      }
      /* Since the files in the repository change with each build, we need to recheck for changes */
      configurations.classpath {
        resolutionStrategy {
          cacheChangingModulesFor 30, 'minutes'
          cacheDynamicVersionsFor 30, 'minutes'
        }
      }
      dependencies {
        components {
          all { ComponentMetadataDetails details ->
            details.changing = true
          }
        }
      }
      /* Add bnd gradle plugin to buildscript classpath of rootProject */
      def bndPlugin = files(configurations.classpath.files)
      gradle.projectsLoaded { gradle ->
        gradle.rootProject.buildscript {
          dependencies {
            classpath bndPlugin
          }
        }
      }
    }
    apply plugin: 'biz.aQute.bnd.workspace'

I ran `./gradlew :dist:index` to generate the release on `dist/bundles`

I also followed this guide ([Bndtools Developer Guide](https://bndtools.org/development.html)) but the generated folder is empty

How can I install a older version of BndTools on Eclipse as plugin? Because on the Marketplace I can only see the latest version

I am trying to setup this project ([PowerMatcher](https://github.com/flexiblepower/PowerMatcher)) and it requires a older version of BndTools (older than v4.0.0 because it uses annotations that are missing on newer versions)

Thanks in advance for any help

**Comment by bjhargrave** [comment]
You can install Bndtools 3.4.0 from https://dl.bintray.com/bndtools/bndtools/3.4.0/. Update sites for versions 2.2.2 through 4.3.1 of Bndtools are available from the old update site: https://dl.bintray.com/bndtools/bndtools/. 

The current update site, https://bndtools.jfrog.io/bndtools/update-latest/, has all versions of Bndtools from 4.2.0 to the latest version. To see versions other than the current version, you will need to select the option to show older versions.

<img width="940" alt="Screen Shot 2020-08-13 at 09 45 41" src="https://user-images.githubusercontent.com/277682/90142049-e73b5d80-dd49-11ea-9471-40c72dd095c7.png">


If you really need to build an older version from source code, you will need to point to maven central for the Bnd Gradle plugin version you need.
