### ISSUE TITLE
OSGi with Gradle but without Eclipse?

### ISSUE THREAD

**Issue by chrisr3** [bndtools/bnd#4282]
Hi,

I am investigating using OSGi to resolve a deep-seated packaging and modularisation issue that we have. Our established tool-chain is Gradle + IntelliJ, and I seriously don't see anyone replacing IntelliJ for Eclipse any time soon. We also have a heavy investment in our `build.gradle` files, and I doubt these will be going away either.

In practice, this seems to imply that we would want to build our OSGi bundles using
```gradle
plugins {
    id 'biz.aQute.bnd.builder'
}
```
I recognise the output of this Builder plugin as being "Gradle-like" (i.e. it _at least_ generates its output into Gradle's standard `build` directory!) whereas the `Workspace` plugin seems to be playing a different game entirely.

However, while I have(?) managed to _generate_ a provider bundle which imports a simple API bundle, I am drawing a blank on _testing_ this from within Gradle. All of the documentation I have read is just showing me Eclipse rather than teaching me about OSGi itself. I've seen examples using something called `Launcher`, but these use JUnit 4 and we'd like to use JUnit 5.

Are there any examples or _anything_ which focus on _OSGi_ rather than Eclipse please?

**Comment by bjhargrave** [comment]
Are you reporting a problem with Bnd? Usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.

**Comment by chrisr3** [comment]
Well, I _am_ thinking that the lack of Bnd documentation which doesn't expect me to be using Eclipse is an "issue". YMMV.

**Comment by rotty3000** [comment]
I think you might be looking for this :) https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle#create-a-task-of-the-testosgi-type

**Comment by bjhargrave** [comment]
There is nothing about the Bnd Gradle plugins which require the use of Eclipse. The Bnd Gradle plugins support Bnd Workspace model builds and non-Workspace model builds like the traditional Gradle build structure. But neither require you to use Eclipse. Bnd also has Maven plugins which also don't require you to use Eclipse.

**Comment by chrisr3** [comment]
> I think you might be looking for this :) https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle#create-a-task-of-the-testosgi-type

I _did_ see that, but was then unable to "find" this:
```
bndrun 'my.bndrun'
```

**Comment by bjhargrave** [comment]
> Well, I _am_ thinking that the lack of Bnd documentation

But we would welcome documentation improvement pull requests!

**Comment by rotty3000** [comment]
let's take this to the list and we can start you on the right path :)

**Comment by bjhargrave** [comment]
> let's take this to the list and we can start you on the right path

Yes!

**Comment by chrisr3** [comment]
> > Well, I _am_ thinking that the lack of Bnd documentation
> But we would welcome documentation improvement pull requests!

Should I point out the logical absurdity of saying that to _me_...? :exploding_head:

**Comment by rotty3000** [comment]
I'd like to try to defuse the tension that seems to have already built up here. Can we start over on the list?

I just want to add that my company uses bnd in gradle without workspace with hundreds of developers using Intellij. So that's totally doable. Mind you we have our own testing strategy but that's only because we've had it before bnd had it's own OSGiTest gradle plugin.

However, all the bnd gradle parts are in place to do this without any need to be tied to Eclipse. I think what @bjhargrave was trying to put across was that perhaps we are a little light on the documentation for that but that we'd entertain any assistance there. I welcome a discussion on it in the list which ideally could lead to an improvement/creation (whatever the case may be) of said documentation.

**Comment by chrisr3** [comment]
> I'd like to try to defuse the tension that seems to have already built up here. Can we start over on the list?

Sure, I have just posted to the `bndtools-users` list. I'm sure that Bnd _does_ support Gradle without Eclipse; it's just that I'm struggling to understand _how_,
