### ISSUE TITLE
[bndtools-explorer] Add pinned keyword to Bndtools Explorer

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#4283]
The recently added Bndtools Explorer allows to filter project by keywords, very handy. Is it possible to add a kind of pinned keyword to the search box? Something like this (just to grasp the idea, which is to have a set of projects at hand that do not share a common keyword):

![image](https://user-images.githubusercontent.com/25395973/91449737-c14ea680-e87b-11ea-8345-62f5dbfc1b36.png)

**Comment by cdelg** [comment]
Than could be handled with a special syntax too, such as `api + owl`

**Comment by pkriens** [comment]
You know this is a glob?

     api or owl                        api|owl
     api before owl                api*owl
