### ISSUE TITLE
[quickfix] Workspace repository doesn't match class names

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4288]
It appears that the quick fix processor is unable to find classes that are declared in other projects in the workspace. It matches on exported packages, but not classes. Suspect that bnd.hashes is not being generated/used for the workspace repository?

**Comment by pkriens** [comment]
Good for reporting this. I noticed it as well.

**Comment by bjhargrave** [comment]
> Suspect that bnd.hashes is not being generated/used for the workspace repository?

Hashes are added by ResourceBuilder.addFile

https://github.com/bndtools/bnd/blob/877793dbf2cd1a1a5fc39c5378a77043fc4a9b17/biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java#L705-L720

if the file is a bundle (has an OSGi manifest). Project.parseBuildResources use ResourceBuilder.addFile to create resources for the WorkspaceRepositoryDynamic object used for the workspace.

https://github.com/bndtools/bnd/blob/877793dbf2cd1a1a5fc39c5378a77043fc4a9b17/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L3639-L3650

So I don't see how bundles in the workspace does not have hashes for index searching.

**Comment by kriegfrj** [comment]
It could also be on the use side somehow.

**Comment by pkriens** [comment]
Maybe the workspace repo is not included in the search?

**Comment by kriegfrj** [comment]
Also, for whoever gets around to looking at this: generally when you match on a workspace bundle, you'd want to suggest `version=snapshot` rather than version number of the bundle you matched.

**Comment by kriegfrj** [comment]
> So I don't see how bundles in the workspace does not have hashes for index searching.

Ok, I've solved this mystery, but might need some guidance on the solution (or need to handball it).

* `Project.resources` is memoized. Its default supplier is set to `Project::parseBuildFiles`. `Project::parseBuildFiles` should do the right thing, as BJ pointed out above.
* When a project is built locally, the BndtoolsBuilder invokes `Project.build()` -> `Project.build(boolean)` -> `Project.buildLocal()`.
* `buildLocal()` also sets resources:
https://github.com/bndtools/bnd/blob/17964dde8ff973ce008cc468a9d78b967c33f21f/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L1989-L1991
* The individual resource builders are initialised here, using `ResourceBuilder.memoize()`:
https://github.com/bndtools/bnd/blob/17964dde8ff973ce008cc468a9d78b967c33f21f/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L1922-L1923
* `ResourceBuilder.memoize()` does not invoke `addHashes()`.

Presumably, the purpose of the different code path for `buildLocal()` is an optimisation that takes advantage of the fact that the jar file is freshly minted and still in memory. In which case, the best solution will be to insert a call to `addHashes()` (or some variant thereof) in there somewhere. Otherwise, if there is no particular reason it's been written that way, it will be best to modify the code to re-use the same code path.

**Comment by bjhargrave** [comment]
Yes, that seems to be the issue. `ResourceBuilder.memoize` must add the hashes. `ResourceBuilder.memoize` attempts to optimize over `ResourceBuilder.addFile` since it has a `Jar` object at hand. However, it does need to add the hashes but `ResourceBuilder.addHashes` takes a `File` object since `new JarIndex` takes a `File` object. So I think we will need some way to make a `JarIndex` or a `Hierarchy` (supertype of `JarInxex`) from a `Jar` object.

I looked at the code but I was unable to quickly get my head around the hierarchy package. I guess we need to add something to `Jar` that would return a `Hierarchy` object for the `Jar` object. Then that could be used for the adding of hashes.
