### ISSUE TITLE
[junit-platform] Support configuration parameters 

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4297]
In junit-platform, configuration parameters are passed in when you build the `LauncherDiscoveryRequest`. For `biz.aQute.tester.junit-platform`, that means here at the top level for `BundleEngine`:

https://github.com/bndtools/bnd/blob/5595754a984f809ec333f898f3acd357c0bfdad5/biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java#L327-L332

Then inside `BundleEngine`, there is code that copies all of the configuration parameters from the parent discovery request into the sub-discovery request for the particular test engine:

https://github.com/bndtools/bnd/blob/5595754a984f809ec333f898f3acd357c0bfdad5/biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java#L563-L566

We need a way to support customising these configuration parameters so that the tester can be configured to pass in configurations for junit-platform, and particular test engines.

I propose we declare a namespace under tester as an addition to the OSGi properties already supported - eg, "tester.configuration". Then any parameter that would normally be passed to JUnit Platform or one of the test engines, we simply prefix it with "tester.configuration". The Activator can copy all of these configuration constants into the initial LauncherDiscoveryRequest.
Thus `junit.platform.output.capture.stdout` => `tester.configuration.junit.platform.output.capture.stdout`.

`junit.jupiter.execution.parallel.enabled` => `tester.configuration.junit.jupiter.execution.parallel.enabled`.

Another (perhaps complementary) approach would be to use lifecycle callback methods to give plugins the chance to configure test engines programmatically just before they are executed - possibly customising it on a per-bundle basis. I've been thinking about adding lifecycle callbacks for other reasons too, but this will probably be a future project.

**Comment by bjhargrave** [comment]
Since I went ahead and configured stdout/stderr capture (#4299), we don't have pressing immediate need for this.

Also, per https://junit.org/junit5/docs/current/user-guide/#running-tests-config-params, it seems one can configure the known configuration parameters through system properties or a `junit-platform.properties` resource on the class path. So `-runproperties: -Djunit.jupiter.execution.parallel.enabled=true` should do the trick. Do we need to define another way?

**Comment by kriegfrj** [comment]
> Since I went ahead and configured stdout/stderr capture (#4299), we don't have pressing immediate need for this.
> 
> Also, per https://junit.org/junit5/docs/current/user-guide/#running-tests-config-params, it seems one can configure the known configuration parameters through system properties or a `junit-platform.properties` resource on the class path. So `-runproperties: -Djunit.jupiter.execution.parallel.enabled=true` should do the trick. Do we need to define another way?

Assuming that this works (it seems that it should, but I haven't tested it), then no I don't think we need another way. However, now that stdout/stderr capture is hard-coded it cannot be overridden. Maybe we should tweak the implementation so that it uses the system property and/or Java properties file setting for that property first if it can find it, and if not then explicitly set it to `true`. This way we keep it on by default but still allow people to override that if they wish.

**Comment by bjhargrave** [comment]
> Assuming that this works (it seems that it should, but I haven't tested it), then no I don't think we need another way.

https://github.com/junit-team/junit5/blob/4e7a087e052d982ec02a75da4a2c1f6cc34abde2/junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java#L104-L126
