### ISSUE TITLE
[junit-platform] JUnitEclipseListener is not thread-safe

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4308]
Following #4296 and a discussion with @bjhargrave started to get me wondering - I had a bit of a look at our current implementation of `JUnitEclipseListener`. It doesn't look very thread-safe. A quick test seems to confirm this: I just tried running osgi-test junit5 tests with parallel enabled and the Eclipse display gets messed up, with several random tests reporting that they haven't run, or that they started and didn't finish:
![ParallelFail](https://user-images.githubusercontent.com/7224087/92681797-c3316300-f36d-11ea-9653-a42a950153d4.png)

Note that `BundleContextExtension_CleanupTest#cleansUpBundleListenersMultiLevel()` (and a few others in that class) never ran, and that `cleansUpRegisteredServicesMultieLevel()->afterClass` is still marked as running (as are a few other tests further down) even though the entire test suite has finished.

Getting this working properly will require some attention. For now, if anyone wants to run the tests with the Eclipse IDE support enabled, I recommend that they don't try and use parallelism.

**Comment by bjhargrave** [comment]
As I have said in https://github.com/osgi/osgi-test/issues/201#issuecomment-689555373, I don't think CONCURRENT testing is practical for OSGi testing. This is just another example. The communications protocol with the Eclipse IDE does not handle it either. The IDE view should show actual progress of the tests and I don't think the comms protocol can properly handle multiple tests executing simultaneously.

**Comment by kriegfrj** [comment]
> As I have said in [osgi/osgi-test#201 (comment)](https://github.com/osgi/osgi-test/issues/201#issuecomment-689555373), I don't think CONCURRENT testing is practical for OSGi testing. This is just another example. 

To be fair, you said you don't think it's practical for testing services - which in the general case I agree with. And even if you can't run concurrent within the same test class (as they are all accessing the same service), you might be able to run two independent test classes in parallel if they are using independent services.

Several of my own OSGi integration tests could be run parallel.

> The communications protocol with the Eclipse IDE does not handle it either. The IDE view should show actual progress of the tests and I don't think the comms protocol can properly handle multiple tests executing simultaneously.

Actually, I think it *might* be able to. Many of the key message types include a test identifier. For example, `%TESTS`, `%FAILED`, `%ERROR` and `%TESTE` all take the test identifier as a parameter. I remember when coding `JUnitEclipseListener` that I wondered why the identifier was needed for anything other than `%TESTS` - the presence would allow the client receiving the messages to pair the failure/error/test end message with the corresponding test start, even if other test start/end messages are issued in-between. There are certain message sequences that would need to be serialised, but overall I think it might not be as difficult as I first thought.

**Comment by bjhargrave** [comment]
> To be fair, you said you don't think it's practical for testing services

I extended my thinking to now include it being impractical for all OSGi testing. https://github.com/osgi/osgi-test/issues/201#issuecomment-691100313

> Several of my own OSGi integration tests could be run parallel.

This may be true since your tests are not sensitive to the visible side effects of the other tests, or your tests produce no side effects (don't install bundles or register services). But this is just being lucky :-)
