### ISSUE TITLE
The Maven version prerequisite should be part of the pom

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4313]
The prerequisite listed in https://github.com/bndtools/bnd/tree/master/maven#maven-plugins should be reflected in the `pom.xml` as well. This is used by Maven and some of its plugins to enforce this.

**Comment by bjhargrave** [comment]
> The prerequisite listed in https://github.com/bndtools/bnd/tree/master/maven#maven-plugins

That is not a prerequisite for building the maven plugins. It is a statement that we intend the maven plugins to be useable on older versions of maven. See https://github.com/bndtools/bnd/blob/417811e3183520aa0977404b01aaa832bbf0ddf2/maven/pom.xml#L18

**Comment by kwin** [comment]
Prerequisites listed in `pom.xml` for packaging `maven-plugin` are meant to be execution prerequisites. So if you require at least 3.1.1 you should explicitly mention that as prerequisite. The dependencies only will just lead to run time errors.

**Comment by bjhargrave** [comment]
> Prerequisites listed in `pom.xml` for packaging `maven-plugin` are meant to be execution prerequisites

Really? Can you point to documentation for this?

When I build with the prerequisite element in the pom, I don't see any evidence of it appearing in the built plugin artifact's metadata. e.g. `META-INF/maven/plugin.xml`.

According to the documentation I found, https://maven.apache.org/pom.html#prerequisites, it says:

> The only element that exists as a prerequisite in POM 4.0 is the maven element, which takes a minimum version number. It is checked with Maven 2, it is not any more in Maven 3.

Which implies that the prerequisite element is a no-op anyway.

> So if you require at least 3.1.1 you should explicitly mention that as prerequisite. The dependencies only will just lead to run time errors when used with older Maven versions.

It is already mentioned in the built plugin's metadata. From `META-INF/maven/plugin.xml`:

```xml
  <dependencies>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-model</artifactId>
      <type>jar</type>
      <version>3.1.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-settings</artifactId>
      <type>jar</type>
      <version>3.1.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-repository-metadata</artifactId>
      <type>jar</type>
      <version>3.1.1</version>
    </dependency>
```

**Comment by kwin** [comment]
https://issues.apache.org/jira/browse/MNG-6092 and https://issues.apache.org/jira/browse/MNG-5297 have more details. Documentation at https://maven.apache.org/pom.html#prerequisites is misleading unfortunately.

**Comment by bjhargrave** [comment]
> Really? Can you point to documentation for this?

I found this: https://maven.apache.org/guides/development/guide-plugin-documentation.html#optional-elements

Since we flatten the pom, we would need to put the prerequisite element in each child project as the flattening process ignores the prerequisite element in the parent pom.
