### ISSUE TITLE
[source] MavenBndRepository source download doesn't update projects

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4320]
I had org.apache.cxf:cxf-core:3.3.1 in a MavenBndRepository.

I had a project with this bundle on its build path.

I attached sources by right-clicking in the repository view.

The sources downloaded and attached, creating "+cxf-core" in the appropriate directory.

However, my project didn't notice and continued linking to "cxf-core" (the bundle without the attached sources). I triggered a re-build of the Bnd dependencies by removing cxf-core from the build path and re-adding it to get it to link to the version of the bundle with attached sources. It would be nice if this were not necessary.

**Comment by bjhargrave** [comment]
This is purely an Bndtools/Eclipse thing. We need someway to force the BndClasspathContainers to be regenerated when a +file is created.

**Comment by kriegfrj** [comment]
Possibly related: I also removed a couple of artifacts from my `central.mvn` file and some of the dependent projects didn't automatically notice.

**Comment by pkriens** [comment]
The refresh button on the Bndtools explorer works perfectly for this purpose since it will recalculate the class path.

Though I am a bit confused that the automatic source collection does not work? The MavenBndRepository does support the <bsn>.source pattern I think.

**Comment by kriegfrj** [comment]
> The refresh button on the Bndtools explorer works perfectly for this purpose since it will recalculate the class path.
>

Thanks for the tip! But one of the key selling points of Bndtools is that you don't have to manually press a button to refresh things like this.
 
> Though I am a bit confused that the automatic source collection does not work? The MavenBndRepository does support the .source pattern I think.

I'm assuming that it doesn't attach the sources in the ClassPathEntry object to the existing jar once they have been successfully downloaded. So as long as it still points to the old jar the source lookup won't work.

**Comment by pkriens** [comment]
> Thanks for the tip! But one of the key selling points of Bndtools is that you don't have to manually press a button to refresh things like this.

Yeah, but I guess there are limits to free stuff :-)

> I'm assuming that it doesn't attach the sources in the ClassPathEntry object to the existing jar once they have been successfully downloaded. So as long as it still points to the old jar the source lookup won't work.
Well, the + files work because Eclipse will always look inside the JAR, this is a standard feature. But I recall that we were trying to attach source code with the bsn trick when we constructed the Eclipse classpath. 

If only I could debug bndtools again :-(

**Comment by bjhargrave** [comment]
Do we still have an issue here?

**Comment by pkriens** [comment]
I am still experiencing it

**Comment by bjhargrave** [comment]
@juergen-albert Can you fix by Sep 15 (of defer to 6.1)?
