### ISSUE TITLE
Error: Classes found in the wrong directory

### ISSUE THREAD

**Issue by rakeshk15** [bndtools/bnd#4322]
I am embedding the RESTEasy and related dependencies in a bundle and today updated the Smallrye common dependency to v1.9.0 and after that while building BND started failing with this error.

bnd-maven-plugin:5.1.2:bnd-process (default) @ adeptj-modules-jaxrs-resteasy ---
[ERROR] /Users/rakesh.kumar/code/adeptj/adeptj-modules/jaxrs/resteasy/bnd.bnd [0:0]: Classes found in the wrong directory: {META-INF/versions/9/io/smallrye/common/classloader/ClassDefiner$1.class=io.smallrye.common.classloader.ClassDefiner$1, META-INF/versions/9/io/smallrye/common/classloader/ClassDefiner.class=io.smallrye.common.classloader.ClassDefiner}

It works with an older version v1.8.6 of Smallrye common.

This is an open source project and available here - https://github.com/AdeptJ/adeptj-modules/tree/master/jaxrs/resteasy

Please let me know if you need more information.

Thanks,
Rakesh

**Comment by rotty3000** [comment]
This is not really a bug. You could use:

```
-fixupmessages: "Classes found in the wrong directory:";is:=ignore
```

Also this is more of a usage question so I'd ask you to use the mail list :)

**Comment by rakeshk15** [comment]
Hi @rotty3000,

Thanks for the clarification, just for my understanding, by using the directive -fixupmessages we are are telling bnd to ignore the error and continue the build.

Thanks,
Rakesh

**Comment by rotty3000** [comment]
It's very likely that this is a false positive so the likeliness that this is a _real_ problem is not very high.
