### ISSUE TITLE
gradle build fails if a maven or bnd pom repository can't find a declared artifact

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4323]
The `MavenRepository` declares Artifacts it can't find as an error. This is transported to project and appears in the errors list. The gradle build checks each project for errors and thus fails on each project regardless if the artifact is needed or not. 

For a `MavenBndRepository` this might make sense, because it can be fixed by correcting the index file and it forces people to keep their Repository clean. For a `BndPomRepository` however this is a problem, because any transitive dependency that can't be found causes the same issue and one can not necessary do anything about it. 

I would suggest that we scale this back as a warning. I will provide a PR for this ASAP.

**Comment by bjhargrave** [comment]
Just use a -fixupmessages to convert the error. Don't change the Bnd code.

**Comment by juergen-albert** [comment]
This would be a quickfix, but I'd say we need a more permanent solution, because we basically changed the build behavior under gradle in a significant way. In fact each of our builds and of our customers breaks, when we use a Version higher as 5.0, if a BndPomRepo is used. 

Another thing is, that till now one of our best arguments for bndtools with gradle was, that works in bndtools meant it works in gradle as well. 

To get a solution for the long run: We could introduce a `strict` property at least for BndPom Repository and maybe for the maven Repo as well that controls if this will be warning or error. For myven the default can be true and for the bndpom repo false.

**Comment by bjhargrave** [comment]
I would say it is always an error if a transitive dependency cannot be found. It indicates a bad repository or badly configured repositories. If a particular build does not care about this error, it can use -fixupmessages to elide the error.

**Comment by juergen-albert** [comment]
Worked like a charm, but I have to admit the fixup messages are one of the more advanced tools in our drawer. 

In general I'm with you, that a missing dependency should be seen as an error for a repository and something that needs to be taken care of. I would vote for my suggestion with the strict mode non the less, because e.g. maven does not really complain about something like this as well. 

We help people to switch to bnd and in some parts it is already a hard sell, because we need to teach pople a lot of things along the way. It mostly becomes an exercise in yak shaving already and I would opt for a bit of convenience here. Especially in the migration phase, I can gauge what reaction the tip with the fixup messages will provoke at certain points. A mob with pitchforks and a whispering of witches and a stake is included!

**Comment by bjhargrave** [comment]
I'd like to close this. As I stated above, only a given build can know that a missing transitive dependency is _not_ an error. So it is up to that build to de-escalate the error into a warning or ignore the error. It is wrong from Bnd to always assume a missing transitive dependency is just a warning.

**Comment by bjhargrave** [comment]
Closing.
