### ISSUE TITLE
Exposing classpath outside BND

### ISSUE THREAD

**Issue by caesarkim** [bndtools/bnd#4326]
I am not sure if my question is correct. With my understanding, BND plugin configures classpath based on bnd.bnd file from each bundle and compiles OSGI java files.  It is because we defines dependencies inside bnd.bnd file.  I need to run PMD code analysis for all the OSGI bundles in my workspace, but the problem is that PMD does type resolution, so if it can't find a class, it throws NoClassDefFoundError.

The issue that I have is that I don't have build.gradle per bundle, so PMD does not seem to know the classpath. So I am wondering if there is a way to expose the classpath that BND uses for compilation.  I am not sure if it is related to PMD configuration or bnd configuration.. i am not quite sure.

**Comment by bjhargrave** [comment]
If you are using the Bnd Workspace Gradle plugin (https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle#gradle-plugins-for-bnd-workspace-builds), then this plugin will properly configure the gradle project's configurations to the classpath established by the bnd.bnd file. For example, the `compileJava` task's classpath:

https://github.com/bndtools/bnd/blob/a067990705b8219300fdeb1965d6bb6e8328a0dc/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L514

Also, usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>. So I will close this issue. Please ask any additional usage questions in the mail list. Thanks.

**Comment by pkriens** [comment]
I once wrote a feature in the bnd command line to provide you with a classpath in platform-dependent path form so you could give it to an application, it was only a few lines of code. I think I needed this to run the jshell. 

     $ jshell -cp `bnd project classpath`

However, it somehow must never have been committed. I can add such a command if you want.
