### ISSUE TITLE
[BndPomRepository] NPE

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4328]
I'm not exactly sure how, but managed to capture a decent stack trace that the interested person should be able to use to track it down:

![BndPomRepoNPE](https://user-images.githubusercontent.com/7224087/94451313-61864b00-01ed-11eb-87db-9a646f67260e.png)

**Comment by juergen-albert** [comment]
There is obviously a null check missing. It looks like the failing method https://github.com/bndtools/bnd/blob/a33a1a0a42ba70bae26226058ca81a5d69f6c0a8/biz.aQute.repository/src/aQute/maven/provider/POM.java#L334 
can be totally replaced with https://github.com/bndtools/bnd/blob/a33a1a0a42ba70bae26226058ca81a5d69f6c0a8/biz.aQute.repository/src/aQute/maven/provider/POM.java#L319 . 

They both do the exact same thing, just without the null check that is causing the issue.

**Comment by juergen-albert** [comment]
@rotty3000 any thoughts from your side, because you had been the last to anything in this methods.

**Comment by bjhargrave** [comment]
The methods are different but the `getOrSetNoInheritance` method forgot to check for `null` before calling `replaceMacro`.
