### ISSUE TITLE
Import Packages for java.* packages appear in projects < Java 9

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4348]
It appears that the new functionality to generate Import Packages declarations kicks in, even if the Java Version is  lower then Java 9.

An example workspace can be found here: https://gitlab.com/gecko.io/gecko-jaxb in the java8 branch. Maybe I've missed something, but everything I found points to java 8.

**Comment by bjhargrave** [comment]
From the 5.2.0 wiki page: 

> Bnd will now import java.* packages if the bundle requires Java 11, or later, or if the bundle imports the org.osgi.framework package at a version >= 1.9. The importing of java.* packages can be disabled with the instruction -noimportjava: true.

**Comment by bjhargrave** [comment]
There is a bug in the Bnd resolver for this which I have a fix for in #4347.

**Comment by juergen-albert** [comment]
hmm, why do we depend on a framework >= 1.9? Bundles Such a Bundle does not resolve a current felix with java8. Is this what we want?

**Comment by juergen-albert** [comment]
ah, okay. Will this be part of the 5.2. Release?

> There is a bug in the Bnd resolver for this which I have a fix for in #4347.

**Comment by bjhargrave** [comment]
> hmm, why do we depend on a framework >= 1.9?

Because you compile against `org.osgi:osgi.core:7.0.0`



> Such a Bundle does not resolve a current felix with java8. Is this what we want?

Perhaps this is a Felix bug. The R7 spec requires to resolve imports of java.* on any java version. Not just Java 9 and later.



> ah, okay. Will this be part of the 5.2. Release?

I plan to add it. But that fix only affects Bnd resolving and not runtime.

**Comment by bjhargrave** [comment]
> I plan to add it.

I added #4347 to the next branch for 5.2. 5.2.0.RC3 is building now.

**Comment by karlpauls** [comment]
> hmm, why do we depend on a framework >= 1.9? Bundles Such a Bundle does not resolve a current felix with java8. Is this what we want?

Felix does support this since quite a while. It is part of the R7 spec and we support that since 6.0.0

**Comment by juergen-albert** [comment]
@bjhargrave I've tested your fix and with RC3 it resolves now as expected. Thx!
