### ISSUE TITLE
Since 3.4.0 bind and unbind methods generated by SCRDescriptorBndPlugin are not included any more in the final JAR

### ISSUE THREAD

**Issue by rudolfstrehle** [bndtools/bnd#4351]
In version 3.4.0 aQute.bnd.osgi.Resource.buffer() has been introduced to cache the resource's bytes. In aQute.bnd.osgi.Analyzer all resources and classes previously visited buffer() is called, which loads the class file into memory. 
A subsequent execution of SCRDescriptorBndPlugin adds the bind and unbind methods to the file system, but the buffer is not updated and when the final JAR is built, then the cached content without bind and unbind methods is written to the JAR.

Can be reproduced by adding to your pom

```
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>3.4.0</version>
        <extensions>true</extensions>
        <configuration>
          <exportScr>false</exportScr>
          <instructions>
            <_include>osgi.bnd</_include>
            <_noee>true</_noee>
            <_plugin>org.apache.felix.scrplugin.bnd.SCRDescriptorBndPlugin;destdir=${project.build.outputDirectory}</_plugin>
          </instructions>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.scr.bnd</artifactId>
            <version>1.9.4</version>
          </dependency>
        </dependencies>
      </plugin>
```

and using org.apache.felix.scr.annotations.Reference. The bind and unbind methods are added to target/classes, but not to the final jar.

**Comment by bjhargrave** [comment]
This seems like a flaw in the `SCRDescriptorBndPlugin`. It mutates a class file after its Resource has been placed in the Jar but does not update the Resource in the Jar with the mutated class file. It only mutates a file on the file system. Any mutation of a Resource in the Jar should be done to the Jar and not the file system as the Jar is already populated with Resources.

**Comment by rudolfstrehle** [comment]
Actually SCRDescriptorBndPlugin is executed before the Jar contains any resources. So it could not update the Jar at time of execution. The problem here is, that the class file is correctly updated by SCRDescriptorBndPlugin, but an older version is kept in the buffer and populated to the Jar after execution of SCRDescriptorBndPlugin. I don't see a viable way for SCRDescriptorBndPlugin to fix the problem.

**Comment by bjhargrave** [comment]
The SCRDescriptorBndPlugin is most definitely executed _after_ Analyzer has populated the Jar object with Resources. SCRDescriptorBndPlugin is an AnalyzerPlugin which is passed the Analyzer after the Analyzer has populated the Jar. SCRDescriptorBndPlugin is in error by not updating the Resources in the Jar after mutating them.

**Comment by rudolfstrehle** [comment]
Well, I debugged the bundle plugin and could see, that while the SCRDescriptorBndPlugin was executed the Jar was still empty or inexistent (don't remember). The resources were populated to the Jar after execution of SCRDescriptorBndPlugin. 
I can replicate the behavior if required and provide screenshots, but that takes time and would prefer not to do that. But let me know if you nevertheless need them to dig deeper into the issue.

**Comment by bjhargrave** [comment]
Analyzer populates the Jar here

https://github.com/bndtools/bnd/blob/4915ec122195965dec919d19a74e3e2f2c936a8c/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L210-L212

The AnalyzerPlugins are called later here

https://github.com/bndtools/bnd/blob/4915ec122195965dec919d19a74e3e2f2c936a8c/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L247-L249

If the Analyzer had not populated the Jar with Resources, the Resouces would not exist for the buffer() method to have been called.

I do not see any defect in Bnd here. Any issues are with how SCRDescriptorBndPlugin operates. It should not be mutating the file system and expecting that is sufficient for Bnd to notice. SCRDescriptorBndPlugin needs to mutate the Jar object in the provided Analyzer object. So I don't see that we need to dig any deeper into this from the Bnd point of view. The problem needs to be addressed in maven-bundle-plugin and SCRDescriptorBndPlugin.

**Comment by bjhargrave** [comment]
> Well, I debugged the bundle plugin and could see, that while the SCRDescriptorBndPlugin was executed the Jar was still empty or inexistent (don't remember).

I will note that SCRDescriptorBndPlugin is both a Plugin and an AnalyzerPlugin. 

https://github.com/apache/felix-dev/blob/ca021fd59fc4e6996495f63f7fa47cc39fe25538/tools/org.apache.felix.scr.bnd/src/main/java/org/apache/felix/scrplugin/bnd/SCRDescriptorBndPlugin.java#L61

It is only at 

https://github.com/apache/felix-dev/blob/ca021fd59fc4e6996495f63f7fa47cc39fe25538/tools/org.apache.felix.scr.bnd/src/main/java/org/apache/felix/scrplugin/bnd/SCRDescriptorBndPlugin.java#L149

that the Analyzer will be provided with a populated Jar since the AnalyzerPlugins are called from Analyzer.doPlugins.

SCRDescriptorBndPlugin also has other flaws. AnalyzerPlugins should be stateless. AnalyzerPlugins are singleton objects and are called multiple times for each Analyzer. In multi threaded situations, that can create problems. You will see, for example, that 

https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java

is stateless.

**Comment by rudolfstrehle** [comment]
Thank you very much for the detailed clarification. Your comments make the issue clear. I will file an issue for the SCRDescriptorBndPlugin. For Bnd in my opinion the issue can be closed as invalid.
