### ISSUE TITLE
[bndtools] UI lockup when copying a file

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4358]
See image:

![image](https://user-images.githubusercontent.com/7224087/96248636-64f24280-0ff3-11eb-94d8-55a2cdf7dd7f.png)

I'm sorry, I don't know the exact steps that I did to get into this state. But it was something like this:

* I created the new Bndtools project `au.org.greekwelfaresa.idempiere.test.generator.ui`.
* I dragged launch-ui.bndrun from the project above into the new project. This action hung waiting for the build to complete.
* Tried to cancel everything - as you can see, nothing worked.
* Tried to exit Eclipse - still nothing. Had to forcefully kill it.

I've seen this happen before so I thought it would be good to report in case anyone else is having the issue. Could be a Windows thing.

**Comment by juergen-albert** [comment]
I have the same issue from time to time and also have a customer that has this issue on a regulare basis. I currently run my eclipse constantly in debug mode, in the hope to find this cause of the issue because this is really annoying. Unfortunately I can't reliably reproduce it. 

@kriegfrj do you use windows? Till now, I only saw this on windows. Can your reproduce it with your described steps?

What I found the one time I managed to attach the debugger, was that the builder is waiting for a bundle to use and all the repositories had been waiting for promises that tell them if they are fresh. I will add more details, when I have the situation

**Comment by juergen-albert** [comment]
@bjhargrave can you assign this to me and put it on the 5.3 milestone? We really need to fix this somehow.

**Comment by bjhargrave** [comment]
I assigned to you. Once you have a PR, we can milestone the issue.

**Comment by kriegfrj** [comment]
> I have the same issue from time to time and also have a customer that has this issue on a regulare basis. I currently run my eclipse constantly in debug mode, in the hope to find this cause of the issue because this is really annoying. Unfortunately I can't reliably reproduce it.
> 

I'm glad to hear that I'm not the only one!

> @kriegfrj do you use windows? Till now, I only saw this on windows.
> 

Yes, I'm using Windows 10. 

Given that this seems to be a Windows-specific issue, the problem might be related to file locking. In which case, in addition to running with the debugger, you should also run with the file leak detector utility: https://file-leak-detector.kohsuke.org/ @pkriens pointed me at this utility when he was helping me chase down some build errors on Windows due to file locking, it's quite handy. Put this on the command line of your Eclipse instance, and configure its in-built http server - then when you have a lockup you can browse to the http server port on localhost and get a dump of the open files and the stack trace of the code that opened them.

I have also noticed occasionally the old build error problem  due to file locking that I haven't been able to pin down. I wonder if it's related to this issue.

> Can your reproduce it with your described steps?

I just gave it a try - I was not able to reproduce it. In fact, I don't think I've seen it happen since I opened this issue request.

In my case, it happened in connection with the creation of a new project.

> What I found the one time I managed to attach the debugger, was that the builder is waiting for a bundle to use and all the repositories had been waiting for promises that tell them if they are fresh. I will add more details, when I have the situation

Maybe the file-leak-detector will help throw up some new information. If you can catch it in this state again, have a look at the open files dump and something might jump out.

**Comment by kriegfrj** [comment]
After a bit of a hiatus, this has happened to me a few times today.

It seems to be happening when I am updating my .mvn files/repositories. In all cases I've seen, the progress meter is showing a "build" and an "update repositories". I suspect that these two operations are both waiting for the other somehow.

In the lockups I've seen today, I've also seen "Refreshing /cnf" come up, but that is not in the screenshot that I reported above. The "update repositories" and "build" tasks were in my task list today. That is why I suspect that the lockup is happening between these two tasks and not others.
