### ISSUE TITLE
[resolver] Preserve full log on resolution failure

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4360]
@juergen-albert added the useful feature as part of #4155, that if you cancel the resolution while it is in progress it will store the log somewhere where you can open it and examine it if you wish (or it will delete it if you say you don't want it).

It would be nice if this feature could be extended to optionally preserve the resolve log for any failure (or perhaps even any resolve operation), and not just when you cancel a resolve.

As #4354 demonstrates (and there are other examples) there are times when a resolution fails but the short summary of the failure that the resolver displays you doesn't give you the full picture. In lieu of the resolver being able to give a useful summary, preserving the log for direct examination could be the next-best-thing.

**Comment by juergen-albert** [comment]
I'll have a look if I find the time! 
@bjhargrave Can you assign it to me?

**Comment by bjhargrave** [comment]
@juergen-albert Can you fix by Sep 15 (or defer to 6.1)?

**Comment by juergen-albert** [comment]
@BJ can you move it to 6.1. I unfortunately can't modify anything here, beyond unassigning me.
