### ISSUE TITLE
Externally Loaded Exporter Plugins are hard to use and usually cause ClassNotFoundExceptions

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4361]
I try to develop and Exporter Plugin for BND and stumbled upon a few problems if I want to use it in bndtools, that make it really hard to use.

In order to get bnd to recognize it, I need to set a `-pluginpath` instruction to get it loaded. In order not to use file references I opted to use the repo macro like `${repo;atomos-bnd-plugin;latest}`to references it. To get this to work, I need to do this in my bndrun file, In order to kick the export of, I have the following entry in a bnd file next to the bndrun:
```
-export:\
	launch.bndrun;type=substrate
```
Bndtools now fails with a ClassNotFoundException, because it can't load our Exporter class, which resided in bndlib. The reason is the mechanism we use to load Plugins. We use the `Processor.CL` which is initialized by calling 

```
public CL(Processor p) {
			super(p, p.getClass()
				.getClassLoader());
		}
```

As we are in bndtools, p is in this case `Bndrun? which resided in the bundle `biz.aQute.resolve`. This in turn has no import for the `Exporter` package and thus can not load my plugin, because I inherit from Explorer. 

The easiest solution that I see is, to change the CL constructor to:
```
public CL(Processor p) {
			super(p, Processor.class
				.getClassLoader());
		}
```
This should always provide the ClassLoader of the bndlib bundle. 

Any thoughts on that?

**Comment by bjhargrave** [comment]
> super(p, Processor.class
> 				.getClassLoader());

Well this might solve one problem here, but will just create a different problem finding exporters in the processor subclasses class loader.

This issue seems to be created by "hacking" to use `Bndrun` from resolver than `Run` from bndlib. @pkriens will need to provide advice here.

**Comment by pkriens** [comment]
Easiest solution seems to define the plugin in build.bnd? In general, all plugins are supposed to be defined there. However, at that time the repositories are not yet defined since they are plugins. The plugin mechanism clearly was not designed to use repositories.

We could change Processor to always use the Workspace classloader as parent. Plugins are part of Processor but it is a bit in puberty with its relation to its parent. I do not trust any plugin to work on lower levels.

Longer term solution is to use the [External Plugin](https://bnd.bndtools.org/chapters/875-external-plugins.html) model I made in the export function. This will allow you to just develop the plugin as a workspace project or deliver it via the repo. See `aQute.bnd.build.ProjectGenerate.doGeneratePlugin(String, Map<String, String>, List<String>, InputStream, OutputStream, OutputStream)` for a usage pattern. Should be straightforward to use. Or `biz.aQute.externalplugin.ExternalPluginHandlerTest`

**Comment by juergen-albert** [comment]
> Easiest solution seems to define the plugin in build.bnd? In general, all plugins are supposed to be defined there. However, at that time the repositories are not yet defined since they are plugins. The plugin mechanism clearly was not designed to use repositories.
Yes, this is one issue I realized as well.
> 
> We could change Processor to always use the Workspace classloader as parent. Plugins are part of Processor but it is a bit in puberty with its relation to its parent. I do not trust any plugin to work on lower levels.

https://github.com/bndtools/bnd/blob/1e8e209df4691d1eee46a4b30279f791c8b50148/biz.aQute.bndlib/src/aQute/bnd/osgi/ActivelyClosingClassLoader.java#L201

In this Method we already have a fallback, to ask the systembundle for the class if we are inside an OSGi Framework. I would simply add another step to look inside the bundle the `ActivelyClosingClassLoader` comes from. This should be the bndlib bundle.
> 
> Longer term solution is to use the [External Plugin](https://bnd.bndtools.org/chapters/875-external-plugins.html) model I made in the export function. This will allow you to just develop the plugin as a workspace project or deliver it via the repo. See `aQute.bnd.build.ProjectGenerate.doGeneratePlugin(String, Map<String, String>, List<String>, InputStream, OutputStream, OutputStream)` for a usage pattern. Should be straightforward to use. Or `biz.aQute.externalplugin.ExternalPluginHandlerTest`

I'd like to implement this. The question to me is how. Internal and external Plugin usage is obviously different and it would be nice if could be addressed in a similar fashion without the need to implement an extra handling for each type of plugin. I believe we should move this discussion to an extra issue.

**Comment by pkriens** [comment]
We could create a `getAllPlugins(Class<T>)` method in Workspace that combines the two mechanisms. However, I designed the External Plugins to keep the classloader open shortly. However, maybe with a proxy it could work.
