### ISSUE TITLE
[bndlib] allow specification of version in analyzer.addClasspath( ... )

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#4375]
https://bnd.bndtools.org/chapters/600-developer.html states that

// You can provide additional class path entries to allow
// bnd to pickup export version from the packageinfo file,
// Version annotation, or their manifests.
analyzer.addClasspath( new File("jar/spring.jar") );

it would be good if one can alternatively supply a version of the classpathentry if none is found automatically e.g.

analyzer.addClasspath( new File("jar/spring.jar"), "1.2.3" );

**Comment by bjhargrave** [comment]
> it would be good if one can alternatively supply a version

I am not sure what this means. You are supplying a File object and if the file has OSGi metadata, that will be read form the file. Simply adding a version string is not a replacement for OSGi metadata. If you have a file with non-OSGi metadata, you really need to wrap it to create proper OSGi metadata. https://bnd.bndtools.org/chapters/390-wrapping.html

**Comment by laeubi** [comment]
According to the doc
 //You can provide additional class path entries to allow
// bnd to pickup export version from the **packageinfo file**,
// **Version annotation**, or their **manifests**.
it does not only consider OSGI-Manifest information, so I would expect that if I supply a version and a package from the supplied class-path entry is used it uses package-import with the supplied version if none of the above succeed in finding a valid version.

Of course I can first check if it is a bundle and wrap it first (but then i need also wrap dependencies of this item as well and so on...).

**Comment by bjhargrave** [comment]
packageinfo files are in the jar file. Version annotations are in package-info.class files in the jar file. The bundle's manifest is in the jar file. They all are from the specified File. I am not sure what you think a supplied version string would be the version of? What OSGi metadata would you expect Bnd to synthesize from a supplied version string here?

**Comment by bjhargrave** [comment]
Also, Bnd only would be interested in packageinfo/Version annotations for packages exported by the classpath entry as described in the file's OSGi manifest. If the entry does not export a package, then an analyzed bundle cannot successfully import it.

**Comment by laeubi** [comment]
I have an artifact I try to wrap with the analyzer, and I like to archive that the package-imports get version constraints.
Currently the analyzer correctly creates package-imports but without version constraints. So if I supply a version here and no ther metadata is available it should simply assume that version for all packages of the extra-classpath item.

As you mentioned I can also wrap the class-path item first but hope to avoid that, because then I need to know in advance how the dependency tree looks like to first wrap those without any additional dependencies and so on.

To get a simple example I have three jars (A, B, C), all without metadata and I wan't to wrap all of them, I know the BSN and I know the Version and I simply export/import all packages.

So I create an analyzer for A, and add B+C as extra Claspath, then one for B and add A+C and then one for C and and A+B, the problem is that I do not know in advance what artifact export and what import so I can't compute an order for those.

My goal would be to have something like:
Analyzer forJarA = ...
forJarA..addClasspath( new File("B.jar"), "1.2.3" ); // --> all import for packages from A -> B will get version=1.2.3
forJarA..addClasspath( new File("C.jar"), "4.5.1" ); // --> all import for packages from A -> C will get version=4.5.1

hope it is more clear now.

**Comment by laeubi** [comment]
By the way: of course it would be extremely useful if I add multiple jars with BND instructions to one Analyzer and the calculate the manifest for those but it seems that the analyzer only accepts one jar at a time.

**Comment by rotty3000** [comment]
This is really a usage question, but for completeness, since you know enough ahead of time to add a specific jar B with version 1.2.3 and C with version 4.5.1 to the classpath, why don't you simply write:
```
Import-Package: \
    packages.from.B.*;version=1.2.3,\
    packages.from.C.*;version=4.5.1,\
    *
```
which has the same exact effect?
HTH

**Comment by bjhargrave** [comment]
> why don't you simply write:

This is much better and avoids having to define a strange overload of addClasspath with very weak OSGi semantics.

**Comment by laeubi** [comment]
@rotty3000 thanks for the hint, the answer is simple:
Because BND is much smarter than me finding what are inside the jars :-)

If I want to give that information you suggested ahead of time I have to open all jars, find out what packages are there, mostly that what the analyzer would already do. That's why I thought it would be smarter to give the Analyser a hint instead of me do (additional) parsing.
What for example also would work is to first wrap all jars with only Export-Packages, then start another iteration with the actual desired meta-data throwing the old one away, I just hoped to avoid this extra round-trip.

**Comment by bjhargrave** [comment]
> I just hoped to avoid this extra round-trip

I think you need to do this work yourself. It does not make sense to modify the Analyzer to add a convenience method to recursively call the Analyzer on the added file.
