### ISSUE TITLE
[resolver] [mvn] Fragment bundles are not resolved since 4.3.1. <Bundle> was not associated with a resource in the resolution

### ISSUE THREAD

**Issue by dpishchukhin** [bndtools/bnd#4382]
The last version of bnd maven plugin that resolves the Fragment bundle correctly is 4.3.1. After update to 5+ version maven plugin fires the error:

`[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:5.2.0:export (default) on project gateway-distribution-bnd-assembly: The capability for wire osgi.identity;filter:='(osgi.identity=logback-smart-filter)' -> [logback-smart-filter version=20.10.0] was not associated with a resource in the resolution -> [Help 1]`

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by dpishchukhin** [comment]
[Gitrepo](https://github.com/dpishchukhin/bnd_issue_4382)

if you change root pom property **bnd.version** to **4.3.1** it's possible to build the assembly.

**Comment by bjhargrave** [comment]
Thanks. I debugged it and there is something wrong in the Apache Felix resolver as far as I can see. I have asked @tjwatson to take a look when he can. 

The resolver appears to add the wires to the initial requirement for the `ch.qos.logback.classic` host and the `logback-filter` fragment. But it fails to add the resources of either to the wiring result.
