### ISSUE TITLE
The Verifier insists on a version range when importing Java APIs other then javax.*.

### ISSUE THREAD

**Issue by chrisr3** [bndtools/bnd#4388]
Observed with Bnd 5.2.0.

```java
import static aQute.bnd.osgi.Constants.STRICT;
import aQute.bnd.osgi.Jar;
import aQute.bnd.osgi.Verifier;

Verifier verifier = Verifier(jar);
verifier.setProperty(STRICT, "true");
verifier.verify();
```
This generates the following error for my jar:
```
Import Package clauses without version range (excluding javax.*): [sun.misc]
```
There is no version range suitable for a package provided by the JVM itself.

**Comment by bjhargrave** [comment]
If the package comes from the highest EE used by the jar, then we should probably not complain if the import is not versioned.

**Comment by chrisr3** [comment]
Heh, I was just [looking into this myself](https://github.com/chrisr3/bnd/tree/chrisr3-unversioned-ee-ok) :wink:
