### ISSUE TITLE
RFE: Java runtimes make invalid assumptions about ModulePackages attribute under JPMS

### ISSUE THREAD

**Issue by markt-asf** [bndtools/bnd#4398]
This is not, in my view, a bnd bug. It is a request for a workaround for what looks like a [JRE bug](https://bugs.openjdk.java.net/browse/JDK-8255854) to me.

The issue was originally observed in Apache Tomcat which uses the bnd 5.2.0 JAR to generate OSGi and JPMS metadata.

The short version is:

- The JVM specification (version 9 onwards) defines the ModulePackages attribute for module-info.class and, if the attribute is present, only requires packages to be listed if they are exported, opened or contain service implementations.
- bnd is correctly implementing this requirement.
- An optimisation has been implemented in the OpenJDK JRE class loader (and hence picked up by most if not all JRE implementations) that incorrectly assumes that if the ModulePackages attribute is present **all** packages present in the module will be listed.

The result is CNFEs when trying to load classes present in a module where the ModulePackages attribute is present but the class is in a package that is not listed in the ModulePackages attribute.

It would be very helpful if there was a way in bnd to work-around this. It could be an option to add all packages discovered to the 
ModulePackages attribute, it could be a new package annotation that explicitly added a package to the ModulePackages attribute. It could be something else.

**Comment by bjhargrave** [comment]
I guess the best solution is for Bnd to either (1) add all packages to the ModulePackages attribute or (2) cease to add a ModulePackages attribute. 

There does not seem to be any harm in the ModulePackages attribute listing all packages. I'll work on a PR for this.

**Comment by markt-asf** [comment]
Thanks. Much appreciated.

**Comment by markt-asf** [comment]
Many thanks. I really appreciate the fast turn-around on this. Is the a CI/snapshot build somewhere I can try?

**Comment by bjhargrave** [comment]
> Is the a CI/snapshot build somewhere I can try?

https://github.com/bndtools/bnd/blob/master/README.md#using-the-latest-development-snapshot-build-of-bndbndtools

**Comment by markt-asf** [comment]
Thanks. Sorry. Missed that in my searching.
