### ISSUE TITLE
[bndlib] ProjectTracker.update() clears state after updating

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4403]
I think I found an issue which might be the root cause of #4401 and #4253.

Refer the following code:

```java
	private void update() {
		if (!changed) {
			return;
		}
		changed = false;


		Path base = workspace.getBase()
			.toPath();
		Set<String> older = new HashSet<>(models.keySet());
		try (DirectoryStream<Path> directories = newDirectoryStream(base, Files::isDirectory)) {
			for (Path directory : directories) {
				models.compute(directory.getFileName()
					.toString(), (name, project) -> {
						if (project != null) {
							older.remove(name);
							if (directory.equals(project.getBase()
								.toPath()) && project.isValid()) {
								return project;
							}
							IO.close(project);
						}
						if (isRegularFile(directory.resolve(Project.BNDPATH))) {
							project = new Project(workspace, directory.toFile());
							if (project.isValid()) {
								return project;
							}
							IO.close(project);
						}
						return null;
					});
			}
		} catch (IOException e) {
			throw Exceptions.duck(e);
		}


		older.stream()
			.map(models::remove)
			.forEach(IO::close);
	}
```

I'm not intimately familiar with this code, so I might be way off base here - but my reading of it (and stepping through it with the debugger) seems to indicate that it is problematic. The intent seems to be to synchronize the internal in-memory model state for the workspace's projects when there are changes on the filesystem. But the way it is written, it will always end up completely clearing the in-memory model of all previously-cached projects:

1. The line `Set<String> older = ...` takes a snapshot of all projects currently cached by the `ProjectTracker`.
2. The for loop loops over the directories in the workspace and creates Project instances for all the valid bnd projects that it finds.
3. The last line then loops over "older" and removes all of the projects in the snapshot taken at 1.

The problem is that there is no code between 1 and 3 that modifies "older". So whatever was in the snapshot before the loop began will still be there when the loop is finished, regardless of what happened inside the loop. So all the projects that were there to start with will be removed, even if they were updated in the loop. So if (eg) you started with a `ProjectTracker` that has already has all of the projects for all of the workspace, by the time `update()` has finished `models` will be empty.

On the other hand, if you start off with a `ProjectTracker` that is empty, it will produce the correct result because the `older.stream()...` at the end will be a no-op. I suspect this is why this bug has gone unnoticed in practice for so long - from the command line, you're typically running Bnd afresh each time and the `ProjectTracker` always starts off empty. It is only in Bndtools and its live incremental building where this behaviour would manifest.

I also have noticed in the past that Bndtools sometimes seems to do multiple passes when rebuilding a workspace (this was especially noticeable when I was trying to sort out the slow build issues which turned out to be primarily due to Windows Defender). Perhaps this explains why. In normal usage of Bndtools the `ProjectTracker` will sort itself out after multiple passes - the first call to `update()` would be likely to clear the `ProjectTracker`, and then the next call shortly thereafter will populate it properly. Normal human-speed interaction with the workspace is not fast enough to catch the `ProjectTracker` in that in-between state where it has cleared itself. However, programmatic interaction (such as the integration test) is sometimes quick enough, and if it happens to catch it in the in-between state then the `Project` instance it is looking for will come back `null`. Hence #4253. 

The fix should be fairly simple and will follow shortly, along with a regression test. Perhaps this should also be a maintenance candidate (although this behaviour has probably been there for a long time, so it might be able to wait?)

**Comment by kriegfrj** [comment]
Ok, I need to learn to read properly. There is *some* code that calls `older.remove()`, but based on my experience in the debugger it appears to not be working 100% properly. I will continue to investigate.

**Comment by bjhargrave** [comment]
>     2\. The for loop loops over the directories in the workspace and creates Project instances for all the valid bnd projects that it finds.

It does not always create them. It uses `Map.compute` which may modify the entry value or delete it. In our case we either leave the value alone after removing from `older` (`return project`), delete it (`return null`), or create a new Project.


>     3\. The last line then loops over "older" and removes all of the projects in the snapshot taken at 1.

At this point `older` will only contain Projects for which there is no backing directory on the file system. So these Projects are gone and need to be removed and closed.

> The problem is that there is no code between 1 and 3 that modifies "older".

Yes there is as you found. I am not sure why `HashSet.remove(Object)` would not always work. Sounds like there would be a total mess everywhere then.

I have worked extensively on this class and I am confident it is correct. But please keep investigating.

**Comment by kriegfrj** [comment]
Yeah, I think I jumped the gun on this one. Too much stepping in the debugger hath driven me mad.

I'll re-open if anything pops up.
