### ISSUE TITLE
Quickfix -buildpath/-testpath addition

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4410]
Currently an addition via the Quickfix to the -buildpath/-testpath adds the version.

I do not like these versions and want to skip them when possible. In a curated repo there is only a single version. If you add a version, you need to update it everywhere when you update the repo.

I would therefore like to remove the version when the repositories contain only one candidate for a BSN.

Thoughts?

**Comment by bjhargrave** [comment]
Or use `version=latest` instead of a specific version. This works when additional versions are added to the repos in the future. Missing version on -buildpath means `version=earliest` so we need to consider what should be the behavior when additional versions may be added to the repos in the future.

**Comment by pkriens** [comment]
No, I think we should always compile against the _oldest_. So if there is only one version in the quickfix, that should be ok. Less is more <=>! We pay a steep price for a type safe language, this is one of the places where it pays off.

**Comment by kriegfrj** [comment]
I agree with this complaint and had been meaning to raise this issue myself.

I'm not 100% sure that we should *always* compile against the oldest. But I think this makes sense for the majority of cases. So I think simply leaving the version off makes sense as the default behaviour, and I think is a good 80% solution. This is in fact what the old quick fix processor used to do, I think.

A couple of enhancements (in order of importance):

1. If the sole matching bundle is a workspace artifact, then I think that version=snapshot should be the default.
2. If there are two matching bundles, provide the option of no version and "version=latest".
3. Add a Bndtools configuration option to allow the user to configure the default for the workspace as either no version, version=latest or "version=<exact>".
4. Ideally, all of the various options would be directly available in the quickfix menu. However, if you put in all of the "version=" options for each matching bundle, you'd end up with an explosion of bundles and it would no longer be "quick" to find your match. Ideally, you'd list all the matching bsns, and as you hovered over the bsn that you're interested in it would give you the additional version options for that bsn that you can select. If you click on the head item it uses the default versioning strategy you've chosen. I think this is possible by implementing `ICompletionProposalExtension3` (it allows you to display additional info in a custom control) but I haven't had a chance to try it out.

Anyway, :+1: to this idea. Even a simple removing of the version by default would be a significant improvement I think (though I think the enhancement to add version=snapshot should be included too 
- once we get suggestions working for workspace bundles (!) that will be useful).

**Comment by kriegfrj** [comment]
> I agree with this complaint and had been meaning to raise this issue myself.
> 
> I'm not 100% sure that we should _always_ compile against the oldest. But I think this makes sense for the majority of cases. So I think simply leaving the version off makes sense as the default behaviour, and I think is a good 80% solution. This is in fact what the old quick fix processor used to do, I think.
> 
> A couple of enhancements (in order of importance):
> 
I have submitted a PR that fixes this, but did HRT manage to include the whole wish list:

> 1. If the sole matching bundle is a workspace artifact, then I think that version=snapshot should be the default.

This is not currently possible as the AggregateRepository does not keep track of which repo each result came from. Will need to change the api of search() to make it possible too. I propose to raise a new issue for this feature. 

> 2. If there are two matching bundles, provide the option of no version and "version=latest".

I've implemented 3 in favor of this option. 

> 3. Add a Bndtools configuration option to allow the user to configure the default for the workspace as either no version, version=latest or "version=".

This is done except for version=<version>.

> 4. Ideally, all of the various options would be directly available in the quickfix menu. However, if you put in all of the "version=" options for each matching bundle, you'd end up with an explosion of bundles and it would no longer be "quick" to find your match. Ideally, you'd list all the matching bsns, and as you hovered over the bsn that you're interested in it would give you the additional version options for that bsn that you can select. If you click on the head item it uses the default versioning strategy you've chosen. I think this is possible by implementing `ICompletionProposalExtension3` (it allows you to display additional info in a custom control) but I haven't had a chance to try it out.
> 

I tried this out and it won't work. Ilearned that ICompletionProposal3 is for Content Assist, not for quick fixes.
