### ISSUE TITLE
[bndlib] AlsoLauncherTest is flaky

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4414]
yes, but it is in another test you [@kriegfrj] authored which is now regularly failing CI builds like this one.

https://github.com/bndtools/bnd/pull/4404/checks?check_run_id=1389155797#step:5:449

Can you look into this? I would like to stabilize the CI builds.

_Originally posted by @bjhargrave in https://github.com/bndtools/bnd/issues/4404#issuecomment-727048734_

This test parses STDERR looking for the right values. As such, it is sensitive to other bits of the code spewing garbage into STDERR at just the wrong time. Usually this indicates a bug elsewhere in the code (as was the case in #3558), but unfortunately the test as it is currently constructed doesn't give the full stderr output - it tries to truncate it to make it more readable, but in the process it seems (in this case) to be truncating the useful information.

First step will be to try and improve the diagnostics in the existing test. Hopefully then we can capture enough information to find out what the root cause is.

**Comment by kriegfrj** [comment]
@bjhargrave , has this error happened again recently? Now that #4415 has been merged it should produce more useful diagnostics when it happens so I can debug the root cause.

It would be interesting if this stopped when you disabled the testOSGi task. Perhaps stray stderr output from that test failure was interfering with the other test somehow?

**Comment by bjhargrave** [comment]
> has this error happened again recently?

I have not seen it since the change to capture more diagnostics. I'll keep my eye open.



> It would be interesting if this stopped when you disabled the testOSGi task. Perhaps stray stderr output from that test failure was interfering with the other test somehow?

I would be shocked if this were the case. They are two distinct gradle tasks so I don't seen any real way the outputs of the two gradle tasks could interleave.

**Comment by kriegfrj** [comment]
> > has this error happened again recently?
> 
> I have not seen it since the change to capture more diagnostics. I'll keep my eye open.
> 

Anything?

> > It would be interesting if this stopped when you disabled the testOSGi task. Perhaps stray stderr output from that test failure was interfering with the other test somehow?
> 
> I would be shocked if this were the case. They are two distinct gradle tasks so I don't seen any real way the outputs of the two gradle tasks could interleave.

I concur... hence why I said it would be "interesting" (to be fair, perhaps "interesting" would be a bit of an understatement...).

**Comment by bjhargrave** [comment]
Lets close for now. We can reopen if this issue rears its head again.
