### ISSUE TITLE
Missing service capability when using component factory

### ISSUE THREAD

**Issue by cdelg-ct** [bndtools/bnd#4429]
I have upgraded bnd from 5.1.2 to 5.2.0, in 5.1.2 when a bundle contains a component factory (using DS Component annotation) the generated manifest was:

```
osgi.service;objectClass:List<String>="my.factory.Component"
```
and I used to add `osgi.service;objectClass="org.osgi.service.component.ComponentFactory";effective:=active` manually to avoid missing requirement when resolving.
Now with 5.2.0, I automatically get:
```
osgi.service;objectClass:List<String>="org.osgi.service.component.ComponentFactory";component.factory="my.factory.id"
```
so I suppose I have to add `osgi.service;objectClass:List<String>="my.factory.Component"` manually. Am I right?

**Comment by rotty3000** [comment]
I guess you might be right. IIUC you a saying that at least part of this is a regression?

**Comment by cdelg-ct** [comment]
It would be nice if both capabilities were generated, no?

**Comment by bjhargrave** [comment]
This change is intended to more properly support component factories. See https://github.com/bndtools/bnd/pull/4252 and the change is described in the release notes https://github.com/bndtools/bnd/wiki/Changes-in-5.2.0#bnd.

> It would be nice if both capabilities were generated, no?

Well DS will register the component factory (once satisfied). But it is not clear the registered ComponentFactory service will ever be called to register the produced service. So I am not sure it is good for Bnd to also emit a capability for that service. As you note, you can add that capability yourself.

**Comment by cdelg-ct** [comment]
From the spec I see:

> The Service Namespace is intended to be used for:
> * Preventing a bundle from resolving if there is not at least one bundle that potentially can register a specific service

The **potentially** can refer to component factory creating an instance, no?

> But it is not clear the registered ComponentFactory service will ever be called to register the produced service.
I don't understand your point, why a component factory no registering an instance isn't treat like a missing configuration for which a `osgi.service` capability is generated?

**Comment by bjhargrave** [comment]
DS will register the ComponentFactory service. But DS will never call the ComponentFactory service to make a component. Some other bundle must do that. So it is possible that wont ever happen/

Also, the ComponentFactory may generate components which are not services.

I can make a PR to also emit the service capability for the component instances of a factory component if the factory component instances are services.
