### ISSUE TITLE
Snapshot version with -snaptshot instruction will result in export-package versions with snaptshot qualifier

### ISSUE THREAD

**Issue by swimmesberger** [bndtools/bnd#4432]
When using BND in combination with a gradle project which releases to maven using the default gradle maven publish plugins and therefore using the maven versioning scheme (e.g. 3.4.1-SNAPSHOT) in combination with the BND -snaptshot instruction will result in 3.4.1.SNAPSHOT export-package versions.

E.g. when my project is using the version 1.0.0-SNAPSHOT for maven snapshot releases I want to use 1.0.0.BUILD-${tstamp} as my Bundle-Version. I also want to use 1.0.0.RELEASE as Bundle-Version for release versions. This ensures that 1.0.0.RELEASE is always picked before 1.0.0.BUILD-${tstamp} in OSGi. The issue is in the SNAPSHOT release path here I use the "-snapshot" instruction to convert my project version 1.0.0-SNAPSHOT into 1.0.0.BUILD-${tstamp} for BND like so:
"-snapshot: BUILD-${tstamp}"

BND is then generating a MANIFEST.MF with the correct Bundle-Version header:
Bundle-Version: 1.0.0.BUILD-202011261100

But it is also generating Export-Package attributes like so:
Export-Package: at.swimmesberger;version="1.0.0.SNAPSHOT"

The reason for that is that processing the -snapshot instruction is done after processing the export-package instruction.

But what we really want in this case is a export-package attribute like so:
Export-Package: at.swimmesberger;version="1.0.0"
or so:
Export-Package: at.swimmesberger;version="1.0.0.BUILD-202011261100"

The reason for BND to use "SNAPSHOT" as the version qualifier for the Export-Package attribute is that when cleanupVersion is called for the Export-Package attribute the project version 1.0.0-SNAPSHOT is passed, which is a correct maven version but not a valid OSGi version, therefore this regex check is evaluating to false https://github.com/bndtools/bnd/blob/a00db24d6526bbacd2d81700de2c3c9cb8e5001a/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L486

When this regex check evaluates to false the qualifier is not removed from the Export-Package version attribute. I would expect that maven qualifiers like "-SNAPSHOT" are also removed.

Example Project:
https://github.com/swimmesberger/bnd-snapshot-test

**Comment by rotty3000** [comment]
@swimmesberger  If you show me how the packages are exported I can give you the simplest change required that will solve this.

Normally package version is specified at the point of export. When it is not you end up with a fallback behaviour which is what you are seeing. i.e. I do not believe this is a bug, but let's work through it first :)

**Comment by swimmesberger** [comment]
The project does not specify (see the test project attached in the issue) a specific export - it uses a wildcard export: "Export-Package: *". We encountered the issue when I was helping the spring guys over at project reactor getting BND to work with the new versioning scheme. In the project they don't really want to spend that much time thinking about OSGi specifics instead they want that BND does the heavy lifting for them to get their libraries OSGi ready for those using them in OSGi environments (like we do). I recommend the "-snapshot" instructions but in this specific use-case the instruction didn't really work out for them because of the behavior mentioned above. I think that people finding that instruction are kind of confused why BND is generating "X.X.X.SNAPSHOT" version attributes for those packages when using the instruction.
A exported package with a SNAPSHOT qualifier for SNAPSHOT releases is most of the time not the thing you want. What you want is packages with a version without a qualifier but a Bundle version with e.g. the current timestamp like what we did with the "-snapshot: BUILD-${tstamp}" instruction.

I think handling that case would make BND easier to use for maven/gradle projects/libraries where OSGi is not a first-class citizen.

**Comment by rotty3000** [comment]
ah, you should not handle it this way. That's the cause of your issues :)

Two points:

- `Export-Package: *` is not doing exactly what you think it should be. To be very clear you should rather use: `-exportcontents: *`
- Don't let package version rely on the last fallback that bnd has which means you should at least specify a policy or a default version mask or something that produces something you are happy with

Combining the two into the simplest solution is a configuration like:

`-exportcontents: *;version=${version;${Bundle-Version};===}`

Can you try this and see what you get?

**Comment by swimmesberger** [comment]
I mean we do not really use Export-Package: * but something like reactor.core.* (export all packages starting with this package name which should be every package of this library)

I never really understood why one should use "-exportcontents" for exporting packages - but I have adapted and tried following instruction:
`-exportcontents: *;version=${versionmask;===;${Bundle-Version}}`
but that does not work too because at this point ${Bundle-Version} also resolves to "1.0.0-SNAPSHOT" which is an invalid OSGi version which results in:
`
error  : Invalid syntax for version: 1.0.0-SNAPSHOT, for cmd: versionmask, arguments; [versionmask, ===, 1.0.0-SNAPSHOT]error  : No name before '=' sign for attribute
`
In this case "-snapshot" is again resolved later in the stage otherwise the version would be something like "1.0.0.BUILD-202011261600" which would be a valid OSGi version.

**Comment by rotty3000** [comment]
I'm not sure how bnd is ending up with a non-OSGi compatible version in Bundle-Version. I don't think it will ever do that on it's own. However, you could try using the `${version_cleanup}` macro to convert from maven form to osgi form and then mask it.

**Comment by rotty3000** [comment]
also, you don't need `${versionmask}` so try

`-exportcontents: reactor.core.*;version=${version;===;${version_cleanup;${Bundle-Version}}}`

**Comment by swimmesberger** [comment]
As far as I understand the "-snapshot" instruction according to the doc: https://bnd.bndtools.org/instructions/snapshot.html

"When the bundle version’s qualifier equals “SNAPSHOT” or ends with “-SNAPSHOT”, the STRING value of the -snapshot instruction is substituted for “SNAPSHOT”. The STRING value of the empty string will remove the qualifier if it equals “SNAPSHOT” or will remove “-SNAPSHOT” from the end of the qualifier."

Therefore I set the Bundle-Version to my gradle project version which would be "1.0.0-SNAPSHOT"
Therefore I have explicitly set "Bundle-Version" to "1.0.0-SNAPTSHOT"
So I define a "-snaptshot" instruction to get rid of the incompatible version:
`-snapshot: BUILD-${tstamp}`

Now BND replaces the Bundle-Version "1.0.0-SNAPSHOT" with "1.0.0.BUILD-202011261600" somewhere in the processing stages. So the resulting MENIFEST.MF contains Bundle-Version: 1.0.0.BUILD-202011261600 but at the point of processing the exports BND still thinkgs the Bundle-Version is "1.0.0-SNAPTSHOT" which results in the issue I have.

**Comment by swimmesberger** [comment]
The version with "version_cleanup" works but that is kind of besides the point. In my opinion doing the version processing in gradle is still cleaner than decrypting those BND macros so we use that for now but I'm still concerned about the default behavior we get in this situation. 

Offering a instruction like  "-snapshot" should be thought through and should result in sane behavior. According to the documentation people would assume that using that instruction gets rid of the maven "SNAPSHOT" version issue people have when publishing SNAPSHOT releases. Offering a "hotfix" by applying all kinds of processing to get it somehow to work with packages too is not really user friendly. In my opinion the plugin has more than enough information at this point to know what it should do in this situation. Therefore I propose that the "-snapshot" instruction documentation is updated to reflect that it's has no effect on the Export-Package version or that the "-snapshot" version interpolation is done before package exports are calculated not after.

**Comment by rotty3000** [comment]
> Therefore I have explicitly set "Bundle-Version" to "1.0.0-SNAPSHOT"
I am saying that you should _not_ do that. BND only ever expects a valid version in Bundle-Version. IF you must set it this way, as you said, pre-process it in gradle before giving it to bnd (via Bundle-Version). in fact if you simply don't pass bnd a version at all, and just set the gradle `project.version` property, bnd should do the right thing with it.

**Comment by swimmesberger** [comment]
But why does the "-snaptshot" instruction support it according to the documentation (https://bnd.bndtools.org/instructions/snapshot.html) when we should not do that? 

> When the bundle version’s qualifier equals “SNAPSHOT” **or ends with “-SNAPSHOT**”

We can't simply use the project.version because the version we use for the project and maven is a different OSGi incompatible version therefore we have to use a different version for OSGi.

**Comment by rotty3000** [comment]
bnd plugins know how to mangle the version when it obtains it from the build plugins (in both maven and gradle), but if you pass it explicitly it believes that you have overridden that behaviour. Would you mind trying it and let me know what the error is if any?

**Comment by swimmesberger** [comment]
The version contains the year now so it looks like something along this lines:
Snapshot:
2020.1.0-SNAPSHOT
2020.1.1-SNAPSHOT
2020.2.0-SNAPSHOT
Release:
2020.1.0
2020.1.1
2020.2.0

In the maven/gradle world the ordering would be correct because maven treats "-SNAPSHOT" version differently.
In the OSGi world this would mean the snapshot version (qualifier) has an higher version than the version without a qualifier which is not the ordering we want. Therefore we used following versions in OSGi:
Snapshot:
2020.1.0.BUILD-202011261600
2020.1.1.BUILD-202011261600
2020.2.0.BUILD-202011261600
Release:
2020.1.0.RELEASE
2020.1.1.RELEASE
2020.2.0.RELEASE

to enforce that release versions are always "higher" than snapshot versions (qualifier lexical order).

Therefore we were forced to define a custom Bundle-Version were we simply wanted to say to BND:
"This is our version you can use - do everything as before except that the "-SNAPTSHOT" qualifier should be replaced with BUILD-${tstamp}"

**Comment by rotty3000** [comment]
I understand, but if you need to give bnd a version rather than let it calculate it, it _must_ be a valid OSGi version, therefore when you set the Bundle-Version you have to at least do something like: `Bundle-Version: ${version_cleanup;${the_version}}`
here's an example in the wild: https://github.com/apache/tomcat/blob/master/res/bnd/build-defaults.bnd#L16

**Comment by swimmesberger** [comment]
>  it must be a valid OSGi version
Not always as it seems because the following will produce a valid MANIFEST.MF

`
Bundle-Version: 1.0.0-SNAPSHOT (invalid OSGi Version!)
-snapshot: BUILD-${tstamp}
`

will produce following MANIFEST.MF:
Bundle-Version: 1.0.0.BUILD-202011261800

So I have passed a invalid Bundle-Version to BND and got no validation error or anything else and got a valid OSGi Bundle-Version out. That's the thing I'm not understanding when you say "you must provide a valid OSGi version" but on the other hand not providing a valid OSGi version does not result in an validation/bnd error instead there is an instruction that explicitly supports it to turn a invalid provided Bundle-Version into a valid Bundle-Version. The same things works even if no gradle/maven/bndtools or whatever is involved this is 100% pure BND processing.

**Comment by swimmesberger** [comment]
Even when no "-snapshot" instruction is used BND will turn explicitly defined versions like:
`Bundle-Version: 1.0.0-SNAPSHOT`

into something valid:
`Bundle-Version: 1.0.0.SNAPSHOT`

so saying providing OSGi incompatible versions to BND is not supported is wrong when clearly it is supported in some way.

**Comment by rotty3000** [comment]
I don't know what more I can say. We'll have to wait for @bjhargrave to chine in. Sorry I couldn't be of any assistance.

**Comment by swimmesberger** [comment]
@rotty3000 no problem - thanks for your help anyway I have learned a couple of things 😊 
It is no big issue as I have said we have found a workaround but it just seemed inconsistent in my eyes therefore I wanted to have it discussed/documented here 🙂

**Comment by bjhargrave** [comment]
I'm late to the party and got lost in all the comments. But `-snapshot` is for `Bundle-Version` which is not a semantic version.

Package which are exported should be semantically versioned by human developers (with help from baselining in Bnd). Using the bundle version as the exported package version is supported by Bnd as a hack but no one should really do that in properly professional software.

So I do not see any change to be made to Bnd here. You seem to have figured out how to hack the bundle version as your export package versions in a way that meets your needs.

**Comment by swimmesberger** [comment]
>  Using the bundle version as the exported package version is supported by Bnd as a hack but no one should really do that in properly professional software.
That might be true for us who develop applications based on OSGi but there are many libraries in the java ecosystem we in the OSGi ecosystem want to use but where OSGi is not number 1 priority. For those libraries a way to generate a sane OSGi ready MANIFEST.MF without thinking much about those details is good for us in the OSGi world because we have more possibilities. We might not have the versioning guarantees we have when using a properly versioned bundle but that is a sacrifice one can make to still have the possibility to use them.

**Comment by bjhargrave** [comment]
> For those libraries a way to generate a sane OSGi ready MANIFEST.MF

I guess we can debate whether it _is_ sane to put a non-semantic, monotonically increasing version number on an exported package. Any bundle which imports those packages will import them with a version range (Bnd default behavior) which does not mean anything since the export version has no semantic meaning. It is not much better than if the packages were exported with a constant version number for all bundle versions.

If the developers are not semantically versioning the exported packages, then all importers are at risk since they have no idea if they will work at runtime _unless_ they import at the exact version (`[v,v]`) of the exported package. But this is very brittle (but nor far from maven behavior).

**Comment by swimmesberger** [comment]
Sure it might not be sane in the sense of a perfectly find OSGi product but in our case we want to use the whole java ecosystem and we don't want to lock ourself into a ecosystem where only perfectly fine OSGi libraries are allowed. We review every library we use before updating anyway and we also do not support loading external bundles at runtime we have not approved. Therefore the exported package version is not that relevant for us for those non OSGi libraries. What is relevant is if the libraries publish their libraries with OSGi metadata or not and getting them to include OSGi metadata is difficult enough requiring them to carefully version their packages (which is only required for OSGi) would mean that they would drop OSGi support completely because maintaining that doesn't really worth it from their perspective.
