### ISSUE TITLE
Workspace with only errors that warn that the project is not build

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4434]
I've seen several situations where a whole workspace is ok, but the error from bnd that it has not been build is still there.

Do we need that error?

**Comment by kriegfrj** [comment]
I think a more important question is: if the whole workspace is ok, why hasn't Bndtools built the project(s)? Or did you have automatic building turned off?

**Comment by pkriens** [comment]
No, automatic build was on. I think the problem is that a change in the -buildpath is done but does not clear the error somehow. I could make it consistently but had no time to setup the debugger.

**Comment by kriegfrj** [comment]
I've noticed a couple of similar weird things ruth stuff not automatically building when i thought it should. Possibly related to #4404?
