### ISSUE TITLE
Usage of transparent 'Pin project' icon

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#4443]
The latest snapshot version of Bndtools comprises the new functionality to pin a project. I believe it would be better to use a transparent icon instead. Currently there is the possibility for users to opt in Dark Theme and the current icon looks a bit strange.

<img width="455" alt="Screenshot 2020-12-08 at 13 09 48" src="https://user-images.githubusercontent.com/13380182/101482259-bc0ef680-3956-11eb-8434-87ae8b0ed47a.png">

**Comment by pkriens** [comment]
I always felt there was something wrong with dark theme users :-)

I am awful with these icons .... Any volunteers? The refresh icon could also be better.

**Comment by amitjoy** [comment]
If I get time, I will try to update them tomorrow. But first, I need to locate the bundles where they are stored 😄
