### ISSUE TITLE
Inconsistent resolve between bnd-resolver-maven-plugin and bnd-testing-maven-plugin v5.2.0

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#4460]
The resolution result produced by the bnd-resolver-maven-plugin is rejected by the bnd-testing-maven-plugin (with resolve=true and failOnChanges=true). Both are version 5.2.0. The calculated runbundles differ from the existing runbundles only in terms of ordering.

First I did a resolve as follows:

    mvn -Dbnd.export.skip -DskipTests -Dmaven.javadoc.skip \
      -am -pl eclipsehelp.customization.bundle-test \
      package bnd-resolver:resolve

Then I ran a test:

    mvn clean verify -am -pl eclipsehelp.customization.bundle-test

The error output of the testing plugin is as follows. Note that I have reformatted the output for readability, and anonymized the name of my client to "acme":

```
[INFO] --- bnd-testing-maven-plugin:5.2.0:testing (default) @ eclipsehelp.customization.bundle-test ---
[INFO] Matching glob *
[ERROR] Error   : Fail on changes set to true (--xchange,-x) and there are changes
[ERROR] Error   :    Existing runbundles   [ch.qos.logback.classic;version='[1.2.3,1.2.4)',\
    ch.qos.logback.core;version='[1.2.3,1.2.4)',\
    com.acme.tools.sdk.eclipsehelp.customization;version='[0.0.9,0.0.10)',\
    com.acme.tools.sdk.eclipsehelp.customization.bundle-test;version='[0.0.9,0.0.10)',\
    com.acme.tools.sdk.model.loader;version='[1.1.1,1.1.2)',\
    com.acme.tools.sdk.model.system;version='[2.3.0,2.3.1)',\
    com.acme.tools.sdk.utils;version='[1.4.0,1.4.1)',\
    com.ibm.icu;version='[56.1.0,56.1.1)',\
    org.apache.commons.logging;version='[1.2.0,1.2.1)',\
    org.apache.felix.configadmin;version='[1.9.16,1.9.17)',\
    org.apache.felix.fileinstall;version='[3.6.6,3.6.7)',\
    org.apache.felix.scr;version='[2.1.16,2.1.17)',\
    org.apache.pdfbox;version='[2.0.20,2.0.21)',\
    org.apache.pdfbox.fontbox;version='[2.0.20,2.0.21)',\
    org.apache.servicemix.bundles.junit;version='[4.12.0,4.12.1)',\
    org.eclipse.core.contenttype;version='[3.7.800,3.7.801)',\
    org.eclipse.core.expressions;version='[3.7.0,3.7.1)',\
    org.eclipse.core.runtime;version='[3.18.0,3.18.1)',\
    org.eclipse.equinox.app;version='[1.5.0,1.5.1)',\
    org.eclipse.help;version='[3.8.0,3.8.1)',\
    org.eclipse.persistence.antlr;version='[3.2.0,3.2.1)',\
    org.eclipse.persistence.asm;version='[3.3.1,3.3.2)',\
    org.eclipse.persistence.core;version='[2.5.2,2.5.3)',\
    org.eclipse.persistence.moxy;version='[2.5.2,2.5.3)',\
    org.osgi.util.function;version='[1.1.0,1.1.1)',\
    org.osgi.util.promise;version='[1.1.0,1.1.1)',\
    slf4j.api;version='[1.7.26,1.7.27)',\
    org.eclipse.core.jobs;version='[3.10.1000,3.10.1001)',\
    org.eclipse.equinox.common;version='[3.14.0,3.14.1)',\
    org.eclipse.equinox.preferences;version='[3.8.100,3.8.101)',\
    org.eclipse.equinox.registry;version='[3.10.0,3.10.1)']
[ERROR] Error   :    Calculated runbundles [ch.qos.logback.classic;version='[1.2.3,1.2.4)',\
    ch.qos.logback.core;version='[1.2.3,1.2.4)',\
    com.acme.tools.sdk.eclipsehelp.customization;version='[0.0.9,0.0.10)',\
    com.acme.tools.sdk.eclipsehelp.customization.bundle-test;version='[0.0.9,0.0.10)',\
    com.acme.tools.sdk.model.loader;version='[1.1.1,1.1.2)',\
    com.acme.tools.sdk.model.system;version='[2.3.0,2.3.1)',\
    com.acme.tools.sdk.utils;version='[1.4.0,1.4.1)',\
    com.ibm.icu;version='[56.1.0,56.1.1)',\
    org.apache.commons.logging;version='[1.2.0,1.2.1)',\
    org.apache.felix.configadmin;version='[1.9.16,1.9.17)',\
    org.apache.felix.fileinstall;version='[3.6.6,3.6.7)',\
    org.apache.felix.scr;version='[2.1.16,2.1.17)',\
    org.apache.pdfbox;version='[2.0.20,2.0.21)',\
    org.apache.pdfbox.fontbox;version='[2.0.20,2.0.21)',\
    org.apache.servicemix.bundles.junit;version='[4.12.0,4.12.1)',\
    org.eclipse.core.contenttype;version='[3.7.800,3.7.801)',\
    org.eclipse.core.expressions;version='[3.7.0,3.7.1)',\
    org.eclipse.core.jobs;version='[3.10.1000,3.10.1001)',\
    org.eclipse.core.runtime;version='[3.18.0,3.18.1)',\
    org.eclipse.equinox.app;version='[1.5.0,1.5.1)',\
    org.eclipse.equinox.common;version='[3.14.0,3.14.1)',\
    org.eclipse.equinox.preferences;version='[3.8.100,3.8.101)',\
    org.eclipse.equinox.registry;version='[3.10.0,3.10.1)',\
    org.eclipse.help;version='[3.8.0,3.8.1)',\
    org.eclipse.persistence.antlr;version='[3.2.0,3.2.1)',\
    org.eclipse.persistence.asm;version='[3.3.1,3.3.2)',\
    org.eclipse.persistence.core;version='[2.5.2,2.5.3)',\
    org.eclipse.persistence.moxy;version='[2.5.2,2.5.3)',\
    org.osgi.util.function;version='[1.1.0,1.1.1)',\
    org.osgi.util.promise;version='[1.1.0,1.1.1)',\
    slf4j.api;version='[1.7.26,1.7.27)']
```

Putting these side-by-side we can see that the testing plugin is *only* complaining about ordering. All the same bundles are present with the exame same version ranges. However it looks like the resolver plugin has sorted the bundles alphanumerically, whereas the testing plugin wants us to move some of the Eclipse bundles (org.eclipse.core.jobs and org.eclipse.equinox.* below slf4j.api).

This is really important to get right because users should not have to manually edit runbundles lists, so they need to rely on the results of the resolver plugin producing output that can be consumed by the rest of our toolsuite.

Note that there is no possibility of the inputs changing between these two jobs. The test job was executed immediately after the resolve job, and there are no -SNAPSHOT dependencies into Maven Central.

It seems that a simple fix here would be to relax the validation performed by the testing plugin so that ordering is not significant.

**Comment by bjhargrave** [comment]
There is a bug in 5.2.0 (https://github.com/bndtools/bnd/commit/0c53e138b170b9578a241a9b73242a37aff95e38#diff-1d2232fa30efb7723be4dab49355752815f9f84753c8151f72dfe3d7cd5e8f87) in which the displayed existing runbundles list in this error message is wrong.

Try again with the latest 5.3.0-SNAPSHOT to get the proper output message.

**Comment by njbartlett** [comment]
Upgrading to 5.3.0-SNAPSHOT produced exactly the same result. I copied it below for reference.

Minor correction: I was reading the existing and calculated the wrong way around. The testing plugin wants the bundles sorted alphanumerically, whereas the resolver plugin produces a list with some Eclipse bundles at the bottom. The effect is the same, and I still think the fix should be to make ordering not significant to the `failOnChanges` check in the testing plugin (and possibly also to implement an alpha sort in the resolver plugin).

```
[INFO] --- bnd-testing-maven-plugin:5.3.0-SNAPSHOT:testing (default) @ eclipsehelp.customization.bundle-test ---
[INFO] Matching glob *
[ERROR] Error   : Fail on changes set to true (--xchange,-x) and there are changes
[ERROR] Error   :    Existing runbundles   [ch.qos.logback.classic;version='[1.2.3,1.2.4)', ch.qos.logback.core;version='[1.2.3,1.2.4)', com.acme.tools.sdk.eclipsehelp.customization;version='[0.0.9,0.0.10)', com.acme.tools.sdk.eclipsehelp.customization.bundle-test;version='[0.0.9,0.0.10)', com.acme.tools.sdk.model.loader;version='[1.1.1,1.1.2)', com.acme.tools.sdk.model.system;version='[2.3.0,2.3.1)', com.acme.tools.sdk.utils;version='[1.4.0,1.4.1)', com.ibm.icu;version='[56.1.0,56.1.1)', org.apache.commons.logging;version='[1.2.0,1.2.1)', org.apache.felix.configadmin;version='[1.9.16,1.9.17)', org.apache.felix.fileinstall;version='[3.6.6,3.6.7)', org.apache.felix.scr;version='[2.1.16,2.1.17)', org.apache.pdfbox;version='[2.0.20,2.0.21)', org.apache.pdfbox.fontbox;version='[2.0.20,2.0.21)', org.apache.servicemix.bundles.junit;version='[4.12.0,4.12.1)', org.eclipse.core.contenttype;version='[3.7.800,3.7.801)', org.eclipse.core.expressions;version='[3.7.0,3.7.1)', org.eclipse.core.runtime;version='[3.18.0,3.18.1)', org.eclipse.equinox.app;version='[1.5.0,1.5.1)', org.eclipse.help;version='[3.8.0,3.8.1)', org.eclipse.persistence.antlr;version='[3.2.0,3.2.1)', org.eclipse.persistence.asm;version='[3.3.1,3.3.2)', org.eclipse.persistence.core;version='[2.5.2,2.5.3)', org.eclipse.persistence.moxy;version='[2.5.2,2.5.3)', org.osgi.util.function;version='[1.1.0,1.1.1)', org.osgi.util.promise;version='[1.1.0,1.1.1)', slf4j.api;version='[1.7.26,1.7.27)', org.eclipse.core.jobs;version='[3.10.1000,3.10.1001)', org.eclipse.equinox.common;version='[3.14.0,3.14.1)', org.eclipse.equinox.preferences;version='[3.8.100,3.8.101)', org.eclipse.equinox.registry;version='[3.10.0,3.10.1)']
[ERROR] Error   :    Calculated runbundles [ch.qos.logback.classic;version='[1.2.3,1.2.4)', ch.qos.logback.core;version='[1.2.3,1.2.4)', com.acme.tools.sdk.eclipsehelp.customization;version='[0.0.9,0.0.10)', com.acme.tools.sdk.eclipsehelp.customization.bundle-test;version='[0.0.9,0.0.10)', com.acme.tools.sdk.model.loader;version='[1.1.1,1.1.2)', com.acme.tools.sdk.model.system;version='[2.3.0,2.3.1)', com.acme.tools.sdk.utils;version='[1.4.0,1.4.1)', com.ibm.icu;version='[56.1.0,56.1.1)', org.apache.commons.logging;version='[1.2.0,1.2.1)', org.apache.felix.configadmin;version='[1.9.16,1.9.17)', org.apache.felix.fileinstall;version='[3.6.6,3.6.7)', org.apache.felix.scr;version='[2.1.16,2.1.17)', org.apache.pdfbox;version='[2.0.20,2.0.21)', org.apache.pdfbox.fontbox;version='[2.0.20,2.0.21)', org.apache.servicemix.bundles.junit;version='[4.12.0,4.12.1)', org.eclipse.core.contenttype;version='[3.7.800,3.7.801)', org.eclipse.core.expressions;version='[3.7.0,3.7.1)', org.eclipse.core.jobs;version='[3.10.1000,3.10.1001)', org.eclipse.core.runtime;version='[3.18.0,3.18.1)', org.eclipse.equinox.app;version='[1.5.0,1.5.1)', org.eclipse.equinox.common;version='[3.14.0,3.14.1)', org.eclipse.equinox.preferences;version='[3.8.100,3.8.101)', org.eclipse.equinox.registry;version='[3.10.0,3.10.1)', org.eclipse.help;version='[3.8.0,3.8.1)', org.eclipse.persistence.antlr;version='[3.2.0,3.2.1)', org.eclipse.persistence.asm;version='[3.3.1,3.3.2)', org.eclipse.persistence.core;version='[2.5.2,2.5.3)', org.eclipse.persistence.moxy;version='[2.5.2,2.5.3)', org.osgi.util.function;version='[1.1.0,1.1.1)', org.osgi.util.promise;version='[1.1.0,1.1.1)', slf4j.api;version='[1.7.26,1.7.27)']
```

NB I re-resolves with the bnd-resolver-maven-plugin 5.3.0-SNAPSHOT before running this test.

**Comment by njbartlett** [comment]
@bjhargrave If you agree with my suggestion to make the ordering not significant then I can work on a PR.

**Comment by rotty3000** [comment]
We've come to adopt a habit to add this configuration to bndrun files in order to get consistent resolution order:
```
-runstartlevel: \
	order=sortbynameversion,\
	begin=-1
```
Does that solve your issue?

Secondly, why re-resolve an already resolved solution? The fact that other plugins besides bnd-resolver-maven-plugin can do a resolve is really legacy (to be deprecated) and you shouldn't really use that. The idea being that each plugin should have do one thing and do it well.

**Comment by bjhargrave** [comment]
I think the way to address ordering is for the bndrun file to set the ordering:

https://github.com/osgi/osgi-test/blob/e2b5b4dc63656c00d0b83d7646ad3bd9d7ff352f/org.osgi.test.junit5/test.bndrun#L41-L44

```properties
# This will help us keep -runbundles sorted
-runstartlevel: \
    order=sortbynameversion,\
    begin=-1
```

If the ordering changes in a resolve, that may be significant (since sometimes bundles are not well behaved with respect to start ordering). So I am not sure ignoring ordering in the runbundles before/after comparison is always safe.

The best choice is simply for the bndrun file to assert the ordering it wants as the example above does.

**Comment by njbartlett** [comment]
Thanks, I wasn't aware of that directive. I confirm that when I set that my resolution works as expected.

Still, this should have a default value, and it  should be the same default between the resolver plugin and the testing plugin. It doesn't make sense for the resolver plugin to produce output that cannot be validated by the testing plugin, without any other change to the bndrun file, whatever this directive says.

**Comment by njbartlett** [comment]
> Secondly, why re-resolve an already resolved solution? The fact that other plugins besides bnd-resolver-maven-plugin can do a resolve is really legacy (to be deprecated) and you shouldn't really use that. The idea being that each plugin should have do one thing and do it well.

I disagree: the purpose of resolving in the testing plugin is to guard against unexpected dependencies sneaking in. The purpose of resolving with the resolver plugin is to consciously update the runbundles list when you *know* that you need a new dependency, or if you have bumped the bundle version.

**Comment by rotty3000** [comment]
> I disagree: the purpose of resolving in the testing plugin is to guard against unexpected dependencies sneaking in. The purpose of resolving with the resolver plugin is to consciously update the runbundles list when you know that you need a new dependency, or if you have bumped the bundle version.

I disagree with your disagreement ;) 

Reason being that the testing plugin is for running tests in an osgi framework. Not to resolve. We usually resolve continuously with the bnd-resolver-maven-plugin anyway (at least that's the model I choose to adopt and promote) and so why do work twice?

Furthermore the integration in M2E does NOT recognize the resolver configuration in any other plugins besides the bnd-resolver-maven-plugin so you have the possibility of things going out of sync if you configure resolution in any other plugins and expect for those to be coordinated.

**Comment by njbartlett** [comment]
I see your disagreement and disregard it as irrelevant ;-)

The testing plugin has always supported resolution, so you can't take that away without breaking backwards compatibility. Like it or not, we have multiple plugins involved in resolution, so they should at least work consistently.

The bnd-resolver-maven-plugin isn't intended for automatic resolution in every build. As the README states: "Since the resolve operation is not associated with any maven build phase, it must in invoked manually".

If you don't test resolution with either the testing-plugin or the export-plugin, that means you have no guard against unexpected dependencies creeping in. If you don't find that check valuable, that's fine, but I do.

I didn't really understand your final paragraph but I'm not interested in M2E at the moment, just the Maven plugins themselves.

**Comment by bjhargrave** [comment]
Closing as there is the ability to control the ordering by -runstartlevel.
