### ISSUE TITLE
BND build fails every 2nd time

### ISSUE THREAD

**Issue by mgerlich** [bndtools/bnd#4461]
We're using bndtools in version 5.3.0-SNAPSHOT on our Jenkins CI with Gradle version 5.6.2. We're using a SNAPSHOT version here because of additional contributions from the Gecko BND people (Jürgen Albert).

Almost every second build fails on a BND compileJava task with an NPE
>Execution failed for task ':my.project.bsn:compileJava'.
 [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.NullPointerException (no error message)

I've replaced our bundleId with 'my.project.bsn' and uploaded a snippet from the whole log at [PasteBin](https://pastebin.com/wDMT343m). As recommended by Gradle, I performed a rerun with --debug and--stacktrace. The snippet is from that run.

**Comment by bjhargrave** [comment]
Here is the NPE

```
14:17:04.049 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NullPointerException
14:17:04.049 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at aQute.bnd.osgi.Instruction.getMatcher(Instruction.java:269)
14:17:04.050 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at aQute.bnd.osgi.Instruction.finds(Instruction.java:298)
14:17:04.050 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at aQute.bnd.osgi.Instructions.finder(Instructions.java:265)
14:17:04.050 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at aQute.bnd.osgi.Processor.doFixup(Processor.java:1881)
14:17:04.050 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at aQute.bnd.osgi.Processor.fixupMessages(Processor.java:1875)
14:17:04.050 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at aQute.bnd.osgi.Processor.getErrors(Processor.java:467)
14:17:04.050 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at aQute.bnd.osgi.Processor.getInfo(Processor.java:302)
14:17:04.050 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at aQute.bnd.gradle.BndPlugin.checkProjectErrors(BndPlugin.groovy:606)
```

I can only suspect there is some thread-safety issue in the `pattern()` method around the reading and writing of the pattern field. I will make a PR to improve the thread-safety of the `pattern()` method's access to the `pattern` field.
