### ISSUE TITLE
bnd does not build on apple silicon, and doesn't run from cli

### ISSUE THREAD

**Issue by mcginkel** [bndtools/bnd#4466]
Using the cli version gives errors exporting or running bundles via Gradle or cli
 
example and error:
> ./gradlew run.shell
warning: No translation found for macro: native_capability
error  : null, for cmd: native_capability, arguments; [native_capability]

The processors architecture is not recognised as this is apple's arm architecture.
bnd version: 5.2.0 and 5.3.0-DEV (master)
java version: 11
os: macOS 11.1, M1/ARM processor

(I have debugged, forked and fixed this, and will raise a PR with a fix asap)

**Comment by bjhargrave** [comment]
My M1 Macbook Air says:

```shell
➜  ~ arch
arm64
➜  ~ java -version                                              
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+1015-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+1015-CA (build 11.0.9.1+1-LTS, mixed mode)
➜  ~ java -XshowSettings:properties -version 2>&1 | grep os.arch
    os.arch = aarch64
```

https://docs.osgi.org/reference/osnames.html does not include `aarch64` or `arm64` and so Bnd's `OSInformation` does not either. We need to add `aarch64` with an `arm64` alias as a processor family to both OSGi and Bnd.

```diff
diff --git a/biz.aQute.bndlib/src/aQute/bnd/osgi/OSInformation.java b/biz.aQute.bndlib/src/aQute/bnd/osgi/OSInformation.java
index c9774130a..166f720f7 100644
--- a/biz.aQute.bndlib/src/aQute/bnd/osgi/OSInformation.java
+++ b/biz.aQute.bndlib/src/aQute/bnd/osgi/OSInformation.java
@@ -33,6 +33,8 @@ public class OSInformation {
                        "x86", "pentium", "i386", "i486", "i586", "i686"
                }, new String[] {
                        "68k"
+               }, new String[] {
+                       "aarch64", "arm64"
                }, new String[] {
                        "ARM"
                }, new String[] {
```

Apple Silicon is little endian but this is not reported in any way by the `arch` command or the Java `os.arch` system property.

**Comment by mcginkel** [comment]
You are quick to respond...
I tried to solve it bij adding an alias to ARM_le, which works. Is that a good way as well? (I was still working on a proper unit test..)

		}, new String[] {
			"x86", "pentium", "i386", "i486", "i586", "i686"
		}, new String[] {
			"68k"
		}, new String[] {
			"ARM"
		}, new String[] {
			"ARM_be"
		}, new String[] {
			"ARM_le", "aarch64"
		}, new String[] {
			"Alpha"
		}, new String[] {
			"ia64n"

**Comment by bjhargrave** [comment]
> I tried to solve it bij adding an alias to ARM_le

I think we need a new `aarch64` entry as I suggested. `ARM` is not 64-bit. It is for the 32-bit instruction set. `aarch64` is the proper name for the ARM 64-bit instruction set. https://en.wikipedia.org/wiki/AArch64. `arm64` is a useful alias.

**Comment by mcginkel** [comment]
Ok, let me do that and see if I get it running.

**Comment by mcginkel** [comment]
That works well, I can run my own projects again with that build, but I get errors in the unitest. I will try to highlite them.

Any ideas if this is fixable at the moment? I don't mind spending the time, but it is far out of my comfort zone. I expect that I need to wait until the java implementation/jwt is ready. It only effects the test that use a GUI.


> Task :bndtools.core.test:test NO-SOURCE
 
test cases filter set to null
run unresolved true
using /Users/kees/Development/bnd/bndtools.core.test/generated/test-reports/testOSGi, path: /Users/kees/Development/bnd/bndtools.core.test/generated/test-reports/testOSGi
automatic testing of all bundles with Test-Cases header
Opening BundleTracker for finding test bundles
starting queue


java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
	/private/var/folders/67/yjqxr89j6554mg2dp2h87j6w0000gn/T/osgi.17437790730352196272.fw/org.eclipse.osgi/245/0/.cp/libswt-cocoa-4922r32.jnilib: dlopen(/private/var/folders/67/yjqxr89j6554mg2dp2h87j6w0000gn/T/osgi.17437790730352196272.fw/org.eclipse.osgi/245/0/.cp/libswt-cocoa-4922r32.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/67/yjqxr89j6554mg2dp2h87j6w0000gn/T/osgi.17437790730352196272.fw/org.eclipse.osgi/245/0/.cp/libswt-cocoa-4922r32.jnilib: mach-o, but wrong architecture
	/private/var/folders/67/yjqxr89j6554mg2dp2h87j6w0000gn/T/osgi.17437790730352196272.fw/org.eclipse.osgi/245/0/.cp/libswt-cocoa-4922r32.jnilib: mach-o, but wrong architecture
	no swt-cocoa in java.library.path: [/Users/kees/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	/Users/kees/.swt/lib/macosx/aarch64/libswt-cocoa-4922r32.jnilib: dlopen(/Users/kees/.swt/lib/macosx/aarch64/libswt-cocoa-4922r32.jnilib, 1): no suitable image found.  Did find:
	/Users/kees/.swt/lib/macosx/aarch64/libswt-cocoa-4922r32.jnilib: mach-o, but wrong architecture
	/Users/kees/.swt/lib/macosx/aarch64/libswt-cocoa-4922r32.jnilib: mach-o, but wrong architecture
	Can't load library: /Users/kees/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:329)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:241)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:106)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:741)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:163)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:185)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:128)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at bndtools.core.test.launch.HeadlessLauncher.lambda$launch$0(HeadlessLauncher.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at aQute.launcher.Launcher.launch(Launcher.java:452)
	at aQute.launcher.Launcher.run(Launcher.java:185)
	at aQute.launcher.Launcher.main(Launcher.java:161)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
tests bundle queue interrupted


> Task :bndtools.core.test:testOSGi

error  : Exit code remote process 127: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java -cp /var/folders/67/yjqxr89j6554mg2dp2h87j6w0000gn/T/pre17185843419709822690.jar -Dlauncher.properties=/Users/kees/Development/bnd/bndtools.core.test/generated/tmp/testOSGi/generated/launch3174410224603013933.properties -XstartOnFirstThread -Djava.awt.headless=true -Dorg.eclipse.swt.internal.carbon.smallFonts -ea -Dlauncher.runpath=/Users/kees/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar,/Users/kees/.m2/repository/org/slf4j/slf4j-nop/1.7.25/slf4j-nop-1.7.25.jar,/Users/kees/Development/bnd/cnf/cache/stable/Eclipse-2018-12/org.eclipse.osgi-3.13.200.v20181130-2106.jar,/Users/kees/Development/bnd/biz.aQute.launcher/generated/biz.aQute.launcher.jar aQute.launcher.pre.EmbeddedLauncher

> Task :bndtools.core.test:check

**Comment by njbartlett** [comment]
The paths to those JNILIB files suggest they are compiled for ARM but are you running on a native ARM JVM, or an x86 JVM under Rosetta? I believe that you can't link ARM libraries into an x86 executable or vice versa.

I think we need to ensure that the `OSInformation` class detects the architecture as x86_64 when running under Rosetta?

**Comment by bjhargrave** [comment]
That test, `:bndtools.core.test:testOSGi`, tries to launch an Eclipse instance. I don't think the Eclipse instance being used by the test has SWT libraries for `aarch64`. I am not sure any Eclipse does yet.

Set the env var `BNDTOOLS_CORE_TEST_NOJUNITOSGI` to `true` (`export BNDTOOLS_CORE_TEST_NOJUNITOSGI=true`) before building. This will disable the `:bndtools.core.test:testOSGi` task which we don't run in the CI build anyway.

https://github.com/bndtools/bnd/blob/49a13e35b488e21100ecfb7e157e69f03f3e23cd/.github/workflows/cibuild.yml#L22

**Comment by bjhargrave** [comment]
> I think we need to ensure that the `OSInformation` class detects the architecture as x86_64 when running under Rosetta, even if the physical chip is aarch64.

OSInformation will use what the JVM reports via `os.arch` system property. So a JVM running under Rosetta 2 better report `os.arch=x86_64` otherwise many things will break for native libraries.

**Comment by mcginkel** [comment]
So I did some more tests:
I installed a non arm build of openjdk-java. running a JVM that is not build for ARM under rosetta gives 'x86_64'.

```
 java -XshowSettings:properties -version 2>&1 | grep os.arch
   os.arch = x86_64

```

```
/usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    15.0.1 (x86_64) "Azul Systems, Inc." - "Zulu 15.28.51" /Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home
    11.0.9.1 (arm64) "Azul Systems, Inc." - "Zulu 11.43.1015" /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home


```

Forcing the java11 to run under rosetta does not work as that are probably not universal binaries
```
arch -x86_64 java -XshowSettings:properties -version 2>&1 | grep os.arch
    os.arch = aarch64
```

not sure how to continue from here. Test are running fine now. Will fix the PR comment.
