### ISSUE TITLE
Enhance bnd-baseline-maven-plugin to support immutable releases

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#4473]
I would like to propose the following enhancement to the bnd-baseline-maven-plugin: to (optionally) fail the build when the project is a release version (i.e. not a SNAPSHOT) and the same version exists in the baseline repository.

The motivation for this is that I want to set up a build system in which:

1. Releases are immutable;
2. Release versions may only depend on other releases;
3. OSGi versions are semantically correct.

Requirement 2 can be achieved with the maven-enforcer-plugin and the `requireReleaseDeps` rule. Requirement 3 can be achieved with the bnd-baseline-maven-plugin currently. However, requirement 1 cannot be enforced by any existing Maven plugin or configuration that I have been able to find.

Many organisations already enforce immutability of release repos by configuring their repository server (e.g. Nexus or Artifactory) to disallow overwrites or deletes in release repos. However, configuring this requires administration rights on the repository server, which are not always available to developers or development teams. This is especially true if the server is managed company wide; different teams will have different requirements, and admins will often choose the more permissive option.

If there existed a capability to enforce immutable releases from the Maven build configuration then individual project teams can work according to their preference.

bnd-baseline-maven-plugin is a good place to implement such a check, because it already does most of the work of determining the latest release version and comparing that version against the module being built.

**Comment by bjhargrave** [comment]
Doesn't this mean I cannot checkout the release tag and locally build since I would be building a release that already exists in maven central? 

I am not sure I see the utility in such an option in baselining. Such an option should be in the release plugin. Building an existing release should never be an error. Releasing an existing release is an error which I think will already be caught.

**Comment by njbartlett** [comment]
Hmm yes that is a problem, I will have to think about this a bit more.

Releasing an existing release is not an error in Maven, and there is no option in existing Maven plugins to prevent this. It only becomes an error if you have configured your repository (e.g. Nexus or Artifactory) to disallow overwrites or deletes in release repositories.
