### ISSUE TITLE
bnd-resolver-plugin: Add parameter for inline launch description

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4476]
Currently the Maven plugin only uses external bndrun files (https://github.com/bndtools/bnd/blob/fb81a01eed1a89760d8e32f27b795ecf727cb03f/maven/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/ResolverMojo.java#L104). Similar to `bnd-maven-plugin`s parameter `bnd` (https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin#configuration-parameters) it should support in-pom launch description (which can potentially be inherited).

**Comment by bjhargrave** [comment]
I don't think pom-based bndrun configuration is a good idea. Unlike building a bundle with bnd-maven-plugin, bndrun configuration is used across many Bnd maven plugins. Resolve uses it, test uses it, run uses it. Since I am unaware of any way in a pom to defined configuration which can be used by several plugins, the separate bndrun file is important. It is also important since the Bndtools UI can edit and resolve bndrun files.

**Comment by kwin** [comment]
My use case for inheritance is: Checking several bundles if they resolve against a common baseline of bundles. For the common baseline of bundles I currently use
```
-include ../baseline.bndrun
```

with `baseline.bndrun` having

```
-standalone: ${fileuri;${.}/target/index.xml}
-runfw: org.apache.felix.framework
-runee: JavaSE-1.8
```

I would love to encapsulate the baseline in a dedicated Maven artifact (containing both the repositoy xml as well as the relevant bndrun configuration referencing it. 
Any other idea how to reference such a common base line from Maven coordinates?

**Comment by kwin** [comment]
Also if `bnd-resolver-maven-plugin`, `bnd-run-maven-plugin` and `bnd-testing-maven-plugin` share a common configuration, it would probably make sense to encapsulate all of them in different mojos in the same(!) plugin. That way they could easily share a configuration

**Comment by bjhargrave** [comment]
> Also if `bnd-resolver-maven-plugin`, `bnd-run-maven-plugin` and `bnd-testing-maven-plugin` share a common configuration

They don't share a common maven configuration but can share a common bndrun file.

**Comment by kwin** [comment]
Using external configuration files for parameterizing runs of Maven plugins is kind of an anti-pattern (due to the limited inheritance)

**Comment by bjhargrave** [comment]
> kind of an anti-pattern

Perhaps, but since Bnd supports much more than just maven and Bnd already has bndrun files, the current approach is used.

> My use case for inheritance is

Perhaps @rotty3000 can suggest a better maven configuration story for your use case.

**Comment by rotty3000** [comment]
creating a distro is simple:
- start the "target runtime" (which has all the base bundles you wish)
- install bnd remote agent into the runtime ([here](https://search.maven.org/artifact/biz.aQute.bnd/biz.aQute.remote.agent/5.2.0/jar))
- using bnd cli execute `bnd remote distro <bsn> <[version]>`
- release artifact for posterity

here's an example I did with Karaf a while back https://github.com/rotty3000/demo-live-coding

**Comment by kwin** [comment]
@rotty3000 Thanks a lot for that hint. Is there any Maven tooling support for automatically creating distro's? I do have a list of Maven (bundle) dependencies and some additional hardcoded config. Out of this I would like to continuously create distros (preferably with Maven).

**Comment by bjhargrave** [comment]
Closing.
