### ISSUE TITLE
Please Update infos for bindex

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#4477]
https://github.com/osgi/bindex references that the code moved into BND.

> This repository remains only to point people to the bnd project to find the latest repository indexer work

sadly the link is dead and the bnd homepage also does not provide a hint (or I can't find it) where the indexer/analyses can be found and how it could be used to generate/consume repositories inside an OSGi application.

Maybe it would be a good idea to have a section on the homepage "OSGi Repositories" that covers this aspect in contrast to https://bnd.bndtools.org/chapters/250-resolving.html that covers the case how to use this in BND itself.

**Comment by pkriens** [comment]
The bnd command line tool can create indexes like bindex did: https://bnd.bndtools.org/commands/index.html

You can also use gradle.

**Comment by laeubi** [comment]
Is there any similar for library use like the Analyzer available? Maybe it would be good to change the link in the bindex repo to the mentioned documentation?

**Comment by pkriens** [comment]
It is an archived repo ... For programmatic use, see the `biz.aQute.bnd.osgi.resource` package. The `ResourceBuilder` allows you to quickly turn a manifest or a JAR into a Resource that  you can add to a ResourcesRepository. You can then turn that repository into an XML file.

**Comment by rotty3000** [comment]
To add to Peter's suggestion,

It might also be useful to look at usages of
https://github.com/bndtools/bnd/blob/a33a1a0a42ba70bae26226058ca81a5d69f6c0a8/biz.aQute.bndlib/src/aQute/bnd/osgi/repository/SimpleIndexer.java

(Bnd itself uses this in almost all index scenarios)

It is a simple builder based indexer impl you can use to index files and
should do the most come tasks related to that without having to deviate
from it's simple api. But paired with ResourceBuilder, as Peter suggested,
gives you advanced features to do anything else not covered.

- Ray

**Comment by bjhargrave** [comment]
Closing as this is not a Bnd issue.
