### ISSUE TITLE
Create macro to give the current running BND Version

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4485]
@bjhargrave I would give it a shot in the coming days. Would care to assign it to me?

**Comment by bjhargrave** [comment]
It should go in the Macro class.

**Comment by juergen-albert** [comment]
> And make sure to document the macro with a new doc page.

The macro index list page is created automatically or do I need to add it somewhere?

**Comment by bjhargrave** [comment]
> The macro index list page is created automatically or do I need to add it somewhere?

Automatic.
