### ISSUE TITLE
[bndtools debug] Conditional breakpoints not working

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4506]
The source lookup as implemented in #3993 seems to have had the side effect of making conditional breakpoints not working.

This is because conditional breakpoints need to be compiled within the context of a Java project, and the jars in question are not on the build path of the Java project. Seems to be a manifestation of https://bugs.eclipse.org/bugs/show_bug.cgi?id=542089

As a workaround, I have done this:

* Create an empty Bndtools project.
* Set up my launch file within this project.
* Copy the bundles in -runfw, -runpath and -runbundles into -buildpath.
* In the source lookup configuration, move the "Default" configuration to be ahead of the "Bnd Dependencies" entry. (I tried to remove the "Bnd Dependencies" entry but it seems to get added automatically.)

**Comment by bjhargrave** [comment]
Is this really something which can be Bndtools fault? Not sure we have anything to do with Java debugging in JDT.

**Comment by kriegfrj** [comment]
Yes and no. It's not Bndtools' fault the current implementation isn't
working. But it might be possible to work around the Eclipse issue with a
different implementation.
