### ISSUE TITLE
[Enhancement] BND Workspace Extensions

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4508]
Moved this from discourse. For the history look [here](https://bnd.discourse.group/t/add-release-extra-bundles/70/16).
@pkriens last message has been:

I’ve done a bit more thinking … Maybe we should not use Git repos but good old bundles? An extension could easily be stored in a JAR and a Capability describing it.
```
Provide-Capability \
    bnd.workspace.extension; \
           bnd.workspace.extension=biz.aQute.workspace.awesome; \
           where=we/awesome; \
           version = 1.2.3, \
    bnd.workspace.extension; \
           bnd.workspace.extension=biz.aQute.workspace.javagen; \
           where=we/javagen; \
           version = 4.5.6
```
The humongous advantage is then that search, discovery, caching, naming, versioning, version ranges, distribution, security, building, annotations, releasing, snapshots, authentication, format, etc. are all already in place and done pretty professionally.

Key problem is of course that they then come from repositories and they should be able to create repositories. However, the plus side is so large that I think it is worth considering this avenue.

```
 -workspace-extension \
        biz.aQute.workspace.awesome;version=1.2, \
        ...
```
We could make a context menu entry that lists all workspace extensions in the repositories and automatically inserts it in the instruction, like I did for the -plugins.

> Regarding your -use instruction: would this be similar to what I have in my example with -enable-gecko-emf: true ?

Close but not exactly. I think we need a workspace.bnd that defines global things and a per project project.bnd that is only included when you use -use. So the workspace.bnd could still do global things and the project.bnd could be empty. However, it allows the extension to delay some stuff until a project really uses it.

**Comment by pkriens** [comment]
I think the discussion is fine on the forum. Maybe others pitch in?

**Comment by juergen-albert** [comment]
I had a similar thought, but wasn't sure about the implications for the loading sequence as you have mentioned as well.

All in all I like this idea more then the git version. First of, it is close to my original intention and see the other advantages you named. In addition to that, it would also follow the concept we use in most other parts and fits nicely with e.g. the templates, external plugins etc.

If we want to add the possibility to have the project specific extension as well, I would suggest the following:

```
Provide-Capability \
    bnd.workspace.extension; \
           bnd.workspace.extension=biz.aQute.workspace.awesome; \
           where=we/awesome; \
           type=workspace;\
           version = 1.2.3, \
    bnd.workspace.extension; \
           bnd.workspace.extension=biz.aQute.workspace.javagen; \
           where=we/javagen; \
           type=project;\
           version = 4.5.6, \
     bnd.workspace.extension; \
           bnd.workspace.extension=biz.aQute.workspace.bndrun; \
           where=we/bndrun; \
           type=bndrun;\
           version = 4.5.6,,
```

so, we have can have extensions for each workspaces, projects and bndruns. I'm not quite sure what your idea behind the where was however.

**Comment by juergen-albert** [comment]
> I think the discussion is fine on the forum. Maybe others pitch in?

Sure, I will post my answer there as well. Now we at least have a ticket we can point the PR finally on :-)
