### ISSUE TITLE
NullCheck while starting Junit-Tests

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#4520]
@juergen-albert this is just a reminder.

In some cases we have a NPE.

https://github.com/bndtools/bnd/blob/a33a1a0a42ba70bae26226058ca81a5d69f6c0a8/bndtools.core/src/bndtools/launch/JUnitShortcut.java#L233

**Comment by juergen-albert** [comment]
Already addressed with https://github.com/bndtools/bnd/pull/4521
