### ISSUE TITLE
[m2e tester] JUnit 5 macro does not find classes that implement package-private interfaces

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4527]
The bnd macro used for finding JUnit 5 classes in the bnd maven plugins is:

`${classes;HIERARCHY_INDIRECTLY_ANNOTATED;org.junit.platform.commons.annotation.Testable;CONCRETE}`

I just discovered that this macro will not find test classes that implement test interfaces with default methods that are annotated as tests. So the following:

```java
interface MyTestInterface {
   @Test
   default void myTestMethod() {}
}

class MyTestClass implements MyTestInterface {
}
```
`MyTestClass` will not be included by the macro.

 I'm not proficient enough in bnd macro language to know what is wrong with it off the top of my head; possibly the "CONCRETE" flag is being applied at each level of the hierarchy?

**Comment by rotty3000** [comment]
I think it's more likely this has to do with default methods being missed in the HIERARCHY_INDIRECTLY_ANNOTATED scenario. A test would be to make a similar header using the `${classes}` macro with fewer filters until you find the one that misses the class.

What do you get for: `${classes;HIERARCHY_INDIRECTLY_ANNOTATED;org.junit.platform.commons.annotation.Testable}` ?

**Comment by bjhargrave** [comment]
The `HIERARCHY` operations only look through the super type hierarchy and not at the interfaces since they could not hold method implementations. For each type in the super type hierarchy, we collect all the annotations on the type. We would expand that to also include all the annotations on the implemented interfaces but that itself becomes another deep chain. I think this would be very hard to handle default methods on directly or indirectly implemented interfaces.

The following example should not include `MyTestClass` in the macro since the interface method is implemented with out the `@Test` annotation.

```java
interface MyTestInterface {
   @Test
   default void myTestMethod() {}
}

class MyTestClass implements MyTestInterface {
     void myTestMethod() {}
}
```
What should the following do?

```java
interface MyTestInterface {
   @Test
   void myTestMethod();
}

class MyTestClass implements MyTestInterface {
     void myTestMethod() {}
}
```

If we include the directly and indirectly implemented interfaces in the macro, then `MyTestClass` is included. 

I think we should not attempt to handle the directly and indirectly implemented interfaces of the super type hierarchy.

**Comment by kriegfrj** [comment]
If we're not going to change the default macro that we use for bnd-maven-plugin, we should at least document that it might not automatically find tests cases defined in interfaces.

**Comment by bjhargrave** [comment]
> If we're not going to change the default macro that we use for bnd-maven-plugin

There is currently nothing better to change it to. The `classes` macro is doing what it is designed to do. The question, which I posed above, includes what do we really want for interface handling? Do we care that interfaces are decorated with the named annotation type? Only if they are default methods? But only if they are not overridden? I suppose if there were documented rules for JUnit 4's and Junit Jupiter's annotation searching algorithms, then we could look to better support them. But without a crisp specification of those rules, we would just be guessing and may guess wrong.

> we should at least document that it might not automatically find tests cases defined in interfaces.

We can document more specifically what the `testCases` configuration options does. We already do state it uses the `classes` macro: https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin#test-cases. And the `classes` macro is clear that it looks at the super type hierarchy: https://bnd.bndtools.org/macros/classes.html. 

> The class, or one of its super classes, must be directly or indirectly annotated with an annotation that matches the pattern.

But we can highlight the limitations which are basically that the `classes` macro will _not_ look at directly or indirectly implemented interfaces for the named annotation type and thus default methods in interfaces will _not_ be found. But as long as the class directly or indirectly implementing the interface is annotated by the named annotation type, it will be included in the result. It is only the corner case above where the concrete class does _not_ reference the named annotation type, that the concrete class will not be included in the result. Basically a pretty narrow corner case :-)
