### ISSUE TITLE
Getting the real BundleVersion in a macro does ignore -snapshot

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4544]
If I have a bnd like:
```
Bundle-Version: 1.0.0-SNAPSHOT
-snapshot: 
Test: ${Bundle-Version}
```

I would expect Test to be 1.0.0, but it still has the SNAPSHOT attached.

I saw, the the final Version is calculated when the the final Manifest is calculated. I guess the macro is resolved to early for this.  Any ideas how to fix this? Do we have a macro that takes care of this? I couldn't find any.

**Comment by bjhargrave** [comment]
`1.0.0-SNAPSHOT` is not a valid bundle version.

**Comment by bjhargrave** [comment]
`-snapshot` is processed by Builder during analyze which is called by calcManifest. So I would expect `Test` to match the value of `Bundle-Version`.

**Comment by juergen-albert** [comment]
bnd can work with both. -SNAPSHOT and .SNAPSHOT. At least in regard to replacing the snapshot qualifier on release. 

I've just realized, that the bsn macro is also only working when the Manifest is calculated. I guess we should start documenting, on what level a macro is available. Users (me included) are not aware, what macro is when and where available.

**Comment by bjhargrave** [comment]
Closing. Only the Analyzer processes the `-snapshot` instruction when calculating the manifest. So when not using the Analyzer, no one is there to process the `-snapshot` instruction.
