### ISSUE TITLE
Raise Bndtools' Eclipse dependency from 4.10 (2018-12) to 4.16 (2020-06)

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4545]
Launching with the rather old 4.10 eclipse jars on macOS results in 

```
java.lang.NullPointerException: null
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2180)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:177)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:138)
```

This is fixed in 4.16 by [Eclipse Bug 548430](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548430).

**Comment by bjhargrave** [comment]
See <http://archive.eclipse.org/eclipse/downloads/> for archived Eclipse releases. We will also need the corresponding version of Eclipse m2e for the version of Eclipse.

**Comment by gamerson** [comment]
> See http://archive.eclipse.org/eclipse/downloads/ for archived Eclipse releases. We will also need the corresponding version of Eclipse m2e for the version of Eclipse.

The version of m2e we need is `1.15.0` from here: https://download.eclipse.org/technology/m2e/releases/1.15/1.15.0.20200310-1746/

**Comment by bjhargrave** [comment]
<http://download.eclipse.org/releases/2020-06/202006171000/plugins/> seems to be a source of all the 4.16 plugins, including m2e. But it is showing the m2e version at 1.16 (not 1.15).

**Comment by gamerson** [comment]
> http://download.eclipse.org/releases/2020-06/202006171000/plugins/ seems to be a source of all the 4.16 plugins, including m2e. But it is showing the m2e version at 1.16 (not 1.15).

You are right.  I looked into the first subfolder under the 4.16 composite repo here and found m2e 1.15. 
https://download.eclipse.org/releases/2020-06/202004171000/plugins/

The last composite folder (GA release?) shows m2e 1.16.  So this folder should be the right one to use:
https://download.eclipse.org/technology/m2e/releases/1.16.0/

However, there is the most recent 1.16.2 patch release which may be "better"
https://download.eclipse.org/technology/m2e/releases/1.16.2/

**Comment by gamerson** [comment]
Nah 1.16.0 is the right one to compile again.  Because not everyone who has m2e installed may have updated to 1.16.2 version.

**Comment by bjhargrave** [comment]
I am using the technique at <https://phauer.com/2015/offline-copy-mirror-eclipse-p2-repository/#command-line-eclipses-mirrorapplication> to download the <http://download.eclipse.org/releases/2020-06/202006171000/> p2 repo to my workstation now.

**Comment by kriegfrj** [comment]
Once upon a time, I created an empty writeable OSGIRepository pointing to a dir on my local filesystem, and a P2Repository that pointed to the remote Eclipse repo. Then I simply used the drag-and-drop in Bndtools to copy all of the artifacts from the P2Repository into the OSGiRepository. Or something like that. Took a while, but seemed to work!
