### ISSUE TITLE
The NAME query for ${classes} macro does not use classes' FQN.

### ISSUE THREAD

**Issue by chrisr3** [bndtools/bnd#4557]
According to the [documentation](https://bnd.bndtools.org/macros/classes.html):
```
NAMED | PATTERN | The class fqn must match the given pattern.
```
However, the implementing code in `aQute.bnd.osgi.Clazz` contains:
```java
case NAMED : {
    requireNonNull(instr);
    return instr.matches(getClassName().getDottedOnly()) ^ instr.isNegated();
}
```
rather than:
```java
case NAMED : {
    requireNonNull(instr);
    return instr.matches(getClassName().getFQN()) ^ instr.isNegated();
}
```
This matters for inner, nested and anonymous classes whose FQNs contain `$` characters which `TypeRef.getDottedOnly()` replaces with `.`.

The OSGi headers that Bnd writes into `MANIFEST.MF` still contain `$` characters.

The current behaviour is probably too well-established to be considered a bug, so perhaps we need a new `BINNAME` query to operate on the class binary name (which is what `TypeRef.getFQN()` really provides).

My use-case is to _exclude_ all nested, inner and anonymous classes from the `${classes}` output, for which I would need access to the class binary name.

**Comment by bjhargrave** [comment]
I think if we want to support that, we should name the new case `NAMED_BINARY` which used the binary name (`TypeRef.getBinary()`) e.g. `com/foo/Outer$Inner`.

**Comment by chrisr3** [comment]
Is this feature sufficiently "safe" to be included in the 5.3 release please?

**Comment by bjhargrave** [comment]
> Is this feature sufficiently "safe" to be included in the 5.3 release please?

5.3 is feature complete and RC2. It is basically done; it just needs the final build. So I would say no.

**Comment by chrisr3** [comment]
> I think if we want to support that, we should name the new case `NAMED_BINARY` which used the binary name (`TypeRef.getBinary()`) e.g. `com/foo/Outer$Inner`.

The number of different Java class names always confounds me, but isn't `com/foo/Outer$Inner` the _internal_ name rather than the binary name?

Hmm, [opinion is dvided on the subject](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html):

> For historical reasons, the syntax of binary names that appear in class file structures differs from the syntax of binary names documented in JLS §13.1. In this internal form, the ASCII periods (.) that normally separate the identifiers which make up the binary name are replaced by ASCII forward slashes (/). The identifiers themselves must be unqualified names (§4.2.2).

Gee, thanks Sun! I'm not sure that the internal binary name is very interesting to me while I'm wearing my OSGi hat :thinking:.

**Comment by bjhargrave** [comment]
Reading those specs takes some care. Much of the discussion in the JLS is about the Identifier for a class not its fully qualified name.

In Java source code, a fully qualified type name is always dot-separated. This also includes dot-separation between the outer class identifier and the nested class identifier.

In class files, a fully qualified type name is always slash-separated. And the identifier of an nested class includes the names of all the outer classes which are dollar-separated.

There is no real scenario in Java where you have both dot and dollar separation. It is either all dots (source code), or slash and dollar (class files).

---

Some terms:

A _nested_ class is any class whose declaration occurs within the body of another class or interface. <https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html>

A _top-level_ class is a class that is not a nested class.

An _inner_ class is a nested class that is not explicitly or implicitly declared static. <https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.1.3>

_Anonymous_ classes and _local_ classes are inner classes. 

So your particular use case is to identify only _top-level_ classes, right? Or alternately to exclude _nested_ classes?

Using `$` in the class name is not sufficient to accurately do what you want. It is perfectly legal (although discouraged) to use `$` in type names: `class Foo$Bar`. `Foo$Bar` is a top-level class.

So to accurately do what you want, we should rather define new query types for the `classes` macro like `TOPLEVEL`, `NESTED`, `INNER`.

**Comment by chrisr3** [comment]
Actually, I have already discovered that excluding class names containing `$` would not work, even if Bnd 5.2 supported it :disappointed:. I think what I really need to do is exclude _non-static_ inner classes (i.e. those containing an implicit `this` reference to an instance of their host class), anonymous classes and local classes, which I can _partially_ implement using:
```
NAMED;!*\.[\\d]+
```
This much is _probably_ good enough for now, although I will still need to filter the non-static inner classes out elsewhere. The end goal is to identify a list of `PUBLIC`, `CONCRETE` classes inside the bundle which `IMPLEMENT` a given interface, and that we can reasonably expect to be able to construct instances of ourselves via OSGi Something/Java Reflection/Evil Magic etc.

The point is that we cannot perform this kind of class scanning once inside an OSGi framework

**Comment by bjhargrave** [comment]
> _non-static_ inner classes

Inner classes are by definition non-static.

> anonymous classes and local classes

These are by definition inner classes.

> NAMED;!*\.[\\d]+

This would only exclude anonymous classes since the JLS does not allow class identifiers be only digits. <https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.1>

> This much is _probably_ good enough for now

OK. What do we do with this issue now?

> The end goal is to identify a list of `PUBLIC`, `CONCRETE` classes inside the bundle which `IMPLEMENT` a given interface, and that we can reasonably expect to be able to construct instances of ourselves via OSGi Something/Java Reflection/Evil Magic etc.

So this is the `TOPLEVEL` + `NESTED` classes and not the `INNER` classes. So maybe we need just a`NON_INNER` query type. We already have `Clazz.isInnerClass()` which could be used to implement a `NON_INNER` query type.

**Comment by chrisr3** [comment]
Yes, also being able to identify `INNER` classes (for exclusion) would be a big help please. But I think the issue with the lack of `$` characters in the `NAMED` query is still real, albeit separate. My point is that Bnd does not apply the `NAMED` query to the same names which are ultimately generated by the `${classes}` macro. So given
```
${classes} -> Foo$Bar
```
then this query would inexplicably also return `Foo$Bar`:
```
${classes;NAMED;[^$]+}
```
I needed to examine Bnd's source code to understand why this was happening.

Of course, my new `NAMED;!*.[\d]+` filter now _requires_ the dotted form :grinning:. But I still think that another query which operates over the actual `${classes}` results would be less confusing.

**Comment by chrisr3** [comment]
> There are 4 naming forms in use in Java. I will call then source form, runtime form, binary form, and signature form.

:grinning: I have delved into the world of Java byte-code myself, and have discovered the "joys" of class names, binary names (both internal and "otherwise") and descriptors. But these are not details that I expect to _need_ to be aware of in order to use the `${classes}` macro successfully.

**Comment by bjhargrave** [comment]
> But these are not details that I expect to _need_ to be aware of in order to use the `${classes}` macro successfully.

True. My PR updates the documentation to be clear what form is used by which query type. For backwards compatibility reasons, we should not change a query type from one form to another. 

Also, no one should be looking for names with or without a `$` in them as this does not mean anything about inner or non-inner classes. It just means the class name as a `$` in it.

The PR was simple enough, I think I will cherry-pick the commit into the 5.3 branch.

**Comment by chrisr3** [comment]
Thanks, that works for me. The entire "name with a `$` in it" was _from the start_ just a means to try and classify the scanned classes, so any more precise filter is obviously an improvement. Discovering that the `NAME` filter didn't behave as expected either was an extra blow.
