### ISSUE TITLE
Adding bnd to sdkman?

### ISSUE THREAD

**Issue by joerg-rade** [bndtools/bnd#4558]
Is it possible?

**Comment by pkriens** [comment]
I've no idea what sdkman is?

**Comment by njbartlett** [comment]
> I've no idea what sdkman is?

Basically another package manager: https://sdkman.io/

I do find it useful for provisioning and quickly switching between different versions of the JDK.

**Comment by joerg-rade** [comment]
Sorry - a tool to manage lots of jvm related tools (languages, buildtool), see
* https://sdkman.io/
* https://sdkman.io/usage

Sample: 
```
joerg.rade@DEW30555 MINGW64 /
$ sdk help
No update at this time. Using existing cache: ant,asciidoctorj,ballerina,bpipe,btrace,ceylon,concurnas,crash,cuba,cxf,doctoolchain,dotty,gaiden,glide,gradle,gradleprofiler,grails,groovy,groovyserv,http4k,infrastructor,java,jbake,jbang,karaf,kotlin,kscript,layrry,lazybones,leiningen,maven,micronaut,mulefd,mvnd,sbt,scala,spark,springboot,sshoogr,test,tomcat,vertx,visualvm
Not refreshing version cache now...

Usage: sdk <command> [candidate] [version]
       sdk offline <enable|disable>

   commands:
       install   or i    <candidate> [version] [local-path]
       uninstall or rm   <candidate> <version>
       list      or ls   [candidate]
       use       or u    <candidate> <version>
       completion        <bash|zsh>
       default   or d    <candidate> [version]
       home      or h    <candidate> <version>
       env       or e    [init|install|clear]
       current   or c    [candidate]
       upgrade   or ug   [candidate]
       version   or v
       broadcast or b
       help
       offline           [enable|disable]
       selfupdate        [force]
       update
       flush             [archives|tmp|broadcast|version]

   candidate  :  the SDK to install: groovy, scala, grails, gradle, kotlin, etc.
                 use list command for comprehensive list of candidates
                 eg: $ sdk list
   version    :  where optional, defaults to latest stable if not provided
                 eg: $ sdk install groovy
   local-path :  optional path to an existing local installation
                 eg: $ sdk install groovy 2.4.13-local /opt/groovy-2.4.13
```

**Comment by pkriens** [comment]
If someone figures out how to provide our jars for each release, I guess we can support it. Surprised they do not use Maven Central though. Does look a bit like my [jpm](https://github.com/bndtools/jpmcli) though :-(

**Comment by joerg-rade** [comment]
So I'll raise an issue with the sdkman project?!

**Comment by joerg-rade** [comment]
Looking deeper into https://sdkman.io/vendors, it seems the effort would be on the side of the 'vendor', here: the bndtools/bnd project. Afore mentioned url includes a mailTo link for getting in contact.

**Comment by bjhargrave** [comment]
I looked into doing this some time back and it was too complicated for me to bother with. So I passed. 

brew is way easier and saner. It can be done with a simple commands and is git based.

I sent an email to SDKMAN to ask about getting credentials to publish.

**Comment by bjhargrave** [comment]
Like with brew, I think we only publish bnd.jar to sdkman. Not sure how we set the execution script for the jar...

**Comment by bjhargrave** [comment]
> Not sure how we set the execution script for the jar...

I think this was the problem. With brew, we install a `bnd` command (shell script) which runs `java -jar bnd.jar`. I don't see how this is possible in SDKMAN. Perhaps someone knows how?

**Comment by joerg-rade** [comment]
withdrawn

**Comment by bjhargrave** [comment]
I emailed sdkman and bnd's CLI is not something they can handle. They only do zip/tar based distributions like JDK. So no sdkman for the bnd CLI.
