### ISSUE TITLE
Bnd does not read/refresh repositories

### ISSUE THREAD

**Issue by dkorchagin** [bndtools/bnd#4559]
I am trying to build an OSGi project using bnd 5.1.1

I have a cnf folder containing a build.bnd, which configures a number of Maven repositories, and a number of bnd OSGi projects on the same level as cnf directory.

When I build one of the projects on a Windows machine - all works fine. All the repositories are loaded, and the project is packaged.

However, when I run same thing from whithin a Kubernetes pod (RHEL7), it reports a lot of artifacts cannot be found in local Maven cache, and it won't attempt to download it. I tried **repo list**, **repo refresh** prior to do **package** - same negative result.

debug command reports 000: No build.bnd file in cnf in both cases, however, when run on Windows it won't report absence of the artifacts, while when run within a pod it does report those.

File ownership within a Kubernetes pod is the current user, I can see the build.bnd file in cnf directory as well, everything is readable.

What could be the reason for this behavior?

**Comment by dkorchagin** [comment]
Guys, nobody can comment on that?

**Comment by juergen-albert** [comment]
We could, but we chose not to till now. If it is an issue nobody has an immediate idea, we talk about it in the next meeting we have. This is an OSS Project and everything happens, when things happen.

Your description did not really present much to go by. God knows how this works in K8s and how you are actually building it. Is it gradle or by using the bnd jar. Without any logs we can't really tell you anything. My guess is, that is called from the wrong path or something like this.

**Comment by pkriens** [comment]
If you can run a shell in the pod, you might want to try:

	bnd -dt repo list

The -dt sets it in debug mode and the t in trace mode. This tends to give a lot of detail.

It does not happen often that something works well in Windows and not on Linux! :-)

Good luck. Kind regards,

	Peter Kriens

**Comment by bjhargrave** [comment]
Any feedback? Or shall we close?

**Comment by dkorchagin** [comment]
Sorry, I lost hope and haven't checked email for a while. Will try what @pkriens suggested and see what it looks like. Thanks for your help.

**Comment by dkorchagin** [comment]
> We could, but we chose not to till now. If it is an issue nobody has an immediate idea, we talk about it in the next meeting we have. This is an OSS Project and everything happens, when things happen.
> 
> Your description did not really present much to go by. God knows how this works in K8s and how you are actually building it. Is it gradle or by using the bnd jar. Without any logs we can't really tell you anything. My guess is, that is called from the wrong path or something like this.

Thanks for paying attention to this. I am using bnd jar. Will try @pkriens' suggestion to see what's in logs - maybe I get some idea then.

**Comment by stbischof** [comment]
Which Java -version?

**Comment by dkorchagin** [comment]
> If you can run a shell in the pod, you might want to try: bnd -dt repo list The -dt sets it in debug mode and the t in trace mode. This tends to give a lot of detail. It does not happen often that something works well in Windows and not on Linux! :-) Good luck. Kind regards, Peter Kriens

When I use -dt it reports -d is unknown option; -t works though - how important -d would be, is it same as --debug?

**Comment by dkorchagin** [comment]
> > If you can run a shell in the pod, you might want to try: bnd -dt repo list The -dt sets it in debug mode and the t in trace mode. This tends to give a lot of detail. It does not happen often that something works well in Windows and not on Linux! :-) Good luck. Kind regards, Peter Kriens
> 
> When I use -dt it reports -d is unknown option; -t works though - how important -d would be, is it same as --debug?

sorry, there's no --debug.. I apparently messed it with some other thing, sorry. -d doesn't work anyway.

**Comment by pkriens** [comment]
I am not sure what you're running then ... `bnd -dt repo repos` absolutely works:
```
 bnd -dt repo repos
[main] DEBUG aQute.bnd.main.bnd - Setup logger
[main] INFO aQute.bnd.remoteworkspace.server.RemoteWorkspaceServer - Registering remote workspace server /Users/aqute/Ws/HEILA/heilaiq-bnd/cnf/cache/remotews/51702
[main] DEBUG aQute.bnd.main.bnd - Using workspace Workspace [heilaiq-bnd]
[main] DEBUG aQute.bnd.main.bnd - rewritten [repo, repos]
[main] DEBUG aQute.bnd.main.RepoCommand - getting project repos
[main] DEBUG aQute.bnd.main.RepoCommand - repos [bnd-cache [/Users/aqute/Ws/HEILA/heilaiq-bnd/cnf/cache/5.2.0/bnd-cache r/w=false], MavenBndRepository [localRepo=/Users/aqute/.m2/repository, storage=Central, inited=false, redeploy=false], MavenBndRepository [localRepo=/Users/aqute/.m2/repository, storage=Github, inited=false, redeploy=false], MavenBndRepository [localRepo=/Users/aqute/.m2/repository, storage=Local, inited=false, redeploy=false], aQute.bnd.build.WorkspaceRepository@370736d9]
[main] DEBUG aQute.bnd.main.RepoCommand - writable MavenBndRepository [localRepo=/Users/aqute/.m2/repository, storage=Github, inited=false, redeploy=false]
001: Central               r/o MavenBndRepository   https://repo.maven.apache.org/maven2/, https://maven.mangoautomation.net/repository/ias-release/, https://jitpack.io
002: Github                r/w MavenBndRepository   https://maven.pkg.github.com/HeilaTechnologies/heilaiq-bnd
003: Local                 r/w MavenBndRepository   ~/.m2/repository
004: heilaiq-bnd           r/o WorkspaceRepository  /Users/aqute/Ws/HEILA/heilaiq-bnd

**Comment by dkorchagin** [comment]
> I am not sure what you're running then ... `bnd -dt repo repos` absolutely works:
> 
> ```
>  bnd -dt repo repos
> [main] DEBUG aQute.bnd.main.bnd - Setup logger
> [main] INFO aQute.bnd.remoteworkspace.server.RemoteWorkspaceServer - Registering remote workspace server /Users/aqute/Ws/HEILA/heilaiq-bnd/cnf/cache/remotews/51702
> [main] DEBUG aQute.bnd.main.bnd - Using workspace Workspace [heilaiq-bnd]
> [main] DEBUG aQute.bnd.main.bnd - rewritten [repo, repos]
> [main] DEBUG aQute.bnd.main.RepoCommand - getting project repos
> [main] DEBUG aQute.bnd.main.RepoCommand - repos [bnd-cache [/Users/aqute/Ws/HEILA/heilaiq-bnd/cnf/cache/5.2.0/bnd-cache r/w=false], MavenBndRepository [localRepo=/Users/aqute/.m2/repository, storage=Central, inited=false, redeploy=false], MavenBndRepository [localRepo=/Users/aqute/.m2/repository, storage=Github, inited=false, redeploy=false], MavenBndRepository [localRepo=/Users/aqute/.m2/repository, storage=Local, inited=false, redeploy=false], aQute.bnd.build.WorkspaceRepository@370736d9]
> [main] DEBUG aQute.bnd.main.RepoCommand - writable MavenBndRepository [localRepo=/Users/aqute/.m2/repository, storage=Github, inited=false, redeploy=false]
> 001: Central               r/o MavenBndRepository   https://repo.maven.apache.org/maven2/, https://maven.mangoautomation.net/repository/ias-release/, https://jitpack.io
> 002: Github                r/w MavenBndRepository   https://maven.pkg.github.com/HeilaTechnologies/heilaiq-bnd
> 003: Local                 r/w MavenBndRepository   ~/.m2/repository
> 004: heilaiq-bnd           r/o WorkspaceRepository  /Users/aqute/Ws/HEILA/heilaiq-bnd
> ```

You are right, apologies. On my windows machine I have different version - 3.3.0. Let me retest with the right version on both machines.

**Comment by dkorchagin** [comment]
> Which Java -version?

**Windows**:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Container**:
openjdk version "1.8.0_271"
OpenJDK Runtime Environment (Zulu 8.49.0.16-SA-linux64) (build 1.8.0_271-b09)
OpenJDK 64-Bit Server VM (Zulu 8.49.0.16-SA-linux64) (build 25.271-b09, mixed mode)

Let me retest with the right version of bnd though.

**Comment by dkorchagin** [comment]
The -dt option revealed lots of access denied exceptions to local container file system during repo download. I think that's the reason for repo not loaded, thanks for the hint @pkriens.

May I ask you to keep this ticket open for a while. Need to fix that issue and retest. I will update on the result here.

**Comment by dkorchagin** [comment]
I also think those access denied exceptions should be reported as errors even without -dt used, perhaps?

**Comment by dkorchagin** [comment]
I fixed access stuff and that fixed the issue - closing it out.
Thanks all!
