### ISSUE TITLE
[bndtools] Startup deadlock accessing Central.workspace

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4573]
While working on the bndtools integration tests (combination of #4253 and #4569), I noticed an occasional startup deadlock which I think is related to #4253. I managed to trap this deadlock in the debugger.

The tester thread is mutually deadlocked with a worker thread `org.eclipse.core.internal.resources.ContentDescriptionManager.FlushJob`. Here is a description of the state of those two threads:

The `FlushJob` is executed at startup. It initializes JDT, which in turn (eventually) calls through to `BndContainerInitializer.initialize()`, which in turn calls `Central.getWorkspace()`. This thread is currently blocked in the execution of `Central.getWorkspace()`, waiting to acquire the monitor for `Central.workspace`, which is the memoizer for the (bnd)  `Workspace` object. Full stack trace:

```
Thread [Worker-4: Flushing content description cache.] (Suspended)	
	waiting for: MemoizingSupplier<T>  (id=181)	
	Central.getWorkspace() line: 230	
	Central.getProject(File) line: 649	
	1422396072.apply(Object) line: not available	
	1422396072(FunctionWithException<T,R>).lambda$0(Object) line: 21	
	1626693057.apply(Object) line: not available	
	Optional<T>.map(Function<? super T,? extends U>) line: 215	
	Central.getProject(IProject) line: 655	
	BndContainerInitializer$Updater.<init>(IProject, IJavaProject) line: 230	
	BndContainerInitializer.initialize(IPath, IJavaProject) line: 87	
	JavaModelManager.initializeContainer(IJavaProject, IPath) line: 3195	
	JavaModelManager$10.run(IProgressMonitor) line: 3079	
	JavaModelManager.initializeAllContainers(IJavaProject, IPath) line: 3139	
	JavaModelManager.getClasspathContainer(IPath, IJavaProject) line: 2111	
	JavaCore.getClasspathContainer(IPath, IJavaProject) line: 3752	
	JavaProject.resolveClasspath(IClasspathEntry[], IClasspathEntry[], boolean, boolean) line: 3196	
	JavaProject.resolveClasspath(JavaModelManager$PerProjectInfo, boolean, boolean) line: 3360	
	JavaProject.getResolvedClasspath() line: 2444	
	DeltaProcessingState.getRootInfos(boolean) line: 311	
	DeltaProcessingState.initializeRoots(boolean) line: 259	
	DeltaProcessor.processResourceDelta(IResourceDelta) line: 1953	
	DeltaProcessor.resourceChanged(IResourceChangeEvent) line: 2155	
	DeltaProcessingState.resourceChanged(IResourceChangeEvent) line: 477	
	NotificationManager$1.run() line: 305	
	SafeRunner.run(ISafeRunnable) line: 45	
	NotificationManager.notify(ResourceChangeListenerList$ListenerEntry[], ResourceChangeEvent, boolean) line: 295	
	NotificationManager.broadcastChanges(ElementTree, ResourceChangeEvent, boolean) line: 158	
	Workspace.broadcastPostChange() line: 380	
	Workspace.endOperation(ISchedulingRule, boolean) line: 1502	
	ContentDescriptionManager$FlushJob(InternalWorkspaceJob).run(IProgressMonitor) line: 49	
	Worker.run() line: 63	
```

The tester thread is also started automatically at startup. It is currently executing `Central.getWorkspace()`, has acquired the monitor for `Central.workspace` (which is what is blocking the `FlushJob`), and is currently calling `Central.workspace.get()` to create the bnd `Workspace` object. However, the workspace creation process has called `IResource.refreshLocal()`, which in turn has spawned a refresh job. This refresh job is waiting for the current blocking job to finish before proceeding. You guessed it - the current blocking job is the `FlushJob`. Relevant portion of the stack trace:

```
Daemon Thread [bnd Runtime Test Bundle] (Suspended)	
	owns: AtomicBoolean  (id=180)	
	owns: MemoizingSupplier<T>  (id=181)	
	waiting for: Object  (id=179)	
	Object.wait(long) line: not available [native method]	
	Object.wait() line: 502	
	ThreadJob.waitForRun(ThreadJob, IProgressMonitor, InternalJob) line: 316	
	ThreadJob.joinRun(ThreadJob, IProgressMonitor) line: 205	
	ImplicitJobs.begin(ISchedulingRule, IProgressMonitor, boolean) line: 95	
	JobManager.beginRule(ISchedulingRule, IProgressMonitor) line: 298	
	WorkManager.checkIn(ISchedulingRule, IProgressMonitor) line: 124	
	Workspace.prepareOperation(ISchedulingRule, IProgressMonitor) line: 2242	
	Folder(Resource).refreshLocal(int, IProgressMonitor) line: 1549	
	Central.refreshFile(File, IProgressMonitor, boolean) line: 622	
	WorkspaceListener.changed(File) line: 32	
	Workspace.changedFile(File) line: 465	
	Project.getSrcOutput0() line: 466	
	Project.prepare() line: 379	
	Project.getDependson() line: 886	
	Workspace.getBuildOrder() line: 612	
	Central.createWorkspace() line: 303	
	1360788400.get() line: not available	
	MemoizingSupplier<T>.get() line: 36	
	Central.getWorkspace() line: 231	
	AbstractBuildpathQuickFixProcessorTest.beforeAllBase() line: 134	
```

Although this is happening (occasionally) to the tester, I think (in theory at least) the potential exists for it to happen during regular Bndtools usage too. It probably doesn't happen in practice because the user is too slow to trigger any event that might try to initialize the workspace before the startup `FlushJob` completes.

I think having figured this out now, I'm not 100% sure on the best solution. I'm going to have to think on it for a bit. One way around it will probably be for `AbstractBuildpathQuickFIxProcessorTest.beforeAllBase()` to acquire somehow synchronize with the `FlushJob`, but it seems that `Central` is already trying to handle thread safety (and in this instance failing). Do I try and fix `getWorkspace()`'s thread-safetiness? Or do I add an extra layer of synchronization at the job level to ensure that `beforeAllBase()` doesn't call `getWorkspace()` while `FlushJob` is running? The second is probably easier for my immediate problem but it leaves a time bomb behind for other code to fall over on the same issue if they don't take care of their own synchronization.

Thoughts?

**Comment by pkriens** [comment]
This is part of the rewrite. We should start using the Workspace.readLocked and Workspace.writeLocked methods. We should also very clearly define the rules around using bnd code. We seem to be synchronously refreshing in several places. I'll open an issue so we can discuss these rules.

**Comment by kriegfrj** [comment]
> This is part of the rewrite. We should start using the Workspace.readLocked and Workspace.writeLocked methods. We should also very clearly define the rules around using bnd code. We seem to be synchronously refreshing in several places. I'll open an issue so we can discuss these rules.

For posterity, the issue @pkriens opened was #4575.

**Comment by bjhargrave** [comment]
> The tester thread is also started automatically at startup. It is currently executing `Central.getWorkspace()`, has acquired the monitor for `Central.workspace`

You should wait before getting the workspace to allow the other threads in Eclipse to do the work. Something like:

```java
	@BeforeAll
	static void beforeAllBase() throws Exception {
		// Get a handle on the repo. I have seen this come back null on occasion
		// but not exactly sure why and spinning doesn't seem to fix it; ref
		// #4253
		CountDownLatch latch = new CountDownLatch(1);
		Central.onCnfWorkspace(ws -> latch.countDown());
		latch.await();
		LocalIndexedRepo localRepo = (LocalIndexedRepo) Central.getWorkspace()
			.getRepository("Local Index");
```
