### ISSUE TITLE
Resolve Tasks is uncacheable

### ISSUE THREAD

**Issue by leonard84** [bndtools/bnd#4577]
The [ResolveTask](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Resolve.groovy) / [BndrunTask](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy) declares `bndrun` as `@InputFile` but then also modifies it during execution. (Other tasks might also be affected, but I didn't use them.)

This conflicts with general task [UP-TO-DATE](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks) checks and [build caching](https://docs.gradle.org/current/userguide/build_cache_concepts.html)

To fix this, first add a separate `@OutputFile`. Second, the `@InputFile` should not be modified, but instead be copied to the `@OutputFile` first, and then modified.

**Comment by bjhargrave** [comment]
One of the main points of resolving is to modify the input bndrun file with the resolved `-runbundles` which is then available to later tasks like the TestOSGi task or the Bndrun task. This is part of the expected Bnd workflow.

So the bndrun is both an input and an output. I am not sure how to mark that for Gradle.

If you do not want to modify the input file, you can configure the task to fail of the `-runbundles` changes.

**Comment by leonard84** [comment]
> So the bndrun is both an input and an output. I am not sure how to mark that for Gradle.

You can't, as this makes the task not cacheable.

Why is it not possible to just point it to a different output file, eg. 
```groovy
tasks.register('resolve', Resolve) { t ->
  t.bndrunInput = file("in.bnd")
  t.bndrunOutput = file("out.bnd")
}
```
Internally, you could copy the `in.bnd` to `out.bnd` and then modify it.
And if you still want the old behavior, you could point those to the same file, while I strongly recommend against that.

**Comment by bjhargrave** [comment]
> You can't, as this makes the task not cacheable.

I think for your workflow, you would want `failOnChanges = isCIbuild()` and `writeOnChanges = !isCIbuild()` and then you need to resolve outside of the CI build and commit the updated bndrun file to git. So resolving in the CI build is just a test to ensure the bndrun has been properly updated by the developers.

**Comment by bjhargrave** [comment]
What I am thinking is to add a new output file which will contain the computed `-runbundles` if the output file is specified. If the output file is specified, then `writeOnChanges` will default to `false` instead of `true`.

This would allow an output file to be created if desired with just the computed `-runbundles`. The input file can conditionally include this file: `-include: -output.bndrun`.

**Comment by leonard84** [comment]
> If the output file is specified, then writeOnChanges will default to false instead of true.

I'm a bit confused `writeOnChanges` why would it be `false` when you define an output file?
Or, would `writeOnChanges` imply modifying the input?

You might also want to look into how to make tasks [cacheable](https://docs.gradle.org/current/userguide/build_cache.html#enable_caching_of_non_cacheable_tasks) via build cache, as this has some more requirements than just the local UP-TO-DATE checking.

**Comment by bjhargrave** [comment]
> Or, would `writeOnChanges` imply modifying the input?

Yes, `writeOnChanges` is about modifying the input bndrun file with the calculated `-runbundles` value.


> You might also want to look into how to make tasks [cacheable](https://docs.gradle.org/current/userguide/build_cache.html#enable_caching_of_non_cacheable_tasks) via build cache, as this has some more requirements than just the local UP-TO-DATE checking.

That is a larger issue, no? Since it would need to examine all of the Bnd gradle tasks.

**Comment by leonard84** [comment]
> That is a larger issue, no? Since it would need to examine all of the Bnd gradle tasks.

Yes, and it can be done later.

**Comment by bjhargrave** [comment]
So I started to look into this and I don't think we can change to use a different output file. bndrun files are location sensitive. They can contain relative paths to other files and use the here `${.}` reference which is the folder holding the bndrun file. If we modify the resolve task to write the modified bndrun file to a new folder (in the build directory), then when this new bndrun file is used by the testOSGi task, it will fail since the bndrun file is not in the project folder which is expected for the relative and here `${.}` references.

**Comment by leonard84** [comment]
@bjhargrave  you could create it in the source directory next to the existing file, so that the paths match, and then move it to the output directory once everything is resolved.

**Comment by bjhargrave** [comment]
> then move it to the output directory once everything is resolved.

Sure. But then how is that file useful to downstream tasks? The point of resolving a bndrun file is for downstream tasks (like testOSGi, export, run) to be able to use the generated `-runbundles` and the updated bndrun file must still be in the source folder since it will still have relative references and use here `${.}` and the downstream tasks will itself need to load the updated bndrun file into a Bndrun object.

**Comment by bjhargrave** [comment]
> you could create it in the source directory next to the existing file

I also suspect that this would still upset Gradle's out-of-date analysis since Gradle is now using file system watching in Gradle 7. So writing an output file to a watched source folder, even temporarily, may still trigger Gradle to see that task as out-of-date.

**Comment by leonard84** [comment]
Let me preface I'm not familiar with how bnd works at all, I just have to support OSGi declarations as some users of Spock need them.

I think it should be possible to have a "working directory" and be able to define a separate file, that is then treated as if it were at in the "working directory". IMHO modifying sources in-place during build is a bad practice.

In Spocks particular use-case we don't actually care about the result, just that it doesn't fail https://github.com/spockframework/spock/blob/37a4e3e116af58a6499f295fee50b2679d5ca01d/spock-core/core.gradle#L105 and we use a generated properties file as input.

At the very least all `@InputFile`, `@InputFiles`, `@InputDirectory` should use [@PathSensitive](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/PathSensitive.html)(RELATIVE) so that only their relative location in the projects is taken into account, not where user has its workspace.

**Comment by bjhargrave** [comment]
> modifying sources in-place during build is a bad practice.

Yes, but the original intent was for developers to use the resolve task on their workstation, verify the results and commit the changes as source. The CI build was not meant to be the place to run the resolve task. But people do this.

Thanks for continuing to push me on this. In continuing to reflect upon this, I think I know have a solution which I will work on after the weekend.



> At the very least all `@InputFile`, `@InputFiles`, `@InputDirectory` should use [@PathSensitive](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/PathSensitive.html)(RELATIVE) so that only their relative location in the projects is taken into account, not where user has its workspace.

I will also look into this.
