### ISSUE TITLE
[tester] Additional lifecycle callbacks for BundleEngine

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4587]
# Problem Use Case

I'm currently writing some tests for an iDempiere plugin I'm working on, and attempting using TDD. The problem is that iDempiere caches the data dictionary, so any time that I make a change to the data dictionary during my testing I have to restart the test instance in order to clear its cache.

I could attempt to clear the cache at the start of each test class, but that would slow down the testing unnecessarily. As the test should not be modifying the data dictionary during execution, it is sufficient to clear the cache once at the start of the test.

Unfortunately, there are no appropriate lifecycle callbacks available to me to do this during testing. I could do it in the bundle activator of my test, but then that will only happy when the bundle is restarted - if I change the dictionary and want to re-run the test, I will have to either manually restart the test bundle - I can't simply type "runTests" in the console.

# Proposed Solution

For some time, I had the idea for `BundleEngine` to have lifecycle callbacks, similar to what `JupiterEngine` has. These lifecycle callbacks would reflect the additional levels of hierarchy in the test output that the `BundleEngine` introduces. The proposal:

## Timing
* Before/AfterAllBundles - called at the start/end of the test run.
* Before/AfterEachBundle - called before/after BundleEngine starts to execute the tests in each of the bundles.
* Before/AfterAllEngines - called for each bundle, before/after all engines are run
* Before/AfterEachEngine - called for each bundle, before/after each engine is run

Below this level of the hierarchy, individual test engines will be responsible for the types of callbacks they provide.

## Scoping
* The Before/AfterEach/AllBundle(s) callbacks would be globally scoped, and can be registered from any bundle, and will apply to all bundles in any given test run.
* The Before/AfterEach/AllEngine(s) callbacks would be scoped to the bundle that they are defined in.

This distinguishes Before/AfterEachBundle from Before/AfterAllEngines - the timing of these two callbacks is the same, but their scope is different.

## Registration of callbacks

The callbacks would be defined as interfaces, similar to what Jupiter does. Callbacks would be registered through the OSGi service registry, and `BundleEngine` would track them using a `ServiceTracker`.

## Context

For maximum flexibility, lifecycle callbacks will need access to the bundle engine's execution context (`BundleEngineContext`)- similar to Jupiter extensions which have access to the `ExecutionContext`.
There are two ways in which this could be done:

1. As a parameter to the lifecycle callback methods (like Jupiter extensions), or
2. Via a globally-registered service that extensions could reference if desired, or
3. Both.

The first has the advantage that it is more in-line with what Jupiter does and thus will be more familiar. But the second also makes the `BundleEngineContext` accessible from any context and not only from `BundleEngine` callbacks (eg, from within a Jupiter extension, or even from within a running test).

I propose to have callback interfaces like this:

```java
public interface BeforeAllEngines {
   void beforeAllEngines(BundleEngineContext context);
}
```

## Open questions

The above scheme leaves a couple of holes:
* Is there any use case where you might like a Before/AfterAllBundles callback to run, but *only* if the bundle in which it is defined is included in the current test run?
* Is there any use case where you might like to define a global Before/AfterEachEngine callback to run in global context?

These seem like edge cases to me. Perhaps we can start with the basic implementation above and add these features later if necessary - the migration path should be fairly painless.

Another open question:  Should a separate set of callbacks be introduced for the "fragment" level of the hierarchy, as distinct from the "bundle" level? I'm not sure of the answer and I'm inclined to keep it simple for now and add this later if necessary.

# Conclusion

This is not a spontaneous idea - it's something I've been thinking about pretty much since I first implemented the junit-platform tester. But this is the first time I've fully fleshed it out and sketched out a bit of a design on e-paper. I'm interested in thoughts/feedback/suggestions to refine the design.

**Comment by bjhargrave** [comment]
> I had the idea for `BundleEngine` to have lifecycle callbacks, similar to what `JupiterEngine` has.

Are you proposing some new annotations to supplement the (Before|After)(Each|All) annotations? That is, providing bundle activation level call backs to supplement the existing class and method level call backs of Jupiter?

I can perhaps see a BeforeBundle and AfterBundle callback that each bundle could provide which would be called if the bundle has any selected tests. How would the engine find these annotations? We know what the test classes are from the Test-Cases header so we can process those classes. What if the BeforeBundle annotation is in some other class in the bundle? Must we scan all classes in the bundle? This does not seem like a good idea either. Or do you require the BeforeBundle annotation to be in a class listed in Test-Cases?

But I am not sure a call back before|after all bundles is a good idea. Then you have to look in all bundles for it.

>     * Is there any use case where you might like a Before/AfterAllBundles callback to run, but _only_ if the bundle in which it is defined is included in the current test run?

It seems wrong that a bundle which is not "under" test would be influencing the tests of another bundle. This almost seems to be something to solve "side effects" of running prior tests. But I would assume/hope each test would reset the state after the test run rather than rely upon some external entity (which may not be present) to reset the state.

>  Should a separate set of callbacks be introduced for the "fragment" level of the hierarchy,

This seems wrong. Fragments do not have an activation lifecycle. They are attached to bundles (perhaps multiple bundles) and the bundles have an activation lifecycle.

**Comment by kriegfrj** [comment]
> > I had the idea for `BundleEngine` to have lifecycle callbacks, similar to what `JupiterEngine` has.
> 
> Are you proposing some new annotations to supplement the (Before|After)(Each|All) annotations? That is, providing bundle activation level call backs to supplement the existing class and method level call backs of Jupiter?
> 
> I can perhaps see a BeforeBundle and AfterBundle callback that each bundle could provide which would be called if the bundle has any selected tests. How would the engine find these annotations? We know what the test classes are from the Test-Cases header so we can process those classes. What if the BeforeBundle annotation is in some other class in the bundle? Must we scan all classes in the bundle? This does not seem like a good idea either. Or do you require the BeforeBundle annotation to be in a class listed in Test-Cases?
> 
> But I am not sure a call back before|after all bundles is a good idea. Then you have to look in all bundles for it.
>

Yes, I'm suggesting providing additional callbacks to supplement class and method level callbacks of Jupiter (or of any other engine for that matter).

However, I am not proposing using annotations for this as I don't think they are the best fit for callbacks at a higher level of scope than class or package, for all the reasons that you highlighted above. That is why I think that these would be best done through a global mechanism like the OSGi service registry. Per the OP:

"The callbacks would be defined as interfaces, similar to what Jupiter does. Callbacks would be *registered through the OSGi service registry*, and BundleEngine would track them using a ServiceTracker."

Note that even in Jupiter, global extensions are not registered using annotations (for the reasons you outline), but through the `ServiceLoader` mechanism (https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic). Using the service registry in an OSGi context seems like the natural way to do the equivalent.

> > 
> > * Is there any use case where you might like a Before/AfterAllBundles callback to run, but _only_ if the bundle in which it is defined is included in the current test run?
> > 
> 
> It seems wrong that a bundle which is not "under" test would be influencing the tests of another bundle. This almost seems to be something to solve "side effects" of running prior tests. But I would assume/hope each test would reset the state after the test run rather than rely upon some external entity (which may not be present) to reset the state.
>

But the point of an extension is not necessarily to do any testing (not even necessarily to affect state), but to add capability to existing tests.

The case I am envisaging is similar to what global extensions in Jupiter are set up to handle. In Jupiter, a global extension applies to all running tests and may be (in fact, probably usually is) defined in a different jar to the tests themselves. An example is the extension that generates pretty display names for tests by mapping `this_is_the_test_method_name()` to `This is the test method name` - once registered, it applies to all tests. You could have a similar callback for Bundle Engine which remaps your bundle's display name from the BSN to the Bundle-Name, for example, and you would probably want to register this once and apply it to all bundles without necessarily having to modify the bundles themselves to achieve that.

The original use case that I suggested in my OP also falls into this category: in my situation, I am developing iDempiere plugins and I sometimes have more than one plugin bundle in a test run (each plugin bundle having its own corresponding test bundle). `iDempiere` has a data dictionary and each instance maintains a cache of that dictionary. None of my test bundles or bundles-under-test affect the data dictionary while they are running, but during development I often iteratively modify the data dictionary through another iDempiere instance connected to the same backend database. When the test re-runs, these changes to the data dictionary are not reflected in the tests because the cache in iDempiere test instance has not been flushed. At the moment I can't fix this other than by manually restarting my test instance, or by automatically flushing the data dictionary in a class-level `@BeforeAll` callback. Neither approach is the most efficient - because I know that the data dictionary remains static throughout the test, the most efficient time to flush it is when the test run starts. The would be done in a `BeforeAllBundles` callback, and it would probably not make sense for it to be registered in any one of my test bundles, but more sensibly it would be defined & registered once in the idempiere-test utility bundle that they all rely upon.

> > Should a separate set of callbacks be introduced for the "fragment" level of the hierarchy,
> 
> This seems wrong. Fragments do not have an activation lifecycle. They are attached to bundles (perhaps multiple bundles) and the bundles have an activation lifecycle.

But I think you're confusing the bundle/fragment activation lifecycle with the test execution lifecycle. The test execution lifecycle doesn't necessarily follow the bundle activation lifecycle, and within a test execution there is a definite and well-defined lifecycle for a fragment that is distinct from the host bundle it is attached to (in the same way that a test method lifecycle is distinct from the test class lifecycle of which the test method is a member).

**Comment by bjhargrave** [comment]
> However, I am not proposing using annotations for this

How will the BundleEngine discover these callbacks? Must a bundle run an activator to register them as OSGi services? This would mean a timing issue between the bundle registering these callback services and the BundleEngine processing the bundle's tests. It would require the test bundle to register any such lifecycle callbacks in its activator to ensure they are registered prior to any test selection. And since we process STARTING bundles, there is still a small timing window.

> Note that even in Jupiter, global extensions are not registered using annotations (for the reasons you outline), but through the `ServiceLoader` mechanism

Those are not test execution lifecycle callbacks. So I don't think this is comparable to your ideas here.

> The case I am envisaging is similar to what global extensions in Jupiter are set up to handle. In Jupiter, a global extension applies to all running tests

This seems completely different to lifecycle callback which is the subject of this issue. Here you seem to be talking about getting extensions (aka `@ExtendWith`, `@RegisterExtension`) from the service registry. Perhaps we need to clarify what it is you are suggesting here.

I think using OSGi services also has timing issues. In the current case the test engine is solely responsible for discovery (annotation scanning, service loader calls) and instantiation but using OSGi services means that timing of the starting of bundles can cause issues with the test engine discovering (via the OSGi service registry) extensions after test execution has begun. And what if an extension service is unregistered during test execution? 

There is a life cycle mismatch between test discovery and OSGi service discovery. The former is under full control of the test engine and cannot be removed while in test execution. The latter is completely out of control of the test engine and can be added or removed at any time during test execution.

So I don't think OSGi services are a proper fit for use with testing extensions or lifecycle callbacks.

**Comment by kriegfrj** [comment]
> > However, I am not proposing using annotations for this
> 
> How will the BundleEngine discover these callbacks? Must a bundle run an activator to register them as OSGi services? This would mean a timing issue between the bundle registering these callback services and the BundleEngine processing the bundle's tests. It would require the test bundle to register any such lifecycle callbacks in its activator to ensure they are registered prior to any test selection. And since we process STARTING bundles, there is still a small timing window.
> 

The short answer is yes, that is what I was thinking. However, I admit to not being fully aware of the timing issues when I wrote the above (in particular with regard to lazy activation, which I recently discovered the hard way).

The only sensible alternative I can think of rather than services is a manifest header that lists the callbacks. Either a new one, or else re-purpose the Test-Cases header to allow it to contain references to bundle-level-and-higher callbacks. But then, why can't that header simply be a Provide-Capability for the relevant callback interface service?

> > Note that even in Jupiter, global extensions are not registered using annotations (for the reasons you outline), but through the `ServiceLoader` mechanism
> 
> Those are not test execution lifecycle callbacks. So I don't think this is comparable to your ideas here.
> 

Global extensions in Jupiter can implement any of the extension interfaces, including lifecycle callbacks. At least, that is my understanding - it is possible to write a class that implements (eg) `BeforeEachCallback`, register that class globally using the `ServiceLoader` mechanism, and thereby have it applied automatically to each test class when it runs.

> > The case I am envisaging is similar to what global extensions in Jupiter are set up to handle. In Jupiter, a global extension applies to all running tests
> 
> This seems completely different to lifecycle callback which is the subject of this issue. Here you seem to be talking about getting extensions (aka `@ExtendWith`, `@RegisterExtension`) from the service registry. Perhaps we need to clarify what it is you are suggesting here.
> 
> I think using OSGi services also has timing issues. In the current case the test engine is solely responsible for discovery (annotation scanning, service loader calls) and instantiation but using OSGi services means that timing of the starting of bundles can cause issues with the test engine discovering (via the OSGi service registry) extensions after test execution has begun. And what if an extension service is unregistered during test execution?
> 
> There is a life cycle mismatch between test discovery and OSGi service discovery. The former is under full control of the test engine and cannot be removed while in test execution. The latter is completely out of control of the test engine and can be added or removed at any time during test execution.
> 

I don't think that this is that big of an issue, but I admit to still be working through it in the light of what you wrote above.

It is true that the lifecycle of services is in theory independent of the test discovery and outside the control of the tester bundle. In practice, however, the lifecycle of services is under the control of the developer assembling the test suite - and it would be a silly developer who arranged for the extension service to disappear during a test. Note also that bundle lifecycle is not strictly under the control of the test discovery either and it possible for a bundle to be closed during a test. This doesn't make it unworkable - just means that the test developer has to be careful not to close bundle during the test.
