### ISSUE TITLE
P2 repository is broken

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#4589]
https://bndtools.jfrog.io/artifactory/update-snapshot/ seems not to contain the necessary files if one browse the link the usual p2.index, content.jar and artifacts.jar are missing, this causes problems for consumers of the repository see https://www.eclipse.org/lists/tycho-dev/msg01852.html for example.

**Comment by bjhargrave** [comment]
The URL is a virtual p2 repository in Artifactory. It works for Eclipse to install/update Bndtools. But if you browse to the folder, it appears empty. But if you ask for the specific file (as Eclipse does), then they will be served.

So there is nothing for us to do here.

**Comment by bjhargrave** [comment]
BTW, if you need access to the Bndtools jars in a maven build, you don't need to use the p2 repo. They are avaiable from the maven repo <https://bndtools.jfrog.io/bndtools/libs-release-local/>.

**Comment by bjhargrave** [comment]
Closing as the Bndtools p2 update repositories work for their intended purpose of installing Bndtools into Eclipse.
