### ISSUE TITLE
[gradle] export task with custom exporter suddenly starts failing

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4607]
We have one Projects, that uses the 5.4.0-SNAPSHOT in its build (living on the edge you know...). The build suddenly started failing and the Fix was to go back to 5.3.0. Thus I suspect that a change to the gradle plugin may have caused it. 

The Exception:

```
* What went wrong:
A problem occurred evaluating project ':com.playertour.backend.runtime'.
> Could not find method exporter() for arguments [gecko.export] on task ':com.playertour.backend.runtime:geckoExport' of type aQute.bnd.gradle.Export.

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':com.playertour.backend.runtime'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
------ a lot of lines I removed because it didn't look important enough -----
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method exporter() for arguments [gecko.export] on task ':com.playertour.backend.runtime:geckoExport' of type aQute.bnd.gradle.Export.
	at org.gradle.internal.metaobject.AbstractDynamicObject$CustomMissingMethodExecutionFailed.<init>(AbstractDynamicObject.java:190)
	at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:184)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:86)
```

We have bndrun that should use our own exporter. The definition there looks like this:

```
-pluginpath:\
	${repo;org.gecko.runtime.bnd;latest}
	
-plugin.geckoexporter:\
	org.gecko.runtime.bnd.export.GeckoExporter
	
-exporttype: gecko.export;gecko.runtime.dir=${.}/runtime
```

To trigger it, we have a build.gradle in the the project that looks as follows: 

```
/*
 * build Gradle build script
 */
import aQute.bnd.gradle.Export

configurations {
  bundles
}

task geckoExport(type: Export) {
   description "Export playertour.bndrun"
   group 'export'
   bndrun "playertour.bndrun"
   exporter  'gecko.export'
}
```

The working  and failing build (Timezone is CEST):
![image](https://user-images.githubusercontent.com/8199490/113263990-c0c73400-92d2-11eb-8b93-9780a375df5c.png)

@bjhargrave might have something to do with https://github.com/bndtools/bnd/pull/4604 or https://github.com/bndtools/bnd/pull/4602

**Comment by bjhargrave** [comment]
Change to

```groovy
  bndrun = file('playertour.bndrun')
   exporter = 'gecko.export'
```

`exporter` is a property and not a method. So you really should be "setting" the property with `=`. Same for `bndrun`. It is a file property, so you should set it to a file value.

I made many changes to the Bnd Gradle plugins to modernize their implementations and pay off some technical debt. Gradle 7 has deprecated some old ways of working, so the Bnd Gradle plugins need to adapt.

**Comment by bjhargrave** [comment]
> @bjhargrave might have something to do with #4604 or #4602

FYI, the change that "caused" this is https://github.com/bndtools/bnd/commit/af0ae3c813e485d3035f7e233ed2b251ff0e7f08

**Comment by bjhargrave** [comment]
Closing as the fix was explained.
