### ISSUE TITLE
includeresource unroll to relative path

### ISSUE THREAD

**Issue by rymsha** [bndtools/bnd#4610]
bnd .gradle 5.3.0

Documentation has an example to unroll entire jar to a specific jar's folder 
`-includeresource folder=@jar`

*Actually, I don't think _syntax_ allows it, because assignment is not part of unroll
`iclause          ::= (unroll | copy) parameter*`
`unroll           ::= '@' (PATH | URL) ( '!/' SELECTOR )?`

There is also example to unroll specific files to jar's root
`-includeresource @jar/osgi.jar!/!(LICENSE|about.html|org/*)`

Is there any way to "unroll" and copy files without full path?
`-includeresource folder=@jar/a/b/*`
so jar will contain
`/folder/file`
not
`/folder/a/b/file`

**Comment by pkriens** [comment]
I do not think this is proper syntax? `@jar/a/b/*` since it would try to unroll _all_ files in the `jar/a/b` directory? As far as I recall, this wild carding does not work. If you mean `@foo.jar!/a/b/*`, I would expect the files in `b` to end up in `folder`.

If this is just a clarification, please discuss it at bnd.discourse.group. If you think it is an error, please provide a concrete example.

**Comment by rymsha** [comment]
Sorry for confusion, It is more like a feature request.
There is no correct syntax for this, it is just an example.

> If you mean @foo.jar!/a/b/*, I would expect the files in b to end up in folder.

Problem is, files in `b` end up in `/folder/a/b`, not in `/folder`

**Comment by bjhargrave** [comment]
Have you tried the `flatten` directive? https://bnd.bndtools.org/instructions/includeresource.html

`-includeresource    target/=hierarchy/;flatten:=true`

**Comment by rymsha** [comment]
`webjars=@momentjs-2.11.1.jar!/META-INF/resources/webjars/*;flatten:=true`
files endup in `/webjars//META-INF/resources/webjars/...`
(I want them in `/webjars/...`)

`webjars=@momentjs-2.11.1.jar!/META-INF/resources/webjars;flatten:=true`
files endup nowhere (well, probably because `/META-INF/resources/webjars` is a directory record in zip/jar)

so, `flatten` has no effect for unroll

**Comment by pkriens** [comment]
guess that was worth a try :-(

I am afraid I do not see a solution right now.

**Comment by juergen-albert** [comment]
I just stumbled upon this. @rymsha even if this issue is nearly a year old, what you asked for is now possible. https://bnd.bndtools.org/instructions/includeresource.html has now a rename, which is what you asked for here, as far as I can tell. You will find it under the unroll options.

**Comment by rymsha** [comment]
Thank you for an update. I'll try it out.
