### ISSUE TITLE
Return manifest attribute value when '%' prefix is not used

### ISSUE THREAD

**Issue by alexrobin** [bndtools/bnd#4619]
Shouldn't Domain.translate() method return the attribute value instead of 'null' when manifest value doesn't start with '%'? The code is at https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java#L80

Among other things, this prevents some values to be extracted from manifest to properly populate the index generated by SimpleIndexer.

Am I missing something?

**Comment by bjhargrave** [comment]
Thanks for this problem report!
