### ISSUE TITLE
Include-Resource exports all packages from the included bundle/JAR

### ISSUE THREAD

**Issue by strmecki** [bndtools/bnd#4631]
Hello,

I used the Include-Resource to embed an OSGi core bundle into a new bundle like this:
`Include-Resource: target/dependency/onecms.core-${onecms.core.version}.jar;lib:=true`

This works fine, but the problem is that the new bundles also export all packages from the embedded bundle.
I tried explicitly removing the exported package, but it doesn't seem to work:
`Export-Package: !com.client.onecms.core;version=1.0.0`

BR,
Daniel

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by strmecki** [comment]
Hello, sure I can, but it's Adobe Experience Manager. Do you have a license for it so that you can test it?

**Comment by bjhargrave** [comment]
We need a _small_ github repo which focuses on the reported problem. I expect the problem has nothing to do with AEM (which I expect none of us have a license to.)

**Comment by strmecki** [comment]
Hello again,

I attached a small multi-module AEM project as an example. The problem is not related to AEM and you don't need to install the project, just build it and check the generated manifest. 

Wehn you run `mvn clean install` you will see that the "brand" module exports two packages:
`Export-Package: com.demo.brand;version="1.0.0",com.demo.core;version="
 1.0"`

However, in the bnd-maven-plugin configuration only one export is defined:
`Export-Package: com.demo.brand, !com.demo.core`

I believe the reason for this strange behavior is that the parent pom defines:
`-exportcontents: ${removeall;${packages;VERSIONED};${packages;CONDITIONAL}}`

So the bnd-maven-plugin is automatically exporting all versioned packages from the embedded bundle. 
This is a bug in my opition. I don't want the plugin to export packages from embedded dependencies.

[bndDemo.zip](https://github.com/bndtools/bnd/files/6389886/bndDemo.zip)

**Comment by strmecki** [comment]
@bjhargrave as a temporary solution to this problem, can I disable plugin from automatically exporting versioned packages?
I tried removing `-exportcontents: ${removeall;${packages;VERSIONED};${packages;CONDITIONAL}}` but nothing changed.

**Comment by bjhargrave** [comment]
You probably do not want to use both `Export-Package` and `-exportcontents`. `Export-Package` does two things. It adds the packages to the bundle _and_ it marks them for export. `-exportcontents` only marks packages for export. So using them both can do something you don't really way. In this case, you probably only want to use `-exportcontents`. You can use `-includepackages` if you need to add package to the bundle from the classpath.

**Comment by strmecki** [comment]
Thank you. Removing `-exportcontents: ${removeall;${packages;VERSIONED};${packages;CONDITIONAL}}` from the parent pom and replacing `Export-Package: com.assaabloy.brand.*;` with  `-exportcontents: com.assaabloy.brand.*;` in the bundle pom seems to be working fine.

**Comment by bjhargrave** [comment]
Great. So I will close this issue. Remember, you can ask Bnd usage questions in the Bnd Discourse Group. See <https://github.com/bndtools/bnd#feedback>.

**Comment by strmecki** [comment]
Will do @bjhargrave. Just one last related question: is it possible NOT to register services from an embedded OSGi bundle?
The idea is to use it as a library, but all services/filters/schedulers inside it get automatically registered in the OSGi container.

**Comment by bjhargrave** [comment]
I would ask you to pose that question in the [Bnd discourse group](https://bnd.discourse.group/).
