### ISSUE TITLE
Getting 'Error: Could not find or load main class aQute.launcher.Launcher'

### ISSUE THREAD

**Issue by vorajeem** [bndtools/bnd#4641]
Hi,
I am getting the following error ```Error: Could not find or load main class aQute.launcher.Launcher``` when I run my .bndrun file.  

I had to reinstall my PC along with all the dev environment software. However, when I re-installed Java/Eclipse/bndtools I could not get my code to work. My code had been working using my original setup using Bndtools 4.2.0 and Eclipse 2020-03.

My .bndrun file (called stub.bndrun) does not run in Eclipse, but it works perfectly when I run it on the command line (i.e. using ```bnd stub.bndrun```)

 This issue is similar to bug fix #2947 but even after reading the comments, I haven't been able to solve my problem.(https://github.com/bndtools/bnd/issues/2947)

Some of my current setup info is given below:
 - Eclipse 2020-03 (Eclipse IDE for Enterprise Java Developers.)
- Java 8 (OpenJDK)
- Ubuntu 16.04 Desktop edition
- Bndtools 5.3.0.REL

(EDIT: I have also tried using Eclipse 2021-03 with Bndtools 5.3.0.REL, but I am still getting the same error.)

I've run my ```stub.bndrun``` file with the option `-runvm -verbose:class` in Eclipse, and the console output is given in this text file attached.
[console_output.txt](https://github.com/bndtools/bnd/files/6389891/console_output.txt).

From the console output, it seems like all the Java packages are loaded successfully, but the aQute packages cannot be loaded correctly.

I have tried deleting the ```cnf/cache/``` directory and restarting Eclipse, but I still get the same error.

I see that the only file in the ```cnf/cache/biz.aQute.launcher/``` directory is ```biz.aQute.launcher.latest.jar```. (Do I need to change the name of this file??)

Here's the workspace which you can use to reproduce my issue: (https://github.com/vorajeem/bndtools_error_reproduce_public.git)

My apologies, I am a beginner in bndtools/OSGi development, so I don't know if I've messed up something in my Eclipse/Bndtools configuration. Your help would be much appreciated.

The issue is fully explained in my StackOverflow 
https://stackoverflow.com/questions/67190975/getting-error-could-not-find-or-load-main-class-aqute-launcher-launcher-in-ec

My apologies for posting the issue on both StackOverflow and Github issues, but after trying to fix this problem  - I still haven't found a solution.

Thanks

**Comment by bjhargrave** [comment]
You are not using the Bnd Gradle build (See the 5.3 branch: https://github.com/bndtools/workspace/tree/5.3). You are using Ferry Hubert's gradle build (https://gitlab.com/fhuberts/bndtoolsWorkspace). I have no idea if Ferry's gradle build works with the latest versions of Bnd and Bndtools. You probably need to either consult with Ferry or switch to the the Bnd Gradle build. I am not going to dig into why this is not working.

**Comment by vorajeem** [comment]
Cool. Thanks for the feedback.

**Comment by bjhargrave** [comment]
There are no tutorials for switching. I would suggest you copy the 5.3 branch, https://github.com/bndtools/workspace/tree/5.3, and move your code into the empty Bnd Workspace and then go from there. See https://github.com/bndtools/bnd/blob/5.3.0.REL/biz.aQute.bnd.gradle/README.md#gradle-plugins-for-bnd-workspace-builds for documentation on the Bnd Gradle plugin for Bnd Workspace builds.

**Comment by bjhargrave** [comment]
Closing as there is no present issue here. Please move this discussion to the Bnd Discourse Group. See <https://github.com/bndtools/bnd#feedback>.
