### ISSUE TITLE
Bndtools sync causes problems with non-bnd projects

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4646]
In the Bnd repo, we have a maven folder with maven projects nested.

<img width="213" alt="image" src="https://user-images.githubusercontent.com/277682/116737166-e1aca300-a9be-11eb-8e54-5f0f0c01f808.png">

When I updated to the latest 6.0.0-SNAPSHOT, I received 2 errors from Bndtools regarding syncing the workspace.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/277682/116737319-17ea2280-a9bf-11eb-9292-4644676b5634.png">

 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/277682/116737397-2d5f4c80-a9bf-11eb-8bd2-c98409311ec1.png">

<img width="681" alt="image" src="https://user-images.githubusercontent.com/277682/116737459-410ab300-a9bf-11eb-8908-69531df65acc.png">

The new syncing support does not hand this properly.

**Comment by bjhargrave** [comment]
I am also still seeing

<img width="402" alt="image" src="https://user-images.githubusercontent.com/277682/116828733-828d9080-ab6e-11eb-929f-6f1837224292.png">

When I restart Eclipse.

**Comment by pkriens** [comment]
I did a fix monday morning, I noticed this as well. Was a pretty bad bug

**Comment by bjhargrave** [comment]
I just installed the latest build with https://github.com/bndtools/bnd/pull/4649 and did not do anything to address this issue. I still get the exceptions in the error log and the popup dialog.

**Comment by pkriens** [comment]
You noticed it deleted the prject on disk? :-(

**Comment by pkriens** [comment]
I just took the latest release and it worked fine

**Comment by bjhargrave** [comment]
It never deleted anything on disc. I just get those exceptions in the error log and the popup dialog. I am happy to webex and show you.

**Comment by pkriens** [comment]
No, bnd accidentally deleted the project on disk. So you need make sure you have a clean git workspace. Was quite bad. That is why I had the saturday morning fix.

**Comment by bjhargrave** [comment]
OK, maybe you are talking about some problem other than the one I am talking about in this issue.

**Comment by pkriens** [comment]
the first one deleted some projects on disk. So unless you made sure those projects are restored, you would see this error?

**Comment by bjhargrave** [comment]
At no time did I see the maven folder deleted from my file system. I use a separate Eclipse workspace from the git working directory.

**Comment by pkriens** [comment]
ok, maybe that is different.

**Comment by pkriens** [comment]
let me try

**Comment by pkriens** [comment]
Yes, I have it here, let me check what is going on

**Comment by pkriens** [comment]
[type: ERROR], [path: null], [message: /Users/aqute/Ws/bnd/maven overlaps the location of another project: 'bnd-plugin-parent'], [plugin: org.eclipse.core.resources], [exception: null]

**Comment by bjhargrave** [comment]
> maven overlaps the location of another project: 'bnd-plugin-parent'

I merged a PR to have the maven folder also have the maven Eclipse project name. #4651 

But since I had to revert Bndtools to 5.4.0 as the sync workspace changes have made Bndtools unusable for Bnd development, I cannot test if the PR resolved this issue.

**Comment by bjhargrave** [comment]
This seems to have been addressed by https://github.com/bndtools/bnd/pull/4651 which changed the maven folder to be a bnd project named maven and an Eclipse project named maven.
