### ISSUE TITLE
Use extensionName in doIncludeFile as sufix instead of prefix

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4667]
When we include files from the `cnf/ext` directory we use the bnd file name as extensionname here: https://github.com/bndtools/bnd/blob/50c2aa5c946dc665eda58dd6943bb7d4425a147d/biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java#L1244

I had the expectation, that the extension would have been used as a namespace for the keys that are duplicates. For some reason this is not the case and `-plugin: whatever plugin` in `cnf/ext/foo.bnd` will become `foo.-plugin: whatever plugin`. This breaks any instruction and is hard to spot from the perspective of bndtools. With gradle and bnd itself, I can look at the final properties, but this is also something one needs to know. 

In my workspace, this is somewhat manageable. I'm currently implementing my workspace extensions. With them I use the `doIncludeFile` method in the end, but here it can really cause problems. I basically include external bnd files, and I can't be sure that my namespaces will be unique.

Thus I would suggest to simply use the extension name as a sufix.

**Comment by bjhargrave** [comment]
Can you make a PR?
