### ISSUE TITLE
Gradle Plugin breaks when adding Gradle buildSrc folder

### ISSUE THREAD

**Issue by lostiniceland** [bndtools/bnd#4668]
I came accross an issue which breaks the bnd.workspace plugin. When adding a buildSrc folder to add some additional Gradle plugin inside the project, Gradle fails with `'buildSrc' cannot be used as a project name as it is a reserved name`. From my work on the Bndtools Import-Workspace wizard, I remember that bnd treats all folders next to cnf as a project. The gradle-plugin is using this information to setup a Gradle project for each bnd project and fails for the bnd-project "bndSrc".

Here is my currently broken repo: https://github.com/lostiniceland/liberty-extensions

I tried to make use of the builderignore-instruction without success
`-builderignore: buildSrc,${if;${driver;gradle};bin,bin_test,generated;build;}`

When you comment everything in settings.gradle it works fine, but of course it is unusable then.

I think there is a general issue with the convention that every folder is a bnd project. Which is also the reason why the gradle-wrapper for bnd is using the folder `/.gradle-wrapper/` instead of just `/gradle/`. This is actually another issue: when you import a bnd-gradle workspace to Intellij it will recreate the gradle folder and mess with the `gradlew` and `gradlew.bat` files because by convention the Gradle wrapper has to reside in `/gradle/` (I could not find an option to change this convention in Gradle itself).

Without having dug to deep I think the quickest solution is to add a configuration to the gradle-plugin which allows to ignore folders during setup. In the long run I assume this should be done within bnd itself, which might also benefit the bnd-maven-plugin.

Reproduce:
Just add a folder named `buildSrc` next to cnf.

**Comment by bjhargrave** [comment]
If you apply the `biz.aQute.bnd.workspace` in `settings.gradle`, you are asking the plugin to calculate the folders to include in the gradle build. It does this based upon any tasks specified on the command line. But if no tasks are specified, it will include all folders in the rootDir (except for private folders starting with `.` like `.git`). 

But you have correctly identified that `buildSrc` is a special gradle folder and should not be included by default. I will make this fix. I will also update it to make sure the `gradle` folder is not included by default.

If you have special needs for which folders should be included in the build, you should not apply the `biz.aQute.bnd.workspace` in `settings.gradle` and instead apply it in the root `build.gradle`. You can then write your own folder include logic in `settings.gradle`.

> (I could not find an option to change this convention in Gradle itself).

https://github.com/bndtools/bnd/blob/50c2aa5c946dc665eda58dd6943bb7d4425a147d/build.gradle#L118 is how one sets the wrapper folder to use. See https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html#org.gradle.api.tasks.wrapper.Wrapper:jarFile. Intellij should be made to understand this and not always assume the wrapper location.

**Comment by lostiniceland** [comment]
I can confirm the fix works as expected. I tested the snapshot build on my repo.
Thanks

In case someone else is using the Kotlin DSL, this is how to apply the snapshot
```
buildscript {
  repositories {
    maven {
      setUrl("https://bndtools.jfrog.io/bndtools/libs-snapshot")
    }
  }
  dependencies {
    classpath("biz.aQute.bnd:biz.aQute.bnd.gradle:+")
  }
}
apply<aQute.bnd.gradle.BndWorkspacePlugin>()
```

**Comment by lostiniceland** [comment]
Though a minor remark. "build" seems to be the default Gradle output folder. Some plugins, like the liberty-gradle-plugin, write data to this folder.
Maybe "build" should be excluded as well.

**Comment by bjhargrave** [comment]
For a Bnd Workspace build, you should not be doing any work in the root project of the Bnd workspace. If you do work there, then any number of folder's could be written to.

**Comment by lostiniceland** [comment]
ok
