### ISSUE TITLE
Support Gradle toolchains and javaLauncher in Bndrun tasks.

### ISSUE THREAD

**Issue by chrisr3** [bndtools/bnd#4688]
Gradle 6.7+ allows Gradle tasks to use a different JVM than Gradle itself. This is done using [Gradle Toolchains](https://docs.gradle.org/current/userguide/toolchains.html). The most obvious use-case would be for the `Bndrun` task, to make it easier to choose precisely which JVM to use to execute `EmbeddedLauncher`:
```gradle
tasks.register('testOSGi', TestOSGi) {
    // etc...

    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(16)
    }
}
```
Bnd's currently seems to locate the `java` executable as follows:
- By consulting any `java` instruction in the `.bndrun` file.
- Checking for the existence of `$JAVA_HOME/bin/java`, for environment variable `JAVA_HOME`.
- Using the `java.home` system property to check for `${java.home}/bin/java`.

In my case, Bnd assigning higher precedence to the `JAVA_HOME` environment variable thwarts my efforts to determine Bnd's JVM via either of IntelliJ's "Project SDK" or "Gradle JVM" settings. However, Gradle toolchains could still allow me to choose a JVM without adding a `java` instruction to every `.bndrun` file.

**Comment by bjhargrave** [comment]
Bnd 5.3.0's Gradle Plugins support Gradle 5.3 (released 2019-03). The Bnd Gradle plugins for Bnd 6.0.0 now support Gradle 6.1 (released 2020-01) to handle API deprecations made in Gradle 7.1 for removal in Gradle 8. Adding a reference to the JavaLauncher type would require raising the minimum supported Gradle version to 6.7 (released 2020-10). It is a big jump from Gradle 5.3 to 6.7. I am not sure that is a good idea to jump that far.

**Comment by kriegfrj** [comment]
How hard would it be to take advantage of toolchains iff Gradle 6.7 is present?

**Comment by bjhargrave** [comment]
> How hard would it be to take advantage of toolchains iff Gradle 6.7 is present?

I tried and it does not work since gradle needs access to the generic type to create the proxy object.

**Comment by bjhargrave** [comment]
I made PR #4728 to add a javaLauncher property to the Bndrun and TestOSGi tasks.
