### ISSUE TITLE
Improve message for exports with private references

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4693]
Currently warnings for exported packages which have references to private packages look like this:

```
Export org.apache.jackrabbit.vault.fs,  has 1,  private references [org.apache.jackrabbit.vault.fs.impl]
```

It would be nice to get some more details about it like the class and method using the private reference.
Also the comma in the message seems wrong.

**Comment by kwin** [comment]
Changing the text leads to potentially breaking `fixupmessages` by consumers: https://github.com/bndtools/bnd/issues/3444

**Comment by pkriens** [comment]
There is a bnd xref command that can xref by class
