### ISSUE TITLE
bnd-(resolver|testing)-maven-plugins should quietly ignore pom packaging

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4696]
When configuring a build with a parent pom with `<packaging>pom</packaging>`, one has to go out of their way to configure the bnd maven plugins to not fail on the pom packaging projects. The `osgi-test` project has to do this for the resolver and testing plugins (which the osgi-test project uses).

The bnd maven plugins should just quietly ignore pom packaging projects.

**Comment by bjhargrave** [comment]
Never mind. There are tests which are pom package which use these plugins to resolve bndruns or test bndruns. So there are use cases where people may want to resolve/test in pom packaging projects...

**Comment by rotty3000** [comment]
Thanks for realizing it. 

`pom` packaging is a convenient for "assembly" oriented modules.

Here is an example https://github.com/rotty3000/osgi-config-aff/blob/main/pom.xml

**Comment by timothyjward** [comment]
For posterity, resolving a `pom` project is important for me too. I use the exporter plugin with `pom` projects to produce runnable outputs.
