### ISSUE TITLE
Where is the eclipse update site for eclipse bndtools plugin with version 3.4.0REL

### ISSUE THREAD

**Issue by skshyamal** [bndtools/bnd#4700]
Where is the eclipse update site for eclipse bndtools plugin with version 3.4.0REL?

Currently in the jfrog eclipse update site I see only the release from 4.0.X

**Comment by juergen-albert** [comment]
For questions like this, please use the https://bnd.discourse.group/

Regarding your question: you can use the repositories shown here: https://bndtools.org/installation.html

**Comment by bjhargrave** [comment]
Bintray was shutdown. So there is no place where very old versions of Bndtools are available for installation. 3.4.0 is from July 2017 which is now 4 years ago. The oldest version of Bndtools is 4.2.0 from the jfrog artifactory repository.

If you need very old versions of Bndtools, you can build them from their tags in this git repo and the archived [Bndtools repo](https://github.com/bndtools/bndtools/tree/3.4.0.REL) (at that time, Bnd and Bndtools lived in separate git repos) and then install them from that build.

**Comment by skshyamal** [comment]
> Bintray was shutdown. So there is no place where very old versions of Bndtools are available for installation. 3.4.0 is from July 2017 which is now 4 years ago. The oldest version of Bndtools is 4.2.0 from the jfrog artifactory repository.
> 
> If you need very old versions of Bndtools, you can build them from their tags in this git repo and the archived [Bndtools repo](https://github.com/bndtools/bndtools/tree/3.4.0.REL) (at that time, Bnd and Bndtools lived in separate git repos) and then install them from that build.

I find it really annoying when one artifact was released in past why that is not available in your infrastructure, something like you can say delete all 5 years old artifact from maven central which will be very unusual.

**Comment by bjhargrave** [comment]
> I find it really annoying when one artifact was released in past why that is not available in your infrastructure

I am sorry you are annoyed. This is an open source project staffed by volunteers who try to do the best job we can for people. But as a volunteer effort with no funding, we rely upon services and infrastructure provided by others (GitHub, JFrog, etc.) and we have no control over whether they continue to provide their services.

**Comment by bjhargrave** [comment]
I have found old Bndtools builds (including 3.4.0.REL) on my workstation. So I will try and upload them so that are visible on the JFrog update site.

**Comment by bjhargrave** [comment]
You can now install 3.4.0 from the JFrog update-latest URL.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/277682/121404166-ae4c2500-c929-11eb-8df8-2821410b74e1.png">

**Comment by stbischof** [comment]
Maybe Supriya Kumar Shyamal you or your company is able to give the project an sponsorship that helps to finance all long term support and infrastructure you wish.

Akaik ther is a sponsor button.

Thank you all lot for your support!
