### ISSUE TITLE
[Feature Request] Extend Differ to compare OBR XMLs

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#4711]
In many scenarios, people require to compare OBR XMLs directly but the current implementation supports only comparison between JARs comprising OBR XMLs. It would be really useful to extend the current implementation of `aQute.bnd.differ.DiffPluginImpl` for the support of OBR XML comparison.

**Comment by amitjoy** [comment]
I am just starting with the implementation. As soon as it gets finalized, I will link the PR to it.

**Comment by bjhargrave** [comment]
OBR (RFC 112) is obsolete. For a long time. Why do we want to add a differ for that?

It has long been replaced by the [Repository Service Specification](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.repository.html).

**Comment by amitjoy** [comment]
I always thought the `Repository Service Specification` is the extended version of `OBR` and that's why I mentioned `OBR` in the task's title. I actually meant the `Resource API` and `Repository Service Specification`. The current `differ` already supports it but I want to extend it in a way that it can compare two XMLs directly that follow XML repository schema.

**Comment by bjhargrave** [comment]
> I always thought the `Repository Service Specification` is the extended version of `OBR` and that's why I mentioned `OBR` in the task's title.

No. OBR was input to the Repository Service Specification design but Repository Service Specification is different in many ways and completely supersedes OBR. So one should not refer to Repository Service Specification as OBR. You wont find OBR anywhere in the spec text.


> compare two XMLs

XML diffing is very hard such that you want to avoid false positives. Good luck!

**Comment by pkriens** [comment]
1) OBR is the common name used in the field for the resource XML
2) Generic  XML diffing is hard, but diffing the 'OBR' XML is straightforward. A Resource & its Cap/Req is a tree that can map to the differ's tree model. We already represent this information as a manifest header.
