### ISSUE TITLE
[baselining] Narrowed return type should be a minor change

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4713]
I've just played with re-enabling the baseline for https://github.com/osgi/osgi-test, now that it has been released.

Since 1.0.0 we had a bunch of methods that have narrowed their return type - whereas in 1.0.0 they returned an abstract subclass, in HEAD they now return a concrete superclass.

The baselining plugin is complaining about this, but I think it is being overly aggressive in its suggestion. Here is a sample:

```
[ERROR] Baseline mismatch for package org.osgi.test.assertj.bundlereference, MAJOR change. Current is 1.0.0, repo is 1.0.0, suggest 2.0.0 or -
MAJOR                PACKAGE    org.osgi.test.assertj.bundlereference
  MAJOR              CLASS      org.osgi.test.assertj.bundlereference.AbstractBundleReferenceAssert
    MAJOR            METHOD     refersToBundleThat()
      REMOVED        RETURN     org.osgi.test.assertj.bundle.AbstractBundleAssert
      ADDED          RETURN     org.osgi.test.assertj.bundle.BundleAssert
  MAJOR              CLASS      org.osgi.test.assertj.bundlereference.BundleReferenceAssert
    MAJOR            METHOD     refersToBundleThat()
      REMOVED        RETURN     org.osgi.test.assertj.bundle.AbstractBundleAssert
      ADDED          RETURN     org.osgi.test.assertj.bundle.BundleAssert
```

Obviously in the general case where a return type changes this would be a breaking change and a major increment is warranted. But if it is changing to a type that is a subclass, I'd intuitively have thought I minor increment would be more appropriate.  Unless there is some detail about the binary compatibility that I am not appreciating that means that a major increment is necessary.

**Comment by timothyjward** [comment]
The baseliner is correct as per the JLS. See [13.4.14 and 13.4.12](https://www.cs.cornell.edu/andru/javaspec/13.doc.html#45197)

**Comment by kriegfrj** [comment]
> The baseliner is correct as per the JLS. See [13.4.14 and 13.4.12](https://www.cs.cornell.edu/andru/javaspec/13.doc.html#45197). You are correct that the change is source compatible, but a recompile is necessary to produce bytecode that will link against the new method signature.

Thanks for the reference!

> Is there any chance of adjusting the fix so that binary compatibility is maintained?

There is some chance. I'll have a look and see what we can do.

Maybe the Bnd baseliner could detect this situation and automatically add a synthetic method with the old return type that delegates to the new method. That would be gold! I vaguely remember the class file format supports two methods with the same signature but different return types, but the Java source does not.

**Comment by timothyjward** [comment]
> I vaguely remember the class file format supports two methods with the same signature but different return types, but the Java source does not. 

Yes, this is used by generics when making bridge methods. There's a good discussion [here](http://www.angelikalanger.com/GenericsFAQ/FAQSections/TechnicalDetails.html#FAQ103). It would probably be easier to keep the return type though, as I'm not sure that we want to start bytecode generating... @bjhargrave WDYT?

**Comment by kriegfrj** [comment]
> > I vaguely remember the class file format supports two methods with the same signature but different return types, but the Java source does not.
> 
> Yes, this is used by generics when making bridge methods. There's a good discussion [here](http://www.angelikalanger.com/GenericsFAQ/FAQSections/TechnicalDetails.html#FAQ103).

More directly relevant to current case is when you override a superclass method and narrow the return type- the compiler generates a synthetic bridging method to maintain binary compatibility. 
> It would probably be easier to keep the return type though, as I'm not sure that we want to start bytecode generating... @bjhargrave WDYT?

It would definitely be easier for this single instance to fix the return type. The idea about byte code generation was an idea for another day. 😄

**Comment by bjhargrave** [comment]
> The baselining plugin is complaining about this, but I think it is being overly aggressive in its suggestion. Here is a sample:

I am not sure why you see this. I ended up reverting the change to use concrete types in the 1.0.0 release since assertj-core reverted their change in 3.20.2.

https://github.com/osgi/osgi-test/blob/8a93911e57d99efd2510a7dc5f3af8863f280709/org.osgi.test.assertj.framework/src/main/java/org/osgi/test/assertj/bundlereference/AbstractBundleReferenceAssert.java#L47-L51

Perhaps you polluted your local .m2 cache by building and installing a 1.0.0 version before it went final. Please clear your local m2 cache of osgi-test 1.0.0 artifacts and try again.

**Comment by bjhargrave** [comment]
> t would probably be easier to keep the return type though, as I'm not sure that we want to start bytecode generating...

We do not want Bnd to generate bytecodes. And this case does not really exist as @kriegfrj seems to have a polluted m2 cache. The actual final 1.0.0 binaries use the abstract types like the main branch with the 1.1.0 stream.

**Comment by kriegfrj** [comment]
> Perhaps you polluted your local .m2 cache by building and installing a 1.0.0 version before it went final. Please clear your local m2 cache of osgi-test 1.0.0 artifacts and try again.

It must have been something like this. As it happens I've just been trying this this on a different machine with baselining enabled and the build is fine, as was my CI build on my fork.
