### ISSUE TITLE
[junit-platform tester] Add Require-Capability declarations for test engines

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4719]
Now that junit-team/junit5#2544 is merged and will be part of the JUnit 5.8 release, it would be nice if Bnd came to the party for the Require-Cap side of the equation.

The end-goal is to be able to generate test fixtures with a minimum of configuration necessary. If the test bundles explicitly declare their requirement on a particular test engine, then the resolver can take care of ensuring that that engine is part of the assembled test bundles; and if bnd can further ensure that the test bundle has the correct Req-Cap header in it for the test engine(s) that it requires, then the resolver will be able to take care of most of it. When combined with an implementation of #3795, all the user will need to do is make sure that their test bundle is in `-runrequires` and the resolver will take care of the rest.

We had a discussion in the OSGi tech channel back in Jan 2021 as to how this should be implemented. Options discussed where:
* An annotation that test writers would need to include in their tests. Disadvantage: not seamless as it puts the burden back on the developer to include the annotation in at least one of their test classes or on the package-info.java.
* Meta-annotate the JUnit test annotations. This has a couple of disadvantages:
   * It introduces compile-time dependencies on OSGi for JUnit even though many users of JUnit won't want or need OSGi (bit of a showstopper).
   * JUnit 4 is not being actively developed anymore; it is not known when (or even if) the next release would be that could include the necessary Req-Cap annotation on the JUnit 4 `@Test` annotation.
* Modify Bnd with some special-case code to generate the necessary Req-Cap

In the end, we agreed that the third would be the best approach. As @rotty3000 noted, there is precedent for this with the api-guardian support that we added.

There are two complicating factors:
1. There will still be older versions of the engine bundles without the `Provide-Cap` headers in circulation for some time to come. 
2. There will be some bundles that are still intended to run with `biz.aQute.tester`.

I think we could take care of the second by adding a `Provide-Cap` header for junit-vintage-engine to `biz.aQute.tester` and `biz.aQute.junit` (might raise a separate issue for this one). That just leaves the first issue.

A couple of ways to handle the backward compability issue:
1. Add Req-Cap, mandatory by default. Don't care about backward compatibility as we are incrementing a major version for Bnd now anyway. Disadvantage: need to wait for JUnit 5.8 to be released before this becomes feasible.
2. Add Req-Cap by default, but optional.
3. Make behaviour configurable as to whether to make it mandatory, optional or not included at all. In this case, there is a further question as to which of these the default behaviour should be.

I'm leaning towards 3, with optional requirement as the default (should still be backward compatible). Something like this:

```
-require-testengine: [none | optional | mandatory] (default: optional)
```

I'm open to suggestions on the exact syntax.

**Comment by rotty3000** [comment]
Before we go to far down this path can we try something first? I have an additional [PR on Junit5](https://github.com/junit-team/junit5/pull/2654) which brings this much further along.

When I've tested this:
- I only added `-tester: biz.aQute.tester.junit-platform`
- I no longer have to specify additional dependencies in my `-runrequires` like:
  ```
  bnd.identity;id='junit-jupiter-engine',\
  bnd.identity;id='junit-platform-launcher'
  ```

The only requirement is that the dependencies have to be in one of your resolve repos. Outside of that the rest is handled by the resolver.

**Comment by kriegfrj** [comment]
> Before we go to far down this path can we try something first? I have an additional [PR on Junit5](https://github.com/junit-team/junit5/pull/2654) which brings this much further along.
> 
> When I've tested this:
> 
> * I only added `-tester: biz.aQute.tester.junit-platform`
> * I no longer have to specify additional dependencies in my `-runrequires` like:
>   ```
>   bnd.identity;id='junit-jupiter-engine',\
>   bnd.identity;id='junit-platform-launcher'
>   ```
> 
> The only requirement is that the dependencies have to be in one of your resolve repos. Outside of that the rest is handled by the resolver.

I made a review pass on your PR; I wasn't sure if it was best to continue the discussion here or there...

**Comment by kriegfrj** [comment]
@bjhargrave, @rotty3000 and I have thrashed this out in junit-team/junit5#2654 and @rotty3000 has come up with a solution that will work for Jupiter without a need for this ticket. JUnit 3/4 will require manual intervention by the developer to add the necessary Require-Capability to your test bundle. As this is not a common case (and will become less common over time as Jupiter supplants JUnit 3/4), we don't consider it worthwhile to go to the effort of implementing an automated fix for it.
