### ISSUE TITLE
SInce 5.x VersionRange.toFilter does not correctly handle atleast versions

### ISSUE THREAD

**Issue by bpapez** [bndtools/bnd#4720]
Since version 5.x we see that `new VersionRange("3.5").toFilter()` wrongly resolves to` (&(version>=3.5.0)(version<=3.5.0))` whereas before it used to correctly resolve to `(version>=3.5.0)`

The specification states that passing a single version without any brackets to a version range means "at least" . http://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#i3189032
> If a version range is specified as a single version, it must be interpreted as the range [version,∞)

This commit seems to have changed that:
https://github.com/bndtools/bnd/commit/67f9d2c245af9374615c9672379da50d797b7687#diff-e31b8d0090ba489e8ccbc4538765a5052836cfbaea0543b8637d5a6a8cc286ae

**Comment by bjhargrave** [comment]
> new VersionRange("3.5").toFilter()

I think you want `VersionRange.parseOSGiVersionRange("3.5").toFilter()`.

The VersionRange constructor does not do what you want. Using the constructor on a single version will result in an exact range.

**Comment by bjhargrave** [comment]
> Using the constructor on a single version will result in an exact range.

But that seems wrong. I'm testing a fix to the constructor.
