### ISSUE TITLE
[bndtools] Rhyme and reason for the package names

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4723]
As we discussed in the last Bndtools meeting, we're looking at modularizing bndtools to make it more friendly for testing & development.

I thought this might be a good opportunity for us to stop and reflect on our package naming conventions, so that we can standardize these as we modularize the project.

Some of the packages and bundle BSNs follow the naming convention `bndtools.*`. Others are `org.bndtools.*`.

In all of the bundles with BSN following the longer convention (`org.bndtools.*`), all the packages do too. The same is not true for all of the `bndtools.*` bundles - some of them contain packages using the longer convention as well as the shorter convention.

Is there a pattern to this that I have not detected (eg, one convention is for public packages and the other for private)? Or is one of them a legacy convention and the other preferred?

With Bnd itself, the bundle BSNs follow the longer pattern while the package names follow the shorter convention. This does not appear to be consistently the case with Bndtools however.

If there is no pattern or reason behind the different conventions, should we adopt one? Should we try and emulate the convention that Bnd is using?

**Comment by pkriens** [comment]
History ... @njbartlett started bndtools independently from bnd. I had to fly to London and beat him up to start working together :-) although in different repositories. (This was still CVS I recall.) I think Neil picked the bndtools names. Then we moved to Github and after Neil became less active we merged the repositories.

I really like the pattern because it sorts very well:

        <organization> '.' <logical> '.' <physical> '.' <type>

A related aspect of the history is that significant functionality was developed on the bndtools site that logically should have been part of the bnd side. For example, Neil drove the resolver but did all of it on the bndtools side.

All said, I think we probably should stick with `org.bndtools` for any Eclipse UI code and `biz.aQute.bnd` for any library code. I am not a fan of renaming existing packages.

**Comment by kriegfrj** [comment]
Interesting history. I was aware of some of it - my first issues/prs were on the split repos. 
> All said, I think we probably should stick with `org.bndtools` for any Eclipse UI code 

Is this for bsns, package names, or both?

> I am not a fan of renaming existing packages.

For public API I understand, but for Bndtools it's really all private api. I doubt there are too many 3rd party libraries out there using Bndtools as a library. Plus, we're changing a major version this time around so people shouldn't expect backward compatibility. I am happy to defer to your greater experience though.

**Comment by njbartlett** [comment]
Peter is correct that this inconsistency is mostly my fault. The bare `bndtools.*` name seemed to make sense initially when Bndtools was just a single Eclipse plugin (bundle) and all packages were private. As we extended it to multiple bundles, a more conventional naming scheme of `org.bndtools.*` made more sense.

**Comment by pkriens** [comment]
> is mostly my fault. 

I don't think it was a fault. And if it is, it might have been inspired by my use of 'aQute.bnd' before I was beaten in submission to conform to the Java naming rules. Although one tiny letter still holds out against the confirmists  ... :-)

**Comment by kriegfrj** [comment]
I'm not sure how I trip closing these by accident...

**Comment by kriegfrj** [comment]
So if I can summarize the discussion so far:

* We should make new bundles and packages follow the more traditional convention `org.bndtools`.
* For existing bundles/packages: @pkriens is against renaming them to bring them into line. I'm tentatively for it...

**Comment by bjhargrave** [comment]
> So if I can summarize the discussion so far:

Basically business as usual. I am not sure I see anything new to be done here.

**Comment by pkriens** [comment]
> I am not sure I see anything new to be done here.

We could change the upper case `Q` for a lower case `q` in aQute? That would be fun! 🤓

**Comment by pkriens** [comment]
we can close this I think.
