### ISSUE TITLE
Debugging Gradle TestOSGi tasks via IntelliJ

### ISSUE THREAD

**Issue by chrisr3** [bndtools/bnd#4748]
I have discovered that I can add the following line to a `.bndrun` file to tell Bnd to expect an external debugger:
```
-runjdb: <port-number>
```
This works, but requires people to edit the `.bndrun` files when they want to debug their `TestOSGi` tasks, and then remove the line again when they have finished debugging. Is there a way that this `runjdb` option can be passed to the `ProjectLauncher` from a Gradle command line please? This would allow people to create separate Run/Debug configurations in IntelliJ without needing to edit the `.bndrun` files at all.

**Comment by kriegfrj** [comment]
I don't know a direct answer to your question, but it is possible to have multiple .bndrun files and specify which one. You could have your main .bndrun file and then a debug one which -includes the main file and adds the -runjdb option.

**Comment by bjhargrave** [comment]
Bnd also looks for properties in the system properties, so you could pass it that way also. For example:

```
➜  java -D-runjdb=1000 -jar biz.aQute.bnd/generated/biz.aQute.bnd.jar shell -p biz.aQute.bnd       
Base biz.aQute.bnd
> -runjdb
1000
> exit
➜  java -jar biz.aQute.bnd/generated/biz.aQute.bnd.jar shell -p biz.aQute.bnd 
Base biz.aQute.bnd
> -runjdb
${-runjdb}
-----------------
Warnings
000: No translation found for macro: -runjdb
> exit
```

**Comment by kriegfrj** [comment]
Did either of these two suggestions solve the problem to your satisifaction, @chrisr3 ?

**Comment by chrisr3** [comment]
Hi, sorry for the delay. We would like to avoid touching the `.bndrun` files at all, but it looks like `-D-runjdb=xxxx` might do the trick. I still need to test how it works in practice though.

Thanks for replying,
Cheers,
Chris

**Comment by chrisr3** [comment]
Yes, creating a "Run Configuration" with this JVM argument:
```shell
-D-runjdb=1044
```
and these Gradle tasks:
```shell
:mymodule:cleanTestOSGi :mymodule:testOSGi
```
is enough to configure IntelliJ to execute the `TestOSGi` task for debugging :partying_face:. All it needs do now is notify IntelliJ of the tests' outcome, and I'm _hoping_ I can do that by adding some JUnit `TestExecutionListener` service component into the OSGi framework :crossed_fingers:.

**Comment by kriegfrj** [comment]
> Yes, creating a "Run Configuration" with this JVM argument:
> 
> ```shell
> -D-runjdb=1044
> ```
> 
> and these Gradle tasks:
> 
> ```shell
> :mymodule:cleanTestOSGi :mymodule:testOSGi
> ```
> 
> is enough to configure IntelliJ to execute the `TestOSGi` task for debugging 🥳.

🍾 

> All it needs do now is notify IntelliJ of the tests' outcome, and I'm _hoping_ I can do that by adding some JUnit `TestExecutionListener` service component into the OSGi framework 🤞.

I'm glad to have found someone else interested in this. I started playing with some of these ideas but haven't had a chance to follow through as yet. You might want to take a look at #4762 for reference on how to write a a `TestExecutionListener` - it's pretty easy. But some kind of mechanism for redirecting the test output through Gradle would have additional uses beyond simply IntelliJ integration (eg, you can adjust the detail output level from the testing on the Gradle command line), 

My idea to do what you've suggested was to use remote services - the testOSGi task would register a server object logging service, and a client bundle with a remote client for that service. There are a couple of different ways this could be done in a Gradle context; but my investigation hasn't progressed very far as I don't have the time. But here are some high-level thoughts.

Option 1: Use `TestExecutionListener` as the remote interface. The server object implements this interface and logs test output appropriately to the Gradle environment, client implementation implements the interface, connects to the server and redirects calls through the server. I suspect that Gradle might have its own `TestExecutionListener` implementation for its own Java test task implementation; it might be possible to leverage the built-in implementation to implement the server-side part of this interface. Or indeed, Gradle might already have some remote implementation it injects into forked tests.

Option 2: Use one SLF4J's interfaces as the remote interface. On the client side, this becomes your SLF4J binding that remotely connects to the server's SLF4J instance and redirects all logging through the server instance.

Advantage of 1: likely to work better for test output. Disadvantage: you might miss some of the other logging that your application-under-test emits.

Option 3: some kind of hybrid of 1 & 2 to get the best of both worlds.

**Comment by chrisr3** [comment]
> I'm glad to have found someone else interested in this. I started playing with some of these ideas but haven't had a chance to follow through as yet. You might want to take a look at #4762 for reference on how to write a a `TestExecutionListener` - it's pretty easy.

Heh, my mission is to integrate with IntelliJ and so I am expecting IntelliJ to be large constraint in whatever I end up doing. _However_, IntelliJ already receives JUnit test results when it delegates test execution _directly_ to Gradle, and so I have good reason to hope that JUnit's `TestExecutionListener` is already involved... :pray:.

**Comment by bjhargrave** [comment]
Can we close this since you can set -runjdb in the system properties in the launch?
