### ISSUE TITLE
Finer-grained error handling for unused packges in Import-Package instruction

### ISSUE THREAD

**Issue by chrisr3** [bndtools/bnd#4775]
Bnd supports a [`-consumer-policy`](https://bnd.bndtools.org/instructions/consumer_policy.html) to provide a global "versioning mask". Package-specific version policies are documented as being set via the `Import-Package` instruction:
```
Import-Package com.gavinking.*;version="${range;[--,++)}", *
```
(Note: Should that be `[==,++)` rather than `[--,++)`?)

However, unused packages in an `Import-Package` instruction currently generate a warning:
```
warning: Unused Import-Package instructions: [com.example.foo.*] 
```
The `-fixupmessages` instruction can only suppress this warning completely, whereas for my use-case I would only want to suppress it for certain packages.

Could we add an extra directive to the `Import-Package` instruction please, e.g.
```
Import-Package: com.example.foo.*;unused:=(ignore|warn)
```
At which point, my package-specific `consumer-policy` could become:
```
Import-Package: \
    << ordinary package import instructions >>, \
    com.example.foo.*;version="${range;[==,++)}";unused:=ignore, \
    com.example.bar.*;version="${range;[==,++)}";unused:=ignore, \
    com.example.mumble.*;version="${range;[==,++)}";unused:=ignore, \
    *
```

**Comment by rotty3000** [comment]
Why do you say "The -fixupmessages instruction can only suppress this
warning completely"?

Aren't there examples of doing this in the bnd project? Is it possible that
you forgot to escape some special characters? fixupmessages has glob
pattern support.

Ray

**Comment by chrisr3** [comment]
So if I have _N_ packages that I would like to set a `consumer-policy` for, and given that this warning message may contain any of these package filters in any order, what would my glob look like?

**Comment by bjhargrave** [comment]
Another option would be to _not_ warn for unused wildcard patterns. Only warn for unused non-wildcard patterns. After all, we don't warn for the unused wildcard pattern `*`.  I guess I would rather not add a new `unused:` directive which needs to be documented.

**Comment by chrisr3** [comment]
> Another option would be to _not_ warn for unused wildcard patterns. Only warn for unused non-wildcard patterns. After all, we don't warn for the unused wildcard pattern `*`. I guess I would rather not add a new `unused:` directive which needs to be documented.

Yes, that approach would also work for me. I would only be applying my consumer policy to a collection of wildcard patterns.

**Comment by kriegfrj** [comment]
> Another option would be to _not_ warn for unused wildcard patterns. Only warn for unused non-wildcard patterns. After all, we don't warn for the unused wildcard pattern `*`. I guess I would rather not add a new `unused:` directive which needs to be documented.

:+1:

I had a similar issue when adding OSGi metadata to API Guardian/JUnit 5 - a number of imports across the build which, if used, should have been optional. But not all bundles in the build reference all packages, so either you have to tailor an `Import-Packages` directive for each one or else you get the warnings. We got around it with fixupmessages (@rotty3000 had already laid the groundwork on that approach), but I only had a handful of import declarations so I didn't have to deal with too many combinations. It would not be a manageable workaround for large N.

**Comment by bjhargrave** [comment]
> Another option would be to _not_ warn for unused wildcard patterns. Only warn for unused non-wildcard patterns.

So I played with this. Bnd only ever warns for unused wildcard values. The use of a non-wildcard value is assumed to be a manual "add". So not warning for unused wildcard values means removing the warning entirely.

There is already support in Bnd to ignore "optional" instructions but there is no way to set the optional-ness of the instruction. So I will add a `o` flags which can be set by suffixing the package glob with `:o`. For example:

    com.example.foo.*:o;version="${range;[==,++)}"
