### ISSUE TITLE
[bndtools] Hover for macro expansion

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4791]
I was working on a bnd file the other day and really wanted to know what the expansion was for the macro/property that I was was looking at.

It would be handy if you were able to hover the mouse over the macro and have a tooltip pop up with an expansion. It would also be good if the same tooltip could be triggered by a key combination so that it could be conveniently available while using the keyboard without having to switch to the mouse.

**Comment by pkriens** [comment]
Select the text and hover with the  mouse over the selection:

https://bnd.discourse.group/t/macros-as-functions/50

**Comment by kriegfrj** [comment]
Thank you. I knew I had seen a similar feature somewhere but couldn't recall where. 

I think it would be a great enhancement if you didn't have to select the text first. Intuitively that's how I expected to use it, and also users are more likely to discover it accidentally when they move the mouse.

**Comment by pkriens** [comment]
Without text selection it becomes awfully annoying and it makes it very hard to decide  what the scope to be evaluated is.I did that first and I did not like it.

**Comment by kriegfrj** [comment]
What was your heuristic for determining what to evaluate? If you were doing it every time you hovered anywhere in a property that would be annoying, but if you only did it when you hovered over an actual macro and evaluate the narrowest scope containing the hover point, I can't imagine it would be too intrusive? Maybe it is...

**Comment by bjhargrave** [comment]
Figuring out the bounds of the narrowest scope can be quite hard. There is also the case of viewing the result of sequential macros. So evaluating selected text relies upon the user to select what is to be evaluated.
