### ISSUE TITLE
[bndtools] Use `split()` rather than `newChild()`

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4805]
I suggest using `split()` rather than `newChild()`. The main functional difference is that `split()` will efficiently do cancelation checks for you whereas `newChild()` will not do any cancelation checks. The only reason to use `newChild()` is if you need compatibility for Eclipse < 4.6 (which we don't).

There are a few other instances of `newChild()` here too. But this is an old issue so it might make sense to fix these in a new, dedicated PR.

_Originally posted by @kriegfrj in https://github.com/bndtools/bnd/pull/4789#discussion_r689931971_

**Comment by kriegfrj** [comment]
Updated the title as it is not only the m2e plugin that has this issue.
