### ISSUE TITLE
Message that bnd-resolver-maven-plugin is missing comes to often

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#4856]
The newly introduced message that a bndrun can't be resolved appears in to many cases, even in some bnd files.

![image](https://user-images.githubusercontent.com/8199490/134162657-7f32cabc-be50-4c06-bf65-d6c8d4a48231.png)

@bjhargrave I'd like to improve this behavior before the 6.0.0 release.

**Comment by bjhargrave** [comment]
When did this start? After the fix for #4320?

**Comment by juergen-albert** [comment]
No, it came with PR  https://github.com/bndtools/bnd/pull/4794
