### ISSUE TITLE
[6.1 DEV] Opening the Build Path Dialog takes very long

### ISSUE THREAD

**Issue by maho7791** [bndtools/bnd#4857]
Opening the Project Buildpath Dialog takes more than 10 seconds. Every time I click it. In addition to that, during this time the UI is blocked.

OS: Linux Ubuntu 20.04, GTK3

![Bildschirmfoto von 2021-09-23 12-20-12](https://user-images.githubusercontent.com/8199528/134491774-f8949763-b3d2-4f2b-a6f0-f02a6c606305.png)

**Comment by stbischof** [comment]
This is a maven project and Eclipse M2E support.

**Comment by maho7791** [comment]
No its is a gradle based workspace

**Comment by pkriens** [comment]
Closing it for inactivity. Can always be reopened if still an issue
