### ISSUE TITLE
[m2e] Native launch doesn't work in m2e

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4868]
the first `Launch Problems`  Dialog still exists

![remoterunnative](https://user-images.githubusercontent.com/33224746/134936467-991c6a76-b7e4-4ca4-b2b5-26b82725b9a4.png)

Example Repo:
https://github.com/stbischof/stbischof-native.test.bundle

This runs (see readme) with plain maven but not when starting inside the ide

_Originally posted by @stbischof in https://github.com/bndtools/bnd/issues/4863#issuecomment-929384704_

**Comment by kriegfrj** [comment]
### Executive Summary

As far as I can tell, this is an old issue. I suspect that the native launcher has never worked in an M2E context and that @stbischof is breaking new ground (@stbischof, if you have had this working in the past, please correct me).

### Detail
The problem starts here:

https://github.com/bndtools/bnd/blob/861f51d0d1cbb4bcbe9a0d05ea428f6063bab0c7/org.bndtools.launch/src/bndtools/launch/bnd/NativeBndLaunchDelegate.java#L90-L93

`getProject()` is returning `null`. Digging deeper, the root cause is in this git of code in `Central.getProjectFromFile()`:

https://github.com/bndtools/bnd/blob/861f51d0d1cbb4bcbe9a0d05ea428f6063bab0c7/biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java#L437-L440

`getBase()` returns the "base" directory of the current workspace. Under the workspace model, that would be the parent directory of `cnf`.  The workspace model requires your projects and `cnf` to be in the same directory, and the `if` statement here is effectively an assertion of this requirement.

However, under m2e, there isn't a regular `cnf` directory - instead, the base dir is set to `$USER_HOME$\.bnd\default-ws` and a workspace is created there. This means that the project's parent directory is not the same as the workspace's base dir. Hence the assumption fails and `getProjectFromFile()` gives up and returns `null`. 

I have an idea for a fix which I have just tried out and it seems to work. I will submit a PR.

**Comment by rotty3000** [comment]
Just for additional context, I've never used the native launcher from m2e (at least not with success) nor have I had a real need for it tbh.

**Comment by rotty3000** [comment]
Also note, that in the maven/m3e model, there is no true central (bnd) workspace. Each invocation of a mojo bootstraps a standalone workspace on demand.
