### ISSUE TITLE
Documentation Search

### ISSUE THREAD

**Issue by danelowe** [bndtools/bnd#4891]
There is a lot of documentation, but it can be very hard to find things in it.

e.g. I recall reading about a certain feature, but can't remember the details or what chapter it was in, and I spend a _**lot**_ of time trying to find it again, then begin to wonder whether my memory was incorrect.

Algolia has some good and easy options for adding search to static sites, especially for open source projects.

1. [DocSearch](https://docsearch.algolia.com/) - They crawl your documentation for you, and give you a javascript snippet, requires the maintainer to apply.
2. [jekyll-algolia](https://community.algolia.com/jekyll-algolia/getting-started.html) + [Autocomplete](https://www.algolia.com/doc/ui-libraries/autocomplete/introduction/what-is-autocomplete/)

Speaking of documentation, would there be any interest in looking at something like [VitePress](https://vitepress.vuejs.org/) or VuePress? From a user perspective there is familiarity and friendly typography etc. From maintenance perspective, JavaScript now has ubiquitous tooling on most machines, VitePress is specifically designed for technical documentation, is very fast to build, and would come with simple theme etc.

**Comment by danelowe** [comment]
<img width="650" alt="Screen Shot 2021-10-15 at 9 10 02 PM" src="https://user-images.githubusercontent.com/924802/137454361-077b7b3b-b591-4123-8e14-d457b1380805.png">
<img width="1434" alt="Screen Shot 2021-10-15 at 9 09 47 PM" src="https://user-images.githubusercontent.com/924802/137454371-b9e178a2-70df-43bf-8274-c417d2a5ed84.png">

I think the search UI designed to work with DocSearch, or at least with the Algolia index having a specific setup

**Comment by bjhargrave** [comment]
> Vitepress supports GitHub pages out of the box

It does not quite seem that way. You need to have build steps which build the static content and then commit/push that content to the gh-pages branch in the git repo for github pages to serve.

I don't want to add any additional steps to doc publishing. RIght now with github pages, we just add/edit markdown files and github pages automagically builds and deploys it. We only have a github actions job to validate docs changes but that job is not necessary to publish.

> then request that you apply for DocSearch

What does this mean? I guess I don't understand why google indexing the site does not provide answers in a google search? <https://www.google.com/search?q=conditional+package+site%3Abndtools.org> already seems to work quite well to search the existing site.

> Vitepress also supports DocSearch out of the box.

Their website says they are still pre-release. So that does not seem a good idea to add as a dependency.

**Comment by danelowe** [comment]
I understand that you believe the two to be conflated, but I think that ignores the fact that there is an emotional aspect to everything. 

Also the reason for suggesting VitePress was because it was by far the easiest way to get search in there, and makes the idea of working with the documentation more appealing. 

I’m not really able to comment on the documentation until I understand it fully. Understanding it fully would be aided be improving my ability to consume it. The best kind of person to comment on or improve the documentation for newcomers would be a newcomer who has recently made sense of it. 

To clarify my position, I’m looking into OSGi because it seems from a technical perspective to be an almost perfect fit for the projects my team are working on. However OSGi would be almost unusable without bnd. 

I of course am grateful for the tool, but if there seems to be not much of a community or other form of support behind it, then it becomes too great a risk and I think I’ll reluctantly move on.

Again, not here to push anything on you or argue at all. I just want to see if I can do what I can to make the experience better.

**Comment by bjhargrave** [comment]
Like most open source projects, the maintainers are better coders (hopefully) than documentation writers. My main goal would be more and better content over different look-and-feel and/or integrated search. But I am just one maintainer and the others may have differing opinions. Hopefully they will weigh in.

I am not trying to discourage you from using Bnd or contributing to Bnd, but whatever is done needs to be something the maintainers can maintain and are willing to maintain.

**Comment by danelowe** [comment]
Thanks for your thoughts. I completely understand your desire to ease maintenance and remain with what you know. I guess I’m just a newcomer sort of testing the waters. 

This issue was aimed at getting a gauge in what sort of buy-in there could possibly be before I invest any more time in it. 

From my perspective; I’ve used Jekyll before and it’s always felt like a bit of a hack to get it working the way I want it. Even though ruby was once my preferred language

I believe everything you mentioned should be relatively trivial with VitePress.

Vue and all of its sub-projects have versioned documentation. 

Documentation would remain in markdown, but code snippets can be improved by changing to blocks in backticks for syntax highlighting etc. almost no risk there. 

The look and feel requires no work at all, it come with it.

Algolia is SaaS that is free for Open Source projects. DocSearch makes it easier by letting them do the indexing for you rather than having to do it during build. 

JavaScript and even vue (which is very easy to use but probably won’t even need to use it at all) is I assume more common with JVM devs than ruby/haml/sass etc.

There may be other tools popular in the JVM ecosystem but I wouldn’t really know about them.

VitePress is designed for documenting libraries, and requires almost no customization for that use case. 

Build script might change, but I’m fairly certain at this point that it’s just a couple of lines that can be run in GitHub actions. 

I have no skin in the game except wanting to do what I can to help make it easier for others, and this is what I know.

**Comment by danelowe** [comment]
I will take a break this weekend m, but potentially come back later with a solution that covers off everything here.

**Comment by danelowe** [comment]
I should apologize for the ramblings. I’ve been stuck in lockdown for the last two months in a small house with a toddler. Bored out of my mind and exhausted at the same time.

I think the general gist is you’re not keen on changing unless it can be demonstrated that it would be easier to maintain. I don’t really want to invest a lot of time in unless my time would ultimately add value. 

To that end I’ll leave it here. If I can address your concerns and show value with a short bit of work when I get a chance, I’ll report back.

**Comment by danelowe** [comment]
Added a couple of PRs. This should all be possible sticking with the existing Jekyll implementation (albeit a bit painful with the 30sec rebuilds).
