### ISSUE TITLE
[BND] BND 5.2.0 with Apache Karaf 4.2.12 leads to high memory / OOM errors

### ISSUE THREAD

**Issue by mdonkers** [bndtools/bnd#4901]
We have an Agent written on top op Apache Karaf, which most often runs with constraint resources (limited memory). Recently we updated Apache Karaf from 4.2.9 to 4.2.12. Where normally this Agent runs fine in a test environment with +/- 450 Mb of heap, we started noticing it ran into Out of Memory Errors all the time, for the same configured heap.

After taking heap-dumps we noticed more than 350 Mb is retained by the `aQute.bnd.osgi.Jar` class. While we haven't finalized our analysis, it seems there is some issue inside the updated BND OSGi library, causing this high memory usage. At least Karaf 4.2.11 updated `bndlib` from 3.5.0 to 5.2.0 ( [Karaf release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12348692&styleName=&projectId=12311140&Create=Create&atl_token=A5KQ-2QAV-T4JA-FDED_ce55801d566577f2ae56833d2d84ccb3692cb412_lout) ), which could explain why issues started to show with the new Karaf version.

I'll try to list below all we saw with screenshots etc. Full heap dump is available if needed or happy to try and help out to figure out what might be causing this.

From the heap dump it's immediately clear the majority is retained by a single instance of the `Jar` class:
![image](https://user-images.githubusercontent.com/954721/137744205-7cd20c75-dbf7-4f97-9cf3-604436315094.png)

Looking at the JAR it's trying to load, it's the file `kubernetes-model-4.9.2.jar`. This has a size of around 12 Mb:
```
# ls -la
total 11640
drwxr-xr-x. 2 root root     4096 Oct 15 09:21 .
drwxr-xr-x. 3 root root     4096 Oct 15 09:21 ..
-rw-r--r--. 1 root root 11908731 Oct 15 06:39 kubernetes-model-4.9.2.jar
```
And consists of about 8200 files and directories (after extracting the ZIP file):
```
# find . | wc -l
8139
```

But while [directories are skipped](https://github.com/bndtools/bnd/blob/c9791146e2d53925142f1c8d0b9a95547a05e752/biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java#L296) it seems to create many more instances of `EmbeddedResource` then there are files:
![image](https://user-images.githubusercontent.com/954721/137791574-1ea2aa6f-2d04-47cf-894e-6337ae5167f2.png)
And because buffers are created with a default size, much more memory seems to be reserved than actually being used.

Also many more `EmbeddedResource` instances seem to have been created than there are linked from the `resources` map:
(around 10,550 entries vs 5278 actually referenced)
![image](https://user-images.githubusercontent.com/954721/137792070-841d87d5-a092-4164-ac84-683d5c573c6f.png)

So besides reserving more memory via the Byte Buffers than necessary, my main question is why that many instances of `EmbeddedResource` could get created?

**Comment by bjhargrave** [comment]
The code did not do well when the ZipEntries did not contain a size. I have a fix to only use the actual size arrays.

**Comment by bjhargrave** [comment]
> The heap dump is pretty clear in that all these `EmbeddedResource` instances get referenced by the same `Jar` instance.

But you previously said:

> around 10,550 entries vs 5278 actually referenced

So these seem to contradict.

**Comment by mdonkers** [comment]
Hi,

After running some tests and trying to reproduce, with the fix mentioned before (https://github.com/bndtools/bnd/commit/89743f9ed2554981934b71df301572665ef95dcd), it seems all issues are gone. Memory footprint looks much better.

Regarding;

> > But the Jar holds active references to 10,550 EmbeddedResource instances.
> 
> The Jar object generally refers to each resource from 2 maps. resources which is flat view NavigableMap<String, Resource> and directories which is a tree view NavigableMap<String, Map<String, Resource>>. But it is the same Resource object in each of the views. Not copies. So I think there are not actually 10K distinct Resource objects but only 5K distinct Resource objects held in 2 maps.

It indeed looks like I misinterpreted Eclipse MAT results, where the histogram shows correct numbers but the dominator tree shows them twice because referenced twice. Apologies for any confusion there.

Thanks for all the support and I'll be looking forward to the next release.
