### ISSUE TITLE
Can't find old releases.

### ISSUE THREAD

**Issue by TheTimKiely** [bndtools/bnd#4915]
Hi,
I'm trying to install an old version of bndtools (3.0.0) on an old version of Eclipse.
It looks like the bintray links are no longer available.  I get a 404 when going to https://dl.bintray.com/bndtools/bndtools/3.0.0.
And I can't figure out if old versions are available on the jfrog site, where the latest releases are available - https://bndtools.jfrog.io/bndtools/update-latest.
For example, I tried https://bndtools.jfrog.io/bndtools/3.0.0, but get redirected to a login page.

Does anyone know where I can download old releases?

Thanks,
Tim

**Comment by bjhargrave** [comment]
<img width="296" alt="138719928-b8d55ff8-2875-4f6b-8a27-bf54796a91b3" src="https://user-images.githubusercontent.com/277682/140074527-388c3cd2-f1ad-4c4f-8fce-3d3ebf98ba61.png">
