### ISSUE TITLE
Tasks extending from AbstractBndrun are not Configuration Cache compatible

### ISSUE THREAD

**Issue by leonard84** [bndtools/bnd#4919]
Tasks extending from `AbstractBndrun` are not compatible with Gradle's Configuration Cache, as they access the [project during execution](https://docs.gradle.org/7.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution) (The link contains information how to fix this problem).

**Comment by bjhargrave** [comment]
> On execution you could construct a simple pojo to hold the `project` properties that your need,

But the Bnd Gradle plugin cannot know, at configuration time, the properties that are needed at execution time when Bnd must resolve the macro references in the bndrun file like `${project.customUserDefinedProjectProperty}`. 

A custom project property example:

https://github.com/bndtools/bnd/blob/9a8938460018e1a74c7b9aa0fa1045aac893fad2/gradle-plugins/biz.aQute.bnd.gradle/testresources/exporttask1/build.gradle#L24-L26

https://github.com/bndtools/bnd/blob/9a8938460018e1a74c7b9aa0fa1045aac893fad2/gradle-plugins/biz.aQute.bnd.gradle/testresources/exporttask1/export.bndrun#L3

This support is expected and used by Bnd gradle plugin users so they can centralize configuration in the build.gradle file.

**Comment by rotty3000** [comment]
It would be annoying and error prone to have to duplicate all this information in two places; once in the bnd macros and again in the plugin configuration.

**Comment by leonard84** [comment]
You could do the following to keep the old behavior, while still allowing those who want to use configuration caching and proper up-to-date checks to add some extra configuration to get those benefits.

Add a `MapProperty<String, Object> templateParameters` (or choose a different name) to the `AbstractBndrun` task.
You can even prefill it with common values from the `project`, e.g. `templateParameters.put('projectName', project.getName())`.

To make the transition easier, I would also use a `StrictMap` that throws when an unknown key is requested.
This way, users can figure out if they try to access unavailable data instead of just getting `null`.

Add a switch to the task, `Property<Boolean> safeConfiguration` which will affect the available template binding parameters.
* If it is `false`, then you have the current set of bindings. 
* If it is `true`, then you only have access to the values from the `templateParameters`, you can inject empty instances of `StrictMap` for the `project` binding to get a meaningful error message.

You would probably have to either enhance `BeanProperties` to deal with `Map` fields, or just use the map values as property values, loosing the strict behavior, but reducing the complexity as well.

Now users can choose to optimize their build if they desire, or they can use the old behavior if they don't care.

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/blob/master/gradle-plugins/README.md#gradle-configuration-cache-support for information on how to configure the Builder plugin for the Configuration Cache.

**Comment by leonard84** [comment]
Thanks @bjhargrave 👍
