### ISSUE TITLE
Feature request: support merging of -includeresource by the launcher/exporter

### ISSUE THREAD

**Issue by abroekhuis** [bndtools/bnd#4924]
When using a merging instruction for "-includeresource" it is not picked up when exporting a bndrun file. 

I would like to use merging instructions for the includeresource as well.

**Comment by bjhargrave** [comment]
https://github.com/bndtools/bnd/blob/9a8938460018e1a74c7b9aa0fa1045aac893fad2/biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java#L317 is the culprit. It does not handle merged resources like the Builder https://github.com/bndtools/bnd/blob/9a8938460018e1a74c7b9aa0fa1045aac893fad2/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L903-L905.
