### ISSUE TITLE
Better error message when no snapshotUrl configured for a MavenBndRepository

### ISSUE THREAD

**Issue by brampouwelse** [bndtools/bnd#4930]
Took me some time to figure out what bnd was trying to tell mw with the  message 

```
error: my-project: No metadata for revision my.group:my.artifact:1.0.0-SNAPSHOT
```

Traced it down to the MavenRepository#resolveSnapshot method ( https://github.com/bndtools/bnd/blob/ba0bd37c2c33afe4ccfd8660b1a37b1c1ac52eaa/biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java#L225 ) 

I forgot to configure the snapshotUrl ... A more informative message at this point could have been of great help and would probably have saved me an hour (or 2).

Maybe something like 

```
Trying to resolve snapshot revision 'my.group:my.artifact:1.0.0-SNAPSHOT' but no snapshotUrl configured.
```

**Comment by bjhargrave** [comment]
Maybe you can make a PR?
