### ISSUE TITLE
Repositories are duplicated after final launch validation

### ISSUE THREAD

**Issue by mgerlich** [bndtools/bnd#4933]
We have our client built with bnd and use a base bndrun file and additional other bndrun for development and testing that basically include the base bndrun file.
After everything is properly resolved, the repositories are shown as is, i.e. all are unique.
When opening e..g the development bndrun and clicking the _Run OSGi_ button, the 'Launching : Perform final launch validation' tasks is in progress. This takes ~10 seconds (showing the Windows wait circle cursor) and immediately this finishes, the repositories are all duplicated. Only exceptions to this are our local maven repository marked as _-buildrepo_ as well as the _Maven Dependencies_ folder. The duplicate repositories are of type {{aQute.bnd.repository.p2.provider.P2Repository}} or 
{{aQute.bnd.repository.maven.provider.MavenBndRepository}}.

We have the latest bndtools 6.0.0 release version in use with Eclipse 2021-09 on a Windows x64 machine.
Please have a look at the state of the repositories view before clicking _Run OSGi_, while it performs validation and after it finishes, starting the client.

Before:
![repositories_before](https://user-images.githubusercontent.com/688198/140399524-bc753920-705f-452c-8bd5-2d8331942ec8.png)

During:
![repositories_during](https://user-images.githubusercontent.com/688198/140399527-e1f7cff7-4e06-4382-9efe-b2578aa4f4f1.png)

After:
 ![repositories_after](https://user-images.githubusercontent.com/688198/140399523-fcebe71d-1bac-45ab-a1b0-835cab3e3c36.png)

**Comment by kriegfrj** [comment]
@mgerlich, thanks for this report. May I ask you to clarify something - you said you are using 6.0.0, I just wanted to confirm that you're using the official 6.0.0 release, and not the the latest snapshot (derived from 6.0.0)?

**Comment by mgerlich** [comment]
Sorry for being unclear - yes indeed, it is the `6.0.0.REL-202110041835-gc077e57` release version

**Comment by bjhargrave** [comment]
6.2.0 (under development) has a number of changes we think may address this issue including https://github.com/bndtools/bnd/pull/5000/commits/41c94ca8675f2c3c56440c3354a330d679056998 and some locking improvements.

So will will close this for now. If, after 6.2.0 is released (est. mid Feb 2022), you still see the problem, please open a new issue and please provide a small github repo which demonstrates the problem along with instructions on how to reproduce.
