### ISSUE TITLE
BndRun Issue with BndTools 6.0.0 version in eclipse

### ISSUE THREAD

**Issue by priyankabishnoi** [bndtools/bnd#4945]
We recently upgraded eclipse and our project. We have the latest eclipse 2021-09 and out project is on Java 11. We installed bndtools and the version which was installed was 6.0.0. What we are observing is that when we click on resolve in bndrun then the resolution is all fine. I see that the bundles which we require are being picked from the .m2 repo.

Our BndRun is for Test cases
However when i create a new Osgi  Junit Tests configuration then i get error . The error states that it is not able to find find bundles.
I see that now the configuration is trying to look for bundles in bnd-cache rather than .m2
I Tried a lot to update the reference for runbunldes in eclipse run configuration but all in vain.
We never saw this issue in older version of bndtools i.e. 5.3.0

Can you please help us with what needs to be done to make the bndrun work?

**Comment by juergen-albert** [comment]
For starters: Please do not use bndtools 6.0 with eclipse 2021-09. There was a But in Eclipse version of m2e that can cause bnd do a build loop. I'd suggest going back to 2021-06 or updating m2e to the latest version (I believe the fix is already released).

To better understand what happens: what do you mean by "create a new Osgi Junit Tests configuration"? Do you run your tests based on a bndrun or as part of a bnd file?

**Comment by juergen-albert** [comment]
Is your problem similar to what is described here: https://bnd.discourse.group/t/cant-run-junit-integration-test-from-eclipse/191

**Comment by priyankabishnoi** [comment]
> Is your problem similar to what is described here: https://bnd.discourse.group/t/cant-run-junit-integration-test-from-eclipse/191

No Its not the same

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem along with instructions on how to reproduce? Then we can investigate. Thanks.

**Comment by priyankabishnoi** [comment]
> m2e

Yes we run Junits through bnd. See below
<img width="670" alt="eclipse" src="https://user-images.githubusercontent.com/27962108/141503639-6b8fba13-6ee7-4cc1-a339-f72b59b73dcb.png">

Also see this: Before Resolve the Repository in bndrun in  Workspace and the rundles are seen 
![image](https://user-images.githubusercontent.com/27962108/141503858-cf6cfd69-1bb1-4471-9dab-458c36d2da20.png)

After Resolve
I see the Repository section changes to the project name with implicit in bracket
And all rundles are shown twice one with implicit and other with Maven Dependencies
![image](https://user-images.githubusercontent.com/27962108/141504678-794aaf6e-791a-40e7-8067-56475ec78b6c.png)

So when we run the this bndrun looks like its not able to resolve dependecnies as it ries ti find them in bndCache rather than .m2

**Comment by bjhargrave** [comment]
I am not sure what the implicit repo is that you have scratched out.

In any case, 6.2.0 (under development) has a number of changes we think may address this issue including https://github.com/bndtools/bnd/pull/5000/commits/41c94ca8675f2c3c56440c3354a330d679056998 and some locking improvements.

So will will close this for now. If, after 6.2.0 is released (est. mid Feb 2022), you sill see the problem, please open a new issue and please provide a small github repo which demonstrates the problem along with instructions on how to reproduce.
