### ISSUE TITLE
add -offline instruction

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#496]
I would really like an -offline instruction to enforce an offline build, with NO cache access.

Use-case is a self-contained build.
For example for products that must be supported and re-buildable long-term.

**Comment by bjhargrave** [comment]
We now (mostly) have this for 3.3 with the new RepositoryPlugins that use HttpClient. See https://github.com/bndtools/bnd/pull/1673

When running gradle with --offline, this will set the Workspace in offline mode and direct the HttpClient to not access the network. Older repository plugins which do not use HttpClient will not understand offline mode. 

Changes in Bndtools to support this will come in 3.4: https://github.com/bndtools/bndtools/pull/1536.
