### ISSUE TITLE
Using manifest builder in a lib not exporting the "org.osgi.service.log" package

### ISSUE THREAD

**Issue by jmini** [bndtools/bnd#4969]
The goomph plugin is using the classes `aQute.bnd.osgi.Builder` and `aQute.bnd.osgi.Constants` in [BndManifestPlugin](https://github.com/diffplug/goomph/blob/main/src/main/java/com/diffplug/gradle/osgi/BndManifestPlugin.java) (see the [documentation](https://javadoc.io/doc/com.diffplug.gradle/goomph/3.33.2/com/diffplug/gradle/osgi/BndManifestPlugin.html)) by having a dependency to `biz.aQute.bnd:biz.aQute.bndlib:5.3.0`.

As indicated in https://github.com/diffplug/goomph/issues/171#issue-1055801463 this is causing following error:
```
java.lang.SecurityException: class "org.osgi.service.log.LogLevel"'s signer information does not match signer information of other classes in the same package
```
When we try to create a new OSGi runtime with `Framework framework = new EquinoxFactory().newFramework(config)`

We have both `org.eclipse.platform:org.eclipse.osgi:3.15.0` and `biz.aQute.bnd:biz.aQute.bndlib:5.3.0` on the classpath.

What are the options?
Is there a way to consume the Builder from an other jar?

**Comment by bjhargrave** [comment]
You can try version 6.1.0 of the Bnd jar. In 6.1.0, we no longer include copies of the OSGi packages.

**Comment by jmini** [comment]
Thank you a lot.

Duplicate of issue #4897, see PR #4918
