### ISSUE TITLE
Bndrun files cannot override -runbundles

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#4982]
I have created a simple Maven test project at timothyjward/runbundles.inheritance@d7e62903d06c549393b93173652823b66a3411b1

This demonstrates several issues:

1. The core issue - there are two bndrun files, `launch.bndrun` and `gogo.bndrun`. `launch.bndrun` is resolved and runnable (`mvn bnd-run:run@launch`, the endpoint is accessible at http://localhost:8080/respond/Bob ). `gogo.bndrun` includes `launch.bndrun` and adds requirements for gogo - these resolve, but when running gogo (`mvn bnd-run:run@gogo`) there are no gogo bundles installed and no shell started.
2. On most machines it isn't possible to use Bndtools to select a bndrun and "Right click -> Run As... -> OSGi Run Launcher" as the referenced bundles cannot be found from the pom
3. On most machines it isn't possible to use Bndtools to resolve the bndrun files. They resolve fine from the command line.

**Comment by timothyjward** [comment]
Note that issue 1. can be worked around by creating a third bndrun file to use as the parent which contains no `-runbundles` entry. The `launch` and `gogo` files can then both `-include` this other file.

**Comment by bjhargrave** [comment]
I think this is user error. The include overwrites properties in the bndrun which does the include. So launch.bndrun's runbundles replaces gogo.bndrun's runbundles. If you do not want the overwrite behavior, you need to prefix the file name with `~`:

```properties
-include: ~launch.bndrun
```

Note: Despite the [documentation](https://bnd.bndtools.org/instructions/include.html) and the comments in the code, the default behavior is overwrite and the `~` prefix turns off that behavior.

https://github.com/bndtools/bnd/blob/49a9491a22119677efaf70ed8e8c53bd24138ad8/biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java#L875-L883

**Comment by timothyjward** [comment]
> I think this is user error.
> ...
> Note: Despite the documentation and the comments in the code, the default behavior is overwrite and the ~ prefix turns off that behavior.

I think that referring to this as user error is somewhat uncharitable. The documentation is pretty clear, and the user followed it. If the code doesn't do what the documentation says then that's really a bug, as it requires a change in a bnd to fix it! 😉 

My next question is - will the documentation or the code be fixed? The current implemented behaviour feels wrong to me as local entries typically override imported entries in Java. Having the default behaviour of `-include` be to override locally set properties is both surprising and counterintuitive. The documented behaviour is much more in keeping with other Java inheritance.

Whichever solution is applied, there then exist the other problems that I found when creating my small test project, namely that the IDE integration seems unable to locate the project's dependencies, even though they are directly referenced in the pom. I'm certain that this used to work.

**Comment by bjhargrave** [comment]
> Working on the doc fix now...

Fixed by #4983.

**Comment by bjhargrave** [comment]
@timothyjward Given the understanding of how overwriting actually works, can you please update this issue with the remaining issues including how to reproduce? 2 and 3 in your list.

**Comment by rotty3000** [comment]
Is there really still an issue here?

**Comment by bjhargrave** [comment]
Closing.
