### ISSUE TITLE
Macros p_<something>, e.g. p_sourcepath not working

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4996]
Whenever I use one of the macros documented at https://bnd.bndtools.org/chapters/855-macros-ref.html starting with `p_` like `p_sourcepath` bnd always emits

```
 No translation found for macro: p_sourcepath
```

I tested with bnd-maven-plugin:6.1.0.

**Comment by bjhargrave** [comment]
Are you using a Bnd Workspace model build (with cnf)? Or using a maven build (bnd-maven-plugin)?

Those `p_` macros are Project macros and Project is for Bnd Workspace builds only.

**Comment by kwin** [comment]
I use the Maven plugin. Maven also has the notion of projects. Would be good to clarify which macros can be used where.

**Comment by bjhargrave** [comment]
Each macro doc source page has the `class` attribute. I thought that was used by the jekyll theme to display something on the generated page. @pkriens ?

**Comment by pkriens** [comment]
I don't thing this was styled ever ... nor well maintained. One day we should get some trainee to go over this.

**Comment by pkriens** [comment]
I've added information about the 'class' field to the pages.

**Comment by kwin** [comment]
Thanks. A little description on the different classes on https://bnd.bndtools.org/chapters/855-macros-ref.html would help a lot though...

**Comment by pkriens** [comment]
We love PRs :-)

**Comment by kwin** [comment]
I don't really understand the differences between the classes to be honest, therefore I am not able to come up with one.

**Comment by pkriens** [comment]
Some people say I am too good for this world ... they must be right :-)

See https://bnd.bndtools.org/chapters/790-reference.html and all new buttons are linked to it.
