### ISSUE TITLE
Bndrun for gradle runs "too detached"

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#4997]
I'm using Bndrun (from bnd 6.1.0) in a non-workspace build. When I execute the task, a framework is started as expected ([minimal example](https://github.com/mnlipp/bnd-issue-demo), `./gradlew RunDemo:run`).

When I type ctrl-c, gradle stops (again as expected) but the framework continues to run. As this way of starting a framework is most likely used for testing/debugging, this is quite unexpected behavior. IMHO the JVM that runs the framework should stop as well.

**Comment by bjhargrave** [comment]
This topic was discussed in <https://bnd.discourse.group/t/kill-container-from-gradle-run/168>.

There is no clear solution as the Bnd gradle plugin does not use Gradle's Javaexec task to run bndrun files. It uses Bnd's ProjectLauncher.

**Comment by mnlipp** [comment]
I've defined a JavaExec task that [runs bnd](https://github.com/mnlipp/jgrapes-webconsole/blob/f60f31175b3c3029b7a10594ffb1a8570a3b1ccb/WebConsoleOSGiDemo/build.gradle#L57) as a workaround.Solves the problem for me.
