### ISSUE TITLE
Missing stdin for gradle Bndrun

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#4998]
I'm using Bndrun (from bnd 6.1.0) in a non-workspace build. When I configured framework plus gogo-shell as a simple example, I found that the `System.in` isn't connected to my started framework. This is a well known [gradle behavior](https://stackoverflow.com/questions/13172137/console-application-with-java-and-gradle).

The `JavaExec` task provides a way to "forward" `System.in` to the started JVM. I think this should be added to Bndrun.

(Sorry, but although I have a basic understanding about gradle plugins and bnd, my knowledge of the environment isn't sufficient for a PR.)

**Comment by bjhargrave** [comment]
The Bnd gradle plugin does not use Gradle's `Javaexec` task to run bndrun files. 

https://github.com/bndtools/bnd/blob/ec9368b9e7e2f71a86ac6a8835aa001a2495487b/gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/Bndrun.java#L104-L107

It uses Bnd's ProjectLauncher (which is used in Eclipse and Maven). And ProjectLauncher defaults to use `System.in` as the input.

https://github.com/bndtools/bnd/blob/ec9368b9e7e2f71a86ac6a8835aa001a2495487b/biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java#L91

**Comment by mnlipp** [comment]
I've defined a JavaExec task that [runs bnd](https://github.com/mnlipp/jgrapes-webconsole/blob/f60f31175b3c3029b7a10594ffb1a8570a3b1ccb/WebConsoleOSGiDemo/build.gradle#L57) as a workaround.Solves the problem for me.
