### ISSUE TITLE
[builder] Convert Bndtools builder to a facade pattern

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#5004]
In order to streamline future development on the Bndtools builder (eg, #3175), I would like to convert it to a facade pattern so that the builder bundle can be restarted without needing to restart Eclipse. Creating this issue to hang a corresponding commit/PR from.

**Comment by kriegfrj** [comment]
> Care is needed since this is the crux of the Bndtools value.

**Comment by pkriens** [comment]
@kriegfrj I am not sure how this can be done? Creating the facade is easy but BndtoolsBuilder is connected with the project. So if the service goes, you need to save the state and restore it?

I like the idea but I would like to close this issue, it is has been outstanding for a long time. I can move it to abeyance if you want.

**Comment by pkriens** [comment]
Ok, I am moving it to abeyance for now. It looks very interesting though, would be great if you could finish it one day.
