### ISSUE TITLE
[validator] Project/builder validators not generating markers

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#5006]
While working on #5004, I was running a few tests to see if I had broken anything with the standard build behaviour. I tried to misconfigure an Eclipse project to see if would still generate error markers, and found that it didn't. When I dug further, I discovered the following bit of code in `master`:

https://github.com/bndtools/bnd/blob/f848ef99deed1cbd1c4c576f9575781ca4a07a7d/bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java#L207-L213

The problem here is that "markers.validate()" is run on `model` (and more importantly, generates its errors on `model`), and it is run *after* the call to `processor.getInfo(model)` (which is supposed to populate `processor` with the errors in `model`). Then the markers are generated from `processor` (which still has the snapshot of errors from before `validate()` was run).

A potential fix is to run `markers.validate()` before the call to `processor.getInfo()`. This seems to be working in my test environment, but I'm not sure if there was a reason why the previous author attempted to defer the call to `validate()` into the "after" block - for performance - to minimise time running inside the locked section, or to avoid potential deadlock? Maybe the solution would be to put another `getInfo()` call inside the `after` block, after the `validate()` call?

**Comment by pkriens** [comment]
No you're right, the reason was performance but it then uses the wrong state. Can you fix it?
