### ISSUE TITLE
OSGi Builder non-reproducible Export-Package and Private-Package values

### ISSUE THREAD

**Issue by hboutemy** [bndtools/bnd#5021]
reported to Felix https://issues.apache.org/jira/browse/FELIX-6496

looking at Builder code, I suppose the `traverse()` method that uses `File.listFiles()` API is causing the issue: the API does not provide consistent order, you need to sort when in reproducible mode
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L1153

**Comment by bjhargrave** [comment]
I think you need to try with the latest version of Bnd -> 6.1.0 to see if the issue is still present. 5.1.1 is rather old now.

**Comment by bjhargrave** [comment]
> looking at Builder code, I suppose the `traverse()` method that uses `File.listFiles()` API is causing the issue: the API does not provide consistent order, you need to sort when in reproducible mode
> https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L1153

This code only applies when `-includeresource` uses the `cmd` attribute which is not commonly used.

**Comment by hboutemy** [comment]
I tested upgrading to 6.1.0 and got the exact same result (which is stable on 1 local machine given multiple runs, but is not stable against other machines builds: not easy to reproduce alone)

can you point me to how these Export-Package and Private-Package are automatically discovered, please?

**Comment by hboutemy** [comment]
ok, I tested using disorderfs to randomize FS order: https://salsa.debian.org/reproducible-builds/disorderfs

the result is unstable, which tend to prove `File.listFiles()` is used...
