### ISSUE TITLE
Build ignoring upstream changes

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#5025]
I've got a project that creates a JAR from other projects. When any of the upstream projects change, the dist builder gets called. However, it never really builds since it cannot see any changes.

I can see that the Java builder gets a FULL_BUILD due to the BndContainer changing but when we get to the Bndtools Builder this has been lowered to an AUTO_BUILD. Since there is no Java code changing, the delta is empty.

I am thinking of checking the dates of the classpath files against the last build. However, this feels rather hackish. @bjhargrave  any ideas?

**Comment by bjhargrave** [comment]
The BndContainer holds a lastModified value which is the lastModified value of the newest element in the container. I guess the Bndtools builder could compare that value against the last modified time of the project's `buildfiles` file and build if the container is newer than the `buildfiles` file.

**Comment by kriegfrj** [comment]
Ive got my hands dep in this code at the moment. Some of my changes will make this easier to develop and test. If it is not urgent, I'm happy to tack a fix on for this too (it will be just as easy as handling the merge conflict...)

**Comment by pkriens** [comment]
The #5038 fix seems to solve the problem for me. I just tried it out. Before the log clearly showed it was not build, with #5038 it does.
