### ISSUE TITLE
TLS client certificates don't work if verification disabled or trust given

### ISSUE THREAD

**Issue by kurthuwig** [bndtools/bnd#5034]
If you need to use both a TLS client certificate and basic auth to authenticate to your maven repository (e.g. Nexus 3), then you need to be extra cautious:

In `src/aQute/bnd/connection/settings/ConnectionSettings.java` this code decides what to do:

              // verify=false, trust.isEmpty -> void default check
              // verify=false, !trust.isEmpty -> ignore
              // verify=true, trust.isEmpty -> use default check
              // verify=true, !trust.isEmpty -> verify against given certs
   
              boolean hasCerts = serverDTO.trust != null && !serverDTO.trust.isEmpty();
              if (serverDTO.verify == false || hasCerts)
                  https = new HttpsVerification(serverDTO.trust, serverDTO.verify, processor);
              else
                  https = null; // verify & no certs ==> default

So if either there is a `<verify>false</verify>`  or there is a `<trust>...</trust>` then the own `HttpsVerification` is used which does not support TLS client authentication.

To reproduce:

1. Configure gradle to use TLS client certificates:

    systemProp.javax.net.ssl.keyStoreType=pkcs12
    systemProp.javax.net.ssl.keyStore=/home/kurt/SSL/keystore.p12
    systemProp.javax.net.ssl.keyStorePassword=XXX

2. Configure `connection-settings.xml` to either have a `<verify>false</verify>` entry or have a `<trust>` entry.
3. try to download dependencies with a gradle build

Expected result:

Dependencies are downloaded

Actual result:

TLS client certificates are not sent => server denies access.

Workaround:

Don't have `<verify>` or `<trust>` entries in your `connection-settings.xml`.

**Comment by bjhargrave** [comment]
Fixed by 8368bad44603fb913daa8a74cc54af1c0b1a82ac
