### ISSUE TITLE
Maven plug-ins: Mark Maven-exported dependencies as scope provided

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#5039]
To prevent unnecessary artifact downloads with Maven 3 all dependencies provided by the Maven distribution should have scope "provided" (and only be listed with the version shipping with the minimum Maven version being supported). For further info look at https://issues.apache.org/jira/browse/MPLUGIN-370 and https://issues.apache.org/jira/browse/MNG-7097.

**Comment by bjhargrave** [comment]
Can you be more specific? We already use provided scope for the core maven dependencies.

https://github.com/bndtools/bnd/blob/dd70f591faa71e26a0425822099480c0942de132/maven/bnd-plugin-parent/pom.xml#L89-L112

**Comment by bjhargrave** [comment]
If you are concerned about the plugin.xml descriptor having too many dependencies listed, this is a bug in maven-plugin-plugin 3.6.2 (which I just reverted from the build). See https://issues.apache.org/jira/browse/MPLUGIN-382.

**Comment by kwin** [comment]
Indeed, most dependencies have the right scope already.  Slf4j is provided by Maven as well though: https://github.com/apache/maven/blob/maven-3.3.9/maven-core/src/main/resources/META-INF/maven/extension.xml#L116-L119
