### ISSUE TITLE
[builder] No automatic build when build.bnd changes

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#5060]
As part of #5011, I took as my starting point these comments at the top of `BndtoolsBuilder`:

https://github.com/bndtools/bnd/blob/3b3c8a9c2d8e12f907ef52fc0753e95ed116a329/bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java#L48-L63

However, I've now implemented most of these tests and found that many of them don't work exactly as expected. I suspect this is mostly  a case of improvements that haven't been reflect in the comments. However, there is is one that I think is a definitely a bug.

It seems changes to build.bnd do not trigger an automatic rebuild.

I have attempted to see if this behaviour is replicated in HEAD, and as far as I can tell it is. I tested on the Bnd workspace by creating a small test project with a single class and an empty bnd.bnd. Then I changed base.version to 6.3.0, and I can see that the jar still has 6.2.0 in it as the version. In fact, even if I remove test.jar the automatic rebuild still produces 6.2.0. It is not unless you do a clean that the new base.version is reflected in the output jar.

This is a bit finnicky and I may have done something silly to cause this behaviour. So if anyone could verify this behaviour, it would be appreciated. I'm a bit surprised if it is the case because it seems like a core behaviour; however perhaps because build.bnd is updated infrequently we haven't noticed much.

If the above is correct, it probably means that BndtoolsBuilder is caching some state somewhere.

**Comment by pkriens** [comment]
I can confirm that changes to build.bnd are not propagated. Will see if I can make a quick fix
