### ISSUE TITLE
[Eclipse Bug] JVM Crash

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#5062]
Reappearance of #4854

Tested Version:

* Latest Snapshot
* Eclipse 2021-12

**Comment by ViToni** [comment]
Also valid for Eclipse 2022-09 and bnd 6.3.1.
(Somehow expected since https://bugs.eclipse.org/bugs/show_bug.cgi?id=576099 doesn't have any progress on that matter.)
