### ISSUE TITLE
Check version values in annotations

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#5087]
Annotations such as `@org.osgi.annotation.versioning.Version` have `RetentionPolicy.CLASS`, are thus compiled into the class-file, and may be used by tools to generate bundle manifests or otherwise e.g. [process the version of a package](https://docs.osgi.org/specification/osgi.core/7.0.0/framework.api.html#org.osgi.annotation.versioning.Version). Values used in annotations should therefore be "literal", i.e. shouldn't  need further evaluation.

Although values used in annotations *should* be "literal", `bnd` "pipes" them since "almost forever (at least since 2010)" through its macro processor. Therefore `MANIFEST.MF` usually has the expected values. The resulting bundle, however, includes a mixture of evaluated information in `MANIFEST.MF` and macros in `package-info.java`. If the later are used as input in a subsequent `bnd` run, the macros are re-evaluated using the then current environment, which may result in values that differ from the ones in `MANIFEST.MF`.

While this behavior cannot be changed without the risk of breaking existing builds, users should at least be made aware of the "discouraged" usage of macros in values of annotations. Any retrieval of values from annotations should check if the value is a macro and generate a warning (maybe it should check if applying the macro evaluation changes its value).

(This hopefully summarizes [this discussion](https://bnd.discourse.group/t/bnd-macro-expansion-class-works-but-version-doesnt/212)).

**Comment by timothyjward** [comment]
> Values used in annotations should therefore be "literal", i.e. shouldn't need further evaluation.

I think it’s a bit more nuanced than this. At the very least it is common (and valuable) to use the class name macro when declaring a BundleActivator header. This macro is also never going to give different values in different builds. 

A blanket ban on macros would block (or at least unfairly stigmatise) the perfectly acceptable use of class and package name expansions which are very useful in headers and requirements/capabilities.

**Comment by mnlipp** [comment]
I wanted to make the point that the issue most likely goes beyond `@Version`, which the [discussion](https://bnd.discourse.group/t/bnd-macro-expansion-class-works-but-version-doesnt/212) focused on. (In theory, this would also be a point about interoperability of build tools, but in reality there's only one.) The most important point IMHO is that the "caveats" of using macros in annotations are well documented, especially in such a way that new users may become aware of pending problems as early as possible.

**Comment by bjhargrave** [comment]
> I wanted to make the point that the issue most likely goes beyond `@Version`,

Not really. The issue is strictly about the `Version` annotation. It is the only annotation which needs to hold an actual OSGi version string. The other annotations are only used to generate the OSGi metadata for the manifest while the `Version` annotation is used to "know" the version of a package.

So I agree with @timothyjward.
