### ISSUE TITLE
[bndlib] Container.getBundleSymbolicName() returns the name of the jar

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#5090]
While working on #3175, I noticed that `Container.getBundleSymbolicName()` returns the filename of the Jar rather than the straight BSN (ie, `my.bundle.jar` rather than simply `my.bundle`). Not sure if this is by design but a superficial glance suggests that this is a bug.

**Comment by kriegfrj** [comment]
Further investigation suggests that this might only be happening on `Container`s of type `PROJECT`, `LIBRARY` seems to work ok.

**Comment by bjhargrave** [comment]
For a container of type PROJECT, there is no bundle from which the BSN can be obtained. A project may be `-nobundle`. Also, until a project is built, the BSN may not be known. So I can certainly see that for PROJECT, the reported bsn will be only an "estimate".

**Comment by kriegfrj** [comment]
Granting everything that you've said, but in my case, it calculates the BSN correctly only append ".jar". Even if it is estimating, there doesn't seem to be a sensible reason to estimate that the BSN should have a ".jar" on the end...
