### ISSUE TITLE
[builder] Get access to ArtifactInfo after a build

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#5102]
In trying to implement #3175...

`BndtoolsBuilder`'s current workhorse is to call (Bnd) `Project.build()`. Most of BndtoolsBuilder is about checking preconditions and then handling the result. `build()` generates the jar(s) and writes them to disk.

The current implementation of `BndContainerInitializer` then reads the jar(s) from disk and examines the manifest.

There are a number of issues with this approach:
1. Classpath re-calculation happens often. I think it might be beneficial to cache this information in-memory as part of the transient build state.
2. To implement #3175 properly, we need to know not only the exported packages, but the contained packages. This information may not be present in the manifest if the Private-Package header has been stripped.

`Project.build()` actually generates all of the necessary information during the build when it defers to `ProjectBuilder.build()` (`ArtifactInfo` interface and implementation) - however, the `ArtifactInfo`(s) are only accessible via the `BuildInfo`, which is in turn only accessible via `ProjectBuilder`. By the time that `Project.build()` returns, the `ProjectBuilder` (along with the `BuildInfo` and `ArtifactInfo`s that it generated along the way) has been closed and discarded.

Possible ways around this:
* Modify `Project` to provide a mechanism to give access. Not sure if this will cause issues with keeping a reference after the builder has been `close()`ed.
* Instead of modifying `Project`, subclass it in Bndtools to give access to the `BuildInfo`.
* Instead of "pull" access, give "push" access via some kind of build listener callback interface. This would give users the opportunity to register a listener and capture the information it needs in `buildDone()` before the builder is closed.
* Modify `BndtoolsBuilder` to call `ProjectBuilder.build()` directly instead of via `Project.build()`. That way it has greater control over when the builder(s) are closed and has the opportunity to get the information it needs from `BuildInfo` before it is closed. Howeer, there is a greater risk in this approach of breaking build fidelity inadvertently.
* Simply re-run the Analyzer manually to get the information that you want instead of trying to capture it during the build. Will this be a significant performance penalty?

Thoughts?

**Comment by kriegfrj** [comment]
Actually, digging into this further...

I realised that handling of split packages add a complication to this. For true fidelity, when merging access rules, I need to know not only which resources are included in the final bundle, but which container they came from.

Is there any way to get this information output during the build? Can the `Analyzer` produce this information when invoked directly?

**Comment by pkriens** [comment]
Did you look at the OnWorkspace class? You can subscribe to the workspace events with Workspace.on("name")

**Comment by kriegfrj** [comment]
Thanks for the tip @pkriens!

I've since done a bit more work on this and I think that `Project` actually does have the necessary information in it (after it has been built) via `getExports()` and `getContained()`. I'll leave this issue open for now but I think it may turn out to be a non-issue, in which case I'll simply close it.

**Comment by kriegfrj** [comment]
Yes, at the end of the build, all of the project's exports, imports and contained are copied from the builder/artifact info to the `Project`:

https://github.com/bndtools/bnd/blob/dbf5fb4ddbb5ca0d2cc3292bdff0433e4f781949/biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java#L891-L894

So I'm marking this issue closed.

**Comment by pkriens** [comment]
Notice that the event system in OnWorkspace gives you an immutable copy. The information in Project is not easy to map to subbundles information nor is it immutable

**Comment by kriegfrj** [comment]
> Notice that the event system in OnWorkspace gives you an immutable copy. The information in Project is not easy to map to subbundles information nor is it immutable

Thanks - I'm taking a closer look at this; I think that there are a number of features that the `BndtoolsBuilder` and related components could leverage in order to improve their implementation. At the moment these components are relying on things like file timestamps to check for out-of-dateness, where it would be more precise to rely on property changes.

**Comment by pkriens** [comment]
Yes, the OnWorkspace was an attempt to share the information via a well defined event mechanism. The idea is that this will replace all other communications.
