### ISSUE TITLE
[analyzer] Bnd does not carry forward resolution mode of packages contained on the Bundle-ClassPath

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#5135]
Bnd provides a convenient behaviour of calculating the package imports required by classes found in containers on the Bundle-ClassPath. This is automatic behaviour which happens without manual intervention. However, bnd does not retain the resolution mode of the imported packages from containers on the BCP (except for the root container) during this process which means that the result is lossy.

While it is true that one can resolve this by manually intervening using any of the various bnd instructions to enrich the metadata, the default behaviour is not friendly, can be quite painful when the BCP is very large and could easily be lossless by default (where no intervention is required).

**Comment by rotty3000** [comment]
I'm narrowing the scope of this topic to just cover the resolution mode of packages because this is the most painful. Versions are the next, but I'm happy to tackle one at a time.

However, if we _wanted_ to include versions, then I suggest we cater to that the assumption of there being a single package on the Bundle-ClassPath. The goal is not to enrich that use case for multiple versions and try to deal with it. I'd just like for bnd to not merely throw its hands in the air for any package on the BCP ignoring all information it actually has available already. The idea is merely to make a usable default.

**For `resolution:`:** I believe a reasonably well crafted heuristic should do the trick:
e.g. the first resolution is taken, any subsequent wider scoped resolution supersedes a lower one: `optional` < "unspecified" < `mandatory`

**For `version`:** I suggest behaviour be to take the first version as default, WARN if a different version is encountered on the BCP. The user can then decide to:
1. override the version in the manifest (current behaviour anyway)
2. try to solve by removing the duplicate package, decide which one is actually desired
3. use `-fixupmessages` one time (or per package)

Currently one has to iteratively, painfully backtrack through all the data to try to figure out which packages are actually required and which versions are there. I can show many examples that prove this pain _is_ experienced in the wild when all we need is a reasonable default.

**Comment by bjhargrave** [comment]
> **For `resolution:`:** I believe a reasonably well crafted heuristic should do the trick:

resolution must be a one-way ratchet. It can only go from optional => mandatory. So if at least one entity on the BCP imports resolution:=mandatory or imports without the resolution directive, then the bundles import must not be resolution:=optional.
