### ISSUE TITLE
docs: rendering of table is broken?

### ISSUE THREAD

**Issue by jmini** [bndtools/bnd#5166]
On the page:
https://github.com/bndtools/bnd/blob/master/docs/md/805-instructions.md

Or rendered here:
https://bnd.bndtools.org/md/805-instructions.html

I have the feeling that the tables and the links are broken.

---

I am happy to rework this page but I need some guidance for the direction.

Do we need the rendering to look good with Github-Markdown or with any other markdown library?

**Comment by bjhargrave** [comment]
We don't use the files in the docs/md folder. The actual md file is in the docs/_chapters folder. 

I made #5167 to remove these dead md folders.

**Comment by jmini** [comment]
Ok. Thank you.
