### ISSUE TITLE
Upgrade from Bnd 3.5 to 5.3.0 breaks runtime dependency

### ISSUE THREAD

**Issue by Ozame** [bndtools/bnd#5188]
### Versions
- biz.aQute.bnd:biz.aQute.bnd.gradle:5.3.0
- Java version 1.8.0_321
- Gradle 5.6.4
- Karaf 4.2.15

### Issue
While updating our project from Gradle 4.10.3 to 5.6.4, we also had to update our Bnd plugin. While everything works as expected on the development environment, running certain project's features on Karaf results on the following error:

`
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=xxxxxx; type=karaf.feature; version="[8.8.8,8.8.8]"; filter:="(&(osgi.identity=xxxxxx)(type=karaf.feature)(version>=8.8.8)(version<=8.8.8))" [caused by: Unable to resolve xxxxxx/8.8.8: missing requirement [xxxxxx/8.8.8] osgi.identity; osgi.identity=yyyyyy; type=karaf.feature [caused by: Unable to resolve yyyyyy/8.8.8: missing requirement [yyyyyy/8.8.8] osgi.identity; osgi.identity=yyyyyy; type=osgi.bundle; version="[8.8.8,8.8.8]"; resolution:=mandatory [caused by: Unable to resolve yyyyyy/8.8.8: missing requirement [yyyyyy/8.8.8] osgi.wiring.package; filter:="(osgi.wiring.package=com.sun.xml.internal.messaging.saaj.soap)"]]]`

We are using the `com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl` as the runtime implementation, setting it as the system property `javax.xml.soap.MetaFactory` in the code. This code affect couple different features, and installing either of those results in this error. This has worked before, but since the update it seems the dependency can't be found on runtime. Is there some change in Bnd that affects the usage of the internal` com.sun.*` dependencies? 
We suspect that this is an bnd related issue as the problem doesn't manifest itself while running the same code with IDE on the development environment.

**Comment by juergen-albert** [comment]
Not sure what changed here between 3.5 and 5.3, but this looks like a valid concern of the resolver. BND will only write a package import for `com.sun.xml.internal.messaging.saaj.soap)` in the manifest of bundle `yyyyyy` if somebody is referencing it. 

If you use eclipse with bndtools, you have a resolution view. When you select the jar of bundle `yyyyyy` it can tell you which class is causing the import to be generated.

If this class is used and this is how you want/need it, you must make your framework export this package. This can be done by setting the `org.osgi.framework.system.packages.extra` property. Not sure where karaf does this, but it is most likely defined in some configuration properties files of karaf.

**Comment by rotty3000** [comment]
This might be a side effect of the Class.forName import referencing feature
added around that era.

Try adding the instruction `-noclassforname: true` to see if it solves the
resolution issue.

**Comment by bjhargrave** [comment]
Bnd has improved over time. It got better at finding class references in bundles which may be what you are seeing. 

> If this class is used and this is how you want/need it, you must make your framework export this package. This can be done by setting the `org.osgi.framework.system.packages.extra` property. Not sure where karaf does this, but it is most likely defined in some configuration properties files of karaf.

This is probably your solution. You need to make sure the Karaf framework is configured to know that the subject package is available (exported) from the Java runtime (assuming it actually is). Karaf may have configured bootdelegation for `com.sun.*` but this does not solve the resolver's need to find an exporter for the package.

So I don't think there is a real Bnd defect identified here. Please take such usage questions to the Bnd Discourse Group. See <https://github.com/bndtools/bnd#feedback>.

**Comment by Ozame** [comment]
Thanks everyone for the explanations, I think this cleared out the problem. Through @juergen-albert 's suggestion I found out that adding those missing packages to Karaf's jre.properties exports them to be properly available, which fixes the issue. 

> So I don't think there is a real Bnd defect identified here. Please take such usage questions to the Bnd Discourse Group. See https://github.com/bndtools/bnd#feedback.

Oh, thanks for the info, I didn't notice that this existed. Sorry for the inconvenience.
