### ISSUE TITLE
[examples] bnd-resolver-maven-plugin minimal bndrun file?

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5192]
I have a pure maven plugin I'd like to run integration tests with. The project does not use the bnd-tooling.

For now I started with not specify any file. this results in:

> [WARNING] No bndrun files were specified with <bndrun> or found as *.bndrun in the project. This is unexpected.

With an empty file this results in:

> [INFO] Bnd inferred -runee: JavaSE-11
> [INFO] -runbundles: null

Next I added

```
<plugin>
  <groupId>biz.aQute.bnd</groupId>
  <artifactId>bnd-maven-plugin</artifactId>
  <extensions>true</extensions>
  <executions>
	  <execution>
		  <id>test-jar</id>
		  <goals>
			  <goal>test-jar</goal>
		  </goals>
		  <configuration>
			  <bnd><![CDATA[
			  -noextraheaders: true
			  -noimportjava: true
			  ]]></bnd>
			  <testCases>junit5</testCases>
		  </configuration>
	  </execution>
  </executions>
</plugin>
```

Now I get:

> [INFO] Bnd inferred -runrequires: osgi.identity;filter:='(osgi.identity=pax-jpa-itest)'
> [INFO] Bnd inferred -runee: JavaSE-11
> [ERROR] Resolution failed. Capabilities satisfying the following requirements could not be found:
>     [<<INITIAL>>]
>       ⇒ osgi.identity: (osgi.identity=pax-jpa-itest)

So it seems there is some bare-minimum one needs to specify to use the plugin. To help users it would be nice to have the following:

- an example what is required as minimum to use the plugin
- or maybe generate a file containing those things (if possible) if the file is empty/missing

**Comment by rotty3000** [comment]
Hello @laeubi I'm sorry you are having such a hard time with testing. In the flurry of comments you've made about OSGi testing I've lost whether you've deciphered a few things and made progress or not.

Next, if you are using bnd*-maven-plugins you are using bnd tooling ;), but I digress.

Lastly, this sounds like you are having usage issues rather than identifying a bug. Can we discuss this over in https://bnd.discourse.group/ ?

**Comment by laeubi** [comment]
> Next, if you are using bnd*-maven-plugins you are using bnd tooling

Well, I should have ben more precise in not using bnd-**ide**-tooling :-)

> I've lost whether you've deciphered a few things and made progress or not.

I could run the examples but can't get a standalone setup running. Actually I'm aiming in using osgi-test for integration testing

> Can we discuss this over in https://bnd.discourse.group/ ?

Sure, I singed up there but whats next? Should I open a new topic?

**Comment by bjhargrave** [comment]
Have you looked at https://github.com/osgi/osgi-test/tree/main/examples/osgi-test-example-mvn which is a complete example of osgi testing in maven with the Bnd maven plugins?

Since this is a usage question, I will close this issue. Further discussion should be in the discourse group.

**Comment by laeubi** [comment]
@bjhargrave yes I have looked at the example, but it is complete unclear what of all these properties are actually required, what are specific to the example and what are purely optional (e.g. only required in bnd-ide) ...
