### ISSUE TITLE
Allow multiple source paths to be defined

### ISSUE THREAD

**Issue by jawi** [bndtools/bnd#520]
I was under the impression that the '-sourcepath' property allowed me to specify additional paths, but this is not the case (it is only used to gather the included sources). 

It appears that almost everything is in place for Bnd to handle multiple source paths, but only the single-valued 'src' property is currently used. Is there any reason to not allow multiple source paths to be defined?

(see also [this discussion](https://groups.google.com/forum/#!topic/bndtools-users/woTgOcNkUQo))

**Comment by sandermak** [comment]
For other people finding this issue: this was resolved on master with https://github.com/bndtools/bnd/commit/b5822a57e7e9e0b0b88b51c2c0ae63c29b1587d3

Just add a line like ```src: src,src-gen``` to your bnd file.

Verified that it works for us in a Gradle build using a snapshot build (https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles/biz.aQute.bnd.gradle/biz.aQute.bnd.gradle-latest.jar) of the bnd gradle plugin.
