### ISSUE TITLE
Missing 'aQute.bnd.exceptions' package in bndlib

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#5200]
The latest release (6.2.0) version of `biz.aQute.bndlib` doesn't comprise `aQute.bnd.exceptions` package. I think we would need to package it in bndlib. However, this package exists in the `biz.aQute.remote.agent`.

**Comment by bjhargrave** [comment]
It is in the biz.aQute.bnd.util artifact which biz.aQute.bndlib depends on for several packages: classfile, signature, stream, unmodifiable, and exceptions. So the package is not intended to be in biz.aQute.bndlib. The change to add the biz.aQute.bnd.util artifact was made in 6.0.0.

Can you be more specific on what issue you are facing?

**Comment by amitjoy** [comment]
We are using bndlib in lots of places and have been packaging the utility classes inside the bundles using `-conditionalpackage`. Now, after updating to `6.2.0` from `5.3.0`, I encountered lots of compilation errors. I didn't know about the `biz.aQute.bnd.util`. I think I will consume it from mvn central and consume the required packages.

**Comment by bjhargrave** [comment]
> I think I will consume it from mvn central and consume the required packages.

Yes, you will need to include biz.aQute.bnd.util on your buildpath too. Then your -conditionalpackage can include any needed packages from biz.aQute.bnd.util.

**Comment by bjhargrave** [comment]
I think we can close this issue.
