### ISSUE TITLE
[Feature Request] Option to disable trace logs in `aQute.remote.util.Link<L, R>`

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#5240]
External applications could make use of Bnd Remote Agent to connect to remote runtimes and the trace logs appear consistently and pollutes the remote runtime console heavily. It would be better to introduce a system property to disable the logging on demand.

**Comment by bjhargrave** [comment]
When [launching Bndtools](https://github.com/bndtools/bnd/blob/master/bndtools.core/bndtools.cocoa.macosx.x86_64.bndrun) for testing/debugging, we use [the logback slf4j binding](https://github.com/bndtools/bnd/blob/815cb773b4459b73bd18d9df7eceb6f899162a32/bndtools.core/bndtools.shared.bndrun#L11-L15) with this [configuration file](https://github.com/bndtools/bnd/blob/master/bndtools.core/logback.xml) to control the log levels for various loggers.

**Comment by amitjoy** [comment]
I think we need to introduce logging support [here](https://github.com/bndtools/bnd/blob/484abbf513308859da7faa51d5e488e5cb80ef2c/biz.aQute.remote/src/aQute/remote/util/Link.java#L309)

**Comment by bjhargrave** [comment]
> I think we need to introduce logging support [here](https://github.com/bndtools/bnd/blob/484abbf513308859da7faa51d5e488e5cb80ef2c/biz.aQute.remote/src/aQute/remote/util/Link.java#L309)

In the title of this issue you named `aQute.lib.link.Link` which is, of course, where I looked. Now you seem to instead be talking about `aQute.remote.util.Link` which is a different class. Please correct the title to refer to the class you are talking about. Thanks.

**Comment by amitjoy** [comment]
Yeah, you are right. It was confusing. My bad!! I will change it right away.

**Comment by pkriens** [comment]
Closed by https://github.com/bndtools/bnd/pull/5345
