### ISSUE TITLE
`-runstartlevel` behaves like `-runbundles`

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#5251]
We have added custom start levels in `-runstartlevel` for few bundles. We have in the meanwhile (~5-6 months ago) removed some bundles from the workspace but the corresponding entries still exist in the `-runstartlevel` instruction. Now, in 6.3, if I start the bndrun which inherits this `-runstartlevel`, it reports the problem as enclosed. It seems that `-runstartlevel` now behaves like `-runbundles`. If I remove these obsolete entries from `-runstartlevel`, everything works fine. But, it used to work perfectly in 6.2-REL. 

I know that we should remove those obsolete entries from `-runstartlevel` but still I wanted to let you know if the behaviour of `-runstartlevel` has now been changed in the meanwhile so that it doesn’t introduce any other lurking issues in future.

![Screenshot 2022-05-12 at 15 26 26](https://user-images.githubusercontent.com/13380182/168096139-58a58068-1a7d-4c38-b189-c2c128d9365a.png)

**Comment by bjhargrave** [comment]
Is this not the same as https://github.com/bndtools/bnd/issues/5260?

**Comment by amitjoy** [comment]
Yes, it can be closed now as it has been fixed by https://github.com/bndtools/bnd/pull/5262
