### ISSUE TITLE
Backward incompatibility due to the decoration around `-runstartlevel`

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#5260]
In our project, we have a central bnd file where we have specified all the start levels for all the different bundles and all bndruns now inherit the start levels from this root bnd file. Now, when I run any one of them (bndrun), all the bundles specified in the start level list (`-runstartlevel`) are installed even though the bndrun doesn't have them in its `-runbundles` list. 

In addition, I also have a project which uses the root `-runstartlevel` to prepare a metadata bundle comprising the start levels of all associated bundles.

Due to the introduction of decoration around start level (`-runstartlevel`), if I append `*` at the end of all bundles, bndruns work as expected as now `*` acts as optional type. But, now the aforementioned metadata bundle is unusable as it now contains a `*` in all the bsns.

Is it anyway possible to make the decoration around `-runstartlevel` optional or at least if it is possible to have it the way as it was before?

**Comment by pkriens** [comment]
I agree this is a regression. The new decoration code changed the semantics of the old decoration code by adding literals. At least for all headers that use Project.getBundles(). I think the new semantics do make some sense but the backward incompatibility is quite bad. Having to add a '*' to each bsn is quite ugly.

Maybe we can use another character for decorators with this new behavior? I.e. a '+' for only decorating when the literal matches and '!' for matching & adding literals.

     -runbundles a, b, c
     -runbundles+ a;startlevel=1, b; startlevel=2,d;startlevel=4
     >>>>>> a;startlevel=1, b;startlevel=2, c
     -runbundles! a;startlevel=1, b; startlevel=2,d;startlevel=4
     >>>>>> a;startlevel=1, b;startlevel=2, c, d;startlevel=4

**Comment by bjhargrave** [comment]
This can be handled by making the items not a literal:

See https://github.com/bndtools/bnd/blob/cff2231ed661a71bf0a26b1b1257ab6eb3486961/cnf/build.bnd#L30-L49

The Bnd build itself relies upon the adding of literals:

https://github.com/bndtools/bnd/blob/cff2231ed661a71bf0a26b1b1257ab6eb3486961/cnf/build.bnd#L41-L42



> Maybe we can use another character for decorators with this new behavior? I.e. a '+' for only decorating when the literal matches and '!' for matching & adding literals.

Interesting, but then you have to decide how `+` and `!` merged properties are merged. :-) Do all `+` decorations come before/after all `!` decoration.

**Comment by bjhargrave** [comment]
> Shall we do this? It is a two liner, I can fix it if you're ok with this approach.

What is a two-liner? I am not sure I understand your proposed change. Perhaps a call to discuss is in order.

**Comment by amitjoy** [comment]
Thanks a lot @bjhargrave and @pkriens to take care of it so carefully 👍

**Comment by bjhargrave** [comment]
@amitjoy Please confirm the latest 6.4.0-SNAPSHOT fixes this for you and I will then push the fix to a new 6.3.0 RC build.

**Comment by amitjoy** [comment]
@bjhargrave on it

**Comment by amitjoy** [comment]
@bjhargrave I am hereby confirming that the behaviour is once again backward compatible and works as expected. Thanks a lot once again for your quick support as always 👍
