### ISSUE TITLE
Error Message on missing OCD is a bit misleading

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5269]
If I use and Configuration Annotation and `@Designate` without an `@ObjectClassDefintion` the following Error is shown in bndtools on the bnd file:
```
DS Component my.fancy.ConfigAnnotation specifies ocd class de.jena.mdo.data.importer.DataImporterConfig which cannot be found; known classes []
```

I would add a text like: `Is there an ObjectClassDefintion Annotation missing onmy.fancy.ConfigAnnotation?`

We may also look into placing the error on the `@Designate` that is causing it.

**Comment by bjhargrave** [comment]
@juergen-albert Are you still planning on making a PR for this?
