### ISSUE TITLE
junit-platform: Better diagnostics when test class cannot be resolved

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#5271]
When trying to use the new `assertj-core` 3.23.0 with `osgi-test`, https://github.com/bndtools/bnd/issues/4766 resurfaced. The issue is that `assertj-core` 3.23.0 depends upon Jupiter 5.9.0-M1 [inadvertently](https://github.com/assertj/assertj-core/issues/2637) and we had Jupiter 5.8 in the test execution. It all resolves because `assertj-core` optionally depends upon the Jupiter packages since people may use `assertj-core` without Jupiter.

It seems to me this sort of problem will occur in the future as `assertj-core` raises the level of Jupiter required.

So I am wondering if we should include some runtime check of the bundle wirings to detect and alert the case where the Jupiter and `assertj-core` bundles are resolved but the `assertj-core` bundle's optional wirings to Jupiter are not wired.

In `biz.aQute.tester.junit-platform` where it [confirms the test call can be resolved](https://github.com/bndtools/bnd/blob/1e03d93bf600dbe87604a80018f28be98519245e/biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java#L389-L395) when the test class resolve fails (as it does in the above case), the code could examine the bundles for optional wires to Jupiter which are not wired and provide a more informative message.

**Comment by kriegfrj** [comment]
As it simply reports the exception that it catches, at the moment the quality of that diagnostic depends on the framework. As it is the framework that is attempting to load the classes, it is only the framework that is in a position to tell us why. 

I guess we could special- case checks for wires to Jupiter; I was trying to keep the code generic though.

**Comment by bjhargrave** [comment]
If we get an ArrayStoreException, it most likely means some type could not be loaded. However, the way the reflection code is written in the runtime, it provides no information on the missing type. But I do think some diagnostics on optional wires to Jupiter that are not wired would be a hint as to a potential problem.

**Comment by bjhargrave** [comment]
I played around with trying to do this and it is hard and not likely to provide much useful information.

**Comment by kriegfrj** [comment]
While it's disappointing to know you couldn't improve things, I would have been upset if I had left any low-hanging fruit unpicked. 😄
