### ISSUE TITLE
bnd-baseline-maven-plugin: Support additional bundle fragments

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#5289]
Currently when a bundle has been split up in one main bundle and multiple fragment or merged back from multiple fragments into one bundle (in the current SNAPSHOT version) baselining will emit a lot of false positives. Instead of just ignoring the according packages/bundle headers, it would be beneficial if the bnd-baseline-maven-plugin would support one or more additional fragments in either the base or the current version.

**Comment by bjhargrave** [comment]
Baselining is for comparing artifacts, not comparing collections of artifacts. The base API supports diffing `Jar` objects.

https://github.com/bndtools/bnd/blob/b25057bda79b087bed5f3856c343bbe6e8a5ebca/biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java#L99

So when you refactor an artifact's contents, you will need to handle the baselining issues in that release.

**Comment by bjhargrave** [comment]
Bnd maintainers discussed and we feel this would add too much complexity for limited corner case. Package baselining is fine here. One should prefer not to baseline bundles (Bundle-Version).
