### ISSUE TITLE
bndtools export bndrun exports only launcher in maven shape

### ISSUE THREAD

**Issue by maho7791** [bndtools/bnd#5293]
bndtools version 6.3.1

Pressing the export button in the bndtools export button only exports a jar with the launcher in it, but no other jars from the bndrun. 

The export goal in maven works well with the same bndrun.

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by pkriens** [comment]
I verified it with several setups and it seems to work fine. Closing it until a repo is provided
