### ISSUE TITLE
[bnd-testing-maven-plugin] only create a report but do not fail?

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5295]
https://github.com/bndtools/bnd/blob/master/maven/bnd-testing-maven-plugin/README.md

I'm missing a a surefire feature where one can have `-Dmaven.test.failure.ignore=true` to not fail (but create test reports) if a test currently fails.
This is useful if you run it on a CI server and want to collect all test reports at the end and e.g. mark a build with failing test yellow.

As it is very common, it would be good if BND could also support the `maven.test.failure.ignore` property.

**Comment by bjhargrave** [comment]
To avoid direct conflict with `maven.test.failure.ignore` which is for unit tests, the fix uses the system property `bnd.testing.failure.ignore` for `bnd-testing-maven-plugin`. I was not sure it is a good idea to also use the `maven.test.failure.ignore` name.

**Comment by laeubi** [comment]
Thanks for the fix, an own property is fine for sure.
Is there a SNAPSHOT repository to test this beforehand or do I need to wait fro the next release?

**Comment by bjhargrave** [comment]
> Is there a SNAPSHOT repository to test this beforehand or do I need to wait fro the next release?

https://github.com/bndtools/bnd#using-the-latest-development-snapshot-build-of-bndbndtools

**Comment by laeubi** [comment]
Just tested it an it works great :+1:
