### ISSUE TITLE
[bnd-maven-plugin] bootstrap the bnd-process-goal with an existing manifest

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5297]
See https://github.com/bndtools/bnd/blob/master/maven/bnd-maven-plugin/README.md#bnd-process-goal

I have an existing, hand written manifest, and like to use bnd-maven plugin to enhance it, e.g. add DS, or metatype.

Would it be possible to enhance the `bnd-process-goal` to have a parameter `bootstrapManifest` where I can pass an existing `MANIFEST.MF` so BND uses that to add additional data?

For sure it would be better to let BND do the whole job, but there are situations where existing manifest is there and e.g for migration purpose or other limitations only certain tasks should be delegated to bnd for now.

**Comment by bjhargrave** [comment]
Did you try `-include: META-INF/MANIFEST.MF` in the Bnd instructions? If the include file name ends with `.mf` (case insensitive), then Bnd will treat the file as a Manifest and include the manifest headers in the Bnd instructions.

**Comment by laeubi** [comment]
Thanks, I'll try that out, that looks very promising!

**Comment by laeubi** [comment]
@bjhargrave I have tested this and it works so far that if in the manifest there is an entry it gets loaded, but entries get not merged, e.g. I have in MANIFEST.MF:

`Require-Capability: osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"`

and in the BND file:

`Require-Capability: osgi.serviceloader;osgi.serviceloader="org.osgi.framework.connect.FrameworkUtilHelper"`

the later seem to be ignored. So could I either:

1. enable merging entries
2. let BND take precedence over Manifest entry?

A live example can be found here: https://github.com/eclipse-equinox/equinox/pull/70

**Comment by bjhargrave** [comment]
Closing as this can be done by `-include` on a manifest file.
