### ISSUE TITLE
[jpms] can the generated module-info.class take ;x-internal:=true into account?

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5308]
I'm currently try to automate the JPMS generation in equinox even more, see https://github.com/eclipse-equinox/equinox/pull/70

One issue I found is, that if a package is marked as [`;x-internal:=true`](http://docs.osgi.org/reference/bundle-headers.html) it still apears in the JPMS output, eg.: `exports org.eclipse.osgi.internal.debug;` it would be nice if JPMS gnerator could be adviced to not export such packages.

**Comment by laeubi** [comment]
> If a package is really "internal", then the correct answer generally is not to export it.

As per http://docs.osgi.org/reference/bundle-headers.html it is a standardized directive

`Export-Package | x-internal:, x-friends: | Eclipse Foundation`

> Also, please ask usage questions in the Bnd Discourse Group

This is more an enhancement request.

**Comment by bjhargrave** [comment]
> As per http://docs.osgi.org/reference/bundle-headers.html it is a standardized directive

That does not make it standardized by OSGi. It just means Eclipse has defined a custom directive and it is displayed in the registry so others can be aware of it. But the OSGi spec has nothing to say about it. You will see the previous line mentions the standard directives and attributes as defined by OSGi.

**Comment by laeubi** [comment]
> That does not make it standardized by OSGi.

The document claims different:

>> This section contains a registry for reserved header names **in the OSGi Specification**.

Anyways its not some obscure custom header by a random third-party product but if you don't want to call it standardized we might agree on its a "well defined extension" and would for sure help adopting and acceptance of BND-JPMS module generation. And as it already does a very good job I think this could be beneficial over the current widely used approach of writing the module info by hand...

**Comment by bjhargrave** [comment]
> This section contains a registry for reserved header names **in the OSGi Specification**.

And others. This is not a real point of argument. `x-internal` does not appear in the core spec. You will not convince any one in the OSGi project that it is part of the OSGi spec.



> "well defined extension"

`x-internal` is not a well-defined thing. It is an Eclipse hack whereby Eclipse wants to have its cake and eat it too. Eclipse wants to export the packages and then pretend they are internal. Once they are exported, they are not internal. :-)

Also, Eclipse defined the directive name to start with `x-` which Bnd specifically ignores during bundle verification:

> Directives that are not part of the OSGi specification will give a warning unless they are prefixed with a ‘x-‘.

**Comment by laeubi** [comment]
> You will not convince any one in the OSGi project that it is part of the OSGi spec

I don not aim to convince anyone anyways, I'm just try working with whats a fact today, Eclipse is all open source, so if this really bugs someone it would better be discussed/improved there and then we can kick this off any official OSGi documentation and everyone is happy.

> It is an Eclipse hack whereby Eclipse wants to have its cake and eat it too. Eclipse wants to export the packages and then pretend they are internal. Once they are exported, they are not internal. :-)

Sure but its not me to change the whole Eclipse-Way, I can just try to iteratively improve things, and telling people they are doing things *wrong* and should change to use the only tool that knows how to do it *right* is only the start of fruitless discussion.

So I don't ask for BND to verify and/or change here, its just a suggestion for a very specific Plugin (the JPMS module) to improve its output so the *bad* things do not drip into the generated JPMS infos :-)

**Comment by bjhargrave** [comment]
> its output so the _bad_ things do not drip into the generated JPMS infos :-)

I guess the first order question is whether it _IS_ bad for the `x-internal` packages to be exported by the JPMS module. These package are exported by the system bundle in OSGi and are thus available for other bundles to import. So what is the harm of these packages being exported by the JPMS module? That is, if these packages are available for bundles to use in OSGi, why should they not also be available for modules to use in JPMS?

**Comment by laeubi** [comment]
> So what is the harm of these packages being exported by the JPMS module?

I can't answer that, for this specific issue (Equinox) they where not exported with the hand-crafted module-info, so I assumed that was for a reason, and there seems a reason to export them "not so public".

**Comment by bjhargrave** [comment]
> I can't answer that,

We need to get @tjwatson to weigh in here as he created the original module info.



> export them "not so public"

If I recall correctly, `x-internal` is not processed by the OSGi framework in anyway. It is just "advice" to p2. @tjwatson ?

**Comment by juergen-albert** [comment]
This topic seems in general be more a discussion for the discourse or as an issue on the equinox project.
Given my experience with eclipse projects, a lot of the internal packages especially marked with the x-internal or x-friends, have become kind of public api anyway. Most developers just use Require-Bundle and ignore the warning it produces (works at least for x-friends, not sure about the x-internal). Given this best practice I've seen in the wild, I'd suggest discussing the merit of its use where it should be discussed. 

On a personal note, I can say that i hate constructs like this with a passion. It is used in parts as public api, but only by privileged bundles. And it BTW has only an effect in equinox. In felix it is simply exported if I'm not mistaken.

**Comment by tjwatson** [comment]
> And it BTW has only an effect in equinox.

It has no effect in Equinox.  At this point I only think PDE pays any attention to x-internal x-friends directives.  I did not place the  x-internal or x-friends directives in the module-info because they are not "real" API.  I make breaking changes to them all the time.

**Comment by tjwatson** [comment]
I see no reason to have BND pay any attention to these directives.  I simply saw no need to export them from the JPMS module because I didn't want the java compiler to allow them to be compiled against in the JPMS world.  I really don't want the x-internal/x-friends packages  to be used in any world.  But on the other hand, I'm not sure I would ask BND to do anything here.

**Comment by laeubi** [comment]
> It is just "advice" to p2

P2 has nothing to do with it, its just a **tooling** (PDE) concern used e.g. to warn you with a restriction warning if you use this and are not an x-friend and per Eclipse-API tools you are allowed to "break" internal API without any punishment.

> I really don't want the x-internal/x-friends packages to be used in any world.

That's why I think it would be good to at least ban them in JPMS already, and as these are Tools-Concerns it fits into the BND-Tool ;-)

> On a personal note, I can say that i hate constructs like this with a passion.

I don't think 'hate' helps anything....


> Most developers

Just a personal note: I generally _don't like_ this "most developers" argument as it is neither useful nor proves anything. I think there is no such thing as "most developers" and things are evolving every day.

>  And it BTW has only an effect in equinox. In felix it is simply exported if I'm not mistaken. This I would stand with BJ on this.

As described this is a tooling concern, and BND is a tool, so its valid to ask for it if it can process such things, as it process many things that are irrelevant at runtime e.g (non standard) annotations.

> This topic seems in general be more a discussion for the discourse or as an issue on the equinox project.

Just as a note I found [Github Discussion](https://docs.github.com/en/discussions) much more useful instead of "just another tool" with "just another login", so maybe BND could think about migrating to discussions. Issues can also be converted into a Discussion if it seems there is more to discuss because deriving a "real" issue from it.

**Comment by bjhargrave** [comment]
Closing, the Bnd maintainers do not want to support x-internal.

**Comment by djencks** [comment]
I’m lacking context to understand why you want this.  What’s stopping you from making a normal bundle without the x-* eclipse hacks?  I wasn’t there at the time, but my impression is that these hacks arose because management decided to osgi-ify eclipse but not fund designing appropriate APIs.  Why would you want to perpetuate such unusable design decisions?

**Comment by tjwatson** [comment]
> I’m lacking context to understand why you want this. What’s stopping you from making a normal bundle without the x-* eclipse hacks? I wasn’t there at the time, but my impression is that these hacks arose because management decided to osgi-ify eclipse but not fund designing appropriate APIs. Why would you want to perpetuate such unusable design decisions?

This issue is closed and done, not sure what the point is of this comment.  The end result of x-internal may not have accomplished the original goal.  But to say the old guard of the Eclipse project did not "fund" designing appropriate APIs is laughable.  The team was huge, spent a year each release honing any new APIs, had regular adopters consuming each monthly milestone, giving feedback on the new APIs (both open source and commercial products).  Because they took API design so seriously it took at least a year to get a new API in a public release.  This is the reason x-internal is there.  While an API was in its "beta phase" they would export it with x-internal to allow adopters to try it out early before it was even ready to go into M1 of a release cycle.

Now the end result did not work out so well years and years later, where large projects have become dependent on internals with no real path forward to get off onto a public API.  But that is not at all where this started with "not enough funding" for API design.
