### ISSUE TITLE
Changes for the next Major Version

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5316]
We quite often have corners that are how they are for historic reasons. They made sense at the time, but cause nowadays behavior that seems counterintuitive and is often hard to explain to new users and changing them might cause existing setups to change or break. I think we should try to change some of them with the next major release. 
I hope we can use this issue to collect and discuss at least the smaller changes, that might be easy to fix. 

I make a start:

# bnd-testing-maven-plugin - default scopes
The testing plugin uses the compile and runtime as its default scopes. This is according to @rotty3000 a remanent of the time, as we havn't support tests in the `src/test/java` directory.  We should add the TEST scope, now that it can be used in the standard Maven fashion.

# poll_time default for repositories
AFAIK we currently have the default for most Repositories set to 5 seconds. auto polling of repositories is sometimes useful, but usually is something you don't want (maybe except for SNAPSHOTS). It additionally can cause problems in Eclipse, especially with the `BndPomRepository`. I'd suggest changing the default to -1, at least for the afore mentioned repo.

**Comment by bjhargrave** [comment]
Perhaps we need an issue per item since they can be discussed and action taken independently.

**Comment by bjhargrave** [comment]
Closing as each item should be its own issue.
