### ISSUE TITLE
Performance: bndtools takes too long for SHA-256 and is not interruptable

### ISSUE THREAD

**Issue by reckart** [bndtools/bnd#5322]
It seems that bndtools is slowing down things significantly when used in a large Eclipse workspace / projects with lots of dependencies. Using the sampler VisualVM, it appears that the time is mostly spent for SHA-256 calculation.

<img width="1482" alt="Screenshot 2022-07-18 at 12 38 25" src="https://user-images.githubusercontent.com/1410238/179495205-f2c9a0b0-8d4b-4e4c-a74b-27fd3051b34a.png">

Even when trying to shut down Eclipse, the shut down hangs because bndtools first wants to complete these SHA-256 calculations. 

* It would be nice if calculations would not take so much time - maybe they can be performed lazily or maybe they can be cached?
* When Eclipse is being shut down, it would be nice if the m2e bndtools would detect this and stop their build.

**Comment by pkriens** [comment]
The issue is not the bnd code, it is the code that is called in the VM (it is confusing that you not show the next 2-3 levels?). Checking for interrupts will only make it slower in the normal case.

**Comment by reckart** [comment]
The SHA-256 is generated from a file, right? As long as the file does not change, it would not be necessary to recalculate the checksum. Maybe a file timestamp could be used as an indication whether the file has changed and if a re-calculation of the sum would be necessary?

**Comment by bjhargrave** [comment]
> I have an idea on how to handle deferral here which I will experiment with.

@reckart Please try PR #5323 to see if that helps your performance issue.

**Comment by reckart** [comment]
The situation seems to be improved. I'll keep monitoring it. Thanks!

**Comment by reckart** [comment]
So, opening the said `bndrun` file in a freshly opened and fully built workspace is down from 15 minutes beachballing to 2 minutes beachballing. Not bad ;)

**Comment by reckart** [comment]
That said, it appears that the background task that builds the implicit repository can still take a very long time and it seems it can also make the Eclipse UI freeze up for a significant time. A first glance with VisualVM does not point to a particular hotspot. The time seems to be spend in general on artifact resolving distributed over a number of difference methods.

**Comment by bjhargrave** [comment]
At some points, the SHA-256 value is needed. There is no way to avoid it being needed. The PR only deferred the calculation into some future which you now seem to be running into. ResourceImpl.equals needs the value to properly determine if two Resources are equal. This equality test needs the values of the attributes of all the resource's capability which includes the SHA-256 value.
