### ISSUE TITLE
Calculate moduleName for multi-release-jar-dependencies

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#5327]
When calculating the module-names of dependencies while using the [jpms modul-info generator](https://bnd.bndtools.org/chapters/330-jpms.html), bnd failed to get the name when the dependency-jar is a multi-release jar with no `module-info` in the root folder but in the `META-INF/versions/9` folder.

https://github.com/bndtools/bnd/blob/53d15f2285114e224d85638459580382c91cb0bc/biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java#L476

ref: #2227

**Comment by laeubi** [comment]
@stbischof I'll try to take a look a good example where this occurs seems 
- https://github.com/ClickHouse/clickhouse-jdbc/tree/master/clickhouse-client/

**Comment by bjhargrave** [comment]
Bnd does not yet have multi release jar support. There is an open issue on that.

**Comment by pkriens** [comment]
Combined with  #5346
