### ISSUE TITLE
Enhance CONTRIBUTING with some basic information about setup of IDE

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5330]
I have read https://github.com/bndtools/bnd/blob/master/CONTRIBUTING.md

it says:

> The only thing you need to build Bnd/Bndtools is Java. 

alright that works, but I assume no one uses test-editor to develop the code and then maven to run the build.

So I downloaded latest, eclipse (for java developers) and installed latest bndtools release, then imported projects from the git repository, but it seems not enough, all projects show a lot of build errors.

So I'd like to suggest to enhance the CONTRIBUTING file with a small section about IDE setup.

**Comment by bjhargrave** [comment]
A PR would be welcome.

**Comment by chrisrueger** [comment]
Some info can be found here: https://bndtools.org/development.html
