### ISSUE TITLE
Include html files in the artifacts / publish results

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5333]
Currently a Github build includes the XML files, but the error output indicates there is a more user friendly way:

> 2: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':biz.aQute.bnd.reporter:test'.
> > There were failing tests. See the report at: file:///home/runner/work/bnd/bnd/biz.aQute.bnd.reporter/generated/reports/tests/test/index.html

Beside that, it would be great to publish the results to github e.g.: https://github.com/marketplace/actions/publish-unit-test-results#support-fork-repositories-and-dependabot-branches

**Comment by bjhargrave** [comment]
> Beside that, it would be great to publish the results to github e.g.: https://github.com/marketplace/actions/publish-unit-test-results#support-fork-repositories-and-dependabot-branches

This link is broken. 

Perhaps you can make a PR with the proposed github actions changes?

**Comment by pkriens** [comment]
Waiting for PR
