### ISSUE TITLE
[jar] the data integrity of bnd Jar at risk because it exposes internal datastructures and allows bypassing sanity checks

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5344]
The (bnd) Jar has several methods to modify the jar

- getResource
- putResource
- remove

all these methods perform two checks

1. that the jar is open
2. that the path is valid to prevent [Zip Slip](https://github.com/snyk/zip-slip-vulnerability) attacks 

beside that it maintains two maps that need to be in sync

- resources
- directories

The problem is that the Jar class exposes direct **modifiable** access to these internal datastructures via the

- getDirectories
- getDirectory
- getResources

methods and thus one can:

1. bypass the  [Zip Slip](https://github.com/snyk/zip-slip-vulnerability) checks by directly putting data into these maps
2. put the jar into an inconstant state, e.g. by only modify  one of the maps, or violate the internal contract of those
3. bypass the close checks

**Comment by pkriens** [comment]
There is no way that bnd is secure in any way, nor are there any intention. Actually, Java security as it stands ranks high in the list bad ideas of Java: it takes a lot of CPU cycles, introduces lots of programming obstacles, and has very little value since you can never really trust it. Only process based security enforced by the OS offers a modicum of security. If we can't trust the code we run then imho all bets are off.

I strongly suggest we close this because I do not think any overhead in bnd for its Java security is worth it.

**Comment by laeubi** [comment]
> I strongly suggest we close this because I do not think any overhead in bnd for its Java security is worth it.

Can you explain where I wrote anything about "Java security"?

**Comment by pkriens** [comment]
> Can you explain where I wrote anything about "Java security"?
You want to make the modifiable acces protected against an attack ... I'd call that security?

**Comment by laeubi** [comment]
> You want to make the modifiable acces protected against an attack ... I'd call that security?

Java Security is an well defined term: https://docs.oracle.com/javase/9/security/java-security-overview1.htm#JSSEC-GUID-2EF91196-D468-4D0F-8FDC-DA2BEA165D10

So if you mean something else, e.g. you think that sanity checks or separation of concerns or object oriented design principles like not exposing (modifiable) state from an object are a "bad idea", it would really help to be clear.

And if all that's "overhead" why was it added at the first place to BND at all?

> I'd call that security?

If you read carefully through the text, it is not only security but also data-integrity. If I allow arbitrary code (trusted or not) to modify my internal states I make my object open to data-corruption (even by accident, not everything is "malicious") and prevents me to perform certain action (caching, alternative views to the internal representation, multi-threading, ...) because I never can be sure that my data is not modified out-of-bands...

**Comment by rotty3000** [comment]
@laeubi I think the heading `[security]` is just hitting a nerve and might be served better to simply renamed to something like: *[jar] the data integrity of bnd Jar at risk because it exposes internal datastructures and allows bypassing sanity checks*. Would that be ok for you?

**Comment by laeubi** [comment]
@rotty3000 sure, feel free to adjust the title what ever fits best here :-)
