### ISSUE TITLE
[bnd] Support processing of Multi-Release-Jars

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5346]
This is related to 
- https://github.com/bndtools/bnd/issues/2227

But only handles a subset, that is, support processing of Multi-Release-Jars.

Currently when one tries to process a Multi-Release-Jar with BND, the `bnd-maven-plugin` complains with the following message:
> [ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:6.4.0-SNAPSHOT:bnd-process (bnd-process) on project clickhouse-client: Classes found in the wrong directory: {META-INF/versions/9/module-info.class=module-info}

The problem is, that BND currently do not read Multi-Release-Jar  correctly leading to issues else where
- https://github.com/bndtools/bnd/issues/5334
- https://github.com/bndtools/bnd/issues/5327
-  ... (see linked issues of https://github.com/bndtools/bnd/issues/2227)

One problem is, that Multi-Release-Jar processing requires to know what are the java release, this usually is taken from either the running VM or by specify it directly, e.g by a compiler switch.

Therefore I propose, as a first step, to allow specify a new directive in a bnd file `-release` that takes an integer and is interpreted as the desired target release.

BND should then work in the following way:

- if no `-release` is specified, it should behave as of today, e.g. Multi-Release-Jars processing is disabled and might even lead to the current problems
- if `-release` is specified and it is smaller than `0` it is interpreted as if it was not specified
- if `-release` is specified and it is smaller than `9` it is interpreted as processing a jar with the default jar content that is ignoring anything from `META-INF/versions` and thus also don't find any modules info, or classes and do not complain
- if `-release` is specified and it is larger or equal to `9` then it is interpreted as processing a jar with the given release, that is any class/resource in `META-INF/versions/...` that are smaller or equal to `<release>` will shade any class/resource from the default jar content

This will ensure:

1. Current users of BND won't be affected and it would be 100% backward compatible
2. Users that demand Multi-Release-Jar can at least read and process jars with the desired `release` option

**Comment by laeubi** [comment]
> I wonder if bnd could be even smarter than that.

Sure, the current approach is just as minimal and "dumb" as possible,mainly to not change too much and thus not requiring any (major) version bumps and my previous attempt even contained a list of discovered versions inside a jar, so one can think about the following:

1. find the minimal EE of the jar to be analyzed, lets assume it is 11
2. find any versioned classes in the jar, lets assume it is 17
3. No check all jars on the analyzer classpath, lets say it includes 9 and 14

So a "smart" way would be to assume we need:

- one computation with `release = 11`  for the default manifest
- a partial one with `release = 14` 
- a partial one with `release = 17` 

but such an automatic approach would that requires much more attention e.g. for the analyzer it needs some kind of loop in "analyze", one for each release to be computed, and probably reset any cached states I don't know how good e.g. Analyzer plugins are prepared for multiple invocations with slightly different content returned.

**Comment by HannesWell** [comment]
Is there any progress planned on this issue?
This is for example a blocker to use the `bnd-maven-plugin` in https://github.com/qos-ch/slf4j/pull/327.

**Comment by bjhargrave** [comment]
It is still on my work queue. I have a local feature branch but the work is still in progress.

**Comment by laeubi** [comment]
@HannesWell there is actually:
- https://github.com/bndtools/bnd/pull/5359

that already supports fully automated building of MR jars, there is even an example here:
- https://github.com/ClickHouse/clickhouse-jdbc/pull/1016

**Comment by stbischof** [comment]
This multi Release jar thing is also a Blocker on our site. Some os project's love the multi release jars.  They would accept bnd als build tool but its blocked by multi release support.

**Comment by pkriens** [comment]
I am closing this as done. The test case for maven does not work yet but that is an open PR and does not seem to affect the current implementation
