### ISSUE TITLE
bnd seems to pollute global maven reactor state

### ISSUE THREAD

**Issue by reckart** [bndtools/bnd#5352]
Ok, so it is a bit complex and I don't have a project to reproduce this... bug here is what happens and my theory:

We have a reactor like

```
 - root
   - module.a
   - module.b 
```

The `pom.xml` in the `root` module has a dependency management section which declares the versions for all the modules, e.g.

```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>foo</groupId>
      <artifactId>module.a</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>foo</groupId>
      <artifactId>module.b</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
  </dependencies>
</dependencyManagement>
```

Furthermore:

* `module.b` and `module.a` are both OSGI bundles
* `module.a` uses the `bnd-resolver-maven-plugin` to prepare a test run and then uses `bnd-testing-maven-plugin` to run the test -- **NOTE: the option `includeDependencyManagement` is turned on**
* `module.b` depends on `module.a`
* `module.b` and `module.a` both use the `maven-dependency-plugin` to detect (un)used (un)declared dependencies and such

During build, I when I turn on debug logging in maven (`-X`) observe that when `module.a` builds, it resolves `module.b` - likely because `includeDependencyManagement` is on and `module.b` is declared there. However, the reactor has not built `module.b` yet and it is also not really required for running the tests in `module.a`. This could already be a problem if we do not have an old SNAPSHOT version of `module.b` lying around in the local m2 cache or in some Maven repo.

Now, when it comes to building `module.b`, I get warnings about split packages from `module.b` and also the maven-dependency-plugin` complains about `module.b` having a dependency on itself.

Again, looking at the debug logging (`-X`), I can see in the dependency tree that Maven resolves at this point for `module.b`, that `module.b` depends on `module.a` (ok) and then that `module.a` depends on `module.b` -- not ok!

This only happens when I build the reactor from the root. If I resume the build from `module.b`, it works nicely then. Thus my theory, that running the `bnd-resolver-maven-plugin` and/or `bnd-testing-maven-plugin` as part of `module.a` pollutes the dependency information of `module.a` at runtime with information obtained through the `includeDependencyManagement` mechanism which then causes the problems in `module.b`.

I'm now trying to work around the problem by removing all dependency management entries related to the reactor itself from the root `pom.xml` - unfortunately, that means that I will have to add `<version>` tags to all the internal dependencies in all modules :(

**Comment by bjhargrave** [comment]
I am not sure it is a good idea for the parent to declare dependencyManagement on the modules being built by the parent reactor. The modules being built declare their version so they do not need to be in the parent's dependencyManagement.

**Comment by reckart** [comment]
Hard to tell. I have been using this approach for years so that I can avoid having to declare versions any dependencies (be it reactor dependencies or external dependencies) by maintaining managed versions for everything in the root pom. So far, I never had trouble with this.

**Comment by reckart** [comment]
Declaring `<version>${project.version}</version>` leads to other problems: if a module in another reactor inherits such a dependency, then `${project.version}` will be looked up in the inheriting module and not in the module the dependency is inherited from - leading to the dependency not being found.

To fix that, I would have to write `<version>1.0.0-SNAPSHOT</version>` everywhere - but that would mean tons of additional changes when a release is being run. 

.... that's why I ended up preferring the approach with managing everything in the dependency management section ....

**Comment by bjhargrave** [comment]
> that's why I ended up preferring the approach with managing everything in the dependency management section

You are free to do that but then you have the issue you mention. The Bnd maven plugins are using the dependencies in the dependencyManagement section since you configured them to do so. They will include these dependencies in a Bnd repository as potential sources for the resolver and `-runbundles`. If this triggers maven-dependency-plugin to decide the dependency is used, then I am not sure what the Bnd maven plugins can do since you configured them to use the dependencyManagement configuration as input.

For your needs, you may want to configure the Bnd maven plugins to not use the dependencyManagement configuration and instead add the needed dependencies to the project's dependency configuration.

**Comment by reckart** [comment]
If I disable dependency management resolution in bnd, I run into the problem that I have to add all the bundles I need as a test platform to the individual modules. I actually (presently) like the feature that I can use the dependency management for that (although it is a bit magic).

What I think is a bug is that running the build of `module.a` in the above example seems to change the set of dependencies that `module.a` has for the rest of the reactor build and that resuming the build from `module.b` (`-rf :module.b`) seems to work ok. If bnd needs to change the dependencies of `module.a` during the build of the module, shouldn't it restore the previous state afterwards again?

**Comment by bjhargrave** [comment]
> If bnd needs to change the dependencies of `module.a` during the build of the module, shouldn't it restore the previous state afterwards again?

Bnd (attempts) to reset the dependency state:

https://github.com/bndtools/bnd/blob/60392b5a7e27b2012ac476204f1477a9c6e01f69/biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/DependencyResolver.java#L216-L247

@rotty3000 can you comment here since you wrote the above code?

**Comment by rotty3000** [comment]
bnd does indeed attempt to reset the project deps. I'll need a little time to look into this scenario but without a reproducing scenario it will be hard to verify.

**Comment by reckart** [comment]
I stumbled into this in a pretty large proprietary code base that unfortunately, I cannot share. I tried with Maven 3.6.x and 3.8.x to try to exclude a Maven bug. I think the description of the scenario captures the main building blocks, but I shy away a bit from trying to build a minimal example because the effort of converting said codebase to a build that includes bnd is already eating most of time time currently. Also, I have now moved away there from declaring intra-reactor dependencies in the dependency management section to navigate around the problem. That said, I felt doing a bug report was a good thing, so I did that. I probably won't be able to help much further atm.

**Comment by rotty3000** [comment]
There is a mixed opinion on whether this is a "Feature" of maven or a sometimes beneficial side effect. However, it is clear that this is not an outright feature of maven, it just happens to work. So, that being said, I think this is an abuse of `dependencyManagement` which results in complications when dependency management is considered to be "the set of things you depend on from outside the reactor" which is how bnd treats if w.r.t. resolution.

So, I don't really know what to do here... But maybe we could filter out things that come from the reactor found in dependency management?

**Comment by pkriens** [comment]
Closed due to inactivity and no clear path forward.
