### ISSUE TITLE
Performance: very long build times

### ISSUE THREAD

**Issue by reckart** [bndtools/bnd#5378]
I sometimes observe that the build gets stuck in the bnd tooling. This time it seems again to drill down to access to JAR files:

<img width="1179" alt="Screenshot 2022-09-23 at 10 16 15" src="https://user-images.githubusercontent.com/1410238/191919744-1140917b-268a-41bc-bfae-d969741b2e5e.png">

**Comment by reckart** [comment]
While https://github.com/bndtools/bnd/pull/5372 does not seem to do much for #5367 and #5322, it might do something for this PR. I'll try testing a combination of https://github.com/bndtools/bnd/pull/5372 and my own makeshift cache in `ResourceBuilder` as outline in https://github.com/bndtools/bnd/issues/5367#issuecomment-1241017865

**Comment by bjhargrave** [comment]
Closing by #5372
