### ISSUE TITLE
Duplicate context menu items

### ISSUE THREAD

**Issue by reckart** [bndtools/bnd#5393]
After running an OSGI JUnit test for the first time, the BND launching context menu item in the Eclipse context menu are duplicated:

<img width="321" alt="Screenshot 2022-10-07 at 10 20 14" src="https://user-images.githubusercontent.com/1410238/194507412-d773ad76-58ec-45d1-b16e-2ac47da2b6a1.png">

**Comment by bjhargrave** [comment]
Perhaps your p2 install of Bndtools is messed up. Try with a fresh Eclipse and Bndtools installation.

**Comment by kriegfrj** [comment]
Does the project have both Bnd and m2e natures by any chance?

**Comment by reckart** [comment]
It probably does because all my projects are Maven projects and most of them are now also using bndtools and the bnd-maven-plugin.

**Comment by kriegfrj** [comment]
You can use Bndtools m2e without your project having the bndtools nature. Can you post your .project and .classpath files to be sure?

**Comment by reckart** [comment]
I have upgraded to Bndtools 6.4.0.DEV-202210141516-g1414370	- here, I don't see the issue anymore.

**Comment by reckart** [comment]
Btw. I checked - there were no two natures when I checked. But this was after the upgrade to 6.4.0.DEV-202210141516-g1414370, so I don't know if earlier possibly two natures were present.

**Comment by reckart** [comment]
Issue still exists.

Here the contents of the `.project` file of the relevant project:

```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>MY-PROJECT</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.m2e.core.maven2Builder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>org.eclipse.m2e.core.maven2Nature</nature>
	</natures>
</projectDescription>
```
