### ISSUE TITLE
remove `-includeresource` as one of the Markers to ignore Annotations

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5407]
`-includeresource` is together with `Export-Package` and `-privatepackage` a trigger to not look for `@Export` annotations. If you want to include resources with your bundle and still use the comfortable Annotations you need to give the `-includeresource` a namespace and then it works. This however is so much magic, that most of our customers are confused regularly and I need to explain to basically everybody at one point why suddenly all there Packages are marked as excluded. 

I would opt for changing this once an for all. I know that changing default behavior is bad and can break things. In this case however I believe it will not. 
I see the following scenarios:
1. use of `-includeresource` in a reosurce only bundle or one with no code: nothing changes
2. use of `-includeresource` with Annotations via a namespace: nothing changes
3. `-includeresource` with manual Package declaration: nothing changes
4. `-includeresource` with abandoned code that is not intended to be packaged: Well, in this case it will have an impact. But why should this be a pattern?

Anything I may have missed?

**Comment by stbischof** [comment]
I am absolutely with you. Run to often in this.

Maybe just deprecate includeresources and create a Importresource instruction that does it .. right..

**Comment by bjhargrave** [comment]
@pkriens suggests we instead change the defaults to provide the everything-in-project behavior rather than the current way we do this.
