### ISSUE TITLE
Hot code replacement does not work while running a bnd application in Eclipse

### ISSUE THREAD

**Issue by mikerumpf** [bndtools/bnd#5410]
While running bnd applications with bndtools (6.3.1.REL-202206071316) in the Eclipse (Version: 2022-06 (4.24.0) on Windows 10 debugger hot code replacement seems not work. ( I have the "Update bundles during runtime" option turned off in the run configuration)

I always get the follwing error dialog:

![bnd-hotcode-replacement](https://user-images.githubusercontent.com/1438969/199504113-7bc5009a-42e0-4421-8e71-d52baad62493.png)

(Java: Openjdk version "11.0.3" 2019-04-16)

**Comment by juergen-albert** [comment]
We discussed the topic at length and we are not sure how to solve this. We have a few suspicions on the probable causes but no clue or knowledge on how to help Eclipse along here. 

If anybody has a clue how the eclipse usually does this sync, any hint would be appreciated.

**Comment by leftbit** [comment]
Getting Hot-Code-Replacement-Errors when updating resource files. In my case some XML contained in a folder configured with
```
-includeresource: \
	resources=resources
```
Changing the XML triggers the compiler.

**Comment by mikerumpf** [comment]
Setting the property "java.security.manager=allow" in the bdnrun file solves the issue. Would be cool if bndtools would include this option, when launching in debug mode.

**Comment by mikerumpf** [comment]
However we still encounter issues like this while debugging: Any idea why we are getting timeouts?

![error](https://user-images.githubusercontent.com/1438969/215766008-c7cc2fe9-f697-4d1c-ad6d-d49c5c9543d7.png)

**Comment by mikerumpf** [comment]
> Setting the property "java.security.manager=allow" in the bndrun file solves the issue. Would be cool if bndtools would include this option, when launching in debug mode.

It's quite weird: After setting the property I could solve the initial issue in one workspace. After that I could remove the property and it still was working. In another workspace setting the java.security.manager didn't have any effect at all...

**Comment by mikerumpf** [comment]
Regarding the "contains obsolete methods"-error: 

It appears that this error only occurs for hot code replacement in activate-methods or methods annotated with `@Reference`.

If I extract the contents of the activate method in its own method and try hot code replacement in this extracted method (called from activate) everythings works fine. 

I guess this must be an issue with reflection used to call methods like activate.
