### ISSUE TITLE
add another instruction name for `-runstartlevel`

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5413]
I myself and a couple of our customers individually run in the misconception the `-runstartlevel` instruction configures configures the Launcher (on what level to start and so on). I know that this is a classical case of RTFM as it is explained perfectly well. 

Projecting my own stupidity on the rest of the world I would suggest to introduce a more idiot proof naming for it.

As this configures the behavior of the resolver I would suggest something like `-resolver.startlevel` or `-resolverstartlevel`. The .startlevel variant would fit to `-resolver.effective` but might confuse people as it would collide with the general namespace concept.

We should keep the old instruction to stay backward compatible and replace it everywhere in the documentation.

**Comment by bjhargrave** [comment]
Closing as wont fix.
