### ISSUE TITLE
JUnit 5 extension auto-registration support (?)

### ISSUE THREAD

**Issue by reckart** [bndtools/bnd#5420]
Is there already a way to use the [JUnit extension auto-registration](https://junit.org/junit5/docs/5.5.0-RC1/user-guide/index.html#extensions-registration-automatic) with the bnd test runner?

Simply adding a `runroperties` in the `*.bndrun` file does not seem to do the trick:

```
-runproperties: \
	junit.jupiter.extensions.autodetection.enabled=true,\
```

**Comment by bjhargrave** [comment]
Did you try

`-runvm: -Djunit.jupiter.extensions.autodetection.enabled=true`

**Comment by kriegfrj** [comment]
Auto-registration depends on the `ServiceLoader`. In addition to getting the right system property set, you might also need to:
1. use Spi-Fly to make sure that the bridge the service loader client in the Jupiter engine bundle (BSN "junit-jupiter-engine") is properly instrumented to load `ServiceLoader` implementations from the OSGi service registry;
2. register your extension as a service in your own bundle (declaring it as a `@Component` should do the trick);
3. ensure that the bundle that contains your extension is started before the test suite runs.

I have not personally tested this myself so I might not be of much further help to you in any of the details, but it theory it should work.

**Comment by bjhargrave** [comment]
Not a Bnd problem.

**Comment by kriegfrj** [comment]
This might be more appropriate in the discussion forum https://bnd.discourse.group
