### ISSUE TITLE
ExternalPlugin annotation with Macro produces duplicated Capability

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5423]
If I add `@ExternalPlugin(name = "geckoEMF", objectClass = Generator.class, version = "${Bundle-Version}")` to my Generator Plugin, the Capability is in there twice:

```
Provide-Capability                      bnd.external.plugin;implementation="org.gecko.emf.osgi.codegen.GeckoEmfGenerator";bnd.external.plugin=geckoEMF;objectClass="aQute.bnd.service.generate.Generator";version:Version="${Bundle-Version}"
                                        bnd.external.plugin;implementation="org.gecko.emf.osgi.codegen.GeckoEmfGenerator";bnd.external.plugin=geckoEMF;objectClass="aQute.bnd.service.generate.Generator";version:Version="4.4.0.202211101742-SNAPSHOT"
```
Thw Version with the unresolved Macros naturally causes issues.

**Comment by pkriens** [comment]
We do not process macros in annotations since it depends on the runtime. It would allow any external code from maven central to run a macro. The macros we support in the capability are treated specially
