### ISSUE TITLE
6.4.0 not available on Maven Central

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#5442]
https://repo1.maven.org/maven2/biz/aQute/bnd/bnd-baseline-maven-plugin/ only exposes version 6.3.1. Was anything broken with the publishing?

**Comment by bjhargrave** [comment]
> Was anything broken with the publishing?

No. I am still in the middle of publishing. I guess dependabot has jumped the gun. :-)

**Comment by kwin** [comment]
Maybe next time you can defer publishing the release notes at https://github.com/bndtools/bnd/releases until Maven Central has it.

**Comment by bjhargrave** [comment]
> defer publishing the release notes

Yes. But it unclear that making a github release will trigger dependabot. I would assume dependabot should only make PRs when the dependencies actually exist.

**Comment by bjhargrave** [comment]
It now appears 6.4.0 is available in maven central.
