### ISSUE TITLE
bnd export gradle plugin doesn't include configured bnd launcher

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#5471]
When we export any bndrun, bnd, by default, includes the bnd launcher of the bnd configured in the workspace inside the exported executable JAR. Bnd also proovides the option to set the runpath in the bndrun to include bnd launcher of a specific version.

If we export the bndrun file in Eclipse IDE, the executable JAR includes the specific bnd launcher version configured in the runpath, but if we export the same bndrun using gradle, the executable JAR still does not contain the specific bnd launcher, rather the version of the bnd launcher which is configured in the workspace.

Example:

Configured Bnd Workspace: `6.3.1`

In `dev-tgt-gcm.bndrun`,
```
-runpath: \
	biz.aQute.launcher;version='[6.0.0, 6.0.1)'
-runbundles: \
	biz.aQute.remote.agent;version='[6.3.1,6.3.2)',\
	com.qivicon.gateway.dmt.container.plugin;version=snapshot,\
	com.qivicon.gateway.dmt.simple.provider;version=snapshot,\
	com.qivicon.gateway.dmt.systemproperty.synchronizer;version=snapshot,\
	com.qivicon.gateway.logger.forwarder;version=snapshot,\
	com.qivicon.gateway.slm.agent;version=snapshot,\
	com.qivicon.runtime.osgiagent;version=snapshot,\
	com.qivicon.runtime.systemstate.provider;version=snapshot
```
Now, if we export in IDE, the exported executable JAR contains the `bnd launcher - 6.0.0` as configured in `-runpath`.

But, if we export using Gradle: `./gradlew :com.qivicon.product.luther.application:export.frm-tgt-gcm`, it contains, the `bnd launcher - 6.3.1`

**Comment by bjhargrave** [comment]
There is nothing in the gradle plugin which does anything unique here:

https://github.com/bndtools/bnd/blob/1a25f6da09ad4d3ffe25c45a8da09f45543b8ab2/gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/Export.java#L152

It just uses the `Project.export` method. So, if there is any difference between Bndtools export and Gradle export, the difference is really between Bndtools export and bndlib's Project export method. That is, I don't see that the gradle plugin is responsible for any difference.

**Comment by pkriens** [comment]
I checked this out.

- bnd 6.4.0 in started from Eclipse
- Gradle 7.4 with bnd 6.4.0 plugin
- A bndrun file that puts biz.aQute.launcher;version='[6.0.0,6.1.0]' on -runpath
- Export a minimal executable JAR with the export, correct version
- Manually exported from the GUI, correct version
- Exported with gradle, correct version

I am closing this because it is hard to see how this can not work from the code pov. However, if you can repeat this in a consistent way from a workspace open this bug again and contact me so we can debug it there.
