### ISSUE TITLE
New Bnd OSGi Workspace from template bndtools/workspace branch: origin/6.4 fails.

### ISSUE THREAD

**Issue by zelorun** [bndtools/bnd#5476]
Using a fresh Eclipse IDE 2022‑12, installing Bndtools using the Marketplace is not able to create a new Bnd OSGi Workspace (tested on Windows and Ubuntu).

In the Preview Changes window it shows the error:

"Checkout conflict with files: gradle.properties"

The list of files is empty. Next > button is disabled.

Version:
Bndtools 6.4.0.REL-202211291949-g25e4898 bndtools.main.feature.feature.group Bndtools

**Comment by zelorun** [comment]
@pkriens can you please validate this issue?

My first idea was that this issue is related to the cloned workspace repository, but for what reasons ever it works if using another branch than the offical current 6.4.0.

**Comment by mikerumpf** [comment]
I encountered the same issue.

**Comment by zelorun** [comment]
@pkriens if you cannot reproduce the issue on your system please feel free to contact me for a coop session.

**Comment by pkriens** [comment]
@zelorun can you send me your email address? I am peter.kriens@aQute.biz

**Comment by pkriens** [comment]
I got it on mac as well ...

**Comment by pkriens** [comment]
As an intermediate fix, it seems to work if you use an alternative template. When I moved back to the template selection and then picked the other one it worked.

**Comment by bjhargrave** [comment]
The code uses Eclipse JGit to perform the git operations. It is possible some change in JGit in the latest version of Eclipse has upset something here.

Have you tried adding `setForced(true)` to the checkout command (do not confuse with the deprecated and misnamed `setForce` method)?

```java
				CheckoutCommand checkout = git.checkout()
					.setCreateBranch(true)
					.setName("_tmp")
					.setForced(true);
```

**Comment by pkriens** [comment]
Since I could only run this in another Eclipse I tried to change the boolean fields and see what happened. The fix to not create a branch and get all paths worked fine. We know the directory is empty since we just created it.

Can you take this issue to cherry pick it on the next branch?

**Comment by zelorun** [comment]
@pkriens after checking out this repository (and applying the fix), which command do i have to run to generate the eclipse plug-ins?

**Comment by pkriens** [comment]
you can run it in the Eclipse debugger, that is the easiest way.

The command to create a p2 repository is `./gradlew p2`. I am not sure where the are placed but likely in the dist project.

**Comment by zelorun** [comment]
@bjhargrave how long does it normally take until a new (bugfix) release comes out?

**Comment by pkriens** [comment]
It should work ok for the current snapshot. We do not have a time plan yet but we should have a release in the next few months.
