### ISSUE TITLE
Remove bndtools.pde feature and plugin

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#5481]
With the update of the Eclipse dependency to 4.25, the bndtools.pde feature is now showing deprecation warnings due to changes in the PDE API.

Is this feature still relevant? Do people use it?

The code for this feature has not materially changed since its initial commit https://github.com/bndtools/bnd/commit/550a411442bbe05e03a7b403c3e1980743cd88e0 over 5 years ago.

I would like to consider removing the bndtools.pde feature and plugin for the 7.0.0 release.

**Comment by juergen-albert** [comment]
Yes this is a really helpful part. Some Eclipse Plugins only know about the target platform and this provides the only way right now to sell bundles provided via bnd to them. I can have a look at the deprecation warnings and what we can do about it.

**Comment by bjhargrave** [comment]
> I can have a look at the deprecation warnings and what we can do about it.

Yes, please do make a PR to fix the deprecation warnings.

**Comment by laeubi** [comment]
> Some Eclipse Plugins only know about the target platform and this provides the only way right now to sell bundles provided via bnd to them

That is not  really correct, bundles actually don't care anything about the target-platform,  PDE just resolves bundles from the target state by default, but you probably want to take a look at the `org.eclipse.pde.core.pluginClasspathContributors` that allows to inject any bundle into the projects classpath.

**Comment by juergen-albert** [comment]
I can't be more specific then as soon as I'm able. Sorry.
