### ISSUE TITLE
Automatically download the framework from runfw parameter?

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5504]
I'm playing around a bit with bnd-testing-plugin and has previously used 

`-runfw: org.eclipse.osgi`

and the test is run.

now try use 

`-runfw: org.apache.felix.framework`

now the test fails with:

```
[ERROR] Tests not run because project has errors
[ERROR] Error   : org.apache.felix.framework; Not found in ...
```

I noticed that bnd already downloads some thing automatic to `target/.../cnf/cache/6.4.0/bnd-cache` (e.g. `biz.aQute.launcher`), it would be good if the same could work for the `runfw`, of course bnd can't know **all** frameworks, but if this e.g. works for felix+equinix+ ... maybe others on central ... that would be great if bnd can download them automatically.

**Comment by bjhargrave** [comment]
> cnf/cache/

That is for Bnd artifacts such as launcher. It is the contents of the [embedded repo](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.embedded-repo/bnd/embedded-repo.bnd). So it is fixed set of artifacts established at Bnd's build time.

All other artifacts, in maven, must come from the maven project. Either via dependencies or bundles configuration of the plugin.

**Comment by laeubi** [comment]
Okay I have assumed these are actually downloaded from maven, then this might not work and specify it explicitly is required.
What I can think about is that one adds a "maven repo" at the ned of the list that just contains the fw artifact...

**Comment by laeubi** [comment]
> That is for Bnd artifacts such as launcher. It is the contents of the [embedded repo](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.embedded-repo/bnd/embedded-repo.bnd). So it is fixed set of artifacts established at Bnd's build time.

I wanted to investigate more about this kind of repo, can you give me an hint where in the maven-plugin this is loaded/extracted? I would assume it is somewhere loaded from the plugin artifacts?

**Comment by bjhargrave** [comment]
The `embedded-repo.jar` is a [resource](https://github.com/bndtools/bnd/blob/e7ab7a98a88bf034238747188812fdc26bb1f77b/biz.aQute.bnd.embedded-repo/bnd.bnd#L15-L16) in `biz.aQute.bnd.embedded-repo` artifact.

Each Bnd maven plugin which needs to launch/test has a [maven dependency](https://github.com/bndtools/bnd/blob/e7ab7a98a88bf034238747188812fdc26bb1f77b/maven-plugins/bnd-testing-maven-plugin/pom.xml#L64-L67) on the `biz.aQute.bnd.embedded-repo` artifact.

The Bnd `Workspace` class has a private `FileRepo` subclass which [extracts](`embedded-repo.jar`) the contents of the `embedded-repo.jar` resource and makes it [available](https://github.com/bndtools/bnd/blob/e7ab7a98a88bf034238747188812fdc26bb1f77b/biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java#L780-L783) as a repository in the workspace.

**Comment by laeubi** [comment]
Thanks, so if I understand correctly there can only be even one embedded-repo, but now I see how this data is pulled in!
