### ISSUE TITLE
BndrunContainer.Builder allow adding plugins

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5514]
Currently it is not possible with the `aQute.bnd.maven.lib.resolve.BndrunContainer.Builder` to add additional plugins.
One can workaround this by execute the run, add the plugin and then refresh the workspace, but it seems more usefull to be able to add plugins ad the Builder directly.

This will allow to e.g. specify additional `RepositoryPlugin`s see for example 
- https://github.com/bndtools/bnd/issues/5504

also one then can use that to add additional plugins with maven-model and would make the rather monolithic  embedded-repo artifact obsolete.

**Comment by pkriens** [comment]
No intention to implement. If you want this then we probably won't object to a PR but there are no takers.
