### ISSUE TITLE
if macro behaviour

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5526]
According to https://bnd.bndtools.org/macros/if.html `${if;${foo};${foo};Ouch}` should result in `Ouch` if foo is not set. In reality however it is `${foo}`. Is the Documentation wrong or is this a bug?

**Comment by bjhargrave** [comment]
I think you want `${def;foo;Ouch}` which will give the value of `foo` if set and `Ouch` otherwise. `${if}` will only work when you know that `foo` has a value.

**Comment by juergen-albert** [comment]
This was my solution as well. I guess we should change the documentation if it is wrong or the behavior is different now.

**Comment by bjhargrave** [comment]
When processing the `if` macro, Bnd must first expand the arguments. If `foo` has a value `foovalue`, then `${foo}` evaluates to `foovalue`. So then the `if` macro would then be `${if;foovalue;foovalue;Ouch}` and the `if` macro would evaluate `foovalue` as truthy and then return the second argument `foovalue`. 

If `foo` is not assigned a value, then `${foo}` evaluates to itself `${foo}`. So then the `if` macro would then be `${if;${foo};${foo};Ouch}` and the literal `${foo}` is evaluated as truthy and the second argument `${foo}` would be returned.

So there is no issue with the `if` macro or the doc. It is just that you did not see how macros are evaluated. Arguments to the macro are evaluated before the macro is evaluated. If `foo` is not assigned a value, `${foo}` is not evaluated to the empty string as this would wallpaper over potential bugs of unassigned macros. When a macro may not have been assigned, you need to use the `${def}` macro.

**Comment by juergen-albert** [comment]
Well, I do understand how it works and I understood why it would not in the first place. The following is literally how the example in the above mentioned link looks like:
```
# Display ${foo} if set, otherwise 'Ouch'. See also ${def} 
whatisfoo = ${if;${foo};${foo};Ouch}
```

**Comment by bjhargrave** [comment]
Then that example is wrong.

**Comment by pkriens** [comment]
Fixed in doc
