### ISSUE TITLE
Enhance the handling of template defaults in TemplateParamsWizardPage

### ISSUE THREAD

**Issue by scottslewis** [bndtools/bnd#5537]
Currently the NewBndProjectWizard TemplateParamsWizardPage checks only for empty fields to determine if the page is complete.

It would be convenient to allow a default of "<foo>" or "<bar>" having the meaning that the default value had to be replaced in the TemplateParam dialog before it was considered complete (and the Finish button was enabled).

I will produce a pull request.

**Comment by scottslewis** [comment]
Pull request #5538 submitted

**Comment by scottslewis** [comment]
See new pull request #5553

**Comment by pkriens** [comment]
I guess this can also be closed?
