### ISSUE TITLE
Runner requirements are not take into account when resolving

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5539]
I use the bnd-maven-plugin with `resolve=true` but the run fails with:

```
! could not resolve the bundles: [biz.aQute.tester-6.3.1.202206071316 org.osgi.framework.BundleException: Could not resolve module: biz.aQute.tester [3]
  Unresolved requirement: Import-Package: junit.framework; version="[3.8.0,5.0.0)"
```

So i now need to adjust my config to require additional items, it would be good if BND inferred this automatically when resolving.

**Comment by pkriens** [comment]
it would help if you could make a test case for the build that shows this.

**Comment by laeubi** [comment]
You can use this as an example:
- https://github.com/microsoft/mssql-jdbc/pull/2066/files

it runs fine, but if you remove 

```
- bnd.identity;id=junit-jupiter-engine, \
- bnd.identity;id=junit-platform-launcher
```

from the bndrun file then it fails with errors.

**Comment by laeubi** [comment]
I think if one wants to reproduce this in plain vanilla it should work like this:

1. Create a bundle with a testcase and build it
2. Now create a new project that reference this build bundle (but itself has no test code) and try to run it from there with minimal runbundles (== only the one build in step 1)

**Comment by pkriens** [comment]
will you be providing a test case PR?
