### ISSUE TITLE
Unclear error message when processing DS 1.2 annotations

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5548]
I currently try to update a previously in xml defined component to annotation, that annotation claims to currently DS 1.2.

But while processing I get an error, so likely it is already using some 1.3 features, nerveless I probably just can upgrade it to 1.3, **the error itself** is unclear and confusing:

> [org.eclipse.equinox.internal.event.EventComponent] component org.eclipse.equinox.event version 1.3.0 exceeds -dsannotations-options version;maximum version 1.2.0 because base

I can decode it up to the point that BND thinks 1.3 is the minimum version, but:

- "because base" seem to give a reason but I'm not sure I understand. it should be rephrased to be more clear or is there some word missing?
- It would be good if BND could evaluate the version constrain earlier and give a more specific error, e.g. *what* 1.3 feature is used here so that 1.2 do not apply.

The component itself can be found here:
https://github.com/eclipse-equinox/equinox/blob/d114f11bd0cd0479dd9a6ebbfb1a6d7976c0683d/bundles/org.eclipse.equinox.event/src/org/eclipse/equinox/internal/event/EventComponent.java

This is the XML generated by BND:
```
<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.3.0" name="org.eclipse.equinox.event" activate="activate" deactivate="deactivate">
  <service>
    <provide interface="org.osgi.service.event.EventAdmin"/>
  </service>
  <implementation class="org.eclipse.equinox.internal.event.EventComponent"/>
</scr:component>
```

And this is the XML how it currently looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" activate="activate" deactivate="deactivate" immediate="false" name="org.eclipse.equinox.event">
   <implementation class="org.eclipse.equinox.internal.event.EventComponent"/>
   <service>
      <provide interface="org.osgi.service.event.EventAdmin"/>
   </service>
</scr:component>
```

Due to 
- https://github.com/osgi/osgi/issues/570

I'm currently using https://mvnrepository.com/artifact/org.osgi/osgi.cmpn/5.0.0 for the annotations itself I use 
- https://mvnrepository.com/artifact/org.osgi/osgi.cmpn/5.0.0

what exports `org.osgi.service.component.annotations;version="1.2"`

**Comment by laeubi** [comment]
PDE generates the following XML (even if I allow 1.3):
```
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" activate="activate" deactivate="deactivate" name="org.eclipse.equinox.event">
   <service>
      <provide interface="org.osgi.service.event.EventAdmin"/>
   </service>
   <implementation class="org.eclipse.equinox.internal.event.EventComponent"/>
</scr:component>
```

It switches to 1.3 if I e.g. use a reference in a field.

**Comment by pkriens** [comment]
Is it possible that you have -dsannotation-options set in your code?

We changed in bnd to have 1.3 as the minimum version. It seems like you want to force the version to 1.2?

	static class VersionSettings {
		Version	minVersion	= V1_3;
		Version	maxVersion	= VMAX;
	}

**Comment by laeubi** [comment]
> Is it possible that you have -dsannotation-options set in your code?

Yes exactly!

>  It seems like you want to force the version to 1.2?

Correct.

**Comment by pkriens** [comment]
That is impossible. I think about 4 years ago we had a horrible versioning problem and the only real solution seems to be to only allow >= 1.3 ...

**Comment by laeubi** [comment]
Well I think its not impossible, but if you say its currently not supported thats fine, maybe it could be documented somewhere (or I missed that when using that option).

Still I think the message is confusing here, maybe better something like this then:

1.2.0 is not supported, the lowest supported version is 1.3

**Comment by pkriens** [comment]
That makes sense.
