### ISSUE TITLE
bnd-maven-plugin: Export-Package still contains default package version derived from pom version

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#5555]
Despite what is said in https://bnd.bndtools.org/chapters/920-faq.html?#exportversions the MANIFEST.MF being generated from `bnd:6.4.0:bnd-process` still contains `Export-Package` with package versions **derived from bundle-version/pom version**, although no explicit version has been specified in either the `bnd.bnd` nor in any `package-info.java`/`packageinfo` file.

Example project: https://github.com/eclipse/sisu.inject/tree/master/org.eclipse.sisu.inject

**Comment by pkriens** [comment]
Was this a regression? I.e. did this not happen prior 6.4.0?

**Comment by kwin** [comment]
No, happens even with 5.3.0 but still is contradicting documentation.

**Comment by pkriens** [comment]
You need to add -nodefaultversion=true

**Comment by kwin** [comment]
Thanks for the quick documentation fix.
