### ISSUE TITLE
aQute.bnd.osgi.PluginsContainer can't load plugins from other bundles

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5571]
I'm currently trying loading a (plain) Bnd-Workspace layout projects (this one https://github.com/aQute-os/com.example ) in an OSGi context with the function 

`Project project = Workspace.getProject(baseDir);`

this currently fails with `ClassNotFoundException`, because `PluginsContainer` cant load the (named) plugin `aQute.bnd.repository.maven.provider.MavenBndRepository` what is part of another bundle and as there is no import the loading is refused.

I see the following options:

1. `biz.aQute.bndlib` could get a `DynamicImport-Package: *` (or at least `aQute.bnd.*` but this will block custom plugin implementations)
2. The `PluginsContainer` could be enhanced in a way that it do something similar like `DynamicImport-Package` by iterating over all bundles and try to load the requested plugin, for this purpose it might narrow down things a bit and e.g. only ask bundles that have the BSN as a prefix of the plugin class (in this case all bundles first that have a bsn of `aQute.bnd.repository.maven.provider`, then `aQute.bnd.repository.maven`, then `aQute.bnd.repository` ... and so on) what might be an acceptable convention even for third party plugins and would not require to open the bundle to any exported classes like option (1)

**Comment by pkriens** [comment]
You better use the library for the bnd command line. It contains the necessary dependencies and can work standalone. It is a a bit of a hack so you could add the different standard dependencies to your class path.

Dynamic-ImportPackage is fundamentally wrong. You pay a lot to get OSGi and then with one fell swoop to descent back in JAR hell ...  It is only useful as a temporary lifeline in a fatally screwed up project :-)

**Comment by laeubi** [comment]
Well currently bndlib is "screwed up", recommending to use a commandline tool does not really makes sense here as I want to use it in OSGi (seems obvious for a tool made for OSGi...) and I also suggested an approach without `DynamicImport-Package` so as long as it works I won't mind from a users point-of-work what tchnique you are using in the back.

**Comment by pkriens** [comment]
bndlib is not screwed up, your setup/dependencies are not correct. I am still not clear how you actually want to use it? What is your setup and what do you want to achieve?

**Comment by laeubi** [comment]
Just load Bndlib in an OSgiFramework, then have a bundle using that and calling:

```
File file = new File("<your example path>/bnd.workspace.example/com.example.eval.api")
Project p = Workspace.getProject(file);
p.getWorkspace().getErrors().forEach(System.out::println);
```
(example is from https://github.com/aQute-os/com.example)
and you will see it can't load the mavenrepository plugin...

**Comment by pkriens** [comment]
In Central there is an Auxiilary class that scans the bundles for `bnd-plugins` packages and imports them accordingly using the WeaveHook ....

You could use that mechanism

**Comment by pkriens** [comment]
i am closing this since this does not require new code?

**Comment by laeubi** [comment]
> In Central there is an Auxiilary class that scans the bundles for `bnd-plugins` packages and imports them accordingly using the WeaveHook ....
> 
> You could use that mechanism

Would it be possible to be _a little bit more specific_? According to their stats, there 3.2 Million of artifacts on central... so a little pointer where this Auxiilary class is located (e.g. artifact name) or a link to the documentation where it is described would certainly help....

**Comment by kriegfrj** [comment]
He means the Bndtools utility class called Central. It is in the bndtools project (as is the Auxiliary class). Hopefully that narrows your search a little. :)

**Comment by laeubi** [comment]
So users of bndlib need to includ bndtools-core (2.2 MB!) that even pulls in more dependencies e.g. templating (another 2.5 MB) and then requires to call `bndtools.central.Central.getInstance()` to trigger the loading, thats' way much more I would call a "Utility class"....

So basically this then do something similar as proposed in (2) and should be part of the lib bundle itself.

**Comment by pkriens** [comment]
You have a very special use case that is not part of the things we support out of the box: maven, ant, gradle, eclipse, intellij, etc. That is fine but if you explore uncharted territory and it behooves to be aware of the pittfals.

Since Eclipse is the only place where we have an OSGi framework, I added Auxiliary & the manifest attribute `bnd-plugin` on the export to handle the more complex class loading situation in Eclipse/OSGi. We have many other eclipse specific solutions.

However, I am not sure why you want an OSGi framework in the first place? If you place bndlib & repository on a class loader things should work fine out of the box? This how it is done in Gradle, Ant, bnd, and Intellij. I love OSGi but in this case I am not sure I understand the value?

If you really want to run it in an OSGi framework I suggest to port the Auxliary code to a new project and then use it from the bndtools site & as an extra bundle in your setup. But unless you have a compelling need for OSGi (unlike bnd code itself) then I would definitely skip OSGi.

And as I said earlier, for the flat class path depending on the bnd jar is easier since it is guaranteed to contain all the dependencies in one convenient JAR.

**Comment by laeubi** [comment]
I run this code in an Eclipse-Application and I don't want to pull in BndTools, easy as that... if every user is adding its own workaround one will just end-up with a whole mess of duplicate or even competing approaches, a the OSGi specification recommends to refreh packages of consumers if imports are changed or hooks arive "too late" so this can produce a loot of rumor.

The `bnd-plugin` attribute seems a good idea, only bad thing is that the `PluginsContainer` do not make use of it, e.g. instead of adding dynamic imports this can simply be used to select bundle to search for and load from them if linear classcanning did not suceed, no need for a weaving hook (with "bad" dynamic imports ,neither directly or indirectly) and would work out-of-thebox .
