### ISSUE TITLE
Package imports for java.* & compatibility

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5585]
See here:

I believe this to be a bug in bnd's heuristics. Imports for `java.*` packages were added (in release 7 I think) to help support modular Java runtimes and not necessary in previous versions. Bnd uses the Java version as a proxy for framework version if no framework package is imported. Java 9 existed long enough ago that it *might* be used with an old framework, hence the heuristic to be "old".

In this case the heuristic is wrong as Multi-Release bundles were added in Core R7, which means that `java.*` packages *should* be imported by bundles using them.

_Originally posted by @timothyjward in https://github.com/osgi/osgi/issues/573#issuecomment-1462241037_

If a multi-release supplemental manifest is computed can always assume that `R7` is used and therefore `java.*` packages can be imported.

**Comment by pkriens** [comment]
We check for >= Java 11. I fail to understand the reasoning since the code explicitly checks for the framework package version. If the import range is pre OSGi 7, we do not import java. 

Any idea why we would check for the EE version? We can run Java 7 code with OSGi 6  on a Java 17 VM? The code level is  not sufficient to determine if we run on JPMS as far as I can see.

I can remove the EE check completely. The framework version check seems to be full proof as far as I can see.

**Comment by laeubi** [comment]
But what if I do not import any framework package? I think the idea is that with Java 11 everything is modularized so package imports for `java.*` are important but thats only a guess, maybe just enable these imports always for Java9+ is simple enought... if I want to build a bundle for an old framework it can be disabled in the bnd-file...

**Comment by timothyjward** [comment]
> Any idea why we would check for the EE version? We can run Java 7 code with OSGi 6 on a Java 17 VM? The code level is not sufficient to determine if we run on JPMS as far as I can see.

The rationale was that “Java 11 is *too new* for any R6 framework to know what it is, so if I want a framework that can run my bundles it will have to be R7.

**Comment by timothyjward** [comment]
I’m not wild about losing the EE check - what happens if there is no framework impl or API on the classpath? I don’t want to have bundles missing these imports when they enable so much value.

**Comment by laeubi** [comment]
As there is an [option to switch this off](https://bnd.bndtools.org/instructions/noimportjava.html) would it not be an option to simply generate such java imports always?
If one is targeting older Frameworks one can simply use that option to prevent that, R7 is out ~ 5 years now and I think anyone upgrading to never BND version has already upgraded to newer frameworks as well.

**Comment by timothyjward** [comment]
> @timothyjward the default without framework is to have java.* imports so I am not sure I understand. The only way not to not get them is to put an old framework on the classpath or -noimports=true. In all other cases they are there?

I'm glad to hear that. It wasn't 100% clear to me from the code and there were no tests to verify, so all I saw was the removal of an "enable on Java 11+". I've added a couple of basic tests in #5590 which will ensure that this desirable behaviour isn't accidentally broken in future.

**Comment by pkriens** [comment]
These multi rules are always tricky to read so I did my utmost best to clarify them in the code. The previous code was kind of hard to read with a `while` in there that was only there for the `break`.

	boolean frameworkSupportsJavaImports = getExportVersion(getPackageRef("org.osgi.framework"))
		.map(actual -> actual.compareTo(frameworkR7) >= 0)
		.orElse(true);
	boolean elideImports = is(NOIMPORTJAVA) || !frameworkSupportsJavaImports;

	if (elideImports) {
		imports.keySet()
			.removeIf(PackageRef::isJava);
	}

I am not sure this could be more clear in the code?
