### ISSUE TITLE
Add tutorial steps for using Gradle's kotlin dsl 

### ISSUE THREAD

**Issue by ben-manes** [bndtools/bnd#5642]
I struggled quite a bit when migrating a groovy dsl build to use precompiled kotlin script plugins. Using `tasks.withType<Bundle>` did not seem to be applied to the `jar` task, and kotlin wouldn't let me enrich if `withType<Jar>` or `named<Bundle>("jar")`. I was able to figure it out using junit5 and okhttp as examples, who muck with the extension directly. Maybe there is a better way, hope this helps as some readme or samples would be great!

```kotlin
// build.gradle.kts
tasks.withType<Jar>().configureEach {
  applyOsgi(this, mapOf(
    "Bundle-SymbolicName" to "com.github.ben-manes.caffeine.guava",
    "Import-Package" to listOf(
      "com.google.common.cache",
      "com.google.common.util.concurrent",
      "com.github.benmanes.caffeine.cache",
      "com.github.benmanes.caffeine.cache.stats").joinToString(","),
    "Export-Package" to "com.github.benmanes.caffeine.guava",
    "Automatic-Module-Name" to "com.github.benmanes.caffeine.guava"))
}

// ProjectExtension.kt
fun Project.applyOsgi(task: Jar, instructions: Map<String, Any>) {
  plugins.withId("java-library") {
    val extension = the<JavaPluginExtension>()
    val languageVersion = extension.toolchain.languageVersion.get()
    val bundleExtension = task.extensions.findByType(BundleTaskExtension::class.java)
      ?: task.extensions.create(BundleTaskExtension.NAME, BundleTaskExtension::class.java, task)
    bundleExtension.apply {
      bnd(instructions + mapOf(
        "Bundle-License" to "https://www.apache.org/licenses/LICENSE-2.0",
        "Build-Jdk-Spec" to languageVersion,
        "Implementation-Title" to description,
        "Bundle-Description" to description,
        "Implementation-Version" to version,
        "-reproducible" to "true"))
      task.doLast(buildAction())
      properties.empty()
    }
  }
}

```

**Comment by ben-manes** [comment]
I attached a debugger to the task and saw that the `buildAction` was being executed twice. It reads and overwrites the source jar to enrich it with the osgi metadata, so this seems to cause it to lose the computed properties. The plugin also adds a `task.doLast(buildAction())`, so my addition per the references was causing duplicate work. That lost the computed metadata, perhaps something to do with baseline diffs, and thus the warnings/errors.

The root cause appears to be that the extension is not being created automatically by the kotlin dsl so my usage forces that, which then triggers all of the desired behaviors. The other explicit overrides were then not necessary and caused weirdness, which removing seems to resolve. Therefore this incantation is what is needed, though maybe I am doing something unnecessary but no longer destructive.

```kts
/** Adds the osgi manifest attributes to the jar task. */
fun Project.applyOsgi(task: Jar, instructions: Map<String, Any>) {
  plugins.withId("java-library") {
    val extension = the<JavaPluginExtension>()
    if (task.extensions.findByType(BundleTaskExtension::class.java) == null) {
      task.extensions.create(BundleTaskExtension.NAME, BundleTaskExtension::class.java, task)
    }
    val defaults = mapOf(
      "Bundle-License" to "https://www.apache.org/licenses/LICENSE-2.0",
      "Build-Jdk-Spec" to extension.toolchain.languageVersion.get(),
      "Implementation-Title" to description,
      "Bundle-Description" to description,
      "Implementation-Version" to version,
      "-noextraheaders" to true,
      "-reproducible" to true,
      "-snapshot" to "SNAPSHOT")
    task.extensions.configure<BundleTaskExtension>(BundleTaskExtension.NAME) {
      properties.set(provider {
        mapOf("project.description" to project.description)
      })
      bnd(defaults + instructions)
    }
  }
}
```

**Comment by pkriens** [comment]
BJ used to do all the gradle work. Would you be willing to take a stab at providing a PR for this?

**Comment by ben-manes** [comment]
No thank you. This was frustratingly to work through and osgi is foreign to me, so I’d do not want to revisit until necessary.

**Comment by bjhargrave** [comment]
> @bjhargrave any idea if we can use this, and how?

I am not sure what the ask is here. I am unable to do any significant work here. I can see that a Kotlin example is necessary and that the example's creation may expose some UX issues for the Bnd plugin in Kotlin.

**Comment by pkriens** [comment]
Of course I understand you don't have time to do any real work on this.

However, the question is basically is a there a quick way to extract from the work done here? I am really out of my league but if we have some seed point in the documentation people might add to it.

**Comment by bjhargrave** [comment]
Actually, you can use the existing `bundle` [DSL element](https://github.com/bndtools/bnd/tree/master/gradle-plugins/biz.aQute.bnd.gradle/src/dsl/kotlin/org/gradle/kotlin/dsl) to configure the task for Bnd. Just like you would in Groovy. See <https://github.com/bndtools/bnd/blob/master/gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin3/build.gradle.kts> for a test case that shows this.

So probably all that may be needed it to mention, in the [Bnd gradle plugin readme](https://github.com/bndtools/bnd/blob/master/gradle-plugins/README.md), is that a `bundle` DSL element is available for Kotlin scripts just like it is for Groovy scripts.

**Comment by ben-manes** [comment]
I think this is where some of the differences of Kotlin are less obvious. When using `tasks.withType<Jar>().configureEach { ... }` style, then the bundle extension is not applied. The `tasks.jar { ... }` style does have it, though. I believe the styles differ in that `configureEach` allows for lazy configurations to improve build performance, so it is more hygenic to use that by default. Hence one runs into confusion, which is why junit5 and okhttp likewise have complex workarounds because it was not obvious how to access via the DSL.

**Comment by ben-manes** [comment]
Oh, I guess it is only eager in the Groovy DSL. I am still not very comfortable with the Kotlin one yet.

I tried [switching](https://github.com/ben-manes/caffeine/commit/fdf756d81b2b3d435bea6898759b791d96f8510d) to the DSL style you recommended, verified that the `MANIFEST.MF` looks correct, and my PaxExam tests pass. Oddly it then gives me an unrelated build error, though I did not modify that section of the logic. I'm unsure how that would have impacted the lifecycle to trigger this, so more debugging is needed...
> The value for task ':guava:test' property 'testFrameworkProperty' is final and cannot be changed any further.

**Comment by bjhargrave** [comment]
You need to avoid referencing the project object at task execution time. See https://github.com/junit-team/junit5/commit/9c287897a89bb43ca8966d4db700e94649dd0f6a for an example of the changes needed.

**Comment by ben-manes** [comment]
Oh that's right. I cleared it out for now, `properties.empty()`, and will apply your suggestion afterwards. A compile passes and we'll see if the tests fail similarly on the [github action](https://github.com/ben-manes/caffeine/actions/runs/5049063177).

**Comment by ben-manes** [comment]
Wonderful! Now it works [beautifully](https://github.com/ben-manes/caffeine/commit/e804ab73593a95a5465661a71914031a4eb195fa) using the bundle dsl, thank you :-)

**Comment by pkriens** [comment]
I guess no more actions here?
