### ISSUE TITLE
Question: pretty printing import/export-package

### ISSUE THREAD

**Issue by tivervac** [bndtools/bnd#5656]
I often come across BND generated OSGi manifest files, and once in a while I need to manually go through these, search for version, copy paste some things and what not.

This is however always complicated by the fact that BND generates Import/Export-Package with a character limit. e.g. see the excerpt of `org.eclipse.lsp4j_0.19.0.v20221118-0359` below.

I wonder why it doesn't just generate a line per package instead, this would only minorly increase the file size but would make these so much easier to read. If this is just an oversight, or pretty printing is not the default but instead an option, then this can question can be considered as a feature request ;)

```
Export-Package: org.eclipse.lsp4j;uses:="com.google.gson.annotations,org
 .eclipse.lsp4j.adapters,org.eclipse.lsp4j.jsonrpc.messages,org.eclipse.
 lsp4j.jsonrpc.validation,org.eclipse.xtext.xbase.lib";version="0.19.0",
 org.eclipse.lsp4j.adapters;uses:="com.google.gson,com.google.gson.refle
 ct,com.google.gson.stream,org.eclipse.lsp4j,org.eclipse.lsp4j.jsonrpc.m
 essages";version="0.19.0",org.eclipse.lsp4j.launch;uses:="org.eclipse.l
 sp4j.jsonrpc,org.eclipse.lsp4j.services";version="0.19.0",org.eclipse.l
 sp4j.services;uses:="org.eclipse.lsp4j,org.eclipse.lsp4j.adapters,org.e
 clipse.lsp4j.jsonrpc.json,org.eclipse.lsp4j.jsonrpc.messages,org.eclips
 e.lsp4j.jsonrpc.services";version="0.19.0",org.eclipse.lsp4j.util;uses:
 ="org.eclipse.lsp4j";version="0.19.0"
```

**Comment by tivervac** [comment]
Looking at it a bit more closely, a first reason is likely the use of `uses`. I'm usually mostly focussed on `import-package` where I don't see this. Still, I think the following looks better than what is currently generated

```
Export-Package: org.eclipse.lsp4j;uses:="com.google.gson.annotations,org.eclipse.lsp4j.adapters,org.eclipse.lsp4j.jsonrpc.messages,org.eclipse.lsp4j.jsonrpc.validation,org.eclipse.xtext.xbase.lib";version="0.19.0",
 org.eclipse.lsp4j.adapters;uses:="com.google.gson,com.google.gson.reflect,com.google.gson.stream,org.eclipse.lsp4j,org.eclipse.lsp4j.jsonrpc.messages";version="0.19.0",
 org.eclipse.lsp4j.launch;uses:="org.eclipse.lsp4j.jsonrpc,org.eclipse.lsp4j.services";version="0.19.0",
 org.eclipse.lsp4j.services;uses:="org.eclipse.lsp4j,org.eclipse.lsp4j.adapters,org.eclipse.lsp4j.jsonrpc.json,org.eclipse.lsp4j.jsonrpc.messages,org.eclipse.lsp4j.jsonrpc.services";version="0.19.0",
 org.eclipse.lsp4j.util;uses:="org.eclipse.lsp4j";version="0.19.0"
```

**Comment by juergen-albert** [comment]
Even though bnd is creating the content for the Manifest, it is not the provider of the Code that writes it. For this, we use the `java.util.jar.Manifest` class, which is responsible for the final deserialization. Furthermore is the line length specified to be 72 bytes (no clue why) https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#Manifest_Specification.

So, Manifests must look like this and are written in a similar fashion by e.g. maven as well.

If you use bndtools I'd suggest using the jar editor (does not work on classpath entry, but any jar file). It has a tab which shows you a pretty printed Version.

**Comment by tivervac** [comment]
I was not aware of those limitations, this is very useful information, thanks!

**Comment by pkriens** [comment]
@juergen we actually do write our own manifest :-) See `aQute.lib.manifest`. This is ensuring we do not have platform dependent coding of UTF-8 and sorting entries to make things repeatable.

But you're right the formatting is specified by the JAR specification. The 72 character limit was so readers could allocate a limited buffer. A long, long time ago 640K was a lot of memory :-) How times have changed ...
