### ISSUE TITLE
Baseline maven plugin fails on absent jar file in repository with failOnMissing=false

### ISSUE THREAD

**Issue by andrusha19** [bndtools/bnd#5667]
I use bnd-baseline-maven-plugin
1) If I don't set "base" in configuration and there is no release of that module (in multi-module repo), and parameter "failOnMissing"=false - in that case I got warning, but build passes.
2) If I set "base" in configuration (groupId, artifactId, version (this version is common for all modules)) and there is no release of that module (in multi-module repo), and parameter "failOnMissing"=false - in that case I error "Failure to find ...."

My thought was that if I set  "failOnMissing"=false - build should pass either version was not set in config or there is no jar in repo.
This logic is checked here:
https://github.com/bndtools/bnd/blob/master/maven-plugins/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java#L129

**Comment by pkriens** [comment]
Ping?

**Comment by andrusha19** [comment]
Sorry, a bit tied on the job. Will look later

**Comment by pkriens** [comment]
Any chance? We want to close this to move on to the release. You can always send a PR later if you have time?

**Comment by pkriens** [comment]
Should be fixed in #5768
