### ISSUE TITLE
Eclipse endless build loop in combination with class-file post-processing Maven plugin

### ISSUE THREAD

**Issue by reckart** [bndtools/bnd#5668]
I have a workspace with a large number of projects (> 100) in Eclipse. These are Maven projects that use the bnd-maven-plugin to turn my JAR artifacts into OSGI bundles.

The `bnd-jar` goal does [not support including/excluding files](https://bnd.discourse.group/t/how-to-exclude-files-packages-from-the-jar/300/8) from the JAR. Hence, I was advised to try not using the `bnd-jar` goal, but rather to only use the `process-classes` goal to generate the manifest. Not using the `bnd-jar` reinstates the default `maven-jar-plugin` execution. So I could configure my includes/excludes there. So far so good.

However, I noticed that after removing the `bnd-jar` execution to reinstate the `maven-jar-plugin` execution, the Eclipse incremental build would get stuck in an endless build loop at a random Maven/OSGI/bnd project, endlessly logging the execution of the `jar:jar` goal and then re-scheduling another build of the same module as soon as the JAR had been built. I could abort the incremental build from the progress view, but unless I spammed cancel on the rapidly respawning builds, it would get hung again in the same or in another random Maven/OSGI/bnd project. Turning off auto-build in Eclipse would temporarily resolve the issue, but turning it back on, the IDE would immediately re-enter the endless build loop. Trying to refresh, update, rebuild projects before turning on auto-build again had no effect. 

I did investigate the situation from a couple of angles and looked at excluding other plugins as possible sources for the loop. That allowed me to improve my build in various ways, but eventually did not resolve the problem.

Switching back to using the `bnd-jar` execution resolved the problem. 

As far as I could tell (don't ask me exactly how - I believe I had a peek at the stack trace in VisualVM), it seems that the `jar:jar` execution that seems to be scheduled when `bnd-jar` is not used is triggered by the `BND Decorator` in Eclipse.

**Environment**
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2023-03 (4.27.0)
Build id: 20230309-1520

<img width="1150" alt="Screenshot 2023-05-22 at 08 23 43" src="https://github.com/bndtools/bnd/assets/1410238/66882b72-1eeb-4b5d-8cc4-ad3de5349396">

**Comment by reckart** [comment]
Sounds like it might be, but #4789 has been fixed a long time ago. I am using BND 6.4.0 and also the BND Eclipse Plugins 6.4.0 which should no longer be affected by that bug.

**Comment by kriegfrj** [comment]
Sorry, yes I know - I was linking to the other issue in case this one might be caused by something similar, in the hopes that @juergen-albert (who fixed the other issue) might have some insights into this one. I know he's had his head deep in that code before and our other resident m2e expert is not as available as he used to be.

**Comment by reckart** [comment]
Anyway, the pointer was helpful for further investigation. I'm trying to rebuild the BND plugins with additional logging information in the `BndConfigurator` to see if I can glean some additional information. In particular since this morning I am also experiencing the loop with the `bnd-jar` execution. 

I have the impression the issue might be caused by another plugin I am using that post-processes class files. I have been using that other plugin for ages now and never experienced a problem... but who knows...

**Comment by reckart** [comment]
Ok, so more input now. 

I added some log output to `bndtools.m2e.BndConfigurator.needsBuilding(IResourceDelta, IMavenProjectFacade)`. Now, I can see that the BND detects the class file that is post-processed by the other plugin as changed and then re-schedules a build.

What is not clear to me is why the class file is detected as changed.

The class-file post-processing plugin is running in the `process-classes` phase of the Maven lifecycle. In theory, there could be a ordering conflict with the `bnd:bnd-process` goal running in the same phase  in the sense that the generated manifest might not have seen the classes updated by the other plugin. However, in my case, this would not be a problem as the changes to the class files would have any consequences for the generation of the manifest file.

The `bnd:jar` goal is only run during the packaging phase.

I would assume that the delta detected by the Bnd Decorator should be between the previous run and the current run and not between two phases in the same incremental build run...

**Comment by pkriens** [comment]
thanks for digging this deep.
