### ISSUE TITLE
Support merged and decorated instructions for "standalone"

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#5673]
Sometimes when merging `bndrun` files from multiple sources via `include` it is useful to rely on merged and/or decorated instructions. For `standalone` (https://bnd.bndtools.org/instructions/standalone.html) this doesn't seem to be supported e.g. something like this does not work in a `bndrun`

```
-standalone: target/myindexa.xml
-standalone.extra: target/myindexb.xml
```

The second instruction is simply ignored.

**Comment by pkriens** [comment]
can you make a PR?
