### ISSUE TITLE
upload/release of extra artifacts

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5678]
It would be great if we could use the release process as used by e.b. gradle to upload more then only jars. 

My idea would be to have the following in a projects bnd file:

```
-release-extra: \
  stuff/some.json,\ // groupid, version are taken from the project. artifactId can be the filename and the packaging would be the file extension
  morestuff/test.txt;artifactId=myfancyName;groupId=myOtherGroup;classifier=youNameIt;version=1.2.3 //all necessary attributes can be overwritten
```

Not sure if the file only version is sufficient, to derive useful defaults for the full GAV. 

This should work at least for maven, but might also be nice for OBRs, even though they seem to become obsolete.

The usecase behind this, are e.g. BOMs that are usually only pom.xml files or the new feature jsons.

**Comment by juergen-albert** [comment]
@stbischof @timothyjward This might be of interesst for you as well.

**Comment by pkriens** [comment]
Could you add a concrete use case? As you really need it?

**Comment by pkriens** [comment]
I think we can add this pretty straight forward to the MavenBndRepository. It already gets parameter from the context, which is usually the Project, with the [-maven-release](https://bnd.bndtools.org/instructions/maven-release.html) instruction.

I suggest we add an `extra`option to the `options`.

     extra ::= extra-spec ( ',' extra-spec) *
     extra-spec ::= `extra` (';path=' PATH)? ( ';class=' class )? 

So if you specify (give g=group id, v = version, and a = artifact id):

     -maven-release \
         extra; path=some/stuff.json; class=feature

It will upload relative to the project's directory the `some/stuff.json` file and copy it to `g/a/v/a-v-feature.json`

Is this ok?
