### ISSUE TITLE
Add option to place module-info.class into META-INF/versions/X

### ISSUE THREAD

**Issue by michael-o** [bndtools/bnd#5687]
This one comes from:
* https://github.com/apache/maven-shared-jar/pull/21
* https://bz.apache.org/bugzilla/show_bug.cgi?id=66631

Bnd's Ant task creates the `module-info.class` into the JAR's root where class analyzers will consider the entire JAR as Java 9 while it is Java 8, see `tomcat-jni-9.0.75.jar` or other Tomcat 9 JARs.

Ideally either me or Bnd will automatically decude to place to `META-INF/versions/9` in this case, then it needs to say `Multi-Release: true` since the class file is not in the root anymore. This can also be coupled with `-release 8` or similar to make it easier.

At least https://bnd.bndtools.org/chapters/330-jpms.html does not tell how to control this.

**Comment by laeubi** [comment]
I think there are two things:

1. Historically adding `module-info.class` in the root does not harm as older JDKs wont read the file so there is no issue and one *might* argue that an analyzer should probably just ignore the file
2. Technically always add it to `META-INF/versions/9` and set `Multi-Release` will of course work, but it seems the JDK people has decided to explicitly have a user to enable `Multi-Release` so there *might* be some surprise if it is simply enabled by default

So I think BND do not behaves wrong per-se, if `Multi-Release` is already enabled I would expect it to be placed **always** in `META-INF/versions/9` if the baseversion is 8, so I think for the mentioned issue there are two options:

1. **disable** JPMS as it makes no sense if MR is not used and the jar is java 8 only
2. **enable** `Multi-Release: true` so BND already has an option to enable such behavior?

**Comment by michael-o** [comment]
FTR: I did add `Mutli-Release: true` to Tomcat 9's Bnd options, of course no avail.

**Comment by pkriens** [comment]
If Multi-Release is set && base release < 9 : place module-info in the versioned part , otherwise in the root?

**Comment by michael-o** [comment]
> If Multi-Release is set && base release < 9 : place module-info in the versioned part , otherwise in the root?

What if MR is set, base is 11, but also contains code for 17? Will you create two `module-info.class` files?

**Comment by pkriens** [comment]
We do generate different module-info.class files for each release when they differ. The 1.8 case for the base is really the only special one I think.

The `-jpms-module-info` instruction is a bit of an orphan. I just read the help text for the first time and it comes over as a cool idea but a bit convoluted. (Who cares about synthetic modules?) I wonder how interesting this might be for non-OSGi users? Are they willing to use OSGi & bnd annotations? 

If there is some high end open source project adopting this I can do some extra work to make it a bit more appealing and simple for newcomers.

**Comment by pkriens** [comment]
I am closing this since I do not have time and I don't think anyone else wants to pick it up?

I marked it as abeyance to indicate it is open for volunteers

**Comment by michael-o** [comment]
> I am closing this since I do not have time and I don't think anyone else wants to pick it up?
> 
> I marked it as abeyance to indicate it is open for volunteers

I don't understand this. You have closed as completed, but nothing has been completed. If you are looking for volunteers it should stay open at least for some while.

**Comment by pkriens** [comment]
https://github.com/bndtools/bnd#issues

**Comment by michael-o** [comment]
> https://github.com/bndtools/bnd#issues

Understood, but "completed" is still wrong.

**Comment by laeubi** [comment]
> https://github.com/bndtools/bnd#issues

It says:

>> If you got time to spare, do not hesitate to open them and indicate you're willing to work on them.

But only committers can reopen issues...

**Comment by michael-o** [comment]
@pkriens Please reopen and close as closed and not completed.

**Comment by laeubi** [comment]
One can only close an issues as "completed" or "not planned", I think both are simply inappropriate choices for issues that are meant to be "Not fixed right now but we want contributions" 

![grafik](https://github.com/bndtools/bnd/assets/1331477/f67f2b74-71be-40f0-86ff-f02c20dfe778)

**Comment by michael-o** [comment]
> One can only close an issues as "completed" or "not planned", I think both are simply inappropriate choices for issues that are meant to be "Not fixed right now but we want contributions"
> 
> ![grafik](https://user-images.githubusercontent.com/1331477/250083766-f67f2b74-71be-40f0-86ff-f02c20dfe778.png)

Closed as not panned would be the right one here.

**Comment by pkriens** [comment]
If you create a PR that references it I will open it again.
