### ISSUE TITLE
Unrecognized constant pool tag value 60

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5713]
While working with a library I get:

`Contains: Invalid class file com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class (Unrecognized constant pool tag value 60 at index 41)`

the class is contained in this artifact:

```
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ibm.icu</groupId>
  <artifactId>icu4j</artifactId>
  <version>2.6.1</version>
</project>
```

**Comment by pkriens** [comment]
This is an 18 year old jar that is also causing problems in javap: 

     javap -v -c biz.aQute.bnd.util/testresources/diverse/LocaleElements_zh__PINYIN.class
     Error: error while reading constant pool for biz.aQute.bnd.util/testresources/diverse/LocaleElements_zh__PINYIN.class: unexpected tag at #41: 60

I assume this error is logged and further ignored so i will close this as no fix.
