### ISSUE TITLE
Feature request: Official  bnd rules for Bazel

### ISSUE THREAD

**Issue by GuusDeLange** [bndtools/bnd#5738]
The project that I'm working on makes heavy use of bnd (specifically the maven plugins). For this project we're currently in the early (planning) stages of migrating from Maven to Bazel as the build system. A major downside of this is that since there are currently no official rules/tools in bnd for Bazel  (as far as we know). This will at best significantly increase the complexity of migrating to Bazel.

We're currently managing this in a test environment through our own custom rules that use bndlib to build, test and export bundles, but these rules are far from exhaustive.

For this reason, in combination with the fact that Bazel is becomming more widely used, I'd like to ask whether official support for Bazel as a build system in a similar capacity to Maven/Gradle is something you'd consider looking into, or if that is even an option?

Cheers!

**Comment by pkriens** [comment]
Guus,
That sounds awfully interesting! 

Clearly we can integrate Bazel support on the same level as maven, eclipse, sbt, ant, and gradle. However, unless you're willing to fund the work, you will have to make the contributions ... I will of course help with architecture and integration but this is not (yet) my itch. That said, if you could raise some funding for this work I'd love to be more active, it is right up my sleeve.

To see how to start we could have a zoom call. Please contact me on peter.kriens@aQute.biz to setup a call.

**Comment by GuusDeLange** [comment]
Peter,

Thanks for the positive response! I will discuss the proposition internally here, and we will see where to go from there.

**Comment by pkriens** [comment]
Shall we close this issue to abeyance until the time you want to work on this? I'd like to keep the list of open issues to the one that are actively worked upon.
