### ISSUE TITLE
aQute.bnd.osgi.resource.FileResourceCache.getResource(File, URI) does not take URI into account

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5740]
If one generates a resource for the same file in a session one gets the resource with an old URI in the content capability.

That is because `aQute.bnd.osgi.resource.FileResourceCache.getResource(File, URI)` does not take the URI into account when computing the cache key.

**Comment by pkriens** [comment]
Do you want this in the 7.0.0 release cycle @laeubi ?

**Comment by laeubi** [comment]
@pkriens as this is deep into BND internals I'm not sure if can contribute more than the initial analysis/problem description here.

**Comment by laeubi** [comment]
> Do you want this in the 7.0.0 release cycle @laeubi ?

Would be useful indeed.
