### ISSUE TITLE
git plugin missing in bnd list of plugins

### ISSUE THREAD

**Issue by linusjf** [bndtools/bnd#5741]
Platform: Arch Linux on Termux
Java version: openjdk 20.0.2 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+9)
OpenJDK 64-Bit Server VM (build 20.0.2+9, mixed mode, sharing)
Bnd version: 6.4.1

While using the [guided tour](https://bnd.bndtools.org/chapters/123-tour-workspace.html), `bnd plugins` does not list git as an available plugin:

```
000 Workspace [com.acme.prime]
001 java.util.concurrent.ThreadPoolExecutor@527740a2[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
002 org.osgi.util.promise.PromiseFactory@7ba18f1b
003 <empty>
004 aQute.bnd.build.LoggingProgressPlugin@23e028a9
005 Maven [m2=/root/.m2/repository]
006 Settings[/root/.bnd/settings.json]
007 bnd-cache [/root/com.acme.prime/cnf/cache/6.4.1/bnd-cache r/w=false]
008 ResourceRepositoryImpl [cache=/root/.bnd/caches/shas, indexFile=/root/com.acme.prime/cnf/repo.json, ]
009 aQute.bnd.exporter.executable.ExecutableJarExporter@8b87145
010 aQute.bnd.exporter.runbundles.RunbundlesExporter@6483f5ae
011 aQute.bnd.http.HttpClient@b9afc07
012 aQute.bnd.osgi.Processor
013 aQute.bnd.osgi.Processor
```

Additionally, 
`bnd add plugin git`
fails with the following message:
```
Errors
000: No such plugin: git
/root/LearnJava/bnd exited with error code 1
```

**Comment by linusjf** [comment]
> It is still there but we hid it. The commit:
> 
> ```
> [plugins] Added hide to plugins 
> 
> Some plugins are internal (I think) and should not
> show on the insert menu.
> ```

If that's the case, kindly update the documentation to reflect the same. I am not familiar with OSGI and why you would need it hid.

**Comment by pkriens** [comment]
If you're new, this might not be the right place to start if you're totally unfamiliar. The bnd tools is kind of quirky, extremely useful for the expert but lots of history for the uninitiated.  You might want to lay out your situation and what you want from OSGi on bnd.discourse.group. People generally get then directed to the right path. There are so many options in the Java world that it is easy to get overwhelmed.
