### ISSUE TITLE
How to migrate RCP-project to bnd-project?

### ISSUE THREAD

**Issue by AlBundy33** [bndtools/bnd#5756]
I have currently no idea where to start. 🙁 

What I've done:
create c:\temp
download eclipse-rcp-2023-06-R-win32-x86_64.zip to this folder and extract the archive
modify eclipse.ini (just to ensure no side effects with existing installations)
add this to the beginning
```
-data
C:/temp/home/workspace
-configuration
C:/temp/home/configuration
```
and this to the end of the eclipse.ini
```
-Duser.home=C:/temp/home
-Dbnd.home.dir=C:/temp/home/.bnd_temp
```

now start eclipse and open File -> New -> Plug-In Project
enter project name bnd.example.app and click next
select generate an activator and set create rich client application to yes
client next and select RCP 3.x Mail Template and click finish.

This opens the manifest where I can start the example-application.

Now installer bndtools from marketplace and restart eclipse.

Now select File -> New -> Other and create a new Bnd OSGî Workspace from bndtools/bndtools.workspace.min

After that edit cnf/build.bnd and add
```
# Eclipse Release repositories 
eclipse.version          = 4.28
eclipse.name             = 2023-06
eclipse.platform.version = R-4.28-202306050440

eclipse.platform.baseurl = http://download.eclipse.org/eclipse/updates
#eclipse.platform.baseurl = "${fileuri;${user.home}}www/download.eclipse.org/eclipse/updates"
eclipse.platform.name    = Platform_${eclipse.platform.version}
eclipse.platform.url     = "${eclipse.platform.baseurl}/${eclipse.version}/${eclipse.platform.version}"

# Remote Eclipse repositories

# 1. creation of the indices via this configurations and store inside cnf/fixedIndices
-plugin.1.eclipse.platform: \
    aQute.bnd.repository.p2.provider.P2Repository; \
       name  = ${eclipse.platform.name}; \
        url   = ${eclipse.platform.url}
```
After saving the file click on reload workspace in Bndtools explorer to download the "target-platform".

And now I'm stuck 🙂 
I have a working rcp app and installed bndtools but what are the next steps?
Can I somehow create the bnd- and bndrun-files from my existing project?
And if not what do I have to add to the files?

thanks in advance 🙂

**Comment by juergen-albert** [comment]
As this is not a Bug, I'd suggest you reopen this in https://bnd.discourse.group/, so we can discuss it there. We can give a few pointers.
