### ISSUE TITLE
Jar Sign error when signing fat jar (jar size is larger)  in bnd project

### ISSUE THREAD

**Issue by ganesh08** [bndtools/bnd#5760]
We utilize bnd to create a fat JAR file for a specific use case. However, when the size of the fat JAR reaches 23.1 MB, the JAR signing process encounters a failure and the JAR file is not generated.
Jar sign working as expected for small size jars.

Error message as below no further details shown

```
Signing Jar out:
err:
```

Inside the project bnd file I use` -includeresource :` \ to include different jar and make fat jar
BND Version : 6.4.0
In main bnd file jar signing property provided as below
`-sign : ${sign.alias}; keypass:=${sign.keypass}`

Any help will be appreciated resolving this issue or to exclude this particular project from signing process

Thanks in advance

**Comment by pkriens** [comment]
Is it possible to share the project or make a sharable repo that exhibits this behavior?

**Comment by pkriens** [comment]
I want to release the first release candidate at the end of the week. If this is not fixed before, it will be moved to 7.1

**Comment by pkriens** [comment]
I am going to  close this is will not be fixed. If you have a demo project, you can reopen it.
