### ISSUE TITLE
aQute.bnd.header.OSGiHeader.parseHeader does not properly handle an unquoted filter value

### ISSUE THREAD

**Issue by merks** [bndtools/bnd#5762]
The following simple program demonstrate the problem:
```
package bizq;

import aQute.bnd.header.OSGiHeader;

public class Test {
	public static void main(String[] args) {
		for (var header : new String[] {
				"osgi.extender; filter:=(&(osgi.extender=osgi.remoteserviceadmin) (version>=1.1) (!(version>=2.0))),osgi.extender;filter:=\"(&(osgi.extender=osgi.remoteserviceadmin.localdiscovery)(version>=1.0)(!(version>=2.0)))\"",
				"osgi.extender; filter:=\"(&(osgi.extender=osgi.remoteserviceadmin) (version>=1.1) (!(version>=2.0)))\",osgi.extender;filter:=\"(&(osgi.extender=osgi.remoteserviceadmin.localdiscovery)(version>=1.0)(!(version>=2.0)))\"", }) {
			var parseHeader = OSGiHeader.parseHeader(header);
			System.out.println(header);
			for (var entry : parseHeader.entrySet()) {
				System.out.print("  ");
				System.out.println(entry);
			}
		}
	}
}
```

It prints out this:
```
osgi.extender; filter:=(&(osgi.extender=osgi.remoteserviceadmin) (version>=1.1) (!(version>=2.0))),osgi.extender;filter:="(&(osgi.extender=osgi.remoteserviceadmin.localdiscovery)(version>=1.0)(!(version>=2.0)))"
  osgi.extender=filter:="(&(osgi.extender"
osgi.extender; filter:="(&(osgi.extender=osgi.remoteserviceadmin) (version>=1.1) (!(version>=2.0)))",osgi.extender;filter:="(&(osgi.extender=osgi.remoteserviceadmin.localdiscovery)(version>=1.0)(!(version>=2.0)))"
  osgi.extender=filter:="(&(osgi.extender=osgi.remoteserviceadmin) (version>=1.1) (!(version>=2.0)))"
  osgi.extender~=filter:="(&(osgi.extender=osgi.remoteserviceadmin.localdiscovery)(version>=1.0)(!(version>=2.0)))"
```
The only difference between the two headers is the quotes around the first `filter:=`'s value of the second header value. 

I don't think the header is invalid according to the OSGi specification; I think the header parsing utility just doesn't cover this corner case.

The above is using https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bndlib/6.4.1/

with Java:

> openjdk version "17.0.7" 2023-04-18
> OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
> OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

on Windows 10.

See https://github.com/merks/simrel-maven/issues/10 for more background.

**Comment by pkriens** [comment]
BTW, it would really help if you whittle down the example to the bare minimum.

**Comment by pkriens** [comment]
I am closing this, please reopen if I was wrong in the diagnosis.

**Comment by merks** [comment]
@pkriens 

I believe your assessment is correct.  I found this with a BNF grammar:

https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fosgi%2Futil%2FManifestElement.html

It says this:
> If components contain delimiter characters (e.g ';', ',' ':' "=") then it must be a quoted string.

Thank you.
