### ISSUE TITLE
Remove org.osgi.util.promise from bndtools.main.feature

### ISSUE THREAD

**Issue by tjwatson** [bndtools/bnd#5787]
The `org.osgi.util.promise` has been included in the Eclipse platform since 2022-06.  Can we remove the older version included in `bndtools.main` feature?

https://github.com/bndtools/bnd/blob/99e901cda3a445cdb241ded80d66b3c76ec6a284/org.bndtools.p2/features/bndtools.main/feature.xml#L685-L690

**Comment by laeubi** [comment]
I just wanted to mention that actually it is not required to include requirement in features anyways if they are transitively required by a bundle so a feature should at best only list the direct application bundles that make up the feature but not any dependencies.

**Comment by bjhargrave** [comment]
Seems reasonable to me. Probably an oversight on my part when I updated the Eclipse deps to 4.25 (2022-09).

`org.osgi.util.function` should also be removed too, right? I assume if Eclipse provides promise it also provides function.

**Comment by tjwatson** [comment]
> `org.osgi.util.function` should also be removed too, right? I assume if Eclipse provides promise it also provides function.

Yes `org.osgi.util.function` is included in the RCP feature also.  So it should always be there.  I didn't notice the duplicate here because currently both projects are using the same version so there is no duplicate installed when installing BND tools.

**Comment by bjhargrave** [comment]
> the RCP feature

RCP feature? Bndtools depends upon:

https://github.com/bndtools/bnd/blob/99e901cda3a445cdb241ded80d66b3c76ec6a284/org.bndtools.p2/features/bndtools.main/feature.xml#L513-L515

If promise and function are not part of the `org.eclipse.platform` feature, then Bndtools will need to continue to require them.

**Comment by laeubi** [comment]
> If promise and function are not part of the `org.eclipse.platform` feature, then Bndtools will need to continue to require them.

As said this is not true in general. If the feature includes "bundle A" and that bundles requires a package of `org.osgi.util.promise` it will be included, if `org.osgi.util.promise` requires `org.osgi.util.function` it will be installed as well and so on.

If you just want to include it in the update-site, you should just include it there, but it is not required in the feature itself.

**Comment by pkriens** [comment]
@tjwatson will you make a PR?
