### ISSUE TITLE
Derivation of JPMS automatic module name

### ISSUE THREAD

**Issue by ppkarwasz** [bndtools/bnd#5792]
In the case a JAR file has neither a `module-info.class` descriptor nor an `Automatic-Module-Name` header, BND should:
 * derive the module name from the file name using the algorithm described in [`Modulefinder#of`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/module/ModuleFinder.html#of(java.nio.file.Path...)),
 * warn the user about the intrinsic instability of module names derived from file names.
 
 The current behavior in [`JPMSModuleInfoPlugin`](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSModuleInfoPlugin.java) does not convert non-alphanumeric characters like `-` into dots.

**Comment by pkriens** [comment]
Is the issue only the name conversion or are the other issues also not properly handled?

**Comment by ppkarwasz** [comment]
In our effort to generate JPMS modules using BND (apache/logging-log4j2#1819), we encountered two kinds of issues:

1.  if we mark with `resolution:=optional` the packages that depend on optional dependencies, the corresponding modules will be correctly marked as `static`, but might be also `transitive`, which will force consumers to add all optional modules to the compile path. We override it in our BND configuration,
1. we have some problems with module names of our dependencies. Most of these problems were solved by #5327, but some of our dependencies are old APIs (like `commons-logging`) that do not have a predefined module name.

I tested the new `7.1.0-SNAPSHOT` version and it works great except this small problem.

**Remark**: these issues are not blockers, since we can workaround them with explicit configuration, but we would prefer not to do it.

**Comment by pkriens** [comment]
I understand the non-alphanumeric and can fix this.

However, you mention lots of issues and I am not sure I can see what we should do for them or if they are just provided for background info?

**Comment by ppkarwasz** [comment]
The issues are provided as background.

I compared BND with other tools that generate JPMS descriptors and I am very satisfied with the results. The only useful automation that is missing is:

-  fixing the non-alphanumeric problem,
-  warn the developer if a filebased module name obtained from such a procedure is used in a non-`static` require statement.

**Comment by pkriens** [comment]
I will fix the conversion.

However, for the warning about non-static require statement I will need more help. This seems on the maven side which I've been trying to avoid like the plague after bad childhood memories :-) Could you make a PR?

**Comment by ppkarwasz** [comment]
> However, for the warning about non-static require statement I will need more help. This seems on the maven side which I've been trying to avoid like the plague after bad childhood memories :-) Could you make a PR?

Sure, I'll submit a PR.

**Comment by pkriens** [comment]
I might be a bit daft, but is the only issue a warning when a file name is used for the module name? If so, I can add it.

**Comment by ppkarwasz** [comment]
@pkriens,

Yes, that should be enough. Maven prints this warning: https://stackoverflow.com/q/46501047/11748454

In the future BND could check if file-based module names are not used in a `requires` statement that is not `static`. However one could argue, that in the future there will be no more file-based module names.
