### ISSUE TITLE
Wrong Minimal required maven version for 7.0.0

### ISSUE THREAD

**Issue by ZheSun88** [bndtools/bnd#5801]
Hi, our project is using the `bnd-maven-plugin` and recently we have upgraded the version from 6.4.0 to 7.0.0. 
then i can see this error in my build log
```
Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:7.0.0:bnd-process (default) on project : The plugin biz.aQute.bnd:bnd-maven-plugin:7.0.0 requires Maven version 3.8.1 
```

but in the 7.0 [release note](https://github.com/bndtools/bnd/wiki/Changes-in-7.0.0#backward-compatibility), you have stated
```
The Bnd Maven plugins require a minimum of Maven 3.3.9. The bnd-generate-maven-plugin's poorly named goal bnd-generate has been renamed generate
```

which side is wrong in this case?

**Comment by pkriens** [comment]
The problem is as far as I am concerned the version of Maven ...

I've update the release changes. Unless you really need to be compatible with the older version, I'd like to close this issue?

**Comment by ZheSun88** [comment]
sure, as long as the maven version has been aligned here. it is fine.
