### ISSUE TITLE
[bndtools] Create test bndrun for latest version of Eclipse

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#5815]
The Eclipse version that we build against for Bndtools is typically a year or two behind the latest version. This is also the version that our existing `bndtools.*.bndrun` files launch.

It is not uncommon to hit bugs in Bndtools that only manifest in versions of Eclipse that are later than the baseline we are buliding/testing against (https://github.com/bndtools/bnd/issues/4433#issuecomment-752656364, https://bnd.discourse.group/t/test-bnd-bndtools-bundle-in-eclipse/358/3). It would be handy if we had a `.bndrun` in the workspace that would launch an Eclipse instance with Bndtools installed that could be used to test against a later version of Eclipse.

**Comment by pkriens** [comment]
@kriegfrj do you intend to open a PR?

**Comment by kriegfrj** [comment]
Hopefully soon, I'm prioritising the Builder enhancements.

**Comment by pkriens** [comment]
@peterkir has some contributions here.

**Comment by pkriens** [comment]
Please reopen when needed.
