### ISSUE TITLE
Inline comments in Eclipse not working

### ISSUE THREAD

**Issue by mswatosh** [bndtools/bnd#5817]
I recently had a line like the following in my bnd.bnd file:
![Screenshot 2023-10-16 at 9 02 52 AM](https://github.com/bndtools/bnd/assets/21284019/6152e769-fb1d-4cbe-ae89-011b2513e825)

Eclipse highlights the inline comment correctly, however it seems like the comment isn't actually honored. I'm ok with not being able to do inline comments, but would it be possible to have eclipse not highlight them as comments, to avoid confusion?

**Comment by pkriens** [comment]
Phew, the Eclipse Text Editor highlighting is a horrible thing. That was really complicated to fix.
