### ISSUE TITLE
The default package should be automatically excluded from the Import-Package header

### ISSUE THREAD

**Issue by ptziegler** [bndtools/bnd#5830]
We use Tycho/m2e in our project, in order to include Maven artifacts in our RCP application. For artifacts without proper OSGi metadata, both tools use BND to automatically convert them into proper OSGi bundles.

The following dependency is now causing problems:
```
<dependency>
    <groupId>net.sf.jazzy</groupId>
    <artifactId>jazzy-core</artifactId>
    <version>0.5.2</version>
</dependency>
```

using those bnd instructions:
> Import-Package: *;resolution:=optional
> Export-Package: *;version="${version}";-noimport:=true

with the following error message:
> The default package '.' is not permitted by the Import-Package syntax.
 This can be caused by compile errors in Eclipse because Eclipse creates
valid class files regardless of compile errors.
The following package(s) import from the default package null

This leads me to the assumption, that BND also considers the classes that are located inside the root directory and them attempts to add them to the `Import-Packages` header, regardless of whether they are valid candidates:

![image](https://github.com/bndtools/bnd/assets/70652978/4988108e-2558-4b99-b73d-4a802a66ac82)

I've played around a little with custom Import-Package/Export-Package instructions but even when I set the packages manually (or set none at all), the error still shows up.

Here's a quick example that should reproduce the same error (tested with both bnd 6.4.1 and 7.0.0)
```
try (Jar jar = new Jar(new File("jazzy-core-0.5.2.jar"))) {
	try (Analyzer analyzer = new Analyzer(jar);) {
		analyzer.setProperty("mvnGroupId", "net.sf.jazzy");
		analyzer.setProperty("mvnArtifactId", "jazzy-core");
		analyzer.setProperty("mvnVersion", "0.5.2");
		analyzer.setProperty("mvnClassifier", "jar");

		analyzer.setProperty("Bundle-SymbolicName", "wrapped.${mvnGroupId}.${mvnArtifactId}");
		analyzer.setProperty("Bundle-Version", "${mvnVersion}");
		analyzer.setProperty("Bundle-Name", "Bundle derived from maven artifact ${mvnGroupId}:${mvnArtifactId}:${mvnVersion}");
		analyzer.setProperty("DynamicImport-Package", "*");
		analyzer.setProperty("Import-Package", "*;resolution:=optional");
		analyzer.setProperty("Export-Package", "*;version=\"${mvnVersion}\";-noimport:=true");
		jar.setManifest(analyzer.calcManifest());
		jar.write(new File("wrapped-jazzy-core-0.5.2.jar"));

		for (String err : analyzer.getErrors()) {
			System.out.println(err);
		}
	}
}
```

A quick debugging session lead me to the local field `referred` in the Analyzer class which includes the default package. I think this is probably a good starting point to figure out what's going on.

**Comment by pkriens** [comment]
I think the best way is to ignore the error message with `-fixupmessages`. The message is an import warning for Eclipse users because it is likely that partially compiled class files were included.

There are a tiny set of valid use cases but I think it is better then to explicitly ignore the error/warning instead of silently ignoring it.

**Comment by pkriens** [comment]
I am closing this  as not fix, if you've think you can convince me, feel free to reopen it with the additional arguments.
