### ISSUE TITLE
PropertiesLineReader never updates lastValue

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5839]
[PropertiesLineReader](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/properties/PropertiesLineReader.java) has a method value() but the field **is always null** as it is never assigned any value.

So any call to `PropertiesLineReader#value()` always throws exception.

**Comment by laeubi** [comment]
If one is working on it, it would be great to have not only `IRegion` for whole but also for key / value separately.

**Comment by pkriens** [comment]
Will you be submitting a PR?

**Comment by laeubi** [comment]
See
- https://github.com/bndtools/bnd/pull/5850
