### ISSUE TITLE
PropertiesLineReader has now way to read the comment

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5843]
When `PropertiesLineReader` encounters a comment it currently just returns (and throws away everything), so after that the caller needs to recover the data by some other means.

Beside that `key()` method returns the key of the last seen item but should be `null` at this point

**Comment by pkriens** [comment]
Are you going to work on this class? Could you then just open an (empty if you want) PR? I want to keep the issues razor sharp focused on problems that need urgent fixing.

**Comment by laeubi** [comment]
See
- https://github.com/bndtools/bnd/pull/5850
