### ISSUE TITLE
[pde+bndtools] extract the bnd instructions (BndSourceEditorPage) into a bndtools.editor bundle

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5844]
bndtools and pde both now include an editor that shows a source tab.
Unless 
- https://github.com/bndtools/bnd/issues/5833

is done and adopted, it seems a good idea to share these codes (currently there is an attempt to copy the basic parts [here](https://github.com/eclipse-pde/eclipse.pde/pull/823)).

For that purpose i'd like to suggest a new  `bndtools.editor` bundle that contains these basic parts in a way that it only depends on

- bndlib
- eclipse
- bndtools.api

that way PDE can include it with a consumer version range making it possible to nicely coexits with bndtools install.

Beside the editor, such bundle should at best also contain a [content-type definition](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_core_contenttype_contentTypes.html) so PDE+BND can share the same content type so extension of one plugin can be applied to the other easily (this probably would also fix current [PDE vs BNDTools Editor confusion](https://github.com/eclipse-pde/eclipse.pde/issues/672) as one can define proper priority rules then).

**Comment by pkriens** [comment]
Do you intend to make a PR or should we move this to abeyance  until someone wants to work on this?
