### ISSUE TITLE
Add help buttons to all bndtools views linking to manual

### ISSUE THREAD

**Issue by chrisrueger** [bndtools/bnd#5849]
To make it easier to get context sensitive help I would suggest to add some kind of "help" buttons to each View linking to the relevant sections of the manual.

- Bndtools Explorer
- Repository View
- Resolution View

**Goal**

- Make it easier for (new) users to find out what a view is for. 
- Currently there is no real way from Bndtools in Eclipse to the Manual. That would be an entry point. 

## Like this.

<img width="1180" alt="image" src="https://github.com/bndtools/bnd/assets/188422/81884900-9de6-4cd3-9a78-269d140ff09d">

Note: I quickly added the icon over existing icons hiding them.... In the solution I would of course add them next to appearing in the upper right corner of those bars.

Also an entry in the Welcome Screen could be useful. Seems that plugins can hook in there.

<img width="1728" alt="image" src="https://github.com/bndtools/bnd/assets/188422/55237c23-a7b5-4613-bb1b-f998ae63536f">

Maybe this could go to https://bndtools.org/workspace.html

If that is considered helpful I would start working on a PR for this.

**Comment by pkriens** [comment]
You're doing great work so please continue!

In general, if you want to provide an improvement, please file a PR directly and any discussions can take place there. This keeps the issues list more on urgent or contentious issues. We rarely deny useful additions but if you want to brainstorm, please do this on bnd.discourse.group. This allows more people to participate.

But please continue, love what you're doing.
