### ISSUE TITLE
[pde+bndtools] define a way for project template creation

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5851]
PDE has an extension point `org.eclipse.pde.ui.pluginContent` (org.eclipse.pde.ui.IBundleContentWizard) that allows the user to select some example content for a project:

![grafik](https://github.com/bndtools/bnd/assets/1331477/30c71051-7361-4ac9-96c0-7059486f4987)

beside that it support "Custom Plugin Wizard" with the `org.eclipse.pde.ui.templates` (org.eclipse.pde.ui.templates.ITemplateSection) extension point

![grafik](https://github.com/bndtools/bnd/assets/1331477/46975890-1962-4f09-b106-0450059f0b4c)

BNDtools offers something similar:
![grafik](https://github.com/bndtools/bnd/assets/1331477/c35233b1-867c-4155-b4e3-332fa4bebe1d)

It would be good to investigate how this can be unified in a way so PDE+BNDtools can share the same templates.

**Comment by pkriens** [comment]
Please provide these kind of 'nice if we had x' issues as a PR. I'd like to keep the issues for errors that need to be addressed for the next release. 

It would be different if we had a bunch of committers desperate for work ... but this will just go in abeyance soon when no  PR emerges.

**Comment by laeubi** [comment]
>  I'd like to keep the issues for errors that need to be addressed for the next release.

Why not use a [label](https://github.com/bndtools/bnd/labels) or [milestone](https://github.com/bndtools/bnd/milestones) for that?

It doesn't make much sense to "hide" everything from the rest of the world this makes it really hard for people like to contribute to bnd and higher the risk of duplicate work or forgotten issues/improvements. As an alternative you might want to enable [GitHub Discussions](https://docs.github.com/en/discussions/quickstart) to collect ideas for further improvements that might need some more ideas from others.

**Comment by pkriens** [comment]
We had the discussions a few years ago and explicitly decided to use bnd.discourse.group.

We are a tiny  little project and at the time we felt we were spreading ourselves too thin with Slack, Issues, PRs, and discourse.

However, group is changed so feel free to open this discussion in Slack or discourse.

However, I am pretty strong on keeping the open issue for issues that _really_ need someone to work on before the next release and not someone's todo/wish list.

**Comment by pkriens** [comment]
Do you intend to provide a PR or should we move this to abeyance until someone is found to work on this?
