### ISSUE TITLE
Missing Help Menu bar entries in launched Eclipse instance during bndtools development

### ISSUE THREAD

**Issue by chrisrueger** [bndtools/bnd#5853]
For some reason when I launch bndtools from `/bndtools.core/bndtools.cocoa.macosx.x86_64.bndrun` the launched Eclipse instance's (Version: 2022-09 (4.25) Build id: I20220831-1800) **Help menu bar** looks like this.

<img width="361" alt="image" src="https://github.com/bndtools/bnd/assets/188422/497e86d7-95e7-40d4-bc01-f661b4a59ba2">

Compare it to the normal Eclipse 4.29 **from** which I launched it:

<img width="366" alt="image" src="https://github.com/bndtools/bnd/assets/188422/d04e7b1d-093c-486c-b4c0-123c3dc5290d">

I discovered during work on #5852 where I wanted to extend the Welcome Intro screen. But I cannot open the Welcome screen because the entry is missing.

Has anybody seen this behavior? @laeubi  maybe?

OS: MacOS Sonoma 14.1.

**Comment by laeubi** [comment]
I have no mac for testing but @SyntevoAlex might be the SWT mac expert, but you should probabbly also report this to the [SWT project](https://github.com/eclipse-platform/eclipse.platform.swt/issues?q=is%3Aopen+is%3Aissue+label%3AmacOS) if you think its an SWT issue.

Another problem might be that your bndrun does not include everything (e.g mpc, p2, oomph) what contributes to the menu. When you have a recent PDE you can create a product file, add bndtools feature + platform sdk + marketplace should give you similar, or you create a new product run out of your workspace.

**Comment by chrisrueger** [comment]
> Another problem might be that your bndrun does not include everything (e.g mpc, p2, oomph) what contributes to the menu.

Ha you were right 😄 

`-runbundles` seems to contain [org.eclipse.ui.intro;version='[3.6.600,3.6.601)',\](https://github.com/bndtools/bnd/blob/master/bndtools.core/bndtools.cocoa.macosx.x86_64.bndrun#L278C42-L278C52) but maybe not other intro-related bundles?

e.g. if I search my repo I find other bundles which are not yet part of `-runbundles`.

<img width="508" alt="image" src="https://github.com/bndtools/bnd/assets/188422/561fad22-e437-494c-bcbc-3ceda50510f9">

After I added all of them to -runbundles manually I now see the Welcome menu entry.
<img width="364" alt="image" src="https://github.com/bndtools/bnd/assets/188422/f8f661cf-bce1-40dd-9aa0-1d98ead2d8c5">

I am not sure which one it is wether it is just one or all of them. 

@pkriens : What would be the best way to go forward here? Are the `-runbundles` maintained just manually?

**Comment by pkriens** [comment]
They are maintained manually. I think @kriegfrj was working on improving this. 

Can this issue be closed?

**Comment by chrisrueger** [comment]
> Can this issue be closed?

When you give your ok that I add this to my work in #5852 then yes, this can be closed.

**Comment by kriegfrj** [comment]
> They are maintained manually. I think @kriegfrj was working on improving this.
> 

No, @bjhargrave fixed this. We use the resolver. The base set of runbundles is in the bndtools.shared.bndrun, with os-specific requirements added using the merged property feature (ie, -runtequires.win32, etc) in the os- specific bndruns that include the shared bndrun.

**Comment by chrisrueger** [comment]
Thanks @kriegfrj . I added them to shared.bndrun in
 https://github.com/bndtools/bnd/pull/5852/commits/2591b3a9def01f41400389a4f211f9aba9a4e1e5

then I ran the resolver which resulted in the following `-runbundles`

https://github.com/bndtools/bnd/pull/5852/commits/b05a414d07d87b08f8f468a63e440801259d37b1

I think we can close this issue here and continue in #5852
