### ISSUE TITLE
Don't use distribution management in Baseline Maven plugin by default

### ISSUE THREAD

**Issue by ppkarwasz** [bndtools/bnd#5854]
A common misconception about `<distributionManagement>` is that it can be used to **download** releases.

This Maven element is actually only useful to **upload** releases (cf. the discussion in CycloneDX/cyclonedx-maven-plugin#245 for example). The recent [`org.apache:apache`](https://github.com/apache/maven-apache-parent) artifacts, which are used by all Apache projects including Maven itself use a **write-only** URL in the distribution management.

Therefore IMHO, the `includeDistributionManagement` option of the `bnd-baseline-maven-plugin` should be disabled by default.

**Comment by pkriens** [comment]
will you make a PR?

**Comment by pkriens** [comment]
PR closed, so we can close this as well
