### ISSUE TITLE
bndtools 7 release still using osgi R7 (not R8) for built-in workspace templates

### ISSUE THREAD

**Issue by scottslewis** [bndtools/bnd#5864]
The two 'built-in' workspace templates in repos:   [bndtools.workspace.min](https://github.com/bndtools/bndtools.workspace.min) and [bndtools.workspace](https://github.com/bndtools/workspace) are both still pointing to OSGi R7 repos/bundles rather than OSGi R8 (latest release).

One user-visible effect this has is that anyone trying/using the new [OSGi Service wizard ](https://github.com/bndtools/bnd/issues/5632) (for Java) via Wizards->Other->OSGi Services->Java Service will produce projects that do not compile and run because the two workspaces above do not have the necessary R8 dependencies as described here

Issues for each repo to update from R7 to R8

https://github.com/bndtools/workspace/issues/23
https://github.com/bndtools/bndtools.workspace.min/issues/7

Having these old (R7) built-in templates makes it impossible to use the new OSGi Services wizard.

**Comment by pkriens** [comment]
I am closing this in lieu of #5632
