### ISSUE TITLE
Bndtools JAR Editor often hangs on reading JAR file

### ISSUE THREAD

**Issue by ideas-into-software** [bndtools/bnd#5897]
- Bndtools JAR Editor often hangs on reading JAR file – regardless if opening a JAR file from bundle’s generated folder or from `Repositories` view;
- In `Progress` view, `Reading zip file` and `Creating link.: Refreshing '/.BndtoolsJAREditorTempFiles/temp/…'` can be seen;
- In majority of cases, this causes Eclipse to stop responding and, when this happens, 90% of the time killing of Eclipse process is required in order to continue – only on rare cases does it gracefully brings itself back to normal functioning;
- Regardless of version of Eclipse and plugins used, frequency of occurrence of this problem completely disrupts normal work flow;
- Please see attached screenshots and log samples for details;

## Setup
**Eclipse IDE**: 
    • Version 2023-09 (4.29.0)
    • Build id: 4.29.0.20230907-1200
**Bndtools**: 7.0.0.REL-202310060912-gb82dc86
**OS**: Ubuntu 22.04.3 LTS
**Hardware**: Dell Precision 7560, Intel® Xeon(R) W-11855M CPU, 64 GB RAM, M.2 SSD disks

In case more details are needed, I also saved output from Eclipse IDE installation details “Configuration” tab: see attached `eclipse-20230907-1200_bndtools-7.0.0.REL_configuration.txt` file.

## Attachments

[BndtoolsJAREditor_issues_screenshots.zip](https://github.com/bndtools/bnd/files/13404860/BndtoolsJAREditor_issues_screenshots.zip)
[BndtoolsJAREditor_issues_logs.zip](https://github.com/bndtools/bnd/files/13404863/BndtoolsJAREditor_issues_logs.zip)
[eclipse-20230907-1200_bndtools-7.0.0.REL_configuration.txt](https://github.com/bndtools/bnd/files/13404864/eclipse-20230907-1200_bndtools-7.0.0.REL_configuration.txt)

**Comment by pkriens** [comment]
This should be fixed by # #5910, please verify.

I assumed it came because the refresh caused an update. I now just refuse to have 2 background jobs.

Not completely sure this is the case so please reopen when you still experience this. This seems to be a problem on your platform (which might be timing) because I've never had this and this is a very popular JAR editor

**Comment by ideas-into-software** [comment]
@pkriens

I installed latest build snapshot (`7.1.0.DEV-202312261441-gd759351`) and briefly tested with tenths of JARs. It looks like this problem does not appear anymore but I will let you know if I still come across this issue.

Thank you very much for your help.
