### ISSUE TITLE
Eclipse Oxygen 4.7.3a repository is down

### ISSUE THREAD

**Issue by gg-dim** [bndtools/bnd#5898]
The location of the Eclipse Oxygen 4.7.3a index.xm.gz isn't available any more:

```repositories.bnd
    aQute.bnd.repository.osgi.OSGiRepository;\
        name="Eclipse Oxygen 4.7.3a";\
        locations="https://dl.bintray.com/bndtools/eclipse-repo/4.7.3a/index.xml.gz";\
        poll.time=-1;\
        cache="${workspace}/cnf/cache/stable/EclipseOxygen",\
```
![image](https://github.com/bndtools/bnd/assets/100089178/6323907c-e15b-4b0a-ae4d-fdba58d8e387)

The package should be uploaded again or moved to a more reliable location. (bnd.bndtools.org ...?)

**Comment by pkriens** [comment]
This happened a long time ago when JFrog stopped bintray. 

We are currently using: https://bndtools.jfrog.io/bndtools/bnd-build/eclipse/4.25/index.xml.gz
