### ISSUE TITLE
bndfile didn't work

### ISSUE THREAD

**Issue by interesting2333** [bndtools/bnd#5921]
I want to use bnd.bnd to create .mf file only. But the .mf file always has class from pom.xml which is different wit bnd.bnd. How can i fix this problem. The bnd-maven-plugin version is 6.4.0 and the bndfile target like this : <bndfile>${project.basedir}/bnd.bnd</bndfile>

**Comment by pkriens** [comment]
You will have to provide a lot more information because I've no idea what you're talking about? 

It helps to make a small repo on github that shows what you want.

**Comment by pkriens** [comment]
I am closing this issue since it has not enough information to follow up. Please reopen with additional info if you think there is an issue.
