### ISSUE TITLE
BndPomRepository cannot resolve OSGi dependencies by GAV like MavenBndRepository

### ISSUE THREAD

**Issue by chrisrueger** [bndtools/bnd#5961]
I was using `MavenBndRepository` so far. 
Yesterday I experimented with BndPomRepostory ([converted central.mvn to pom.xml](https://bnd.discourse.group/t/pro-con-of-using-pom-xml-vs-central-mvn-files-for-maintaining-dependencies-in-bndtools-mavenbndrepository-vs-bndpomrepository/407)) and I was getting errors.

**Eclipse Problems View: Bndtools Path Problem Marker**

`com.couchbase.client:core-io;version=1.7.23 Not found in [bnd-cache [/myproject/plugins/cnf/cache/7.1.0/bnd-cache r/w=false], BndPomRepository [name=mavenpom, localRepo=/Users/christoph/.m2/repository, location=cnf/cache/pom-mavenpom.xml]]
`
**Eclipse Problems View: Bndtools Problem Marker**

`${repo} macro refers to an artifact com.google.http-client:google-http-client-latest (HIGHEST) that has an error: com.google.http-client:google-http-client;version=latest Not found in [bnd-cache [/myproject/plugins/cnf/cache/7.1.0/bnd-cache r/w=false], BndPomRepository [name=mavenpom, localRepo=/Users/christoph/.m2/repository, location=cnf/cache/pom-mavenpom.xml]]
`

The thing is that my `/.m2/repository` definitely contains both.

Here is a `bnd.bnd` where those errors appear when I use `BndPomRepo`.

```
-buildpath: \
	com.couchbase.client:core-io;version=1.7.23,\

-includeresource: \
	@${repo;com.google.api-client:google-api-client;latest},\

```

Both things work **fine** when using MavenBndRepository.

I noticed the BndPomRepository builds an .xml index file and for the first entry above I see this:

<img width="682" alt="image" src="https://github.com/bndtools/bnd/assets/188422/4a426c9f-707b-4703-8ae2-9367d2226691">

## Now the strange thing how I can get it to work:

When I use only the `bsn` without the `groupId` then the error goes away.

```
-buildpath: \
	core-io;version=1.7.23,\

-includeresource: \
	@${repo;com.google.api.client.googleapis;latest},\

```

Notice the difference... there is no colon separating `groupId` and `artifactId`.

## Question

Is this expected behavior, that BndPomRepository behaves different?

Any idea where to start debugging this? 
Maybe differences in MavenBndRepository.get() vs BndPomRepository.get() ?

Here is my repository config ( only have one of each active)

```
-plugin.6b.Central: \
	aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
		snapshotUrl=http://repository.apache.org/snapshots/; \
		releaseUrl=https://repo.maven.apache.org/maven2/; \
		pom=${.}/pom.xml; \
		transitive=false; \
		name="mavenpom"
		
-plugin.6.Central: \
	aQute.bnd.repository.maven.provider.MavenBndRepository; \
		snapshotUrl=http://repository.apache.org/snapshots/; \
		releaseUrl=https://repo.maven.apache.org/maven2/; \
		index=${.}/central.mvn; \
		readOnly=true; \
		name="Maven Central"
```

Content of `central.mvn`:

`com.couchbase.client:core-io:1.7.23`

Content of corresponding `pom.xml` (which was created from `central.mvn`)

```
<dependency>
            <groupId>com.couchbase.client</groupId>
            <artifactId>core-io</artifactId>
            <version>1.7.23</version>
        </dependency>
```

**Comment by pkriens** [comment]
I am always impressed with your stamina. 

The MavenBndRepository is significantly more mature than the BndPomRepository. Although they're based on the same code, they do not have the same usefulness. When I got the idea for the Pom repository I thought it was one of the best ideas I'd ever had but using it made me really dislike it, mostly because it still confronts you with the immense redundancy of maven XML but there were other issues.

handling the GAV as BSN was a hack. Although it is a very useful hack. I guess we could add the same code to the BndPomRepository

**Comment by chrisrueger** [comment]
Thanks @pkriens 

> handling the GAV as BSN was a hack. Although it is a very useful hack. I guess we could add the same code to the BndPomRepository

So does that mean the only the `bsn` is actually the correct way?

I mean I could just change all the places in our `bnd.bnd` files too, no problem. I mainly want to do it the "right" way - if there is one. When I created the ticket I wasn't aware that the way I am doing things is actually the "hack". 

I am just wondering how I got there. Let me hypothesize:

about `- buildpath`:
- I could just imagine that when we introduced bndtools a couple of years ago we just did that in a couple of places. I checked our bnd.bnd files and I found a mix. Mostly we already use just the bsn and not the GAV
- I think that often I also use the bnd editor to add bundles to the buildpath and the editor's button just adds the `bsn`

about `-includeresource` with ${repo;} reference:
- here I find that I used the GAV almost everytime.
- I think this is meantioned in the examples [in the manual (Assignment form)](https://bnd.bndtools.org/instructions/includeresource.html) 

<img width="891" alt="image" src="https://github.com/bndtools/bnd/assets/188422/fe7830ea-b76e-435b-b82a-3f75073544ab">

I remember that I copied and pasted from there, so I guess that is how I thought it should be and how it ended up in our code base.


Ok I see mainly documentation TODOs so far.

1. the example(s) here https://bnd.bndtools.org/instructions/includeresource.html

`-includeresource: ${repo;com.acme:foo;latest}`

`-includeresource: acme-foo-snap.jar=${repo;com.acme:foo;snapshot}`

2. And maybe mentioning the behavior on the docs

- maybe here https://bnd.bndtools.org/plugins/pomrepo.html in the "Caveats" section at the bottom? 
- and here https://bnd.bndtools.org/plugins/maven.html I don't know. Maybe just make aware of the difference to BndPomRepo and link to the Caveats section of BndPomRepo ?

What do you think?

**Comment by pkriens** [comment]
> So does that mean the only the bsn is actually the correct way?
> I mean I could just change all the places in our bnd.bnd files too, no problem. I mainly want to do it the "right" way - if there is one. When I created the ticket I wasn't aware that the way I am doing things is actually the "hack".

Nope :-) The hack was needed because many maven jars do not have a bsn. The only way to use the jar then is to use the GAV. It is a last resort. This is a hack because not everybody has seen the OSGi light :-) In a good OSGi world you should _always_ use the bsn. The bsn is a pretty fundamental invariant in the OSGi world. Using the GAV when a bsn is available is begging for more beatings.

It is always surprising what you dreg up from the bowels of our documentation :-) I guess at the time I wrote that I was very smug with myself by having added the GAV. Although for `-includeresource` it is not completely out of line to show examples with GAV since you need these kind of instructions when you run head on into an OSGi challenged JAR :-(

**Comment by chrisrueger** [comment]
> > So does that mean the only the bsn is actually the correct way?
> > I mean I could just change all the places in our bnd.bnd files too, no problem. I mainly want to do it the "right" way - if there is one. When I created the ticket I wasn't aware that the way I am doing things is actually the "hack".
> 
> Nope :-) The hack was needed because many maven jars do not have a bsn. The only way to use the jar then is to use the GAV. It is a last resort. This is a hack because not everybody has seen the OSGi light :-) In a good OSGi world you should _always_ use the bsn. The bsn is a pretty fundamental invariant in the OSGi world. Using the GAV when a bsn is available is begging for more beatings.
> It is always surprising what you dreg up from the bowels of our documentation :-) I guess at the time I wrote that I was very smug with myself by having added the GAV. Although for `-includeresource` it is not completely out of line to show examples with GAV since you need these kind of instructions when you run head on into an OSGi challenged JAR :-(

Ah ok, interesting.

So could we say:
- for `- buildpath` you **should** always use bsn (because this is OSGi-land) and you are dealing with bundles for sure. You cannot use a non-OSGi jar in a `bnd.bnd` file. Should / could we add a warning marker to Eclipse-Problems view if you are using GAV there? so that people notice it and could clean it up?

- for `-includeresource` I totally see that it makes sense. I definitly use it to wrap non-OSGi jars. 
But given your statement to use GAV for `-includeresource` when there is no bsn, I think this would be a code change to allow that for BndPomRepository, right? to fix the error I currently  get with `@${repo;com.google.api-client:google-api-client;latest},\`


I can try to work on a PR. Just want to understand the goal :)

**Comment by chrisrueger** [comment]
I created PR https://github.com/bndtools/bnd/pull/5964

I found out the following:
- BndPomRepository has a problem when the bundle is an OSGi bundle, and it can resolve it only via bsn
- MavenBndRepository can do both bsn + gav if both are available
- I found `MavenBndRepoTest.testGetViaBSNAndGAV()` which I will adapt for BndPomRepository too

More in the PR
