### ISSUE TITLE
Add runrepos blacklist

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#5966]
One case I often run into is, that the resolver also pulls artifacts from the baseline repo, which is usually only for baselining. I need a mechanism to generically exclude this repo. Right now, we only have a whitelist, but a Blacklist would be much better, as repos usually change over time.

**Comment by pkriens** [comment]
There was a recent discussion to add tags to the plugins for exactly this reason: https://bnd.discourse.group/t/baseline-repo-exclude-from-the-build-path/391/2

**Comment by pkriens** [comment]
Will you implement this with tags as outlined? Then maybe we should have a short discussion?

**Comment by pkriens** [comment]
Any movement over here
