### ISSUE TITLE
Collector: new Quick Fixes

### ISSUE THREAD

**Issue by chrisrueger** [bndtools/bnd#5975]
This is a collector issue for findings regarding quick fixes.
Related to https://github.com/bndtools/bnd/pull/5969

**Comment by chrisrueger** [comment]
Basedon   `Bndtools	7.1.0.DEV-202401161323-gfa3d6b8	bndtools.main.feature.feature.group	Bndtools`

- [ ] "Add Component" replaces all existing import statements with `import org.osgi.service.component.annotations.Component;`. Expected: Just adding the import

- [ ] Convert to Textblock exists in Eclipse already (at least in 2023-12 ... not sure when it was added)
<img width="331" alt="image" src="https://github.com/bndtools/bnd/assets/188422/c6f442da-e805-447a-adfe-081ca101b170">

- [ ] **Add Component** and **Add Gogo** currently appear everywhere.
Expected: should only appear at the class name.

<img width="298" alt="image" src="https://github.com/bndtools/bnd/assets/188422/51d55a3a-2c50-42b5-9be6-31c3df1de09a">

- [ ] Add Gogo does nothing. Not sure what it should do.

- [ ] **Uppercase / Lower Case** remove imports. In my test it removed only an import of an annotation I was using:

<img width="638" alt="image" src="https://github.com/bndtools/bnd/assets/188422/bf9314b9-8993-49ca-bcf9-e31ca1f9d031">

**after to UPPERCASE**:

<img width="603" alt="image" src="https://github.com/bndtools/bnd/assets/188422/ec791e66-e5b6-4d93-ba5b-24f04f8b199f">

It removed a few more.
<img width="382" alt="image" src="https://github.com/bndtools/bnd/assets/188422/f078545f-7c54-4fdf-8b94-5e5ddac83436">

- import org.apache.commons.lang3.StringUtils
- import java.util.stream.Collectors;
- some internal JsonUtil of us..
- import javax.persistence.FetchType; (but other `javax.persistence.` imports are kept e.g. import `javax.persistence.Entity;` is not removed ) 

I Cannot recognize a pattern.

**Comment by pkriens** [comment]
I think I fixed these. I had fixed the imports in the test cases but in the Eclipse env. another constructor was used.

**Comment by chrisrueger** [comment]
Great thanks. I will try with next snapshot

**Comment by pkriens** [comment]
Ok, see I also have a problem with static imports :-(
