### ISSUE TITLE
Add a "validate" target for the bnd-resolver-maven-plugin

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#5984]
The current bnd-resolver-maven-plugin does validation using `failOnChanges` but this is a brittle solution. If different JVMs or different architectures are used then resolve output can be subtly different, e.g. by including an API jar such as `org.osgi.service.cm`.

We should add a `validate` target which creates a repository and run requirements from the `-runbundles`, checking that the -run bundles are locatable and will resolve.

**Comment by pkriens** [comment]
Are you going to provide a PR?

**Comment by timothyjward** [comment]
> Are you going to provide a PR?

As requested
