### ISSUE TITLE
Invalid error on DS field replacement

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#5994]
My DS component includes the following:

    @Reference(cardinality = ReferenceCardinality.MULTIPLE, policy = ReferencePolicy.DYNAMIC)
    volatile Set<MyService> services = new HashSet<>();

As far as I am aware this is perfectly legal [according to the DS spec](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-reference.field.option)

Despite this the following code in bnd triggers an error. I think this check needs to be removed.
https://github.com/bndtools/bnd/blob/58a13dcff87929498cc5f1eb6c786f94c0f35197/biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java#L1036-L1040

**Comment by pkriens** [comment]
Since you do not declare the field `final` it is considered a REPLACE Field Option. According to the annotation doc for `fieldOption`:
![image](https://github.com/bndtools/bnd/assets/200494/d41000c9-b754-43e1-ac08-dc5225280de4)

Since such a REPLACE field is under management of the SCR the assignment of the 'new HashTable()` would be superfluous since it will be replaced.

So I think the code is right to emit an error?

**Comment by pkriens** [comment]
Yes, I see it now. I think you're right. 

Will you make a PR?

**Comment by bjhargrave** [comment]
Bnd is correct here.

See https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-field.injection

> A subtype of Collection - This type can only be used for dynamic references using the update reference field option. The component instance must initialize the field to a collection object in its constructor. 

`Set` is not `Collection` or `List`. So to use `Set` you *must* use the update option.

**Comment by timothyjward** [comment]
> Bnd is correct here.

This is why I wanted more eyes on the review. I was surprised something like this might have slipped through. I would add that `isCollectionSubClass` isn't the best name for a field that will be `false` if the field is of type `List`. That definitely had me confused!
