### ISSUE TITLE
Allow the same PID for both pid and factoryPid attribute in @ObjectClassDefinition

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#6042]
When using the following code snippet

```
@ObjectClassDefinition(factoryPid="com.example.MyComponent", pid="com.example.MyComponent")
private static @interface Config {
  @AttributeDefinition(name = "Some setting")
  String setting();
}

```

Bnd  bails out with `Duplicate pid com.example.MyComponent from class ...Config` when generating the metadata (e.g. with `bnd-maven-plugin:bnd-process`). This validation happens in https://github.com/bndtools/bnd/blob/fd296ccec6b251c11666f5ffd94b968ab87e4a39/biz.aQute.bndlib/src/aQute/bnd/metatype/MetatypeAnnotations.java#L146.

According to https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.metatype.html#org.osgi.service.metatype.annotations.ObjectClassDefinition or https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.metatype.html#i1492258 that is not necessarily forbidden.

Although probably an edge case, sometimes the same component class should be used both via configuration factories as well as a singleton configuration (e.g. for migrating purposes from one to the other while staying backwards compatible from the configuration signature)

**Comment by stbischof** [comment]
Not an edge case. Each conponent with a pid is implicit an factory pid 

E.g. the felix http.whiteboard  

> Multiple Servers
It is possible to configure several Http Services, each running on a different port. The first service can be configured as outlined above using the service PID for "org.apache.felix.http". Additional servers can be configured through OSGi factory configurations using "org.apache.felix.http" as the factory PID. The properties for the configuration are outlined as above.

The default server using the PID "org.apache.felix.http" can be disabled by specifying a negative port and then all servers can be used through factory configurations.

**Comment by kwin** [comment]
The problem is the existing persisted configurations with a PID not containing a `~`. But according to https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-deployment an OSGi DS Component is either configured through a PID or a Factory PID (never both).

**Comment by pkriens** [comment]
If you make PR that changes this and it actually works (the creation of the Designate element seems problematic, but you'll find it out by trying.

If you're not intending to make a PR, let's move this to abeyeance?

**Comment by pkriens** [comment]
I think the code is in error. As far as I can see the pid/factoryPid must be checked in separate namespaces. I can't see any reason why using the same pid for factory and singleton would be problematic. 

We're now using the set `pids`to check for the uniqueness, we should add a set `factoryPids` and check factories against that. Or append the factory boolean to the PID?

I'd prefer to close this because I find it an edge case but a PR is ok as long as this issue is closed I am happy :-)

**Comment by kwin** [comment]
@pkriens Please check https://github.com/bndtools/bnd/pull/6052 which does exactly that, i.e. use separate namespaces for factory and non factory pids.
