### ISSUE TITLE
ANSI Console doesn't work with bndtools

### ISSUE THREAD

**Issue by maho7791** [bndtools/bnd#6159]
There is a `bndtools.core.console.AnsiHandler` in bndtools.core, that causes the Eclipse Console to clear randomly when using ANSI coding.

Is this handler still in use?  

Disabling this handler in the plugin.xml  makes the console output look ok.

https://github.com/bndtools/bnd/blob/35d63c0ac6982114f1627a641355a596826eead6/bndtools.core/_plugin.xml#L4

and

https://github.com/bndtools/bnd/blob/master/bndtools.core/src/bndtools/core/console/AnsiHandler.java

The Eclipse console supports ANSI natively.

**Comment by pkriens** [comment]
will you make a PR?

**Comment by maho7791** [comment]
Yes

**Comment by stbischof** [comment]
@maho7791 i have this issue since years. thx for fixing

@laeubi this is what i showed you.

**Comment by stbischof** [comment]
lovely
