### ISSUE TITLE
Issues with bndtools Eclipse dev instance on MacOS Sonoma 14.3+ with temurin JDK > 17.0.09+9

### ISSUE THREAD

**Issue by chrisrueger** [bndtools/bnd#6185]
Based on https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012#issuecomment-2232936903 and comments below.

The problem: new contributors will have a hard time figuring out what's wrong because the dev child eclipse instance shows a broken Ui without buttons etc.

This happens under the following setup:
- MacOS Sonoma 14.5 (23F79)

and any Eclipse Temurin JDK > 17.0.09+9 such as:

- OpenJDK Runtime Environment Temurin-17.0.11+9 
- as well as OpenJDK Runtime Environment Temurin-21.0.3+9 

Then, when launching bndtools Eclipse dev instance via `bndtools.cocoa.macosx.aarch64.bndrun` it looks like this:

<img width="602" alt="image" src="https://github.com/user-attachments/assets/1938aea5-391e-40be-b1cb-8aa3d9a8e9c6">

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/64ca8367-895d-4176-959b-f2901fe2dd1d">

## Workarounds 

- it works e.g. with JDK Temurin 17.0.9+9 or other JDKs as pointed out [here](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012#issuecomment-2233058695).

Relates to https://github.com/bndtools/bnd/issues/5815

**Comment by bjhargrave** [comment]
> I read in https://bnd.discourse.group/t/test-bnd-bndtools-bundle-in-eclipse/358/8 that P2 Repo for Eclipse 4.25 https://bndtools.jfrog.io/ui/native/bnd-build/eclipse/4.25/ is hand crafted.
> 
> I was wondering how this was done. Any docu links?

Yes, I did the hand crafting. I don't have any docs on what I did. It happens so infrequently, I had no confidence what I did for 4.25 would even apply to any future eclipse release.

**Comment by pkriens** [comment]
Wasn't @kriegfrj also intending to something with an update for this?
