### ISSUE TITLE
Gradle plugin does not honor the instruction "-sources: false"

### ISSUE THREAD

**Issue by dmm9** [bndtools/bnd#6230]
My bundle jar, created with the [gradle plugin for bnd workspace build](https://github.com/bndtools/bnd/tree/master/gradle-plugins#gradle-plugins-for-bnd-workspace-builds) had not only one, but two copies of the source code. Adding `-sources: false` to `bnd.bnd` only removes one of the copies of the source code.

My assumption is that the gradle plugin takes the `src` param from bnd.bnd and adds all files to the jar, which is not the standard behavior of gradle. I have created my own workaround by adding build.gradle to the app folder in order to exclude all files, but I think this should be done by the bnd gradle plugin by default...

### Example

With the following repo:

```bash
├── app
│   ├── bnd.bnd
│   ├── build.gradle
│   └── src
│       ├── backend    # java
│       │   ├── package1
│       │   └── ...
│       └── frontend    # typescript
│           ├── node_modules
│           ├── package.json
│           └── ...
├── cnf
├── gradle.properties
├── gredlew
├── gradlew.bat
└── settings.gradle
```
and 
```yml
# bnd.bnd
src: src
-sources: false
...
```

Without -sources:false, the .jar has:
```bash
└── app.jar
    ├── backend     ######## <------- Copy #1 (Java .class files, as expected, but also .xml, README.md, ...)
    ├── frontend    ######## <------- Copy #1 (full copy of frontend)
    │       ├── node_modules
    │       ├── package.json
    │       └── ...
    ├── META-INF
    ├── OSGI-INF
    └── OSGI-OPT
        └── src   ######## <------- Copy #2 (full copy of frontend + backend)
            ├── backend
            └── frontend
```
And with `-sources:false`, only the `OSGI-OPT/src` disappears.

My assumption is that the gradle plugin takes the `src` param and adds all files to the jar, which is not the standard behavior of gradle. I have created my own workaround by adding build.gradle to the app folder in order to exclude all files, but I think this should be done by the bnd gradle plugin by default...

```groovy
// app/build.gradle

processResources {
    include '**/*.class'
}
```

**Comment by pkriens** [comment]
This is outside our control. We do the `OSGI-OPT/src` but the other parts depend on your compiler settings. Compilers generally will copy resource in the source directory. Although they generally will not copy java files.

**Comment by dmm9** [comment]
I doubt it. According to this post, Gradle only includes compiled classes by default:

![grafik](https://github.com/user-attachments/assets/d1192745-79c5-4e28-906b-f9c73f3f3b13)

[Source here](https://discuss.gradle.org/t/how-to-make-gradle-to-include-java-sources/11487/2). Also documented in [Gradle docs](https://docs.gradle.org/current/userguide/java_plugin.html)

So I guess the bnd-gradle-plugin is modifying the gradle task to include more than just the compiled classes. Does it make sense?

**Comment by pkriens** [comment]
That could be right because Eclipse compiler is doing this so to get the same semantics we copy the resources in the source directory. However, this does **not** include the Java sources?

**Comment by pkriens** [comment]
Please reopen if you want to pursue this further. As far as I am concerned I think bnd does the right thing
