### ISSUE TITLE
Creating Bndtools Workspace (Tutorial) does not work without an internet connection

### ISSUE THREAD

**Issue by AhmetBilgin** [bndtools/bnd#6231]
HI,
I'm trying to follow this [tutorial](https://bndtools.org/tutorial.html) to create a _Bndtools workspace_. My developer machine has no direct internet access.
I installed the bndtools pde feature for eclipse via a p2 proxy of the bndtools p2 site in our nexus. This worked fine.
Unfortunately I discovered that in order to create a bndtools workspace, the tooling has to retrieve workspace templates from a github repository. Anything other than some artifact repositories in our nexus is not available on my machine.
The "Use Bndtoools in offline mode"-Option in the preferences did not help, as I can't retrieve a Workspace template to continue.

Now to my questions:
- Is it possible to use the eclipse bndtools without any internet connection?
- Can I redirect the contacted git(hub) repositories to a self hosted clone or something like that?
  - I saw the git configured repos under _[Window] -> [Preferences] ->[Bndtools]_
  - Then in the tabs _Repositories_ and _Workspace Template_

Thanks for your help!

Best regards,
Ahmet

**Comment by pkriens** [comment]
If you point Eclipse to a bnd directory that has the following layout:
```
cnf/
  build.bnd
```
then it should be happy.

For projects, there should be a choice for an empty project that does not require an internet template.

**Comment by pkriens** [comment]
Please reopen when you feel that more needs to be done (and provide a PR? :-)
