### ISSUE TITLE
Gradle Project fails to configure with Kotlin >= 1.7.0

### ISSUE THREAD

**Issue by maxemann96** [bndtools/bnd#6264]
## Error description
Kotlin compile tasks no longer inherit the Gradle `AbstractCompile` task. They inherit only the `DefaultTask` (Directly taken from the release changelog from [1.7.0](https://kotlinlang.org/docs/whatsnew17.html#changes-in-compile-tasks)).

## Error appearance
The error appears in the gradle configuration phase (so for any gradle subcommand):
```
A problem occurred configuring project ':my_awesome_project'.
> The task 'compileKotlin' (org.jetbrains.kotlin.gradle.tasks.KotlinCompile) is not a subclass of the given type (org.gradle.api.tasks.compile.AbstractCompile).
```

## Where to find the erroneous code
See Line 321ff [BndPlugin.java](https://github.com/bndtools/bnd/blob/master/gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java#L321).

## Known workaround
Sadly not

**Comment by pkriens** [comment]
@bjhargrave any idea?

**Comment by bjhargrave** [comment]
That looks like a lot of work on our part We just assume all compile tasks are AbstractCompileTask and use methods defined on AbstractCompileTask. We would have to write special code using reflection to configure Kotlin compile tasks. Nice job Kotlin...

**Comment by pkriens** [comment]
thx. I remember that the Kotlin architecture also seemed designed to not let bnd use it :-( They would not create the byte codes on the fly.

**Comment by pkriens** [comment]
@maxemann96 I seem to have closed accidentally is as not planned but you're of course free to submit a PR or raise an issue with Kotlin.

**Comment by maxemann96** [comment]
Thanks for your replies. Originally I just wanted to contribute some Kotlin implementations to another open source project (currently consisting only of Java modules). I had not contributed to this one yet. It uses BND and I stumbled upon this problem.

At the moment my time for open source projects unfortunately does not allow me to think about a new open source project, a completely new build tool and about an issue at Kotlin itself. So I won't open a MR here or a issue at Kotlin, sorry :/
