### ISSUE TITLE
Expose references towards java.lang classes with xref

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#6296]
When using [xref](https://bnd.bndtools.org/commands/xref.html) e.g. with options `-cf` there is no references towards classes below `java.lang.*` exposed [#2507].

I need this to debug why an import-package header to `java.lang.constant` is being generated by `bnd` despite compiling with [`--release 11`](https://docs.oracle.com/en/java/javase/11/tools/javac.html#GUID-AEEC9F07-CB49-4E96-8BC7-BCC2C7F725C9__GUID-D343F6B4-3FDD-43A8-AD24-43DD70214471).
The package [`java.lang.constant`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/constant/package-summary.html) however was only added in Java 12.

I tried with 

```
bnd version                                                 
7.0.0.202310060912
```

**Comment by pkriens** [comment]
I was in a good mood: https://github.com/bndtools/bnd/pull/6297
