### ISSUE TITLE
[New Create new Workspace] might create "no" workspace

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#6300]
If I use the mechanism as follows:

![image](https://github.com/user-attachments/assets/9b63e141-3535-4c59-b34c-07bd67f600dd)

a cnf folder is created but the build.bnd is missing and nothing is imported. This gives a bad user experience.  I had to also mark the gradle fragment.

Proposed solution:
After the fragments are applied, we should check if a build.bnd exists and if the fragment does not come with one and non already exists, we should create an empty one.

**Comment by chrisrueger** [comment]
Seems to be related to https://github.com/bndtools/bnd/issues/6302#issuecomment-2380115998

I tested with and without "Update current Eclipse Workspace"

1. With "Update current Eclipse Workspace" checked

<img width="586" alt="image" src="https://github.com/user-attachments/assets/d1ee0094-f536-4b3d-9bbc-584eef035f7b">

It looks like nothing is happening, but it is there. I just needed to import via **File / Import / Existing Bnd Workspace** and choose my current workspace (not intuitive)

Maybe this is a bug and the import should be done automatically.

2. Without "Update current Eclipse Workspace" checked

Here same thing. The path I choose for location , I need to import afterwards.
