### ISSUE TITLE
Problem on 'osgi.service; (objectClass=org.bndtools.versioncontrol.ignores.manager.api.VersionControlIgnoresPlugin)' but it could not be found

### ISSUE THREAD

**Issue by microwan** [bndtools/bnd#6305]
Im trying to build an eclipse plugin based on org.eclipse.pde.core 
there is a dependency on org.bndtools.versioncontrol.ignores.manager 

my continuous integration is blocked due to this version

[ERROR] Cannot resolve dependencies of project com.st.stellar.core:com.st.stellar.ui.templates:eclipse-plugin:1.1.0-SNAPSHOT
[ERROR]  with context {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true}
[ERROR]   Software being installed: com.st.stellar.ui.templates 1.1.0.qualifier
[ERROR]   Missing requirement: org.bndtools.versioncontrol.ignores.manager 
7.0.0.202310060912 requires 'osgi.service; (objectClass=org.bndtools.versioncontrol.ignores.manager.api.VersionControlIgnoresPlugin)' but it could not be found
[ERROR]   Cannot satisfy dependency: com.st.stellar.ui.templates 1.1.0.qualifier depends on: osgi.bundle; org.bndtools.versioncontrol.ignores.manager 
7.0.0: See log for details

Could you help me for this issue ?

   Best Regards

                          Erwan

**Comment by chrisrueger** [comment]
Seems you need to add a dependency to your build: https://mvnrepository.com/artifact/org.bndtools/org.bndtools.versioncontrol.ignores.manager/7.0.0

**Comment by microwan** [comment]
By adding in pom.xml (source), Build in CI is ok 

`<dependencies>
		<dependency>
			<groupId>org.bndtools</groupId>
			<artifactId>org.bndtools.versioncontrol.ignores.plugin.git</artifactId>
			<version>7.0.0</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
		<dependency>
			<groupId>org.bndtools</groupId>
			<artifactId>org.bndtools.headless.build.plugin.gradle</artifactId>
			<version>7.0.0</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
	</dependencies>`

It seems to have an issue in bndtools as a dependency in pde.core

**Comment by chrisrueger** [comment]
Ok, I don't think there is much that can be done from bnd here. Maybe consider asking the [pde.core team](https://github.com/eclipse-pde/eclipse.pde/issues)
