### ISSUE TITLE
make baselining work in standalone bnd builds

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#632]
the goal is to make it possible to baseline from non-workspace builds (i.e. maven-bundle-plugin, gradle plugins, etc. any builder which uses bnd under the hood).

**Comment by rotty3000** [comment]
I went ahead and made a couple small changes which I believe enable a very simple usage of baseline and a companion simple deployer to go with it.

With these two changes no workspace is required and it becomes very simple to implement baseline and release to repo in any build tool without a workspace setup.

An example usage is:

```.java
BaselineProcessor baselineProcessor = new BaselineProcessor();

// set your properties
Properties properties = baselineProcessor.getProperties();
properties.putAll(...);

// the jar file you want to baseline
File newerJarFile = ...
Jar newerJar = new Jar(newerJarFile);

// find the older version in configured repos
Jar olderJar = baselineProcessor.getBaselineJar();

// do baseline
Baseline baseline = new Baseline(baselineProcessor, new DiffPluginImpl());
Set<Info> infos = baseline.baseline(newerJar, olderJar, null);
```

Lastly, you probably want to put released artifacts into the repo in order to do future baselines:

```.java
BaselineProcessor processor = new BaselineProcessor();

// set your properties
Properties properties = processor.getProperties();
properties.putAll(...);

// deploy to configured releaserepo
Deployer deployer = new Deployer(processor);
deployer.deploy(newerJarFile);
```

**Comment by bjhargrave** [comment]
We now have baseline support for maven and non-workspace gradle.
