### ISSUE TITLE
Unable to build biz.aQute.bnd.annotation

### ISSUE THREAD

**Issue by SamratDawn** [bndtools/bnd#6335]
I am trying to build biz.aQute.bnd.annotation but the gradlew command does not work somehow. Maybe there is something wrong with the way I am using the build command.

Version used- 5.3.0 REL and DEV
Build Command used- ./gradlew build
Source URL used- https://github.com/bndtools/bnd/tree/master

**Comment by pkriens** [comment]
Closing this until you can provide more details.
