### ISSUE TITLE
Startlevel in output of bnd-resolver-maven-plugin does not include/incorporate startlevels from runbundles decorator

### ISSUE THREAD

**Issue by glimmerveen** [bndtools/bnd#6364]
I noticed in a project that any startlevel set using the `-runbundles+` decorator does not show-up in the `-runbundles` outputted by the `bnd-resolver-maven-plugin`. Note that if the bndrun _also_ includes a `-runstartlevel` instruction, then the output of bnd-resolver-maven-plugin will include startlevel attribute, but only with the value(s) following from the `-runstartlevel` instruction, and **not** from the `-runbundles+` decoration.

When a bndrun file that uses a `-runstartlevel` instruction and some specific startlevels assigned using `-runbundles+` decoration is generated into an executable JAR, then the resulting startlevels used within that executable JAR is the expected combination of both.

Is it to be expected that the output of the `bnd-resolver-maven-plugin` with respect to startlevel attributes is aligned with the effective output of the `bnd-exporter-maven-plugin`?

**Comment by pkriens** [comment]
Agree.

Can you provide a PR?

**Comment by pkriens** [comment]
This will be closed if no reply ...

**Comment by glimmerveen** [comment]
> This will be closed if no reply ...

Sorry for not responding to your initial response. I am willing to providing a PR for this, but haven't gotten around to properly dive into this.

**Comment by pkriens** [comment]
ok, then we keep it open ... thanks.

**Comment by chrisrueger** [comment]
Closed via https://github.com/bndtools/bnd/pull/6407
