### ISSUE TITLE
`bnd-testing-maven-plugin` fails with Java 24

### ISSUE THREAD

**Issue by scordio** [bndtools/bnd#6370]
In AssertJ, we use the `bnd-testing-maven-plugin` for [OSGi integration tests](https://github.com/assertj/assertj/blob/97cc0f866c31a76dc705fdec0d9bdcad1cd640b9/assertj-tests/assertj-integration-tests/assertj-core-osgi/pom.xml#L101-L130), and the plugin started failing today when running on [Java 24](https://github.com/assertj/assertj/blob/97cc0f866c31a76dc705fdec0d9bdcad1cd640b9/.github/workflows/cross-version.yml#L19-L24):

```
INFO] --- bnd-testing:7.0.0:testing (osgi-integration-testing) @ assertj-core-osgi ---
[INFO] Matching glob *
[INFO] Testing /home/runner/work/assertj/assertj/assertj-tests/assertj-integration-tests/assertj-core-osgi/target/verify.bndrun:
[INFO] Bnd inferred -runee: JavaSE-21
! Unexpected error in the run body: Setting a system-wide Policy object is not supported
java.lang.UnsupportedOperationException: Setting a system-wide Policy object is not supported
	at java.base/java.security.Policy.setPolicy(Policy.java:114)
	at aQute.launcher.Launcher.activate(Launcher.java:493)
	at aQute.launcher.Launcher.launch(Launcher.java:403)
	at aQute.launcher.Launcher.run(Launcher.java:185)
	at aQute.launcher.Launcher.main(Launcher.java:161)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
java.lang.UnsupportedOperationException: Setting a system-wide Policy object is not supported
	at java.base/java.security.Policy.setPolicy(Policy.java:114)
	at aQute.launcher.Launcher.activate(Launcher.java:493)
	at aQute.launcher.Launcher.launch(Launcher.java:403)
	at aQute.launcher.Launcher.run(Launcher.java:185)
	at aQute.launcher.Launcher.main(Launcher.java:161)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
[INFO] 127 Error(s)
[ERROR] Error   : Exit code remote process 127: /opt/hostedtoolcache/Java_jdkfile_jdk/24/x64/bin/java -cp /home/runner/work/assertj/assertj/assertj-tests/assertj-integration-tests/assertj-core-osgi/target/test/tmp/testing/verify/cnf/cache/7.0.0/bnd-cache/biz.aQute.launcher/biz.aQute.launcher.pre.jar -Dlauncher.properties=/home/runner/work/assertj/assertj/assertj-tests/assertj-integration-tests/assertj-core-osgi/target/test/tmp/testing/verify/generated/launch13560035249624281069.properties -ea -Dlauncher.runpath=/home/runner/.m2/repository/org/eclipse/platform/org.eclipse.osgi/3.21.0/org.eclipse.osgi-3.21.0.jar,/home/runner/work/assertj/assertj/assertj-tests/assertj-integration-tests/assertj-core-osgi/target/test/tmp/testing/verify/cnf/cache/7.0.0/bnd-cache/biz.aQute.launcher/biz.aQute.launcher-7.0.0.jar aQute.launcher.pre.EmbeddedLauncher
```

Source: https://github.com/assertj/assertj/actions/runs/11846157794/job/33013148936#step:4:8886

Do you know what the root cause could be?

**Comment by stbischof** [comment]
Code:

https://github.com/bndtools/bnd/blob/b2deb7f91312a4d37f0504d8cfd904847ca028a2/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L493

I think this is related to:

https://openjdk.org/jeps/486

**Comment by scordio** [comment]
Thanks for the quick feedback, @stbischof!

> The fastest solution would be to some RunProperties ad describes in the jep. '-D.....'
> 
> https://github.com/assertj/assertj/blob/97cc0f866c31a76dc705fdec0d9bdcad1cd640b9/assertj-tests/assertj-integration-tests/assertj-core-osgi/verify.bndrun#L16

Could you please elaborate on the workaround you have in mind? I didn't fully understand what you meant and couldn't figure it out by going through the JEP.

**Comment by chrisrueger** [comment]
Can't just remove that line? 

https://github.com/bndtools/bnd/blob/b2deb7f91312a4d37f0504d8cfd904847ca028a2/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L493

bnd is officially on Java17 and Policy deprecated for removal. 

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/68e793fd-e9bc-4e29-b615-445bea19c7c5">

@pkriens ?

**Comment by timothyjward** [comment]
> @timothyjward this tests are there because of osgi-test

It’s good that we have these tests, but in this case it’s very much the maven plugin that’s the issue. Everyone’s tests will be broken on Java 24. 

> Can't just remove that line?

I agree with @chrisrueger - we should also add Java 24 to the CI build matrix and see what else breaks.

**Comment by chrisrueger** [comment]
I created https://github.com/bndtools/bnd/pull/6371 which is currently building.

@timothyjward 
> I agree with @chrisrueger - we should also add Java 24 to the CI build matrix and see what else breaks.

Unfortunatelly Java 24 seems still early access and it didn't work with Github Actions (seems 23 is the latest). If anybody can tell me how to add it, I can do it.
In the meantime I added Java 23 in this PR, to see how at least that behaves.

**Comment by timothyjward** [comment]
> Unfortunatelly Java 24 seems still early access and it didn't work with Github Actions (seems 23 is the latest). If anybody can tell me how to add it, I can do it.

According to [the docs](https://github.com/actions/setup-java?tab=readme-ov-file#supported-version-syntax) it should be `24-ea`

**Comment by stbischof** [comment]
https://github.com/assertj/assertj/blob/3.x/.github%2Fworkflows%2Fcross-version.yml

**Comment by chrisrueger** [comment]
> According to [the docs](https://github.com/actions/setup-java?tab=readme-ov-file#supported-version-syntax) it should be `24-ea`

Thanks. Looks like this worked and it is using Java 24 now.
Unfortunatelly now it fails later: https://github.com/bndtools/bnd/actions/runs/11859401489/job/33052249683?pr=6371

```
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 68
> Unsupported class file major version 68
```

Hmm will look into it later.

**Comment by timothyjward** [comment]
> Maybe gradle is [not Java 24 ready](https://docs.gradle.org/current/userguide/compatibility.html) yet?

Certainly possible, but I’m sure that other parts of bnd (e.g. the analyzer) will need some tweaks too.

**Comment by chrisrueger** [comment]
The Exception `java.lang.UnsupportedOperationException: Setting a system-wide Policy object is not supported` should be solved by https://github.com/bndtools/bnd/pull/6371

**Comment by scordio** [comment]
Hi @chrisrueger, do you think this change will be released before Java 24 GA, due in March?

**Comment by chrisrueger** [comment]
@scordio I don't know, but I think so. @pkriens ?

**Comment by pkriens** [comment]
no, I do not see a release before March. Maybe Before mid April

**Comment by scordio** [comment]
Hi all, can the fix be released?

Now that we are using Java 25 for the build, we have to keep the OSGi integration tests disabled.

**Comment by chrisrueger** [comment]
@scordio we are working on doing a release candidate this week.

**Comment by scordio** [comment]
Thanks!

**Comment by chrisrueger** [comment]
@scordio bnd 7.2.0-RC1 is ready for testing https://bnd.discourse.group/t/bnd-bndtools-7-2-0-rc1-is-ready-for-testing/542

**Comment by scordio** [comment]
Hi @chrisrueger, I upgraded to 7.2.0-RC1 at assertj/assertj#4041, but the build seems stuck after this message:

```
[INFO] --- bnd-testing:7.2.0-RC1:testing (osgi-integration-testing) @ assertj-core-osgi ---
[INFO] Matching glob *
[INFO] Testing /home/runner/work/assertj/assertj/assertj-tests/assertj-integration-tests/assertj-core-osgi/target/verify.bndrun:
[INFO] Bnd inferred -runee: JavaSE-25
[INFO] [ConnectionSettings] Read from file: /home/runner/.m2/settings.xml (See https://bnd.bndtools.org/instructions/connection_settings.html for more information)
[INFO] Resolved all Dependencies for org.assertj:assertj-core-osgi:jar:4.0.0-SNAPSHOT. Checked: 10, Skipped(no need to revisit): 0, Failed: 0, Resulting Dependencies: 10
[INFO] Resolved all Dependencies for org.assertj:assertj-core-osgi:jar:4.0.0-SNAPSHOT. Checked: 63, Skipped(no need to revisit): 0, Failed: 0, Resulting Dependencies: 63
! could not resolve the bundles: [biz.aQute.tester.junit-platform-7.2.0.202511281037-RC1 org.osgi.framework.BundleException: Could not resolve module: biz.aQute.tester.junit-platform [10]
  Unresolved requirement: Import-Package: org.junit.platform.commons; version="[1.10.1,1.13.0)"
]
! Failed to start bundle biz.aQute.tester.junit-platform-7.2.0.202511281037-RC1, exception Could not resolve module: biz.aQute.tester.junit-platform [10]
  Unresolved requirement: Import-Package: org.junit.platform.commons; version="[1.10.1,1.13.0)"
org.osgi.framework.BundleException: Could not resolve module: biz.aQute.tester.junit-platform [10]
  Unresolved requirement: Import-Package: org.junit.platform.commons; version="[1.10.1,1.13.0)"
	at org.eclipse.osgi.container.Module.start(Module.java:495)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:471)
	at aQute.launcher.Launcher.start(Launcher.java:704)
	at aQute.launcher.Launcher.startBundles(Launcher.java:684)
	at aQute.launcher.Launcher.activate(Launcher.java:590)
	at aQute.launcher.Launcher.launch(Launcher.java:403)
	at aQute.launcher.Launcher.run(Launcher.java:185)
	at aQute.launcher.Launcher.main(Launcher.java:161)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:169)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:134)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:51)
```

From https://github.com/assertj/assertj/actions/runs/19767775155/job/56644676345?pr=4041

I tried the same locally, and it got stuck, too.
