### ISSUE TITLE
No documentation page for `-versionpolicy` instruction

### ISSUE THREAD

**Issue by bric3** [bndtools/bnd#6372]
I was reading this page (https://bnd.bndtools.org/heads/import_package.html) and tried to navigate to the version policy instruction page (https://bnd.bndtools.org/instructions/versionpolicy.html), but this lands on a 404.

I suppose the doc is simple, however having a description of the default format would be nice.

I have this in mockito `-versionpolicy: [${version;==;${@}},${version;+;${@}})`, and I think it means something about a range from the current version to the next.

**Comment by chrisrueger** [comment]
@bric3 there is https://bnd.bndtools.org/instructions/consumer_policy.html and https://bnd.bndtools.org/instructions/provider_policy.html

I cannot find a versionpolicy.md in the source anymore, so maybe it is outdated.

Do these two links answer your questions? If yes, I could update the docs to link to those two links instead of the 404 one.

**Comment by bric3** [comment]
@chrisrueger I saw these links, that say I don't really now how much they apply there. 

I'm not well versed in OSGI (so I'm not sure at all of what write there), they all look fitting in a way like section 10.5 in https://bnd.bndtools.org/chapters/170-versioning.html but I feel this option is about conmfguring a _default_ for the import package directive as the doc page indicates:

> The import package doc That is, when the exporter is `1.2.3.build123`, then the import version will be `1.2`. If a specific version (range) is specified, this will override any found version. This default an be overridden with the [`-versionpolicy`](https://bnd.bndtools.org/instructions/versionpolicy.html) instruction.

Also I'm not sure how to read the range `[${version;==;${@}},${version;+;${@}})` from range documentation page because the syntax is completely different.

**Comment by chrisrueger** [comment]
I believe this is also an important link for the version / versionmask macro: 
https://bnd.bndtools.org/macros/version.html
