### ISSUE TITLE
Bnd Run File Editor: “Resolve” button stopped working in Maven workspaces since Bndtools 7.1.0

### ISSUE THREAD

**Issue by sad-poet** [bndtools/bnd#6380]
Starting with Bndtools 7.1.0, opening a *.bndrun file in a Maven-only workspace and clicking the *Resolve* button results in a NullPointerException (see below).

The problem is not reproduced when using Bndtools 7.0.0.

# Environment

* Bndtools 7.1.0.202411251545 (installed from https://bndtools.org/bndtools.p2.repo/7.1.0/)
  * `Git-Descriptor: 7.0.0.DEV-1660-g47e504d78`
  * `Git-SHA: 47e504d7881ba466703c55a8dca7b0578561582d`
* Eclipse Temurin JDK 21.0.5
* Eclipse IDE for Java Developers 2024-09
* Eclipse Java Development Tools 3.19.600.v20240903-0240
* Eclipse PDE is not installed
* Apache Maven 3.9.9
* bnd-maven-plugin 7.1.0
* Devuan GNU+Linux codename Ceres (corresponding to Debian sid/unstable)

It was also possible to reproduce the error using Eclipse 2024-12 preview version, and on Windows 11.

# Steps to reproduce

1. Install Eclipse IDE (from Eclipse Installer) and latest Bndtools (from Eclipse Marketplace Client), including Bndtools m2e integration feature.
2. Clone the example project and open it in Eclipse IDE: https://github.com/sad-poet/bndtools-resolve-npe-reproducer
4. Open app/app.bndrun file in Bnd Run File Editor.
5. Click Resolve button.

# Expected result

There should be no error. A *Resolution Results* window should open, displaying the required resources used to create the Run Bundles list.

# Actual result

The following error message is displayed in the *Resolution Results* window:

```
Exception during resolution.
java.lang.NullPointerException: Cannot invoke "aQute.bnd.build.Project.get(String)" because "project" is null
	at biz.aQute.resolve.RunResolution.resolve(RunResolution.java:101)
	at org.bndtools.core.resolve.ResolveOperation.lambda$run$0(ResolveOperation.java:62)
	at org.bndtools.core.resolve.ResolveOperation.coordinate(ResolveOperation.java:102)
	at org.bndtools.core.resolve.ResolveOperation.run(ResolveOperation.java:52)
	at org.bndtools.core.resolve.ResolveJob.run(ResolveJob.java:89)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

![screenshot](https://github.com/user-attachments/assets/f9db767a-2a59-43c6-bc43-860129645da9)

No new errors appear in the Eclipse’s *Error Log* view.

The problem persists in all Maven projects that use bnd-maven-plugin. I was also able to reproduce the error when trying to resolve the app/app.bndrun file in a different example project found at https://github.com/fipro78/osgi-jakartars/tree/main/jakartars.

# Workaround

If bnd-resolver-maven-plugin is set up, the command line `mvn bnd-resolver:resolve` can be used and works as expected.

**Comment by chrisrueger** [comment]
Thanks @sad-poet for the detailed report. Seems this is related to:

https://github.com/bndtools/bnd/commit/cd21a96bebbaa031b4511dd1ab7748f8cd57f1cd#diff-38351aedb1322e930095be9f6746dd4d6aecc5fc660f2656cebe14f3076ed93dR100-R107

I see some options:
- use `actualProperties` instead of `project` (assuming this this is not null)
- or check `project` for null (but this might be incorrect too, because then the `-resolve` property is ignored)

Or find out why `project` is `null` in a m2e project. I assume this has something to do with that it is a maven project and not a bnd workspace model project.  

One caller is  

https://github.com/bndtools/bnd/commit/fbc917cbd192b3becec226b401991eb254932eff#diff-a4b407ab5fd64c74fc1c5decc823f997e3ba96bc4aefda5829aa7153d52d9ba9L57-R60

```
Project run = model.getOwner(Project.class)
					.orElse(null);
				RunResolution resolution = RunResolution.resolve(run,
					model.getProperties(),
					operationCallbacks, logger);
```

which in 7.0.0 was 

`RunResolution resolution = RunResolution.resolve(model.getProject(), model.getProperties()`

@pkriens and @juergen-albert  thoughts?

**Comment by chrisrueger** [comment]
@sad-poet I pushed PR https://github.com/bndtools/bnd/pull/6381 Are you able to test if this fixes your problem?

Depending on the discussion, we could also try merging it to master, and you could use the resulting SNAPSHOT build - if that makes testing easier (and if @pkriens agrees).

**Comment by chrisrueger** [comment]
@sad-poet Thanks too for your quick test. This is very helpful. 
Some quick thoughts:

- It seems my "fix" fixed the NPE at the place it was happening in your initial bug report
- BUT: now it just happens later

![image](https://github.com/user-attachments/assets/b6e5d0bc-3cae-4d37-9c79-a854a0f6b558)

I think it comes down to the question: Why is `project` null suddenly?

I think we need to investigate in the code place I referenced earlier:

https://github.com/bndtools/bnd/commit/fbc917cbd192b3becec226b401991eb254932eff#diff-a4b407ab5fd64c74fc1c5decc823f997e3ba96bc4aefda5829aa7153d52d9ba9L57-R60 

```
Project run = model.getOwner(Project.class)
					.orElse(null);
				RunResolution resolution = RunResolution.resolve(run,
					model.getProperties(),
					operationCallbacks, logger);
```

which in 7.0.0 was

`RunResolution resolution = RunResolution.resolve(model.getProject(), model.getProperties()`

This was related to change to BndEditModel in PR https://github.com/bndtools/bnd/pull/6082

Maybe in the M2E case, something is different than in the Bnd Workspace Model.

**Comment by pkriens** [comment]
I'll take a look ...

**Comment by markus7017** [comment]
Has the fix already been merged, because I see the same problem with a fresh IDE install

**Comment by chrisrueger** [comment]
> Has the fix already been merged, because I see the same problem with a fresh IDE install

https://github.com/bndtools/bnd/pull/6382 has been merged to master branch on Dec 2, 2024. 
That means it is not part of bndtools 7.1.0 which was released in November. 

But it is in the latest 7.2.0 SNAPSHOT (basically the master build) which you could get via [Update Site](https://bndtools.org/installation.html#update-site).
**Eclipse Update Site**: https://bndtools.jfrog.io/bndtools/update-snapshot 

<img width="784" alt="Image" src="https://github.com/user-attachments/assets/a07157f2-af92-4931-b1c6-eda25f8a2053" />
