### ISSUE TITLE
Maven bnd:7.1.0:bnd-process. NPE after migrating from 7.0.0

### ISSUE THREAD

**Issue by dpishchukhin** [bndtools/bnd#6387]
After updating the maven plugin version to the version 7.1.0, there is an NPE 

```
Exception: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "map" is null
	at aQute.bnd.osgi.metainf.MetaInfService.getServiceFiles(MetaInfService.java:63)
	at aQute.bnd.osgi.metainf.MetaInfServiceParser.analyzeJar(MetaInfServiceParser.java:55)
	at aQute.bnd.osgi.Analyzer.lambda$doPlugins$21(Analyzer.java:992)
	at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:1024)
	at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:988)
        .....
```

**Comment by chrisrueger** [comment]
I will have a look.

**Comment by chrisrueger** [comment]
I almost have a fix ready. I think that happens where there is a jar with a `META-INF/services/subfolder` BUT META-INF/services itself does not contain any files.
Could you maybe confirm? @

**Comment by dpishchukhin** [comment]
> I almost have a fix ready. I think that happens where there is a jar with a `META-INF/services/subfolder` BUT META-INF/services itself does not contain any files. Could you maybe confirm? @dpishchukhin

Yes, that is correct.

**Comment by chrisrueger** [comment]
> > I almost have a fix ready. I think that happens where there is a jar with a `META-INF/services/subfolder` BUT META-INF/services itself does not contain any files. Could you maybe confirm? @dpishchukhin
> 
> Yes, that is correct.

Could you give some more details about this specific layout? I could not find anything in the Java SPI specification, that subfolders in META-INF/services are allowed (or considered by the SPI lookup mechanism). 

Just want to find out more, about this specific use case.

**Comment by dpishchukhin** [comment]
you can check [Karaf Shell Commands](https://github.com/apache/karaf/tree/main/shell/commands/src/main/resources)

**Comment by chrisrueger** [comment]
@pkriens While my PR https://github.com/bndtools/bnd/pull/6388 fixes the NPE, the question would be what to do with Subfolders inside `META-INF/services` like in the example of [Karaf Shell Commands](https://github.com/apache/karaf/tree/main/shell/commands/src/main/resources)

which has nested subfolders (`/META-INF/services/org/apache/karaf/shell/commands`) where [/commands](https://github.com/apache/karaf/blob/main/shell/commands/src/main/resources/META-INF/services/org/apache/karaf/shell/commands) seems to be the file containing the references to the Implementations.

Currently files in subfolders are ignored by our `MetaInfServices.java`.

... and as far as I could find out, also ignored by Java. 
So maybe that is a Karaf-specific thing? Should we just ignored it? (but of course prevent the NPE like #6388 )

References: 
- https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html
- https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html
