### ISSUE TITLE
Issue trying to wrap non-OSGi-bundle graalvm.polyglot

### ISSUE THREAD

**Issue by mikerumpf** [bndtools/bnd#6400]
I tried to wrap the non-OSGi-bundle graalvm.polyglot via bnd.

However, trying to do this, I get the following error:
"Your bnd file contains a header called 'Name'. This interferes with the manifest name section."

That's actually true, since the original manifest contains a name entry.

Is there a specific reason for the check in
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L1188

Or is this an issue with bnd? Maybe the graalvm guys should not use the name tag. However can bnd really make that assumption for random 3rd party jars?

The dependency we used is:
```
<!-- https://mvnrepository.com/artifact/org.graalvm.polyglot/polyglot -->
<dependency>
    <groupId>org.graalvm.polyglot</groupId>
    <artifactId>polyglot</artifactId>
    <version>24.1.1</version>
</dependency>
```

**Comment by pkriens** [comment]
In your bnd file you can add:

       -fixupmessages "Your bnd file contains a header called 'Name'."

This will ignore the error

**Comment by pkriens** [comment]
Please close this issue if this works for you

**Comment by mikerumpf** [comment]
Thank you for the help.
