### ISSUE TITLE
Allow suggesting namespace version for (spec) metatype annotations

### ISSUE THREAD

**Issue by djencks** [bndtools/bnd#675]
Until 1.3 compliant metatype implementations become available it may be useful to suggest that bnd generate 1.2 namespace metatype resources from the spec annotations.  AFAIK this involves:
- a "marker" ocd with no ad's must be 1.3
- "Character" type is "Char" in 1.2.

I don't know of any reason to try to generate pre-1.2 documents.
This will be turned on by
-metatypeannotations-flags: preferV12

**Comment by bjhargrave** [comment]
@djencks What is the status with this issue? Fixed already?

**Comment by bjhargrave** [comment]
Closing. Reopen if this is still an active issue.

**Comment by kwin** [comment]
For me with BND 3.0 metatype resources always get the namespace 1.3. Is this an oversight?
Also the source at https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/metatype/DesignateDef.java#L31 will always create the 1.3 namespace!

**Comment by djencks** [comment]
I am fine with the current behavior.  If Peter and BJ lean on me enough I’ll consider changing it as long as it is possible to specify a higher namespace than the minimum.

david jencks

**Comment by pkriens** [comment]
Consider yourself leaned upon! :-)

I think we should try to use the minimum to not force people to update their metatype impl. immediately. Feel free to allow a higher version to be specified. Though I am not sure why, would this not be simply done with your runbundles?

**Comment by djencks** [comment]
AFAIK all the existing metatype impls are happy with 1.3 namespace and use of CHARACTER rather than CHAR even though they claim to support only 1.2.  So I don’t think the current behavior actually forces anyone to change their metatype impl.  How would runbundles affect the metatype xml generation?

david jencks

**Comment by pkriens** [comment]
It would not influence the generation but it would decide the implementation that is used. 

Whatever, I trust you :-)

**Comment by kwin** [comment]
I use Apache Felix Metatype 1.0.10 (shipped with a commercial product) which I cannot easily upgrade, therefore generating Metatypes with 1.3 NS is a problem for me. Only Felix Metatype 1.1 supports NS 1.3.

**Comment by djencks** [comment]
OK, I’ll see what I can come up with.

david jencks

**Comment by bjhargrave** [comment]
Well that is 2 versions old of Metatype spec. The new Metatype annotations were introduced by the Metatype 1.3 spec. Perhaps it is a bit of a stretch to require that the new 1.3 annotation support all the way back to Metatype 1.1 spec resources?

Metatype 1.2 introduced the `AD` type `Password`, made `pid` attribute on `designate` element optional, and allowed multiple `Icon` elements. To supports generating Metatype 1.1 resources from Metatype 1.3 annotations would require these verifications as well as the changes for Metatype 1.3: `AD` elements are optional, and the rename of `AD` type `Char` to `Character`.

**Comment by kwin** [comment]
Actually Felix Metatype 1.0.10 is Metatype 1.2 compliant (https://issues.apache.org/jira/browse/FELIX/fixforversion/12314144/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel)

**Comment by kwin** [comment]
Could someone with enough karma remove the Milestone 3.0 and reopen this issue?

**Comment by bjhargrave** [comment]
I would just open a new issue with a description of the current problem.

On Tue, Nov 3, 2015 at 18:46 Konrad Windszus <notifications@github.com>
wrote:

> Could someone with enough karma remove the Milestone 3.0 and reopen this
> issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bnd/issues/675#issuecomment-153430280>.
>
-- 
-- 
BJ
