### ISSUE TITLE
Update DS anno processing for field injection

### ISSUE THREAD

**Issue by djencks** [bndtools/bnd#688]
Update the DS annotation processing to generate correct xml from the field-injection-related annotations and the other recent annotation updates.

**Comment by djencks** [comment]
Implemented in pull request https://github.com/bndtools/bnd/pull/803 with hacky generic signature "parsing".  This seems to work but I'm not about to write a better parser when we can copy the one from apache Harmony.  Comment soon or I will merge....

**Comment by bjhargrave** [comment]
I saw the PR and added a couple of line comments.

**Comment by djencks** [comment]
Replaced by https://github.com/bndtools/bnd/pull/804 incorporating BJ's comments and pulling in R6 core and DS for the tests.

**Comment by bjhargrave** [comment]
You know you can just `git push --force` to the branch on your fork to update the PR. You don't need to delete the old PR and create a new one.

**Comment by bjhargrave** [comment]
I made a number of code comments on the #804 changes.
