### ISSUE TITLE
Package not imported when a sub-package is contained in the bundle

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#708]
if a bundle has a.b.c but imports a.b then bnd cannot find the version of a.b because the scanning of a.b.c already has set the information for a.b to "nothing".

The learnPackage() method must be adapted so that "empty" package do not occupy a position

This was diagnosed by Balázs Zsoldos <balazs.zsoldos@everit.biz>

**Comment by balazs-zsoldos** [comment]
@bjhargrave When do you plan to release 2.4.1?

**Comment by bjhargrave** [comment]
We are going to discuss this Friday. I hope it will be released next week.

**Comment by bjhargrave** [comment]
The fix has introduced a regression into bnd. See https://github.com/bndtools/bndtools/issues/1000. Reopening.

**Comment by bjhargrave** [comment]
It seems this fix depends on previous changes post 2.4.0.REL and cannot be cherry-picked alone into next for a maintenance release. So, @balazs-zsoldos, we will not have a fix for this bug in 2.4.1 unless @pkriens will craft a new fix specifically for the next branch.

**Comment by bjhargrave** [comment]
Closing. This fix will not be in 2.4.1. 3.0 will contain this fix.
