### ISSUE TITLE
Bndrun configuration trips up if you add an empty run property

### ISSUE THREAD

**Issue by m4rr5** [bndtools/bnd#709]
In any Bndrun configuration, if you, on the "Run" tab, add a new run property and leave the key and value empty, it will generate sourcecode that looks like this:

    -runproperties:  \
        =

The launcher subsequently cannot parse that statement anymore and the whole framework fails to launch when you try to run it. I think we should catch this case in the Bndtools UI and not try to generate a property if key and value are empty.

Note: I've moved this issue from Bndtools to Bnd, it was originally issue https://github.com/bndtools/bndtools/issues/955 but the fix should happen in Bnd.

**Comment by pkriens** [comment]
How's this going?

**Comment by bjhargrave** [comment]
I suspect this is no longer an issue given that a new bnd file parser with error checking was added.
