### ISSUE TITLE
Need a way for Ant build to not fail if integration test failure only.

### ISSUE THREAD

**Issue by dhumeniuk** [bndtools/bnd#719]
See for initial discussion: https://groups.google.com/forum/#!topic/bndtools-users/GOIvlJ3zKXA

Currently either an Ant or Gradle build will fail and not continue if there is a single test failure in an integration tests. This is unlike regular unit tests and I would expect the build to continue so it can report all failures and warnings. Sometimes failures are acceptable or intermittent issues that are not easy to fix or sometimes you just want to get a full report of all issues so you can fix all issues at once.

You can do different tricks in Ant or Gradle to allow the bndtest task to not cause a build fail, but this is not desirable as other failures with the bndtest task _should_ cause a failure. For instance, if a bundle is missing and you have package resolution issues so that you can't start the tests, I would expect a build failure.

I would expect there to be a distinction between a complete failure (unable to run a test) to cause a build failure, but not if a single test fails (either as an error or failure). Basically exactly how the junit task works.

**Comment by pkriens** [comment]
We need a PR for this for ant. Are you willing to provide this? This would be in the https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd/src/aQute/bnd/ant/TestTask.java#L83

Can you create such a PR?
