### ISSUE TITLE
Define header in bnd to prevent bundle from being used in the buildpath

### ISSUE THREAD

**Issue by dhumeniuk** [bndtools/bnd#726]
See convo here: https://groups.google.com/forum/#!starred/bndtools-users/K8mR3Jb2c_s

Basically there are some bundles that cause issues if they are used at build time because they contain extra dependencies that the developer should not try to add in. This would be a fail fast situation that would prevent someone from adding in a bunch of extra dependencies into the classpath.

**Comment by pkriens** [comment]
If you provide a PR we consider it otherwise we need to move this to abeyance since we do not have the time.

**Comment by dhumeniuk** [comment]
Feel free to move to abeyance.

**Comment by pkriens** [comment]
thanks
