### ISSUE TITLE
aQute.bnd.annotation.metatype.Configurable should check the min/max annotation values

### ISSUE THREAD

**Issue by gossmer** [bndtools/bnd#727]
Qute.bnd.annotation.metatype.Configurable does not check the min/max annotation values but it checks for “deflt" and “required" and will issue errors, so why not also check the min/max annotation values?

Here is an example of extending this class to support checking the values:

    public static <T> T createConfigurable(Class<T> clazz, Map<?, ?> properties, boolean checkValues)
    {
        T config = Configurable.createConfigurable(clazz, properties);

        if ( !checkValues )
        {
            return config;
        }
        
        Method[] methods = clazz.getDeclaredMethods();

        for (Method method : methods)
        {
            if ( method.getParameterTypes().length != 0 )
            {
                continue;
            }

            // check for min/max values.
            Meta.AD     ad = method.getAnnotation(Meta.AD.class);
            String      minAttr = ad.min();
            String      maxAttr = ad.max();

            if ((maxAttr != null) && maxAttr.equals(Meta.NULL))
            {
                maxAttr = null;
            }
            if ((minAttr != null) && minAttr.equals(Meta.NULL))
            {
                minAttr = null;
            }

            if ( (maxAttr != null) || (minAttr != null) )
            {
                try
                {
                    if ( Proxy.isProxyClass(config.getClass()) )
                    {
                        InvocationHandler   handler = Proxy.getInvocationHandler(config);
                        Object              value = handler.invoke(config, method, null);

                        if ( (value != null) && !(value instanceof Number) )
                        {
                            throw new IllegalStateException(method.getName()
                                    + " configuration not a number but has min/max values.");
                        }

                        if ( value != null )
                        {
                            // check for min/max values matching.
                            checkValue(method.getName(), (Class<?>) method.getGenericReturnType(), (Number) value,
                                    minAttr, maxAttr);
                        }
                    }
                }
                catch (IllegalStateException ee)
                {
                    throw ee;
                }
                catch (Throwable ee)
                {
                    throw new IllegalStateException(method.getName()
                            + " configuration min/max values could not be checked.", ee);
                }
            }
        }
        return config;
    }

    private static void checkValue(String methodName, Class<?> resultType, Number num, String minAttr, String maxAttr)
            throws IllegalStateException
    {
        if ( resultType == short.class )
        {
            short value = num.shortValue();
            if ( (minAttr != null) && (value < Short.parseShort(minAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value less than required minimum "
                        + minAttr);
            }
            if ( (maxAttr != null) && (value > Short.parseShort(maxAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value more than allowed maximum "
                        + maxAttr);
            }
        }
        else if ( resultType == int.class )
        {
            int value = num.intValue();
            if ( (minAttr != null) && (value < Integer.parseInt(minAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value less than required minimum "
                        + minAttr);
            }
            if ( (maxAttr != null) && (value > Integer.parseInt(maxAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value more than allowed maximum "
                        + maxAttr);
            }
        }
        else if ( resultType == long.class )
        {
            long value = num.longValue();
            if ( (minAttr != null) && (value < Long.parseLong(minAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value less than required minimum "
                        + minAttr);
            }
            if ( (maxAttr != null) && (value > Long.parseLong(maxAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value more than allowed maximum "
                        + maxAttr);
            }
        }
        else if ( resultType == float.class )
        {
            float value = num.floatValue();
            if ( (minAttr != null) && (value < Float.parseFloat(minAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value less than required minimum "
                        + minAttr);
            }
            if ( (maxAttr != null) && (value > Float.parseFloat(maxAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value more than allowed maximum "
                        + maxAttr);
            }
        }
        else if ( resultType == double.class )
        {
            double value = num.doubleValue();
            if ( (minAttr != null) && (value < Double.parseDouble(minAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value less than required minimum "
                        + minAttr);
            }
            if ( (maxAttr != null) && (value > Double.parseDouble(maxAttr)) )
            {
                throw new IllegalStateException(methodName + " configuration value more than allowed maximum "
                        + maxAttr);
            }
        }
    }

**Comment by pkriens** [comment]
Please provide a PR

**Comment by bjhargrave** [comment]
The bnd metatype annotations are deprecated in bnd 3.2 and will be removed in bnd 4.0. These annotations are replaced by the OSGi metatype annotations.
