### ISSUE TITLE
Unnecessarily complex filter expression from @RequireCapability

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#743]
Using the enRoute `@WebServerExtender.Require` annotation leads to the following filter expression:

    (&(osgi.extender=osgi.enroute.webserver)(&(version>=1.0.0)(!(version>=2.0.0))))

This is unnecessarily complex and affects downstream tools that try to semantically understand the filter, e.g. the FilterParser in bnd doesn't successfully parse this into a `WithRangeExpression`. Also of course it's harder for humans to understand...

It should be simplified as follows:

    (&(osgi.extender=osgi.enroute.webserver)(version>=1.0.0)(!(version>=2.0.0)))

**Comment by pkriens** [comment]
The FilterParser has no problem with this expression. It prints it as:

     &(osgi.extender==osgi.enroute.webserver)(version=[1.0.0,2.0.0))

If it had been a package:

     osgi.enroute.webserver; version=[1.0.0,2.0.0)

So not sure we should fix this. We should not start pretending that filters are easy parseable?

**Comment by pkriens** [comment]
Neil, can we close this?

**Comment by njbartlett** [comment]
@pkriens I'd rather you didn't, I still think there is a problem. I'll take a look later.
