### ISSUE TITLE
-include ${var} does not work if var defined in same bnd file

### ISSUE THREAD

**Issue by derheld42** [bndtools/bnd#754]
I just discovered this trying to do something in my cnf/ext/repositories.bnd file.

I have a test case here:
https://github.com/derheld42/bnd/commit/64b3b89e6ff11dfad8c327ef8dd09d36672e4346

**Comment by pkriens** [comment]
Won't fix because the include might change the value of the variable, creating really confusing situations. Just define the var in a higher level
