### ISSUE TITLE
osgi.ds -> osgi.component

### ISSUE THREAD

**Issue by seanbright** [bndtools/bnd#755]
The repository index generates an osgi.extender capability with a value of osgi.ds for Felix SCR and Equninox DS.  RFC 190 seems to indicate that osgi.component should be used instead.

**Comment by seanbright** [comment]
Also - Apache Felix SCR 1.8+ supports DS 1.2 and that should be properly reflected in the relevant known-bundles.properties files.

**Comment by bjhargrave** [comment]
> Also - Apache Felix SCR 1.8+ supports DS 1.2 and that should be properly reflected in the relevant known-bundles.properties files.

We will look to pull this change into 2.4.1.

The osgi.extender name change will be for 3.0.

**Comment by seanbright** [comment]
Doesn't look like the req/cap change made it into 2.4.1?

**Comment by bjhargrave** [comment]
Yes, I did forget this since it was on the wrong milestone. I have cherry-picked to next for 2.4.1.

**Comment by bjhargrave** [comment]
Moved back to 3.0 milestone for extender name change.

**Comment by seanbright** [comment]
Closed by https://github.com/bndtools/bnd/pull/813
