### ISSUE TITLE
tstamp consistency across bundles

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#761]
When using the tstamp macro in a version, for example `project.build = ${tstamp;yyyyMMddHHmm}` in cnf/build.bnd and `Bundle-Version: 1.0.0.${project.build}` in the bundle's bnd file, each bundle build evaluates the time independently. This can result in bundles from the same project having different timestamps if the time changes between bundle builds. (This caused a test failure in OSGi where the test expected nested bundles in a project to have the same timestamp.)

bnd needs to use the same time value when evaluating tstamp for all bundles in a project.

It would also be desirable to provide a means to use the same time value when evaluating tstamp for all bundles in a workspace. Then an off-line build could build bundles all sharing the same build timestamp. This would then allow all the bundles to be correlated to the same build. Currently the bundles all have timestamps from the range of time covering the overall build which makes it harder to easily say that two bundles came from the same build.

**Comment by pkriens** [comment]
I'll capture the time for tstamp at the start of a project build.
