### ISSUE TITLE
Named -runbundles such as -runbundles.test don't work in BndEditModel

### ISSUE THREAD

**Issue by paulbakker** [bndtools/bnd#762]
The BndEditModel doesn't seem to support "named" -runbundles. The following works correctly:

```
static final String BND_RUNPATH = "-runbundles: \\\n" +
			"\torg.apache.felix.dependencymanager";

BndEditModel model = new BndEditModel();
		model.loadFrom(getFile(BND_RUNPATH));
		
		List<VersionedClause> runBundles = model.getRunBundles();
		assertEquals(1, runBundles.size());
```

But this doesn't:
```
static final String BND_NAMED_RUNPATH = "-runbundles.test: \\\n" +
			"\torg.apache.felix.dependencymanager";

	public void testNamedRunBundles() throws IOException {
		BndEditModel model = new BndEditModel();
		model.loadFrom(getFile(BND_NAMED_RUNPATH));
		
		List<VersionedClause> runBundles = model.getRunBundles();
		assertEquals(1, runBundles.size());
	}
```
I have added the tests to a branch: https://github.com/paulbakker/bnd/compare/paul/bndmodel-named-runbundles-bug

**Comment by pkriens** [comment]
The problem is that if you define a variable like -runbundles in multiple places you can no longer edit in one place. So I do not really see a solution for this? I am using the editor (sometimes) to edit -runbundles and treat the -runbundles.* as extra.

**Comment by pkriens** [comment]
A BndEditModel has getProperties which returns a Processor, which can do mergeProperties

But Project.getRunBundles() gives you the actual
