### ISSUE TITLE
LocalIndexedRepo (R5) does not generate index file that is gzipped

### ISSUE THREAD

**Issue by gamerson** [bndtools/bnd#763]
While trying to create a local index file (index.xml.gz) using LocalIndexRepo I noticed that the output was getting correctly named index.xml.gz which is the default but the output was not gzipped, instead it was plain text.  I was not able to force the LocalIndexRepo to actually generate a gzipped output even when explicitly setting the pretty=false.

**Comment by bjhargrave** [comment]
Fixed by #764
