### ISSUE TITLE
Generate bundle repository index for runbundles task in Gradle

### ISSUE THREAD

**Issue by paulbakker** [bndtools/bnd#765]
The "runbundles" task in the Gradle plugin exports all bundles listed in a run configuration to a directory. It would be useful to also generate an index for this directory so that it can be used as a repository in a Bndtools workspace.

**Comment by fhuberts** [comment]
use my gradle plugin and its setup; trivial to add the indexing

**Comment by bjhargrave** [comment]
I think you need to write a task for that. In your project, add a build.gradle which adds a doLast for the appropriate runbundles task to add the index or a new task.

Nowhere else in the gradle plugin do we index. The indexer code is not part of the gradle plugin jar.

**Comment by hellorachid** [comment]
@fhuberts  can you please give us your gradle plugin url

**Comment by fhuberts** [comment]
@hellorachid 

https://marketplace.eclipse.org/content/bndtools-plugins-pelagic

and see for an example here: https://github.com/fhuberts/bndtoolsPlugins/blob/master/build/build-settings.gradle

documented here: https://github.com/fhuberts/bndtoolsPlugins/blob/master/nl.pelagic.bndtools.headless.build.plugin.gradle/resources/templates/unprocessed/cnf/gradle/doc/BUILDING-GRADLE.md#BuildTasksIndex

**Comment by hellorachid** [comment]
@fhuberts thank you

**Comment by pkriens** [comment]
I think this is a perfect example of a custom script ... that is what build tools are for. If we're not careful we get a very bloated plugin
