### ISSUE TITLE
Make baseline results more accurate

### ISSUE THREAD

**Issue by dhumeniuk** [bndtools/bnd#766]
This is based on converstation https://groups.google.com/forum/#!starred/bndtools-users/l6gYF-Xnvg0

I could not find any other issues like this, sorry if it is a duplicate.

Basically the baseline operation produces a lot of false positives as it compares the checksum of the compiled class files not the contents of them. I don't know exactly what is available, but I know there are some libraries for looking at Java assembly code (e.g., ASM). I have run into these issues when different minor versions of the same compiler are used (e.g., 1.7_55 vs. 1.7_65) produce different class files. In my opinion that should not be a micro change. Even if you get every machine to build with the exact same Java compiler and minor version, you still end up with different platforms (OS/architecture) creating slightly different class files (according to others).

As an initial workaround/improvement that would probably be easier to implement, if the baseline operation would check only major/minor changes and not even check micro changes, that would be an improvement for me so I could still use baselining day to day to detect the import changes. I would figure this to be a flag that could be added or an extension of the `-diffignore` flag. As it is now, I can't use the baseline operation at all and am left to manually checking like before.

**Comment by bjhargrave** [comment]
Superseded by #794

**Comment by dhumeniuk** [comment]
Even better. Look forward to the other issue being resolved
