### ISSUE TITLE
Declaring an entire package or project as having only producer type interfaces

### ISSUE THREAD

**Issue by dhumeniuk** [bndtools/bnd#769]
From posting: https://groups.google.com/forum/#!starred/bndtools-users/7IOOMTDArTg

I have protocol buffer Java classes that are generated automatically from another format and are part of the API. This part of the API is comprised of ~1000 Java types (classes, interfaces and enums.). Besides somehow adding the @ProducerType annotation to every interface in generated code, I would like a way to define something in the bnd or package info file. There is the `provide:=true` directive for export packages, but this didn't seem to have an effect during baselining operations.

**Comment by rotty3000** [comment]
extending @ProviderType|@ConsumerType to package annotations might be nice.

**Comment by bjhargrave** [comment]
> extending @ProviderType|@ConsumerType to package annotations might be nice.

Well if you can annotate package-info, you can annotate the classes. So I don't see the value in putting these annotations on package-info. (And this is really a spec issue rather than a tool issue.)

As for generated classes, it seems like it would be easy and best to add a build step to insert the desired annotations after the code generation step.

**Comment by rotty3000** [comment]
But you can make the package before the code is generated and annotate the
package-info.java

You often can't edit generated code!

**Comment by rotty3000** [comment]
To clarify, code generators typically have you specify a package (root)
into which the generated classes should land. With that you have the
opportunity to put stuff in that package ahead of, or in association with
the generated code.

I think the package-info.java is particularly suited to handle the default
behaviours you'd like to apply to the generated code.

However, a limitation may be that generators also often create sub-packages
(ours certainly does).

This might be a problem where we might expect to apply defaults to a
recursive list of sub-packages.

**Comment by kmart216** [comment]
At least in our case we maintain the package-info.java files for each package where the generated code goes. We do this for both JAXB classes generated from XSDs using XJC and Protocol Buffers. This is where we store the version of the package already.

**Comment by kmart216** [comment]
I would definitely be for expanding the annotation to packages. The annotation I'm using is defined by bnd. Is there somewhere API issues are logged for bnd?

**Comment by bjhargrave** [comment]
> You often can't edit generated code!

That is what sed/awk are for :-)

> Is there somewhere API issues are logged for bnd?

There are OSGi annotations for this now (bnd lead the way). I would expect further enhancements to occur in the OSGi annotations. Peter tried to raise this discussion in the OSGi call today but we ran long and out of time.

**Comment by kmart216** [comment]
I would image if the changes are made to the OSGi annotations, it would still take some time for it to happen. Seems like the changes could be made in the mean time for bnd a lot sooner. That's just an assumption, but usually implementations move faster than specs.

I might have some time during a weekend to put a pull request together if it is something that would be worthwhile.

**Comment by bjhargrave** [comment]
For the OSGi annotation, we need to do spec work for Core R7. Basically I could see that we allow the annotation to be applied to package-info.java to set the default for unannotated types in the package. @rotty3000 can you start the spec work in OSGi?

**Comment by rotty3000** [comment]
will do!

**Comment by bjhargrave** [comment]
I opened OSGi EG bug https://osgi.org/members/bugzilla/show_bug.cgi?id=2906 to discuss a spec change.

**Comment by bjhargrave** [comment]
This will be for OSGi R7:

> CPEG call: We agreed to change @ProviderType to allow it to be applied to a package (that is, in package-info.java). 
> 
> Applying it to a package means that any importer of the package should import at the narrower provider range. That is, the use of @ProviderType on the package narrows the import range that might have been computed based upon the types used in the package.

**Comment by bjhargrave** [comment]
I updated @ProviderType to allow it to be applied to packages. So we need to update bnd accordingly.

```
 * A package can be marked {@link ProviderType}. In this case, all types in the
 * package are considered to be a provider type regardless of whether they are
 * marked {@link ConsumerType} or {@link ProviderType}.
```
