### ISSUE TITLE
Bindex adds target filter to service requirements

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#770]
Bindex has the following code in the SCRAnalyzer:

    String target = attribs.getValue(ATTRIB_TARGET);
    if (target != null)
      filter = String.format("(&(%s=%s)%s)", Constants.OBJECTCLASS, interfaceClass, target);
    else
      filter = String.format("(%s=%s)", Constants.OBJECTCLASS, interfaceClass);

This means that we fail if the property for the target is set dynamically, e.g. via Config Admin. Suggest we remove this.

**Comment by bjhargrave** [comment]
I don't understand what you suggest. Are you saying the indexer should ignore the target property as set in the component description because it may be different at runtime?

**Comment by pkriens** [comment]
We should not include any target properties since this is more a runtime filter that is often overridden by config admin. Since this is handled in runtime anyway, we should be able to ignore it easily.
