### ISSUE TITLE
bnd should generate osgi.service capabilities and requirements for DS services

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#792]
When bnd makes a bundle which has DS XML:

For provided services, the bundle's manifest needs to provide the proper osgi.service capability.

For consumed services, the bundle's manifest needs to require the osgi.service using effective:=active with only the objectClass attribute.

(From OSGi EG discussions.)

**Comment by bjhargrave** [comment]
@djencks Can you look into this?

**Comment by bjhargrave** [comment]
This can be done for all components. It does not matter what the namespace version is.

**Comment by bjhargrave** [comment]
Based upon #797 we probably need to collect the service information for provided and consumed services in some data structure that other part of bnd (and plugins) can access. We now have two potential consumers of the service information: osgi.service cap/req generation and ServicePermission generation.

**Comment by djencks** [comment]
IIUC (if I understand correctly) Peter is saying this common data structure should be the service capability provides/requires info and the service permission generation should run off that.

**Comment by djencks** [comment]
Should these capabilities only be exposed for interfaces that are exported/imported?  Some projects use DS components for classes that are entirely private to the bundle.  I'd expect these would not be exposed.

**Comment by djencks** [comment]
Initial implementation at https://github.com/djencks/bnd/tree/792-gen-service-caps-1.  This is generating headers such as:
Provide-Capability:osgi.service;objectClass="java.io.Serializable",osgi.service;objectClass="java.lang.Cloneable"

Require-Capability:osgi.service;filter:="(objectClass=org.osgi.service.log.LogService)";effective:=active,osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"

Do these look right?  AFAICT reading the results out using Parameters/Attrs is removing the quoates around the directive values.

**Comment by timothyjward** [comment]
Assuming that the Provide-Capability refers to a single service then I believe that:

> Provide-Capability:osgi.service;objectClass="java.io.Serializable",osgi.service;objectClass="java.lang.Cloneable"

is incorrect. It should actually be:

    Provide-Capability:osgi.service;objectClass:List<String>="java.io.Serializable,java.lang.Cloneable"

If I'm wrong and there are actually two separate services in the bundle then the former is correct.

**Comment by bjhargrave** [comment]
@timothyjward is correct. 

First objectClass must _always_ be `List<String>`. 

Each component that registers a service needs to generate an `osgi.service` capability which lists all the service names. Not multiple `osgi.service` capabilities. 

If multiple components results in the same `osgi.service` capability, then the tool can collapse them into a single `osgi.service` capability since there is no value in duplicate capabilities.

**Comment by djencks** [comment]
OK, now it's generating stuff like
Provide-Capability:osgi.service;objectClass:List<String>="java.io.Serializable,java.lang.Runnable"
thanks

**Comment by bjhargrave** [comment]
> Provide-Capability:osgi.service;objectClass:List="java.io.Serializable,java.lang.Runnable"

I assume you means `objectClass:List<String>`? While `List` is the same as `List<String>` since `<String>` is the default List type, it would be better for bnd to generate the fully qualified List type.

**Comment by djencks** [comment]
The generic type is there, just hidden by my lack of skill with markdown.

**Comment by bjhargrave** [comment]
I fixed your markdown :-)

**Comment by djencks** [comment]
I also added the extender capability when namespace version >= 1.3, package version we are building against is >= 1.3, or an extender flag is set.  Any objections to merging all of this? (I will squish into one commit first).

**Comment by djencks** [comment]
Fixed with merge request #822
