### ISSUE TITLE
Improve error reporting when resolving bundles for headless builds

### ISSUE THREAD

**Issue by dhumeniuk** [bndtools/bnd#793]
Not sure if I'm missing an available option, but I got that sense this request isn't currently supported.

Original conversation here: https://groups.google.com/forum/#!starred/bndtools-users/98VMDZSdgyw

If a bundle is not found on the build path, I don't see an error until compiling of the source code that needs the build dependencies. I get some message about the type not being found. I can see the bundle in question is not on the javac classpath. It would be nice if there was an error when resolving bundles on the bnd buildpath (and other bundle paths) that could not be found. Specifically I've noticed issues where the bundle should be available from the JPM4J bundle repository, but there could be issues with other bundle repositories.

I usually run into this issue when everything seems to be working in Eclipse, but for some reason the bundle is not found while building with Jenkins.

**Comment by derheld42** [comment]
I just added an option that brings the bndtools eclipse access rules closer to how bnd processes things. It's currently not on by default. You could try it with the latest bndtools to see if eclipse fails like the headless build. Add this in cnf/build.bnd to affect all projects:

eclipse.newaccessrules: true

See bndtools/bndtools#1003 for more details.

**Comment by dhumeniuk** [comment]
Will have to check out the latest plug-in, that sounds like it will help me with other issues I've had, but this issue is more of the opposite case where I'm not seeing enough information during a headless build.

I'm expecting a message from Ant/Gradle like bundle osgi.core is not available, instead I get a compiler error like unable to find type Bundle.

I haven't been able to hunt down the actual issue this time, but before it was because the JPM4J bundle repo could not write to the configured cache folder.

**Comment by pkriens** [comment]
Are you sure there is no error reported before the compile errors?

**Comment by pkriens** [comment]
You now get errors when the buildpath contains erroneous entries. They should actually be marked in the bnd source code.

**Comment by bjhargrave** [comment]
> They should actually be marked in the bnd source code.

For bndtools, but that does not apply to offline (headless) builds which are the subject of this issue.

But given there are now errors added to the model, the gradle plugin should report out the errors.

Is there a test repo for this problem?

**Comment by dhumeniuk** [comment]
I believe this issue is now fixed. Last time we had the problem with the path to the JMP4J cache folder, I got an error message with a large stack trace.
