### ISSUE TITLE
Configurable: lists/arrays and null/empty behaviour

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#796]
Consider this interface:
```
package tests;

import java.util.List;

import aQute.bnd.annotation.metatype.Meta;

public interface Config {
	String DEFAULT = "default value";

	@Meta.AD(deflt = DEFAULT, required = false, description = "some list")
	List<String> someList();
}
```

Now run this code
```
/* null */
Map<String, Object> props = new HashMap<>();
props.put("someList", null);
Config config = Configurable.createConfigurable(Config.class, props);
List<String> someList = config.someList();
System.out.printf("(null ) someList size / value = %d / %s\n",someList.size(),someList);

/* empty */
props = new HashMap<>();
props.put("someList", "");
config = Configurable.createConfigurable(Config.class, props);
someList = config.someList();
System.out.printf("(empty) someList size / value = %d / %s\n",someList.size(),someList);
```

and get
```
(null ) someList size / value = 1 / [default value]
(empty) someList size / value = 1 / []
```

Two questions/issues:

1. for the 'null' case: I explicitly set it to ```null```, I did not expect the default value. Is the order of default/props evaluation reversed? Seems to me that there is a setting in the properties thus the default should not be returned. Is this according to spec / expected behaviour?

2. for the 'empty' case: I can see how this would return an array of size 1 with an empty member. However, it seems more intuitive to return an empty array. What is the spec / expected behaviour here?

**Comment by pkriens** [comment]
This is as expected, null == no value so default. An empty string is a value.

**Comment by fhuberts** [comment]
Where is the spec can I find this please?

**Comment by pkriens** [comment]
There is no spec ... this is bnd

**Comment by fhuberts** [comment]
And how would this work for R6 annotations?
The same?

**Comment by bjhargrave** [comment]
> And how would this work for R6 annotations?
> The same?

Component Property Types (annotations) in R6 can't have List values since List values are not supported for annotation elements. Also null property values are not supported in component descriptions or Config Admin (Dictionary keys cannot have null values). So that leaves an array type with an empty string value which would result in a single element array with the empty string coerced to the array component type (or an exception if an empty string cannot be coerced into the array component type.)

**Comment by fhuberts** [comment]
ok, tnx
