### ISSUE TITLE
Feature Request: Generating permissions.perm file

### ISSUE THREAD

**Issue by marcdejonge** [bndtools/bnd#797]
In an OSGi project we are doing, we would like to use the Java Security in OSGi to set permissions for bundles. Currently this is a lot of work doing this correctly. Mainly 2 items that I see that can be generated automatically (which are now a lot of work to keep correct):

- org.osgi.framework.PackagePermission, for all the imported and exported packages
- org.osgi.framework.ServicePermission, for when using DS, you can detect which type of services are used and which are registered

I would like to see that in a bnd.bnd file of a project I could specify something like the following

```
-permissions: generate-all,\
              java.io.FilePermission;path="/";actions="read"
```

Maybe this could be extended with special tokens like: generate-services, generated-package.

What do you think about this idea? Maybe I could start on this feature, but I'm not sure where to start in the code...

**Comment by bjhargrave** [comment]
bnd can already automatically generate the package permissions. Assuming the resource in your project for your permissions is `resources/permissions.perm`. Add the following line to that file:

    ${permissions;packages}

Then include that resource in your bundle with `-includeresource` using curly braces. For example:

    -includeresource: {OSGI-INF/permissions.perm=resources/permissions.perm}

The curly braces tells bnd to process macros in the file(s). OSGi uses this technique to build its security test bundles.

For the security permissions, you probably will want to extends the `${permissions}` macro to have a `services` option. And you will need to figure our how to collect the services known during DS annotation processing. See #792 which is about collecting the services known during DS annotation processing to generate osgi.service capabilities and requirements in the manifest. That is the same information you need to generate ServicePermissions with GET and REGISTER actions. So we need to reuse some logic here.

**Comment by marcdejonge** [comment]
I'll go and try the packages for now. The DS services I'll look into later...

**Comment by marcdejonge** [comment]
I'll go and try this first. I didn't know about these kind of options. Also I can't find any documentation about options like these. Maybe it's a good idea to put features such as these on the bnd website? Or here on the wiki?

For the service generation, I'll look into that when I have the time.

**Comment by bjhargrave** [comment]
The ${permission} macro is mentioned in the bnd docs at <http://bnd.bndtools.org/chapters/850-macros.html> but the doc page, <http://bnd.bndtools.org/macros/permissions.html>, has not been filled in yet.

But if you want to add a wiki page about using the ${permissions} macro to automatically add the PackagePermissions to a bundle's permissions.perm file, that would be great!

**Comment by marcdejonge** [comment]
Ok, I did a first try in implementing the generation of services. Unfortunately it won't work, because the resources are included before the DSAnnotations plugin is called. I don't really see how this can be changed.

I expected some kind of 2-phase building (first the analysis and then generation), but this doesn't seem to be the case. Am I correct?

I've commited my current version to https://github.com/marcdejonge/bnd/compare/797-service-permissions

**Comment by marcdejonge** [comment]
Ok, just found that I can call the analize() method before including the resources. It works for my testcase, but it breaks some of the BuilderTest testcases.

**Comment by bjhargrave** [comment]
See PR https://github.com/bndtools/bnd/pull/809

**Comment by pkriens** [comment]
@marcdejonge : Marc are you working on this?

**Comment by marcdejonge** [comment]
Last time I was a bit stuck on the implementation
I will try to merge it back to the latest version and see what kind of trouble I run into.

**Comment by pkriens** [comment]
Where are we on this? Should we expect to include this in 3.0?

**Comment by bjhargrave** [comment]
PR #809 is making progress. Awaiting response from @marcdejonge after my last comment. I think it is looking good for 3.0.

**Comment by marcdejonge** [comment]
Sorry for the delay, I have a new job, so not that much time available. I think the latest version is looking good though :smile:

**Comment by bjhargrave** [comment]
PR #809 merged.
