### ISSUE TITLE
Exporting an empty/non-existant package with -exportcontents should raise warning

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#814]
If `-exportcontents` refers to a package that doesn't exist then we should generate a warning. There are rare edge cases in which the user might want to do this deliberately, but more likely it will be a typo.

I suggest that we raise a warning if the package name does not contain a wildcard and is non-existent.

**Comment by pkriens** [comment]
Ok, we generate a warning

**Comment by pkriens** [comment]
It is also true for Export-Package

**Comment by pkriens** [comment]
I've added this to the package export verification. This is only
