### ISSUE TITLE
Discouraged access: X is not API with multiple API sub-bundles

### ISSUE THREAD

**Issue by dhumeniuk** [bndtools/bnd#839]
Using the latest Bndtools, I've noticed the discouraged access warning show in place where the type/method is truly API.

I have some Bnd projects that have multiple bundles, each of which export some packages. These APIs are then used by some other project and therefore the bundles are added to the build path. I then incorrectly get the message that the method/type is not in the API. It looks like whichever bundle is listed first will be the only API available from that project. All other bundles listed will basically be ignored as far as available API.

In general that you should not have more than one API bundle per project and usually that is not the case for our workspace, but there are a few cases where it is less complex to have multiple bundles together.

**Comment by bjhargrave** [comment]
> On Mar 1, 2015, at 15:02 , dhumeniuk <notifications@github.com> wrote:
> 
> Using the latest Bndtools, I've noticed the discouraged access warning show in place where the type/method is truly API.
> 
> I have some Bnd projects that have multiple bundles, each of which export some packages. These APIs are then used by some other project and therefore the bundles are added to the build path. I then incorrectly get the message that the method/type is not in the API. It looks like whichever bundle is listed first will be the only API available from that project. All other bundles listed will basically be ignored as far as available API.
> 
> 

You don’t provide any detail on how you reference the API bundles. Lets assume your api project is called com.acme.api and you have subbundles foo.bnd and bar.bnd. If other projects need to reference the api, their -buildpath should have com.acme.api.foo.jar;version=latest and/or com.acme.api.bnd.jar;version=latest.

With version=latest, bndtools will put the generate bundle on the class path and use the Export-Package statement in the bundle to set the package visibility.

If you use com.acme.api;version=project, then the bin folder of the project is put on the classpath and bndtools must ask the Project object for the exported packages [1] which should be a union of the exports of all the subbundles. But I think it is better, in your case of subbundles, to use version=latest on the individual subbundles when referencing them in other project’s -buildpaths.

Finally, you can also add the attribute “packages” to the entry in the -buildpath. The value is a comma separated, wildcarded list of packages which bndtools will make visible. For example: com.acme.api;version=project;packages=*. In that example, the reference to com.acme.api will have visibility to all package in the bin folder of the com.acme.api project.

[1] https://github.com/bndtools/bndtools/blob/master/bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java#L407
> In general that you should not have more than one API bundle per project and usually that is not the case for our workspace, but there are a few cases where it is less complex to have multiple bundles together.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/bndtools/bnd/issues/839>.
> 

-- 

BJ

**Comment by dhumeniuk** [comment]
Yes, I'm using version=latest and that is when I see these warnings:

    -buildpath: 
      ...
      xyz.api1;version=latest,\
      xyz.api2;version=latest,\
      ...

**Comment by bjhargrave** [comment]
Can you supply a github project with the test projects so I can look into it?

**Comment by dhumeniuk** [comment]
https://github.com/dhumeniuk/discouraged-access-example

**Comment by bjhargrave** [comment]
OK, I see what the issue is. Now I have to figure out how to deal with it.

**Comment by bjhargrave** [comment]
BTW, this issue is a bndtools issue and should have been filed there. But I have a fix I will release shortly.

**Comment by dhumeniuk** [comment]
Yup, looks to be working. Thanks.
