### ISSUE TITLE
launcher: negative return codes are not supported on Linux/Unix systems/shells

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#848]
Negative return codes are not supported on Linux/Unix systems/shells.

A return code is an __unsigned char__

For example: the 'restart please' return code of -4 actually is 252.
Please return only unsigned char return codes and also document them

Note that some return code (> 125) are special (on bash).
See also http://en.wikipedia.org/wiki/Exit_status

**Comment by pkriens** [comment]
Look at aQute.libg.command:
		byte exitValue = (byte) process.waitFor();

So bnd supports the byte range, which includes negative numbers. Not all systems targeted support larger exit codes.
