### ISSUE TITLE
RFE: improve bnd file error detection / detect trailing backslash

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#893]
It would be nice to detect the following situation and generate an error:
```
-buildpath: \
 	some.package;version=latest,\
 	${junit},\
 -sub: *.bnd
```

IOW: detect the trailing backslash on the line before an instruction/header

cloned from https://github.com/bndtools/bndtools/issues/1083

**Comment by pkriens** [comment]
This is generating an error already in 3.0 because the -sub *.bnd is not a value bsn

**Comment by fhuberts** [comment]
yes, for this specific example

obviously I mean it in a generic sense, please re-open

**Comment by pkriens** [comment]
Well, it is highly unlikely the next line would be a valid bsn?

Anyway, not much we can do since we use the standards Properties parser which does not handle these errors. You might want to reopen this on bndtools to change the editor to show these cases.
