### ISSUE TITLE
Failed bndlib tests on windows

### ISSUE THREAD

**Issue by marcdejonge** [bndtools/bnd#927]
There are a couple of failed tests when I run junit 3 on bndlib.tests.

There are 2 tests in `BuilderTest` that try to use the user path as an `URI` by doing:
```
new URI(pwd).toString()
```
This fails on a windows machine because a path such as `C:\Users\...` is not a valid URI. I will propose a quick fix for this

The second problem is a bit harder, but in involved the `CommandResource`. On [this line](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/CommandResource.java#L25) the command `sh` in invoked, which of course will never work on a normal windows machine (without cygwin or someting similar). Because of this there are 3 tests in `ResourceTest` that fail.

Should the `CommandResource` ever work on a Windows machine? Or should we just ignore these? In that case I do propose that we give a clear warning when the `CommandResource` is used on a windows machine that this won't work.

**Comment by pkriens** [comment]
Disable windows tests

**Comment by bjhargrave** [comment]
We now have bnd building and testing on Windows using the AppVeyor CI system: <https://ci.appveyor.com/project/bjhargrave/bnd>. This does not exhibit any failures in CommandResource. So perhaps this issue can be closed?

**Comment by bjhargrave** [comment]
Why do we need to disable these tests? They seem to be passing in the appveyor CI builds.

**Comment by pkriens** [comment]
AppVeyor has this unix shell installed …

I do not think it is worth it to fine-tune this …

Kind regards,

	Peter Kriens
