### ISSUE TITLE
[remote] launcher CommandSession/GogoRedirector output can be slow

### ISSUE THREAD

**Issue by gamerson** [bndtools/bnd#933]
When using -runremote and specifying the shell to use "CommandSession/GogoRedirector" (specify the shell=-1) if I send a command in the eclipse console like "lb" it will return the output line by line, where it takes maybe 15-20 seconds to output a standard "lb" command with maybe 100 bundles.

**Comment by pkriens** [comment]
Can you debug this Greg? If so we can put it on 3.0 otherwise I move it to 3.1
