### ISSUE TITLE
Feature request: parameterise RequireCapability filter using annotation attributes

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#938]
I would like to define an annotation as follows:

    @RequireCapability(ns = "foobar", filter = "(foobar=@value)")
    public @interface MyAnnotation { String value(); }

Such that using the annotation with a value attribute like this:

    @MyAnnotation("hello")

will result in a generated requirement like this:

    Require-Capability: foobar; filter:="(foobar=hello)"

The syntax for the placeholder is not important to me. We could reuse macro syntax but it may not be sensible to use the full power of macros here.

**Comment by bjhargrave** [comment]
We discussed this basic topic at OSGi this week during a discussion about [RFP 167](https://github.com/osgi/design/blob/master/rfps/rfp-0167-Manifest-Annotations.pdf). So I expect something like this will be in the RFC.

**Comment by njbartlett** [comment]
Fixed in a54a1b7
