### ISSUE TITLE
Warning for private references

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#942]
If an exported package has private references then a warning is raised. However, if the package is exported only this cannot really do any harm, can it?

**Comment by bjhargrave** [comment]
Is this evidence of improper coupling? How is an importer of the package supposed to use a method if the method takes, returns or throws some type it has no visibility to?

Seems to me the issue exists even for export only. Sure the bundle itself is fine in that it has access to the private types and can fully use the exported package. But no other bundle importing the exported package can.

**Comment by pkriens** [comment]
You're right. The forgot that the warning is ONLY there when the private packages are in the exported API. Then again, it would be impossible to use that method in the compiler?

**Comment by bjhargrave** [comment]
> Then again, it would be impossible to use that method in the compiler?

In bndtools, you would (hopefully) get a warning. But in a headless build (gradle/ant), javac will only see the bundle as a classpath and thus all the non-exported types are visible. So it would be quite likely to be able to use the method. bnd may object when making the bundle from the compiled code since it cannot find an exported package for the referenced types.

**Comment by pkriens** [comment]
Hmm, bndtools would generate a warning/error on any of those imports.

**Comment by bjhargrave** [comment]
That's good, but that does not mean there is not an issue on the exporting bundle's side. I think the warning still is valid.

**Comment by pkriens** [comment]
Ok, closing

**Comment by mnlipp** [comment]
> How is an importer of the package supposed to use a method if the method takes, returns or throws some type it has no visibility to?

Is "takes, returns or throws" the complete list? I get this warning and cannot find its cause (btw, wouldn't it be possible to specify the offending method in this warning?*). The only dependency between my exported package and the not-exported package is inheritance. Some type in the exported package inherit from the types in the not-exported package. Does this count as well?

(*) I only get: `Warning: Export <name of package.exported>,  has 1,  private references [<name of package.internal>]`

**Comment by martingd** [comment]
@mnlipp Did you ever find a way to identify the offending method, constructor, etc.?

**Comment by mnlipp** [comment]
> @mnlipp Did you ever find a way to identify the offending method, constructor, etc.?

Sorry, but this is from 2017. I cannot remember what caused the problem or how i fixed it.

**Comment by juergen-albert** [comment]
The analyser view of bndtools might give you a hint. If not, look through the imports of your classes of the exported packages it mentions. If something is imported, that is in your bunde but not marked as export package you have your culprit.
