### ISSUE TITLE
biz.aQute.launcher includes aQute.libg code which is -target 1.7

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#948]
biz.aQute.launcher is compiled -target 1.6 but the jar includes code from the aQute.libg project which is -target 1.7. So this defeats the point of making biz.aQute.launcher -target 1.6.

We may have to back aQute.libg down to -target 1.6 if we really want biz.aQute.launcher to run on Java 6.

**Comment by pkriens** [comment]
7a66f1fb1b ([build] Moved back to 1.6 because launch depends on it)
