### ISSUE TITLE
XMLAttribute defined annotation array value not parsed correctly into string

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#954]
given the following definition
```java
	@XMLAttribute(
		embedIn = "*",
		namespace = "meta-type-model-hints",
		prefix = "mh"
	)
	@Retention(RetentionPolicy.CLASS)
	@Target(ElementType.TYPE)
	public @interface Category {
		String[] category();
	}
```
The class
```java
@Category(category = "category.content")
@ObjectClassDefinition(id = "fee.fi.fo.Fum")
public interface Fum {
}
```
The generated metatype XML contains:
```xml
<metatype:MetaData xmlns:metatype="http://www.osgi.org/xmlns/metatype/v1.3.0" xmlns:mh="meta-type-model-hints" localization="OSGI-INF/l10n/fee.fi.fo.Fum">
  <OCD id="fee.fi.fo.Fum" name="Fee fi fo Fum configuration" description="" mh:category="[Ljava.lang.Object;@bc146c7">
...
```

**Comment by rotty3000** [comment]
workaround... don't use array. (still think it's a bug though)

**Comment by djencks** [comment]
I agree, this is a bug.  I might be able to look into it this weekend.

**Comment by bjhargrave** [comment]
I think the issue is here: <https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/xmlattribute/ExtensionDef.java#L53>.

    String value = String.valueOf(entry.getValue().get(key));

This code needs to call `Arrays.toString` if the entry value is an array type. Otherwise `String.valueOf` is fine.

**Comment by djencks** [comment]
I think space separation is perhaps more likely to be appropriate than comma separation?  Referring to http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/datatypes.html#built-in-derived all the build in datatypes that are "multiple" such as NMTOKENS, IDREFS, ENTITIES are all space separated.
Without a strong argument to the contrary I'll implement using space separation.

**Comment by bjhargrave** [comment]
👍🏻

**Comment by rotty3000** [comment]
+1

**Comment by djencks** [comment]
I don't see the point in trying to deal with nested arrays?  I didn't implement that.

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/pull/958

**Comment by djencks** [comment]
I'm not sure why this is closed with the pull request not merged?

**Comment by rotty3000** [comment]
I think that was accidental. @pkriens?

**Comment by bjhargrave** [comment]
I missed the bndtools call, so was not there to explain. I'll reopen until the PR is merged.

**Comment by djencks** [comment]
merged, closing.
