### ISSUE TITLE
@Reference annotation is missing @Target(ElementType.FIELD)

### ISSUE THREAD

**Issue by bosschaert** [bndtools/bnd#956]
The Reference annotation now also supports field references, however, the @Reference annotation in the BND codebase only allows it on methods. This should be fixed.

**Comment by timothyjward** [comment]
At this point there's nothing that bnd annotations can do that can't be done with the standard annotations so it was my understanding that the bnd annotations were no longer being updated, and were effectively deprecated.

**Comment by bosschaert** [comment]
Forgot to mention, this is in org.osgi.service.component.annotations.Reference that is shipped with bndlib 2.4.1, i.e. the latest release. So this *is* actually in the standard OSGi annotations...

**Comment by timothyjward** [comment]
From what I can see those are a private package in the bndlib bundle, and should not be built against. It also looks like they are the annotations from the previous release of the DS spec, which is all bndlib 2.4.1 understands. That version of those annotations does not support field references.

**Comment by bosschaert** [comment]
Maybe I mistakenly thought that bnd supported the latest DS spec annotations. Any ETA on when the latest DS annotations will be supported?

**Comment by timothyjward** [comment]
I believe that the support is complete in the master branch, and will be released as part of bnd 3.0

**Comment by bjhargrave** [comment]
> I believe that the support is complete in the master branch, and will be released as part of bnd 3.0

Yes. bnd 2.4.1. does not support the new DS annotation changes. Support for them is in the master branch for 3.0.
