### ISSUE TITLE
Should XMLAttribute emit annotation defaults

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#957]
As discussed later in #955 it's not clear how annotation defaults should be used

* should they be printed
* should they not be printed

I'm of the mind they should be printed as it greatly simplifies both the writing and usage of extension annotations.

**Comment by bjhargrave** [comment]
By "printed", you mean emitted in the generated XML?

An issues is whether the default value in the annotation has any relationship to the default value in the XML. For example, in

```java
    @XMLAttribute(
        embedIn = Hint.EMBED_IN,
        namespace = Hint.NS,
        prefix = Hint.PREFIX)
    public @interface ReadOnly {
        boolean readOnly() default true;
    }
```
the mere use of the ReadOnly annotation means you want to emit `mh:readOnly=true` in the generated XML. But from the perspective of the XML schema, the default value of the readOnly attribute is probably false.

It really depends upon how one writes their annotation as to whether the annotation default differs from the XML schema default and thus whether the annotation default should always be emitted in the generated XML. Perhaps we need an `XMLAttribute.Emit` annotation to force emitting?

```java
    @XMLAttribute(
        embedIn = Hint.EMBED_IN,
        namespace = Hint.NS,
        prefix = Hint.PREFIX)
    public @interface ReadOnly {
        @XMLAttribute.Emit
        boolean readOnly() default true;
    }
```

**Comment by djencks** [comment]
I don't really anticipate that anyone is likely to define a schema for their own-namespace additions to e.g. the ds or namespace schema, and it's even less likely that any code that reads the xml is going to pay attention to schema defaults.  For instance for felix ds, we use kxml. Any defaults are going to be hard coded in the implementation of the xml reader.

Your @Emit is similar in effect to my idea of a @Default annotation.  This would certainly provide the most flexibility.  I'm wondering though if this flexibility is actually useful or if constraining usage to Ray's style of "many small with emitted defaults" annotation is just fine.

**Comment by rotty3000** [comment]
I'd be fine with something like that. It had occurred to me that it might be useful to have both options (emit in some cases, not emit in others).

**Comment by rotty3000** [comment]
David beat me... I think for quickness and simplicity though that I would agree with David's assessment in that smaller more focused annotations which emit defaults feels most practical and simplest to achieve.

**Comment by bjhargrave** [comment]
> Your @Emit is similar in effect to my idea of a @Default annotation. This would certainly provide the most flexibility. I'm wondering though if this flexibility is actually useful or if constraining usage to Ray's style of "many small with emitted defaults" annotation is just fine.

I think Ray's style is how one can use annotations to emit an attribute with a value other than the schema default. It is probably easier to read the code with an @ReadOnly annotation than with an @Options(readOnly=true) assuming Option was an annotation aggregating all the extended attributes. It would also be silly to make people write @ReadOnly(readOnly=true) :-).

If your style is to use the @Options annotation, then you probably wrote the Options annotation so that the annotation defaults match the XML schema defaults and thus don't want to emit the attributes unless specified in the source.

So we probably do need some @Emit annotation to support either style. Without @Emit, the attribute will only be emitted if it is specified in the source. With @Emit, the attribute is always emitted.

**Comment by djencks** [comment]
Let me say it again.... what xml schema defaults?  I'm not about to write a schema for felix ds extension options, nor to make the felix ds xml processing schema-aware.  And I'm certainly not about to try to make the bnd plugins schema aware for 3rd party namespaces for non-existent schemas.

I'd suggest that we start by making the annotation default emitted, and if anyone complains, add an @Optional annotation to suppress it.  

To be clear.... I haven't actually written either of the annotations I have in mind yet, I just had an idea in mind how to do it.  So we wouldn't be breaking anything by changing the behavior.

**Comment by bjhargrave** [comment]
> Let me say it again.... what xml schema defaults? 

The defaults that are in the schema whose namespace the extensions belong too. For example, the `readOnly` attribute probably has some default in the schema which defines the attribute.

> I'm not about to write a schema for felix ds extension options, nor to make the felix ds xml processing schema-aware. And I'm certainly not about to try to make the bnd plugins schema aware for 3rd party namespaces for non-existent schemas.

I never said that and I don't mean that. bnd does not care what the schema says. bnd only cares about what the annotation says. But the annotation author probably knows and cares about what the schema defaults are.

> I'd suggest that we start by making the annotation default emitted, and if anyone complains, add an @Optional annotation to suppress it.

So if the annotation element has a default and the source does not specify the annotation element, then the XML attribute is emitted with the value set to the annotation element default value? I suppose that would be fine. You can always define the annotation element to not have a default to avoid it being always emitted in the generated XML.

> To be clear.... I haven't actually written either of the annotations I have in mind yet, I just had an idea in mind how to do it. So we wouldn't be breaking anything by changing the behavior.

**Comment by djencks** [comment]
-- schema: I guess you think that someone involved has a conceptual schema in their head, although no one has any intention of writing it down or referring to it?  I still don't know what schema you might be thinking of.
-- defaults: in my recollection of my experience, annotations don't work that way.  If you don't specify a default in the annotation definition, I think the annotation use does not compile unless it specifies a value for that element.  So my suggestion is that all annotation elements always be emitted into the generated xml, using either the default or explicitly specified value.

**Comment by bjhargrave** [comment]
> -- schema: I guess you think that someone involved has a conceptual schema in their head, although no one has any intention of writing it down or referring to it? I still don't know what schema you might be thinking of.

There may be a real schema. Obviously there is an xmlns and a prefix. So while there may not be a formal schema XSD file, there certainly is a virtual schema since there are defined attribute names and acceptable attribute values.

> -- defaults: in my recollection of my experience, annotations don't work that way. If you don't specify a default in the annotation definition, I think the annotation use does not compile unless it specifies a value for that element. So my suggestion is that all annotation elements always be emitted into the generated xml, using either the default or explicitly specified value.

If the annotation element does not have a default and it is not specified in the source, then how can you emit it into the XML since you do not know what value to emit (since you do not know the XML schema)?

**Comment by djencks** [comment]
Does this compile for you? It does not for me.  I think it is the situation you are asking about.  An annotation element cannot be null,  it has to have a default or be explicitly specified.
    @Target(ElementType.TYPE)
    public @interface Foo {
        String bar();
    }
    
    @Foo
    public class Baz {}

**Comment by bjhargrave** [comment]
Yes, you are correct. I keep forgetting that about annotation usage. So you can just always emit the attribute since you must either have a specified value or a default value.

**Comment by djencks** [comment]
see #959

**Comment by rotty3000** [comment]
Thanks David! I'll try to test before next week.

**Comment by djencks** [comment]
merged, closing.
