### ISSUE TITLE
Allow generation of multiple manifest headers from a single annotation

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#961]
Currently you can only annotate a type once with a given annotation. This makes it impossible to generate multiple Require-Capability headers from a single annotation. We might want to look at solving this.

I think Java 8 already supports multiple annotations per target?

**Comment by bjhargrave** [comment]
OSGi's design for bundle annotations will support Repeatable annotations. See <https://github.com/osgi/design/tree/master/rfcs/rfc0220>.
