### ISSUE TITLE
DS @Reference cardinality should set resolution: and cardinality: directives on generated requirements

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#972]
When we generate a requirement in the `osgi.service` namespace from a DS Reference, we should set the `resolution:` and `cardinality:` directives correctly depending on the cardinality of the reference. For example if the cardinality is `0..n` then we should set `resolution:=optional` and `cardinality:=multiple`.

**Comment by bjhargrave** [comment]
@djencks Can you look into this?

**Comment by djencks** [comment]
I wrote something, see pull request.  Are the defaults required and single respectively so those don't need the directives, or should those be emitted as well?  Should the values be in quotes, like
{code}
resolution:="optional"
{code}
should there be a constant for "cardinality:"?

**Comment by bjhargrave** [comment]
I made comments on #973.

**Comment by bjhargrave** [comment]
@njbartlett closed this with #974.
