### ISSUE TITLE
Default values of annotation attributes not included for customized webresource annotations

### ISSUE THREAD

**Issue by tverbele** [bndtools/bnd#976]
When I add a customized webresource annotation to a type definition, the default attributes are not included in the Require-Capability header.

For example with the Jsonrpc webresource annotation this leads to the following Require-Capability in the manifest: `osgi.enroute.webresource;filter:="(&(osgi.enroute.webresource=/osgi/enroute/jsonrpc)(&(version>=1.1.1)(!(version>=2.0.0))))"`. Only when I explicitly add `resource={"jsonrpc.js"}` this is reflected in the manifest: `osgi.enroute.webresource;resource:List<String>="jsonrpc.js";filter:="(&(osgi.enroute.webresource=/osgi/enroute/jsonrpc)(&(version>=1.1.1)(!(version>=2.0.0))))"`, although jsonrpc.js is set as default for the resource attribute.

**Comment by pkriens** [comment]
Fixed by #1244
