### ISSUE TITLE
Private-Package is unexpectedly exported

### ISSUE THREAD

**Issue by codetackler** [bndtools/bnd#985]
I'm resubmitting this issue because I forgot to properly format it on the earlier submission.

This problem may be a newbie misunderstanding but here it goes anyway.

Is there a reason why a package specified as a Private-Package gets listed in the manifest exports? In this case, I have a test.object.concrete package that is set as a Private-Package in the pom.xml but it still gets exported. My assumption would be that packages listed in the Private-Package list would not get exported but this obviously isn't the case. Note that I don't have any other exported packages so this is not a case where a test.object.* package is already exported. I'm I missing something or is this a bug?

Here is the generated MANIFEST.MF file:
```
    Build-Jdk: 1.7.0_75
    Built-By: john
    Bundle-ManifestVersion: 2
    Bundle-Name: test.object
    Bundle-SymbolicName: codetackler.test.object
    Bundle-Version: 1.0.0
    Created-By: Apache Maven Bundle Plugin
    Export-Package: test.object.concrete;version="1.0.0";uses:="test.api"
    Import-Package: test.api;version="[1.0,2)"
    Provide-Capability: osgi.service;effective:=active;objectClass="test.api
    .TestObject"
    Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
    Service-Component: OSGI-INF/component.xml
    Tool: Bnd-2.4.1.201501161923
```

Here is the maven-bundle-plugin section from the pom.xml file:
```
    <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>2.5.4</version>
        <extensions>true</extensions>
        <configuration>
            <instructions>
                <Import-Package>test.api</Import-Package>
                <Private-Package>test.object.concrete</Private-Package>
                <Service-Component>OSGI-INF/component.xml</Service-Component>
            </instructions>
        </configuration>
    </plugin>
```

Note that if I change the package name to test.object.internal or test.object.impl, the package does NOT get exported(regardless of whether it is listed as a Private-Package or not).
```
	Manifest-Version: 1.0
	Bnd-LastModified: 1434827294501
	Build-Jdk: 1.7.0_75
	Built-By: john
	Bundle-ManifestVersion: 2
	Bundle-Name: test.object
	Bundle-SymbolicName: codetackler.test.object
	Bundle-Version: 1.0.0
	Created-By: Apache Maven Bundle Plugin
	Import-Package: test.api;version="[1.0,2)"
	Provide-Capability: osgi.service;effective:=active;objectClass="test.api
	.TestObject"
	Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
	Service-Component: OSGI-INF/component.xml
	Tool: Bnd-2.4.1.201501161923
```
```	
    <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>2.5.4</version>
        <extensions>true</extensions>
        <configuration>
            <instructions>
                <Import-Package>test.api</Import-Package>
                <Private-Package>test.object.internal</Private-Package>
                <Service-Component>OSGI-INF/component.xml</Service-Component>
            </instructions>
        </configuration>
    </plugin>
```

Also I've found that I can force the test.object.concrete package to NOT get exported by listing it as a NOTed entry in the Export-Package list.
```
    <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>2.5.4</version>
        <extensions>true</extensions>
        <configuration>
            <instructions>
                <Import-Package>test.api</Import-Package>
                <Export-Package>!test.object.concrete</Export-Package>
                <Private-Package>test.object.concrete</Private-Package>
                <Service-Component>OSGI-INF/component.xml</Service-Component>
            </instructions>
        </configuration>
    </plugin>
```
Shouldn't a package listed in the Private-Package list get NOTed out of the exported packages automatically?

**Comment by bjhargrave** [comment]
From the [maven-bundle-plugin docs][1]:

Under Default Behavior:

    <Export-Package> is now assumed to be the set of packages in your local Java sources, excluding
    the default package '.' and any packages containing 'impl' or 'internal'. (before version 2 of the 
    bundle plugin it was based on the symbolic name)

and under Instructions:

    <Private-Package>
    
    The <Private-Package> instruction is similar in every way to the <Export-Package> instruction,
    except for the fact that these packages will not be exported by the bundle. If a package is 
    selected by both the export and private package headers, then the export takes precedence.

So your package is included in export by default by the maven-bundle-plugin. If you do not want to export it, you will need to add it with a negation (“!test.object.concrete”) in the Export-Package instruction.

Note: this is not standard bnd behavior. It is behavior of maven-bundle-plugin.

[1]: http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html

**Comment by codetackler** [comment]
I don't see the point of having a Private-Package specification if all packages are exported by default and a private package requires a negation entry in the Export-Package list to not get exported.  Why doesn't the Private-Package imply an export negation?  Doesn't make sense to me.  Also the internal/impl special package naming is a bit of a kludge. IMO a build tool shouldn't require specific package naming.  I can see why this is not standard behavior for bnd.  Thanks for you insight. Perhaps I'll enter an enhancement request on the maven-bundle-plugin. Blah.
