### ISSUE TITLE
`permissions` macro should also generate the `org.osgi.framework.BundlePermission`

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#988]

**Comment by bjhargrave** [comment]
Why? Just write the permission in the permissions.perm file. You can reference the Bundle-SymbolicName in the permission, no?

**Comment by bjhargrave** [comment]
Also, BundlePermission deals with hosts/fragments and Require-Bundle which are OSGi features bnd does not really have any support for.

**Comment by pkriens** [comment]
Are you going to create a PR for this?

**Comment by rotty3000** [comment]
I need a reproducible failure test case first. I'll do this next week.

**Comment by bjhargrave** [comment]
Can we close this, @rotty3000?
