### ISSUE TITLE
Support release workspace  to Maven local repository

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#997]
Make it possible to release a workspace and/or project and/or bundle to the local maven repository

**Comment by paulvi** [comment]
:+1: 

Is deploying to remote maven repo, like Sonatype Nexus already supported?

**Comment by pkriens** [comment]
It works for me :-) 

The current build contains the Maven Bnd Repository which supports the ~/.m2/repository and Nexus, including Maven Central. Some work left for documenting it and testing it, it is alpha state now. So keep watching this space.

Kind regards,

	Peter Kriens

**Comment by bjhargrave** [comment]
Fixed by @pkriens in 3.2.

**Comment by eximius313** [comment]
@bjhargrave @pkriens - where I can find documentation explaining how I can release my bundles to Maven local repository and remote Nexus?

**Comment by eximius313** [comment]
Ok, missing ingredient was to add:
```
-releaserepo: Maven Local
```
this was not mentioned in: https://bnd.bndtools.org/plugins/maven.html

**Comment by pkriens** [comment]
I am confused because on the mail you were using the pure gradle plugin but this is only for the workspace?
To release to nexus from the Workspace model, this is useful: https://v2archive.enroute.osgi.org/appnotes/nexus.html

You can also set `-buildrepo 'Maven Local'`. This will put a copy of the build in your Maven Local repo every time you save.

**Comment by eximius313** [comment]
@pkriens - I'm trying to migrate pure Gradle to `bndtools workspace`, but the need to use three separate documentations (each of them contains part of the information):
* https://v2archive.enroute.osgi.org
* https://bnd.bndtools.org/
* and https://bndtools.org

makes learning curve reeeeally steep ;)

**Comment by pkriens** [comment]
Yes, we know it is a mess. However, the amount of variations people want is staggering this is mostly volunteer work. So help us out ... 
That said, I am unclear where you want to go to? If you want to go to the workspace, then your gradle files are mostly empty except gradle.settings? Things then work out of the box, no need to touch gradle in any way?

**Comment by eximius313** [comment]
1. I'm already trying to help ;) 
I could write a document on how to migrate from Gradle approach to `bndtools workspace`.

2. Almost
* Yes, now my gradle files are empty besides `gradle.settings`
* I already know how to replace:
```
dependencies {
  compileOnly group: 'xxx', name: 'yy', version: 'zzz'
}
```
with https://groups.google.com/forum/#!topic/bndtools-users/W8XfUVCbR_E
* I already know how to replace:
```
    apply plugin: 'maven-publish'
    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
        repositories {
            mavenLocal()
        }
    }
```
and `publishToMaven` with https://v2archive.enroute.osgi.org/appnotes/nexus.html
* The last thing I don't know (for now) is how to replace:
```
allprojects {
  group = 'com.example'
}
```
because bnd publishes all bundles using their project name as group and artifactId, while it should use the name only for artifactId, but let the groupId to be configured (I'm sure there is a way, but I didn't found it so far)

**Comment by pkriens** [comment]
See https://bnd.bndtools.org/instructions/pom.html 

The -group can set a default group id but the -pom instruction is better. Look at the bnd build.bnd file, there we're doing a similar thing.

**Comment by eximius313** [comment]
Thanks, I already found that ;)
