### ISSUE TITLE
repoindex does not check validity of attribute names

### ISSUE THREAD

**Issue by db82407** [bndtools/bnd#998]
I accidentally created a bundle with a bad Provide-Capability header:

    Provide-Capability: com.example.transport;com.example.transport=jms;jms-version<Version>="1.1"

repoindex should have complained about the illegal '<' character before Version, but it just generated an index containing:

    <capability namespace="com.example.transport">
      <attribute name="com.example.transport" value="jms"/>
      <attribute name="jms-version&lt;Version&gt;" value="1.1"/>
    </capability>

**Comment by pkriens** [comment]
bnd is already taking care that this error cannot happen for bnd manifest. Since we don't have a lot of time, we decided not to add validation this it is a major work to do it properly
