### ISSUE TITLE
Add information about compatibility with maven-scr-plugin

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#999]
The information whether the maven-scr-plugin is compatible should be added to the readme.md.
Currently a lot of projects are still relying on maven-scr-plugin annotations rather than on the annotations defined by bnd. So if a project wants to migrate from maven-bundle-plugin to bnd-maven-plugin it probably needs to take care of migrating to other annotations as well.

**Comment by rotty3000** [comment]
The bnd DS annotations are deprecated since the addition and support of the standardized OSGi DS annotations. Wouldn't the DS spec cover how to use those annotations already?

**Comment by kwin** [comment]
Yes, that is fine (maybe a link to the spec could be added, however). But my point was, that it should be explicitly mentioned that the maven-scr-plugin is not compatible, so bnd-maven-plugin cannot be used just as a drop-in replacement for the maven-bundle-plugin. Maybe it would be good to explicitly list what has to be considered for migrating from maven-bundle-plugin/maven-scr-plugin to bnd-maven-plugin. Probably such a list should also contain the information that currently the bnd-directives need to be put separately (and they cannot live in the pom.xml, compare with https://github.com/bndtools/bnd/issues/952)

**Comment by bjhargrave** [comment]
I think the [maven-scr-plugin](http://felix.apache.org/documentation/subprojects/apache-felix-maven-scr-plugin.html) is for the [Felix SCR annotations](http://felix.apache.org/documentation/subprojects/apache-felix-maven-scr-plugin/scr-annotations.html). Not the bnd or DS spec annotations.

> bnd-maven-plugin cannot be used just as a drop-in replacement for the maven-bundle-plugin

This is true regardless of DS annotations. The bnd-maven-plugin uses bnd files for bnd configuration rather then pom configurations.

> Maybe it would be good to explicitly list what has to be considered for migrating from maven-bundle-plugin/maven-scr-plugin to bnd-maven-plugin

If you want to work on this, please do submit a pull request. See [CONTRIBUTING](https://github.com/bndtools/bnd/blob/master/CONTRIBUTING.md).

**Comment by kwin** [comment]
> I think the maven-scr-plugin is for the Felix SCR annotations. Not the bnd or DS spec annotations.

The maven-scr-plugin also supports DS spec annotations now (http://felix.apache.org/documentation/subprojects/apache-felix-maven-scr-plugin/apache-felix-maven-scr-plugin-use.html)

> This is true regardless of DS annotations. The bnd-maven-plugin uses bnd files for bnd configuration rather then pom configurations.

This may change in the future if I understand Peter Kriens' comment in https://github.com/bndtools/bnd/issues/952.

I will try to come up with a PR briefly listing the differences to the maven-felix-plugin.

**Comment by bjhargrave** [comment]
> The maven-scr-plugin also supports DS spec annotations now (http://felix.apache.org/documentation/subprojects/apache-felix-maven-scr-plugin/apache-felix-maven-scr-plugin-use.html)

I guess there are technically two different plugins, but you don't need to the use felix plugin for DS spec annotations since bnd already supports that and bnd is the engine on both the maven-bundle-plugin and the bnd-maven-plugin.

> This may change in the future if I understand Peter Kriens' comment in #952.

Well, someone will need to make a pull request. :-)

> I will try to come up with a PR briefly listing the differences to the maven-felix-plugin.

Thanks!

**Comment by pkriens** [comment]
Awaiting pull request ...
